### ISSUE TITLE
Taro 3 默认模板(JavaScript) 打包各个小程序失败

### ISSUE THREAD

**Issue by Zevin888** [NervJS/taro#10087]
### 相关平台
微信小程序

**小程序基础库: 2.17.3**
**使用框架: React**

### 复现步骤
npm run build:weapp

### 期望结果
打包成功

### 实际结果
缺少 app 全局配置文件，请检查！

(node:16192) UnhandledPromiseRejectionWarning: Error: 缺少 app 全局配置文件，请检查！
    at TaroMiniPlugin.getAppConfig (E:\Project\VSCode\React.js\test\node_modules\_@tarojs_mini-runner@3.3.3@@tarojs\mini-runner\src\plugins\MiniPlugin.ts:518:13)
    at TaroMiniPlugin.run (E:\Project\VSCode\React.js\test\node_modules\_@tarojs_mini-runner@3.3.3@@tarojs\mini-runner\src\plugins\MiniPlugin.ts:389:29)
    at TaroMiniPlugin.<anonymous> (E:\Project\VSCode\React.js\test\node_modules\_@tarojs_mini-runner@3.3.3@@tarojs\mini-runner\src\plugins\MiniPlugin.ts:187:20)
    at Generator.next (<anonymous>)
    at E:\Project\VSCode\React.js\test\node_modules\_@tarojs_mini-runner@3.3.3@@tarojs\mini-runner\dist\plugins\MiniPlugin.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\Project\VSCode\React.js\test\node_modules\_@tarojs_mini-runner@3.3.3@@tarojs\mini-runner\dist\plugins\MiniPlugin.js:4:12)
    at E:\Project\VSCode\React.js\test\node_modules\_@tarojs_mini-runner@3.3.3@@tarojs\mini-runner\src\plugins\MiniPlugin.ts:186:58
    at TaroMiniPlugin.<anonymous> (E:\Project\VSCode\React.js\test\node_modules\_@tarojs_mini-runner@3.3.3@@tarojs\mini-runner\src\plugins\MiniPlugin.ts:162:13)
    at Generator.next (<anonymous>)
    at E:\Project\VSCode\React.js\test\node_modules\_@tarojs_mini-runner@3.3.3@@tarojs\mini-runner\dist\plugins\MiniPlugin.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\Project\VSCode\React.js\test\node_modules\_@tarojs_mini-runner@3.3.3@@tarojs\mini-runner\dist\plugins\MiniPlugin.js:4:12)
    at E:\Project\VSCode\React.js\test\node_modules\_@tarojs_mini-runner@3.3.3@@tarojs\mini-runner\src\plugins\MiniPlugin.ts:160:44
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\Project\VSCode\React.js\test\node_modules\_tapable@1.1.3@tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (E:\Project\VSCode\React.js\test\node_modules\_tapable@1.1.3@tapable\lib\Hook.js:154:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing 
inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To 
terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:16192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### 环境信息
```
Taro CLI 3.3.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\User\AppData\Roaming\npm\yarn.CMD
      npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
在安装依赖时存在多个包因平台原因安装不了

**Comment by Chen-jj** [comment]
没有复现，升级到最新版再试试
