### ISSUE TITLE
小程序插件代码转换成Taro代码报错

### ISSUE THREAD

**Issue by ltp11** [NervJS/taro#1025]
**问题描述**
小程序插件代码转换成Taro代码报错

**复现步骤**
[复现问题的步骤]
1.  在小程序代码目录执行taro convert
2. Error: 组件 /Users/liangtianpei/Desktop/aotu/wx_login_plugin/plugin:/loginPlugin/index 没有 JS 文件！

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
import { Block, Button } from '@tarojs/components'
import Taro from '@tarojs/taro'
import withWeapp from '@tarojs/with-weapp'
import util from '../../../public/loginUtil.js'
import Instruction from '../../../plugin:/loginPlugin/instruction'
import Index from '../../../plugin:/loginPlugin/index'
import './index.css'
let plugin = requirePlugin('loginPlugin')
let config = util.getLoginConfig()
```

**期望行为**
插件应该写在配置文件app.json中

**报错信息**

错误  组件转换  plugin:/loginPlugin/index.js
Error: 组件 /Users/liangtianpei/Desktop/aotu/wx_login_plugin/plugin:/loginPlugin/index 没有 JS 文件！
    at components.forEach.componentObj (/Users/liangtianpei/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/src/convertor.js:393:17)
    at Set.forEach (<anonymous>)
    at Convertor.traverseComponents (/Users/liangtianpei/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/src/convertor.js:379:16)
    at pages.forEach.page (/Users/liangtianpei/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/src/convertor.js:367:14)
    at Set.forEach (<anonymous>)
    at Convertor.traversePages (/Users/liangtianpei/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/src/convertor.js:300:16)
    at Convertor.run (/Users/liangtianpei/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/src/convertor.js:522:10)
    at Object.<anonymous> (/Users/liangtianpei/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/bin/taro-convert:12:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
错误  组件转换  plugin:/loginPlugin/instruction.js
Error: 组件 /Users/liangtianpei/Desktop/aotu/wx_login_plugin/plugin:/loginPlugin/instruction 没有 JS 文件！
    at components.forEach.componentObj (/Users/liangtianpei/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/src/convertor.js:393:17)
    at Set.forEach (<anonymous>)
    at Convertor.traverseComponents (/Users/liangtianpei/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/src/convertor.js:379:16)
    at pages.forEach.page (/Users/liangtianpei/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/src/convertor.js:367:14)
    at Set.forEach (<anonymous>)
    at Convertor.traversePages (/Users/liangtianpei/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/src/convertor.js:300:16)
    at Convertor.run (/Users/liangtianpei/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/src/convertor.js:522:10)
    at Object.<anonymous> (/Users/liangtianpei/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/bin/taro-convert:12:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)

**系统信息**

 - 操作系统: [e.g. Mac os 10.13.4]
 - Taro 版本 [e.g. v1.2.0-alpha.3]
 - Node.js 版本 [e.g. v8.11.1]
 - 报错平台 [weapp]

**Comment by gd-ldj** [comment]
这个还存在的bug，怎么关闭了
