### ISSUE TITLE
scheduler.production.min.js 报错

### ISSUE THREAD

**Issue by neewbee** [NervJS/taro#10458]
### 相关平台
微信小程序

**小程序基础库: 1.4.1**
**使用框架: React**

### 复现步骤
有部分用户会报异常
堆栈信息（去掉了行列号）
`
"|\u0002\u0000\u0000\"MiniProgramError\\nCannot read property 'now' of undefined\\nTypeError: Cannot read property 'now' of undefined\\n    at Object.<anonymous> (https://usr/app-service.js:)\\n    at Object._ (https://usr/app-service.js:)\\n    at l (https://usr/app-service.js:)\\n    at Object._ (https://usr/app-service.js:)\\n    at l (https://usr/app-service.js:)\\n    at Object._ (https://usr/app-service.js:)\\n    at l (https://usr/app-service.js:)\\n    at Module._ (https://usr/app-service.js:25254:14)\\n    at l (https://usr/app-service.js:)\\n    at t (https://usr/app-service.js:)\"\u0000",
  "|\u0002\u0000\u0000\"MiniProgramError\\nCannot read property 'now' of undefined\\nTypeError: Cannot read property 'now' of undefined\\n    at Object.<anonymous> (https://usr/app-service.js:)\\n    at Object._ (https://usr/app-service.js:)\\n    at l (https://usr/app-service.js:\\n    at Object._ (https://usr/app-service.js:)\\n    at l (https://usr/app-service.js:10312:91)\\n    at Object._ (https://usr/app-service.js:)\\n    at l (https://usr/app-service.js:)\\n    at Module._ (https://usr/app-service.js:)\\n    at l (https://usr/app-service.js:)\\n    at t (https://usr/app-service.js:)\"\u0000"
`
定位了下代码

![截屏2021-10-19 16 33 46](https://user-images.githubusercontent.com/13777940/137874143-ce468355-0ba3-4502-af45-e19539f12564.png)

__Date.now 这里报错了

<img width="707" alt="截屏2021-10-19 16 38 03" src="https://user-images.githubusercontent.com/13777940/137874370-1356ebe0-cf41-41ae-8850-3e8e771f8dce.png">

之前有个 issue https://github.com/NervJS/taro/issues/8327 提到了这个问题，我不太确定是不是同一个原因，应为只有一部分用户有报错。

### 期望结果
不报错

### 实际结果
报错

### 环境信息
```
👽 Taro v3.0.21

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating

  Taro CLI 3.0.21 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v12.18.2/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.21 => 3.0.21
      @tarojs/components: 3.0.21 => 3.0.21
      @tarojs/mini-runner: 3.0.21 => 3.0.21
      @tarojs/react: 3.0.21 => 3.0.21
      @tarojs/runtime: 3.0.21 => 3.0.21
      @tarojs/service: ^3.0.21 => 3.0.21
      @tarojs/taro: 3.0.21 => 3.0.21
      @tarojs/webpack-runner: 3.0.21 => 3.0.21
      babel-preset-taro: 3.0.21 => 3.0.21
      eslint-config-taro: 3.0.21 => 3.0.21
      react: ^16.10.0 => 16.14.0

```

**Comment by neewbee** [comment]
好嘞！
