### ISSUE TITLE
TypeScript 模式下 leancloud-storage 编译失败

### ISSUE THREAD

**Issue by cheese-git** [NervJS/taro#1053]
**问题描述**

TypeScript 模式下 leancloud-storage SDK 编译失败

**复现步骤**

1. 使用 taro-cli 初始化一个使用 typescript, redux 的新项目
2. `yarn add leancloud-storage`

```ts
// 改成 import * as AV from "leancloud-storage" 结果是一样的
import { Query } from "leancloud-storage"

// ...

const query = new Query('Todo')
this.setState({
  todos: await query.find()
})
```

**期望行为**

能够正常使用 leancloud-sdk

**报错信息**

```js
thirdScriptError 
 sdk uncaught third Error 
 module "npm/uuid/lib/crypto" is not defined 
 Error: module "npm/uuid/lib/crypto" is not defined
    at require (http://127.0.0.1:51184/appservice/__dev__/WAService.js:1:716241)
    at http://127.0.0.1:51184/appservice/__dev__/WAService.js:1:715991
    at http://127.0.0.1:51184/appservice/npm/uuid/lib/rng.js:4:14
    at require (http://127.0.0.1:51184/appservice/__dev__/WAService.js:1:716382)
    at http://127.0.0.1:51184/appservice/__dev__/WAService.js:1:715991
    at http://127.0.0.1:51184/appservice/npm/uuid/v4.js:1:446
    at require (http://127.0.0.1:51184/appservice/__dev__/WAService.js:1:716382)
    at http://127.0.0.1:51184/appservice/__dev__/WAService.js:1:715991
    at http://127.0.0.1:51184/appservice/npm/leancloud-storage/dist/node/av.js:4:12
    at require (http://127.0.0.1:51184/appservice/__dev__/WAService.js:1:716382)
```

**系统信息**

 - Windows 10
 - Taro 版本  v.1.1.1
 - Node.js 版本 v8.11.4
 - 报错平台 weapp

**Comment by luckyadam** [comment]
import { Query } from 'leancloud-storage/dist/av-weapp.js'

**Comment by cheese-git** [comment]
> import { Query } from 'leancloud-storage/dist/av-weapp.js'

目前就是这样解决的，但是一来麻烦，二来没有代码提示

**Comment by luckyadam** [comment]
就是应该这样，leancloud-storage 默认导出的文件是不能直接在小程序内使用的
