### ISSUE TITLE
taro2.x版本重新安装依赖后build:weapp失败

### ISSUE THREAD

**Issue by NeroWzl** [NervJS/taro#10763]
### 相关平台
微信小程序

**小程序基础库: 2.16.1**
**使用框架: React**

### 复现步骤
创建一个taro2.x版本的项目或一个已有项目删除node_modules文件夹后，重新cnpm安装依赖，此后运行build:weapp命令编译打包小程序。使用yarn安装依赖目前没有问题，问题只出在cnpm安装依赖上。我目前是2.2.13版本，但是我试了2.2.18也是一样结果

### 期望结果
正常打包出小程序

### 实际结果
编译过程中抛出错误无法完成编译

### 环境信息
```
Taro CLI 2.2.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 7.20.0 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
抛出错误如下：
(node:1176) UnhandledPromiseRejectionWarning: TypeError: item.node is not a function
    at C:\Users\nerowu\Desktop\work\jinma\node_modules\_webpack-sources@1.4.3@webpack-sources\lib\ConcatSource.js:59:50
    at Array.map (<anonymous>)
    at ConcatSource.node (C:\Users\nerowu\Desktop\work\jinma\node_modules\_webpack-sources@1.4.3@webpack-sources\lib\ConcatSource.js:58:63)
    at ConcatSource.proto.sourceAndMap (C:\Users\nerowu\Desktop\work\jinma\node_modules\_webpack-sources@1.4.3@webpack-sources\lib\SourceAndMapMixin.js:29:18)
    at CachedSource.sourceAndMap (C:\Users\nerowu\Desktop\work\jinma\node_modules\_webpack-sources@1.4.3@webpack-sources\lib\CachedSource.js:58:31)
    at TerserPlugin.taskGenerator (C:\Users\nerowu\Desktop\work\jinma\node_modules\_terser-webpack-plugin@3.0.2@terser-webpack-plugin\dist\index.js:178:23)
    at taskGenerator.next (<anonymous>)
    at C:\Users\nerowu\Desktop\work\jinma\node_modules\_terser-webpack-plugin@3.0.2@terser-webpack-plugin\dist\index.js:417:54
    at C:\Users\nerowu\Desktop\work\jinma\node_modules\_p-try@2.2.0@p-try\index.js:4:10
    at new Promise (<anonymous>)
    at pTry (C:\Users\nerowu\Desktop\work\jinma\node_modules\_p-try@2.2.0@p-try\index.js:3:37)
    at run (C:\Users\nerowu\Desktop\work\jinma\node_modules\_p-limit@2.3.0@p-limit\index.js:23:18)
    at enqueue (C:\Users\nerowu\Desktop\work\jinma\node_modules\_p-limit@2.3.0@p-limit\index.js:32:4)
    at C:\Users\nerowu\Desktop\work\jinma\node_modules\_p-limit@2.3.0@p-limit\index.js:38:60
    at new Promise (<anonymous>)
    at generator (C:\Users\nerowu\Desktop\work\jinma\node_modules\_p-limit@2.3.0@p-limit\index.js:38:37)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with
To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1176) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by z1098481875** [comment]
楼主解决了吗？我也遇到同样的问题了～ @NeroWzl

**Comment by MrChen2016-08-27** [comment]
我记得之前看过Taro2.x 的另一个压缩插件也会报错的issues，这两个原因都一样，好像是webpack版本的原因。
所以两者解决方法应该也一样，你可以尝试:

1. 删除该项目下的node_modles, 在该项目下执行以下命令
2. 执行 `npm install webpack@4.44.2 -g`
3.  执行`npm install webpack@4.44.2 --save`
4. 再执行`npm install` 安装完整
(以上命令如果在国内网速不佳， 以上npm 可以替换为 cnpm)
安装完成后，最后执行` npm run build:weapp `
