### ISSUE TITLE
taro 3.3.7 新建 vue3.0 项目 打包支付宝报错 

### ISSUE THREAD

**Issue by jiezai0920** [NervJS/taro#11133]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/jiezai0920/taro-test](https://github.com/jiezai0920/taro-test)
**小程序基础库: 2.0**
**使用框架: Vue 3**

### 复现步骤
在项目根目录中运行yarn build:alipay，将打包好的dis文件在支付宝开发者工具中打开

### 期望结果
支付宝小程序可以正常运行

### 实际结果
报错
myApp1/dist/vendors.js: Unexpected token (2207:136)
Please set enableNodeModuleBabelTransform to true or add "myApp1/dist/vendors.js" to node_modules_es6_whitelist in mini.project.json for node_modules babel transform

### 环境信息
```
Taro v3.3.3


  Taro CLI 3.3.3 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 7.18.1 - ~/.nvm/versions/node/v16.4.0/bin/npm
    npmPackages:
      @tarojs/components: 3.3.3 => 3.3.3
      @tarojs/mini-runner: 3.3.3 => 3.3.3
      @tarojs/runtime: 3.3.3 => 3.3.3
      @tarojs/taro: 3.3.3 => 3.3.3
      @tarojs/webpack-runner: 3.3.3 => 3.3.3
      babel-preset-taro: 3.3.3 => 3.3.3
      eslint-config-taro: 3.3.3 => 3.3.3
```

**Comment by Chen-jj** [comment]
升级最新版再试试

**Comment by jsjzh** [comment]
同样的问题，也是 vue3.x，taro 已经全部升级到最新版本 3.4.0，node v14

并且发现，上传 alipay 时，preview 不会报错，upload 会报错，问了 alipay 的人说是 upload 开启了代码压缩，preview 没有，是压缩代码导致的报错信息，我已经到 alipay 那边要来了具体报错内容，如下所示

```
03:06:23.567 - Failed to compile

03:06:23.568 - 压缩代码时报错，请检查node_modules中是否使用了ES6语法, ES6代码会导致 iOS9/iOS10 运行时白屏

出错位置: /tmp/data/onetime_tmp_dir/951a8397-4536-4ae4-84c7-8173659c66d3-1642561571311/tiny-Gyfxe1Ouo-1642561571335/main/index.worker.js:647:67687
错误信息: index.worker.js from UglifyJs
Unexpected token: name «property», expected: punc «,» [./vendors.js:1,2][index.worker.js:647,67687]
```

**Comment by Chen-jj** [comment]
@jiezai0920 楼主的代码我用 Taro 3.4 测试没有发现有报错额：

![image](https://user-images.githubusercontent.com/11807297/150670179-b7169ac2-c546-48e4-a283-760ec6dd7b67.png)

**Comment by Chen-jj** [comment]
@jsjzh 

1.  如果有和楼主一样的问题，可以提供一下 Demo？这边没有复现
2. 上传了个简单 Demo 进行测试也没有复现。看报错是说 vendor.js 有 ES6 语法的样子，可以先检查一下。Webpack splitchunks 配置了 vendor.js 是 node_modules 依赖，可能是某些依赖带有 ES6 语法，如果是这个问题，可以配置 babel-loader 去编译这些依赖。

**Comment by Chen-jj** [comment]
#11142

**Comment by MarshallYang** [comment]
@Chen-jj 还是不可以，新建的项目， vue3 + typescript + sass + 默认模版
![image](https://user-images.githubusercontent.com/13745468/154428331-ba8646dc-d15b-4040-ba16-01a9e607e1f9.png)
执行 yarn build:alipay， 支付宝运行
![image](https://user-images.githubusercontent.com/13745468/154428646-92d3cc88-fdb0-4e21-a6ca-c46aa6730571.png)
仍然提示 vendor.js 里面有问题。
支付宝小程序开发者工具版本：版本2.7.2 (2.7.2)

**Comment by loong917** [comment]
也遇到这样的问题，选择vue3模板，dev正常，build报错

**Comment by sjx1995** [comment]
同样的错误
taro3.4.3，钉钉小程序，vue3模板，dev正常，build报错

**Comment by emaoxiongzhang** [comment]
> 同样的错误 taro3.4.3，钉钉小程序，vue3模板，dev正常，build报错

我在build命令 后面增加了 --watch解决了

**Comment by emaoxiongzhang** [comment]
> 也遇到这样的问题，选择vue3模板，dev正常，build报错


我在build命令 后面增加了 --watch解决了

**Comment by emaoxiongzhang** [comment]
> @Chen-jj 还是不可以，新建的项目， vue3 + typescript + sass + 默认模版 ![image](https://user-images.githubusercontent.com/13745468/154428331-ba8646dc-d15b-4040-ba16-01a9e607e1f9.png) 执行 yarn build:alipay， 支付宝运行 ![image](https://user-images.githubusercontent.com/13745468/154428646-92d3cc88-fdb0-4e21-a6ca-c46aa6730571.png) 仍然提示 vendor.js 里面有问题。 支付宝小程序开发者工具版本：版本2.7.2 (2.7.2)


我在build命令 后面增加了 --watch解决了`"build:dd": "taro build --type dd --watch",`

**Comment by emaoxiongzhang** [comment]
> ### 相关平台
> 支付宝小程序
> 
> ### 复现仓库
> https://github.com/jiezai0920/taro-test **小程序基础库: 2.0** **使用框架: Vue 3**
> 
> ### 复现步骤
> 在项目根目录中运行yarn build:alipay，将打包好的dis文件在支付宝开发者工具中打开
> 
> ### 期望结果
> 支付宝小程序可以正常运行
> 
> ### 实际结果
> 报错 myApp1/dist/vendors.js: Unexpected token (2207:136) Please set enableNodeModuleBabelTransform to true or add "myApp1/dist/vendors.js" to node_modules_es6_whitelist in mini.project.json for node_modules babel transform
> 
> ### 环境信息
> ```
> Taro v3.3.3
> 
> 
>   Taro CLI 3.3.3 environment info:
>     System:
>       OS: macOS 10.15.5
>       Shell: 5.7.1 - /bin/zsh
>     Binaries:
>       Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
>       Yarn: 1.22.4 - ~/.yarn/bin/yarn
>       npm: 7.18.1 - ~/.nvm/versions/node/v16.4.0/bin/npm
>     npmPackages:
>       @tarojs/components: 3.3.3 => 3.3.3
>       @tarojs/mini-runner: 3.3.3 => 3.3.3
>       @tarojs/runtime: 3.3.3 => 3.3.3
>       @tarojs/taro: 3.3.3 => 3.3.3
>       @tarojs/webpack-runner: 3.3.3 => 3.3.3
>       babel-preset-taro: 3.3.3 => 3.3.3
>       eslint-config-taro: 3.3.3 => 3.3.3
> ```

我在build命令 后面增加了 --watch解决了"build:dd": "taro build --type dd --watch",

**Comment by duanxianze** [comment]
这个问题依旧存在啊  3.4.4版本

**Comment by Chen-jj** [comment]
@jiezai0920 @jsjzh @MarshallYang @loong917 @sjx1995 @emaoxiongzhang @sjx1995 @duanxianze 各位提供一下编译信息？

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/11807297/162906507-84d3bedb-a80c-4b57-ad95-e4b33f51661f.png">

尝试过【 Taro `v3.4.4` + Vue3 NutUI 模板 + 支付宝开发者工具 `v2.7.2` 】打包生产模式代码：无论是支付宝还是钉钉模式，开发者工具都能正常编译显示；点击上传也没有报错，可以成功上传。因此还是不确定触发此问题的条件。

翻阅支付宝小程序文档，在[小程序基础库 v2](https://opendocs.alipay.com/mini/framework/lib-upgrade-v2) 中有提到此报错。然而尝试过开启或关闭小程序基础库 2.0 构建，都能正常编译。

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/11807297/162907393-90cbf181-ffba-4d26-b247-90ca3c516714.png">

报错原因应该是我之前提到的，存在 es6 的语法：

> 1. 如果有和楼主一样的问题，可以提供一下 Demo？这边没有复现
> 2. 上传了个简单 Demo 进行测试也没有复现。看报错是说 vendor.js 有 ES6 语法的样子，可以先检查一下。Webpack splitchunks 配置了 vendor.js 是 node_modules 依赖，可能是某些依赖带有 ES6 语法，如果是这个问题，可以配置 babel-loader 去编译这些依赖。

**Comment by duanxianze** [comment]
https://github.com/duanxianze/tarodemo
我的复现仓库  node 14.9  vue3 taro3.4.4

**Comment by duanxianze** [comment]
支付宝小程序开发工具 Version 2.7.2  
我只能想到可能是这里的问题了。。

**Comment by duanxianze** [comment]
我把我运行build生成的dist也传上去了  您可以运行看下

**Comment by sjx1995** [comment]
![image](https://user-images.githubusercontent.com/8850692/163096067-2acc36b1-517b-41b7-9151-bfb74407bac6.png)

@Chen-jj 我编译到钉钉小程序没有【启用小程序基础库2.0构建】的选项，现在使用 `npm run build:dd -- --watch` 编译可以暂时解决问题

**Comment by cys19970903** [comment]
支付宝小程序 config/index.js mini下增加已下配置问题解决  
 webpackChain(chain, webpack) {
      chain.merge({
        module: {
          rule: [
            {
              test: /.js$/,
              loader: "babel-loader",
            },
          ],
        },
      });
    },

**Comment by asvue** [comment]
> 支付宝小程序 config/index.js mini下增加以下配置问题解决
> 
> ```
> webpackChain(chain, webpack) {
>       chain.merge({
>         module: {
>           rule: [
>             {
>               test: /.js$/,
>               loader: "babel-loader",
>             },
>           ],
>         },
>       });
>     },
> ```

这个答案配上 watach 完美解决.谢谢大哥

**Comment by feibi** [comment]
不增加 `babel-loader`，只更换`esbuild`也可以
```ts
{
  jsMinimizer: 'esbuild',
  esbuild: {
    minify: {
      enable: true,
      config: {
        // 配置项同 https://github.com/privatenumber/esbuild-loader#minifyplugin
        target: process.env.TARO_ENV === 'h5' ? 'es5' : 'es2015', // target 默认值为 es5
      },
    },
  },
}
```

**Comment by jerryyan1990** [comment]
> 支付宝小程序 config/index.js mini下增加以下配置问题解决
> 
> ```
> webpackChain(chain, webpack) {
>       chain.merge({
>         module: {
>           rule: [
>             {
>               test: /.js$/,
>               loader: "babel-loader",
>             },
>           ],
>         },
>       });
>     },
> ```

感谢，使用这个方法暂时解决了。打包没问题了。但开发模式，预览和真机调试会出现找不到页面的情况，不知道为什么。支付宝模拟器正常无报错。真机调试有报错。
`index.vue?db4f:9 TypeError: Cannot read property 'indexOf' of undefined
    at ../shared-utils/lib/env.js (index.worker.js:15:295378)
    at r (index.worker.js:15:296263)
    at index.worker.js:15:296774
    at index.worker.js:15:296710
    at ./node_modules/.pnpm/@tarojs+plugin-vue-devtools@3.6.23_@tarojs+runtime@3.6.23_postcss@8.4.31_vue@3.3.8/node_modules/@tarojs/plugin-vue-devtools/dist/backend/build/hook.js (index.worker.js:15:288930)
    at t (index.worker.js:3:79124)
    at ./node_modules/.pnpm/@tarojs+plugin-vue-devtools@3.6.23_@tarojs+runtime@3.6.23_postcss@8.4.31_vue@3.3.8/node_modules/@tarojs/plugin-vue-devtools/dist/backend/index.js (index.worker.js:15:297163)
    at t (index.worker.js:3:79124)
    at ./node_modules/.pnpm/@tarojs+plugin-vue-devtools@3.6.23_@tarojs+runtime@3.6.23_postcss@8.4.31_vue@3.3.8/node_modules/@tarojs/plugin-vue-devtools/dist/runtime.js (index.worker.js:15:301250)
    at t (index.worker.js:3:79124)
    at ./src/app.js (index.worker.js:3:85278)
    at t (index.worker.js:3:79124)
    at n (index.worker.js:3:97493)
    at index.worker.js:3:97555
    at index.worker.js:3:79531
    at index.worker.js:3:97575
    at n (index.worker.js:3:80479)
    at GfhN (index.worker.js:3:81814)
    at t (index.worker.js:3:392)
    at r (index.worker.js:3:13643)
    at h (index.worker.js:13:4)
    at index.worker.js:15:55
    at index.worker.js:3:15427
    at 1Fxu (index.worker.js:3:13105)
    at t (index.worker.js:3:392)
    at 0 (index.worker.js:3:1584)
    at t (index.worker.js:3:392)
    at index.worker.js:3:1185
    at index.worker.js:3:91
h @ index.vue?db4f:9
(anonymous) @ index.vue?db4f:9
(anonymous) @ index.vue?db4f:9
1Fxu @ index.vue?3e67:9
t @ index.vue?3e67:9
0 @ bootstrap:5
t @ rewrite-helper.js:31
(anonymous) @ bootstrap:5
(anonymous) @ index.worker.js:3
index.vue?db4f:9 Error: [🍍]: "getActivePinia()" was called but there was no active Pinia. Are you trying to use a store before calling "app.use(pinia)"?
See https://pinia.vuejs.org/core-concepts/outside-component-usage.html for help.
This will fail in production.
    at s (index.worker.js:15:1258285)
    at ./src/hooks/useNeedLogin.js (index.worker.js:3:145822)
    at t (index.worker.js:3:79124)
    at ./node_modules/.pnpm/unplugin@1.5.1/node_modules/unplugin/dist/webpack/loaders/transform.js?unpluginName=unplugin-auto-import!./node_modules/.pnpm/unplugin@1.5.1/node_modules/unplugin/dist/webpack/loaders/transform.js?unpluginName=unplugin-vue-components!./node_modules/.pnpm/babel-loader@9.1.3_@babel+core@7.23.3_webpack@5.89.0/node_modules/babel-loader/lib/index.js!./node_modules/.pnpm/babel-loader@8.2.1_@babel+core@7.23.3_webpack@5.89.0/node_modules/babel-loader/lib/index.js??clonedRuleSet-12.use[0]!./node_modules/.pnpm/vue-loader@17.3.1_@vue+compiler-sfc@3.3.8_vue@3.3.8_webpack@5.89.0/node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/pages/index/index.vue?vue&type=script&setup=true&lang=js (index.worker.js:3:52223)
    at t (index.worker.js:3:79124)
    at ./src/pages/index/index.vue?vue&type=script&setup=true&lang=js (index.worker.js:3:70452)
    at t (index.worker.js:3:79124)
    at ./node_modules/.pnpm/@tarojs+taro-loader@3.6.23_@tarojs+runtime@3.6.23_postcss@8.4.31_vue@3.3.8/node_modules/@tarojs/taro-loader/lib/raw.js!./node_modules/.pnpm/@tarojs+taro-loader@3.6.23_@tarojs+runtime@3.6.23_postcss@8.4.31_vue@3.3.8/node_modules/@tarojs/taro-loader/lib/entry-cache.js?name=pages/index/index!./src/pages/index/index.vue (index.worker.js:3:38935)
    at t (index.worker.js:3:79124)
    at ./src/pages/index/index.vue (index.worker.js:3:69816)
    at t (index.worker.js:3:79124)
    at n (index.worker.js:3:75827)
    at index.worker.js:3:75889
    at index.worker.js:3:79531
    at index.worker.js:3:75924
    at n (index.worker.js:3:80479)
    at 8x2U (index.worker.js:3:38440)
    at t (index.worker.js:3:392)
    at +3/E (index.worker.js:3:1246)
    at t (index.worker.js:3:392)
    at pages/index/index (index.worker.js:3:14291)
    at h (index.worker.js:13:4)
    at index.worker.js:15:55
    at index.worker.js:3:15427
    at 1Fxu (index.worker.js:3:13105)
    at t (index.worker.js:3:392)
    at 0 (index.worker.js:3:1584)
    at t (index.worker.js:3:392)
    at index.worker.js:3:1185
    at index.worker.js:3:91
h @ index.vue?db4f:9
(anonymous) @ index.vue?db4f:9
(anonymous) @ index.vue?db4f:9
1Fxu @ index.vue?3e67:9
t @ index.vue?3e67:9
0 @ bootstrap:5
t @ rewrite-helper.js:31
(anonymous) @ bootstrap:5
(anonymous) @ index.worker.js:3`
