### ISSUE TITLE
微信小程序反向转换报错Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option

### ISSUE THREAD

**Issue by chenwebber** [NervJS/taro#11173]
### 这个特性解决了什么问题？
微信小程序反向转换为taro, 以便多端开发

### 这个 API 长什么样？
Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean. If you are migrating from Babylon/Babel 6 or want to use the old decorators proposal, you should use the 'decorators-legacy' plugin instead of 'decorators'.
    at validatePlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@babel_parser@7.16.10@@babel/parser/src/plugin-utils.js:87:13)
    at getParser (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@babel_parser@7.16.10@@babel/parser/src/index.js:83:5)
    at parse (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@babel_parser@7.16.10@@babel/parser/src/index.js:58:12)
    at parseWithCodeFrame (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@babel_template@7.16.7@@babel/template/lib/parse.js:175:30)
    at parseAndBuildMetadata (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@babel_template@7.16.7@@babel/template/lib/parse.js:36:15)
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/_@babel_template@7.16.7@@babel/template/lib/string.js:19:50
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/_@babel_template@7.16.7@@babel/template/lib/builder.js:75:14
    at /usr/local/lib/node_modules/@tarojs/cli/src/convertor/index.ts:352:20
    at Set.forEach (<anonymous>)
    at exit (/usr/local/lib/node_modules/@tarojs/cli/src/convertor/index.ts:345:29)
    =============
    at /usr/local/lib/node_modules/@tarojs/cli/src/convertor/index.ts:349:27
    at Set.forEach (<anonymous>)
    at exit (/usr/local/lib/node_modules/@tarojs/cli/src/convertor/index.ts:345:29)
    at NodePath._call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@babel_traverse@7.16.10@@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@babel_traverse@7.16.10@@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@babel_traverse@7.16.10@@babel/traverse/lib/path/context.js:109:8)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@babel_traverse@7.16.10@@babel/traverse/lib/context.js:103:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@babel_traverse@7.16.10@@babel/traverse/lib/context.js:77:19)

**Comment by Chen-jj** [comment]
看看生成的装饰器代码有没错误，没有的话搜索一下此报错

https://www.google.com/search?q=The+%27decorators%27+plugin+requires+a+%27decoratorsBeforeExport%27+option&oq=The+%27decorators%27+plugin+requires+a+%27decoratorsBeforeExport%27+option&aqs=chrome..69i57j69i61.308j0j1&sourceid=chrome&ie=UTF-8

**Comment by chenwebber** [comment]
![image](https://user-images.githubusercontent.com/33859450/151508878-ca7a4868-1b35-4a14-a573-0041c708638e.png)
没有生成代码，页面转换的时候已经报错了

**Comment by yujingwyh** [comment]
+1 同样遇到
目前手动修改了 /opt/homebrew/lib/node_modules/@tarojs/cli/dist/config/babylon.js 文件解决了

['decorators',{
decoratorsBeforeExport:true
}]

**Comment by slogeor** [comment]
> /cli/dist/config/babylon.js

大佬，taro convert 出现的error: slot 的值必须是一个字符串 这个错误遇到过吗

**Comment by yujingwyh** [comment]
没有，已经放弃转换了

**Comment by webpangxing** [comment]
我也遇到这个问题了。。。算了吧，这个转换功能太扯犊子了，内部真的测过吗

**Comment by jackzhujie** [comment]
> +1 同样遇到 目前手动修改了 /opt/homebrew/lib/node_modules/@tarojs/cli/dist/config/babylon.js 文件解决了
> 
> ['decorators',{ decoratorsBeforeExport:true }]

这个插件要放到最前面，放后面还不行，本人亲测有效。改完之后的样子：
`"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const config = {
    sourceType: 'module',
    plugins: [
		['decorators',{
				decoratorsBeforeExport:true
			}],
        'typescript',
        'classProperties',
        'jsx',
        'asyncGenerators',
        'objectRestSpread',
        'decorators',
        'dynamicImport'
    ]
};
exports.default = config;
//# sourceMappingURL=babylon.js.map`

**Comment by gemxx** [comment]
> ['decorators',{ decoratorsBeforeExport:true }]

+1

**Comment by YOHN89** [comment]
一样的问题。 
太扯了，这种bug自己拿一个原生小程序跑一下就能发现的问题。
