### ISSUE TITLE
taro init创建的rn模版项目执行pushy bundle 报错

### ISSUE THREAD

**Issue by YuanQuan** [NervJS/taro#11187]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
taro init 选择rn模版

### 期望结果
可以执行pushy bundle --platform android 命令

### 实际结果
index.js入口文件未找到

### 环境信息
```
Taro CLI 3.4.0 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.0 => 3.4.0 
      @tarojs/components: 3.4.0 => 3.4.0 
      @tarojs/mini-runner: 3.4.0 => 3.4.0 
      @tarojs/react: 3.4.0 => 3.4.0 
      @tarojs/runtime: 3.4.0 => 3.4.0 
      @tarojs/taro: 3.4.0 => 3.4.0 
      @tarojs/webpack-runner: 3.4.0 => 3.4.0 
      babel-preset-taro: 3.4.0 => 3.4.0 
      eslint-config-taro: 3.4.0 => 3.4.0 
      react: ^17.0.2 => 17.0.2 
      react-native: ^0.66.0 => 0.66.4
```

---
### 补充信息
yuanquandeMacBook-Pro:SOUGE-Taro-Base waterman$ pushy bundle --platform android 
Bundling with react-native:  0.66.4
react-native-update-cli: 1.8.1
react-native-update: 7.3.8
Running bundle command: node node_modules/react-native/local-cli/cli.js bundle --assets-dest .pushy/intermedia/android --bundle-output .pushy/intermedia/android/index.bundlejs --dev false --entry-file index.js --platform android --reset-cache
warning: the transform cache was reset.

Welcome to Metro!
              Fast - Scalable - Integrated

error The resource `/Users/waterman/Desktop/project/souge/SOUGE-Taro-Base/index.js` was not found.
Error: The resource `/Users/waterman/Desktop/project/souge/SOUGE-Taro-Base/index.js` was not found.
    at /Users/waterman/Desktop/project/souge/SOUGE-Taro-Base/node_modules/metro/src/IncrementalBundler.js:289:24
    at gotStat (fs.js:1665:21)
    at FSReqCallback.oncomplete (fs.js:158:21)
info Run CLI with --verbose flag for more details.
Error: "react-native bundle" command exited with code 1.
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/react-native-update-cli/lib/bundle.js:82:16)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Comment by zhiqingchen** [comment]
**TODO** Taro RN支持使用 `node_modules/react-native/local-cli/cli.js bundle` 进行打包

**Comment by YuanQuan** [comment]
> **TODO：** Taro RN支持使用 `node_modules/react-native/local-cli/cli.js bundle` 进行打包

请问入口文件写什么，我的项目根目录中没有index.js文件，我是用taro init 生成的 ts 项目

**Comment by zhiqingchen** [comment]
node_modules/metro/src/node-haste/DependencyGraph/assets/empty-module.js
