### ISSUE TITLE
旧项目升级到3.4.1后编译报错

### ISSUE THREAD

**Issue by kenchu4work** [NervJS/taro#11198]
### 相关平台
微信小程序

**小程序基础库: 2.21.2**
**使用框架: React**

### 复现步骤
按https://docs.taro.zone/blog/2021-11-24-Taro-3.4-beta#%E6%94%AF%E6%8C%81%E4%BD%BF%E7%94%A8-preact 说明升级后编译成小程序时报错

### 期望结果
正常编译

### 实际结果
编译报错：
Module build failed (from ./node_modules/@tarojs/mini-runner/node_modules/babel-loader/lib/index.js):
Error: /Users/k/Documents/project/src/sp13/pages/onepage/index.tsx: Couldn't find a Program
    at Scope.getProgramParent (/Users/k/Documents/project/node_modules/babel-preset-taro/node_modules/@babel/traverse/lib/scope/index.js:864:11)
    at Scope.crawl (/Users/k/Documents/project/node_modules/babel-preset-taro/node_modules/@babel/traverse/lib/scope/index.js:769:32)
    at Scope.init (/Users/k/Documents/project/node_modules/babel-preset-taro/node_modules/@babel/traverse/lib/scope/index.js:758:12)
    at NodePath.setScope (/Users/k/Documents/project/node_modules/babel-preset-taro/node_modules/@babel/traverse/lib/path/context.js:142:30)
    at NodePath.setContext (/Users/k/Documents/project/node_modules/babel-preset-taro/node_modules/@babel/traverse/lib/path/context.js:158:8)
    at NodePath.popContext (/Users/k/Documents/project/node_modules/babel-preset-taro/node_modules/@babel/traverse/lib/path/context.js:218:10)
    at TraversalContext.visitQueue (/Users/k/Documents/project/node_modules/babel-preset-taro/node_modules/@babel/traverse/lib/context.js:117:12)
    at TraversalContext.visitMultiple (/Users/k/Documents/project/node_modules/babel-preset-taro/node_modules/@babel/traverse/lib/context.js:72:17)
    at TraversalContext.visit (/Users/k/Documents/project/node_modules/babel-preset-taro/node_modules/@babel/traverse/lib/context.js:129:19)
    at traverseNode (/Users/k/Documents/project/node_modules/babel-preset-taro/node_modules/@babel/traverse/lib/traverse-node.js:24:17)
    at traverse (/Users/k/Documents/project/node_modules/babel-preset-taro/node_modules/@babel/traverse/lib/index.js:62:34)
    at Function.traverse.hasType (/Users/k/Documents/project/node_modules/babel-preset-taro/node_modules/@babel/traverse/lib/index.js:103:3)
    at BlockScoping.wrapClosure (/Users/k/Documents/project/node_modules/babel-preset-taro/node_modules/@babel/preset-env/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:528:37)
    at BlockScoping.run (/Users/k/Documents/project/node_modules/babel-preset-taro/node_modules/@babel/preset-env/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:383:12)
    at PluginPass.BlockStatement|SwitchStatement|Program (/Users/k/Documents/project/node_modules/babel-preset-taro/node_modules/@babel/preset-env/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:89:24)
    at newFn (/Users/k/Documents/project/node_modules/@tarojs/mini-runner/node_modules/@babel/traverse/lib/visitors.js:177:21)

### 环境信息
```
Taro CLI 3.4.1 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.22.0 - ~/.nvm/versions/node/v12.22.0/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v12.22.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.1 => 3.4.1 
      @tarojs/components: 3.4.1 => 3.4.1 
      @tarojs/mini-runner: 3.4.1 => 3.4.1 
      @tarojs/react: 3.4.1 => 3.4.1 
      @tarojs/runtime: 3.4.1 => 3.4.1 
      @tarojs/taro: 3.4.1 => 3.4.1 
      @tarojs/webpack-runner: 3.4.1 => 3.4.1 
      babel-preset-taro: 3.4.1 => 3.4.1 
      react: ^17.0.0 => 17.0.2 
      react-native: ^0.64.0 => 0.64.2
```

**Comment by Chen-jj** [comment]
@kenchu4work 有按照升级指南操作么：https://docs.taro.zone/blog/2022-01-20-Taro-3.4#%E5%8D%87%E7%BA%A7%E6%8C%87%E5%8D%97

报错信息看不出来问题，可以提供一下 demo

**Comment by kenchu4work** [comment]
> 

完全按照升级指南操作的，因为项目太复杂了，提供不了demo😂

**Comment by kenchu4work** [comment]
> @kenchu4work 有按照升级指南操作么：https://docs.taro.zone/blog/2022-01-20-Taro-3.4#%E5%8D%87%E7%BA%A7%E6%8C%87%E5%8D%97
> 
> 报错信息看不出来问题，可以提供一下 demo

**Comment by kenchu4work** [comment]
> @kenchu4work 有按照升级指南操作么：https://docs.taro.zone/blog/2022-01-20-Taro-3.4#%E5%8D%87%E7%BA%A7%E6%8C%87%E5%8D%97
> 
> 报错信息看不出来问题，可以提供一下 demo

完全按照升级指南操作的，因为项目太复杂了，提供不了demo😂

**Comment by kenchu4work** [comment]
> @kenchu4work 有按照升级指南操作么：https://docs.taro.zone/blog/2022-01-20-Taro-3.4#%E5%8D%87%E7%BA%A7%E6%8C%87%E5%8D%97
> 
> 报错信息看不出来问题，可以提供一下 demo

目前是在mac上出现了这个问题，window上是正常的
