### ISSUE TITLE
升级到3.4.1后项目编译不通过

### ISSUE THREAD

**Issue by tczyb** [NervJS/taro#11295]
### 相关平台
微信小程序

**小程序基础库: 最新**
**使用框架: React**

### 复现步骤
yarn dev:weapp

### 期望结果
正常编译

### 实际结果
Missing semicolon. (2:5)

(node:7856) UnhandledPromiseRejectionWarning: SyntaxError: Missing semicolon. (2:5)
    at Object._raise (E:\TaroProject\hccd\node_modules\@babel\parser\src\parser\error.js:150:45)
    at Object.raiseWithData (E:\TaroProject\hccd\node_modules\@babel\parser\src\parser\error.js:145:17)
    at Object.raise (E:\TaroProject\hccd\node_modules\@babel\parser\src\parser\error.js:89:17)
    at Object.semicolon (E:\TaroProject\hccd\node_modules\@babel\parser\src\parser\util.js:143:10)
    at Object.parseExpressionStatement (E:\TaroProject\hccd\node_modules\@babel\parser\src\parser\statement.js:998:10)
    at Object.parseExpressionStatement (E:\TaroProject\hccd\node_modules\@babel\parser\src\plugins\typescript\index.js:2601:28)
    at Object.parseStatementContent (E:\TaroProject\hccd\node_modules\@babel\parser\src\parser\statement.js:477:19)
    at Object.parseStatementContent (E:\TaroProject\hccd\node_modules\@babel\parser\src\plugins\typescript\index.js:2455:20)
    at Object.parseStatement (E:\TaroProject\hccd\node_modules\@babel\parser\src\parser\statement.js:329:17)
    at Object.parseBlockOrModuleBlockBody (E:\TaroProject\hccd\node_modules\@babel\parser\src\parser\statement.js:1073:25)
    at Object.parseBlockBody (E:\TaroProject\hccd\node_modules\@babel\parser\src\parser\statement.js:1049:10)
    at Object.parseBlock (E:\TaroProject\hccd\node_modules\@babel\parser\src\parser\statement.js:1019:10)
    at Object.parseStatementContent (E:\TaroProject\hccd\node_modules\@babel\parser\src\parser\statement.js:398:21)
    at Object.parseStatementContent (E:\TaroProject\hccd\node_modules\@babel\parser\src\plugins\typescript\index.js:2455:20)
    at Object.parseStatement (E:\TaroProject\hccd\node_modules\@babel\parser\src\parser\statement.js:329:17)
    at Object.parseBlockOrModuleBlockBody (E:\TaroProject\hccd\node_modules\@babel\parser\src\parser\statement.js:1073:25)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To t
erminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:7856) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### 环境信息
```
  Taro CLI 3.4.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.19.0 - F:\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Users\admin\AppData\Roaming\npm\yarn.CMD
      npm: 8.5.0 - F:\nodejs\npm.CMD

```

---
### 补充信息
在app.config.ts中引用了一个JSON文件编译就不通过了，去掉改引用能正常编译，为什么？
import custom from "./pages/custom.json";

export default {
pages: ['pages/ShouYe/ShouYe'],
window: {
backgroundTextStyle: 'light',
navigationBarBackgroundColor: '#fff',
navigationBarTitleText: 'WeChat',
navigationBarTextStyle: 'black',
// enablePullDownRefresh:true
},
}

custom.json：
{
  "a": 11111
}

**Comment by Chen-jj** [comment]
提供一下完整的 demo 咯

**Comment by tczyb** [comment]
> 提供一下完整的 demo 咯

https://github.com/tczyb/TaroDemo.git

**Comment by wangjunjia** [comment]
这样试试呗，const custom = require('./pages/custom.json')

**Comment by tczyb** [comment]
> 这样试试呗，const custom = require('./pages/custom.json')

这样是可以的，在3.2.8上import custom from "./pages/custom.json";是没问题的

**Comment by chendishen** [comment]
我也是在旧项目升级到3.4.3.出现了报错，一开始是所有页面都编译不了
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

SyntaxError: Missing semicolon. (2:16)
然后我按照上边的app.config.ts 的引用方式更改，然后就可以编译了十来个页面后，继续抛这个错误，具体这个是为什么导致的啊 @wangjunjia

**Comment by AdvancedCat** [comment]
这个貌似跟新版本node不支持直接import引入json模块有关，具体参见：https://nodejs.org/dist/latest-v16.x/docs/api/esm.html#json-modules  ，可以加上 `--experimental-json-modules` 试试看呢？
当然用CommonJS引入json文件就没啥问题。

**Comment by Chen-jj** [comment]
的确是 Taro 的问题，下个版本修复

**Comment by FE92star** [comment]
mark
