### ISSUE TITLE
拉取模板错误

### ISSUE THREAD

**Issue by jianhao2010303** [NervJS/taro#11297]
### 相关平台
H5

### 复现仓库
[https://github.com/NervJS/](https://github.com/NervJS/)
**浏览器版本: chrome97**
**使用框架: React**

### 复现步骤
- 正在从 github:NervJS/taro-project-templates#v3.4 拉取远程模板...GotError [RequestError]: unable to verify the first certificate
    at ClientRequest.<anonymous> (D:\Node\node_global\node_modules\@tarojs\cli\node_modules\got\index.js:182:22)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:390:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/NervJS/taro-project-templates/archive/v3.4.zip',
  protocol: 'https:',
  url: 'https://github.com/NervJS/taro-project-templates/archive/v3.4.zip'
}
× 拉取远程模板仓库失败！
创建页面错误：找不到模板D:\Node\node_global\node_modules\@tarojs\cli\templates\redux
PS E:\workspace_xuct\calendar\xuct-calendar-weapp> 

### 期望结果
taro create 成功

### 实际结果
失败

### 环境信息
```
  Taro CLI 3.4.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.2 - D:\Node\node.EXE
      Yarn: 1.22.17 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.2 - D:\Node\npm.CMD

```

**Comment by duongtranfu** [comment]
same here. I am from Vietnam, I got this issue after run this "taro init myApp"

正在从 github:NervJS/taro-project-templates#v3.5 拉取远程模板...GotError [RequestError]: unable to verify the first certificate
    at ClientRequest.<anonymous> (/Users/duongtd2/.config/yarn/global/node_modules/download/node_modules/got/index.js:182:22)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:481:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/NervJS/taro-project-templates/archive/v3.5.zip',
  protocol: 'https:',
  url: 'https://github.com/NervJS/taro-project-templates/archive/v3.5.zip'
}
✖ 拉取远程模板仓库失败！
? 请选择模板 (Use arrow keys)
❯ 默认模板

**Comment by Chen-jj** [comment]
@duongtranfu Fetch template from Github failed for some reasons.You can choose fetching templates from Gitee.

**Comment by duongtranfu** [comment]
@Chen-jj  thank you very much, It worked !!!

**Comment by duongtranfu** [comment]
hello @Chen-jj  , I have one more question, I downloaded Taro TodoMVC-react and ran "yarn && yarn dev:weapp"
Then I open 微信开发者工具.app to open the project, but It became crazy like video below. Maybe it is app id issue. Could you please take a look?

https://user-images.githubusercontent.com/42492073/192992787-56f467ea-411b-4583-8f96-1eee83cf180f.mp4

**Comment by Chen-jj** [comment]
> hello @Chen-jj , I have one more question, I downloaded Taro TodoMVC-react and ran "yarn && yarn dev:weapp" Then I open 微信开发者工具.app to open the project, but It became crazy like video below. Maybe it is app id issue. Could you please take a look?

Never meet this before.
