### ISSUE TITLE
can't read property 'offsetLeft' of undefined

### ISSUE THREAD

**Issue by yuwanlin** [NervJS/taro#1132]
**问题描述**
微信小程序：使用AtTabBar的时候，切换tab会报错。这种常见的场景都没有看到issue，我的操作哪里有问题吗？

**复现步骤**
1. 引入AtTabBar
2. 在微信开发者工具点击tab

[或者可以直接贴源代码，能贴文字就不要截图]
```js
import Taro, { Component } from '@tarojs/taro'
import PropTypes from 'prop-types'
import { View } from '@tarojs/components'
import { AtTabBar } from 'taro-ui'

import './index.less'

export default class BottomTab extends Component {
    showTab(index) {
      switch (index) {
        case 0:
          Taro.switchTab({
            url: `/pages/index/index`
          })
          break;
        case 1:
          Taro.switchTab({
            url: `/pages/mine/index`
          })
          break;
        default:
          break;
      }
    }

    render() {
        const tabList = [
            { title: '撒币', iconType: 'money' },
            { title: '我的', iconType: 'user' },
        ]

        return (
            <View>
                <AtTabBar fixed tabList={tabList} onClick={this.showTab.bind(this)} current={this.props.tab} />
            </View>
        )
    }
}

BottomTab.propTypes = {
    tab: PropTypes.number
}

```

**期望行为**
可以正常跳转tab

**报错信息**

```js
webviewScriptError
Cannot read property 'offsetLeft' of undefined;[Exparser] [Error] [Component] Event Listener Error @ wx-view#(anonymous)
TypeError: Cannot read property 'offsetLeft' of undefined
    at v (http://127.0.0.1:17483/__pageframe__/__dev__/WAWebview.js:20:3894)
    at r.t.(anonymous function).(anonymous function).t.addListener.capture (http://127.0.0.1:17483/__pageframe__/__dev__/WAWebview.js:20:5014)
    at o.safeCallback (http://127.0.0.1:17483/__pageframe__/__dev__/WAWebview.js:5:11511)
    at o.call (http://127.0.0.1:17483/__pageframe__/__dev__/WAWebview.js:5:11275)
    at n (http://127.0.0.1:17483/__pageframe__/__dev__/WAWebview.js:5:13741)
    at http://127.0.0.1:17483/__pageframe__/__dev__/WAWebview.js:5:14295
    at s (http://127.0.0.1:17483/__pageframe__/__dev__/WAWebview.js:5:13309)
    at Function.o.dispatchEvent (http://127.0.0.1:17483/__pageframe__/__dev__/WAWebview.js:5:14196)
    at t (http://127.0.0.1:17483/__pageframe__/__dev__/WAWebview.js:7:9572)
    at g (http://127.0.0.1:17483/__pageframe__/__dev__/WAWebview.js:7:10057)
```

**系统信息**

 - 操作系统: [e.g. mac 10.13]
 - Taro 版本 [e.g. v.1.1.4]
 - Node.js 版本 [e.g. v8.11.3]
 - 报错平台 [weapp]

"@tarojs/taro": "^1.1.4",
"taro-ui": "^1.4.0"
mac 10.13 平台
微信开发者工具版本：1.02.1810240

**补充信息**

**Comment by yuwanlin** [comment]
解决了，在微信开发者工具删掉该小程序，然后重新装上就好了。  不知道具体原因，希望可以给个解答。

**Comment by luckyadam** [comment]
感觉是微信小程序开发工具的bug
