### ISSUE TITLE
1.1.4升级到1.1.6或1.1.7编译报错（1.1.5没有问题）

### ISSUE THREAD

**Issue by AloneWeb** [NervJS/taro#1140]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
项目升级到1.1.6及以上时报错
**复现步骤**
[复现问题的步骤]
1. taro update self
2. npm i -g @tarojs/cli@latest
3. taro update project
4. npm run dev:h5

[或者可以直接贴源代码，能贴文字就不要截图]

```shell
// 这里可以贴代码
{ TypeError: unknown: Property property of MemberExpression expected node to be of a type ["Identifier"] but instead got "StringLiteral"
    at validate (C:\Users\12132\.npm-global\node_modules\@tarojs\cli\node_modules\_babel-types@6.26.0@babel-types\lib\definitions\index.js:109:13)
    at Object.validate (C:\Users\12132\.npm-global\node_modules\@tarojs\cli\node_modules\_babel-types@6.26.0@babel-types\lib\definitions\core.js:412:50)
    at Object.validate (C:\Users\12132\.npm-global\node_modules\@tarojs\cli\node_modules\_babel-types@6.26.0@babel-types\lib\index.js:505:9)
    at NodePath._replaceWith (C:\Users\12132\.npm-global\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\replacement.js:176:7)
    at NodePath.replaceWith (C:\Users\12132\.npm-global\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\replacement.js:160:8)
    at replaceAndEvaluateNode (C:\Users\12132\.npm-global\node_modules\@tarojs\cli\node_modules\_babel-plugin-transform-define@1.3.0@babel-plugin-transform-define\lib\index.js:117:12)
    at processNode (C:\Users\12132\.npm-global\node_modules\@tarojs\cli\node_modules\_babel-plugin-transform-define@1.3.0@babel-plugin-transform-define\lib\index.js:143:5)
    at PluginPass.Identifier (C:\Users\12132\.npm-global\node_modules\@tarojs\cli\node_modules\_babel-plugin-transform-define@1.3.0@babel-plugin-transform-define\lib\index.js:23:9)
    at newFn (C:\Users\12132\.npm-global\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (C:\Users\12132\.npm-global\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\context.js:76:18) _babel: true }
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
不报错
**报错信息**
[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/22211269/48540385-e6fffb00-e8f4-11e8-99b7-e085b5a02850.png)
![image](https://user-images.githubusercontent.com/22211269/48540586-70afc880-e8f5-11e8-89ae-68ebf700fc31.png)

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 1.1.6 or 1.1.7
 - Node.js 版本 v10.5.0
 - 报错平台 h5

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
已修复，升级到 1.1.8 试试

**Comment by AloneWeb** [comment]
更新至1.1.8解决
