### ISSUE TITLE
H5构建报错

### ISSUE THREAD

**Issue by xuzhibin** [NervJS/taro#1142]
**问题描述**
H5构建报错
**复现步骤**
[复现问题的步骤]
1. taro build --type h5 --watch 

**期望行为**
如何解决

**报错信息**

开始编译项目 todoList
创建  发现文件  src/app.js
创建  发现文件  src/app.scss
创建  发现文件  src/index.html
创建  发现文件  src/pages/index/index.js
创建  发现文件  src/pages/index/index.scss
(node:85437) UnhandledPromiseRejectionWarning: Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Volumes/sdcard/Work/Code/taro/todoList/node_modules/.1.1.7@@tarojs/webpack-runner/dist/index.js:17:17)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
(node:85437) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:85437) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 /Volumes/sdcard/Work/Code/taro/todoList   master  webpack -v
4.25.1

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/1763232/48545119-1ff19d00-e900-11e8-9536-85f3e983323b.png">

**系统信息**

 - 操作系统: [e.g. mac 10.14]
- Taro 版本 [e.g. v.1.1.7]
- Node.js 版本 [e.g. v10.13.0]

**Comment by xuzhibin** [comment]
项目依赖重新更新了，问题依旧
<img width="913" alt="image" src="https://user-images.githubusercontent.com/1763232/48595366-4f9bb600-e98f-11e8-96a9-b6fc641176cd.png">

**Comment by luckyadam** [comment]
感觉项目依赖还是没装好，可以删了 node_modules 然后重新安装下

**Comment by jiansir** [comment]
类似同样问题  报webpack-sources  感觉这东西多端配置坑太多了

**Comment by xuzhibin** [comment]
删了 node_modules 然后重新安装，重复了10几次，还是有一些依赖包有问题，再一个个安装。折腾了几天，终于成功看到hello world了。依赖包太多，安装的确是遇到问题，希望能考虑优化一下，真正做到开箱即用。
