### ISSUE TITLE
编译sourcemap出现错误

### ISSUE THREAD

**Issue by willxucn** [NervJS/taro#11574]
### 相关平台
百度小程序

**小程序基础库: 无关**
**使用框架: React**

### 复现步骤
注意，版本是3.4.4，但是open issue时，没有3.4.4的选项，但是确实是3.4.4的问题
系统是Windows 11
node版本 v16.13.2
NODE_ENV=develop情况下，执行  taro build --type swan --watch 就会报错。切换到production不会出现这个问题。

### 期望结果
正常编译结束

### 实际结果
| 正在编译...offset_sourcemap_lines_1.default is not a function

offset_sourcemap_lines_1.default is not a function

node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

TypeError: offset_sourcemap_lines_1.default is not a function
    at TaroMiniPlugin.injectCommonStyles (D:\Users\WillXu\Source\Repos\MiniApp\tarojs331\saqs\node_modules\@tarojs\mini-runner\src\plugins\MiniPlugin.ts:1190:43)
    at TaroMiniPlugin.<anonymous> (D:\Users\WillXu\Source\Repos\MiniApp\tarojs331\saqs\node_modules\@tarojs\mini-runner\src\plugins\MiniPlugin.ts:1007:10)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Users\WillXu\Source\Repos\MiniApp\tarojs331\saqs\node_modules\@tarojs\mini-runner\dist\plugins\MiniPlugin.js:5:58)

### 环境信息
```
👽 Taro v3.4.4


  Taro CLI 3.4.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.2 - D:\ProgramData\Miniconda3\envs\tarojs3\node.EXE
      npm: 8.1.2 - D:\ProgramData\Miniconda3\envs\tarojs3\npm.CMD
```

---
### 补充信息
3.4.3同一套代码，编译没这个问题，是升级到3.4.4后出现的。

升级通过taro update、taro update project并且删除了node_modules目录和lock文件再用npm install安装依赖。出现问题后，尝试再次删除node_modules和lock文件，故障依旧。

**Comment by fesiong** [comment]
遇到了相同的问题，看到 3.4.4 对 [packages/taro-mini-runner/src/plugins/MiniPlugin.ts](https://github.com/NervJS/taro/commit/5e8fc1b0601739f9aa3ab6da5a59229b0057d58b#diff-60837004163d215f0a414d212505df68c2f677dd3da56cc20dd9d988413a3821) 进行了更改，引入了 import offsetLines from 'offset-sourcemap-lines' ，导致百度小程序编译失败，其他小程序编译正常，未知原因中
