### ISSUE TITLE
运行 taro update project 后项目无法启动？是需要项目添加配置还是版本不兼容需要回滚？

### ISSUE THREAD

**Issue by LlanHao** [NervJS/taro#11593]
### 相关平台
微信小程序

**小程序基础库: 2.23.3**
**使用框架: React**

### 复现步骤
taro update project 

cnpm install

npm run dev:weapp

### 期望结果
正常打包预览

### 实际结果
VM211:9 app.js错误:
 Error: Module build failed (from @tarojs/taro-loader):
TypeError: Cannot destructure property 'importFrameworkStatement' of 'options.loaderMeta' as it is undefined.
    at Object.default_1 (:20246/Users/lanjian/WORKS/hf_cloud_service/node_modules/_@tarojs_taro-loader@3.4.4@@tarojs/taro-loader/src/app.ts:9)
    at Object../src/app.js (app.js:16)
    at __webpack_require__ (webpack_bootstrap:79)
    at checkDeferredModules (webpack_bootstrap:45)
    at Array.webpackJsonpCallback [as push] (webpack_bootstrap:32)
    at app.js:6
    at d (WASubContext.js?t=wechat&s=1649386712622&v=2.23.3:2)
    at <anonymous>:7:9
    at doWhenAllScriptLoaded (<anonymous>:7808:21)
    at Object.scriptLoaded (<anonymous>:7836:5)
    at Object.<anonymous> (<anonymous>:7861:22)(env: macOS,mp,1.06.2204022; lib: 2.23.3)

------
WAServiceMainContext.js:2 Uncaught FrameworkError 
 Module build failed (from @tarojs/taro-loader):
TypeError: Cannot destructure property 'importFrameworkStatement' of 'options.loaderMeta' as it is undefined.
    at Object.default_1 (/Users/lanjian/WORKS/hf_cloud_service/node_modules/_@tarojs_taro-loader@3.4.4@@tarojs/taro-loader/src/app.ts:9:11) 
 Error: Module build failed (from @tarojs/taro-loader):
TypeError: Cannot destructure property 'importFrameworkStatement' of 'options.loaderMeta' as it is undefined.
    at Object.default_1 (/Users/lanjian/WORKS/hf_cloud_service/node_modules/_@tarojs_taro-loader@3.4.4@@tarojs/taro-loader/src/app.ts:9:11)
    at Object../src/app.js (http://127.0.0.1:20246/appservice/app.js:16:7)
    at __webpack_require__ (http://127.0.0.1:20246/appservice/runtime.js:81:30)
    at checkDeferredModules (http://127.0.0.1:20246/appservice/runtime.js:47:23)
    at Array.webpackJsonpCallback [as push] (http://127.0.0.1:20246/appservice/runtime.js:34:19)
    at http://127.0.0.1:20246/appservice/app.js:6:49
    at d (http://127.0.0.1:20246/appservice/__dev__/WASubContext.js?t=wechat&s=1649386712622&v=2.23.3:2:705742)
    at <anonymous>:7:9
    at doWhenAllScriptLoaded (<anonymous>:7808:21)
    at Object.scriptLoaded (<anonymous>:7836:5)
    at Object.<anonymous> (<anonymous>:7861:22)(env: macOS,mp,1.06.2204022; lib: 2.23.3)

----

Error: Module build failed (from @tarojs/taro-loader):
TypeError: Cannot destructure property 'importFrameworkStatement' of 'options.loaderMeta' as it is undefined.
    at Object.default_1 (:20246/Users/lanjian/WORKS/hf_cloud_service/node_modules/_@tarojs_taro-loader@3.4.4@@tarojs/taro-loader/src/app.ts:9)
    at Object../src/app.js (app.js:16)
    at __webpack_require__ (webpack_bootstrap:79)
    at checkDeferredModules (webpack_bootstrap:45)
    at Array.webpackJsonpCallback [as push] (webpack_bootstrap:32)
    at app.js:6
    at d (WASubContext.js?t=wechat&s=1649386712622&v=2.23.3:2)
    at <anonymous>:7:9
    at doWhenAllScriptLoaded (<anonymous>:7808:21)
    at Object.scriptLoaded (<anonymous>:7836:5)
    at Object.<anonymous> (<anonymous>:7861:22)(env: macOS,mp,1.06.2204022; lib: 2.23.3)

### 环境信息
```
👽 Taro v3.3.9

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

  Taro CLI 3.3.9 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.5.1 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 4.3.5
```

**Comment by LlanHao** [comment]
https://docs.taro.zone/blog/2021-11-24-Taro-3.4-beta

**Comment by HARRISKING** [comment]
yarn add @tarojs/taro-loader@3.3.9 就可解决
