### ISSUE TITLE
taro命令报错 随便执行一个taro命令（taro info）You gave us a visitor for the node type StaticBlock but it's not a valid type 

### ISSUE THREAD

**Issue by huanlirui** [NervJS/taro#11810]
### 相关平台
微信小程序

**小程序基础库: 2.24.2**
**使用框架: React**

### 复现步骤
taro版本 3.4.9

1. 执行 taro info  或任意指令

2. 报错 You gave us a visitor for the node type StaticBlock but it's not a valid type (While processing: /Users/getaikejiff/.config/yarn/global/node_modules/@babel/preset-typescript/lib/index.js)
    at verify (/Users/getaikejiff/.config/yarn/global/node_modules/@babel/plugin-transform-typescript/node_modules/@babel/traverse/lib/visitors.js:116:13)
    at explode (/Users/getaikejiff/.config/yarn/global/node_modules/@babel/plugin-transform-typescript/node_modules/@babel/traverse/lib/visitors.js:38:3)
    at Object.merge (/Users/getaikejiff/.config/yarn/global/node_modules/@babel/plugin-transform-typescript/node_modules/@babel/traverse/lib/visitors.js:151:5)
    at Object.<anonymous> (/Users/getaikejiff/.config/yarn/global/node_modules/@babel/plugin-transform-typescript/node_modules/@babel/helper-replace-supers/lib/index.js:60:44)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (/Users/getaikejiff/.config/yarn/global/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .js] (/Users/getaikejiff/.config/yarn/global/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
(node:16584) UnhandledPromiseRejectionWarning: Error: [BABEL]: You gave us a visitor for the node type StaticBlock but it's not a valid type (While processing: /Users/getaikejiff/.config/yarn/global/node_modules/@babel/preset-typescript/lib/index.js)
    at verify (/Users/getaikejiff/.config/yarn/global/node_modules/@babel/plugin-transform-typescript/node_modules/@babel/traverse/lib/visitors.js:116:13)
    at explode (/Users/getaikejiff/.config/yarn/global/node_modules/@babel/plugin-transform-typescript/node_modules/@babel/traverse/lib/visitors.js:38:3)
    at Object.merge (/Users/getaikejiff/.config/yarn/global/node_modules/@babel/plugin-transform-typescript/node_modules/@babel/traverse/lib/visitors.js:151:5)
    at Object.<anonymous> (/Users/getaikejiff/.config/yarn/global/node_modules/@babel/plugin-transform-typescript/node_modules/@babel/helper-replace-supers/lib/index.js:60:44)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (/Users/getaikejiff/.config/yarn/global/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .js] (/Users/getaikejiff/.config/yarn/global/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### 期望结果
正确执行taro命令

### 实际结果
控制台报错

### 环境信息
```
taro 环境信息，我无法执行taro info，所以我是拷贝别人的。修改了下版本号。
提交这个issue的表单不也是坑爹吗？我命令都执行不了，。怎么拿到taro info 信息?

👽 Taro v3.4.9

Taro CLI 3.4.9 environment info:
System:
OS: macOS 11.4

Binaries:
Node: 14.16.1 - /usr/local/bin/node
Yarn: 1.22.19 - /usr/local/bin/yarn

```

**Comment by huanlirui** [comment]
可能不是taro的问题。cd 到 /Users/yourDir(路径每个机子不同)/.config/yarn/global  删除node_modules 再重新yarn 。

**Comment by huanlirui** [comment]
如果不行。检查是不是有umi相关的依赖，打开package.json 删除umi/cli相关。重新yarn

**Comment by zjxpcyc** [comment]
我也是这个错误，没解决
