### ISSUE TITLE
3.5版本webpack5编译到H5，报错 defineAppConfig is not defined

### ISSUE THREAD

**Issue by weilaiqishi** [NervJS/taro#11872]
### 相关平台
H5

### 复现仓库
[https://github.com/weilaiqishi/taro35test](https://github.com/weilaiqishi/taro35test)
**浏览器版本: Microsoft Edge 101**
**使用框架: React**

### 复现步骤
1.使用taro-cli和内置模板创建项目
2.调整config配置
  compiler: {
    type: 'webpack5',
    prebundle: {
      enable: false
    }
  },
  cache: {
    enable: false // Webpack 持久化缓存配置，建议开启。默认配置请参考：https://docs.taro.zone/docs/config-detail#cache
  }
3.yarn dev:h5
4.浏览器访问 http://192.168.1.8:10086/

### 期望结果
显示页面内容

### 实际结果
报错 defineAppConfig is not defined
![taroh5](https://user-images.githubusercontent.com/22250972/171340223-5a18decf-a91c-40f0-a5ae-0de42ce7a833.png)

### 环境信息
```
  Taro CLI 3.5.0-beta.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.0 - C:\frontend\nodejsversion\node.EXE
      Yarn: 1.22.18 - C:\frontend\nodejsversion\yarn.CMD
      npm: 8.5.5 - C:\frontend\nodejsversion\npm.CMD
```

**Comment by weilaiqishi** [comment]
如果使用webpack4编译到h5
`config/index/js`
```js
  compiler: {
    type: 'webpack4',
  },
```

那么控制台运行 yarn dev:h5 会报错

TypeError: Cannot read properties of undefined (reading 'tapPromise')
    at C:\frontend\web\project\business\lowcode\taro35test\node_modules\@pmmmwh\react-refresh-webpack-plugin\lib\index.js:104:35
    at Array.forEach (<anonymous>)
    at ReactRefreshPlugin.apply (C:\frontend\web\project\business\lowcode\taro35test\node_modules\@pmmmwh\react-refresh-webpack-plugin\lib\index.js:103:33)
    at webpack (C:\frontend\web\project\business\lowcode\taro35test\node_modules\@tarojs\webpack-runner\node_modules\webpack\lib\webpack.js:51:13)
    at C:\frontend\web\project\business\lowcode\taro35test\node_modules\@tarojs\webpack-runner\src\index.ts:132:20
    at Generator.next (<anonymous>)
    at fulfilled (C:\frontend\web\project\business\lowcode\taro35test\node_modules\@tarojs\webpack-runner\dist\index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by weilaiqishi** [comment]
如果使用webpack4编译到h5
`config/index/js`
```js
  compiler: {
    type: 'webpack4',
  },
```

那么控制台运行 yarn dev:h5 会报错

TypeError: Cannot read properties of undefined (reading 'tapPromise')
    at C:\frontend\web\project\business\lowcode\taro35test\node_modules\@pmmmwh\react-refresh-webpack-plugin\lib\index.js:104:35
    at Array.forEach (<anonymous>)
    at ReactRefreshPlugin.apply (C:\frontend\web\project\business\lowcode\taro35test\node_modules\@pmmmwh\react-refresh-webpack-plugin\lib\index.js:103:33)
    at webpack (C:\frontend\web\project\business\lowcode\taro35test\node_modules\@tarojs\webpack-runner\node_modules\webpack\lib\webpack.js:51:13)
    at C:\frontend\web\project\business\lowcode\taro35test\node_modules\@tarojs\webpack-runner\src\index.ts:132:20
    at Generator.next (<anonymous>)
    at fulfilled (C:\frontend\web\project\business\lowcode\taro35test\node_modules\@tarojs\webpack-runner\dist\index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by weilaiqishi** [comment]
如果 `src/app.config.ts` 去掉defineAppConfig

```ts
export default {
  pages: [
    'pages/index/index'
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black'
  }
}
```

使用webpack5模式打包H5端 `yarn build:h5`，结果没打包出内容
![image](https://user-images.githubusercontent.com/22250972/171344145-af2548bb-c037-433b-af41-c8c3350af2c2.png)

**Comment by ZakaryCode** [comment]
未再 3.5.1-beta.1 复现到该问题，可以检查下依赖和cli是否统一

**Comment by ZakaryCode** [comment]
> 能否给一个可以跑起来的demo让我试一下

直接使用你给的 demo 就是可以正常运行的 （另外，beta 有发布新的版本，也可以升级试试

**Comment by youmeetzz** [comment]
你好  我也遇到这个问题  请问解决了吗？

**Comment by youmeetzz** [comment]
![1655105569852](https://user-images.githubusercontent.com/30773279/173302524-2c6c85f9-05e3-4a51-9dc4-a23dbf3bc8d4.jpg)
windows 上修改成这样就没问题了 
@weilaiqishi 感谢
