### ISSUE TITLE
3.4.12 小程序使用 preact 报错

### ISSUE THREAD

**Issue by w88975** [NervJS/taro#11962]
### 相关平台
微信小程序

**小程序基础库: 2.24.5**
**使用框架: React**

### 复现步骤
taro build --type weapp

### 期望结果
正常运行

### 实际结果
(node:48439) UnhandledPromiseRejectionWarning: TypeError: helper_1.FRAMEWORK_EXT_MAP[framework] is not iterable
    at TaroMiniPlugin.getTabBarFiles (/Users/kamisama/work/kamisama/beijing/user-mobile/node_modules/@tarojs/mini-runner/src/plugins/MiniPlugin.ts:875:30)
    at TaroMiniPlugin.getPages (/Users/kamisama/work/kamisama/beijing/user-mobile/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:454:10)
    at TaroMiniPlugin.run (/Users/kamisama/work/kamisama/beijing/user-mobile/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:303:12)
    at TaroMiniPlugin.<anonymous> (/Users/kamisama/work/kamisama/beijing/user-mobile/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:132:18)
    at Generator.next (<anonymous>)
    at /Users/kamisama/work/kamisama/beijing/user-mobile/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:11:67
    at new Promise (<anonymous>)
    at __awaiter (/Users/kamisama/work/kamisama/beijing/user-mobile/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:4:10)
    at /Users/kamisama/work/kamisama/beijing/user-mobile/node_modules/@tarojs/mini-runner/src/plugins/MiniPlugin.ts:209:30
    at TaroMiniPlugin.<anonymous> (/Users/kamisama/work/kamisama/beijing/user-mobile/node_modules/@tarojs/mini-runner/src/plugins/MiniPlugin.ts:168:7)
    at Generator.next (<anonymous>)
    at /Users/kamisama/work/kamisama/beijing/user-mobile/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:11:67
    at new Promise (<anonymous>)
    at __awaiter (/Users/kamisama/work/kamisama/beijing/user-mobile/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:4:10)
    at /Users/kamisama/work/kamisama/beijing/user-mobile/node_modules/@tarojs/mini-runner/src/plugins/MiniPlugin.ts:167:17
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/kamisama/work/kamisama/beijing/user-mobile/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
(Use `node --trace-warnings ...` to show where the warning was created)
<node_internals>/internal/process/warning.js:33
(node:48439) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
<node_internals>/internal/process/warning.js:33
(node:48439) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### 环境信息
```
👽 Taro v3.4.12


  Taro CLI 3.4.12 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.6.0 - ~/.nvm/versions/node/v14.6.0/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v14.6.0/bin/npm
    npmPackages:
      @tarojs/components: 3.4.12 => 3.4.12 
      @tarojs/mini-runner: 3.4.12 => 3.4.12 
      @tarojs/plugin-framework-react: ^3.4.12 => 3.4.12 
      @tarojs/react: 3.4.12 => 3.4.12 
      @tarojs/runtime: 3.4.12 => 3.4.12 
      @tarojs/taro: 3.4.12 => 3.4.12 
      @tarojs/webpack-runner: ^3.4.12 => 3.4.12 
      babel-preset-taro: 3.4.12 => 3.4.12 
      eslint-config-taro: 3.4.12 => 3.4.12 
      react: ^17.0.0 => 17.0.2 
```

---
### 补充信息
当使用 preact 代替 react 的时候
FRAMEWORK_EXT_MAP[framework]  的 framework 没有对应的配置, 手动映射为react即可正常编译

建议在 tarojs/helper 中, 增加对preact的支持,或者将preact映射为react

**Comment by Chen-jj** [comment]
@w88975 欢迎 PR 呀

**Comment by w88975** [comment]
@Chen-jj  已提
