### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by QiiSyhx** [NervJS/taro#12107]
### 相关平台
H5

**使用框架: Vue 3**

### 复现步骤
npm run dev:h5

### 期望结果
运行成功

### 实际结果
- Compiling...(node:11460) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
i ｢wds｣: Project is running at http://192.168.1.213:10086/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from E:\workspace\js\landui\site_electronic_filing\dist
i ｢wds｣: 404s will fallback to /index.html
http://localhost:10086/
| Compiling...node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (E:\workspace\js\landui\site_electronic_filing\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (E:\workspace\js\landui\site_electronic_filing\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (E:\workspace\js\landui\site_electronic_filing\node_modules\webpack\lib\NormalModule.js:471:10)
    at E:\workspace\js\landui\site_electronic_filing\node_modules\webpack\lib\NormalModule.js:503:5
    at E:\workspace\js\landui\site_electronic_filing\node_modules\webpack\lib\NormalModule.js:358:12
    at E:\workspace\js\landui\site_electronic_filing\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (E:\workspace\js\landui\site_electronic_filing\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (E:\workspace\js\landui\site_electronic_filing\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (E:\workspace\js\landui\site_electronic_filing\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at E:\workspace\js\landui\site_electronic_filing\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at E:\workspace\js\landui\site_electronic_filing\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.1.0

### 环境信息
```
Taro CLI 3.4.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 18.1.0 - d:\nodejs-nvm\node.EXE
      npm: 8.8.0 - d:\nodejs-nvm\npm.CMD
```

**Comment by ZakaryCode** [comment]
这是一个 node18 问题，可以通过设置环境变量解决

```sh
# 👇️ macOS, Linux or Windows Git Bash
export NODE_OPTIONS=--openssl-legacy-provider

# 👇️ Windows CMD
set NODE_OPTIONS=--openssl-legacy-provider

```
