### ISSUE TITLE
3.5.1 dev：h5   报错

### ISSUE THREAD

**Issue by xiaof520** [NervJS/taro#12221]
### 相关平台
H5

**浏览器版本: edge**
**使用框架: React**

### 复现步骤
taro init test

preact
sass
taro-ui

### 期望结果
能修复，3.5.0 正确

### 实际结果
1

### 环境信息
```
Taro v3.5.1


  Taro CLI 3.5.1 environment info:
    System:
      OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
      Shell: 5.1.4 - /bin/bash
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.1 => 3.5.1 
      @tarojs/components: 3.5.1 => 3.5.1 
      @tarojs/helper: 3.5.1 => 3.5.1 
      @tarojs/plugin-framework-react: 3.5.1 => 3.5.1 
      @tarojs/plugin-platform-alipay: 3.5.1 => 3.5.1 
      @tarojs/plugin-platform-jd: 3.5.1 => 3.5.1 
      @tarojs/plugin-platform-qq: 3.5.1 => 3.5.1 
      @tarojs/plugin-platform-swan: 3.5.1 => 3.5.1 
      @tarojs/plugin-platform-tt: 3.5.1 => 3.5.1 
      @tarojs/plugin-platform-weapp: 3.5.1 => 3.5.1 
      @tarojs/router: 3.5.1 => 3.5.1 
      @tarojs/runtime: 3.5.1 => 3.5.1 
      @tarojs/shared: 3.5.1 => 3.5.1 
      @tarojs/taro: 3.5.1 => 3.5.1 
      @tarojs/taro-h5: 3.5.1 => 3.5.1 
      @tarojs/webpack-runner: 3.5.1 => 3.5.1 
      babel-preset-taro: 3.5.1 => 3.5.1 
      eslint-config-taro: 3.5.1 => 3.5.1 
      taro-ui: ^3.1.0-beta.2 => 3.1.0-beta.2 
```

---
### 补充信息
taro.js:1 
        
       Uncaught SyntaxError: Unexpected token '<' (at taro.js:1:1)
app.js:1 
        
       Uncaught SyntaxError: Unexpected token '<' (at app.js:1:1)

**Comment by xiaof520** [comment]
build:h5 正常

**Comment by ZakaryCode** [comment]
未再指定版本复现该问题，如无更多信息，该 issue 将被关闭
