### ISSUE TITLE
[3.5.2] webpack5 启动报错： Cannot find module 'webpack/lib/container/ModuleFederationPlugin'

### ISSUE THREAD

**Issue by kongsiyu** [NervJS/taro#12240]
### 相关平台
H5

**浏览器版本: chrome103**
**使用框架: Vue 3**

### 复现步骤
使用 taro build --type h5 --watch 启动

### 期望结果
正常编译启动

依赖配置：
```
"dependencies": {
    "@babel/runtime": "^7.18.9",
    "@nutui/nutui-taro": "^3.2.0",
    "@tarojs/components": "3.5.2",
    "@tarojs/mini-runner": "^3.5.2",
    "@tarojs/plugin-framework-vue3": "3.5.2",
    "@tarojs/plugin-html": "^3.5.2",
    "@tarojs/runtime": "3.5.2",
    "@tarojs/taro": "3.5.2",
    "@tarojs/webpack5-runner": "^3.5.2",
    "pinia": "^2.0.17",
    "snowflake-id": "^1.1.0",
    "taro-plugin-pinia": "^1.0.0",
    "url": "^0.11.0",
    "vue": "^3.2.37"
  },
  "devDependencies": {
    "@babel/core": "^7.18.10",
    "@dcasia/mini-program-tailwind-webpack-plugin": "^1.5.2",
    "@tarojs/cli": "3.5.2",
    "@types/webpack-env": "^1.17.0",
    "@typescript-eslint/eslint-plugin": "^5.32.0",
    "@typescript-eslint/parser": "^5.32.0",
    "@vue/babel-plugin-jsx": "^1.1.1",
    "@vue/compiler-sfc": "^3.2.37",
    "babel-plugin-import": "^1.13.5",
    "babel-preset-taro": "3.5.2",
    "cross-env": "^7.0.3",
    "eslint": "^8.21.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-config-taro": "3.5.2",
    "eslint-define-config": "^1.5.1",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jest": "^26.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-vue": "^9.3.0",
    "stylelint": "14.9.1",
    "tailwindcss": "^3.1.8",
    "typescript": "^4.7.4",
    "vue-loader": "^17.0.0"
  }
```
### 实际结果
报错：
```
yarn run v1.22.19
$ cross-env NODE_ENV=development API_ENV=beta taro build --type h5 --watch
👽 Taro v3.5.2

node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'webpack/lib/container/ModuleFederationPlugin'
Require stack:
- D:\ProgramData\git\repository\leiyan\moti-frontend\moti-storesearch-taro\node_modules\@tarojs\webpack5-prebundle\dist\webpack\TaroModuleFederationPlugin.js
- D:\ProgramData\git\repository\leiyan\moti-frontend\moti-storesearch-taro\node_modules\@tarojs\webpack5-prebundle\dist\prebundle\index.js
- D:\ProgramData\git\repository\leiyan\moti-frontend\moti-storesearch-taro\node_modules\@tarojs\webpack5-prebundle\dist\index.js
- D:\ProgramData\git\repository\leiyan\moti-frontend\moti-storesearch-taro\node_modules\@tarojs\webpack5-runner\dist\index.h5.js
- D:\ProgramData\git\repository\leiyan\moti-frontend\moti-storesearch-taro\node_modules\@tarojs\webpack5-runner\index.js
- D:\ProgramData\git\repository\leiyan\moti-frontend\moti-storesearch-taro\node_modules\@tarojs\helper\dist\npm.js
- D:\ProgramData\git\repository\leiyan\moti-frontend\moti-storesearch-taro\node_modules\@tarojs\helper\dist\index.js
- D:\ProgramData\git\repository\leiyan\moti-frontend\moti-storesearch-taro\node_modules\@tarojs\helper\index.js
- D:\ProgramData\git\repository\leiyan\moti-frontend\moti-storesearch-taro\node_modules\@tarojs\cli\dist\util\index.js
- D:\ProgramData\git\repository\leiyan\moti-frontend\moti-storesearch-taro\node_modules\@tarojs\cli\bin\taro
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\ProgramData\git\repository\leiyan\moti-frontend\moti-storesearch-taro\node_modules\@tarojs\webpack5-prebundle\src\webpack\TaroModuleFederationPlugin.ts:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.newLoader [as .js] (D:\ProgramData\git\repository\leiyan\moti-frontend\moti-storesearch-taro\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\ProgramData\\git\\repository\\leiyan\\moti-frontend\\moti-storesearch-taro\\node_modules\\@tarojs\\webpack5-prebundle\\dist\\webpack\\TaroModuleFederationPlugin.js',
    'D:\\ProgramData\\git\\repository\\leiyan\\moti-frontend\\moti-storesearch-taro\\node_modules\\@tarojs\\webpack5-prebundle\\dist\\prebundle\\index.js',
    'D:\\ProgramData\\git\\repository\\leiyan\\moti-frontend\\moti-storesearch-taro\\node_modules\\@tarojs\\webpack5-prebundle\\dist\\index.js',
    'D:\\ProgramData\\git\\repository\\leiyan\\moti-frontend\\moti-storesearch-taro\\node_modules\\@tarojs\\webpack5-runner\\dist\\index.h5.js',
    'D:\\ProgramData\\git\\repository\\leiyan\\moti-frontend\\moti-storesearch-taro\\node_modules\\@tarojs\\webpack5-runner\\index.js',
    'D:\\ProgramData\\git\\repository\\leiyan\\moti-frontend\\moti-storesearch-taro\\node_modules\\@tarojs\\helper\\dist\\npm.js',
    'D:\\ProgramData\\git\\repository\\leiyan\\moti-frontend\\moti-storesearch-taro\\node_modules\\@tarojs\\helper\\dist\\index.js',
    'D:\\ProgramData\\git\\repository\\leiyan\\moti-frontend\\moti-storesearch-taro\\node_modules\\@tarojs\\helper\\index.js',
    'D:\\ProgramData\\git\\repository\\leiyan\\moti-frontend\\moti-storesearch-taro\\node_modules\\@tarojs\\cli\\dist\\util\\index.js',
    'D:\\ProgramData\\git\\repository\\leiyan\\moti-frontend\\moti-storesearch-taro\\node_modules\\@tarojs\\cli\\bin\\taro'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1
```

### 环境信息
```
👽 Taro v3.5.2


  Taro CLI 3.5.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD

```

**Comment by zhouzyc** [comment]
3.5.1 =》3.5.2 后我这边是出现：
Cannot find module 'webpack'

**Comment by kongsiyu** [comment]
> 我使用的是react. 3.5.1 =》3.5.2 后我这边是出现： Cannot find module 'webpack'。 然后安装了 'webpack'后，编译时等待非常久卡在编译处，出现： Hot Module Replacement (HMR) is not enabled! React Refresh requires HMR to f

意思是3.5.1是好的吗？

**Comment by zhouzyc** [comment]
> > 我使用的是react. 3.5.1 =》3.5.2 后我这边是出现： Cannot find module 'webpack'。 然后安装了 'webpack'后，编译时等待非常久卡在编译处，出现： Hot Module Replacement (HMR) is not enabled! React Refresh requires HMR to f
> 
> 意思是3.5.1是好的吗？

是的3.5.1是正确的，我回退到3.5.1后编译正常。
