### ISSUE TITLE
Taro 2.2.18   出现 使用async await报错，Function() is not a function

### ISSUE THREAD

**Issue by chencs-19950208** [NervJS/taro#12377]
### 相关平台
钉钉小程序

**小程序基础库: 0.0.18**
**使用框架: React**

### 复现步骤
编译没有问题，运行出现报错，页面崩溃

### 期望结果
一切完好

### 实际结果
95fb1a0c-a590-4546-86a8-b79c48a52458:1 TypeError: Function(...) is not a function
    at Object.node_modules_Babel_runtime7189BabelRuntimeRegeneratorIndexJs (vendors.js:826:1)
    at __webpack_require__ (runtime.js:80:1)
    at Module.node_modules_dvaCore204DvaCoreDistIndexEsmJs (vendors.js:13155:1)
    at __webpack_require__ (runtime.js:80:1)
    at Module.<anonymous> (common.js:7227:1)
    at Module.srcStoreTs (common.js:7258:1)
    at __webpack_require__ (runtime.js:80:1)
    at Module.srcServiceRequestIndexJs (common.js:6501:1)
    at __webpack_require__ (runtime.js:80:1)
    at Module.node_modules_Tarojs_miniRunner226TarojsMiniRunnerDistLoadersWxTransformerLoaderJsSrcAppTsxTaroTypeScriptParseENTRY (app.js:22:1)

### 环境信息
```
👽 Taro v2.2.6
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

  Taro CLI 3.4.13 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.6/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    npmPackages:
      @tarojs/cli: 2.2.6 => 2.2.6
      @taroks/taro-alipay: 2.2.18 => 2.2.18
      @tarojs/components: 2.2.6 => 2.2.6 
      @tarojs/mini-runner: 2.2.6 => 2.2.6  
      @tarojs/taro: 2.2.6 => 2.2.6 
      @tarojs/webpack-runner: 2.2.6 => 2.2.6 
      eslint-config-taro: 2.2.6 => 2.2.6 
      react: ^17.0.0 => 17.0.2 
    npmGlobalPackages:
      typescript: 4.5.5
```

**Comment by Chen-jj** [comment]
taro CLI 和项目 taro 依赖版本保持一致
