### ISSUE TITLE
taro3.4.4升级失败

### ISSUE THREAD

**Issue by SpringHgui** [NervJS/taro#12407]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/none/none](https://github.com/none/none)
**小程序基础库: 1**
**使用框架: Vue 3**

### 复现步骤
taro项目 3.4.4下执行 `taro update project`

### 期望结果
项目升级至最新版本 3.5.4

### 实际结果
taro update project
👽 Taro v3.5.4

\ 正在获取最新版本信息...C:\Users\Sprin\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\presets\commands\update.js:339
                                        _ = "^".concat;
                                          ^

ReferenceError: _ is not defined
    at C:\Users\Sprin\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\presets\commands\update.js:339:43
    at step (C:\Users\Sprin\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\presets\commands\update.js:133:23)        
    at Object.next (C:\Users\Sprin\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\presets\commands\update.js:74:20)  
    at fulfilled (C:\Users\Sprin\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\presets\commands\update.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### 环境信息
```
👽 Taro v3.5.4


  Taro CLI 3.5.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
```

**Comment by feidaZhang** [comment]
+1

**Comment by yuconora** [comment]
3.5.x 版本基本好像都有这个问题 执行 taro update project 会报这个错误

**Comment by Chen-jj** [comment]
感觉是模板字符串里使用了 await 的问题，可能与 nodejs 版本有关。Taro 可以去掉 nerv 相关代码
