### ISSUE TITLE
安装、更新taro 失败

### ISSUE THREAD

**Issue by langlangbody** [NervJS/taro#1247]
**复现步骤**
[复现问题的步骤]
`sudo cnpm i -g @tarojs/cli@latest`

```shell
Error: GET http://registry.npm.taobao.org/@tarojs/cli/download/@tarojs/cli-1.2.0-beta.2.tgz response 403 status
```

**系统信息**

 - 操作系统: [mac]

**Comment by zacksleo** [comment]
用 npm 安装呢？刚装过没问题

**Comment by hjh1123** [comment]
bogon:~ apple$ taro init myApp
/usr/local/lib/node_modules/@tarojs/cli/src/util/index.js:206
exports.replaceAsync = async function (str, regex, asyncFn) {
                             ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/bin/taro:4:44)
    at Module._compile (module.js:573:32)
bogon:~ apple$
