### ISSUE TITLE
Taro 3.5.5 编译别人的项目时提示 “找不到依赖 "@tarojs/plugin-platform-weapp"，请先在项目中安装”

### ISSUE THREAD

**Issue by volvoxc** [NervJS/taro#12484]
Taro 3.5.5 编译别人的项目时提示 “找不到依赖 "@tarojs/plugin-platform-weapp"，请先在项目中安装”

在项目中执行  taro update project 3.5.5 时提示：

C:\Users\xxx\Desktop\taroDemo-master>taro update project 3.5.5
👽 Taro v3.5.5

- 正在获取最新版本信息...C:\nvm\v16.17.0\node_modules\@tarojs\cli\dist\presets\commands\update.js:339
                                        _ = "^".concat;
                                          ^

ReferenceError: _ is not defined
    at C:\nvm\v16.17.0\node_modules\@tarojs\cli\dist\presets\commands\update.js:339:43
    at step (C:\nvm\v16.17.0\node_modules\@tarojs\cli\dist\presets\commands\update.js:133:23)
    at Object.next (C:\nvm\v16.17.0\node_modules\@tarojs\cli\dist\presets\commands\update.js:74:20)
    at fulfilled (C:\nvm\v16.17.0\node_modules\@tarojs\cli\dist\presets\commands\update.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

知道的麻烦给说下原因，想入下门，希望不会是还没入门就被逼放弃

_Originally posted by @volvoxc in https://github.com/NervJS/taro/discussions/12483_

**Comment by TheKonka** [comment]
![image](https://user-images.githubusercontent.com/22173084/192085605-34a9ed93-0708-486d-8a05-e2bab4354495.png)
问题还在

**Comment by yuconora** [comment]
https://github.com/NervJS/taro/issues/12407#issuecomment-1240192407
