### ISSUE TITLE
react-native css 处理检查

### ISSUE THREAD

**Issue by zacksleo** [NervJS/taro#1249]
**问题描述**
 
react-native 编译时，如果CSS存在问题，会报错，但错误信息帮助不大，难以找到具体错误内容

**复现步骤**
[复现问题的步骤]
```js
yarn build:rn
```

**期望行为**
具体警告原因

**报错信息**

```bash
编译  CSS       /builds/lipstick/src/components/TopBar/index.css
警告  css-to-react-native 报错  /builds/lipstick/src/components/TopBar/index.css
Error: Unexpected token type: function
    at TokenStream._throw (/builds/lipstick/node_modules/css-to-react-native/index.js:747:13)
    at TokenStream.expect (/builds/lipstick/node_modules/css-to-react-native/index.js:721:49)
    at Object.background (/builds/lipstick/node_modules/css-to-react-native/index.js:600:44)
    at baseTransformShorthandValue (/builds/lipstick/node_modules/css-to-react-native/index.js:797:30)
    at getStylesForProperty (/builds/lipstick/node_modules/css-to-react-native/index.js:810:64)
    at /builds/lipstick/node_modules/css-to-react-native/index.js:829:33
    at Array.reduce (<anonymous>)
    at index (/builds/lipstick/node_modules/css-to-react-native/index.js:825:16)
    at transformDecls (/builds/lipstick/node_modules/css-to-react-native-transform/dist/index.js:62:60)
    at transform (/builds/lipstick/node_modules/css-to-react-native-transform/dist/index.js:82:7)
```

**系统信息**

 - 操作系统: mac
 - Taro 版本  Taro v1.1.9
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [rn]

**Comment by Pines-Cheng** [comment]
根据警告提示，这个 是  /builds/lipstick/src/components/TopBar/index.css  文件里面有问题 ，导致在使用 css-to-react-native 将 css 转换成 RN style 的时候报错 ，[css-to-react-native](https://github.com/styled-components/css-to-react-native) 只提供了这些报错信息，如果要再详细的话，就得改它的源码了。

建议同时配合一些 stylelint 工具，这样就很顺畅啦。
