### ISSUE TITLE
小程序偶尔白屏，报错“没有找到页面实例”

### ISSUE THREAD

**Issue by kong-dev** [NervJS/taro#12514]
### 相关平台
微信小程序

**小程序基础库: 各版本都有**
**使用框架: React**

### 复现步骤
项目近期从 Taro 1.3.9 升级到 Taro 3.5.4，上线后部分用户反馈白屏，报错信息：
```
没有找到页面实例。
Error: 没有找到页面实例。
at Te (https://usr/app-service.js:14660:79405)
at i.<anonymous> (https://usr/app-service.js:14660:65729)
at Nn (https://usr/app-service.js:14665:29737)
at Da (https://usr/app-service.js:14665:78125)
at Ua (https://usr/app-service.js:14665:77689)
at Aa (https://usr/app-service.js:14665:77221)
at eu (https://usr/app-service.js:14665:89000)
at Xl (https://usr/app-service.js:14665:88349)
at Bl (https://usr/app-service.js:14665:85027)
at rn (https://usr/app-service.js:14665:25162)
```

本地尝试过没有复现。

入口代码：
```tsx
import Taro from '@tarojs/taro'
import { Component } from 'react'
import { Provider } from 'react-redux'
import store from 'src/store'
// ...

export default class App extends Component {
  // ...
  render () {
    return (
      <Provider store={store}>
        { this.props.children }
      </Provider>
    )
  }
}
```

### 期望结果
正常打开页面

### 实际结果
偶现的页面白屏

### 环境信息
```
👽 Taro v3.5.4


  Taro CLI 3.5.4 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    npmPackages:
      @tarojs/cli: ^3.5.4 => 3.5.4 
      @tarojs/components: ^3.5.4 => 3.5.4 
      @tarojs/helper: ^3.5.4 => 3.5.4 
      @tarojs/plugin-framework-react: ^3.5.4 => 3.5.4 
      @tarojs/plugin-platform-weapp: ^3.5.4 => 3.5.4 
      @tarojs/react: ^3.5.4 => 3.5.4 
      @tarojs/router: ^3.5.4 => 3.5.4 
      @tarojs/runtime: ^3.5.4 => 3.5.4 
      @tarojs/service: ^3.5.4 => 3.5.4 
      @tarojs/shared: ^3.5.4 => 3.5.4 
      @tarojs/taro: ^3.5.4 => 3.5.4 
      @tarojs/taro-h5: ^3.5.4 => 3.5.4 
      @tarojs/webpack5-runner: ^3.5.4 => 3.5.4 
      babel-preset-taro: ^3.5.4 => 3.5.4 
      eslint-config-taro: ^3.5.4 => 3.5.4 
      react: ^18.0.0 => 18.2.0 


```

**Comment by Chen-jj** [comment]
@kong-dev 尽量追查一下有没有更详细的信息吧，靠现在这些信息无法定位

**Comment by kong-dev** [comment]
查明是生命周期中出现异常导致的
