### ISSUE TITLE
支付宝小程序开发环境下正常，发布时无法编译

### ISSUE THREAD

**Issue by chenxinbin** [NervJS/taro#12541]
### 相关平台
支付宝小程序

**小程序基础库: 2.0**
**使用框架: React**

### 复现步骤
我也不知道是Taro问题，还是支付宝开发工具的问题（因为当前版本是最新升级的，旧版本可能不存在问题，未测试）。
写在这里，只是给大家提个醒，遇到这问题该怎么解决。

昨天打开支付宝小程序提示以后全部转向基础库2.0，并且开发工具提示升级。升级后遇到问题了，报以下错误：
Failed to compile
Module build failed (from /snapshot/code-repo/out/target/bundle/node_modules/@ali/antcube-thread-loader/lib/cjs.js):
Thread Loader (Worker 0)
@import pre compile failed: 
  => actual: 
 => expect: ./common.acss

    at /snapshot/code-repo/out/target/bundle/node_modules/@ali/antcube-appx-style-compiler/lib/process.js:89:31
    at step (/snapshot/code-repo/out/target/bundle/node_modules/@ali/antcube-appx-style-compiler/lib/process.js:33:23)
    at Object.next (/snapshot/code-repo/out/target/bundle/node_modules/@ali/antcube-appx-style-compiler/lib/process.js:14:53)
    at fulfilled (/snapshot/code-repo/out/target/bundle/node_modules/@ali/antcube-appx-style-compiler/lib/process.js:5:58)

因为小程序版本之前是可用的，把改动恢复后也是不行的，怀疑是小程序开发工具的问题。重新安装老版本小程序工具前，做了以下操作，竟然编译通过了。
打开/dist/app.acss, 在最后的 @import "./common.acss"; 前加一个换行，问题解决。

### 期望结果
正常运行

### 实际结果
编译报错

### 环境信息
```
👽 Taro v3.5.4


  Taro CLI 3.5.4 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.4 => 3.5.4 
      @tarojs/components: 3.5.4 => 3.5.4 
      @tarojs/helper: 3.5.4 => 3.5.4 
      @tarojs/plugin-framework-react: 3.5.4 => 3.5.4 
      @tarojs/plugin-platform-alipay: 3.5.4 => 3.5.4 
      @tarojs/plugin-platform-jd: 3.5.4 => 3.5.4 
      @tarojs/plugin-platform-qq: 3.5.4 => 3.5.4 
      @tarojs/plugin-platform-swan: 3.5.4 => 3.5.4 
      @tarojs/plugin-platform-tt: 3.5.4 => 3.5.4 
      @tarojs/plugin-platform-weapp: 3.5.4 => 3.5.4 
      @tarojs/react: 3.5.4 => 3.5.4 
      @tarojs/router: 3.5.4 => 3.5.4 
      @tarojs/runtime: 3.5.4 => 3.5.4 
      @tarojs/shared: 3.5.4 => 3.5.4 
      @tarojs/taro: 3.5.4 => 3.5.4 
      @tarojs/taro-h5: 3.5.4 => 3.5.4 
      @tarojs/webpack5-runner: 3.5.4 => 3.5.4 
      babel-preset-taro: 3.5.4 => 3.5.4 
      eslint-config-taro: 3.5.4 => 3.5.4 
      react: ^18.0.0 => 18.2.0 
      taro-ui: ^3.1.0-beta.2 => 3.1.0-beta.2 
```

**Comment by feibi** [comment]
#12522

**Comment by chenxinbin** [comment]
> 

是的，是同一个问题

**Comment by chenxinbin** [comment]
> #12522
是的，是同一个问题

**Comment by JunVincetHuo** [comment]
+ 1
