### ISSUE TITLE
Taro3.5.5拉取任意模板，在yarn dev:alipay的时候正常，但是在支付宝开发工具上就一直报错

### ISSUE THREAD

**Issue by 18201492717** [NervJS/taro#12554]
### 相关平台
支付宝小程序

**小程序基础库: 2.0版本及其他版本**
**使用框架: React**

### 复现步骤
终端打开项目文件，启动之后，开发工具编译报错

### 期望结果
能在开发工具正常调试，即开发工具能正常展示页面

### 实际结果
开发工具报错，日志如下
Starting dev server...
[build] version: 0.65.6

Error: ENOENT: no such file or directory, open '/Users/Luchifer/Desktop/mini/project-mini/app.json'
    at Object.openSync (fs.js:462:3)
    at Object.fs.openSync (pkg/prelude/bootstrap.js:503:32)
    at Object.readFileSync (fs.js:364:35)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:711:36)
    at e.initPersistedProperty (/snapshot/code-repo/out/target/bundle/node_modules/@ali/antcube-build/lib/build/option/option.js:1:45141)
    at new e (/snapshot/code-repo/out/target/bundle/node_modules/@ali/antcube-build/lib/build/option/option.js:1:2055)
    at getOptionFromCommand (/snapshot/code-repo/out/target/bundle/node_modules/@ali/antcube-build/lib/build/option/index.js:1:287)
    at i.createOptionsFromCommand (/snapshot/code-repo/out/target/bundle/node_modules/@ali/antcube-build/lib/bootstrap/builder.js:1:3817)
    at i.<anonymous> (/snapshot/code-repo/out/target/bundle/node_modules/@ali/antcube-build/lib/bootstrap/builder.js:1:1447)
    at step (/snapshot/code-repo/out/target/bundle/node_modules/tslib/tslib.js:144:27) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/Luchifer/Desktop/mini/project-mini/app.json'
}

Dev server exited unexpectedly with code 1

Please try to restart by clicking 'Restart'

### 环境信息
```
👽 Taro v3.5.5


  Taro CLI 3.5.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.20.0/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.5 => 3.5.5 
      @tarojs/components: 3.5.5 => 3.5.5 
      @tarojs/helper: 3.5.5 => 3.5.5 
      @tarojs/plugin-framework-react: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-alipay: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-jd: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-qq: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-swan: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-tt: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-weapp: 3.5.5 => 3.5.5 
      @tarojs/react: 3.5.5 => 3.5.5 
      @tarojs/router: 3.5.5 => 3.5.5 
      @tarojs/runtime: 3.5.5 => 3.5.5 
      @tarojs/shared: 3.5.5 => 3.5.5 
      @tarojs/taro: 3.5.5 => 3.5.5 
      @tarojs/taro-h5: 3.5.5 => 3.5.5 
      @tarojs/webpack5-runner: 3.5.5 => 3.5.5 
      babel-preset-taro: 3.5.5 => 3.5.5 
      eslint-config-taro: 3.5.5 => 3.5.5 
      react: ^18.0.0 => 18.2.0 
```

---
### 补充信息
node版本为14.20.0，用12.0.0依旧报错

**Comment by TheKonka** [comment]
> node版本为14.20.0，用12.0.0依旧报错

问题暂且不说，别人都是升级node ,为什么您选择降级🤔️

**Comment by 18201492717** [comment]
> > node版本为14.20.0，用12.0.0依旧报错
> 
> 问题暂且不说，别人都是升级node ,为什么您选择降级🤔️

老项目遇到过  而且正好有这两个版本就试了下

**Comment by hear-tide** [comment]
解决了吗？
