### ISSUE TITLE
导入一个官网推荐的抽奖插件报错 Module parse failed: Unexpected token 

### ISSUE THREAD

**Issue by HZZformGD** [NervJS/taro#12565]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/buuing/lucky-canvas/files/9621199/mini-react.zip](https://github.com/buuing/lucky-canvas/files/9621199/mini-react.zip)
**小程序基础库: 2.26.1**
**使用框架: React**

### 复现步骤
taro版本是3.5.5   在小程序环境下 只要引入该插件 dev:weapp 就报错  /lucky-canvas/issues 在h5下又可以正常编译
```code
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^
{
  moduleIdentifier: '/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/.taro/weapp/prebundle/index-984fd9e7.css',
  moduleName: './node_modules/.taro/weapp/prebundle/index-984fd9e7.css',
  loc: '1:0',
  message: 'Module parse failed: Unexpected token (1:0)\n' +
    'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
    '> .lucky-box {\n' +
    '|   position: relative;\n' +
    '|   overflow: hidden;',
  moduleId: './node_modules/.taro/weapp/prebundle/index-984fd9e7.css',
  moduleTrace: [
    {
      originIdentifier: '/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/.taro/weapp/prebundle/@lucky-canvas_taro_react.js',
      originName: './node_modules/.taro/weapp/prebundle/@lucky-canvas_taro_react.js',
      moduleIdentifier: '/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/.taro/weapp/prebundle/index-984fd9e7.css',
      moduleName: './node_modules/.taro/weapp/prebundle/index-984fd9e7.css',
      dependencies: [
        { loc: '1790:0-30' },
        { loc: '2020:0-30' },
        { loc: '2279:0-30' }
      ],
      originId: './node_modules/.taro/weapp/prebundle/@lucky-canvas_taro_react.js',
      moduleId: './node_modules/.taro/weapp/prebundle/index-984fd9e7.css'
    },
    {
      originIdentifier: 'container entry (default) [["./react",{"import":["/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/.taro/weapp/prebundle/react.js"]}],["./@lucky-canvas/taro/react",{"import":["/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/.taro/weapp/prebundle/@lucky-canvas_taro_react.js"]}],["./@tarojs/taro",{"import":["/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/.taro/weapp/prebundle/@tarojs_taro.js"]}],["./taro-hooks",{"import":["/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/.taro/weapp/prebundle/taro-hooks.js"]}],["./@prequest/miniprogram",{"import":["/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/.taro/weapp/prebundle/@prequest_miniprogram.js"]}],["./@prequest/lock",{"import":["/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/.taro/weapp/prebundle/@prequest_lock.js"]}],["./react/jsx-runtime",{"import":["/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/.taro/weapp/prebundle/react_jsx-runtime.js"]}],["./@tarojs/runtime",{"import":["/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/.taro/weapp/prebundle/@tarojs_runtime.js"]}],["./@tarojs/plugin-framework-react/dist/runtime",{"import":["/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/.taro/weapp/prebundle/@tarojs_plugin-framework-react_dist_runtime.js"]}],["./@tarojs/plugin-platform-weapp/dist/runtime",{"import":["/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/.taro/weapp/prebundle/@tarojs_plugin-platform-weapp_dist_runtime.js"]}],["./@tarojs/plugin-html/dist/runtime",{"import":["/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/.taro/weapp/prebundle/@tarojs_plugin-html_dist_runtime.js"]}],["./react-dom",{"import":["/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/.taro/weapp/prebundle/react-dom.js"]}]]',
      originName: 'container entry',
      moduleIdentifier: '/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/.taro/weapp/prebundle/@lucky-canvas_taro_react.js',
      moduleName: './node_modules/.taro/weapp/prebundle/@lucky-canvas_taro_react.js',
      dependencies: [ { loc: './@lucky-canvas/taro/react[0]' } ],
      originId: 'webpack/container/entry/taro_app_library',
      moduleId: './node_modules/.taro/weapp/prebundle/@lucky-canvas_taro_react.js'
    }
  ],
  details: undefined,
  stack: 'ModuleParseError: Module parse failed: Unexpected token (1:0)\n' +
    'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
    '> .lucky-box {\n' +
    '|   position: relative;\n' +
    '|   overflow: hidden;\n' +
    '    at handleParseError (/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/webpack/lib/NormalModule.js:971:19)\n' +
    '    at /home/hzz/side_hustle/mini/shipai-mini-react/node_modules/webpack/lib/NormalModule.js:1090:5\n' +
    '    at processResult (/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/webpack/lib/NormalModule.js:795:11)\n' +
    '    at /home/hzz/side_hustle/mini/shipai-mini-react/node_modules/webpack/lib/NormalModule.js:855:5\n' +
    '    at /home/hzz/side_hustle/mini/shipai-mini-react/node_modules/loader-runner/lib/LoaderRunner.js:407:3\n' +
    '    at iterateNormalLoaders (/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/loader-runner/lib/LoaderRunner.js:233:10)\n' +
    '    at /home/hzz/side_hustle/mini/shipai-mini-react/node_modules/loader-runner/lib/LoaderRunner.js:224:4\n' +
    '    at /home/hzz/side_hustle/mini/shipai-mini-react/node_modules/webpack/lib/NormalModule.js:829:15\n' +
    '    at Array.eval (eval at create (/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)\n' +
    '    at runCallbacks (/home/hzz/side_hustle/mini/shipai-mini-react/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:27:15)'
}
```

### 期望结果
正常使用

### 实际结果
正常使用

### 环境信息
```
Taro CLI 3.5.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.19 - ~/.local/share/pnpm/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.5 => 3.5.5 
      @tarojs/components: 3.5.5 => 3.5.5 
      @tarojs/helper: 3.5.5 => 3.5.5 
      @tarojs/plugin-framework-react: 3.5.5 => 3.5.5 
      @tarojs/plugin-html: ^3.5.5 => 3.5.5 
      @tarojs/plugin-platform-alipay: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-jd: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-qq: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-swan: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-tt: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-weapp: 3.5.5 => 3.5.5 
      @tarojs/react: 3.5.5 => 3.5.5 
      @tarojs/router: 3.5.5 => 3.5.5 
      @tarojs/runtime: 3.5.5 => 3.5.5 
      @tarojs/shared: 3.5.5 => 3.5.5 
      @tarojs/taro: 3.5.5 => 3.5.5 
      @tarojs/taro-h5: 3.5.5 => 3.5.5 
      @tarojs/webpack5-runner: 3.5.5 => 3.5.5 
      babel-preset-taro: 3.5.5 => 3.5.5 
      eslint-config-taro: 3.5.5 => 3.5.5 
      react: ^18.0.0 => 18.2.0 
```

**Comment by HZZformGD** [comment]
@Chen-jj  排查了好久 不知道啥问题 看起来好像是css加载的问题

**Comment by Chen-jj** [comment]
@HZZformGD `@lucky-canvas/taro/react` 这个包带有样式的 import 语句，但 webpack5 的 prebundle 功能不会编译 css 等资源文件，因此会造成报错。

你可以配置不预编译这个包：

```js
const config = {
  compiler: {
    type: 'webpack5',
    prebundle: {
      exclude: ['@lucky-canvas/taro/react']
    }
  },
  // ...
}
```

或者干脆关闭预编译功能：

```js
const config = {
  compiler: {
    type: 'webpack5',
    prebundle: {
      enable: false
    }
  },
  // ...
}
```

**Comment by Chen-jj** [comment]
@ZakaryCode 或许给预编译的 webpack 添加对静态资源的 external 配置，或为静态资源编写一个空 loader 并提示，会比目前直接暴露 webpack 的报错更加友好。

**Comment by ZakaryCode** [comment]
> @ZakaryCode 或许给预编译的 webpack 添加对静态资源的 external 配置，或为静态资源编写一个空 loader 并提示，会比目前直接暴露 webpack 的报错更加友好。

当前问题更多还是不支持的 css 语法导致的，直接提示排除依赖会导致更多本来可以使用的开发者体验下降。另外 external 也会有导致更多问题，或许考虑 remote 应用打包时继承 webpack 配置处理体验会更好一些。
