### ISSUE TITLE
taro1.2.0-beta.3 css modules 报错:  Cannot read property 'exports' of undefined

### ISSUE THREAD

**Issue by loveonelong** [NervJS/taro#1257]
**问题描述**
测试了一波新鲜出炉的css modules，发现控制台报错：

Cannot read property 'exports' of undefined.

**复现步骤**
使用taro1.2.0-beta.3 生成一个新项目，然后将pages/index中的import './index.scss/' 修改为 import styles from './index.scss/'

在index.scss中写入一个.base{ color: #000;},并在index中使用<View className={styles.base} /> 的方式使用

**报错信息**

```shell
生成  替换代码  为文件 /data/work/myApp/src/pages/index/index.js 生成 css modules
错误  页面编译  页面/data/work/myApp/src/pages/index/index编译失败！
TypeError: Cannot read property 'exports' of undefined
    at ImportDeclaration (/usr/local/lib/node_modules/@tarojs/cli/src/weapp.js:432:36)
    at NodePath._call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:150:16)
```

**系统信息**

 - mac os
 - v1.2.0-beta.3
 - Node.js 10
 - weapp

**Comment by luckyadam** [comment]
因为没有配置开启，默认是关的
`config/index.js` 里，`weapp.module.postcss` 下增加这个配置

```
cssModules: {
    enable: true,  // 默认为 false
    config: {
      generateScopedName: '[name]__[local]___[hash:base64:5]'
    }
  }
```

**Comment by loveonelong** [comment]
@luckyadam 嗯，多谢了。我体验了一下，我觉得当前的规整不太友好。看了一下#933的讨论。我也觉得按照`create-react-app` 的方案来更好。 https://github.com/NervJS/taro/pull/933#issuecomment-435396880

**Comment by loveonelong** [comment]
@luckyadam 我新建了一个issues来讨论这个问题 #1266
