### ISSUE TITLE
升级3.5.7，preact h5 dev build报错不能正常编译

### ISSUE THREAD

**Issue by xiaof520** [NervJS/taro#12693]
### 相关平台
H5

**浏览器版本: Chrome 62**
**使用框架: React**

### 复现步骤
npm run build:h5 -- --watch

### 期望结果
正常编译

### 实际结果
报错

### 环境信息
```
Taro v3.5.7


  Taro CLI 3.5.7 environment info:
    System:
      OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
      Shell: 5.1.4 - /bin/bash
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.7 => 3.5.7 
      @tarojs/components: 3.5.7 => 3.5.7 
      @tarojs/helper: 3.5.7 => 3.5.7 
      @tarojs/plugin-framework-react: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-alipay: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-jd: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-qq: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-swan: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-tt: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-weapp: 3.5.7 => 3.5.7 
      @tarojs/router: 3.5.7 => 3.5.7 
      @tarojs/runtime: 3.5.7 => 3.5.7 
      @tarojs/shared: 3.5.7 => 3.5.7 
      @tarojs/taro: 3.5.7 => 3.5.7 
      @tarojs/taro-h5: 3.5.7 => 3.5.7 
      @tarojs/webpack5-runner: 3.5.7 => 3.5.7 
      babel-preset-taro: 3.5.7 => 3.5.7 
      eslint-config-taro: 3.5.7 => 3.5.7 
      taro-ui: ^3.1.0-beta.2 => 3.1.0-beta.4 
```

---
### 补充信息
TypeError: Cannot read properties of undefined (reading 'isSimple')
    at push../node_modules/.taro/h5/prebundle/chunk-QVO5NZLW.js.options.diffed (vendors-node_modules_taro_h5_prebundle_chunk-QVO5NZLW_js.js:676:53)
    at push../node_modules/.taro/h5/prebundle/chunk-33PHITKG.js._chunk_LVLOPZ53_js__WEBPACK_IMPORTED_MODULE_0__.l.diffed (vendors-node_modules_taro_h5_prebundle_chunk-33PHITKG_js.js:187:10)
    at j (vendors-node_modules_taro_h5_prebundle_chunk-LVLOPZ53_js.js:213:28)
    at w (vendors-node_modules_taro_h5_prebundle_chunk-LVLOPZ53_js.js:127:9)
    at L (vendors-node_modules_taro_h5_prebundle_chunk-LVLOPZ53_js.js:248:42)
    at j (vendors-node_modules_taro_h5_prebundle_chunk-LVLOPZ53_js.js:212:96)
    at w (vendors-node_modules_taro_h5_prebundle_chunk-LVLOPZ53_js.js:127:9)
    at j (vendors-node_modules_taro_h5_prebundle_chunk-LVLOPZ53_js.js:209:269)
    at w (vendors-node_modules_taro_h5_prebundle_chunk-LVLOPZ53_js.js:127:9)
    at j (vendors-node_modules_taro_h5_prebundle_chunk-LVLOPZ53_js.js:209:269)

**Comment by ZakaryCode** [comment]
https://github.com/NervJS/taro/issues/12685#issuecomment-1284985910

可以先试试这样能否编译成功

**Comment by xiaof520** [comment]
上面方法试过不能，，
后来在plugin-framework-react   runtime.js  options.diffed里

if (propValue === false && dom.props[propName] === undefined) {
改
if (propValue === false && dom.props?.[propName] === undefined) {

可以了~

**Comment by ZakaryCode** [comment]
> 上面方法试过不能，， 后来在plugin-framework-react runtime.js options.diffed里
> 
> if (propValue === false && dom.props[propName] === undefined) { 改 if (propValue === false && dom.props?.[propName] === undefined) {
> 
> 可以了~

欢迎 PR
