### ISSUE TITLE
关于 linaria 使用问题

### ISSUE THREAD

**Issue by Howie126313** [NervJS/taro#12703]
### 相关平台
H5

### 复现仓库
[https://github.com/Howie126313/taro-linaria-](https://github.com/Howie126313/taro-linaria-)
**浏览器版本: chrome 106**
**使用框架: React**

### 复现步骤
```
$ yarn dev:h5

ERROR in ./src/pages/index/test.tsx
Module build failed (from ./node_modules/@linaria/webpack-loader/lib/index.js):
Error: [BABEL] /Users/bryan/Desktop/myApp/src/pages/index/test.tsx: .key is not a valid Plugin property
    at forEach (/Users/bryan/Desktop/myApp/node_modules/@linaria/shaker/node_modules/@babel/core/src/config/validation/plugins.ts:112:42)
    at Array.forEach (<anonymous>)
    at validatePluginObject (/Users/bryan/Desktop/myApp/node_modules/@linaria/shaker/node_modules/@babel/core/src/config/validation/plugins.ts:101:20)
    at /Users/bryan/Desktop/myApp/node_modules/@linaria/shaker/node_modules/@babel/core/src/config/full.ts:358:21
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/Users/bryan/Desktop/myApp/node_modules/@linaria/shaker/node_modules/@babel/core/src/gensync-utils/async.ts:10:3)
    at Generator.next (<anonymous>)
    at evaluateSync (/Users/bryan/Desktop/myApp/node_modules/gensync/index.js:251:28)
    at Function.sync (/Users/bryan/Desktop/myApp/node_modules/gensync/index.js:89:14)
    at sync (/Users/bryan/Desktop/myApp/node_modules/@linaria/shaker/node_modules/@babel/core/src/gensync-utils/async.ts:83:25)
    at sync (/Users/bryan/Desktop/myApp/node_modules/gensync/index.js:182:19)
    at onFirstPause (/Users/bryan/Desktop/myApp/node_modules/gensync/index.js:210:24)
```

### 期望结果
成功启动

### 实际结果
报错无法使用

### 环境信息
```
👽 Taro v3.5.6


  Taro CLI 3.5.6 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.17.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.6 => 3.5.6 
      @tarojs/components: 3.5.6 => 3.5.6 
      @tarojs/helper: 3.5.6 => 3.5.6 
      @tarojs/plugin-framework-react: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-alipay: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-jd: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-qq: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-swan: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-tt: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-weapp: 3.5.6 => 3.5.6 
      @tarojs/react: 3.5.6 => 3.5.6 
      @tarojs/router: 3.5.6 => 3.5.6 
      @tarojs/runtime: 3.5.6 => 3.5.6 
      @tarojs/shared: 3.5.6 => 3.5.6 
      @tarojs/taro: 3.5.6 => 3.5.6 
      @tarojs/taro-h5: 3.5.6 => 3.5.6 
      @tarojs/webpack-runner: ^3.5.7 => 3.5.7 
      @tarojs/webpack5-runner: 3.5.6 => 3.5.6 
      babel-preset-taro: 3.5.6 => 3.5.6 
      eslint-config-taro: 3.5.6 => 3.5.6 
      react: ^18.0.0 => 18.2.0 
```

---
### 补充信息
看到 linaria 类似问题已修复，https://github.com/callstack/linaria/pull/1061

在其他项目上还报出其他错误，https://github.com/NervJS/taro/issues/12700

希望解决不要直接关闭

**Comment by guangzhenwang** [comment]
我遇到了同样的问题

**Comment by Howie126313** [comment]
> 我遇到了同样的问题

umm.... 又找到啥解决办法嘛~~

**Comment by githubCK** [comment]
项目紧急需要啊，求大佬解决~

**Comment by Howie126313** [comment]
把 linaria 相关的依赖更新后会解决上文中的报错，但是会出现 https://github.com/NervJS/taro/issues/12700 这个错误。原因应该是这个 https://github.com/callstack/linaria/issues/1063，去掉 react-refresh/babel 插件后报下面的错误，看上去没有什么好的结局方法。看大佬们了~
`ERROR in ./src/pages/index/test.tsx
Module build failed (from ./node_modules/@linaria/webpack5-loader/lib/index.js):
/Users/bryan/Desktop/myApp/node_modules/@linaria/babel-preset/lib/module.js:391
        throw new EvalError(`${e.message} in${callstack.join('\n| ')}\n`);
        ^

EvalError: Unexpected token 'export' in
| /Users/bryan/Desktop/myApp/node_modules/@tarojs/components/dist-h5/react/index.js
| /Users/bryan/Desktop/myApp/src/pages/index/test.tsx

    at forEach (/Users/bryan/Desktop/myApp/node_modules/@linaria/babel-preset/src/module.ts:475:15)
    at Array.forEach (<anonymous>)
    at Module.evaluate (/Users/bryan/Desktop/myApp/node_modules/@linaria/babel-preset/src/module.ts:437:10)
    at require.Object.assign.ensure (/Users/bryan/Desktop/myApp/node_modules/@linaria/babel-preset/src/module.ts:395:13)
    at /Users/bryan/Desktop/myApp/src/pages/index/test.tsx:3:19
    at /Users/bryan/Desktop/myApp/src/pages/index/test.tsx:10:3
    at Script.runInContext (node:vm:141:12)
    at forEach (/Users/bryan/Desktop/myApp/node_modules/@linaria/babel-preset/src/module.ts:460:16)
    at Array.forEach (<anonymous>)
    at Module.evaluate (/Users/bryan/Desktop/myApp/node_modules/@linaria/babel-preset/src/module.ts:437:10)
    at evaluate (/Users/bryan/Desktop/myApp/node_modules/@linaria/babel-preset/src/evaluators/index.ts:28:5)
    at evalStage (/Users/bryan/Desktop/myApp/node_modules/@linaria/babel-preset/src/transform-stages/2-eval.ts:32:21)
    at syncStages (/Users/bryan/Desktop/myApp/node_modules/@linaria/babel-preset/src/transform.ts:50:27)
    at transform (/Users/bryan/Desktop/myApp/node_modules/@linaria/babel-preset/src/transform.ts:200:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 @ ./src/pages/index/index.tsx 9:0-26 38:36-40
 @ ./src/app.config.ts 41:15-44`

**Comment by moseszhou** [comment]
> > 我遇到了同样的问题
> 
> umm.... 又找到啥解决办法嘛~~

你最终解决了么？有什么办法？

**Comment by SidneyLann** [comment]
无解

**Comment by guozih** [comment]
有解决了吗？有什么办法吗？

**Comment by ZakaryCode** [comment]
针对于所示示例存在以下问题：

1. 依赖版本偏低，可以将 Taro 升级到最新版本，webpack 升级到 5.78+，lenaria 可以提升至 v5+，loader 仅保留 wepback5 即可（linariaLoader 需要同步调整）
2. 冗余 process.env 配置，需要移除；缺失 index.scss 文件，可以移除或添加；
3. babel 配置冗余，需要移除 @babel/preset-env、@babel/preset-react 两项 presets 配置
4. linaria 与 react 热更新冲突，需要新增 overrideContext 配置来跳过该问题，这与 issue  https://github.com/NervJS/taro/issues/15075#issuecomment-1951877698 相同

**Comment by victorteokw** [comment]
目前最新版本的taro v3.6.24和最新的linaria无法一起用，效果无效。

**Comment by wiilsliang** [comment]
> 目前最新版本的taro v3.6.24和最新的linaria无法一起用，效果无效。

哥们你现在成功了吗
