### ISSUE TITLE
新建项目报错

### ISSUE THREAD

**Issue by BadKid90s** [NervJS/taro#12770]
### 相关平台
H5

**浏览器版本: 107.0.5304.87**
**使用框架: React**

### 复现步骤
npx @tarojs/cli init taro-app
cd taro-app
npm run dev:h5

### 期望结果
首页显示

### 实际结果
不显示

### 环境信息
```
Taro v3.5.7


  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.6.0 - C:\Program Files\nodejs\npm.CMD 
```

**Comment by robinv8** [comment]
```
Error: Cannot find module './dist/index.js'
Require stack:
- /Users/robin/Projects/taro/packages/taro-plugin-react/index.js
- /Users/robin/.config/yarn/global/node_modules/@tarojs/service/dist/utils/index.js
- /Users/robin/.config/yarn/global/node_modules/@tarojs/service/dist/Kernel.js
- /Users/robin/.config/yarn/global/node_modules/@tarojs/service/dist/index.js
- /Users/robin/.config/yarn/global/node_modules/@tarojs/service/index.js
- /Users/robin/.config/yarn/global/node_modules/@tarojs/cli/dist/cli.js
- /Users/robin/.config/yarn/global/node_modules/@tarojs/cli/bin/taro
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/robin/Projects/taro/packages/taro-plugin-react/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/Users/robin/.config/yarn/global/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/robin/Projects/taro/packages/taro-plugin-react/index.js',
```

**Comment by robinv8** [comment]
node 14、16 下均报错
```
runtime.js:39 Uncaught ReferenceError: $RefreshReg$ is not defined
    at eval (events.js?faa1:497:1)
    at ./node_modules/events/events.js (app.js:29:1)
    at __webpack_require__ (runtime.js:36:33)
    at fn (runtime.js:472:21)
    at eval (emitter.js?93e2:1:1)
    at ./node_modules/webpack/hot/emitter.js (app.js:213:1)
    at __webpack_require__ (runtime.js:36:33)
    at fn (runtime.js:472:21)
    at eval (reloadApp.js:2:80)
    at ./node_modules/webpack-dev-server/client/utils/reloadApp.js (app.js:192:1)
```

**Comment by BadKid90s** [comment]
解决了

**Comment by ZakaryCode** [comment]
Duplicate of #12685
