### ISSUE TITLE
升级3.5.10版本后出现swc相关编译报错

### ISSUE THREAD

**Issue by QingyunYang** [NervJS/taro#12975]
### 相关平台
微信小程序

**小程序基础库: 无**
**使用框架: React**

### 复现步骤
无

### 期望结果
能正常编译

### 实际结果
编译报错

### 环境信息
```
👽 Taro v3.5.10


  Taro CLI 3.5.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.18.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.2 - D:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
从模板初始化项目未复现该报错，无法提供复现demo

thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("D:\\company\\projects\\coding\\small-coupon-master\\src\\app.config.ts")'
Caused by:
    0: Failed to create plugin instance
    1: Error while importing "env"."__set_transform_plugin_core_pkg_diagnostics": unknown import. Expected Function(FunctionType { params: [I32, I32], results: [] })', crates\swc\src\plugin.rs:222:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("D:\\company\\projects\\coding\\small-coupon-master\\src\\app.config.ts")'
Caused by:
    0: Failed to create plugin instance
    1: Error while importing "env"."__set_transform_plugin_core_pkg_diagnostics": unknown import. Expected Function(FunctionType { params: [I32, I32], results: [] })
    at Compiler.transformSync (D:\company\projects\coding\small-coupon-master\node_modules\.pnpm\@swc core@1.2.224\node_modules\@swc\core\index.js:240:29)
    at Object.transformSync (D:\company\projects\coding\small-coupon-master\node_modules\.pnpm\@swc core@1.2.224\node_modules\@swc\core\index.js:347:21)
    at compile (D:\company\projects\coding\small-coupon-master\node_modules\.pnpm\@swc register@0.1.10_@swc core@1.2.224\node_modules\@swc\register\lib\node.js:76:22)
    at compileHook (D:\company\projects\coding\small-coupon-master\node_modules\.pnpm\@swc register@0.1.10_@swc core@1.2.224\node_modules\@swc\register\lib\node.js:91:16)
    at Module._compile (D:\company\projects\coding\small-coupon-master\node_modules\.pnpm\pirates@4.0.5\node_modules\pirates\lib\index.js:130:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Object.newLoader [as .ts] (D:\company\projects\coding\small-coupon-master\node_modules\.pnpm\pirates@4.0.5\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19) {
  code: 'GenericFailure'
}

**Comment by QingyunYang** [comment]
> @QingyunYang 目测是 swc 版本的问题，你现在还是 1.2.224，最新是 1.3.x。可以删除项目 lockfile 后重新安装依赖试试

依照上面方法，可以成功编译，感谢！

**Comment by lstrive-yn** [comment]
taro升级至3.5.10+版本后，mac+node:v14.x版本开发环境，同样编译错误，需要降级swc包版本为1.2.x， 可锁定包版本：
`
// package.json
...
"resolutions": {
      "@swc/core": "1.2.204"
},
...
`
重新安装依赖，dev 完美运行

**Comment by TomatoesMan** [comment]
依旧不行啊！总是找不到 app.config.ts
