### ISSUE TITLE
wepy 打包处理的dist目录，用Taro v1.2.0-beta.3版本执行convert命令时，会提示Cannot set property 'decorators' of undefined

### ISSUE THREAD

**Issue by kucy** [NervJS/taro#1297]
**问题描述**
执行taro convert命令失败

**复现步骤**
wepy 执行打包命令后
在dist目录执行 taro convert

[或者可以直接贴源代码，能贴文字就不要截图]

```js

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

TypeError: Cannot set property 'decorators' of undefined
    at CallExpression (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_taroize@1.2.0-beta.3@@tarojs/taroize/lib/src/script.js:61:42)
    at NodePath._call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:150:16)

**系统信息**

 - 操作系统: [mac]
 - Taro 版本 [Taro v1.2.0-beta.3 ]
 - Node.js 版本 [v8.0.0]
 - 报错平台 []

试了两个项目。都出现了这个错误

**Comment by yuche** [comment]
https://github.com/NervJS/taro/issues/955#issuecomment-433858692
