### ISSUE TITLE
支付宝小程序加载报错: CallMethod error Cannot read properties of undefined (reading 'unmount')

### ISSUE THREAD

**Issue by git-onepixel** [NervJS/taro#12984]
### 相关平台
支付宝小程序

**小程序基础库: 小程序基础库 2.0**
**使用框架: React**

### 复现步骤
1、npm i -g @tarojs/cli 升级到3.5.10
2、taro init myProject 创建项目
3、npm run build:alipay
4、使用支付宝小程序IDE预览（开启小程序基础库2.0构建）
5、预览页面白屏，没有回调 componentDidMount、componentDidShow， 控制台报如下错误：
[APPX][Page] pages/index/index/0 CallMethod error Cannot read properties of undefined (reading 'unmount')/TypeError: Cannot read properties of undefined (reading 'unmount')
    at Object.unmount (http://127.0.0.1:57965/index.worker.js?hash=b1ebba2b&from_service_worker=true&url=file%3A%2F%2F%2Findex.html&page=pages%2Findex%2Findex&appId=2019102968740796&chInfo=ch_scan&referrerInfo=%7B%7D&ap_framework_sceneId=1011&enablePolyfillWorker=true&ap_framework_sceneId=1011:3959:23)
    at Object.onUnload (http://127.0.0.1:57965/index.worker.js?hash=b1ebba2b&from_service_worker=true&url=file%3A%2F%2F%2Findex.html&page=pages%2Findex%2Findex&appId=2019102968740796&chInfo=ch_scan&referrerInfo=%7B%7D&ap_framework_sceneId=1011&enablePolyfillWorker=true&ap_framework_sceneId=1011:3602:69)
    at e.invokePublicMethod (lyra-resource://appx-ng/af-appx.worker.min.js:6:128248)
    at e.invokeLifeCycle (lyra-resource://appx-ng/af-appx.worker.min.js:6:127752)
    at e.performLifeHook (lyra-resource://appx-ng/af-appx.worker.min.js:6:138865)
    at m (lyra-resource://appx-ng/af-appx.worker.min.js:6:5198)
    at e.t.<computed> [as performLifeHook] (lyra-resource://appx-ng/af-appx.worker.min.js:6:43089)
    at e.setStateFromState (lyra-resource://appx-ng/af-appx.worker.min.js:6:140556)
    at e.setState (lyra-resource://appx-ng/af-appx.worker.min.js:6:138588)
    at e.onPageUnload (lyra-resource://appx-ng/af-appx.worker.min.js:6:138456) 

### 期望结果
能够正常预览页面

### 实际结果
页面白屏，js报错

### 环境信息
```
 Taro v3.5.10


  Taro CLI 3.5.10 environment info:
    System:
      OS: macOS 11.3.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.10 => 3.5.10 
      @tarojs/components: 3.5.10 => 3.5.10 
      @tarojs/helper: 3.5.10 => 3.5.10 
      @tarojs/mini-runner: 3.5.10 => 3.5.10 
      @tarojs/plugin-framework-react: 3.5.10 => 3.5.10 
      @tarojs/plugin-platform-alipay: 3.5.10 => 3.5.10 
      @tarojs/plugin-platform-jd: 3.5.10 => 3.5.10 
      @tarojs/plugin-platform-qq: 3.5.10 => 3.5.10 
      @tarojs/plugin-platform-swan: 3.5.10 => 3.5.10 
      @tarojs/plugin-platform-tt: 3.5.10 => 3.5.10 
      @tarojs/plugin-platform-weapp: 3.5.10 => 3.5.10 
      @tarojs/react: 3.5.10 => 3.5.10 
      @tarojs/router: 3.5.10 => 3.5.10 
      @tarojs/runtime: 3.5.10 => 3.5.10 
      @tarojs/shared: 3.5.10 => 3.5.10 
      @tarojs/taro: 3.5.10 => 3.5.10 
      @tarojs/taro-h5: 3.5.10 => 3.5.10 
      @tarojs/webpack-runner: 3.5.10 => 3.5.10 
      babel-preset-taro: 3.5.10 => 3.5.10 
      eslint-config-taro: 3.5.10 => 3.5.10 
      react: ^18.0.0 => 18.2.0 
```

**Comment by TheKonka** [comment]
webpack4? 试下 webpack5

**Comment by git-onepixel** [comment]
> webpack4? 试下 webpack5

试了下 webpack5 是好的，原因是什么呢？

**Comment by git-onepixel** [comment]
webpack 升级到5之后（taro: 3.5.6），Input组件在模拟器和真机上都渲染不出来，TextArea是可以的：

react tsx 代码：
`
 <Input type="number" placeholder='ssss' />
`
编译之后的axml: 
<img width="732" alt="image" src="https://user-images.githubusercontent.com/16113983/208013014-5a8673b0-19d5-4f4c-9dcd-3a84a8460790.png">

这种问题应该怎么排查？

**Comment by git-onepixel** [comment]
> 你前面不还是 `3.5.10`吗，怎么又变成 `3.5.6`了 没有遇到过`Input`渲染不出来的问题，把`@tarojs/cli` 和项目的依赖都升级到`3.5.10`看看

3.5.6是项目版本，3.5.10 是 bug demo， Input不渲染的问题是因为我们内部的taro扩展插件没有适配webpack5所致。

目前看下来，加载报错问题只在webpack4上有，webpack5 上没问题，如果你们不打算修，那就close issue 吧！

**Comment by Chen-jj** [comment]
@git-onepixel 感谢反馈，的确是 Webpack4 会出现的问题。

调查了一下，发现 Webpack4 会注入 `setImmediate` 的 polyfill，在 React 18 中会导致错误：

![image](https://user-images.githubusercontent.com/11807297/209513555-fcc3f124-d531-42d4-82ba-f33d5cd2e47f.png)

![image](https://user-images.githubusercontent.com/11807297/209514051-38b1ac3d-00cd-4f08-b308-bb66a2586784.png)

应该把 Webpack4 的 `setImmediate` polyfill 去掉即可。

**Comment by young-ren** [comment]
> @git-onepixel 感谢反馈，的确是 Webpack4 会出现的问题。
> 
> 调查了一下，发现 Webpack4 会注入 `setImmediate` 的 polyfill，在 React 18 中会导致错误：
> 
> ![image](https://user-images.githubusercontent.com/11807297/209513555-fcc3f124-d531-42d4-82ba-f33d5cd2e47f.png)
> 
> ![image](https://user-images.githubusercontent.com/11807297/209514051-38b1ac3d-00cd-4f08-b308-bb66a2586784.png)
> 
> 应该把 Webpack4 的 `setImmediate` polyfill 去掉即可。

我的taro版本是3.4.0 react 17.0,2 webpack4 目前也出现了这个问题（重新安装npm包之后）
