### ISSUE TITLE
缺少依赖ajv@"^6.9.1"

### ISSUE THREAD

**Issue by wegi8** [NervJS/taro#12996]
### 相关平台
微信小程序

**小程序基础库: 最新**
**使用框架: React**

### 复现步骤
3.4.5 => 3.5.8
const ajv = new Ajv({
            ^

TypeError: Ajv is not a constructor
    at Object.<anonymous> (/Users/ssa-user/Desktop/project/pmp-enterprise-wechat-web/node_modules/css-minimizer-webpack-plugin/node_modules/schema-utils/dist/validate.js:66:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .js] (/Users/ssa-user/Desktop/project/pmp-enterprise-wechat-web/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/ssa-user/Desktop/project/pmp-enterprise-wechat-web/node_modules/css-minimizer-webpack-plugin/node_modules/schema-utils/dist/index.js:6:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14) 

### 期望结果
执行成功

### 实际结果
报错const ajv = new Ajv({
            ^

TypeError: Ajv is not a constructor
    at Object.<anonymous> (/Users/ssa-user/Desktop/project/pmp-enterprise-wechat-web/node_modules/css-minimizer-webpack-plugin/node_modules/schema-utils/dist/validate.js:66:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .js] (/Users/ssa-user/Desktop/project/pmp-enterprise-wechat-web/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/ssa-user/Desktop/project/pmp-enterprise-wechat-web/node_modules/css-minimizer-webpack-plugin/node_modules/schema-utils/dist/index.js:6:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14) 

### 环境信息
```
  Taro CLI 3.5.2 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.12.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.8 => 3.5.8 
      @tarojs/components: 3.5.8 => 3.5.8 
      @tarojs/helper: 3.5.8 => 3.5.8 
      @tarojs/plugin-framework-react: 3.5.8 => 3.5.8 
      @tarojs/plugin-html: 3.5.8 => 3.5.8 
      @tarojs/plugin-platform-weapp: 3.5.8 => 3.5.8 
      @tarojs/react: 3.5.8 => 3.5.8 
      @tarojs/router: 3.5.8 => 3.5.8 
      @tarojs/runtime: 3.5.8 => 3.5.8 
      @tarojs/shared: 3.5.8 => 3.5.8 
      @tarojs/taro: 3.5.8 => 3.5.8 
      @tarojs/taro-h5: 3.5.8 => 3.5.8 
      babel-preset-taro: 3.5.8 => 3.5.8 
      eslint-config-taro: 3.5.8 => 3.5.8 
      react: ^18.0.0 => 18.2.0 


```

**Comment by wegi8** [comment]
安装后执行成功，但没有提PR(某个package下增加peerdenp)，期望尽快修复

**Comment by yoyo837** [comment]
`ls`一下看看

**Comment by wegi8** [comment]
"dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/components": "3.5.8",
    "@tarojs/helper": "3.5.8",
    "@tarojs/plugin-framework-react": "3.5.8",
    "@tarojs/plugin-html": "3.5.8",
    "@tarojs/plugin-platform-weapp": "3.5.8",
    "@tarojs/plugin-platform-weapp-qy": "^0.0.9",
    "@tarojs/react": "3.5.8",
    "@tarojs/router": "3.5.8",
    "@tarojs/runtime": "3.5.8",
    "@tarojs/shared": "3.5.8",
    "@tarojs/taro": "3.5.8",
    "@tarojs/taro-h5": "3.5.8",
    "async-validator": "^4.2.5",
    "jsencrypt-taro": "^1.0.0",
    "mobx": "6.6.1",
    "mobx-react": "7.5.2",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "taro-i18n": "^1.0.3"
  },
  "devDependencies": {
    "@antmjs/vantui": "^2.2.5",
    "@babel/core": "^7.8.0",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.5",
    "@tarojs/cli": "3.5.8",
    "@tarojs/webpack5-runner": "3.5.8",
    "@types/react": "^18.0.0",
    "@types/webpack-env": "^1.13.6",
    "@typescript-eslint/eslint-plugin": "^5.20.0",
    "@typescript-eslint/parser": "^5.20.0",
    "ajv": "^6.12.6",
    "babel-plugin-import": "^1.13.5",
    "babel-preset-taro": "3.5.8",
    "dayjs": "^1.11.5",
    "eslint": "^8.12.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-config-taro": "3.5.8",
    "eslint-import-resolver-typescript": "^3.5.0",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jsx-a11y": "^6.6.1",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "husky": "^8.0.1",
    "miniprogram-ci": "^1.8.35",
    "postcss": "^8.4.18",
    "prettier": "^2.7.1",
    "react-refresh": "^0.11.0",
    "stylelint": "^14.4.0",
    "typescript": "^4.1.0",
    "webpack": "5.69.0"
  },

**Comment by yoyo837** [comment]
`npm ls ajv`

**Comment by wegi8** [comment]
npm ls ajv
pmp@1.0.0 /Users/ssa-user/Desktop/project/pmp-enterprise-wechat-web
├─┬ @pmmmwh/react-refresh-webpack-plugin@0.5.10
│ ├─┬ schema-utils@3.1.1
│ │ ├─┬ ajv-keywords@3.5.2
│ │ │ └── ajv@6.12.6 deduped
│ │ └── ajv@6.12.6 deduped
│ └─┬ webpack-dev-server@4.7.4
│   ├─┬ schema-utils@4.0.0
│   │ ├─┬ ajv-formats@2.1.1
│   │ │ └── ajv@8.11.2 deduped
│   │ ├─┬ ajv-keywords@5.1.0
│   │ │ └── ajv@8.11.2 deduped
│   │ └── ajv@8.11.2
│   └─┬ webpack-dev-middleware@5.3.3
│     └─┬ schema-utils@4.0.0
│       ├─┬ ajv-formats@2.1.1
│       │ └── ajv@8.11.2 deduped
│       ├─┬ ajv-keywords@5.1.0
│       │ └── ajv@8.11.2 deduped
│       └── ajv@8.11.2
├─┬ @tarojs/cli@3.5.8
│ ├─┬ @tarojs/transformer-wx@2.2.10
│ │ └─┬ eslint@5.16.0
│ │   ├── ajv@6.12.6 deduped
│ │   └─┬ table@5.4.6
│ │     └── ajv@6.12.6 deduped
│ └─┬ request@2.88.2
│   └─┬ har-validator@5.1.5
│     └── ajv@6.12.6 deduped
├─┬ @tarojs/webpack5-runner@3.5.8
│ ├─┬ babel-loader@8.2.1
│ │ └─┬ schema-utils@2.7.1
│ │   └── ajv@6.12.6 deduped
│ ├─┬ copy-webpack-plugin@10.2.0
│ │ └─┬ schema-utils@4.0.0
│ │   ├─┬ ajv-formats@2.1.1
│ │   │ └── ajv@8.11.2 deduped
│ │   ├─┬ ajv-keywords@5.1.0
│ │   │ └── ajv@8.11.2 deduped
│ │   └── ajv@8.11.2
│ ├─┬ css-minimizer-webpack-plugin@3.4.1
│ │ └─┬ schema-utils@4.0.0
│ │   ├─┬ ajv-formats@2.1.1
│ │   │ └── ajv@8.11.2 deduped
│ │   ├─┬ ajv-keywords@5.1.0
│ │   │ └── ajv@8.11.2 deduped
│ │   └── ajv@8.11.2
│ ├─┬ file-loader@6.0.0
│ │ └─┬ schema-utils@2.7.1
│ │   └── ajv@6.12.6 deduped
│ ├─┬ mini-css-extract-plugin@2.4.6
│ │ └─┬ schema-utils@4.0.0
│ │   ├─┬ ajv-formats@2.1.1
│ │   │ └── ajv@8.11.2 deduped
│ │   ├─┬ ajv-keywords@5.1.0
│ │   │ └── ajv@8.11.2 deduped
│ │   └── ajv@8.11.2
│ └─┬ url-loader@4.1.0
│   └─┬ schema-utils@2.7.1
│     └── ajv@6.12.6 deduped
├── ajv@6.12.6
├─┬ eslint@8.29.0
│ ├─┬ @eslint/eslintrc@1.3.3
│ │ └── ajv@6.12.6 deduped
│ └── ajv@6.12.6 deduped
├─┬ miniprogram-ci@1.9.3
│ └─┬ cos-nodejs-sdk-v5@2.11.18
│   └─┬ conf@9.0.2
│     ├─┬ ajv-formats@1.6.1
│     │ └── ajv@7.2.4
│     └── ajv@7.2.4
└─┬ stylelint@14.16.0
  └─┬ table@6.8.1
    └── ajv@8.11.2

**Comment by wegi8** [comment]
所以我需要resolutions它么？像swc那样？

**Comment by yoyo837** [comment]
如果这能解决, 你先这样使用...

**Comment by wegi8** [comment]
it's worked
`"resolutions": {
    "ajv": "8.11.2",
    "@swc/core": "1.3.6"
  }`
