### ISSUE TITLE
微信小程序代码转taro报错- Container is falsy

### ISSUE THREAD

**Issue by chenrf** [NervJS/taro#1303]
**问题描述**
使用taro convert转换微信程序项目报错Container is falsy

**复现步骤**

```js
// 这里可以贴代码

**期望行为**

**报错信息**
ReferenceError: Container is falsy
    at NodePath._replaceWith (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\replacement.js:170:11)
    at NodePath.replaceWith (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\replacement.js:160:8)
    at transformLoop (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\taroize\lib\src\wxml.js:225:9)
    at JSXAttribute (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\taroize\lib\src\wxml.js:59:13)
    at NodePath._call (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitMultiple (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:103:17)
    at TraversalContext.visit (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:190:19)
    at Function.traverse.node (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\index.js:114:17)

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 ： Taro v1.2.0-beta.4
 - Node.js 版本：v8.2.1
 - 报错平台 :weapp

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

[floorDirector.zip](https://github.com/NervJS/taro/files/2628374/floorDirector.zip)

**Comment by lixsh8** [comment]
我也同样出现这个问题

**Comment by yuche** [comment]
@lixsh8 你得提供错误文件的源码以及使用的 taro 版本号
