### ISSUE TITLE
微信小程序代码转taro报类型错误

### ISSUE THREAD

**Issue by chenrf** [NervJS/taro#1304]
**问题描述**
微信小程序转taro报错

**复现步骤**

```js

**期望行为**

**报错信息**
错误  页面转换  bee/income.js
TypeError: Property argument of ReturnStatement expected node to be of a type ["Expression"] but instead got "JSXExpressionContainer"
    at Object.validate (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-types\lib\definitions\index.js:109:13)
    at Object.validate (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-types\lib\index.js:505:9)
    at NodePath._replaceWith (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\replacement.js:176:7)
    at NodePath.replaceWith (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\replacement.js:160:8)
    at exit (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\taroize\lib\src\wxml.js:116:30)
    at NodePath._call (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:117:8)
    at TraversalContext.visitQueue (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (C:\Users\chen\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\index.js:114:17)

**系统信息**

 - 操作系统: “Windows 10”
 - Taro 版本 ：“v1.2.0-beta.4”
 - Node.js 版本：“v8.2.1”
 - 报错平台 ：“weapp”

**补充信息**
[bee.zip](https://github.com/NervJS/taro/files/2628689/bee.zip)

**Comment by chenrf** [comment]
这个已经跟JS一起放到zip了

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/d2ffe319fa24e6aaac94a68355fc5a5f2747b4d5
