### ISSUE TITLE
手动引入 package.json 被识别为依赖文件导致原地复制报错

### ISSUE THREAD

**Issue by vimcaw** [NervJS/taro#1315]
**问题描述**
手动引入`package.json`被识别为依赖，导致`package.json`被原地复制导致编译报错

**复现步骤**
任何地方引入`package.json`即可复现，比如：

```js
import pkg from '../../../package.json'

console.log(pkg.version);
```

**期望行为**
不报错

在`fs.copySync`前判断 src 和 dest 是否相同，不同时才复制

**报错信息**
```bash
Error: Source and destination must not be the same.
    at Object.copySync (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\fs-extra\lib\copy-sync\copy-sync.js:30:27)
    at files.forEach.file (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\@tarojs\cli\src\weapp.js:863:10)
    at Array.forEach (<anonymous>)
    at copyFilesFromSrcToOutput (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\@tarojs\cli\src\weapp.js:843:9)
    at buildSinglePage (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\@tarojs\cli\src\weapp.js:1270:7)
    at <anonymous>
```
![image](https://user-images.githubusercontent.com/21964227/49279221-da1d0300-f4c1-11e8-83a6-b6d0fe414cb3.png)

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 v1.1.9
 - Node.js 版本 v8.11.4
 - 报错平台 weapp

**补充信息**

原因是在`taro-cli`下的`weapp.js`的`buildSinglePage`方法判断`package.json`为依赖，于是进行拷贝，但是拷贝的源路径和目标路径相同：
https://github.com/NervJS/taro/blob/master/packages/taro-cli/src/weapp.js#L1348

**Comment by luckyadam** [comment]
已解决 fe9fdca
