### ISSUE TITLE
插件依赖 "@tarojs/plugin-mini-ci" 加载失败

### ISSUE THREAD

**Issue by yangjisen** [NervJS/taro#13278]
### 相关平台
微信小程序

**小程序基础库: latest**
**使用框架: Vue 3**

### 复现步骤
D:\DocumentRoot\Taro>taro init nutui4
 Taro v3.6.1

Taro 即将创建一个新项目!
Need help? Go and open issue: https://tls.jd.com/taro-issue-helper

? 请输入项目介绍
? 请选择框架 Vue3
? 是否需要使用 TypeScript ？ No
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择编译工具 Webpack5
? 请选择包管理工具 yarn
? 请选择模板源 Github（最新）
√ 拉取远程模板仓库成功！
? 请选择模板 vue3-NutUI4（使用 NutUI4.0 的模板）

D:\DocumentRoot\Taro>cd nutui4
D:\DocumentRoot\Taro\nutui4>yarn add -D @tarojs/plugin-mini-ci

按照教程配置 https://taro-docs.jd.com/docs/plugin-mini-ci
```
const CIPluginOpt = {
  // 微信小程序
  weapp: {
    appid: 'xxx',
    privateKeyPath: 'private.key',
  }
}

plugins: ['@tarojs/plugin-html', ['@tarojs/plugin-mini-ci', CIPluginOpt]],
```

npm run dev:weapp

### 期望结果
正常无报错运行

### 实际结果
D:\DocumentRoot\Taro\nutui4>npm run dev:weapp

> nutui4@1.0.0 dev:weapp
> npm run build:weapp -- --watch

> nutui4@1.0.0 build:weapp
> taro build --type weapp --watch

👽 Taro v3.6.1

Error: Cannot find module 'jimp/es'
Require stack:
- D:\DocumentRoot\Taro\nutui4\node_modules\@tarojs\plugin-mini-ci\dist\utils\qrcode.js
- D:\DocumentRoot\Taro\nutui4\node_modules\@tarojs\plugin-mini-ci\dist\AlipayCI.js
- D:\DocumentRoot\Taro\nutui4\node_modules\@tarojs\plugin-mini-ci\dist\index.js
- D:\DocumentRoot\Taro\nutui4\node_modules\@tarojs\plugin-mini-ci\index.js
- D:\DocumentRoot\Taro\nutui4\node_modules\@tarojs\service\dist\utils\index.js
- D:\DocumentRoot\Taro\nutui4\node_modules\@tarojs\service\dist\Kernel.js
- D:\DocumentRoot\Taro\nutui4\node_modules\@tarojs\service\dist\index.js
- D:\DocumentRoot\Taro\nutui4\node_modules\@tarojs\service\index.js
- D:\DocumentRoot\Taro\nutui4\node_modules\@tarojs\cli\dist\cli.js
- D:\DocumentRoot\Taro\nutui4\node_modules\@tarojs\cli\bin\taro
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Function.Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (D:\DocumentRoot\Taro\nutui4\node_modules\@tarojs\plugin-mini-ci\src\utils\qrcode.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Object.newLoader [as .js] (D:\DocumentRoot\Taro\nutui4\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Function.Module._load (node:internal/modules/cjs/loader:930:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\DocumentRoot\\Taro\\nutui4\\node_modules\\@tarojs\\plugin-mini-ci\\dist\\utils\\qrcode.js',
    'D:\\DocumentRoot\\Taro\\nutui4\\node_modules\\@tarojs\\plugin-mini-ci\\dist\\AlipayCI.js',
    'D:\\DocumentRoot\\Taro\\nutui4\\node_modules\\@tarojs\\plugin-mini-ci\\dist\\index.js',
    'D:\\DocumentRoot\\Taro\\nutui4\\node_modules\\@tarojs\\plugin-mini-ci\\index.js',
    'D:\\DocumentRoot\\Taro\\nutui4\\node_modules\\@tarojs\\service\\dist\\utils\\index.js',
    'D:\\DocumentRoot\\Taro\\nutui4\\node_modules\\@tarojs\\service\\dist\\Kernel.js',
    'D:\\DocumentRoot\\Taro\\nutui4\\node_modules\\@tarojs\\service\\dist\\index.js',
    'D:\\DocumentRoot\\Taro\\nutui4\\node_modules\\@tarojs\\service\\index.js',
    'D:\\DocumentRoot\\Taro\\nutui4\\node_modules\\@tarojs\\cli\\dist\\cli.js',
    'D:\\DocumentRoot\\Taro\\nutui4\\node_modules\\@tarojs\\cli\\bin\\taro'
  ]
}
D:\DocumentRoot\Taro\nutui4\node_modules\@tarojs\service\dist\utils\index.js:75
                    throw new Error(`插件依赖 "${item}" 加载失败，请检查插件配置`);
                          ^

Error: 插件依赖 "@tarojs/plugin-mini-ci" 加载失败，请检查插件配置
    at apply (D:\DocumentRoot\Taro\nutui4\node_modules\@tarojs\service\src\utils\index.ts:72:17)
    at Kernel.initPlugin (D:\DocumentRoot\Taro\nutui4\node_modules\@tarojs\service\src\Kernel.ts:157:5)
    at Kernel.resolvePlugins (D:\DocumentRoot\Taro\nutui4\node_modules\@tarojs\service\src\Kernel.ts:130:12)
    at Kernel.initPresetsAndPlugins (D:\DocumentRoot\Taro\nutui4\node_modules\@tarojs\service\src\Kernel.ts:115:10)
    at Kernel.<anonymous> (D:\DocumentRoot\Taro\nutui4\node_modules\@tarojs\service\src\Kernel.ts:312:10)
    at Generator.next (<anonymous>)
    at D:\DocumentRoot\Taro\nutui4\node_modules\@tarojs\service\dist\Kernel.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\DocumentRoot\Taro\nutui4\node_modules\@tarojs\service\dist\Kernel.js:4:12)
    at Kernel.run (D:\DocumentRoot\Taro\nutui4\node_modules\@tarojs\service\dist\Kernel.js:247:16)

Node.js v18.14.0

### 环境信息
```
👽 Taro v3.6.1


  Taro CLI 3.6.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 9.4.2 - C:\Program Files\nodejs\npm.CMD

```

**Comment by The-planet** [comment]
遇到了相同的问题

**Comment by bigmeow** [comment]
等 `3.6.2` 版本发布后再试试

**Comment by yangyankang** [comment]
> 
3.6.2大概什么时候会发布？

**Comment by bigmeow** [comment]
2周一个版本

临时解决办法：
package.json里，暂时锁死版本号

```json
  "resolutions": {
    "jimp": "0.16.1"
  }
```
