### ISSUE TITLE
微信小程序插件，taro build --plugin weapp 编译错误

### ISSUE THREAD

**Issue by DJDIDI** [NervJS/taro#13279]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/DJDIDI/weapp-plugin-taro3.6.1.git](https://github.com/DJDIDI/weapp-plugin-taro3.6.1.git)
**小程序基础库: 2.30.0**
**使用框架: React**

### 复现步骤
1.taro init
2.选择微信小程序插件模板 wxplugin（react ts less）
3.taro build --plugin weapp

### 期望结果
正常编译运行

### 实际结果
/node_modules/@tarojs/webpack5-runner/dist/plugins/MiniSplitChunksPlugin.js:487
            else if (Array.isArray(app.import)) {
                                       ^

TypeError: Cannot read properties of undefined (reading 'import')

### 环境信息
```
$ taro info 
👽 Taro v3.6.1


  Taro CLI 3.6.1 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.1 => 3.6.1 
      @tarojs/components: 3.6.1 => 3.6.1 
      @tarojs/helper: 3.6.1 => 3.6.1 
      @tarojs/plugin-framework-react: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-alipay: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-h5: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-jd: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-qq: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-swan: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-tt: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-weapp: 3.6.1 => 3.6.1 
      @tarojs/react: 3.6.1 => 3.6.1 
      @tarojs/runtime: 3.6.1 => 3.6.1 
      @tarojs/shared: 3.6.1 => 3.6.1 
      @tarojs/taro: 3.6.1 => 3.6.1 
      @tarojs/webpack5-runner: 3.6.1 => 3.6.1 
      babel-preset-taro: 3.6.1 => 3.6.1 
      eslint-config-taro: 3.6.1 => 3.6.1 
      react: ^18.0.0 => 18.2.0
```

**Comment by weiaiSanli** [comment]
如何修复呢？

**Comment by leifeng** [comment]
3.5.12也遇到了，解决了吗？

**Comment by wapchief** [comment]
taro init 选择模板的时候选择 webpack4

**Comment by DJDIDI** [comment]
> taro init 选择模板的时候选择 webpack4

可以临时解决，webpack5的模板有问题

**Comment by wapchief** [comment]
> 

但是我项目跑不起来，
运行
``
taro build --plugin weapp
``
又报了另一个错误
```
Error: Bindings not found
    at Compiler.transformSync (/Users/zacra/.config/yarn/global/node_modules/@swc/core/index.js:250:15)
    at Object.transformSync (/Users/zacra/.config/yarn/global/node_modules/@swc/core/index.js:348:21)
    at compile (/Users/zacra/.config/yarn/global/node_modules/@swc/register/lib/node.js:76:22)
    at compileHook (/Users/zacra/.config/yarn/global/node_modules/@swc/register/lib/node.js:91:16)
    at Module._compile (/Users/zacra/.config/yarn/global/node_modules/pirates/lib/index.js:130:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.newLoader [as .js] (/Users/zacra/.config/yarn/global/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

**Comment by wapchief** [comment]
我看他们在修复这个问题，不知道什么时候发布 https://github.com/NervJS/taro/pull/13527
