### ISSUE TITLE
obj.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by wise199403** [NervJS/taro#1333]
**问题描述**
当组件的某个 property 是通过 Object.create(null) 创建的时候，taro-weapp/src/util.js 中的 isEmptyObject 函数调用 obj.hasOwnProperty 报错。

**复现步骤**
``` js
componentWillMount() {
  const obj = Object.create(null)

  obj.bar = 'bar'
  this.props.foo = obj
}
```

**期望行为**
不报错

**报错信息**
```
obj.hasOwnProperty is not a function;at pages/index/index onReady function;at setTimeout callback function
TypeError: obj.hasOwnProperty is not a function
    at isEmptyObject (http://127.0.0.1:62754/appservice/npm/@tarojs/taro-weapp/dist/index.js:2780:13)
    at http://127.0.0.1:62754/appservice/npm/@tarojs/taro-weapp/dist/index.js:3579:13
    at Array.forEach (<anonymous>)
    at doUpdate (http://127.0.0.1:62754/appservice/npm/@tarojs/taro-weapp/dist/index.js:3571:26)
    at updateComponent (http://127.0.0.1:62754/appservice/npm/@tarojs/taro-weapp/dist/index.js:3548:5)
    at QueryComponent.forceUpdate (http://127.0.0.1:62754/appservice/npm/@tarojs/taro-weapp/dist/index.js:3762:7)
    at QueryComponent.value (http://127.0.0.1:62754/appservice/packages/taro-apollo/src/query-hoc.js:251:16)
    at Object.next (http://127.0.0.1:62754/appservice/packages/taro-apollo/src/query-hoc.js:210:38)
    at notifySubscription (http://127.0.0.1:62754/appservice/npm/zen-observable/lib/Observable.js:142:18)
    at onNotify (http://127.0.0.1:62754/appservice/npm/zen-observable/lib/Observable.js:177:3)
```

**系统信息**

 - 操作系统:  macOS
 - Taro 版本 v1.1.9
 - Node.js 版本 v11.1.0
 - 报错平台 weapp

**补充信息**
[taro-weapp/src/util.js](https://github.com/NervJS/taro/blob/a52fdc494ec94cfcde4b271b63576daff13b2e49/packages/taro-weapp/src/util.js#L8) 使用 `Object.prototype.hasOwnProperty.call` 判断对象是否含有某个属性

**Comment by wise199403** [comment]
在最小实现中不能复现该问题，暂时先关闭该 issue
