### ISSUE TITLE
taro 运行dev:h5，报这个错误failed to register unwind information: "unsupported unwind information"

### ISSUE THREAD

**Issue by jackvvv** [NervJS/taro#13398]
### 相关平台
H5

**浏览器版本: Chrome 110.0.5481.177**
**使用框架: React**

### 复现步骤
ERROR in ./src/app.config.js
Module build failed (from @tarojs/taro-loader/lib/h5):
Error: failed to handle: failed to register unwind information: "unsupported unwind information"
    at Compiler.transformSync (/Users/wmm/Developer/TestApp/com-luckyun-applet/node_modules/@swc/core/index.js:241:29)
    at Object.transformSync (/Users/wmm/Developer/TestApp/com-luckyun-applet/node_modules/@swc/core/index.js:348:21)
    at compile (/Users/wmm/Developer/TestApp/com-luckyun-applet/node_modules/@swc/register/lib/node.js:76:22)
    at compileHook (/Users/wmm/Developer/TestApp/com-luckyun-applet/node_modules/@swc/register/lib/node.js:91:16)
    at Module._compile (/Users/wmm/Developer/TestApp/com-luckyun-applet/node_modules/pirates/lib/index.js:130:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.newLoader [as .js] (/Users/wmm/Developer/TestApp/com-luckyun-applet/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)

### 期望结果
能正常调试h5

### 实际结果
启动调试h5失败

### 环境信息
```
Taro v3.6.1


  Taro CLI 3.6.1 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.1 => 3.6.1 
      @tarojs/components: 3.5.6 => 3.5.6 
      @tarojs/helper: 3.5.6 => 3.5.6 
      @tarojs/mini-runner: ^3.5.6 => 3.5.10 
      @tarojs/plugin-framework-react: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-alipay: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-h5: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-jd: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-qq: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-swan: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-tt: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-weapp: 3.5.6 => 3.5.6 
      @tarojs/react: 3.5.6 => 3.5.6 
      @tarojs/router: 3.5.6 => 3.5.6 
      @tarojs/runtime: 3.5.6 => 3.5.6 
      @tarojs/shared: 3.5.6 => 3.5.6 
      @tarojs/taro: 3.6.1 => 3.6.1 
      @tarojs/taro-h5: 3.5.6 => 3.5.6 
      @tarojs/webpack-runner: ^3.5.6 => 3.5.10 
      @tarojs/webpack5-runner: 3.5.6 => 3.5.6 
      babel-preset-taro: 3.5.6 => 3.5.6 
      eslint-config-taro: 3.5.6 => 3.5.6 
      react: ^18.2.0 => 18.2.0 
      taro-ui: ^3.1.0-beta.2 => 3.1.0-beta.4 
    npmGlobalPackages:
      typescript: 4.9.5

```

**Comment by ZakaryCode** [comment]
请先对齐依赖版本，并补充问题示例

**Comment by umcai** [comment]
这个我也遇到了，taro版本3.6.2，在windows下会复现，linux下正常。
查了一下是@swc/core版本太新的问题。

**Comment by umcai** [comment]
> 解决了吗？

安装1.3.3版本的@swc/core试试，我正常了。

**Comment by Chqqqqqqqqq** [comment]
> > 解决了吗？
> 
> 安装1.3.3版本的@swc/core测试，我正常了。

能说说如何给@swc/core降级吗？我新手，还不太懂。哈哈哈哈感谢！

**Comment by Chqqqqqqqqq** [comment]
> 

感谢！！！

**Comment by Chqqqqqqqqq** [comment]
> > > > 解决了吗？
> > > 
> > > 
> > > 安装1.3.3版本的@swc/core测试，我正常了。
> > 
> > 
> > 能说说怎么给@swc/core降级吗？我是新手，还不太懂。哈哈哈哈谢谢！
> 
> `npm install @swc/core@1.3.3 --save-dev`，安装在项目根目录的node_modules里即可。

谢谢！

**Comment by zhengzhou** [comment]
我的情况是要把.swc文件夹删除掉

**Comment by yoyo837** [comment]
请将 `.swc` 添加到 `.gitignore`
