### ISSUE TITLE
【Taro v3.5.12】编译到微信小程序平台，编译配置 copy.patterns , 原样拷贝 js文件 或 文件夹时，会报错

### ISSUE THREAD

**Issue by qiuxiyu** [NervJS/taro#13396]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/qiuxiyu/taro_issue_demo.git](https://github.com/qiuxiyu/taro_issue_demo.git)
**小程序基础库: 2.11.2**
**使用框架: React**

### 复现步骤
config/index.js 中，编译配置 copy.patterns ，原样拷贝【js文件】或 【文件夹】 到 dist 目录下，运行 npm run build:weapp 会报错

配置示例：
```
module.exports = {
  // ...
  copy: {
    patterns: [
      // 报错
      {
        from: 'src/pages/testCopy/',
        to: 'dist/weapp/pages/testCopy/'
      },

      // 报错
      // {
      //   from: 'src/pages/testCopy/index.js',
      //   to: 'dist/weapp/pages/testCopy/index.js'
      // },

      
      // 成功原样拷贝
      // {
      //   from: 'src/pages/testCopy/index.json',
      //   to: 'dist/weapp/pages/testCopy/index.json'
      // },
      
      // 成功原样拷贝
      // {
      //   from: 'src/pages/testCopy/index.wxml',
      //   to: 'dist/weapp/pages/testCopy/index.wxml'
      // },
    ]
  },
```

### 期望结果
能够按照配置内容，原样拷贝文件、文件夹

### 实际结果
运行 npm run build:weapp 时报错，错误信息：
```
node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

HookWebpackError: content.match is not a function
    at makeWebpackError (D:\test\ctaro\node_modules\webpack\lib\HookWebpackError.js:48:9)
    at D:\test\ctaro\node_modules\webpack\lib\Compilation.js:3058:12
    at eval (eval at create (D:\test\ctaro\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:82:1)
    at D:\test\ctaro\node_modules\webpack\lib\Compilation.js:509:26
    at TaroMiniPlugin.<anonymous> (D:\test\ctaro\node_modules\@tarojs\webpack5-runner\src\plugins\MiniPlugin.ts:146:9)
    at Generator.throw (<anonymous>)
    at rejected (D:\test\ctaro\node_modules\@tarojs\webpack5-runner\dist\plugins\MiniPlugin.js:6:65)
-- inner error --
TypeError: content.match is not a function
    at assets (D:\test\ctaro\plugins\replaceMiniAppPath.js:73:34)
    at Object.fn (D:\test\ctaro\plugins\replaceMiniAppPath.js:42:21)
    at Kernel.<anonymous> (D:\test\ctaro\node_modules\@tarojs\cli\node_modules\@tarojs\service\src\Kernel.ts:257:34)
    at Generator.next (<anonymous>)
    at D:\test\ctaro\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\test\ctaro\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:4:12)
    at D:\test\ctaro\node_modules\@tarojs\cli\node_modules\@tarojs\service\src\Kernel.ts:256:24
    at eval (eval at create (D:\test\ctaro\node_modules\tapable\lib\HookCodeFactory.js:74:10), <anonymous>:16:17)
    at new Promise (<anonymous>)
    at AsyncSeriesWaterfallHook.eval [as promise] (eval at create (D:\test\ctaro\node_modules\tapable\lib\HookCodeFactory.js:74:10), <anonymous>:4:8)
    at AsyncSeriesWaterfallHook.lazyCompileHook (D:\test\ctaro\node_modules\tapable\lib\Hook.js:154:20)
    at Kernel.<anonymous> (D:\test\ctaro\node_modules\@tarojs\cli\node_modules\@tarojs\service\src\Kernel.ts:269:28)
    at Generator.next (<anonymous>)
    at D:\test\ctaro\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\test\ctaro\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:4:12)
    at Kernel.applyPlugins (D:\test\ctaro\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:176:16)
    at D:\test\ctaro\node_modules\@tarojs\cli\dist\presets\commands\build.js:104:47
    at step (D:\test\ctaro\node_modules\@tarojs\cli\dist\presets\commands\build.js:87:23)
    at Object.next (D:\test\ctaro\node_modules\@tarojs\cli\dist\presets\commands\build.js:28:20)
    at D:\test\ctaro\node_modules\@tarojs\cli\dist\presets\commands\build.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\test\ctaro\node_modules\@tarojs\cli\dist\presets\commands\build.js:4:12)
    at modifyBuildAssets (D:\test\ctaro\node_modules\@tarojs\cli\dist\presets\commands\build.js:103:40)
    at TaroMiniPlugin.<anonymous> (D:\test\ctaro\node_modules\@tarojs\webpack5-runner\src\plugins\MiniPlugin.ts:1027:13)
    at Generator.next (<anonymous>)
    at fulfilled (D:\test\ctaro\node_modules\@tarojs\webpack5-runner\dist\plugins\MiniPlugin.js:5:58) {
  details: 'caused by plugins in Compilation.hooks.processAssets\n' +
    'TypeError: content.match is not a function\n' +
    '    at assets (D:\\test\\ctaro\\plugins\\replaceMiniAppPath.js:73:34)\n' +
    '    at Object.fn (D:\\test\\ctaro\\plugins\\replaceMiniAppPath.js:42:21)\n' +
    '    at Kernel.<anonymous> (D:\\test\\ctaro\\node_modules\\@tarojs\\cli\\node_modules\\@tarojs\\service\\src\\Kernel.ts:257:34)\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at D:\\test\\ctaro\\node_modules\\@tarojs\\cli\\node_modules\\@tarojs\\service\\dist\\Kernel.js:8:71\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at __awaiter (D:\\test\\ctaro\\node_modules\\@tarojs\\cli\\node_modules\\@tarojs\\service\\dist\\Kernel.js:4:12)\n' +
    '    at D:\\test\\ctaro\\node_modules\\@tarojs\\cli\\node_modules\\@tarojs\\service\\src\\Kernel.ts:256:24\n' +
    '    at eval (eval at create (D:\\test\\ctaro\\node_modules\\tapable\\lib\\HookCodeFactory.js:74:10), <anonymous>:16:17)\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at AsyncSeriesWaterfallHook.eval [as promise] (eval at create (D:\\test\\ctaro\\node_modules\\tapable\\lib\\HookCodeFactory.js:74:10), <anonymous>:4:8)\n' +
    '    at AsyncSeriesWaterfallHook.lazyCompileHook (D:\\test\\ctaro\\node_modules\\tapable\\lib\\Hook.js:154:20)\n' +
    '    at Kernel.<anonymous> (D:\\test\\ctaro\\node_modules\\@tarojs\\cli\\node_modules\\@tarojs\\service\\src\\Kernel.ts:269:28)\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at D:\\test\\ctaro\\node_modules\\@tarojs\\cli\\node_modules\\@tarojs\\service\\dist\\Kernel.js:8:71\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at __awaiter (D:\\test\\ctaro\\node_modules\\@tarojs\\cli\\node_modules\\@tarojs\\service\\dist\\Kernel.js:4:12)\n' +
    '    at Kernel.applyPlugins (D:\\test\\ctaro\\node_modules\\@tarojs\\cli\\node_modules\\@tarojs\\service\\dist\\Kernel.js:176:16)\n' +
    '    at D:\\test\\ctaro\\node_modules\\@tarojs\\cli\\dist\\presets\\commands\\build.js:104:47\n' +
    '    at step (D:\\test\\ctaro\\node_modules\\@tarojs\\cli\\dist\\presets\\commands\\build.js:87:23)\n' +
    '    at Object.next (D:\\test\\ctaro\\node_modules\\@tarojs\\cli\\dist\\presets\\commands\\build.js:28:20)\n' +
    '    at D:\\test\\ctaro\\node_modules\\@tarojs\\cli\\dist\\presets\\commands\\build.js:8:71\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at __awaiter (D:\\test\\ctaro\\node_modules\\@tarojs\\cli\\dist\\presets\\commands\\build.js:4:12)\n' +
    '    at modifyBuildAssets (D:\\test\\ctaro\\node_modules\\@tarojs\\cli\\dist\\presets\\commands\\build.js:103:40)\n' +
    '    at TaroMiniPlugin.<anonymous> (D:\\test\\ctaro\\node_modules\\@tarojs\\webpack5-runner\\src\\plugins\\MiniPlugin.ts:1027:13)\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at fulfilled (D:\\test\\ctaro\\node_modules\\@tarojs\\webpack5-runner\\dist\\plugins\\MiniPlugin.js:5:58)',
  module: undefined,
  loc: undefined,
  hideStack: true,
  chunk: undefined,
  file: undefined,
  hook: 'Compilation.hooks.processAssets',
  error: TypeError: content.match is not a function
      at assets (D:\test\ctaro\plugins\replaceMiniAppPath.js:73:34)
      at Object.fn (D:\test\ctaro\plugins\replaceMiniAppPath.js:42:21)
      at Kernel.<anonymous> (D:\test\ctaro\node_modules\@tarojs\cli\node_modules\@tarojs\service\src\Kernel.ts:257:34)
      at Generator.next (<anonymous>)
      at D:\test\ctaro\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (D:\test\ctaro\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:4:12)
      at D:\test\ctaro\node_modules\@tarojs\cli\node_modules\@tarojs\service\src\Kernel.ts:256:24
      at eval (eval at create (D:\test\ctaro\node_modules\tapable\lib\HookCodeFactory.js:74:10), <anonymous>:16:17)
      at new Promise (<anonymous>)
      at AsyncSeriesWaterfallHook.eval [as promise] (eval at create (D:\test\ctaro\node_modules\tapable\lib\HookCodeFactory.js:74:10), <anonymous>:4:8)
      at AsyncSeriesWaterfallHook.lazyCompileHook (D:\test\ctaro\node_modules\tapable\lib\Hook.js:154:20)
      at Kernel.<anonymous> (D:\test\ctaro\node_modules\@tarojs\cli\node_modules\@tarojs\service\src\Kernel.ts:269:28)
      at Generator.next (<anonymous>)
      at D:\test\ctaro\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (D:\test\ctaro\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:4:12)
      at Kernel.applyPlugins (D:\test\ctaro\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:176:16)
      at D:\test\ctaro\node_modules\@tarojs\cli\dist\presets\commands\build.js:104:47
      at step (D:\test\ctaro\node_modules\@tarojs\cli\dist\presets\commands\build.js:87:23)
      at Object.next (D:\test\ctaro\node_modules\@tarojs\cli\dist\presets\commands\build.js:28:20)
      at D:\test\ctaro\node_modules\@tarojs\cli\dist\presets\commands\build.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (D:\test\ctaro\node_modules\@tarojs\cli\dist\presets\commands\build.js:4:12)
      at modifyBuildAssets (D:\test\ctaro\node_modules\@tarojs\cli\dist\presets\commands\build.js:103:40)
      at TaroMiniPlugin.<anonymous> (D:\test\ctaro\node_modules\@tarojs\webpack5-runner\src\plugins\MiniPlugin.ts:1027:13)
      at Generator.next (<anonymous>)
      at fulfilled (D:\test\ctaro\node_modules\@tarojs\webpack5-runner\dist\plugins\MiniPlugin.js:5:58)
```

### 环境信息
```
👽 Taro v3.5.12


  Taro CLI 3.5.12 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
```

**Comment by qiuxiyu** [comment]
已解决，与Taro无关，我们内部插件报错
