### ISSUE TITLE
初始化项目后，运行npm run dev:weapp 后提示：defineAppConfig is not defined

### ISSUE THREAD

**Issue by kennybai** [NervJS/taro#13468]
### 相关平台
微信小程序

**小程序基础库: 无**
**使用框架: React**

### 复现步骤
无

### 期望结果
正常打包

### 实际结果
报错

### 环境信息
```

  Taro CLI 3.6.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.0 - E:\node\setup\node.EXE
      Yarn: 1.22.17 - C:\Users\Kenny\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.7 - E:\node\setup\npm.CMD
```

---
### 补充信息
ReferenceError: defineAppConfig is not defined
    at Object.<anonymous> (E:\web\Taro\myapp\src\app.config.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Object.newLoader [as .js] (E:\web\Taro\myapp\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at readConfig (E:\web\Taro\myapp\node_modules\@tarojs\helper\src\utils.ts:661:37)

**Comment by yoyo837** [comment]
配置文件发来看看

**Comment by kennybai** [comment]
// app.config.js
export default defineAppConfig({
  pages: [
    'pages/index/index'
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black'
  }
})

**Comment by kennybai** [comment]
> 配置文件发来看看

是app.config.js么，已经贴出来了

**Comment by TheKonka** [comment]
> > 配置文件发来看看
> 
> 是app.config.js么，已经贴出来了

defineAppConfig  是 typescript用的，要么把你项目改成 ts 的

**Comment by ZakaryCode** [comment]
请检查项目依赖，并保证使用 CLI 与项目内版本一致。

> 如果不需要对 app.config 的代码提示可以自行移除该函数
