### ISSUE TITLE
单步调测配置失败

### ISSUE THREAD

**Issue by GitVitality** [NervJS/taro#13546]
### 相关平台
微信小程序

**小程序基础库: 1.06.2303060**
**使用框架: React**

### 复现步骤
配置 launch.json
```
{
  // ...
  "configurations": [
    //...
    {
      // ...
      "cwd": "/Users/User/Desktop/test",
      "args": ["build", "--type", "weapp", "--watch"]
    }
  ]
}
```

### 期望结果
可以正常单不调试不报错

### 实际结果
单步调试后，有错误
```
Error: Bindings not found
    at Compiler.transformSync (/Users/xuyl/company/taro/node_modules/.pnpm/registry.npmjs.org @swc core@1.3.23/node_modules/@swc/core/index.js:250:15)
    at Object.transformSync (/Users/xuyl/company/taro/node_modules/.pnpm/registry.npmjs.org @swc core@1.3.23/node_modules/@swc/core/index.js:348:21)
    at compile (/Users/xuyl/company/taro/node_modules/.pnpm/registry.npmjs.org @swc register@0.1.10_@swc core@1.3.23/node_modules/@swc/register/lib/node.js:76:22)
    at compileHook (/Users/xuyl/company/taro/node_modules/.pnpm/registry.npmjs.org @swc register@0.1.10_@swc core@1.3.23/node_modules/@swc/register/lib/node.js:91:16)
    at Module._compile (/Users/xuyl/company/taro/node_modules/.pnpm/registry.npmjs.org pirates@4.0.5/node_modules/pirates/lib/index.js:130:29)
    at Module._extensions..js (<node_internals>/internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/Users/xuyl/company/taro/node_modules/.pnpm/registry.npmjs.org pirates@4.0.5/node_modules/pirates/lib/index.js:141:7)
    at Module.load (<node_internals>/internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (<node_internals>/internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {stack: 'Error: Bindings not found
    at Compiler.tra…quire (internal/modules/cjs/loader.js:974:19)', message: 'Bindings not found'}
(node:69878) UnhandledPromiseRejectionWarning: Error: 插件依赖 "/Users/xuyl/company/taro/packages/taro-cli/dist/presets/index.js" 加载失败，请检查插件配置
    at apply (/Users/xuyl/company/taro/packages/taro-service/dist/utils/index.js:76:27)
    at Kernel.initPreset (/Users/xuyl/company/taro/packages/taro-service/dist/Kernel.js:94:38)
    at Kernel.resolvePresets (/Users/xuyl/company/taro/packages/taro-service/dist/Kernel.js:79:18)
    at Kernel.initPresetsAndPlugins (/Users/xuyl/company/taro/packages/taro-service/dist/Kernel.js:73:14)
    at Kernel.<anonymous> (/Users/xuyl/company/taro/packages/taro-service/dist/Kernel.js:263:18)
    at Generator.next (<anonymous>)
    at /Users/xuyl/company/taro/packages/taro-service/dist/Kernel.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/xuyl/company/taro/packages/taro-service/dist/Kernel.js:4:12)
    at Kernel.run (/Users/xuyl/company/taro/packages/taro-service/dist/Kernel.js:247:16)
(Use `node --trace-warnings ...` to show where the warning was created)
```

### 环境信息
```
 Taro CLI 3.6.2 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    npmPackages:
      @tarojs/components: 3.3.19 => 3.3.19 
      @tarojs/mini-runner: 3.3.19 => 3.3.19 
      @tarojs/plugin-framework-react: ^3.6.2 => 3.6.2 
      @tarojs/react: 3.3.19 => 3.3.19 
      @tarojs/runtime: 3.3.19 => 3.3.19 
      @tarojs/taro: 3.3.19 => 3.3.19 
      @tarojs/webpack-runner: 3.3.19 => 3.3.19 
      babel-preset-taro: 3.3.19 => 3.3.19 
      eslint-config-taro: 3.3.19 => 3.3.19 
      react: ^17.0.0 => 17.0.2 

```

**Comment by TheKonka** [comment]
你的 taro 版本和项目版本不一致啊，可以尝试删除 .swc 再试下.. 或者保持版本一致

**Comment by Chen-jj** [comment]
Taro CLI 和 Taro 依赖版本保持一致后再试试

**Comment by bluescurry** [comment]
我把保持版本一致了，都是最新的 3.6.7 还是报这个错误

**Comment by bluescurry** [comment]
> > 
> 
> `npm ls` 每个`@tarojs/` 开头的包看看实际安装了什么版本

版本都是最新的 3.6.7

**Comment by bluescurry** [comment]
我之前是用的 iTerm2 安装的依赖，现在我把 node_modules 删除，用 vscode 内置的终端重新 install 了一遍。就可以了，具体原因是为啥。。。

**Comment by yoyo837** [comment]
最好保留lock文件跟着项目走, 团队里所有人都用同一个.

**Comment by bluescurry** [comment]
> 最好保留lock文件跟着项目走, 团队里所有人都用同一个.

你可能理解错了，我在调试的是 Taro 源码~ 重新装依赖是给 Taro 源码装的

**Comment by yoyo837** [comment]
那你是否用的pnpm, taro里的lock是pnpm

**Comment by bluescurry** [comment]
> 那你是否用的pnpm, taro里的lock是pnpm

是的，用的 pnpm
