### ISSUE TITLE
taro rn报错error index.js: Jest worker encountered 4 child process exceptions, exceeding retry limit.

### ISSUE THREAD

**Issue by Carry3** [NervJS/taro#13557]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
yarn build:rn --platform ios

### 期望结果
期望能够正确进行build

### 实际结果
error index.js: Jest worker encountered 4 child process exceptions, exceeding retry limit.
Error: Jest worker encountered 4 child process exceptions, exceeding retry limit
    at ChildProcessWorker.initialize (E:\Documents\36c-rn\node_modules\jest-worker\build\workers\ChildProcessWorker.js:185:21)
    at ChildProcessWorker._onExit (E:\Documents\36c-rn\node_modules\jest-worker\build\workers\ChildProcessWorker.js:269:12)
    at ChildProcess.emit (node:events:513:28)
info Run CLI with --verbose flag for more details.
Done in 139.15s.

### 环境信息
```
Taro CLI 3.6.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.17.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 8.15.0 - D:\Program Files\nodejs\npm.CMD

```

**Comment by mylvlin** [comment]
同样遇到这个问题 真是 一个环境搞几天 上午还是好的 下午更新一下依赖就跨丝，就不能锁定一个文档的版本么，还有expo-av的版本问题

**Comment by fgy888** [comment]
https://github.com/NervJS/taro/issues/11588#issuecomment-1091090510

**Comment by fgy888** [comment]
我是这样解决的：package.json 新增 https://github.com/NervJS/taro/issues/11588#issuecomment-1091090510
