### ISSUE TITLE
pnpm workspace，webpack5 dev:h5错误

### ISSUE THREAD

**Issue by xiaof520** [NervJS/taro#13600]
### 相关平台
H5

**浏览器版本: edge**
**使用框架: React**

### 复现步骤
https://github.com/xiaof520/pnpm.git
```
/node_modules/.pnpm/webpack@5.69.0_@swc core@1.3.42/node_modules/webpack/lib/util/hash/wasm-hash.js:108
                const length = data.length;
                      ^
TypeError: Cannot read properties of undefined (reading 'length')
```

### 期望结果
正常使用

### 实际结果
dev失败

### 环境信息
```
Taro v3.6.4


  Taro CLI 3.6.4 environment info:
    System:
      OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
      Shell: 5.1.4 - /bin/bash
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.4 => 3.6.4 
      @tarojs/components: 3.6.4 => 3.6.4 
      @tarojs/helper: 3.6.4 => 3.6.4 
      @tarojs/plugin-framework-react: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-alipay: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-h5: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-jd: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-qq: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-swan: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-tt: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-weapp: 3.6.4 => 3.6.4 
      @tarojs/runtime: 3.6.4 => 3.6.4 
      @tarojs/shared: 3.6.4 => 3.6.4 
      @tarojs/taro: 3.6.4 => 3.6.4 
      @tarojs/webpack5-runner: 3.6.4 => 3.6.4 
      babel-preset-taro: 3.6.4 => 3.6.4 
      eslint-config-taro: 3.6.4 => 3.6.4 
      taro-ui: ^3.1.0-beta.2 => 3.1.0-beta.2 
```

**Comment by xiaof520** [comment]
不使用workspace时正常的

**Comment by xiaof520** [comment]
webpack4报
```
Uncaught TypeError: _tarojs_taro__WEBPACK_IMPORTED_MODULE_4__.default.addInterceptor is not a function
    at eval (app.tsx?a4b6:20:1)
    at Array.forEach (<anonymous>)
    at eval (app.tsx?a4b6:20:1)
    at ./src/app.tsx (app.js:2033:1)
    at __webpack_require__ (app.js:85:30)
    at eval (app.config.ts?cf92:1:1)
    at ./src/app.config.ts (app.js:2021:1)
    at __webpack_require__ (app.js:85:30)
    at 0 (app.js:2079:18)
    at __webpack_require__ (app.js:85:30)
```

**Comment by xuanzebin** [comment]
使用 yarn 来安装依赖应该能暂时解决，pnpm 和 npm 的问题还在排查中~

**Comment by orzEric** [comment]
遇到相同的错误，微信小程序正常，h5失败，请问有什么处理办法吗

**Comment by hanwenbo** [comment]
小程序wath无效，h5报错： node_modules/webpack/lib/util/hash/wasm-hash.js:108
                const length = data.length;

**Comment by hanwenbo** [comment]
经测试发现，taro并不支持pnpm，在pnpm下很多bug，一步一个坑

**Comment by xiaof520** [comment]
> 经测试发现，taro并不支持pnpm，在pnpm下很多bug，一步一个坑

升级到3.6.5-alpha上面错误修复了

**Comment by xuanzebin** [comment]
Duplicate of #13568

**Comment by zhaojunf** [comment]
> > 经测试发现，taro并不支持pnpm，在pnpm下很多bug，一步一个坑
> 
> 升级到3.6.5-alpha上面错误修复了

是taro升级到3.6.5-alpha么

**Comment by liyunfei22** [comment]
使用npm 安装，npm run dev:h5报同样的错

**Comment by EtaJx** [comment]
3.6.2版本，同样
- 小程序wath无效
- h5报错：
```
 node_modules/webpack/lib/util/hash/wasm-hash.js:108
const length = data.length;
```

什么时候能修复鸭，要上线了，搞个这

**Comment by xieyezi** [comment]
> 3.6.2版本，同样
> 
> * 小程序wath无效
> * h5报错：
> 
> ```
>  node_modules/webpack/lib/util/hash/wasm-hash.js:108
> const length = data.length;
> ```
> 
> 什么时候能修复鸭，要上线了，搞个这

@EtaJx 解决了吗
