### ISSUE TITLE
taro3.6.4 init选择react-native模板报错

### ISSUE THREAD

**Issue by jingliangapp** [NervJS/taro#13612]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
taro init
? 请输入项目名称！ taroDemo
? 请输入项目介绍
? 请选择框架 React
? 是否需要使用 TypeScript ？ No
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择编译工具 Webpack5
? 请选择包管理工具 yarn
? 请选择模板源 Gitee（最快）
√ 拉取远程模板仓库成功！
? 请选择模板 react-native
D:\Yarn\global\node_modules\mem-fs-editor\node_modules\fast-glob\out\readers\reader.js:9
        this._fsStatSettings = new fsStat.Settings({
                               ^

TypeError: fsStat.Settings is not a constructor
    at new Reader (D:\Yarn\global\node_modules\mem-fs-editor\node_modules\fast-glob\out\readers\reader.js:9:32)
    at new ReaderSync (D:\Yarn\global\node_modules\mem-fs-editor\node_modules\fast-glob\out\readers\sync.js:8:9)
    at new ProviderSync (D:\Yarn\global\node_modules\mem-fs-editor\node_modules\fast-glob\out\providers\sync.js:8:24)
    at getWorks (D:\Yarn\global\node_modules\mem-fs-editor\node_modules\fast-glob\out\index.js:58:22)
    at AsyncFunction.sync (D:\Yarn\global\node_modules\mem-fs-editor\node_modules\fast-glob\out\index.js:20:23)
    at AsyncFunction.module.exports.sync (D:\Yarn\global\node_modules\mem-fs-editor\node_modules\globby\index.js:151:42)
    at EditionInterface.exports.copy (D:\Yarn\global\node_modules\mem-fs-editor\lib\actions\copy.js:30:8)
    at EditionInterface.module.exports.copyTpl (D:\Yarn\global\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:22:8)
    at Project.template (D:\Yarn\global\node_modules\@tarojs\cli\src\create\creator.ts:118:13)
    at D:\Yarn\global\node_modules\@tarojs\cli\src\create\init.ts:133:13

### 期望结果
正常

### 实际结果
异常

### 环境信息
```
👽 Taro v3.6.4


  Taro CLI 3.6.4 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.19.0 - D:\nodejs\node.EXE
      Yarn: 1.22.19 - D:\Yarn\bin\yarn.CMD
      npm: 9.4.2 - D:\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.4 => 3.6.4
      @tarojs/components: 3.6.4 => 3.6.4
      @tarojs/components-rn: 3.6.4 => 3.6.4
      @tarojs/helper: 3.6.4 => 3.6.4
      @tarojs/plugin-framework-react: 3.6.4 => 3.6.4 
      @tarojs/react: 3.6.4 => 3.6.4
      @tarojs/rn-runner: 3.6.4 => 3.6.4
      @tarojs/rn-supporter: 3.6.4 => 3.6.4
      @tarojs/runtime: 3.6.4 => 3.6.4
      @tarojs/runtime-rn: 3.6.4 => 3.6.4
      @tarojs/shared: 3.6.4 => 3.6.4
      @tarojs/taro: 3.6.4 => 3.6.4
      @tarojs/taro-rn: 3.6.4 => 3.6.4
      @tarojs/webpack5-runner: 3.6.4 => 3.6.4
      babel-preset-taro: 3.6.4 => 3.6.4
      eslint-config-taro: 3.6.4 => 3.6.4
      expo: ~47.0.3 => 47.0.14
      react: ^18.1.0 => 18.2.0
      react-native: ^0.70.5 => 0.70.8
      taro-ui: v3.1.0-beta.4 => 3.1.0-beta.4

```

**Comment by TheKonka** [comment]
![image](https://user-images.githubusercontent.com/22173084/230755187-853dc72d-859b-4213-ab32-89ec1ad6dbd6.png)
未复现

**Comment by hanwenbo** [comment]
你们Watching...有效果吗？感觉bug好多呢

**Comment by jingliangapp** [comment]
执行yarn global upgrade后正常
