### ISSUE TITLE
 3.6.5-alpha.1 3.6.5-alpha，Button 组件h5下异常

### ISSUE THREAD

**Issue by xiaof520** [NervJS/taro#13641]
### 相关平台
H5

**浏览器版本: edge**
**使用框架: React**

### 复现步骤
```
alue of [object HTMLElement] which has only a getter
    at HTMLElement.onButtonSubmit (vendors-node_modules_taro_h5_prebundle_chunk-CVPH2KIV_js.js:13196:20)
    at HTMLElement.<anonymous> (vendors-node_modules_taro_h5_prebundle_chunk-CVPH2KIV_js.js:3712:50)
    at emitEvent (vendors-node_modules_taro_h5_prebundle_chunk-CVPH2KIV_js.js:2440:9)
    at Object.emit (vendors-node_modules_taro_h5_prebundle_chunk-CVPH2KIV_js.js:2429:20)
    at push../node_modules/.taro/h5/prebundle/chunk-CVPH2KIV.js.proxyCustomElement.disabled.onTouchEnd (vendors-node_modules_taro_h5_prebundle_chunk-CVPH2KIV_js.js:12331:27)
    at push../node_modules/.taro/h5/prebundle/chunk-CVPH2KIV.js.proxyCustomElement.disabled.<anonymous> (vendors-node_modules_taro_h5_prebundle_chunk-CVPH2KIV_js.js:3712:50) undefined
consoleError @ vendors-node_mod
```
```
                <Button
                    formType='submit'
                    type='primary'
                >
                    保存
                </Button>
```
### 期望结果
正常

### 实际结果
异常

### 环境信息
```
Taro v3.6.5-alpha


  Taro CLI 3.6.5-alpha environment info:
    System:
      OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
      Shell: 5.1.4 - /bin/bash
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
```

---
### 补充信息
3.6.5-alpha pnpm可以使用，h5下新有这个问题
https://github.com/xiaof520/pnpm.git

**Comment by ZakaryCode** [comment]
可以补个用例，或者使用 3.6.5-alpha.1 试试，没能复现到这个问题

**Comment by xiaof520** [comment]
> 

https://github.com/xiaof520/pnpm.git  升级3.6.5-alpha.1 还有一样的异常

**Comment by xiaof520** [comment]
> https://github.com/xiaof520/pnpm.git



> > 
> 
> https://github.com/xiaof520/pnpm.git 升级3.6.5-alpha.1 还有一样的异常



> 可以补个用例，或者使用 3.6.5-alpha.1 试试，没能复现到这个问题

https://github.com/xiaof520/pnpm.git 升级3.6.5-alpha.1 还有一样的异常

**Comment by xiaof520** [comment]
> 可以补个用例，或者使用 3.6.5-alpha.1 试试，没能复现到这个问题

https://github.com/xiaof520/pnpm.git 升级3.6.5-alpha.1 还有一样的异常

**Comment by ZakaryCode** [comment]
是 Form 组件的问题，等等修复
