### ISSUE TITLE
项目初始化报错

### ISSUE THREAD

**Issue by hjh1123** [NervJS/taro#1374]
bogon:~ apple$ taro init myApp
/usr/local/lib/node_modules/@tarojs/cli/src/util/index.js:206
exports.replaceAsync = async function (str, regex, asyncFn) {
                             ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/bin/taro:4:44)
    at Module._compile (module.js:573:32)
bogon:~ apple$

**Comment by yuche** [comment]
你的 node 版本太低了，升级到 8 以上
