### ISSUE TITLE
mac m1 pro 运行npm run dev:weapp 报错

### ISSUE THREAD

**Issue by jws2001** [NervJS/taro#13780]
### 相关平台
微信小程序

**小程序基础库: 2.22.1**
**使用框架: Vue 3**

### 复现步骤
公司的项目在windwo上可以成功运功 
但是在 mac m1 pro 就不行
拉取代吗 下载依赖 npm run dev:weapp 就会出现问题

### 期望结果
npm run dev:weapp运行成功

### 实际结果
thread '<unnamed>' panicked at 'failed to register unwind information: "unsupported unwind information"', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-engine-universal-2.3.0/src/code_memory.rs:199:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: failed to handle: failed to register unwind information: "unsupported unwind information"
    at Compiler.transformSync (/Users/songsong/Desktop/wensong.jiao CODE/cbest-helper-miniapp/node_modules/@swc/core/index.js:241:29)
    at transformSync (/Users/songsong/Desktop/wensong.jiao CODE/cbest-helper-miniapp/node_modules/@swc/core/index.js:348:21)
    at requireWithEsbuild (/Users/songsong/Desktop/wensong.jiao CODE/cbest-helper-miniapp/node_modules/@tarojs/helper/src/esbuild/index.ts:47:38)
    at readConfig (/Users/songsong/Desktop/wensong.jiao CODE/cbest-helper-miniapp/node_modules/@tarojs/helper/src/utils.ts:604:34)
    at MiniPrebundle.getEntries (/Users/songsong/Desktop/wensong.jiao CODE/cbest-helper-miniapp/node_modules/@tarojs/webpack5-prebundle/src/prebundle/index.ts:137:35)
    at MiniPrebundle.<anonymous> (/Users/songsong/Desktop/wensong.jiao CODE/cbest-helper-miniapp/node_modules/@tarojs/webpack5-prebundle/src/mini.ts:224:36)
    at Generator.next (<anonymous>)
    at /Users/songsong/Desktop/wensong.jiao CODE/cbest-helper-miniapp/node_modules/@tarojs/webpack5-prebundle/dist/mini.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/songsong/Desktop/wensong.jiao CODE/cbest-helper-miniapp/node_modules/@tarojs/webpack5-prebundle/dist/mini.js:4:12) {
  code: 'GenericFailure'
}
依赖预编译失败，已经为您跳过预编译步骤，但是编译速度可能会受到影响。
thread '<unnamed>' panicked at 'failed to register unwind information: "unsupported unwind information"', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-engine-universal-2.3.0/src/code_memory.rs:199:18
/Users/songsong/Desktop/wensong.jiao CODE/cbest-helper-miniapp/node_modules/@swc/core/index.js:241
            return bindings.transformSync(isModule ? JSON.stringify(src) : src, isModule, toBuffer(newOptions));
                            ^

Error: failed to handle: failed to register unwind information: "unsupported unwind information"
    at Compiler.transformSync (/Users/songsong/Desktop/wensong.jiao CODE/cbest-helper-miniapp/node_modules/@swc/core/index.js:241:29)
    at transformSync (/Users/songsong/Desktop/wensong.jiao CODE/cbest-helper-miniapp/node_modules/@swc/core/index.js:348:21)
    at requireWithEsbuild (/Users/songsong/Desktop/wensong.jiao CODE/cbest-helper-miniapp/node_modules/@tarojs/helper/src/esbuild/index.ts:47:38)
    at readConfig (/Users/songsong/Desktop/wensong.jiao CODE/cbest-helper-miniapp/node_modules/@tarojs/helper/src/utils.ts:604:34)
    at MiniSplitChunksPlugin.getSubpackageConfig (/Users/songsong/Desktop/wensong.jiao CODE/cbest-helper-miniapp/node_modules/@tarojs/webpack5-runner/src/plugins/MiniSplitChunksPlugin.ts:593:44)
    at MiniSplitChunksPlugin.apply (/Users/songsong/Desktop/wensong.jiao CODE/cbest-helper-miniapp/node_modules/@tarojs/webpack5-runner/src/plugins/MiniSplitChunksPlugin.ts:330:29)
    at createCompiler (/Users/songsong/Desktop/wensong.jiao CODE/cbest-helper-miniapp/node_modules/webpack/lib/webpack.js:73:12)
    at create (/Users/songsong/Desktop/wensong.jiao CODE/cbest-helper-miniapp/node_modules/webpack/lib/webpack.js:134:16)
    at webpack (/Users/songsong/Desktop/wensong.jiao CODE/cbest-helper-miniapp/node_modules/webpack/lib/webpack.js:158:32)
    at f (/Users/songsong/Desktop/wensong.jiao CODE/cbest-helper-miniapp/node_modules/webpack/lib/index.js:63:16) {
  code: 'GenericFailure'
}

### 环境信息
```
 Taro CLI 3.6.6 environment info:
    System:
      OS: macOS 12.6.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.6 => 3.6.6 
      @tarojs/components: 3.6.6 => 3.6.6 
      @tarojs/helper: 3.6.6 => 3.6.6 
      @tarojs/plugin-framework-vue3: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-alipay: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-h5: ^3.6.6 => 3.6.6 
      @tarojs/plugin-platform-jd: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-qq: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-swan: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-tt: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-weapp: 3.6.6 => 3.6.6 
      @tarojs/router: 3.6.6 => 3.6.6 
      @tarojs/runtime: 3.6.6 => 3.6.6 
      @tarojs/shared: 3.6.6 => 3.6.6 
      @tarojs/taro: 3.6.6 => 3.6.6 
      @tarojs/taro-h5: 3.6.6 => 3.6.6 
      @tarojs/webpack5-runner: 3.6.6 => 3.6.6 
      babel-preset-taro: 3.6.6 => 3.6.6 
      eslint-config-taro: 3.6.6 => 3.6.6 
```

**Comment by jws2001** [comment]
搞了一天了 求求哪位大佬帮我解决一下啦

**Comment by yoyo837** [comment]
上个复现?

**Comment by yoyo837** [comment]
@swc/core 版本多少

**Comment by jws2001** [comment]
> @swc/core 版本多少

1.3.23

**Comment by yoyo837** [comment]
搞个复现来看看吧, 我是m1 max

**Comment by jws2001** [comment]
> @swc/core 版本多少

网上的 降级 @swc/core 也试过 还是不行

**Comment by jws2001** [comment]
> 

我就是拉取公司代码就不行 windwo就没有问题

**Comment by jws2001** [comment]
> 搞个复现来看看吧, 我是m1 max

我window可以 mac 就是报这个问题

**Comment by jws2001** [comment]
> .swc 删除重新编译有试过吗

兄弟你厉害 我删除之后在编译就可以了 6

**Comment by jws2001** [comment]
.swc 删除重新编译

**Comment by TheKonka** [comment]
嗯，`.swc` 要加在 `.gitignore` 里面
