### ISSUE TITLE
箭头函数 jsx 不支持

### ISSUE THREAD

**Issue by kdong007** [NervJS/taro#139]
`()=> <Foo />`

这样的格式好像暂时不支持 报错
```
TypeError: Cannot read property 'remove' of undefined
    at transform (/Users/kdong007/mp-collection/taro-mini-program/node_modules/@tarojs/transformer-wx/lib/src/index.js:136:22)
    at buildEntry (/Users/kdong007/mp-collection/taro-mini-program/node_modules/@tarojs/cli/src/weapp.js:528:29)
    at FSWatcher.watcher.on.on.on (/Users/kdong007/mp-collection/taro-mini-program/node_modules/@tarojs/cli/src/weapp.js:976:32)
    at emitOne (events.js:116:13)
    at FSWatcher.emit (events.js:211:7)
    at FSWatcher.<anonymous> (/Users/kdong007/mp-collection/taro-mini-program/node_modules/chokidar/index.js:199:15)
    at FSWatcher._emit (/Users/kdong007/mp-collection/taro-mini-program/node_modules/chokidar/index.js:241:5)
    at FSWatcher.<anonymous> (/Users/kdong007/mp-collection/taro-mini-program/node_modules/chokidar/lib/fsevents-handler.js:206:14)
    at addOrChange (/Users/kdong007/mp-collection/taro-mini-program/node_modules/chokidar/lib/fsevents-handler.js:212:7)
    at FSWatcher.<anonymous> (/Users/kdong007/mp-collection/taro-mini-program/node_modules/chokidar/lib/fsevents-handler.js:244:16)
(node:46142) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
```

以后有可能支持么？

**Comment by yuche** [comment]
目前这个写法只能在map循环函数中使用，以后会进行支持。

**Comment by yuche** [comment]
Duplicate of #157
