### ISSUE TITLE
启动微信小程序编译时报错： HookWebpackError: Called Compilation.updateAsset for not existing filename custom-wrapper.js

### ISSUE THREAD

**Issue by RunningCoderLee** [NervJS/taro#13988]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/RunningCoderLee/my-taro-error-demo.git](https://github.com/RunningCoderLee/my-taro-error-demo.git)
**小程序基础库: 2.30.2**
**使用框架: React**

### 复现步骤
直接运行pnpm dev:weapp 即可复现

### 期望结果
不报错

### 实际结果
编译报错

```shell
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

HookWebpackError: Called Compilation.updateAsset for not existing filename custom-wrapper.js
    at makeWebpackError (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/webpack@5.78.0_@swc+core@1.3.23/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/webpack@5.78.0_@swc+core@1.3.23/node_modules/webpack/lib/Compilation.js:3060:12
    at eval (eval at create (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at fn (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/webpack@5.78.0_@swc+core@1.3.23/node_modules/webpack/lib/Compilation.js:480:17)
    at _next0 (eval at create (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at eval (eval at create (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)
    at eval (eval at create (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/webpack@5.78.0_@swc+core@1.3.23/node_modules/webpack/lib/Compilation.js:502:10
    at Hook.eval [as callAsync] (eval at create (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/Hook.js:18:14)
-- inner error --
Error: Called Compilation.updateAsset for not existing filename custom-wrapper.js
    at Compilation.updateAsset (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/webpack@5.78.0_@swc+core@1.3.23/node_modules/webpack/lib/Compilation.js:4329:10)
    at /Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/webpack@5.78.0_@swc+core@1.3.23/node_modules/webpack/lib/BannerPlugin.js:106:20
    at fn (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/webpack@5.78.0_@swc+core@1.3.23/node_modules/webpack/lib/Compilation.js:478:10)
    at _next0 (eval at create (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at eval (eval at create (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)
    at eval (eval at create (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/webpack@5.78.0_@swc+core@1.3.23/node_modules/webpack/lib/Compilation.js:502:10
    at Hook.eval [as callAsync] (eval at create (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/webpack@5.78.0_@swc+core@1.3.23/node_modules/webpack/lib/Compilation.js:515:46 {
  details: 'caused by plugins in Compilation.hooks.processAssets\n' +
    'Error: Called Compilation.updateAsset for not existing filename custom-wrapper.js\n' +
    '    at Compilation.updateAsset (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/webpack@5.78.0_@swc+core@1.3.23/node_modules/webpack/lib/Compilation.js:4329:10)\n' +
    '    at /Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/webpack@5.78.0_@swc+core@1.3.23/node_modules/webpack/lib/BannerPlugin.js:106:20\n' +
    '    at fn (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/webpack@5.78.0_@swc+core@1.3.23/node_modules/webpack/lib/Compilation.js:478:10)\n' +
    '    at _next0 (eval at create (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)\n' +
    '    at eval (eval at create (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)\n' +
    '    at eval (eval at create (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)\n' +
    '    at /Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/webpack@5.78.0_@swc+core@1.3.23/node_modules/webpack/lib/Compilation.js:502:10\n' +
    '    at Hook.eval [as callAsync] (eval at create (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)\n' +
    '    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/Hook.js:18:14)\n' +
    '    at /Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/webpack@5.78.0_@swc+core@1.3.23/node_modules/webpack/lib/Compilation.js:515:46',
  module: undefined,
  loc: undefined,
  hideStack: true,
  chunk: undefined,
  file: undefined,
  hook: 'Compilation.hooks.processAssets',
  error: Error: Called Compilation.updateAsset for not existing filename custom-wrapper.js
      at Compilation.updateAsset (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/webpack@5.78.0_@swc+core@1.3.23/node_modules/webpack/lib/Compilation.js:4329:10)
      at /Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/webpack@5.78.0_@swc+core@1.3.23/node_modules/webpack/lib/BannerPlugin.js:106:20
      at fn (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/webpack@5.78.0_@swc+core@1.3.23/node_modules/webpack/lib/Compilation.js:478:10)
      at _next0 (eval at create (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
      at eval (eval at create (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)
      at eval (eval at create (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
      at /Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/webpack@5.78.0_@swc+core@1.3.23/node_modules/webpack/lib/Compilation.js:502:10
      at Hook.eval [as callAsync] (eval at create (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
      at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/Hook.js:18:14)
      at /Users/kevin/Developer/github/error-demo/my-taro-error-demo/node_modules/.pnpm/webpack@5.78.0_@swc+core@1.3.23/node_modules/webpack/lib/Compilation.js:515:46
}
```

### 环境信息
```
👽 Taro v3.6.7


  Taro CLI 3.6.7 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.18.0 - ~/.nvm/versions/node/v16.15.0/bin/yarn
      npm: 8.10.0 - ~/.nvm/versions/node/v16.15.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.7 => 3.6.7 
      @tarojs/components: 3.6.7 => 3.6.7 
      @tarojs/helper: 3.6.7 => 3.6.7 
      @tarojs/plugin-framework-react: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-alipay: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-h5: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-jd: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-qq: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-swan: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-tt: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-weapp: 3.6.7 => 3.6.7 
      @tarojs/react: 3.6.7 => 3.6.7 
      @tarojs/runtime: 3.6.7 => 3.6.7 
      @tarojs/shared: 3.6.7 => 3.6.7 
      @tarojs/taro: 3.6.7 => 3.6.7 
      @tarojs/webpack5-runner: 3.6.7 => 3.6.7 
      babel-preset-taro: 3.6.7 => 3.6.7 
      eslint-config-taro: 3.6.7 => 3.6.7 
      react: ^18.0.0 => 18.0.0 
```

---
### 补充信息

我是在安装和使用 [@sentry/webpack-plugin@2.x](https://github.com/getsentry/sentry-javascript-bundler-plugins/tree/main/packages/webpack-plugin) 版本后出现的这个问题，如果安装 [1.x](https://github.com/getsentry/sentry-webpack-plugin) 不会出现此类问题

**Comment by hcxmj** [comment]
我统一的taro版本编译百度也有同样的问题
