### ISSUE TITLE
使用react-intl，编译小程序不通过

### ISSUE THREAD

**Issue by suuzee** [NervJS/taro#1400]
**问题描述**
使用`react-intl`，编译小程序不通过

**复现步骤**
1. `Taro`项目中引入`react-intl`
2. 执行`npm run dev:weapp`

**期望行为**
编译通过，`react-intl`绝对路径引的包从`node_modules`里面找，而不是从相对位置找。

**报错信息**
`react-intl`源码是这样的：
```javascript
// ...
var allLocaleData = _interopDefault(require('../locale-data/index.js'));
var IntlMessageFormat = _interopDefault(require('intl-messageformat'));
var IntlRelativeFormat = _interopDefault(require('intl-relativeformat'));
var PropTypes = _interopDefault(require('prop-types'));
var React = require('react');
var React__default = _interopDefault(React);
var hoistNonReactStatics = _interopDefault(require('hoist-non-react-statics'));
var invariant = _interopDefault(require('invariant'));
var memoizeIntlConstructor = _interopDefault(require('intl-format-cache'));

// ...
```

```bash
{ Error: ENOENT: no such file or directory, open '/Users/test/practices/taro-demo/node_modules/react-intl/lib/intl-format-cache'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at buildSingleComponent (/Users/test/.nvm/versions/node/v8.14.0/lib/node_modules/@tarojs/cli/src/weapp.js:1631:31)
    at buildSingleComponent (/Users/test/.nvm/versions/node/v8.14.0/lib/node_modules/@tarojs/cli/src/weapp.js:1667:20)
    at Promise.all.componentPathList.map.componentObj (/Users/test/.nvm/versions/node/v8.14.0/lib/node_modules/@tarojs/cli/src/weapp.js:1574:60)
    at Array.map (<anonymous>)
    at buildDepComponents (/Users/test/.nvm/versions/node/v8.14.0/lib/node_modules/@tarojs/cli/src/weapp.js:1574:40)
    at buildSinglePage (/Users/test/.nvm/versions/node/v8.14.0/lib/node_modules/@tarojs/cli/src/weapp.js:1323:40)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/test/practices/taro-demo/node_modules/react-intl/lib/intl-format-cache' }
```

**系统信息**

 - 操作系统: macOS 10.14
 - Taro 版本: v1.2.0.beta9
 - Node.js: 版本 v8.14
 - 报错平台: weapp

**补充信息**
感觉问题可能出在这，但是理解不深，不敢猜测

```javascript
// @tarojs/cli/src/util/index.js 335
exports.resolveScriptPath = function (p) {
  let realPath = p
  const SCRIPT_EXT = exports.JS_EXT.concat(exports.TS_EXT)
  for (let i = 0; i < SCRIPT_EXT.length; i++) {
    const item = SCRIPT_EXT[i]

    if (fs.existsSync(`${p}${item}`)) {
      return `${p}${item}`
    }
    if (fs.existsSync(`${p}${path.sep}index${item}`)) {
      return `${p}${path.sep}index${item}`
    }
  }
  return realPath
}
```

**Comment by luckyadam** [comment]
react 的组件用不了

**Comment by joyran** [comment]
@suuzee hello, 请问问题如何解决的，谢谢
