### ISSUE TITLE
无法进行 npm run dev:weapp

### ISSUE THREAD

**Issue by webkonglong** [NervJS/taro#14099]
### 相关平台
微信小程序

**小程序基础库: 还没到小程序开发中工具这一步**
**使用框架: React**

### 复现步骤
通过 `npm install -g @tarojs/cli`安装

然后通过 `taro init xxx-xx-xx`初始化项目
`
? 请输入项目介绍 xxxx
? 请选择框架 React
? 是否需要使用 TypeScript ？ No
? 请选择 CSS 预处理器（Sass/Less/Stylus） Less
? 请选择编译工具 Webpack5
? 请选择包管理工具 npm
? 请选择模板源 Gitee（最快）
✔ 拉取远程模板仓库成功！
? 请选择模板 taro-hooks（使用 taro-hooks 的模板）
`
提示 `
✔ 安装成功
创建项目 xxx-xx-xx 成功！
请进入项目目录 xxx-xx-xx 开始工作吧！😝
`
然后进去后 执行了  `npm run dev:weapp`

### 期望结果
期望 能正确运行 npm run dev:weapp

### 实际结果
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Array]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

### 环境信息
```
👽 Taro v3.6.8


  Taro CLI 3.6.8 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.8 => 3.6.8
      @tarojs/components: 3.6.8 => 3.6.8
      @tarojs/helper: 3.6.8 => 3.6.8
      @tarojs/plugin-framework-react: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-alipay: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-h5: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-jd: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-qq: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-swan: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-tt: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-weapp: 3.6.8 => 3.6.8
      @tarojs/react: 3.6.8 => 3.6.8
      @tarojs/runtime: 3.6.8 => 3.6.8
      @tarojs/shared: 3.6.8 => 3.6.8
      @tarojs/taro: 3.6.8 => 3.6.8
      @tarojs/taro-loader: 3.6.8 => 3.6.8
      @tarojs/webpack5-runner: 3.6.8 => 3.6.8
      babel-preset-taro: 3.6.8 => 3.6.8
      eslint-config-taro: 3.6.8 => 3.6.8
      react: ^18.0.0 => 18.2.0




`
taro v3.6.8
npm v8.15.0
node v16.17.0
webpack 5.88.1
`
```

**Comment by webkonglong** [comment]
**实际结果 很长，提问题 贴不下，我贴这里**

`
> minapp-snap-video@1.0.0 dev:weapp
> npm run build:weapp -- --watch


> minapp-snap-video@1.0.0 build:weapp
> taro build --type weapp

👽 Taro v3.6.8

Tips:
1. 预览模式生成的文件较大，设置 NODE_ENV 为 production 可以开启压缩。
Example:
$ set NODE_ENV=production && taro build --type weapp --watch
2. 建议开启持久化缓存功能，能有效提升二次编译速度，详情请参考: https://docs.taro.zone/docs/config-detail#cache。


Prebundle dependencies:
     @tarojs/plugin-framework-react/dist/runtime
     @tarojs/plugin-platform-weapp/dist/runtime
     @tarojs/runtime
     @tarojs/taro
     react
     react-dom
     react/jsx-runtime
     taro-hooks


✖ Webpack
  Compiled with some errors in 466.44ms

✖ Errors:

resolve '@taro-hooks/core' in 'E:\dev\vlog\minapp-snap-video\node_modules\.taro\weapp\prebundle'
  Parsed request is a module
  using description file: E:\dev\vlog\minapp-snap-video\package.json (relative path: ./node_modules/.taro/weapp/prebundle)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      E:\dev\vlog\minapp-snap-video\node_modules\.taro\weapp\prebundle\node_modules doesn't exist or is not a directory
      E:\dev\vlog\minapp-snap-video\node_modules\.taro\weapp\node_modules doesn't exist or is not a directory
      E:\dev\vlog\minapp-snap-video\node_modules\.taro\node_modules doesn't exist or is not a directory
      E:\dev\vlog\minapp-snap-video\node_modules\node_modules doesn't exist or is not a directory
      looking for modules in E:\dev\vlog\minapp-snap-video\node_modules
        single file module
          using description file: E:\dev\vlog\minapp-snap-video\package.json (relative path: ./node_modules/@taro-hooks/core)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core.mjs doesn't exist
            .vue
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core.vue doesn't exist
        E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core doesn't exist
      E:\dev\vlog\node_modules doesn't exist or is not a directory
      E:\dev\node_modules doesn't exist or is not a directory
      E:\node_modules doesn't exist or is not a directory

→ Watching... [2023/7/1 18:54:15]

<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve '@taro-hooks/core' in 'E:\dev\vlog\minapp-snap-video\node_modules\.taro\weapp\prebundle'
<w> while resolving '@taro-hooks/core' in E:\dev\vlog\minapp-snap-video\node_modules\.taro\weapp\prebundle as file
<w>  at resolve esm file @taro-hooks/core
<w>  at file dependencies E:\dev\vlog\minapp-snap-video\node_modules\.taro\weapp\prebundle\taro-hooks.js
<w>  at file E:\dev\vlog\minapp-snap-video\node_modules\.taro\weapp\prebundle\taro-hooks.js
<w>  at resolve commonjs E:\dev\vlog\minapp-snap-video\node_modules\.taro\weapp\prebundle\taro-hooks.js
{
  moduleIdentifier: 'E:\\dev\\vlog\\minapp-snap-video\\node_modules\\.taro\\weapp\\prebundle\\taro-hooks.js',
  moduleName: './node_modules/.taro/weapp/prebundle/taro-hooks.js',
  loc: '105:0-42',
  message: "Module not found: Error: Can't resolve '@taro-hooks/core' in 'E:\\dev\\vlog\\minapp-snap-video\\node_modules\\.taro\\weapp\\prebundle'",
  moduleId: './node_modules/.taro/weapp/prebundle/taro-hooks.js',
  moduleTrace: [
    {
      originIdentifier: 'container entry (default) [["./react",{"import":["E:\\\\dev\\\\vlog\\\\minapp-snap-video\\\\node_modules\\\\.taro\\\\weapp\\\\prebundle\\\\react.js"]}],["./taro-hooks",{"import":["E:\\\\dev\\\\vlog\\\\minapp-snap-video\\\\node_modules\\\\.taro\\\\weapp\\\\prebundle\\\\taro-hooks.js"]}],["./react/jsx-runtime",{"import":["E:\\\\dev\\\\vlog\\\\minapp-snap-video\\\\node_modules\\\\.taro\\\\weapp\\\\prebundle\\\\react_jsx-runtime.js"]}],["./@tarojs/runtime",{"import":["E:\\\\dev\\\\vlog\\\\minapp-snap-video\\\\node_modules\\\\.taro\\\\weapp\\\\prebundle\\\\@tarojs_runtime.js"]}],["./@tarojs/plugin-framework-react/dist/runtime",{"import":["E:\\\\dev\\\\vlog\\\\minapp-snap-video\\\\node_modules\\\\.taro\\\\weapp\\\\prebundle\\\\@tarojs_plugin-framework-react_dist_runtime.js"]}],["./@tarojs/plugin-platform-weapp/dist/runtime",{"import":["E:\\\\dev\\\\vlog\\\\minapp-snap-video\\\\node_modules\\\\.taro\\\\weapp\\\\prebundle\\\\@tarojs_plugin-platform-weapp_dist_runtime.js"]}],["./@tarojs/taro",{"import":["E:\\\\dev\\\\vlog\\\\minapp-snap-video\\\\node_modules\\\\.taro\\\\weapp\\\\prebundle\\\\@tarojs_taro.js"]}],["./react-dom",{"import":["E:\\\\dev\\\\vlog\\\\minapp-snap-video\\\\node_modules\\\\.taro\\\\weapp\\\\prebundle\\\\react-dom.js"]}]]',
      originName: 'container entry',
      moduleIdentifier: 'E:\\dev\\vlog\\minapp-snap-video\\node_modules\\.taro\\weapp\\prebundle\\taro-hooks.js',
      moduleName: './node_modules/.taro/weapp/prebundle/taro-hooks.js',
      dependencies: [Array],
      originId: 'webpack/container/entry/taro_app_library',
      moduleId: './node_modules/.taro/weapp/prebundle/taro-hooks.js'
    }
  ],
  details: "resolve '@taro-hooks/core' in 'E:\\dev\\vlog\\minapp-snap-video\\node_modules\\.taro\\weapp\\prebundle'\n" +    '  Parsed request is a module\n' +
    '  using description file: E:\\dev\\vlog\\minapp-snap-video\\package.json (relative path: ./node_modules/.taro/weapp/prebundle)\n' +
    "    Field 'browser' doesn't contain a valid alias configuration\n" +
    '    resolve as module\n' +
    "      E:\\dev\\vlog\\minapp-snap-video\\node_modules\\.taro\\weapp\\prebundle\\node_modules doesn't exist or is not a directory\n" +
    "      E:\\dev\\vlog\\minapp-snap-video\\node_modules\\.taro\\weapp\\node_modules doesn't exist or is not a directory\n" +
    "      E:\\dev\\vlog\\minapp-snap-video\\node_modules\\.taro\\node_modules doesn't exist or is not a directory\n" +
    "      E:\\dev\\vlog\\minapp-snap-video\\node_modules\\node_modules doesn't exist or is not a directory\n" +
    '      looking for modules in E:\\dev\\vlog\\minapp-snap-video\\node_modules\n' +
    '        single file module\n' +
    '          using description file: E:\\dev\\vlog\\minapp-snap-video\\package.json (relative path: ./node_modules/@taro-hooks/core)\n' +
    '            no extension\n' +
    "              Field 'browser' doesn't contain a valid alias configuration\n" +
    "              E:\\dev\\vlog\\minapp-snap-video\\node_modules\\@taro-hooks\\core doesn't exist\n" +
    '            .js\n' +
    "              Field 'browser' doesn't contain a valid alias configuration\n" +
    "              E:\\dev\\vlog\\minapp-snap-video\\node_modules\\@taro-hooks\\core.js doesn't exist\n" +
    '            .jsx\n' +
    "              Field 'browser' doesn't contain a valid alias configuration\n" +
    "              E:\\dev\\vlog\\minapp-snap-video\\node_modules\\@taro-hooks\\core.jsx doesn't exist\n" +
    '            .ts\n' +
    "              Field 'browser' doesn't contain a valid alias configuration\n" +
    "              E:\\dev\\vlog\\minapp-snap-video\\node_modules\\@taro-hooks\\core.ts doesn't exist\n" +
    '            .tsx\n' +
    "              Field 'browser' doesn't contain a valid alias configuration\n" +
    "              E:\\dev\\vlog\\minapp-snap-video\\node_modules\\@taro-hooks\\core.tsx doesn't exist\n" +
    '            .mjs\n' +
    "              Field 'browser' doesn't contain a valid alias configuration\n" +
    "              E:\\dev\\vlog\\minapp-snap-video\\node_modules\\@taro-hooks\\core.mjs doesn't exist\n" +
    '            .vue\n' +
    "              Field 'browser' doesn't contain a valid alias configuration\n" +
    "              E:\\dev\\vlog\\minapp-snap-video\\node_modules\\@taro-hooks\\core.vue doesn't exist\n" +
    "        E:\\dev\\vlog\\minapp-snap-video\\node_modules\\@taro-hooks\\core doesn't exist\n" +
    "      E:\\dev\\vlog\\node_modules doesn't exist or is not a directory\n" +
    "      E:\\dev\\node_modules doesn't exist or is not a directory\n" +
    "      E:\\node_modules doesn't exist or is not a directory",
  stack: "ModuleNotFoundError: Module not found: Error: Can't resolve '@taro-hooks/core' in 'E:\\dev\\vlog\\minapp-snap-video\\node_modules\\.taro\\weapp\\prebundle'\n" +
    '    at E:\\dev\\vlog\\minapp-snap-video\\node_modules\\webpack\\lib\\Compilation.js:2022:28\n' +
    '    at E:\\dev\\vlog\\minapp-snap-video\\node_modules\\webpack\\lib\\NormalModuleFactory.js:817:13\n' +
    '    at eval (eval at create (E:\\dev\\vlog\\minapp-snap-video\\node_modules\\webpack\\node_modules\\tapable\\lib\\HookCodeFactory.js:33:10), <anonymous>:10:1)\n' +
    '    at E:\\dev\\vlog\\minapp-snap-video\\node_modules\\webpack\\lib\\NormalModuleFactory.js:275:22\n' +
    '    at eval (eval at create (E:\\dev\\vlog\\minapp-snap-video\\node_modules\\webpack\\node_modules\\tapable\\lib\\HookCodeFactory.js:33:10), <anonymous>:9:1)\n' +
    '    at E:\\dev\\vlog\\minapp-snap-video\\node_modules\\webpack\\lib\\NormalModuleFactory.js:448:22\n' +
    '    at E:\\dev\\vlog\\minapp-snap-video\\node_modules\\webpack\\lib\\NormalModuleFactory.js:118:11\n' +
    '    at E:\\dev\\vlog\\minapp-snap-video\\node_modules\\webpack\\lib\\NormalModuleFactory.js:689:25\n' +
    '    at E:\\dev\\vlog\\minapp-snap-video\\node_modules\\webpack\\lib\\NormalModuleFactory.js:893:8\n' +
    '    at E:\\dev\\vlog\\minapp-snap-video\\node_modules\\webpack\\lib\\NormalModuleFactory.js:1013:5'
}
依赖预编译失败，已经为您跳过预编译步骤，但是编译速度可能会受到影响。

✖ Webpack
  Compiled with some errors in 9.08s

✖ Errors:

resolve '@taro-hooks/core' in 'E:\dev\vlog\minapp-snap-video\node_modules\taro-hooks\lib\createUseInfoHook'
  Parsed request is a module
  using description file: E:\dev\vlog\minapp-snap-video\node_modules\taro-hooks\package.json (relative path: ./lib/createUseInfoHook)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      E:\dev\vlog\minapp-snap-video\node_modules\taro-hooks\lib\createUseInfoHook\node_modules doesn't exist or is not a directory
      E:\dev\vlog\minapp-snap-video\node_modules\taro-hooks\lib\node_modules doesn't exist or is not a directory
      E:\dev\vlog\minapp-snap-video\node_modules\taro-hooks\node_modules doesn't exist or is not a directory
      E:\dev\vlog\minapp-snap-video\node_modules\node_modules doesn't exist or is not a directory
      looking for modules in E:\dev\vlog\minapp-snap-video\node_modules
        single file module
          using description file: E:\dev\vlog\minapp-snap-video\package.json (relative path: ./node_modules/@taro-hooks/core)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core.mjs doesn't exist
            .vue
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core.vue doesn't exist
        E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core doesn't exist
      E:\dev\vlog\node_modules doesn't exist or is not a directory
      E:\dev\node_modules doesn't exist or is not a directory
      E:\node_modules doesn't exist or is not a directory

→ Watching... [2023/7/1 18:54:24]

node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Array]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
`

**Comment by TheKonka** [comment]
看起来是你用了 taro-hooks  的原因，不用这个库 ，或者 关闭 prebundle 试试
```js
	compiler: {
		type: 'webpack5',
		prebundle: {
			enable: false
		}
	},
```

**Comment by webkonglong** [comment]
> 看起来是你用了 taro-hooks 的原因，不用这个库 ，或者 关闭 prebundle 试试
> 
> ```js
> 	compiler: {
> 		type: 'webpack5',
> 		prebundle: {
> 			enable: false
> 		}
> 	},
> ```


在项目根目录的 `config/index.js` 吧  compiler: 'webpack5' 替换成 
`
compiler: {
		type: 'webpack5',
		prebundle: {
			enable: false
		}
	},
`

运行 `pnpm dev:weapp`
得到错误
`
$ pnpm dev:weapp

> minapp-snap-video@1.0.0 dev:weapp E:\dev\vlog\minapp-snap-video
> npm run build:weapp -- --watch


> minapp-snap-video@1.0.0 build:weapp
> taro build --type weapp

👽 Taro v3.6.8

Taro 配置有误，请检查！ (E:\dev\vlog\minapp-snap-video\config\index.js)
  [✗] compiler 的值 {"prebundle":{"enable":false,"exclude":[{}],"include":["react","react-dom","react/jsx-runtime","@tarojs/plugin-framework-react/dist/runtime"]},"type":"webpack5"} 不符合类型要求
`

**Comment by TheKonka** [comment]
这是 3.6.8版本的问题，可以先用 3.6.7 或者 [v3.6.9-alpha.7](https://github.com/NervJS/taro/releases/tag/v3.6.9-alpha.7)

**Comment by webkonglong** [comment]
> 这是 3.6.8版本的问题，可以先用 3.6.7 或者 [v3.6.9-alpha.7](https://github.com/NervJS/taro/releases/tag/v3.6.9-alpha.7)

> npm run build:weapp -- --watch


> minapp-snap-video@1.0.0 build:weapp
> taro build --type weapp

👽 Taro v3.6.7

Tips:
1. 预览模式生成的文件较大，设置 NODE_ENV 为 production 可以开启压缩。
Example:
$ set NODE_ENV=production && taro build --type weapp --watch
2. 建议开启持久化缓存功能，能有效提升二次编译速度，详情请参考: https://docs.taro.zone/docs/config-detail#cache。



✖ Webpack
  Compiled with some errors in 2.63s

✖ Errors:

resolve '@taro-hooks/core' in 'E:\dev\vlog\minapp-snap-video\node_modules\taro-hooks\lib\createUseInfoHook'
  Parsed request is a module
  using description file: E:\dev\vlog\minapp-snap-video\node_modules\taro-hooks\package.json (relative path: ./lib/createUseInfoHook)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      E:\dev\vlog\minapp-snap-video\node_modules\taro-hooks\lib\createUseInfoHook\node_modules doesn't exist or is not a directory
      E:\dev\vlog\minapp-snap-video\node_modules\taro-hooks\lib\node_modules doesn't exist or is not a directory
      E:\dev\vlog\minapp-snap-video\node_modules\taro-hooks\node_modules doesn't exist or is not a directory
      E:\dev\vlog\minapp-snap-video\node_modules\node_modules doesn't exist or is not a directory
      looking for modules in E:\dev\vlog\minapp-snap-video\node_modules
        single file module
          using description file: E:\dev\vlog\minapp-snap-video\package.json (relative path: ./node_modules/@taro-hooks/core)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core.mjs doesn't exist
            .vue
              Field 'browser' doesn't contain a valid alias configuration
              E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core.vue doesn't exist
        E:\dev\vlog\minapp-snap-video\node_modules\@taro-hooks\core doesn't exist
      E:\dev\vlog\node_modules doesn't exist or is not a directory
      E:\dev\node_modules doesn't exist or is not a directory
      E:\node_modules doesn't exist or is not a directory

→ Watching... [2023/7/2 15:01:09]

node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Array]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

**Comment by webkonglong** [comment]
有没有什么，稳定的版本，能用react hook模板 正常运行的？麻烦大佬指个版本，我去试一下

**Comment by TheKonka** [comment]
我也没用过这个库，要不你直接到 https://github.com/innocces/taro-hooks 这里问下

**Comment by uu109** [comment]
我也遇到了，在mac和windows上都没问题，linux容器上会报错


Dockerfile
FROM node:16.15.1
...



Linux a3f0903ecdaa 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64 GNU/Linux

**Comment by uu109** [comment]
似乎在我的linux中webpack会把路径搞错。

resolve './components/ReserveForm/index' in '/home/xxxMyProject/src/pages/testdrive'
  using description file: /home/xxxMyProject/package.json (relative path: ./src/pages/testdrive)
    resolve multi platform file path
      using description file: /home/xxxMyProject/package.json (relative path: ./src/pages/testdrive)
        Field 'browser' doesn't contain a valid alias configuration
        root path /home/xxxMyProject
          using description file: /home/xxxMyProject/package.json (**_relative path: ./home/xxxMyProject/src/pages/testdrive/components/ReserveForm/index_**)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/xxxMyProject/home/xxxMyProject/src/pages/testdrive/components/ReserveForm/index doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              _**/home/xxxMyProject/home/xxxMyProject/src/pages/testdrive/components/ReserveForm/index.js doesn't exist**_

应该是 /home/xxxMyProject/src/pages/testdrive/components/ReserveForm/index.js
变成了 /home/xxxMyProject/home/xxxMyProject/src/pages/testdrive/components/ReserveForm/index.js

**Comment by Chen-jj** [comment]
duplicate #14181
