### ISSUE TITLE
H5: Cannot use import statement outside a module in

### ISSUE THREAD

**Issue by SidneyLann** [NervJS/taro#14101]
### 相关平台
H5

### 复现仓库
[https://github.com/SidneyLann/taro-test-repo.git](https://github.com/SidneyLann/taro-test-repo.git)
**浏览器版本: 谷歌最新版**
**使用框架: React**

### 复现步骤
1. yarn
2. yarn run dev:weapp //编译成功并且可以在开发者工具正常访问
3. yarn android //编译通过
4. yarn run dev:h5 //编译失败, 报错: EvalError: Cannot use import statement outside a module in

### 期望结果
在H5下能编译通过

### 实际结果
在H5下编译不通过

### 环境信息
```
 Taro CLI 3.6.8 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 20.3.1 - D:\DEV\nodejs\node.EXE
      Yarn: 1.22.19 - D:\DEV\nodejs\yarn.CMD
      npm: 9.6.7 - D:\DEV\nodejs\npm.CMD
    npmPackages:
      @tarojs/components: 3.6.8 => 3.6.8
      @tarojs/helper: 3.6.8 => 3.6.8
      @tarojs/plugin-framework-react: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-alipay: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-h5: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-jd: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-qq: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-swan: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-tt: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-weapp: 3.6.8 => 3.6.8
      @tarojs/react: 3.6.8 => 3.6.8
      @tarojs/rn-runner: 3.6.8 => 3.6.8
      @tarojs/rn-supporter: 3.6.8 => 3.6.8
      @tarojs/runtime: 3.6.8 => 3.6.8
      @tarojs/runtime-rn: 3.6.8 => 3.6.8
      @tarojs/shared: 3.6.8 => 3.6.8
      @tarojs/taro: 3.6.8 => 3.6.8
      @tarojs/taro-rn: 3.6.8 => 3.6.8
      @tarojs/webpack5-runner: 3.6.8 => 3.6.8
      babel-preset-taro: 3.6.8 => 3.6.8
      eslint-config-taro: 3.6.8 => 3.6.8
      expo: ~47.0.3 => 47.0.14
      react: 18.1.0 => 18.1.0
      react-native: ^0.70.1 => 0.70.10
```

**Comment by TheKonka** [comment]
```js

        chain.merge({
          module: {
            rule: {
              linariaLoader: {
                test: /\.js$/,
                use: [
                  { loader: 'babel-loader' },
                  {
                    loader: '@linaria/webpack-loader',
                    options: {
                      sourceMap: process.env.NODE_ENV !== 'production',
                    },
                  }
                ],
              },
            },
          },
        })
```

这样可以正常编译

**Comment by SidneyLann** [comment]
h5: {
    publicPath: '/h5',
    staticDirectory: 'static',
    webpackChain(chain, webpack) {
     chain.merge({
          module: {
            rule: {
              linariaLoader: {
                test: /\.tsx$/,
                use: [
                  { loader: 'babel-loader' },
                  {
                    loader: '@linaria/webpack5-loader',
                    options: {
                      sourceMap: process.env.NODE_ENV !== 'production',
                    },
                  }
                ],
              },
            },
          },
        })
    },
  },



这样也编译不了, 报一样的错.

**Comment by SidneyLann** [comment]
3.6.11还是有这个问题. 一个多月了也没人看看吗?

**Comment by ZakaryCode** [comment]
并不能复现该问题

**Comment by SidneyLann** [comment]
ERROR in ./src/view/TextLabel.tsx
Module build failed (from ./node_modules/@linaria/webpack5-loader/lib/index.js):
D:\DEV\eb_app\node_modules\@linaria\babel-preset\lib\module.js:355
      throw new EvalError(`${e.message} in${callstack.join('\n| ')}\n`);
      ^

EvalError: Cannot use import statement outside a module in
| D:\DEV\eb_app\node_modules\@stencil\core\internal\client\index.js
| D:\DEV\eb_app\node_modules\@tarojs\components\dist\components\taro-text-core.js
| D:\DEV\eb_app\node_modules\@tarojs\components\dist\components\index.js
| D:\DEV\eb_app\node_modules\@tarojs\components\lib\react\components.js
| D:\DEV\eb_app\node_modules\@tarojs\components\lib\react\index.js
| D:\DEV\eb_app\src\view\TextLabel.tsx

    at Module.evaluate (D:\DEV\eb_app\node_modules\@linaria\babel-preset\src\module.ts:498:13)
    at require.Object.assign.ensure (D:\DEV\eb_app\node_modules\@linaria\babel-preset\src\module.ts:424:15)
    at D:\DEV\eb_app\node_modules\@tarojs\components\dist\components\taro-text-core.js:7:15
    at D:\DEV\eb_app\node_modules\@tarojs\components\dist\components\taro-text-core.js:53:3
    at Script.runInContext (node:vm:134:12)
    at Module.evaluate (D:\DEV\eb_app\node_modules\@linaria\babel-preset\src\module.ts:483:14)
    at require.Object.assign.ensure (D:\DEV\eb_app\node_modules\@linaria\babel-preset\src\module.ts:424:15)
    at D:\DEV\eb_app\node_modules\@tarojs\components\dist\components\index.js:12:21
    at D:\DEV\eb_app\node_modules\@tarojs\components\dist\components\index.js:13:3
    at Script.runInContext (node:vm:134:12)
    at Module.evaluate (D:\DEV\eb_app\node_modules\@linaria\babel-preset\src\module.ts:483:14)
    at require.Object.assign.ensure (D:\DEV\eb_app\node_modules\@linaria\babel-preset\src\module.ts:424:15)
    at D:\DEV\eb_app\node_modules\@tarojs\taro-components-library-react\src\components.ts:176:22
    at D:\DEV\eb_app\node_modules\@tarojs\taro-components-library-react\src\components.ts:182:8
    at Script.runInContext (node:vm:134:12)
    at Module.evaluate (D:\DEV\eb_app\node_modules\@linaria\babel-preset\src\module.ts:483:14)
    at require.Object.assign.ensure (D:\DEV\eb_app\node_modules\@linaria\babel-preset\src\module.ts:424:15)
    at D:\DEV\eb_app\node_modules\@tarojs\components\lib\react\index.js:12:19
    at D:\DEV\eb_app\node_modules\@tarojs\components\lib\react\index.js:13:3
    at Script.runInContext (node:vm:134:12)
    at Module.evaluate (D:\DEV\eb_app\node_modules\@linaria\babel-preset\src\module.ts:483:14)
    at require.Object.assign.ensure (D:\DEV\eb_app\node_modules\@linaria\babel-preset\src\module.ts:424:15)
    at D:\DEV\eb_app\src\view\TextLabel.tsx:3:19
    at D:\DEV\eb_app\src\view\TextLabel.tsx:18:3
    at Script.runInContext (node:vm:134:12)
    at Module.evaluate (D:\DEV\eb_app\node_modules\@linaria\babel-preset\src\module.ts:483:14)
    at evaluate (D:\DEV\eb_app\node_modules\@linaria\babel-preset\src\evaluators\index.ts:21:5)
    at evalStage (D:\DEV\eb_app\node_modules\@linaria\babel-preset\src\transform-stages\2-eval.ts:30:29)
    at syncStages (D:\DEV\eb_app\node_modules\@linaria\babel-preset\src\transform.ts:48:36)
    at transform (D:\DEV\eb_app\node_modules\@linaria\babel-preset\src\transform.ts:183:10)
 @ ./src/pkgsubject/page/others/OrgJoinApplication.tsx 14:0-43 53:39-48 55:32-41
 @ ./src/app.boot.js 414:15-68
 @ ./src/app.config.ts 3:0-20

**Comment by SidneyLann** [comment]
一直有这个问题. 3.6.13也不行.

**Comment by SidneyLann** [comment]
从新init项目就可以了
