### ISSUE TITLE
pnpm dev:weapp windows下无法启动，在linux下可以正常启动

### ISSUE THREAD

**Issue by cl1107** [NervJS/taro#14236]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/cl1107/partner-miniapp-nutui.git](https://github.com/cl1107/partner-miniapp-nutui.git)
**小程序基础库: 3.0**
**使用框架: React**

### 复现步骤
两种复现方式：npx @tarojs/cli init partner-miniapp 创建一个最新模板的小程序，pnpm   webpack5   typescript   less   nutui的模板，安装依赖后运行 pnpm dev:weapp 

下载重现链接的仓库 运行 pnpm i 然后 pnpm dev:weapp

### 期望结果
正常启动

### 实际结果
```
Error: Can't resolve 'react' in 'C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui'
    at finishWithoutResolve (C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\enhanced-resolve@5.15.0\node_modules\enhanced-resolve\lib\Resolver.js:369:18)
    at C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\enhanced-resolve@5.15.0\node_modules\enhanced-resolve\lib\Resolver.js:461:15
    at C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\enhanced-resolve@5.15.0\node_modules\enhanced-resolve\lib\Resolver.js:519:5
    at eval (eval at create (C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\enhanced-resolve@5.15.0\node_modules\enhanced-resolve\lib\Resolver.js:519:5
    at eval (eval at create (C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\enhanced-resolve@5.15.0\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:89:43
    at C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\enhanced-resolve@5.15.0\node_modules\enhanced-resolve\lib\Resolver.js:519:5
    at eval (eval at create (C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\enhanced-resolve@5.15.0\node_modules\enhanced-resolve\lib\forEachBail.js:39:13 {
  details: "resolve 'react' in 'C:\\Users\\cuiliang\\FE\\APEX\\partner-miniapp-nutui'\n" +
    '  Parsed request is a module\n' +
    '  using description file: C:\\Users\\cuiliang\\FE\\APEX\\partner-miniapp-nutui\\package.json (relative path: .)\n' +
    "    aliased with mapping 'react': 'cjs/react.production.min.js' to 'cjs/react.production.min.js'\n" +
    '      Parsed request is a module\n' +
    '      using description file: C:\\Users\\cuiliang\\FE\\APEX\\partner-miniapp-nutui\\package.json (relative path: .)\n' +
    "        Field 'browser' doesn't contain a valid alias configuration\n" +
    '        resolve as module\n' +
    '          looking for modules in C:\\Users\\cuiliang\\FE\\APEX\\partner-miniapp-nutui\\node_modules\n' +
    "            C:\\Users\\cuiliang\\FE\\APEX\\partner-miniapp-nutui\\node_modules\\cjs doesn't exist\n" +
    "          C:\\Users\\cuiliang\\FE\\APEX\\node_modules doesn't exist or is not a directory\n" +
    "          C:\\Users\\cuiliang\\FE\\node_modules doesn't exist or is not a directory\n" +
    "          C:\\Users\\cuiliang\\node_modules doesn't exist or is not a directory\n" +
    "          C:\\Users\\node_modules doesn't exist or is not a directory\n" +
    "          C:\\node_modules doesn't exist or is not a directory"
}
依赖预编译失败，已经为您跳过预编译步骤，但是编译速度可能会受到影响。

✖ Webpack
  Compiled with some errors in 4.37s

✖ Errors:

resolve 'react' in 'C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\@nutui+icons-react-taro@0.0.1-beta.8\node_modules\@nutui\icons-react-taro\dist\es\icons'
  Parsed request is a module
  using description file: C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\@nutui+icons-react-taro@0.0.1-beta.8\node_modules\@nutui\icons-react-taro\package.json (relative path: ./dist/es/icons)
    aliased with mapping 'react': 'cjs/react.production.min.js' to 'cjs/react.production.min.js'
      Parsed request is a module
      using description file: C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\@nutui+icons-react-taro@0.0.1-beta.8\node_modules\@nutui\icons-react-taro\package.json (relative path: ./dist/es/icons)
        Field 'browser' doesn't contain a valid alias configuration
        resolve as module
          C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\@nutui+icons-react-taro@0.0.1-beta.8\node_modules\@nutui\icons-react-taro\dist\es\icons\node_modules doesn't exist or is not a directory
          C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\@nutui+icons-react-taro@0.0.1-beta.8\node_modules\@nutui\icons-react-taro\dist\es\node_modules doesn't exist or is not a directory
          C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\@nutui+icons-react-taro@0.0.1-beta.8\node_modules\@nutui\icons-react-taro\dist\node_modules doesn't exist or is not a directory
          C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\@nutui+icons-react-taro@0.0.1-beta.8\node_modules\@nutui\icons-react-taro\node_modules doesn't exist or is not a directory
          C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\@nutui+icons-react-taro@0.0.1-beta.8\node_modules\@nutui\node_modules doesn't exist or is not a directory
          C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\@nutui+icons-react-taro@0.0.1-beta.8\node_modules\node_modules doesn't exist or is not a directory
          looking for modules in C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\@nutui+icons-react-taro@0.0.1-beta.8\node_modules
            C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\@nutui+icons-react-taro@0.0.1-beta.8\node_modules\cjs doesn't exist
          looking for modules in C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\node_modules
            C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\.pnpm\node_modules\cjs doesn't exist
          C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\node_modules doesn't exist or is not a directory
          looking for modules in C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules
            C:\Users\cuiliang\FE\APEX\partner-miniapp-nutui\node_modules\cjs doesn't exist
          C:\Users\cuiliang\FE\APEX\node_modules doesn't exist or is not a directory
          C:\Users\cuiliang\FE\node_modules doesn't exist or is not a directory
          C:\Users\cuiliang\node_modules doesn't exist or is not a directory
          C:\Users\node_modules doesn't exist or is not a directory
          C:\node_modules doesn't exist or is not a directory

→ Watching... [2023/7/27 12:01:06]

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Array]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v18.17.0
 ELIFECYCLE  Command failed with exit code 1.
```
          

### 环境信息
```
 Taro CLI 3.6.10 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.17.0 - ~\AppData\Local\fnm_multishells\30324_1690429344225\node.EXE
      npm: 9.6.7 - ~\AppData\Local\fnm_multishells\30324_1690429344225\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.10 => 3.6.10
      @tarojs/components: 3.6.10 => 3.6.10
      @tarojs/helper: 3.6.10 => 3.6.10
      @tarojs/plugin-framework-react: 3.6.10 => 3.6.10
      @tarojs/plugin-html: 3.6.10 => 3.6.10
      @tarojs/plugin-platform-alipay: 3.6.10 => 3.6.10
      @tarojs/plugin-platform-h5: 3.6.10 => 3.6.10
      @tarojs/plugin-platform-jd: 3.6.10 => 3.6.10
      @tarojs/plugin-platform-qq: 3.6.10 => 3.6.10
      @tarojs/plugin-platform-swan: 3.6.10 => 3.6.10
      @tarojs/plugin-platform-tt: 3.6.10 => 3.6.10
      @tarojs/plugin-platform-weapp: 3.6.10 => 3.6.10
      @tarojs/react: 3.6.10 => 3.6.10
      @tarojs/runtime: 3.6.10 => 3.6.10
      @tarojs/shared: 3.6.10 => 3.6.10
      @tarojs/taro: 3.6.10 => 3.6.10
      @tarojs/taro-loader: 3.6.10 => 3.6.10
      @tarojs/webpack5-runner: 3.6.10 => 3.6.10
      babel-preset-taro: 3.6.10 => 3.6.10
      eslint-config-taro: 3.6.10 => 3.6.10
      react: ^18.0.0 => 18.0.0
```

**Comment by TheKonka** [comment]
临时解决方案，可以把  `@tarojs/plugin-framework-react` 降级到 3.6.8 版本

**Comment by cl1107** [comment]
> 临时解决方案，可以把 `@tarojs/plugin-framework-react` 降级到 3.6.8 版本
嗯，降级到3.6.8 可以暂时解决

**Comment by Chen-jj** [comment]
可能与https://github.com/NervJS/taro/pull/14194有关，我们看看的

**Comment by AdvancedCat** [comment]
Posix 与 window 系统下，路径分隔符不一样造成的，原 PR 中的 replace 方法未考虑到 `\` 字符，导致替换失败。

**Comment by yoyo837** [comment]
个人建议再发个版本

**Comment by Chen-jj** [comment]
会的，还有个问题在看哈
