### ISSUE TITLE
thirdScriptError   sdk uncaught third Error   Maximum call stack size exceeded   RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by gclsoft** [NervJS/taro#1430]
```
VM3883:1 thirdScriptError 
 sdk uncaught third Error 
 Maximum call stack size exceeded 
 RangeError: Maximum call stack size exceeded
    at e (http://127.0.0.1:58388/appservice/__dev__/WAService.js:1:660802)
    at e (http://127.0.0.1:58388/appservice/__dev__/WAService.js:1:661058)
    at e (http://127.0.0.1:58388/appservice/__dev__/WAService.js:1:661058)
    at e (http://127.0.0.1:58388/appservice/__dev__/WAService.js:1:661058)
    at e (http://127.0.0.1:58388/appservice/__dev__/WAService.js:1:660990)
    at e (http://127.0.0.1:58388/appservice/__dev__/WAService.js:1:661058)
    at e (http://127.0.0.1:58388/appservice/__dev__/WAService.js:1:661058)
    at e (http://127.0.0.1:58388/appservice/__dev__/WAService.js:1:661058)
    at e (http://127.0.0.1:58388/appservice/__dev__/WAService.js:1:660990)
    at e (http://127.0.0.1:58388/appservice/__dev__/WAService.js:1:661058)
console.error @ VM3883:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1544410684151:4795
window.onerror @ VM3883:1
scriptLoaded @ appservice?t=1544410684151:5678
WAService.js:1 Mon Dec 10 2018 10:58:11 GMT+0800 (中国标准时间) Page route 错误
VM3883:1 Page[pages/home/index/index] not found. May be caused by: 1. Forgot to add page route in app.json. 2. Invoking Page() in async task.
console.warn @ VM3883:1
P @ WAService.js:1
Et @ WAService.js:1
Pt @ WAService.js:1
At @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
ht.emit @ WAService.js:1
emit @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1544410684151:4795
n.registerCallback.t @ appservice?t=1544410684151:4795
l.forEach.t @ appservice?t=1544410684151:4795
(anonymous) @ appservice?t=1544410684151:4795
s.onmessage @ appservice?t=1544410684151:4795
WAService.js:1 Mon Dec 10 2018 10:58:11 GMT+0800 (中国标准时间) Page route 错误
VM3883:1 Page is not constructed because it is not found.
```
编译都没问题，但是在小程序开发者工具里一打开就报错，要怎么解决呢？

**Comment by yuche** [comment]
你要有代码有复现途径才能定位错误，你发一个错误是没有任何意义的

**Comment by gclsoft** [comment]
@yuche 谢谢！解决了问题！

**Comment by atyvee** [comment]
> @yuche 谢谢！解决了问题！

问一下怎么解决的?? 我也出现了这个问题

**Comment by atyvee** [comment]
> 调查之后发现是用循环中的键值 `wx:key` 传入 this 导致爆栈，[7e48dbe](https://github.com/NervJS/taro/commit/7e48dbe91a477b22f3c6ad02fbf2d04c2dcd7a12) 会替换 `this` 并提醒用户修改。

你好, 没看懂是什么问题, 有没有相关详细说明
