### ISSUE TITLE
react-native getMetroConfig 返回Promise

### ISSUE THREAD

**Issue by dagouzhi** [NervJS/taro#14358]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
npm run build:rn

### 期望结果
module.exports = mergeConfig({
  // custom your metro config here
  // https://facebook.github.io/metro/docs/configuration
  resolver: {},
}, getMetroConfig())
正常使用

### 实际结果
react-native getMetroConfig 返回Promise 无法拿到正确配置

### 环境信息
```
Taro CLI 3.6.11 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
      Yarn: 1.22.19 - ~/Library/pnpm/yarn
      npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
    npmPackages:
      @tarojs/cli: ^3.6.12 => 3.6.12 
      @tarojs/components: ^3.6.12 => 3.6.12 
      @tarojs/components-rn: ^3.6.12 => 3.6.12 
      @tarojs/helper: ^3.6.12 => 3.6.12 
      @tarojs/plugin-framework-react: ^3.6.12 => 3.6.12 
      @tarojs/plugin-platform-alipay: ^3.6.12 => 3.6.12 
      @tarojs/plugin-platform-h5: ^3.6.12 => 3.6.12 
      @tarojs/plugin-platform-jd: ^3.6.12 => 3.6.12 
      @tarojs/plugin-platform-qq: ^3.6.12 => 3.6.12 
      @tarojs/plugin-platform-swan: ^3.6.12 => 3.6.12 
      @tarojs/plugin-platform-tt: ^3.6.12 => 3.6.12 
      @tarojs/plugin-platform-weapp: ^3.6.12 => 3.6.12 
      @tarojs/react: ^3.6.12 => 3.6.12 
      @tarojs/rn-runner: ^3.6.12 => 3.6.12 
      @tarojs/rn-supporter: ^3.6.12 => 3.6.12 
      @tarojs/rn-transformer: ^3.6.12 => 3.6.12 
      @tarojs/router-rn: ^3.6.12 => 3.6.12 
      @tarojs/runtime: ^3.6.12 => 3.6.12 
      @tarojs/runtime-rn: ^3.6.12 => 3.6.12 
      @tarojs/shared: ^3.6.12 => 3.6.12 
      @tarojs/taro: ^3.6.12 => 3.6.12 
      @tarojs/taro-loader: ^3.6.12 => 3.6.12 
      @tarojs/taro-rn: ^3.6.12 => 3.6.12 
      @tarojs/webpack5-runner: ^3.6.12 => 3.6.12 
      babel-preset-taro: ^3.6.12 => 3.6.12 
      eslint-config-taro: ^3.6.12 => 3.6.12 
      expo: ^49.0.7 => 49.0.7 
      react: 18.2.0 => 18.2.0 
      react-native: ^0.71.11 => 0.71.12 
```

---
### 补充信息
https://github.com/NervJS/taro/blob/f72825b8c297c9198f5cf41c0da2b86a6b0cfeec/packages/taro-rn-supporter/src/Support.ts#L85

**Comment by zhiqingchen** [comment]
https://github.com/NervJS/taro/blob/next/packages/taro-rn-runner/templates/metro.config.js

**Comment by zhiqingchen** [comment]
模板已更新

**Comment by zhiqingchen** [comment]
同样的错误：

```
error Cannot read properties of undefined (reading 'babelTransformerPath').
TypeError: Cannot read properties of undefined (reading 'babelTransformerPath')
    at /Users/zhiqingchen/ajk/taro-3613/taroDemo/node_modules/metro-config/src/loadConfig.js:140:39
    at Array.reduce (<anonymous>)
    at mergeConfig (/Users/zhiqingchen/ajk/taro-3613/taroDemo/node_modules/metro-config/src/loadConfig.js:96:18)
    at Object.<anonymous> (/Users/zhiqingchen/ajk/taro-3613/taroDemo/metro.config.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
```

**Comment by zhiqingchen** [comment]
重新生成项目，或按上述修改
