### ISSUE TITLE
3.6.14  在配置 h5.miniCssExtractPluginOption.filename 构建以后报错

### ISSUE THREAD

**Issue by lonelyWalkor** [NervJS/taro#14455]
### 相关平台
H5

### 复现仓库
[https://github.com/lonelyWalkor/taro-issus1.git](https://github.com/lonelyWalkor/taro-issus1.git)
**浏览器版本: chrmoe 115**
**使用框架: Vue 2**

### 复现步骤
运行项目 npm run build:h5
打开构建项目 浏览器控制台报错

### 期望结果
能够正常运行

### 实际结果
Uncaught (in promise) Error: TypeError: __webpack_require__.h is not a function
    at _callee$ (619.js:2:396653)
    at tryCatch (app.js:2:199973)
    at Generator.<anonymous> (app.js:2:201647)
    at Generator.throw (app.js:2:200460)
    at rejected (619.js:2:394716)
<img width="757" alt="image" src="https://github.com/NervJS/taro/assets/20573782/f455c52a-2b1e-4a13-b6f6-e5003ea441ca">

### 环境信息
```
Taro v3.6.12


  Taro CLI 3.6.12 environment info:
    System:
      OS: macOS 13.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.18.1 - /opt/homebrew/opt/nvm/versions/node/v16.18.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/opt/nvm/versions/node/v16.18.1/bin/yarn
      npm: 8.19.2 - /opt/homebrew/opt/nvm/versions/node/v16.18.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.14 => 3.6.14 
      @tarojs/components: 3.6.14 => 3.6.14 
      @tarojs/helper: 3.6.14 => 3.6.14 
      @tarojs/plugin-framework-vue2: 3.6.14 => 3.6.14 
      @tarojs/plugin-html: 3.6.14 => 3.6.14 
      @tarojs/plugin-platform-alipay: 3.6.14 => 3.6.14 
      @tarojs/plugin-platform-h5: 3.6.14 => 3.6.14 
      @tarojs/plugin-platform-jd: 3.6.14 => 3.6.14 
      @tarojs/plugin-platform-qq: 3.6.14 => 3.6.14 
      @tarojs/plugin-platform-swan: 3.6.14 => 3.6.14 
      @tarojs/plugin-platform-tt: 3.6.14 => 3.6.14 
      @tarojs/plugin-platform-weapp: 3.6.14 => 3.6.14 
      @tarojs/runtime: 3.6.14 => 3.6.14 
      @tarojs/shared: 3.6.14 => 3.6.14 
      @tarojs/taro: 3.6.14 => 3.6.14 
      @tarojs/taro-loader: 3.6.14 => 3.6.14 
      @tarojs/webpack5-runner: 3.6.14 => 3.6.14 
      babel-preset-taro: 3.6.14 => 3.6.14 
      eslint-config-taro: 3.6.14 => 3.6.14
```

**Comment by ZakaryCode** [comment]
这应当是 webpack 自己的问题，在识别 `[fullhash:base64]` 替换时，并未注入 `RuntimeGlobals.getFullHash` 方法，可以自行写个插件规避该问题，或者去掉 `:base64` 亦可
