### ISSUE TITLE
h5编译失败，微信小程序端是

### ISSUE THREAD

**Issue by lyf103104** [NervJS/taro#1445]
开始编译项目 weapp_new
创建  发现文件  src/app.scss
创建  发现文件  src/app.tsx
{ TypeError: unknown: Property property of MemberExpression expected node to be of a type ["Identifier"] but instead got "StringLiteral"
    at validate (/Users/Charles/.nvm/versions/node/v8.9.3/lib/node_modules/@tarojs/cli/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/Users/Charles/.nvm/versions/node/v8.9.3/lib/node_modules/@tarojs/cli/node_modules/babel-types/lib/definitions/core.js:412:50)
    at Object.validate (/Users/Charles/.nvm/versions/node/v8.9.3/lib/node_modules/@tarojs/cli/node_modules/babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (/Users/Charles/.nvm/versions/node/v8.9.3/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath.replaceWith (/Users/Charles/.nvm/versions/node/v8.9.3/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/replacement.js:160:8)
    at replaceAndEvaluateNode (/Users/Charles/.nvm/versions/node/v8.9.3/lib/node_modules/@tarojs/cli/node_modules/babel-plugin-transform-define/lib/index.js:117:12)
    at processNode (/Users/Charles/.nvm/versions/node/v8.9.3/lib/node_modules/@tarojs/cli/node_modules/babel-plugin-transform-define/lib/index.js:143:5)
    at PluginPass.Identifier (/Users/Charles/.nvm/versions/node/v8.9.3/lib/node_modules/@tarojs/cli/node_modules/babel-plugin-transform-define/lib/index.js:23:9)
    at newFn (/Users/Charles/.nvm/versions/node/v8.9.3/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/Charles/.nvm/versions/node/v8.9.3/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:76:18) _babel: true }
创建  发现文件  src/index.html
创建  发现文件  src/components/index.ts
创建  发现文件  src/constants/country.ts
创建  发现文件  src/constants/credentials-type.ts
创建  发现文件  src/constants/event-center.ts
创建  发现文件  src/constants/index.ts
创建  发现文件  src/interfaces/amount.ts
创建  发现文件  src/interfaces/api.ts
...
Failed to compile.

multi (webpack)-dev-server/client?http://127.0.0.1:10086 (webpack)/hot/dev-server.js ./.temp/app.js
Module not found: Can't resolve '/Users/Charles/Documents/Charles/Code/co-mall/zhongmian/weapp/.temp/app.js' in '/Users/Charles/Documents/Charles/Code/co-mall/zhongmian/weapp'

**Comment by luckyadam** [comment]
项目发出来看下

**Comment by lyf103104** [comment]
已找到问题原因，关闭问题。

**Comment by tourze** [comment]
@lyf103104 你好。我遇到同样的问题，能请教下是什么原因吗？

**Comment by gaoshijun1993** [comment]
遇到同样问题。。
