### ISSUE TITLE
添加mobx相关依赖、更新全部依赖后报错

### ISSUE THREAD

**Issue by hnsxxscyx** [NervJS/taro#1453]
**问题描述**
依照文档安装了mobx相关依赖，配置后无法 import @tarojs/mobx相关，重复安装此依赖问题无法解决，遂更新全部依赖，然后h5和小程序都无法编译了。

h5报错：
```
(node:56832) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of undefined
    at Object.<anonymous> (C:\Users\Administrator\Documents\GitHub\react-style\myApp\node_modules\_chalk@2.4.1@chalk\index.js:72:75)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\Documents\GitHub\react-style\myApp\node_modules\_@tarojs_webpack-runner@1.0.7@@tarojs\webpack-runner\dist\index.js:11:17)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
(node:56832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:56832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
weapp报错：
```
{ Error: Cannot find module 'core-js/library/fn/get-iterator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\Documents\GitHub\react-style\myApp\node_modules\babel-runtime\core-js\get-iterator.js:1:93)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3) code: 'MODULE_NOT_FOUND' }
编译  所有页面
(node:64004) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pages' of undefined
    at buildPages (C:\Program Files\nodejs\node_modules\@tarojs\cli\src\weapp.js:1111:27)
    at Object.build (C:\Program Files\nodejs\node_modules\@tarojs\cli\src\weapp.js:2080:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
(node:64004) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:64004) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [Taro v1.2.0-beta.7]
 - 报错平台 [h5, weapp]

**Comment by hnsxxscyx** [comment]
贴一张当前依赖版本：![image](https://user-images.githubusercontent.com/13851292/49784881-9b0c6e80-fd59-11e8-8536-ff3c024ac299.png)
应该是版本问题，重新init了一个空白项目，dev:h5后浏览器报错Can not find proper registered route for '/'。
空白项目降级至
![image](https://user-images.githubusercontent.com/13851292/49784962-db6bec80-fd59-11e8-9b0a-d961e6c07a99.png)，

**Comment by Littly** [comment]
删除node_modules，重装依赖试试？
