### ISSUE TITLE
Taro 3希望支持快应用

### ISSUE THREAD

**Issue by fortune1992** [NervJS/taro#14530]
### 这个特性解决了什么问题？
测试发现Taro 3编译快应用时报错：不存在编译平台quickapp。导致我使用Taro 3开发时，无法兼容快应用。
taro build --type quickapp --watch

👽 Taro v3.6.15

/usr/local/share/.config/yarn/global/node_modules/@tarojs/service/dist/Kernel.js:262
            throw new Error(`不存在编译平台 ${platform}`);
                  ^

Error: 不存在编译平台 quickapp
    at Kernel.runWithPlatform (/usr/local/share/.config/yarn/global/node_modules/@tarojs/service/src/Kernel.ts:315:13)
    at Kernel.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/@tarojs/service/src/Kernel.ts:371:26)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/share/.config/yarn/global/node_modules/@tarojs/service/dist/Kernel.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.17.1

现在想到的解决方案是：
小程序端使用taro 3编译，快应用降级到taro 2编译，不知道这种做法是否可行？是否存在未知问题？
麻烦大佬帮忙解答下。

### 这个 API 长什么样？
期望taro 3支持快应用。

**Comment by TheKonka** [comment]
https://github.com/NervJS/taro/discussions/13314

**Comment by Chen-jj** [comment]
官方将不会考虑支持

**Comment by dlutwuwei** [comment]
https://docs.taro.zone/docs/quick-app/#%E5%BF%AB%E5%BA%94%E7%94%A8%E9%85%8D%E7%BD%AE
