### ISSUE TITLE
taro h5本地正常打包后运行报错

### ISSUE THREAD

**Issue by jsyanyang** [NervJS/taro#14618]
### 相关平台
H5

**浏览器版本: 版本 116.0.5845.188（正式版本） （64 位）**
**使用框架: React**

### 复现步骤
npm run build:h5

### 期望结果
h5打包后运行正常

### 实际结果
h5打包后运行报错

### 环境信息
```
 taro info
👽 Taro v3.6.17


  Taro CLI 3.6.17 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.20.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
      npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.17 => 3.6.17
      @tarojs/components: 3.6.17 => 3.6.17
      @tarojs/helper: 3.6.17 => 3.6.17
      @tarojs/mini-runner: 3.6.17 => 3.6.17
      @tarojs/plugin-framework-react: 3.6.17 => 3.6.17
      @tarojs/plugin-html: 3.6.17 => 3.6.17
      @tarojs/plugin-platform-alipay: 3.6.17 => 3.6.17
      @tarojs/plugin-platform-h5: 3.6.17 => 3.6.17
      @tarojs/plugin-platform-jd: 3.6.17 => 3.6.17
      @tarojs/plugin-platform-qq: 3.6.17 => 3.6.17
      @tarojs/plugin-platform-swan: 3.6.17 => 3.6.17
      @tarojs/plugin-platform-tt: 3.6.17 => 3.6.17
      @tarojs/plugin-platform-weapp: 3.6.17 => 3.6.17
      @tarojs/react: 3.6.17 => 3.6.17
      @tarojs/runtime: 3.6.17 => 3.6.17
      @tarojs/shared: 3.6.17 => 3.6.17
      @tarojs/taro: 3.6.17 => 3.6.17
      @tarojs/webpack5-runner: 3.6.17 => 3.6.17
      babel-preset-taro: 3.6.17 => 3.6.17
      eslint-config-taro: 3.6.17 => 3.6.17
      react: ^18.0.0 => 18.2.0
      taro-ui: 3.1.0-beta.4 => 3.1.0-beta.4
```

---
### 补充信息
![image](https://github.com/NervJS/taro/assets/94437201/d3c573f0-25ec-41a1-82f6-0ba8bf4cdc81)

app.js:2 TypeError: fe.ZP.createInnerAudioContext is not a function
    at App (app.js:2:640182)
    at Xh (app.js:2:499273)
    at Wk (app.js:2:560654)
    at Vk (app.js:2:549040)
    at Uk (app.js:2:548967)
    at Jk (app.js:2:548826)
    at Ok (app.js:2:545418)
    at Hk (app.js:2:543862)
    at J (app.js:2:593870)
    at MessagePort.R (app.js:2:594444)
Mi @ app.js:2
app.js:2 Uncaught TypeError: fe.ZP.createInnerAudioContext is not a function
    at App (app.js:2:640182)
    at Xh (app.js:2:499273)
    at Wk (app.js:2:560654)
    at Vk (app.js:2:549040)
    at Uk (app.js:2:548967)
    at Jk (app.js:2:548826)
    at Ok (app.js:2:545418)
    at Hk (app.js:2:543862)
    at J (app.js:2:593870)
    at MessagePort.R (app.js:2:594444)
447.js:2 Uncaught (in promise) Error: TypeError: x.ZP.createInnerAudioContext is not a function
    at _callee$ (447.js:2:106867)
    at tryCatch (app.js:2:712845)
    at Generator.<anonymous> (app.js:2:714626)
    at Generator.throw (app.js:2:713355)
    at rejected (447.js:2:104930)

**Comment by ZakaryCode** [comment]
看起来可能使用了特殊编译模式，请提交完整示例用于定位问题。

**Comment by jsyanyang** [comment]
现在本地也不行了
![Uploading image.png…]()
