### ISSUE TITLE
taro3的sourcemap怎么跟小程序后台We分析结合起来定位错误呢?

### ISSUE THREAD

**Issue by jackple** [NervJS/taro#14681]
### 这个特性解决了什么问题？
非本地环境的错误定位

### 这个 API 长什么样？
目前使用小程序开发者工具插件https://developers.weixin.qq.com/miniprogram/dev/devtools/sourcemap.html

小程序后台We分析的错误堆栈如下
```js
Cannot read properties of undefined (reading \'target_id\')
TypeError: Cannot read properties of undefined (reading \'target_id\')
at https://subPackages/customer/subPackages/customer/sub-vendors.js:1:140731
at f (https://vendors.js:1:218120)
at Generator._invoke (https://vendors.js:1:217873)
at Generator.next (https://vendors.js:1:218483)
at r (https://vendors.js:1:211575)
at u (https://vendors.js:1:211780)
at https://vendors.js:1:211839
at e.<anonymous> (https://vendors.js:1:211720)
at e.<anonymous> (https://subPackages/customer/subPackages/customer/sub-vendors.js:1:141089)
at ze (https://vendors.js:1:26572)
at ObservableObject.key (https://vendors.js:1:26095)
at https://subPackages/customer/subPackages/customer/sub-vendors.js:1:150594
```

输入哪一个行号都无法定位到错误, 提示未匹配到结果, 看着像是小程序的功能是日久失修了

请问有比较完善的方案吗?

**Comment by jackple** [comment]
后来通过直接打开taro构建出来的/sub-vendors.js:1:140731, 能大概定位到
