### ISSUE TITLE
npm run build:weapp 报错

### ISSUE THREAD

**Issue by ruanxiaoquan** [NervJS/taro#147]
ReferenceError: Unknown plugin "transform-class-properties" specified in "base" at 0, attempted to resolve relative to "/Users/ruanxiaoquan/elys/taro"
    at /Users/ruanxiaoquan/elys/taro/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/ruanxiaoquan/elys/taro/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/ruanxiaoquan/elys/taro/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/ruanxiaoquan/elys/taro/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/ruanxiaoquan/elys/taro/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/ruanxiaoquan/elys/taro/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/ruanxiaoquan/elys/taro/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at babel (/Users/ruanxiaoquan/elys/taro/node_modules/@tarojs/plugin-babel/index.js:6:17)
    at Object.callPlugin (/usr/local/lib/node_modules/@tarojs/cli/src/util/npm.js:109:10)

**Comment by ruanxiaoquan** [comment]
把node_modules 删除，重新安装一次依赖，好了。。

**Comment by luckyadam** [comment]
好嘞~
