### ISSUE TITLE
小程序引用插件代码转换成Taro代码报错

### ISSUE THREAD

**Issue by gd-ldj** [NervJS/taro#14743]
### 相关平台
微信小程序

**小程序基础库: 3.0.2**
**使用框架: React**

### 复现步骤
组件json内配置useComponents引用插件的方式，即可复现，例如 "ezxr-arsession": "plugin://ezxrARSession/ARSession",

### 期望结果
正常转换

### 实际结果
错误  组件转换  plugin:/ezxrARSession/ARSession.js
Error: 组件 E:\ezxr\EZXRWeb\wx_research_template\wx-innerc6-nav\plugin:\ezxrARSession\ARSession 没有 JS 文件！
    at C:\Users\ezxr.lideju\AppData\Roaming\npm-cache\_npx\8532\node_modules\@tarojs\cli-convertor\dist\index.js:631:27
    at Set.forEach (<anonymous>)
    at Convertor.traverseComponents (C:\Users\ezxr.lideju\AppData\Roaming\npm-cache\_npx\8532\node_modules\@tarojs\cli-convertor\dist\index.js:617:20)
    at C:\Users\ezxr.lideju\AppData\Roaming\npm-cache\_npx\8532\node_modules\@tarojs\cli-convertor\dist\index.js:685:22
    at Set.forEach (<anonymous>)
    at Convertor.traverseComponents (C:\Users\ezxr.lideju\AppData\Roaming\npm-cache\_npx\8532\node_modules\@tarojs\cli-convertor\dist\index.js:617:20)
    at C:\Users\ezxr.lideju\AppData\Roaming\npm-cache\_npx\8532\node_modules\@tarojs\cli-convertor\dist\index.js:605:22
    at Set.forEach (<anonymous>)
    at Convertor.traversePages (C:\Users\ezxr.lideju\AppData\Roaming\npm-cache\_npx\8532\node_modules\@tarojs\cli-convertor\dist\index.js:514:20)
    at Convertor.run (C:\Users\ezxr.lideju\AppData\Roaming\npm-cache\_npx\8532\node_modules\@tarojs\cli-convertor\dist\index.js:834:14)

### 环境信息
```
👽 Taro v3.6.18


  Taro CLI 3.6.18 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.19.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.18 => 3.6.18
      @tarojs/components: 3.6.18 => 3.6.18
      @tarojs/helper: 3.6.18 => 3.6.18
      @tarojs/plugin-framework-react: 3.6.18 => 3.6.18
      @tarojs/plugin-platform-alipay: 3.6.18 => 3.6.18
      @tarojs/plugin-platform-h5: 3.6.18 => 3.6.18
      @tarojs/plugin-platform-jd: 3.6.18 => 3.6.18
      @tarojs/plugin-platform-qq: 3.6.18 => 3.6.18
      @tarojs/plugin-platform-swan: 3.6.18 => 3.6.18
      @tarojs/plugin-platform-tt: 3.6.18 => 3.6.18
      @tarojs/plugin-platform-weapp: 3.6.18 => 3.6.18
      @tarojs/runtime: 3.6.18 => 3.6.18
      @tarojs/shared: 3.6.18 => 3.6.18
      @tarojs/taro: 3.6.18 => 3.6.18
      @tarojs/taro-loader: 3.6.18 => 3.6.18
      @tarojs/webpack5-runner: 3.6.18 => 3.6.18
      babel-preset-taro: 3.6.18 => 3.6.18
      eslint-config-taro: 3.6.18 => 3.6.18

```

**Comment by qican777** [comment]
小程序插件的转换支持目前正在开发中
