### ISSUE TITLE
创建项目报错

### ISSUE THREAD

**Issue by sqs8866** [NervJS/taro#14788]
### 相关平台
微信小程序

**小程序基础库: 111**
**使用框架: React**

### 复现步骤
taro info,或者taro init my App.。使用taro命令就报错

### 期望结果
正常创建项目

### 实际结果
 info
� Taro v3.6.5

Error: Bindings not found
    at Compiler.transformSync (E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\@swc\core\index.js:250:15)
    at Object.transformSync (E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\@swc\core\index.js:348:21)
    at compile (E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\@swc\register\lib\node.js:76:22)
    at compileHook (E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\@swc\register\lib\node.js:91:16)
    at Module._compile (E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\pirates\lib\index.js:113:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.newLoader [as .js] (E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
Error: Bindings not found
    at Compiler.transformSync (E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\@swc\core\index.js:250:15)
    at Object.transformSync (E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\@swc\core\index.js:348:21)
    at compile (E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\@swc\register\lib\node.js:76:22)
    at compileHook (E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\@swc\register\lib\node.js:91:16)
    at Module._compile (E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\pirates\lib\index.js:113:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.newLoader [as .js] (E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\utils\index.js:75
                    throw new Error(`插件依赖 "${item}" 加载失败，请检查插件配置`);
                          ^

Error: 插件依赖 "E:\nvm\v16.17.1\node_modules\@tarojs\cli\dist\presets\index.js" 加载失败，请检查插件配置
    at apply (E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\utils\index.js:75:27)
    at Kernel.initPreset (E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:94:38)
    at Kernel.resolvePresets (E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:79:18)
    at Kernel.initPresetsAndPlugins (E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:73:14)
    at Kernel.<anonymous> (E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:265:18)
    at Generator.next (<anonymous>)
    at E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:4:12)
    at Kernel.run (E:\nvm\v16.17.1\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:249:16)

### 环境信息
```
taro info
👽 Taro v3.0.7



  Taro CLI 3.0.7 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 13.14.0 - ~/.nvm/versions/node/v13.14.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v13.14.0/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v13.14.0/bin/npm
    npmPackages:
      @tarojs/components: 1.3.27 => 1.3.27
      @tarojs/router: 1.3.27 => 1.3.27
      @tarojs/taro: 1.3.27 => 1.3.27
      @tarojs/taro-h5: 1.3.27 => 1.3.27
      @tarojs/webpack-runner: 1.3.27 => 1.3.27
      eslint-config-taro: 1.3.27 => 1.3.27
      eslint-plugin-taro: 1.3.27 => 1.3.27
      nerv-devtools: 1.5.5 => 1.5.5
      nervjs: 1.5.5 => 1.5.5
以上信息不对，是随便找了个信息附上去的，因为必须要附，不然不能提issue ，实际是用taro info 命令的时候就报错了，跟上面的报错一样
```

**Comment by yoyo837** [comment]
看看是这个吗? https://github.com/NervJS/taro/issues/14785

**Comment by sqs8866** [comment]
> 看看是这个吗? #14785

不是一个

**Comment by sujingApril** [comment]
这个问题怎么解决的呢，我也遇到了同样的问题
