### ISSUE TITLE
编译运行后报错

### ISSUE THREAD

**Issue by CrazyLambF** [NervJS/taro#14817]
### 相关平台
支付宝小程序

**小程序基础库: 1.25.9**
**使用框架: React**

### 复现步骤
编译运行，提示报错TypeError: Function(...) is not a function
    at Object.node_modulesBabelRuntimeRegeneratorIndexJs (app.js:821:1)
    at __webpack_require__ (runtime.js:80:1)
    at Module.node_modulesDvaCoreDistIndexEsmJs (app.js:1092:1)
    at __webpack_require__ (runtime.js:80:1)
    at Module.<anonymous> (app.js:6517:1)
    at Module.srcUtilsDvaJs (app.js:6564:1)
    at __webpack_require__ (runtime.js:80:1)
    at Module.node_modulesTarojsMiniRunnerDistLoadersWxTransformerLoaderJsSrcAppJsxTaroTypeScriptParseENTRY (app.js:844:1)
    at __webpack_require__ (runtime.js:80:1)
    at Module.srcAppJsxTaroTypeScriptParseENTRY (app.js:6204:1)

### 期望结果
不报错，稳定运行

### 实际结果
有报错无法运行

### 环境信息
```
👽 Taro v2.2.16


  Taro CLI 2.2.16 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
    npmPackages:
      @tarojs/cli: 2.2.16 => 2.2.16 
      @tarojs/components: 2.2.16 => 2.2.16 
      @tarojs/components-qa: 2.2.16 => 2.2.16 
      @tarojs/components-rn: 2.2.16 => 2.2.16 
      @tarojs/mini-runner: 2.2.16 => 2.2.16 
      @tarojs/plugin-sass: ^2.2.10 => 2.2.10 
      @tarojs/redux: 2.2.16 => 2.2.16 
      @tarojs/redux-h5: 2.2.16 => 2.2.16 
      @tarojs/rn-runner: 2.2.16 => 2.2.16 
      @tarojs/router: 2.2.16 => 2.2.16 
      @tarojs/taro: 2.2.16 => 2.2.16 
      @tarojs/taro-alipay: 2.2.16 => 2.2.16 
      @tarojs/taro-h5: 2.2.16 => 2.2.16 
      @tarojs/taro-qq: 2.2.16 => 2.2.16 
      @tarojs/taro-quickapp: 2.2.16 => 2.2.16 
      @tarojs/taro-redux-rn: 2.2.16 => 2.2.16 
      @tarojs/taro-rn: 2.2.16 => 2.2.16 
      @tarojs/taro-router-rn: 2.2.16 => 2.2.16 
      @tarojs/taro-swan: 2.2.16 => 2.2.16 
      @tarojs/taro-tt: 2.2.16 => 2.2.16 
      @tarojs/taro-weapp: 2.2.16 => 2.2.16 
      @tarojs/webpack-runner: 2.2.16 => 2.2.16 
      eslint-config-taro: 2.2.16 => 2.2.16 
      eslint-plugin-taro: 2.2.16 => 2.2.16 
      nerv-devtools: ^1.5.7 => 1.5.7 
      nervjs: ^1.5.7 => 1.5.7 
      react: 16.8.0 => 16.8.0 
      react-native: 0.59.9 => 0.59.9 
      stylelint-config-taro-rn: 2.2.16 => 2.2.16 
      stylelint-taro-rn: 2.2.16 => 2.2.16 
      taro-ui: ^2.3.1 => 2.3.4 

```

**Comment by TheKonka** [comment]
#14814 #13681 #13234
