### ISSUE TITLE
VirtualList 无法添加 onScrollToLower 回调

### ISSUE THREAD

**Issue by kong-dev** [NervJS/taro#15039]
### 相关平台
H5

### 复现仓库
[https://github.com/kong-dev/taro-bug.git](https://github.com/kong-dev/taro-bug.git)
**浏览器版本: Chrome 120**
**使用框架: React**

### 复现步骤

H5 环境中，VirtualList 添加 onScrollToLower 或 onScrollToUpper 回调都会报错

- clone 仓库
- pnpm install
- pnpm run dev:h5

### 期望结果
回调函数可用

### 实际结果
不可用，控制台报错：
```
Uncaught Error: Argument appears to not be a ReactComponent. Keys: onLoad,onUnload,onReady,onShow,onHide,onPullDownRefresh,onReachBottom,onPageScroll,onResize,onTabItemTap,onTitleClick,onOptionMenuClick,onPopMenuClick,onPullIntercept,onAddToFavorites,eh,data,options,config,$taroPath,path,$taroParams
    at findHostInstanceWithWarning (vendors-node_modules_taro_h5_prebundle_chunk-CRYYUZDT_js._chunkhash_.js:20695:39)
    at Object.findDOMNode (vendors-node_modules_taro_h5_prebundle_chunk-CRYYUZDT_js._chunkhash_.js:21358:32)
    at TaroHooks.<anonymous> (vendors-node_modules_taro_h5_prebundle_chunk-PFBM2DM5_js._chunkhash_.js:214:30)
    at TaroHooks.call (vendors-node_modules_taro_h5_prebundle_chunk-KIJKAK55_js._chunkhash_.js:804:84)
    at findDOM (vendors-node_modules_taro_h5_prebundle_chunk-IWXG5VQN_js._chunkhash_.js:12457:70)
    at get container [as container] (vendors-node_modules_taro_h5_prebundle_chunk-IWXG5VQN_js._chunkhash_.js:19405:55)
    at TaroH5IntersectionObserver.relativeTo (vendors-node_modules_taro_h5_prebundle_chunk-IWXG5VQN_js._chunkhash_.js:19477:27)
    at Preset.boundaryDetectionHelper (preset.js:192:14)
    at SelectorQuery.eval (preset.js:171:40)
    at vendors-node_modules_taro_h5_prebundle_chunk-IWXG5VQN_js._chunkhash_.js:19771:90
```

### 环境信息
```
👽 Taro v3.6.21


  Taro CLI 3.6.21 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.5.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.21 => 3.6.21 
      @tarojs/components: 3.6.21 => 3.6.21 
      @tarojs/helper: 3.6.21 => 3.6.21 
      @tarojs/mini-runner: 3.6.21 => 3.6.21 
      @tarojs/plugin-framework-react: 3.6.21 => 3.6.21 
      @tarojs/plugin-platform-h5: 3.6.21 => 3.6.21 
      @tarojs/plugin-platform-weapp: 3.6.21 => 3.6.21 
      @tarojs/react: 3.6.21 => 3.6.21 
      @tarojs/runtime: 3.6.21 => 3.6.21 
      @tarojs/service: 3.6.21 => 3.6.21 
      @tarojs/shared: 3.6.21 => 3.6.21 
      @tarojs/taro: 3.6.21 => 3.6.21 
      @tarojs/taro-h5: 3.6.21 => 3.6.21 
      @tarojs/webpack5-runner: 3.6.21 => 3.6.21 
      babel-preset-taro: 3.6.21 => 3.6.21 
      eslint-config-taro: 3.6.21 => 3.6.21 
      react: ^18.2.0 => 18.2.0 

```

---
### 补充信息

- 问题出在 `VirtualList` 内部使用了 `Taro.createIntersectionObserver()` ；
- 其 `component` 参数为 `Taro.getCurrentInstance().page`，这个并不是 React 组件的实例；
- 调用到 ReactDom.findDOM 的时候就出错了。

**Comment by ZEJIA-LIU** [comment]
你好，我测试了一下，并没有复现你所描述的问题。方便提供一个可以复现的demo来协助我修复你的问题么？感谢～

**Comment by kong-dev** [comment]
Taro v3.6.24 已经修复了
