### ISSUE TITLE
ubuntu20.04下taro init 报错

### ISSUE THREAD

**Issue by vdfor** [NervJS/taro#15061]
### 相关平台
H5

**浏览器版本: NodeJS 20**
**使用框架: React**

### 复现步骤
报错信息如下：
👽 Taro v3.6.22

⚠ 获取 taro 全局配置文件失败，不存在全局配置文件：/root/.taro-global-config/index.json
node:internal/modules/cjs/loader:1327
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/local/share/.config/yarn/global/node_modules/@tarojs/binding-linux-x64-gnu/taro.linux-x64-gnu.node: undefined symbol: __libc_single_threaded
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1327:18)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/@tarojs/binding/binding.js:188:31)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.newLoader [as .js] (/usr/local/share/.config/yarn/global/node_modules/pirates/lib/index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1091:32) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v20.9.0

### 期望结果
Taro init 正常

### 实际结果
Taro init 出错

### 环境信息
```
Taro v3.6.22


  Taro CLI 3.6.22 environment info:
ubuntu 20.04
node 20.9.0
```

**Comment by jamessawyer** [comment]
Taro: v3.6.23
Node: v18.16.0
操作系统：WLS Ubuntu 20.04.6 LTS
报同样的错误，
```bash
 获取 taro 全局配置文件失败，不存在全局配置文件：/home/xxx/.taro-global-config/index.json
node:internal/modules/cjs/loader:1338
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/binding-linux-x64-gnu/taro.linux-x64-gnu.node: undefined symbol: __libc_single_threaded
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/binding/binding.js:188:31)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.newLoader [as .js] (/usr/local/lib/node_modules/@tarojs/cli/node_modules/pirates/lib/index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1117:32) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.16.0
```

**Comment by luckyadam** [comment]
@vdfor 你这个问题应该升级到 3.6.23 就修复了

**Comment by weikangqq** [comment]
![img_v3_027l_1b546e51-14b0-4fdb-b8a3-a0fe8c21debg](https://github.com/NervJS/taro/assets/20835251/1c500e18-9540-416a-a7ec-d5adbeb02f88)
我也一样 升级到3.6.23不行

**Comment by weikangqq** [comment]
@luckyadam 
![image](https://github.com/NervJS/taro/assets/20835251/8d3e8620-0c70-465c-8f7c-43784d64d3da)

**Comment by vdfor** [comment]
> @vdfor 你这个问题应该升级到 3.6.23 就修复了

不行，还是报错

root@iZj6c:~/demo# taro init demo3
👽 Taro v3.6.23

⚠ 获取 taro 全局配置文件失败，不存在全局配置文件：/root/.taro-global-config/index.json
node:internal/modules/cjs/loader:1327
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/local/share/.config/yarn/global/node_modules/@tarojs/binding-linux-x64-gnu/taro.linux-x64-gnu.node: undefined symbol: __libc_single_threaded
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1327:18)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/@tarojs/binding/binding.js:188:31)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.newLoader [as .js] (/usr/local/share/.config/yarn/global/node_modules/pirates/lib/index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1091:32) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v20.9.0

**Comment by dayeguilaiye** [comment]
一样的错误，请问有进展吗？或者是否有规避方法？ @Chen-jj @luckyadam

**Comment by vdfor** [comment]
实测 3.6.24 已解决

**Comment by suchcl** [comment]
升级到3.6.24之后执行taro init,先提示不存在全局配置文件,然后又开始正常初始化项目了.
![err](https://github.com/user-attachments/assets/d3099b7b-42bb-4b04-933c-a52771852745)
