### ISSUE TITLE
3.6.22 在centos7 上构建失败  code: 'ERR_DLOPEN_FAILED'

### ISSUE THREAD

**Issue by Jinx-1120** [NervJS/taro#15147]
### 相关平台
微信小程序

**小程序基础库: 2.27.3**
**使用框架: React**

### 复现步骤
初始化新项目即可在centos7  
npm run build :weapp

### 期望结果
能够正常构建

### 实际结果
Error: /var/jenkins_home/workspace/frontend-xiaolai-checkin-test/node_modules/@tarojs/binding-linux-x64-gnu/taro.linux-x64-gnu.node: undefined symbol: _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1282:18)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/jenkins_home/workspace/frontend-xiaolai-checkin-test/node_modules/@tarojs/binding/binding.js:188:31)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Object.newLoader [as .js] (/var/jenkins_home/workspace/frontend-xiaolai-checkin-test/node_modules/pirates/lib/index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1076:32) {
  code: 'ERR_DLOPEN_FAILED'
}

### 环境信息
```
👽 Taro v3.6.23


  Taro CLI 3.6.23 environment info:
    System:
      OS: Linux .el7.ucloud.x86_64 #1 SMP Wed Apr 28 09:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
    Binaries:
      Node: 16 
    npmPackages:
      @tarojs/cli: 3.6.23 => 3.6.23 
      @tarojs/components: 3.6.23 => 3.6.23 
      @tarojs/helper: 3.6.23 => 3.6.23 
      @tarojs/plugin-framework-react: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-weapp: 3.6.23 => 3.6.23 
      @tarojs/react: 3.6.23 => 3.6.23 
      @tarojs/runtime: 3.6.23 => 3.6.23 
      @tarojs/shared: 3.6.23 => 3.6.23 
      @tarojs/taro: 3.6.23 => 3.6.23 
      @tarojs/taro-loader: 3.6.23 => 3.6.23 
      @tarojs/webpack5-runner: 3.6.23 => 3.6.23 
      babel-preset-taro: 3.6.23 => 3.6.23 
      eslint-config-taro: 3.6.23 => 3.6.23 
      react: ^18.2.0 => 18.2.0 
```

**Comment by Jinx-1120** [comment]
#15033 #15033 应该都是同一类问题

**Comment by vdfor** [comment]
应该是的，3.6.23 更新了 CI - 降低 Ubuntu 版本到 20.04, 但感觉在不同的CI构建环境下还是有问题。

**Comment by vdfor** [comment]
最好是构建时能够指定是否走rust模块，这样本地非linux系统构建可以走rust，线上发布 ci 构建指定不走rust桥接以避免无法构建的问题。

**Comment by Jinx-1120** [comment]
降级到了3.6.20 去除了@tarojs/binding

**Comment by lanzifeng118** [comment]
同样遇到这样的问题

**Comment by luckyadam** [comment]
升级到 3.6.23 这个问题还有么

**Comment by Jinx-1120** [comment]
3.6.23问题仍然存在

**Comment by tangbzai** [comment]
我之前也遇到了类似的问题（`...taro.linux-x64-gnu.node: undefined symbol...`），升级到3.6.24之后就没出现了
