### ISSUE TITLE
微信小程序项目反编译成taro项目后再打包成其他端项目文件缺失问题

### ISSUE THREAD

**Issue by eric1121** [NervJS/taro#1515]
**问题描述**
现有的微信小程序项目全局安装taro脚手架后，用taro convert编译成taro项目，然后install依赖后，再在taroConvert文件里打包成其他端文件时会有文件缺失，导致报错

**复现步骤**
[复现问题的步骤]
1.npm i -g @tarojs/cli
2. 在项目根目录taro convert
3. 进入taroConvert后install
4. 再用taro build XXX打包

![image](https://user-images.githubusercontent.com/24478669/49982691-e52f6300-ff98-11e8-9650-2c14491fc5dc.png)
![image](https://user-images.githubusercontent.com/24478669/49982695-ebbdda80-ff98-11e8-9f81-c64cd25c9496.png)

```

**期望行为**
希望用taro build 能正常转换

**报错信息**
未找到 app.json 中的定义的 pages "pages/mycenter/mycenter" 对应的 WXML 文件
![image](https://user-images.githubusercontent.com/24478669/49982722-19a31f00-ff99-11e8-90c2-a6f168bef5ed.png)

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]
![image](https://user-images.githubusercontent.com/24478669/49982746-43f4dc80-ff99-11e8-879c-05109f2b32f5.png)

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
taro convert 的日志发出来看下

**Comment by niuben1983** [comment]
我也出现了这个问题，app.json没有生成，
编译日志：
`UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/niuben/maotai/fe/wx-article/taroConvert/src/app'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at buildEntry (/usr/local/lib/node_modules/@tarojs/cli/src/weapp.js:1028:28)
    at Object.build (/usr/local/lib/node_modules/@tarojs/cli/src/weapp.js:2115:21)
    at buildForWeapp (/usr/local/lib/node_modules/@tarojs/cli/src/build.js:48:22)
    at build (/usr/local/lib/node_modules/@tarojs/cli/src/build.js:25:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/bin/taro-build:52:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
(node:75499) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:75499) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by luckyadam** [comment]
@niuben1983 看下 convert 出来的 app.js
