### ISSUE TITLE
3.6.23 在Linux 4.9 Debian GNU 上构建失败 code: 'ERR_DLOPEN_FAILED'

### ISSUE THREAD

**Issue by lanzifeng118** [NervJS/taro#15187]
### 相关平台
微信小程序

**小程序基础库: 3.2.0**
**使用框架: React**

### 复现步骤
npm run build :weapp

### 期望结果
正常构建

### 实际结果
Taro v3.6.23

Error: /builds/xf/xf-mall/weavefuture/frondend/xf-frontend-mini-program/node_modules/@tarojs/binding-linux-x64-gnu/taro.linux-x64-gnu.node: undefined symbol: __libc_single_threaded
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1282:18)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/builds/xf/xf-mall/weavefuture/frondend/xf-frontend-mini-program/node_modules/@tarojs/binding/binding.js:188:31)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Object.newLoader [as .js] (/builds/xf/xf-mall/weavefuture/frondend/xf-frontend-mini-program/node_modules/pirates/lib/index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1076:32) {
  code: 'ERR_DLOPEN_FAILED'
}
找不到项目配置文件config/index，请确定当前目录是 Taro 项目根目录!

### 环境信息
```
Taro CLI 3.6.23 environment info: 
System:
      OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 16.20.1 - /usr/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 8.19.4 - /usr/bin/npm
```

**Comment by lanzifeng118** [comment]
目前解决方案
因为3.6.21解决了swiper在H5的最后一张以及指示器的问题，所以先其他包升级到3.6.21
@tarojs/cli还是保留在3.6.20，构建是通过的，暂时还没发现有其他问题
