### ISSUE TITLE
新项目开发启动报错

### ISSUE THREAD

**Issue by tolerance-go** [NervJS/taro#15209]
### 相关平台
H5

**浏览器版本: chrome 121.0.6167.140**
**使用框架: React**

### 复现步骤
1. pnpm i 安装依赖
2. pnpm dev:h5

### 期望结果
正常启动

### 实际结果
报错了

$ pnpm dev:h5

> myApp6@1.0.0 dev:h5 C:\Users\yarnb\test\myApp6
> npm run build:h5 -- --watch

> myApp6@1.0.0 build:h5
> taro build --type h5 --watch

👽 Taro v3.6.23

Error: The specified module could not be found.
\\?\C:\Users\yarnb\test\myApp6\node_modules\.pnpm\@tarojs+plugin-doctor-win32-x64-msvc@0.0.11\node_modules\@tarojs\plugin-doctor-win32-x64-msvc\taro-doctor.win32-x64-msvc.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\yarnb\test\myApp6\node_modules\.pnpm\@tarojs+plugin-doctor@0.0.11\node_modules\@tarojs\plugin-doctor\js-binding.js:72:29)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (C:\Users\yarnb\test\myApp6\node_modules\.pnpm\pirates@4.0.6\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32) {
  code: 'ERR_DLOPEN_FAILED'
}
Error: The specified module could not be found.
\\?\C:\Users\yarnb\test\myApp6\node_modules\.pnpm\@tarojs+plugin-doctor-win32-x64-msvc@0.0.11\node_modules\@tarojs\plugin-doctor-win32-x64-msvc\taro-doctor.win32-x64-msvc.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\yarnb\test\myApp6\node_modules\.pnpm\@tarojs+plugin-doctor@0.0.11\node_modules\@tarojs\plugin-doctor\js-binding.js:72:29)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (C:\Users\yarnb\test\myApp6\node_modules\.pnpm\pirates@4.0.6\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32) {
  code: 'ERR_DLOPEN_FAILED'
}
C:\Users\yarnb\test\myApp6\node_modules\.pnpm\@tarojs+service@3.6.23_@tarojs+shared@3.6.23_@tarojs+taro@3.6.23\node_modules\@tarojs\service\dist\utils\index.js:89
                        throw new Error(`插件依赖 "${item}" 加载失败，请检查插件配置`);
                              ^

Error: 插件依赖 "C:\Users\yarnb\test\myApp6\node_modules\.pnpm\@tarojs+cli@3.6.23_@tarojs+taro@3.6.23\node_modules\@tarojs\cli\dist\presets\commands\build.js" 加载失败，请检查插件配置
    at apply (C:\Users\yarnb\test\myApp6\node_modules\.pnpm\@tarojs+service@3.6.23_@tarojs+shared@3.6.23_@tarojs+taro@3.6.23\node_modules\@tarojs\service\src\utils\index.ts:84:19)
    at Kernel.initPlugin (C:\Users\yarnb\test\myApp6\node_modules\.pnpm\@tarojs+service@3.6.23_@tarojs+shared@3.6.23_@tarojs+taro@3.6.23\node_modules\@tarojs\service\src\Kernel.ts:181:5)
    at Kernel.resolvePlugins (C:\Users\yarnb\test\myApp6\node_modules\.pnpm\@tarojs+service@3.6.23_@tarojs+shared@3.6.23_@tarojs+taro@3.6.23\node_modules\@tarojs\service\src\Kernel.ts:150:12)
    at Kernel.initPresetsAndPlugins (C:\Users\yarnb\test\myApp6\node_modules\.pnpm\@tarojs+service@3.6.23_@tarojs+shared@3.6.23_@tarojs+taro@3.6.23\node_modules\@tarojs\service\src\Kernel.ts:123:10)
    at Kernel.<anonymous> (C:\Users\yarnb\test\myApp6\node_modules\.pnpm\@tarojs+service@3.6.23_@tarojs+shared@3.6.23_@tarojs+taro@3.6.23\node_modules\@tarojs\service\src\Kernel.ts:354:10)
    at Generator.next (<anonymous>)
    at C:\Users\yarnb\test\myApp6\node_modules\.pnpm\@tarojs+service@3.6.23_@tarojs+shared@3.6.23_@tarojs+taro@3.6.23\node_modules\@tarojs\service\dist\Kernel.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\yarnb\test\myApp6\node_modules\.pnpm\@tarojs+service@3.6.23_@tarojs+shared@3.6.23_@tarojs+taro@3.6.23\node_modules\@tarojs\service\dist\Kernel.js:4:12)
    at Kernel.run (C:\Users\yarnb\test\myApp6\node_modules\.pnpm\@tarojs+service@3.6.23_@tarojs+shared@3.6.23_@tarojs+taro@3.6.23\node_modules\@tarojs\service\dist\Kernel.js:285:16)

Node.js v20.11.0
 ELIFECYCLE  Command failed with exit code 1.

### 环境信息

我获取环境信息直接报错了。。。

$ pnpm taro info
👽 Taro v3.6.23

Error: The specified module could not be found.
\\?\C:\Users\yarnb\test\myApp6\node_modules\.pnpm\@tarojs+plugin-doctor-win32-x64-msvc@0.0.11\node_modules\@tarojs\plugin-doctor-win32-x64-msvc\taro-doctor.win32-x64-msvc.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\yarnb\test\myApp6\node_modules\.pnpm\@tarojs+plugin-doctor@0.0.11\node_modules\@tarojs\plugin-doctor\js-binding.js:72:29)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (C:\Users\yarnb\test\myApp6\node_modules\.pnpm\pirates@4.0.6\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32) {
  code: 'ERR_DLOPEN_FAILED'
}
找不到项目配置文件config/index，请确定当前目录是 Taro 项目根目录!

---
### 补充信息
我是用 npx 安装的，最新的 是"@tarojs/cli": "3.6.23", issue 帮助生成页面最高是3.3.16

**Comment by tolerance-go** [comment]
线上项目 https://github.com/tolerance-go/test-taro

**Comment by tolerance-go** [comment]
windows11 环境

**Comment by Jack-Z-Coding** [comment]
win10
node：v20.0.0

**Comment by angleneo** [comment]
和楼主同样的错误，请问解决了吗

**Comment by Boncen** [comment]
相同的情况，在安装vc++之后解决了。

**Comment by b-yp** [comment]
同样的错误，安装 VC++ 解决，请查看
![image](https://github.com/NervJS/taro/assets/32813227/8705dcdb-8d96-44c9-8575-7b954dc2b25c)

**Comment by Youngwellcool** [comment]
> 同样的错误，安装 VC++ 解决，请查看 ![image](https://private-user-images.githubusercontent.com/32813227/336273238-8705dcdb-8d96-44c9-8575-7b954dc2b25c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMTUzOTUsIm5iZiI6MTcyNTExNTA5NSwicGF0aCI6Ii8zMjgxMzIyNy8zMzYyNzMyMzgtODcwNWRjZGItOGQ5Ni00NGM5LTg1NzUtN2I5NTRkYzJiMjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDE0MzgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYmUyNGRkN2VhODFjMWQ2OWQyYWQ3MGJiOWY0NWU3M2YwNzBkOWQ4M2ZlMGI5NWFkYzNiM2ZmNzBiOTMyODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JSb-azK9jldC6PEwNAGgYQHlN59xm2J5pmtbulO_TT4)

确实安装vc++就可以了，但是文档中没有看到这个提示呀

**Comment by JoJohw** [comment]
雀食啊，我也是这个问题
![image](https://github.com/user-attachments/assets/f7f9c9bb-ccfe-40a2-bf7c-17f128c302ca)
找半天没找到大家说的vc++，然后在csdn找到了个链接
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
![image](https://github.com/user-attachments/assets/bf156082-0487-41aa-9885-edf19375358b)

**Comment by Youngwellcool** [comment]
您好，你的邮件我已经收到了。谢谢！

**Comment by thxcn** [comment]
![Image](https://github.com/user-attachments/assets/72eca7cd-f0ca-43b8-804f-a67ed6b1d5de)我也装了啊，创建新项目就是报这个错

![Image](https://github.com/user-attachments/assets/4a7dcec4-0fdf-4138-a5e9-e013426ffd97)

**Comment by Loongle** [comment]
@thxcn 你好，请问你的问题解决了吗？我也有相同的问题

**Comment by Youngwellcool** [comment]
您好，你的邮件我已经收到了。谢谢！
