### ISSUE TITLE
自定义metro.config.js的transformer的assetPlugins报错，plugin是null

### ISSUE THREAD

**Issue by atlasoy** [NervJS/taro#15371]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
```
//metro.config.js
const { mergeConfig } = require('metro-config')
const { getMetroConfig } = require('@tarojs/rn-supporter')
const cdnPlugin = require('./img-cdn.js')

module.exports = (async function () {
  return mergeConfig({
  // custom your metro config here
    // https://facebook.github.io/metro/docs/configuration
    resolver: {},
    transformer: {
      assetPlugins: [cdnPlugin],
    }
  }, await getMetroConfig())
})()
```
```
//img-cdn.js
module.exports = async function (assetData) {
  return assetData
}
```
运行
```
npx react-native bundle --platform ios --dev false --entry-file ./index.js --bundle-output ./ios/index.ios.bundle --assets-dest ./ios/  --config ./metro.config.js  --minify true --reset-cache --verbose
```

### 期望结果
使用自定义的配置，asset文件经过assetplugins，正常打出bundle

### 实际结果
报错
```
error src/assets/test.png: The "id" argument must be of type string. Received null
TypeError: The "id" argument must be of type string. Received null
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at Module.require (node:internal/modules/cjs/loader:998:3)
    at require (node:internal/modules/cjs/helpers:102:18)
    at applyAssetDataPlugins (/Users/new/code/taro-app-rn/node_modules/metro/src/Assets.js:191:31)
    at getAssetData (/Users/new/code/taro-app-rn/node_modules/metro/src/Assets.js:179:16)
    at Object.transform (/Users/new/code/taro-app-rn/node_modules/metro-transform-worker/src/utils/assetTransformer.js:30:16)
    at transformAsset (/Users/new/code/taro-app-rn/node_modules/metro-transform-worker/src/index.js:374:18)
    at Object.transform (/Users/new/code/taro-app-rn/node_modules/metro-transform-worker/src/index.js:562:14)
```

### 环境信息
```
  Taro CLI 3.6.23 environment info:
    System:
      OS: macOS 14.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.0/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.23 => 3.6.23 
      @tarojs/components: 3.6.23 => 3.6.23 
      @tarojs/helper: 3.6.23 => 3.6.23 
      @tarojs/plugin-framework-react: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-alipay: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-h5: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-jd: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-qq: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-swan: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-tt: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-weapp: 3.6.23 => 3.6.23 
      @tarojs/react: 3.6.23 => 3.6.23 
      @tarojs/rn-runner: 3.6.23 => 3.6.23 
      @tarojs/rn-supporter: 3.6.23 => 3.6.23 
      @tarojs/runtime: 3.6.23 => 3.6.23 
      @tarojs/runtime-rn: 3.6.23 => 3.6.23 
      @tarojs/shared: 3.6.23 => 3.6.23 
      @tarojs/taro: 3.6.23 => 3.6.23 
      @tarojs/taro-loader: 3.6.23 => 3.6.23 
      @tarojs/taro-rn: 3.6.23 => 3.6.23 
      @tarojs/webpack5-runner: 3.6.23 => 3.6.23 
      babel-preset-taro: 3.6.23 => 3.6.23 
      eslint-config-taro: 3.6.23 => 3.6.23 
      expo: ~47.0.3 => 47.0.14 
      react: ^18.1.0 => 18.2.0 
      react-native: ^0.70.1 => 0.70.15 
```

---
### 补充信息
与图片信息无关，打出的错误信息内metro-transform-worker到metro/src/index.js中的applyAssetDataPlugins，其中assetDataPlugins为[null]，也就是说，metro.config.js中的assetplugins配置最后变成了null

**Comment by atlasoy** [comment]
和taro无关。
metro.config.js中transformer.assetPlugins:[cdnPlugin]
此处必须为string，其他type最后都会转为null
