### ISSUE TITLE
node_modules 里面的文件被编译出现的路径错误

### ISSUE THREAD

**Issue by JasonFF** [NervJS/taro#1552]
**问题描述**
安装 cheerio 然后编译会出现很多问题，导致不能使用

![image](https://user-images.githubusercontent.com/16755888/50076103-b4129500-021b-11e9-8e9a-d2e531362bdc.png)
![image](https://user-images.githubusercontent.com/16755888/50076145-d0163680-021b-11e9-9d7e-5644ce5e0d53.png)

导致了错误，无法编译。

**复现步骤**

安装cheerio，然后dev:weapp

**报错信息**

(node:17452) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'F:\github\JFTools\stream'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at recursiveRequire (C:\Users\JasonFF\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\src\util\resolve_npm_files.js:158:24)
    at resolveNpmFilesPath (C:\Users\JasonFF\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\src\util\resolve_npm_files.js:80:5)
    at CallExpression (C:\Users\JasonFF\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\src\util\resolve_npm_files.js:122:33)
    at NodePath._call (C:\Users\JasonFF\AppData\Local\Yarn\Data\global\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Users\JasonFF\AppData\Local\Yarn\Data\global\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\Users\JasonFF\AppData\Local\Yarn\Data\global\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (C:\Users\JasonFF\AppData\Local\Yarn\Data\global\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (C:\Users\JasonFF\AppData\Local\Yarn\Data\global\node_modules\babel-traverse\lib\context.js:108:19)
(node:17452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**Comment by luckyadam** [comment]
cheerio 在小程序里用不了

**Comment by yuche** [comment]
cheerio 是一个专供给 node 使用的包，他用了例如 `process ` 和 `stream` 这样的 api
