### ISSUE TITLE
微信小程序转换问题

### ISSUE THREAD

**Issue by brooke1220** [NervJS/taro#1562]
**问题描述**
问题描述：微信小程序转换时报错

**复现步骤**
[复现问题的步骤]
1. taro convert

```js
错误  页面转换  pages/home/index.js
{ SyntaxError: Unexpected token (1:4)
    at Parser.pp$5.raise (D:\Software\nodejs\node_global\node_modules\@tarojs\cli\node_modules\_babylon@6.18.0@babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (D:\Software\nodejs\node_global\node_modules\@tarojs\cli\node_modules\_babylon@6.18.0@babylon\lib\index.js:1761:8)
    at Parser.pp$3.getExpression (D:\Software\nodejs\node_global\node_modules\@tarojs\cli\node_modules\_babylon@6.18.0@babylon\lib\index.js:3283:10)
    at Object.parseExpression (D:\Software\nodejs\node_global\node_modules\@tarojs\cli\node_modules\_babylon@6.18.0@babylon\lib\index.js:7313:17)
    at parseAttribute (D:\Software\nodejs\node_global\node_modules\@tarojs\cli\node_modules\_@tarojs_taroize@1.2.0@@tarojs\taroize\lib\src\wxml.js:521:97)
    at Array.map (<anonymous>)
    at parseElement (D:\Software\nodejs\node_global\node_modules\@tarojs\cli\node_modules\_@tarojs_taroize@1.2.0@@tarojs\taroize\lib\src\wxml.js:444:65)
    at parseNode (D:\Software\nodejs\node_global\node_modules\@tarojs\cli\node_modules\_@tarojs_taroize@1.2.0@@tarojs\taroize\lib\src\wxml.js:411:12)
    at Array.map (<anonymous>)
    at parseElement (D:\Software\nodejs\node_global\node_modules\@tarojs\cli\node_modules\_@tarojs_taroize@1.2.0@@tarojs\taroize\lib\src\wxml.js:444:160) pos: 4, loc: Position { line: 1, column: 4 } }
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
要有源码，只有报错是没有任何意义的

**Comment by mienv567** [comment]
只要微信官方的demoui组建转换没多大问题，解密的小程序都可以转换

**Comment by brooke1220** [comment]
没有不相信tarojs  只是报错了 不知道位置  不知道怎么取解决

**Comment by brooke1220** [comment]
去

**Comment by brooke1220** [comment]
页面非常长  不好粘贴

**Comment by yuche** [comment]
那就贴文件，你不相信也没办法，这就是事实

**Comment by mienv567** [comment]
你就不会发zip包？
