### ISSUE TITLE
taro convert失败

### ISSUE THREAD

**Issue by cikichen** [NervJS/taro#1565]
代码片段
```
var app = getApp();

var Grid = require('./grid.js');
var Tile = require('./tile.js');
var GameManager = require('./game_manager.js');

var config = {
    data: {
        hidden: false,

        // 游戏数据可以通过参数控制
        grids: [],
        over: false,
        win: false,
        score: 0,
        highscore: 0,
        overMsg: '游戏结束'
    },
    onLoad: function() {
        this.GameManager = new GameManager(4);

        this.setData({
            grids: this.GameManager.setup(),
            highscore: wx.getStorageSync('highscore') || 0
        });

    },
    onReady: function() {
        var that = this;

        // 页面渲染完毕隐藏loading
        that.setData({
            hidden: true
        });
    },
    onShow: function() {
        // 页面展示
    },
    onHide: function() {
        // 页面隐藏
    },
    onUnload: function() {
        // 页面关闭
    },

    // 更新视图数据
    updateView: function(data) {
        // 游戏结束
        if(data.over){
            data.overMsg = '游戏结束';
        }

        // 获胜
        if(data.win){
            data.overMsg = '恭喜';
        }

        this.setData(data);
    },

    // 重新开始
    restart: function() {
        this.updateView({
            grids: this.GameManager.restart(),
            over: false,
            won: false,
            score: 0
        });
    },

    touchStartClienX: 0,
    touchStartClientY: 0,
    touchEndClientX: 0,
    touchEndClientY: 0,
    isMultiple: false, // 多手指操作

    touchStart: function(events) {

        // 多指操作
        this.isMultiple = events.touches.length > 1;
        if (this.isMultiple) {
            return;
        }

        var touch = events.touches[0];

        this.touchStartClientX = touch.clientX;
        this.touchStartClientY = touch.clientY;

    },

    touchMove: function(events) {
        var touch = events.touches[0];
        this.touchEndClientX = touch.clientX;
        this.touchEndClientY = touch.clientY;
    },

    touchEnd: function(events) {
        if (this.isMultiple) {
            return;
        }

        var dx = this.touchEndClientX - this.touchStartClientX;
        var absDx = Math.abs(dx);
        var dy = this.touchEndClientY - this.touchStartClientY;
        var absDy = Math.abs(dy);

        if (Math.max(absDx, absDy) > 10) {
            var direction = absDx > absDy ? (dx > 0 ? 1 : 3) : (dy > 0 ? 2 : 0);

            var data = this.GameManager.move(direction) || {
                grids: this.data.grids,
                over: this.data.over,
                won: this.data.won,
                score: this.data.score
            };

            var highscore = wx.getStorageSync('highscore') || 0;
            if(data.score > highscore){
                wx.setStorageSync('highscore', data.score);
            }

            this.updateView({
                grids: data.grids,
                over: data.over,
                won: data.won,
                score: data.score,
                highscore: Math.max(highscore, data.score)
            });

        }

    }
};

Page(config);
```
报错信息： 
```
错误  页面转换  pages/2048/2048.js
Error: Page 的第一个参数必须是一个对象才能转换。
  -----

    at Object.codeFrameError (/Users/simon/.nvm/versions/node/v10.13.0/lib/node_modules/@tarojs/cli/node_modules/@tarojs/taroize/lib/src/utils.js:62:12)
    at parsePage (/Users/simon/.nvm/versions/node/v10.13.0/lib/node_modules/@tarojs/cli/node_modules/@tarojs/taroize/lib/src/script.js:151:23)
    at CallExpression (/Users/simon/.nvm/versions/node/v10.13.0/lib/node_modules/@tarojs/cli/node_modules/@tarojs/taroize/lib/src/script.js:61:29)
    at NodePath._call (/Users/simon/.nvm/versions/node/v10.13.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/simon/.nvm/versions/node/v10.13.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/simon/.nvm/versions/node/v10.13.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/simon/.nvm/versions/node/v10.13.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/simon/.nvm/versions/node/v10.13.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/simon/.nvm/versions/node/v10.13.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/simon/.nvm/versions/node/v10.13.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/index.js:114:17)
```

**Comment by Eamonnzhang** [comment]
@yuche  page构造函数里如果用这种变量的方式传递参数就会转换失败吗？

**Comment by ofavor** [comment]
@yuche 最后一行的Page(config)里难道不是么？

**Comment by yuche** [comment]
是的，现在这个版本要求一定显示地传值，而且还必须是用 Page、App、Component 创建的函数。

@ofavor 是让你不要传值，直接把那个对象挪进去

**Comment by cikichen** [comment]
```
Error: 组件 /vant-weapp/row/index 没有 JS 文件！
    at components.forEach.componentObj (/Users/simon/.nvm/versions/node/v10.13.0/lib/node_modules/@tarojs/cli/src/convertor.js:566:17)
    at Set.forEach (<anonymous>)
    at Convertor.traverseComponents (/Users/simon/.nvm/versions/node/v10.13.0/lib/node_modules/@tarojs/cli/src/convertor.js:551:16)
    at pages.forEach.page (/Users/simon/.nvm/versions/node/v10.13.0/lib/node_modules/@tarojs/cli/src/convertor.js:539:14)
    at Set.forEach (<anonymous>)
    at Convertor.traversePages (/Users/simon/.nvm/versions/node/v10.13.0/lib/node_modules/@tarojs/cli/src/convertor.js:475:16)
    at Convertor.run (/Users/simon/.nvm/versions/node/v10.13.0/lib/node_modules/@tarojs/cli/src/convertor.js:714:10)
    at Object.<anonymous> (/Users/simon/.nvm/versions/node/v10.13.0/lib/node_modules/@tarojs/cli/bin/taro-convert:12:11)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
```

**Comment by yuche** [comment]
有赞的 UI 库转不了，因为他有 relations，而且不是用 Page、App、Component 创建的组件。
先看文档：
https://nervjs.github.io/taro/docs/taroize.html

**Comment by yantingxi** [comment]
现在这个版本要求一定显示地传递对象，而且还必须是用 Page、App、Component 创建的函数。 这个后续版本会优化么？会的话，大概什么版本能出来？

**Comment by yantingxi** [comment]
@yuche

**Comment by ASeR1-ATG** [comment]
YA IM JUST A LIL CONFUSED I NEVER FINISHED THIS CLASS

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by yuche** [comment]
@yantingxi 这个还没想好怎么做，目前的版本是基于 ast 转换 + 运行时装饰器配合起来运行才能转换，实现传递一个对象的不经过 ast 的话需要重构一下 ast 转换部分 + 运行时装饰器部分 + 小程序运行时框架才能做到。

还得想一下有没有更好的办法。
