### ISSUE TITLE
在服务器Linux无法编译Error: Bindings not found，降级swc也不行，window和mac都可以正常编译

### ISSUE THREAD

**Issue by linddxxx** [NervJS/taro#15701]
### 相关平台
H5

**浏览器版本: 最新版本**
**使用框架: Vue 3**

### 复现步骤
项目直接初始化后在服务器Linux直接进行部署失败,taro info 都无法执行

### 期望结果
正常编译通过

### 实际结果
在服务器CI部署taro info命令都无法执行，降级@swc/core也无效

### 环境信息
```
Taro CLI 3.6.20 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.2.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: ^3.6.20 => 3.6.20 
      @tarojs/components: ^3.6.20 => 3.6.20 
      @tarojs/helper: ^3.6.20 => 3.6.20 
      @tarojs/plugin-framework-vue3: ^3.6.20 => 3.6.20 
      @tarojs/plugin-html: ^3.6.20 => 3.6.20 
      @tarojs/plugin-platform-alipay: ^3.6.20 => 3.6.20 
      @tarojs/plugin-platform-h5: ^3.6.20 => 3.6.20 
      @tarojs/plugin-platform-jd: ^3.6.20 => 3.6.20 
      @tarojs/plugin-platform-qq: ^3.6.20 => 3.6.20 
      @tarojs/plugin-platform-swan: ^3.6.20 => 3.6.20 
      @tarojs/plugin-platform-tt: ^3.6.20 => 3.6.20 
      @tarojs/plugin-platform-weapp: ^3.6.20 => 3.6.20 
      @tarojs/runtime: ^3.6.20 => 3.6.20 
      @tarojs/shared: ^3.6.20 => 3.6.20 
      @tarojs/taro: ^3.6.20 => 3.6.20 
      @tarojs/taro-loader: ^3.6.20 => 3.6.20 
      @tarojs/webpack5-runner: ^3.6.20 => 3.6.20 
      babel-preset-taro: ^3.6.20 => 3.6.20 
      eslint-config-taro: ^3.6.20 => 3.6.20 
    npmGlobalPackages:
      typescript: 5.3.3
```

---
### 补充信息
    Error: Bindings not found
        at Compiler.transformSync (/code/node_modules/@swc/core/index.js:250:15)
        at Object.transformSync (/code/node_modules/@swc/core/index.js:348:21)
        at compile (/code/node_modules/@swc/register/lib/node.js:76:22)
        at compileHook (/code/node_modules/@swc/register/lib/node.js:91:16)
        at Module._compile (/code/node_modules/pirates/lib/index.js:113:29)
        at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
        at Object.newLoader [as .js] (/code/node_modules/pirates/lib/index.js:121:7)
        at Module.load (node:internal/modules/cjs/loader:1119:32)
        at Module._load (node:internal/modules/cjs/loader:960:12)
        at Module.require (node:internal/modules/cjs/loader:1143:19)
    /code/node_modules/@tarojs/service/dist/utils/index.js:89
                            throw new Error(`插件依赖 "${item}" 加载失败，请检查插件配置`);
                                  ^
  
    Error: 插件依赖 "/code/node_modules/@tarojs/cli/dist/presets/index.js" 加载失败，请检查插件配置
        at apply (/code/node_modules/@tarojs/service/dist/utils/index.js:89:31)
        at Kernel.initPreset (/code/node_modules/@tarojs/service/dist/Kernel.js:112:38)
        at Kernel.resolvePresets (/code/node_modules/@tarojs/service/dist/Kernel.js:87:18)
        at Kernel.initPresetsAndPlugins (/code/node_modules/@tarojs/service/dist/Kernel.js:81:14)
        at Kernel.<anonymous> (/code/node_modules/@tarojs/service/dist/Kernel.js:301:18)
        at Generator.next (<anonymous>)
        at /code/node_modules/@tarojs/service/dist/Kernel.js:8:71
        at new Promise (<anonymous>)
        at __awaiter (/code/node_modules/@tarojs/service/dist/Kernel.js:4:12)
        at Kernel.run (/code/node_modules/@tarojs/service/dist/Kernel.js:285:16)
  
    Node.js v18.16.1

**Comment by 402931261** [comment]
解决了吗？再jenkins上也是无法正常打包
`👽 Taro v3.6.25

Error: unknown field `cwd`
    at module.exports.__wbindgen_error_new (/hycan/jenkins-workspace/ECP_TEST_FrontendProject/ecp-hycanpower/node_modules/@swc/wasm/wasm.js:512:17)
    at wasm://wasm/04a31cfa:wasm-function[10173]:0xd3bef4
    at wasm://wasm/04a31cfa:wasm-function[288]:0x3af4dd
    at wasm://wasm/04a31cfa:wasm-function[251]:0x35b51c
    at wasm://wasm/04a31cfa:wasm-function[13223]:0xdacc6b
    at Object.module.exports.transformSync (/hycan/jenkins-workspace/ECP_TEST_FrontendProject/ecp-hycanpower/node_modules/@swc/wasm/wasm.js:333:14)
    at Compiler.transformSync (/hycan/jenkins-workspace/ECP_TEST_FrontendProject/ecp-hycanpower/node_modules/@swc/core/index.js:251:37)
    at Object.transformSync (/hycan/jenkins-workspace/ECP_TEST_FrontendProject/ecp-hycanpower/node_modules/@swc/core/index.js:351:21)
    at compile (/hycan/jenkins-workspace/ECP_TEST_FrontendProject/ecp-hycanpower/node_modules/@swc/register/lib/node.js:76:22)
    at compileHook (/hycan/jenkins-workspace/ECP_TEST_FrontendProject/ecp-hycanpower/node_modules/@swc/register/lib/node.js:91:16)
Error: unknown field `cwd`
    at module.exports.__wbindgen_error_new (/hycan/jenkins-workspace/ECP_TEST_FrontendProject/ecp-hycanpower/node_modules/@swc/wasm/wasm.js:512:17)
    at wasm://wasm/04a31cfa:wasm-function[10173]:0xd3bef4
    at wasm://wasm/04a31cfa:wasm-function[288]:0x3af4dd
    at wasm://wasm/04a31cfa:wasm-function[251]:0x35b51c
    at wasm://wasm/04a31cfa:wasm-function[13223]:0xdacc6b
    at Object.module.exports.transformSync (/hycan/jenkins-workspace/ECP_TEST_FrontendProject/ecp-hycanpower/node_modules/@swc/wasm/wasm.js:333:14)
    at Compiler.transformSync (/hycan/jenkins-workspace/ECP_TEST_FrontendProject/ecp-hycanpower/node_modules/@swc/core/index.js:251:37)
    at Object.transformSync (/hycan/jenkins-workspace/ECP_TEST_FrontendProject/ecp-hycanpower/node_modules/@swc/core/index.js:351:21)
    at compile (/hycan/jenkins-workspace/ECP_TEST_FrontendProject/ecp-hycanpower/node_modules/@swc/register/lib/node.js:76:22)
    at compileHook (/hycan/jenkins-workspace/ECP_TEST_FrontendProject/ecp-hycanpower/node_modules/@swc/register/lib/node.js:91:16)
/hycan/jenkins-workspace/ECP_TEST_FrontendProject/ecp-hycanpower/node_modules/@tarojs/service/dist/utils/index.js:89
                        throw new Error(`插件依赖 "${item}" 加载失败，请检查插件配置`);`

**Comment by JustYouth** [comment]
> ### 相关平台
> H5
> 
> **浏览器版本: 最新版本** **使用框架: Vue 3**
> 
> ### 复现步骤
> 项目直接初始化后在服务器Linux直接进行部署失败,taro info 都无法执行
> 
> ### 期望结果
> 正常编译通过
> 
> ### 实际结果
> 在服务器CI部署taro info命令都无法执行，降级@swc/core也无效
> 
> ### 环境信息
> ```
> Taro CLI 3.6.20 environment info:
>     System:
>       OS: macOS 14.2.1
>       Shell: 5.9 - /bin/zsh
>     Binaries:
>       Node: 20.10.0 - /usr/local/bin/node
>       Yarn: 1.22.22 - /usr/local/bin/yarn
>       npm: 10.2.3 - /usr/local/bin/npm
>     npmPackages:
>       @tarojs/cli: ^3.6.20 => 3.6.20 
>       @tarojs/components: ^3.6.20 => 3.6.20 
>       @tarojs/helper: ^3.6.20 => 3.6.20 
>       @tarojs/plugin-framework-vue3: ^3.6.20 => 3.6.20 
>       @tarojs/plugin-html: ^3.6.20 => 3.6.20 
>       @tarojs/plugin-platform-alipay: ^3.6.20 => 3.6.20 
>       @tarojs/plugin-platform-h5: ^3.6.20 => 3.6.20 
>       @tarojs/plugin-platform-jd: ^3.6.20 => 3.6.20 
>       @tarojs/plugin-platform-qq: ^3.6.20 => 3.6.20 
>       @tarojs/plugin-platform-swan: ^3.6.20 => 3.6.20 
>       @tarojs/plugin-platform-tt: ^3.6.20 => 3.6.20 
>       @tarojs/plugin-platform-weapp: ^3.6.20 => 3.6.20 
>       @tarojs/runtime: ^3.6.20 => 3.6.20 
>       @tarojs/shared: ^3.6.20 => 3.6.20 
>       @tarojs/taro: ^3.6.20 => 3.6.20 
>       @tarojs/taro-loader: ^3.6.20 => 3.6.20 
>       @tarojs/webpack5-runner: ^3.6.20 => 3.6.20 
>       babel-preset-taro: ^3.6.20 => 3.6.20 
>       eslint-config-taro: ^3.6.20 => 3.6.20 
>     npmGlobalPackages:
>       typescript: 5.3.3
> ```
> 
> ### 补充信息
> ```
> Error: Bindings not found
>     at Compiler.transformSync (/code/node_modules/@swc/core/index.js:250:15)
>     at Object.transformSync (/code/node_modules/@swc/core/index.js:348:21)
>     at compile (/code/node_modules/@swc/register/lib/node.js:76:22)
>     at compileHook (/code/node_modules/@swc/register/lib/node.js:91:16)
>     at Module._compile (/code/node_modules/pirates/lib/index.js:113:29)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
>     at Object.newLoader [as .js] (/code/node_modules/pirates/lib/index.js:121:7)
>     at Module.load (node:internal/modules/cjs/loader:1119:32)
>     at Module._load (node:internal/modules/cjs/loader:960:12)
>     at Module.require (node:internal/modules/cjs/loader:1143:19)
> /code/node_modules/@tarojs/service/dist/utils/index.js:89
>                         throw new Error(`插件依赖 "${item}" 加载失败，请检查插件配置`);
>                               ^
> 
> Error: 插件依赖 "/code/node_modules/@tarojs/cli/dist/presets/index.js" 加载失败，请检查插件配置
>     at apply (/code/node_modules/@tarojs/service/dist/utils/index.js:89:31)
>     at Kernel.initPreset (/code/node_modules/@tarojs/service/dist/Kernel.js:112:38)
>     at Kernel.resolvePresets (/code/node_modules/@tarojs/service/dist/Kernel.js:87:18)
>     at Kernel.initPresetsAndPlugins (/code/node_modules/@tarojs/service/dist/Kernel.js:81:14)
>     at Kernel.<anonymous> (/code/node_modules/@tarojs/service/dist/Kernel.js:301:18)
>     at Generator.next (<anonymous>)
>     at /code/node_modules/@tarojs/service/dist/Kernel.js:8:71
>     at new Promise (<anonymous>)
>     at __awaiter (/code/node_modules/@tarojs/service/dist/Kernel.js:4:12)
>     at Kernel.run (/code/node_modules/@tarojs/service/dist/Kernel.js:285:16)
> 
> Node.js v18.16.1
> ```

我重新使用npm i -g @tarojs/cli -ddd，重新安装了一遍cli解决了错误

**Comment by velley** [comment]
我也经常遇到，感觉跟taro版本关系很大。有的版本没有这个问题，有的版本则必定报这个错。比如3.6.30/4.0.6我实测可以正常打包，但更新到最新的4.1.2-4.1.5这个错又出现了。本来想用4.0.6，但因为用了mp-html导致这个版本会报另一个编译错误。真的尴尬，只有多试几个版本了。
