### ISSUE TITLE
微信小程序转Taro imports文件夹下命名混乱，且有缺失

### ISSUE THREAD

**Issue by hugetiny** [NervJS/taro#1579]
以weapp-app-mall为例
imports目录
CartGoodsListTmpl.js
NoGoodsTmpl.js
TaroEmojiViewTmpl.js
TaroParseaaTmpl.js
TaroParseaTmpl.js
TaroParseazTmpl.js
TaroParseBrTmpl.js
TaroParsebTmpl.js
TaroParsecTmpl.js
TaroParsedTmpl.js
TaroParseeTmpl.js
TaroParsefTmpl.js
TaroParsegTmpl.js
TaroParsehTmpl.js
TaroParseImgTmpl.js
TaroParseiTmpl.js
TaroParseTmpl.js
TaroParseVideoTmpl.js

H5运行时报错
./.temp/imports/TaroParseaaTmpl.js
Module not found: Can't resolve './TaroParseabTmpl' in '/Users/zhangzhechong/WebstormProjects/weapp-app-mall/taroConvert/.temp/imports'

微信运行时报错
错误  页面编译  页面/Users/zhangzhechong/WebstormProjects/taro-app-mall/taroConvert/src/pages/goods-details/index编译失败！
TypeError: Cannot read property 'wxss' of undefined
    at buildDepComponentsResult.map.item (/Users/zhangzhechong/.nvm/versions/node/v10.13.0/lib/node_modules/@tarojs/cli/src/weapp.js:1589:23)
    at Array.map (<anonymous>)
    at getDepStyleList (/Users/zhangzhechong/.nvm/versions/node/v10.13.0/lib/node_modules/@tarojs/cli/src/weapp.js:1588:44)
    at buildSinglePage (/Users/zhangzhechong/.nvm/versions/node/v10.13.0/lib/node_modules/@tarojs/cli/src/weapp.js:1348:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

 - 操作系统: [ Mac 10.13.6]
 - Taro 版本 [1.2.0]
 - Node.js 版本 [v10.13.0]
 - 报错平台 [h5, weapp]

[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
能不能先看文档：
https://nervjs.github.io/taro/docs/taroize.html#%E8%BD%AC%E6%8D%A2-wxparse-%E6%8A%A5%E9%94%99%E4%B8%8D%E5%AD%98%E5%9C%A8%E6%96%87%E4%BB%B6

这是由于 wxParse 的源码使用了一个不存在的 template 声明造成的。你可以修改 wxParse 的源码文件 wxParse.wxml 49 行到 129 行：
