### ISSUE TITLE
微信小程序端 run build 会报错 Error: chunk common [mini-css-extract-plugin]

### ISSUE THREAD

**Issue by 160905** [NervJS/taro#15806]
### 相关平台
微信小程序

### 复现仓库
[git@github.com:160905/TaroReactWeapp.git](git@github.com:160905/TaroReactWeapp.git)
**小程序基础库: 3.4.4**
**使用框架: React**

### 复现步骤
npm run build:weapp

### 期望结果
build 时没有错误

### 实际结果
Error: chunk common [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].oneOf[2].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[4].oneOf[2].use[2]!./node_modules/@nutui/nutui-react-taro/dist/esm/NoticeBar/style/style.css
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].oneOf[2].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[4].oneOf[2].use[2]!./node_modules/@nutui/nutui-react-taro/dist/esm/Col/style/style.css
   - couldn't fulfill desired order of chunk group(s) pages/home/index
   - while fulfilling desired order of chunk group(s) pages/goods/index, pages/message/index, pages/mine/index, pages/login/index
 * css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].oneOf[2].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[4].oneOf[2].use[2]!./node_modules/@nutui/nutui-react-taro/dist/esm/Row/style/style.css
   - couldn't fulfill desired order of chunk group(s) pages/home/index
   - while fulfilling desired order of chunk group(s) pages/goods/index, pages/message/index, pages/mine/index, pages/login/index
    at Array.forEach (<anonymous>)

### 环境信息
```
Taro CLI 3.6.30 environment info:
    System:
      OS: Windows 11 10.0.22000
    Binaries:
      Node: 20.13.1 - C:\Users\ADMINI~1\AppData\Local\Temp\yarn--1716901970577-0.7953419740036396\node.CMD
      Yarn: 1.22.22 - C:\Users\ADMINI~1\AppData\Local\Temp\yarn--1716901970577-0.7953419740036396\yarn.CMD
      npm: 10.5.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.30 => 3.6.30 
      @tarojs/components: 3.6.30 => 3.6.30 
      @tarojs/helper: 3.6.30 => 3.6.30 
      @tarojs/plugin-framework-react: 3.6.30 => 3.6.30 
      @tarojs/plugin-html: 3.6.30 => 3.6.30 
      @tarojs/plugin-platform-alipay: 3.6.30 => 3.6.30 
      @tarojs/plugin-platform-h5: 3.6.30 => 3.6.30 
      @tarojs/plugin-platform-jd: 3.6.30 => 3.6.30 
      @tarojs/plugin-platform-qq: 3.6.30 => 3.6.30 
      @tarojs/plugin-platform-swan: 3.6.30 => 3.6.30 
      @tarojs/plugin-platform-tt: 3.6.30 => 3.6.30 
      @tarojs/plugin-platform-weapp: 3.6.30 => 3.6.30 
      @tarojs/react: 3.6.30 => 3.6.30 
      @tarojs/runtime: 3.6.30 => 3.6.30 
      @tarojs/shared: 3.6.30 => 3.6.30 
      @tarojs/taro: 3.6.30 => 3.6.30 
      @tarojs/taro-loader: 3.6.30 => 3.6.30 
      @tarojs/webpack5-runner: 3.6.30 => 3.6.30 
      babel-preset-taro: 3.6.30 => 3.6.30 
      eslint-config-taro: 3.6.30 => 3.6.30 
      react: ^18.0.0 => 18.3.1 
```

**Comment by partnerSun** [comment]
这个解决方案是什么呢

**Comment by bibibala** [comment]
我也是。我在init创建的 Vue3的模板，一直编译报错和这个报错一样
`Error: Module build failed (from ./node_modules/.pnpm/mini-css-extract-plugin@2.4.6_webpack@5.92.1_@swc+core@1.3.96_/node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/.pnpm/postcss-loader@7.3.4_postcss@6.0.23_typescript@4.9.5_webpack@5.92.1_@swc+core@1.3.96_/node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (D:\project\app\node_modules\.pnpm\postcss@6.0.23\node_modules\postcss\lib\processor.es6:114:23)
    at new Processor (D:\project\app\node_modules\.pnpm\postcss@6.0.23\node_modules\postcss\lib\processor.es6:35:29)
    at postcss (D:\project\app\node_modules\.pnpm\postcss@6.0.23\node_modules\postcss\lib\postcss.es6:34:12)
    at Object.loader (D:\project\app\node_modules\.pnpm\postcss-loader@7.3.4_postcss@6.0.23_typescript@4.9.5_webpack@5.92.1_@swc+core@1.3.96_\node_modules\postcss-loader\dist\index.js:83:17)
    at tryRunOrWebpackError (D:\project\app\node_modules\.pnpm\webpack@5.92.1_@swc+core@1.3.96\node_modules\webpack\lib\HookWebpackError.js:88:9)
    at __webpack_require_module__ (D:\project\app\node_modules\.pnpm\webpack@5.92.1_@swc+core@1.3.96\node_modules\webpack\lib\Compilation.js:5246:12)
    at __webpack_require__ (D:\project\app\node_modules\.pnpm\webpack@5.92.1_@swc+core@1.3.96\node_modules\webpack\lib\Compilation.js:5203:18)
    at D:\project\app\node_modules\.pnpm\webpack@5.92.1_@swc+core@1.3.96\node_modules\webpack\lib\Compilation.js:5275:20
    at symbolIterator (D:\project\app\node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:3485:9)
    at done (D:\project\app\node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (D:\project\app\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\project\app\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\Hook.js:18:14)
    at D:\project\app\node_modules\.pnpm\webpack@5.92.1_@swc+core@1.3.96\node_modules\webpack\lib\Compilation.js:5181:43
    at symbolIterator (D:\project\app\node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:3482:9)
    at timesSync (D:\project\app\node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:2297:7)
    at Object.eachLimit (D:\project\app\node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:3463:5)
    at D:\project\app\node_modules\.pnpm\webpack@5.92.1_@swc+core@1.3.96\node_modules\webpack\lib\Compilation.js:5143:16
    at symbolIterator (D:\project\app\node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:3485:9)
    at timesSync (D:\project\app\node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:2297:7)
    at Object.eachLimit (D:\project\app\node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:3463:5)
    at D:\project\app\node_modules\.pnpm\webpack@5.92.1_@swc+core@1.3.96\node_modules\webpack\lib\Compilation.js:5111:15
    at symbolIterator (D:\project\app\node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:3485:9)
    at done (D:\project\app\node_modules\.pnpm\neo-async@2.6.2\node_modules\neo-async\async.js:3527:9)
    at D:\project\app\node_modules\.pnpm\webpack@5.92.1_@swc+core@1.3.96\node_modules\webpack\lib\Compilation.js:5057:8
    at D:\project\app\node_modules\.pnpm\webpack@5.92.1_@swc+core@1.3.96\node_modules\webpack\lib\Compilation.js:3495:6
    at D:\project\app\node_modules\.pnpm\webpack@5.92.1_@swc+core@1.3.96\node_modules\webpack\lib\HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (D:\project\app\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Cache.store (D:\project\app\node_modules\.pnpm\webpack@5.92.1_@swc+core@1.3.96\node_modules\webpack\lib\Cache.js:113:20)
    at ItemCacheFacade.store (D:\project\app\node_modules\.pnpm\webpack@5.92.1_@swc+core@1.3.96\node_modules\webpack\lib\CacheFacade.js:141:15)
    at D:\project\app\node_modules\.pnpm\webpack@5.92.1_@swc+core@1.3.96\node_modules\webpack\lib\Compilation.js:3494:11
    at D:\project\app\node_modules\.pnpm\webpack@5.92.1_@swc+core@1.3.96\node_modules\webpack\lib\Cache.js:97:34
    at Array.<anonymous> (D:\project\app\node_modules\.pnpm\webpack@5.92.1_@swc+core@1.3.96\node_modules\webpack\lib\cache\MemoryCachePlugin.js:45:13)
    at D:\project\app\node_modules\.pnpm\webpack@5.92.1_@swc+core@1.3.96\node_modules\webpack\lib\Cache.js:97:19
    at Hook.eval [as callAsync] (eval at create (D:\project\app\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:19:1)
    at Cache.get (D:\project\app\node_modules\.pnpm\webpack@5.92.1_@swc+core@1.3.96\node_modules\webpack\lib\Cache.js:81:18)
    at ItemCacheFacade.get (D:\project\app\node_modules\.pnpm\webpack@5.92.1_@swc+core@1.3.96\node_modules\webpack\lib\CacheF(env: Windows,mp,1.06.2404301; lib: 3.4.8)`
