### ISSUE TITLE
TS依赖文件编译失败

### ISSUE THREAD

**Issue by netdreamwing** [NervJS/taro#160]
在非page、component的其他TS依赖文件中不能使用变量类型，不然就会编译失败，报错如下：
```
{ SyntaxError: Unexpected token, expected , (8:28)
    at Parser.pp$5.raise (/Users/frank/development/mp/myApp/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/frank/development/mp/myApp/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp.expect (/Users/frank/development/mp/myApp/node_modules/babylon/lib/index.js:1749:33)
    at Parser.pp$3.parseParenAndDistinguishExpression (/Users/frank/development/mp/myApp/node_modules/babylon/lib/index.js:3814:12)
    at Parser.pp$3.parseExprAtom (/Users/frank/development/mp/myApp/node_modules/babylon/lib/index.js:3709:19)
    at Parser.parseExprAtom (/Users/frank/development/mp/myApp/node_modules/babylon/lib/index.js:7238:22)
    at Parser.pp$3.parseExprSubscripts (/Users/frank/development/mp/myApp/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/frank/development/mp/myApp/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/frank/development/mp/myApp/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/frank/development/mp/myApp/node_modules/babylon/lib/index.js:3381:19) pos: 171, loc: Position { line: 8, column: 28 } }
```

如下代码中step:number引起编译失败，去掉number类型约束就能编译通过
```
export let addAction = (step: number = 1) => createAction<Promise<any>>(
  CounterActionTypes.ADD,
  () => {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(step);
      }, 2000)
    })
  }
);
```

**Comment by yuche** [comment]
fix by https://github.com/NervJS/taro/commit/6e2fcfc8fb25d6dec2f68344f3a3757d50fe505e
