### ISSUE TITLE
微信原生小程序转taro报错

### ISSUE THREAD

**Issue by Doomtinger** [NervJS/taro#16371]
### 相关平台
微信小程序

**小程序基础库: 2.33.0**
**使用框架: React**

### 复现步骤
npx @tarojs/cli-convertor

### 期望结果
生成taroConvert

### 实际结果
报错Failed to load plugin 'taro' declared in 'BaseConfig': Cannot find module 'eslint-plugin-taro'
Require stack:
- D:\company\whjz_wechat_c\whjz_wechat_c\__placeholder__.js
Referenced from: BaseConfig
internal/fs/utils.js:332
    throw err;
    ^
Error: EPERM: operation not permitted, unlink 'C:\Users\admin\AppData\Roaming\npm-cache\_npx\21036\node_modules\@tarojs\cli-convertor\node_modules\@swc\core-win32-x64-msvc\swc.win32-x64-msvc.node'       
    at Object.unlinkSync (fs.js:1255:3)
    at fixWinEPERMSync (D:\soft\nvm\nvm\v14.19.0\node_modules\npm\node_modules\rimraf\rimraf.js:219:13)
    at rimrafSync (D:\soft\nvm\nvm\v14.19.0\node_modules\npm\node_modules\rimraf\rimraf.js:319:28)
    at D:\soft\nvm\nvm\v14.19.0\node_modules\npm\node_modules\rimraf\rimraf.js:350:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (D:\soft\nvm\nvm\v14.19.0\node_modules\npm\node_modules\rimraf\rimraf.js:349:26)
    at rmdirSync (D:\soft\nvm\nvm\v14.19.0\node_modules\npm\node_modules\rimraf\rimraf.js:342:7)
    at fixWinEPERMSync (D:\soft\nvm\nvm\v14.19.0\node_modules\npm\node_modules\rimraf\rimraf.js:217:5)
    at rimrafSync (D:\soft\nvm\nvm\v14.19.0\node_modules\npm\node_modules\rimraf\rimraf.js:319:28)
    at D:\soft\nvm\nvm\v14.19.0\node_modules\npm\node_modules\rimraf\rimraf.js:350:5 {
  errno: -4048,
  syscall: 'unlink',
  code: 'EPERM',
  path: 'C:\\Users\\admin\\AppData\\Roaming\\npm-cache\\_npx\\21036\\node_modules\\@tarojs\\cli-convertor\\node_modules\\@swc\\core-win32-x64-msvc\\swc.win32-x64-msvc.node'
}

### 环境信息
```
 Taro CLI 3.6.34 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.34 => 3.6.34
      @tarojs/components: 3.6.34 => 3.6.34
      @tarojs/helper: 3.6.34 => 3.6.34
      @tarojs/plugin-framework-vue3: 3.6.34 => 3.6.34
      @tarojs/plugin-html: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-alipay: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-h5: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-jd: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-qq: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-swan: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-tt: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-weapp: 3.6.34 => 3.6.34
      @tarojs/runtime: 3.6.34 => 3.6.34
      @tarojs/shared: 3.6.34 => 3.6.34
      @tarojs/taro: 3.6.34 => 3.6.34
      @tarojs/taro-loader: 3.6.34 => 3.6.34
      @tarojs/webpack5-runner: 3.6.34 => 3.6.34
      babel-preset-taro: 3.6.34 => 3.6.34
      eslint-config-taro: 3.6.34 => 3.6.34

```

**Comment by CaixyPromise** [comment]
这是缺少依赖了。原地在需要转换的文件夹的cmd输入npm install eslint-plugin-taro可解决。

**Comment by Doomtinger** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by shenxiang11** [comment]
> 这是来自QQ邮箱的假期自动回复邮件。
>  
> 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

修完假了吗

**Comment by hite** [comment]
如果微信小程序使用 TS 写的会报错，找不到 JS 文件。
开始代码转换...
转换  入口文件  app.js
转换  入口配置  app.json
转换  入口样式  app.wxss
错误  页面转换  pages/home/home.js
页面: pages/home/home转换失败 页面 pages/home/home 没有 JS 文件！
错误  页面转换  pages/index/index.js
页面: pages/index/index转换失败 页面 pages/index/index 没有 JS 文件！
错误  页面转换  pages/result/result.js
页面: pages/result/result转换失败 页面 pages/result/result 没有 JS 文件！

**Comment by Doomtinger** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Lmm240336783** [comment]
3.6.15版本 npx @tarojs/cli-convertor 执行缺少@tarojs/binding-win32-x64-msvc

Error: Cannot find module '@tarojs/binding-win32-x64-msvc'
Require stack:
- C:\Users\L2403\AppData\Local\npm-cache\_npx\1c50f9067efbafcb\node_modules\@tarojs\binding\binding.js
- C:\Users\L2403\AppData\Local\npm-cache\_npx\1c50f9067efbafcb\node_modules\@tarojs\cli-convertor\dist\index.js
- C:\Users\L2403\AppData\Local\npm-cache\_npx\1c50f9067efbafcb\node_modules\@tarojs\cli-convertor\bin\taro-convert
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\L2403\AppData\Local\npm-cache\_npx\1c50f9067efbafcb\node_modules\@tarojs\binding\binding.js:70:29)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\L2403\\AppData\\Local\\npm-cache\\_npx\\1c50f9067efbafcb\\node_modules\\@tarojs\\binding\\binding.js',
    'C:\\Users\\L2403\\AppData\\Local\\npm-cache\\_npx\\1c50f9067efbafcb\\node_modules\\@tarojs\\cli-convertor\\dist\\index.js',
    'C:\\Users\\L2403\\AppData\\Local\\npm-cache\\_npx\\1c50f9067efbafcb\\node_modules\\@tarojs\\cli-convertor\\bin\\taro-convert'
  ]
}

**Comment by Doomtinger** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hippone** [comment]
> 如果微信小程序使用 TS 写的会报错，找不到 JS 文件。 开始代码转换... 转换 入口文件 app.js 转换 入口配置 app.json 转换 入口样式 app.wxss 错误 页面转换 pages/home/home.js 页面: pages/home/home转换失败 页面 pages/home/home 没有 JS 文件！ 错误 页面转换 pages/index/index.js 页面: pages/index/index转换失败 页面 pages/index/index 没有 JS 文件！ 错误 页面转换 pages/result/result.js 页面: pages/result/result转换失败 页面 pages/result/result 没有 JS 文件！

我也遇到了，还没修吗，只识别js不识别ts文件
