### ISSUE TITLE
更改了代码之后每次都会出现这个错误，而且页面刷新之后无法访问

### ISSUE THREAD

**Issue by LoganHwl** [NervJS/taro#1645]
如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
创建  添加文件  src\components\head\head_top.styl___jb_tmp___
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'D:\Taro\taro_demo01\src\components\head\head_top.styl___jb_tm
p___'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at processFiles (C:\Program Files\nodejs\node_modules\@tarojs\cli\src\h5.js:804:19)
    at FSWatcher.watcher.on.filePath (C:\Program Files\nodejs\node_modules\@tarojs\cli\src\h5.js:843:7)
    at emitTwo (events.js:126:13)
    at FSWatcher.emit (events.js:214:7)
    at FSWatcher.<anonymous> (C:\Program Files\nodejs\node_modules\@tarojs\cli\node_modules\_chokidar@2.0.4@c
hokidar\index.js:199:15)
    at FSWatcher._emit (C:\Program Files\nodejs\node_modules\@tarojs\cli\node_modules\_chokidar@2.0.4@chokida
r\index.js:241:5)
    at FSWatcher.NodeFsHandler._handleFile (C:\Program Files\nodejs\node_modules\@tarojs\cli\node_modules\_ch
okidar@2.0.4@chokidar\lib\nodefs-handler.js:279:10)
    at FSWatcher.<anonymous> (C:\Program Files\nodejs\node_modules\@tarojs\cli\node_modules\_chokidar@2.0.4@c
hokidar\lib\nodefs-handler.js:480:21)
    at FSReqWrap.oncomplete (fs.js:153:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taro_demo01@1.0.0 build:h5: `taro build --type h5 "--watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the taro_demo01@1.0.0 build:h5 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-12-22T15_07_07_074Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taro_demo01@1.0.0 dev:h5: `npm run build:h5 -- --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the taro_demo01@1.0.0 dev:h5 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-12-22T15_07_07_090Z-debug.log


```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by mienv567** [comment]
首先你的taro 版本有问题， 请使用 taro update self升级，或者 卸载之前的 重新安装 npm install -g tarojs/cli@1.2.1 在自己的项目根目录重新npm install 如果还有错误再发问题

**Comment by LoganHwl** [comment]
您好，按照您的方法试了也没有效果，还是一样的问题。而且把node也重装了也一样
client?742c:177 [WDS] Disconnected!
client?742c:174 Invalid Host/Origin header
浏览器一直重复这个错误

**Comment by LoganHwl** [comment]
噢噢，这个问题解决了，但是我修改了代码之后，浏览器还是会报错
[WDS] Disconnected!
GET http://127.0.0.1:10086/sockjs-node/info?t=1545638330423 net::ERR_CONNECTION_REFUSED

然后IDE中终端运行提示：
创建  添加文件  src\pages\index\index.js___jb_tmp___
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'D:\Taro\taro_demo02\src\pages\index\index.js___jb_tmp___'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at processFiles (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\src\h5.js:804:19)
    at FSWatcher.watcher.on.filePath (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\src\h5.js:843:7)
    at FSWatcher.emit (events.js:182:13)
    at FSWatcher.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_chokidar@2.0.4@chokidar\index.js:199:15)
    at FSWatcher._emit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_chokidar@2.0.4@chokidar\index.js:241:5)
    at FSWatcher.NodeFsHandler._handleFile (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_chokidar@2.0.4@chokidar\lib\nodefs-handler.js:279:10)
    at FSWatcher.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_chokidar@2.0.4@chokidar\lib\nodefs-handler.js:480:21)
    at FSReqWrap.oncomplete (fs.js:155:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taro_demo02@1.0.0 build:h5: `taro build --type h5 "--watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the taro_demo02@1.0.0 build:h5 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-12-24T07_39_00_868Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taro_demo02@1.0.0 dev:h5: `npm run build:h5 -- --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the taro_demo02@1.0.0 dev:h5 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-12-24T07_39_00_899Z-debug.log
当我重新npm run dev xxx后就正常了。（每次修改一点代码就要重新编译）
