### ISSUE TITLE
组件化有问题？

### ISSUE THREAD

**Issue by fantasticsoul** [NervJS/taro#165]
```
ok: <MyComponent prop1="name" />
bad: <MyComponent prop1={{name:'test'}} />
```

后面能够支持传递对象吗

更新，已解决：
传递引用就好了，错误提示必须传递 字符串 数字 或者 引用修饰符
```
const data = {name:'test'};
<MyComponent prop1={data} />
```
感觉文档里没有吧这些坑特别的说明一下啊，文档的组件化章节可以把这些写明白的

**Comment by fantasticsoul** [comment]
感觉ts的组件化有问题，js的是没问题的，哎.....
```
TypeError: Property key of ObjectProperty expected node to be of a type ["Identifier","StringLiteral","NumericLiteral"] but instead got "MemberExpression"
    at validate (/opt/proj/l2l/miniapp-tora/node_modules/_babel-types@6.26.0@babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/opt/proj/l2l/miniapp-tora/node_modules/_babel-types@6.26.0@babel-types/lib/definitions/core.js:505:63)
    at Object.validate (/opt/proj/l2l/miniapp-tora/node_modules/_babel-types@6.26.0@babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (/opt/proj/l2l/miniapp-tora/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/replacement.js:176:7)
    at NodePath.replaceWith (/opt/proj/l2l/miniapp-tora/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/replacement.js:160:8)
    at Identifier (/opt/proj/l2l/miniapp-tora/node_modules/_@tarojs_transformer-wx@0.0.54@@tarojs/transformer-wx/lib/src/class.js:537:42)
    at NodePath._call (/opt/proj/l2l/miniapp-tora/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/opt/proj/l2l/miniapp-tora/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/opt/proj/l2l/miniapp-tora/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/opt/proj/l2l/miniapp-tora/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:150:16)
```

**Comment by luckyadam** [comment]
收到~ 我抽空更新下文档~

**Comment by yuche** [comment]
1.0.0 取消了这个限制
