### ISSUE TITLE
鸿蒙开发，DevEco Previewer 预览页面失败

### ISSUE THREAD

**Issue by CaedmonW** [NervJS/taro#16729]
### 相关平台
鸿蒙

**使用框架: React**

### 复现步骤
1. taro cli 默认模版，输出鸿蒙
2. 使用DevEco Previewer预览首页

### 期望结果
可以正常预览页面

### 实际结果
DevEco 预览报错
```
[ArkRuntime Log] TypeError: Cannot read property mount of null
[Engine Log]    page: pages/index/index.js
[Engine Log]    Error message: Cannot read property mount of null
[Engine Log]    at mount (entry/src/main/ets/npm/@tarojs/plugin-framework-react/dist/runtime/page.ts:135:9)
[Engine Log]    at anonymous (entry/src/main/ets/npm/@tarojs/plugin-framework-react/dist/runtime/page.ts:152:9)
[Engine Log]    at callFn (entry/src/main/ets/npm/@tarojs/runtime/utils/index.ts:148:12)
[Engine Log]    at handlePageAppear 
[Engine Log]    at aboutToAppear (entry/src/main/ets/pages/index/index.ets:52:5)
```

### 环境信息
```
DevEco Studio: 5.0.3.900

👽 Taro v4.0.6


  Taro CLI 4.0.6 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v18.19.1/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
    npmPackages:
      @tarojs/cli: 4.0.6 => 4.0.6 
      @tarojs/components: 4.0.6 => 4.0.6 
      @tarojs/helper: 4.0.6 => 4.0.6 
      @tarojs/plugin-framework-react: 4.0.6 => 4.0.6 
      @tarojs/plugin-platform-alipay: 4.0.6 => 4.0.6 
      @tarojs/plugin-platform-h5: 4.0.6 => 4.0.6 
      @tarojs/plugin-platform-harmony-ets: ^4.0.6 => 4.0.6 
      @tarojs/plugin-platform-harmony-hybrid: 4.0.6 => 4.0.6 
      @tarojs/plugin-platform-jd: 4.0.6 => 4.0.6 
      @tarojs/plugin-platform-qq: 4.0.6 => 4.0.6 
      @tarojs/plugin-platform-swan: 4.0.6 => 4.0.6 
      @tarojs/plugin-platform-tt: 4.0.6 => 4.0.6 
      @tarojs/plugin-platform-weapp: 4.0.6 => 4.0.6 
      @tarojs/react: 4.0.6 => 4.0.6 
      @tarojs/runtime: 4.0.6 => 4.0.6 
      @tarojs/shared: 4.0.6 => 4.0.6 
      @tarojs/taro: 4.0.6 => 4.0.6 
      @tarojs/vite-runner: 4.0.6 => 4.0.6 
      babel-preset-taro: 4.0.6 => 4.0.6 
      eslint-config-taro: 4.0.6 => 4.0.6 
      react: ^18.0.0 => 18.3.1 


```

---
### 补充信息
看起来是DevEco预览页面的时候，不会执行`EntryAbility.onCreate`，所以`createReactApp`没能执行，导致执行`Current.app!.mount()`时报错

需要在页面组件的 `aboutToAppear`生命周期中手动初始化`Current.app`之后，页面才可以正常预览出来。

有没有更好的办法能够预览页面？

**Comment by tangqi9** [comment]
有解决吗

**Comment by CaedmonW** [comment]
> 有解决吗

预览效果和真机效果不是很一致，预览里面似乎也没办法做到代码变更时热重载，所以放弃使用Previewer了

**Comment by prettyboyweiwei** [comment]
@CaedmonW 遇到同样报错，你所说的手动初始化Current.app，能详细说明下吗，比如在哪新增什么代码
> 需要在页面组件的 aboutToAppear生命周期中手动初始化Current.app之后，页面才可以正常预览出来。

**Comment by CaedmonW** [comment]
> [@CaedmonW](https://github.com/CaedmonW) 遇到同样报错，你所说的手动初始化Current.app，能详细说明下吗，比如在哪新增什么代码

目前Taro开发鸿蒙不推荐使用Previewer，因为并没有解决啥问题
https://docs.taro.zone/docs/harmony#3-%E9%A2%84%E8%A7%88--%E8%B0%83%E8%AF%95
