### ISSUE TITLE
命令行缺少window参数

### ISSUE THREAD

**Issue by wikiMaji** [NervJS/taro#16938]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:414:11)
    at spawn (node:child_process:761:9)
    at D:\code\yd\taroyiqiwan\taroYiQiWan\node_modules\@tarojs\rn-runner\src\index.ts:64:12
    at Generator.next (<anonymous>)
    at D:\code\yd\taroyiqiwan\taroYiQiWan\node_modules\@tarojs\rn-runner\dist\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\code\yd\taroyiqiwan\taroYiQiWan\node_modules\@tarojs\rn-runner\dist\index.js:4:12)
    at rnRunner (D:\code\yd\taroyiqiwan\taroYiQiWan\node_modules\@tarojs\rn-runner\dist\index.js:39:12)
    at Object.<anonymous> (D:\code\yd\taroyiqiwan\taroYiQiWan\node_modules\@tarojs\cli\dist\presets\platforms\rn.js:91:27)
    at step (D:\code\yd\taroyiqiwan\taroYiQiWan\node_modules\@tarojs\cli\dist\presets\platforms\rn.js:87:23) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
}
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:414:11)
    at spawn (node:child_process:761:9)
    at D:\code\yd\taroyiqiwan\taroYiQiWan\node_modules\@tarojs\rn-runner\src\index.ts:64:12
    at Generator.next (<anonymous>)
    at D:\code\yd\taroyiqiwan\taroYiQiWan\node_modules\@tarojs\rn-runner\dist\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\code\yd\taroyiqiwan\taroYiQiWan\node_modules\@tarojs\rn-runner\dist\index.js:4:12)
    at rnRunner (D:\code\yd\taroyiqiwan\taroYiQiWan\node_modules\@tarojs\rn-runner\dist\index.js:39:12)
    at Object.<anonymous> (D:\code\yd\taroyiqiwan\taroYiQiWan\node_modules\@tarojs\cli\dist\presets\platforms\rn.js:91:27)
    at step (D:\code\yd\taroyiqiwan\taroYiQiWan\node_modules\@tarojs\cli\dist\presets\platforms\rn.js:87:23) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
}

### 期望结果
(0, child_process_1.spawn)(npxCmd, [
                    'react-native',
                    'start',
                    '--custom-log-reporter-path',
                    '@tarojs/rn-supporter/TerminalReporter'
                ].concat(cliParams), {
                    stdio: 'inherit',
                    shell:true
                });

### 实际结果
(0, child_process_1.spawn)(npxCmd, [
                    'react-native',
                    'start',
                    '--custom-log-reporter-path',
                    '@tarojs/rn-supporter/TerminalReporter'
                ].concat(cliParams), {
                    stdio: 'inherit'
                });

### 环境信息
```
  Taro CLI 4.0.7 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 18.20.4 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - D:\Program Files\nodejs\yarn.CMD
      npm: 10.7.0 - D:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 4.0.5 => 4.0.5
      @tarojs/components: 4.0.5 => 4.0.5
      @tarojs/components-rn: 4.0.5 => 4.0.5
      @tarojs/helper: 4.0.5 => 4.0.5
      @tarojs/plugin-framework-react: 4.0.5 => 4.0.5
      @tarojs/plugin-platform-alipay: 4.0.5 => 4.0.5
      @tarojs/plugin-platform-h5: 4.0.5 => 4.0.5
      @tarojs/plugin-platform-jd: 4.0.5 => 4.0.5
      @tarojs/plugin-platform-qq: 4.0.5 => 4.0.5
      @tarojs/plugin-platform-swan: 4.0.5 => 4.0.5
      @tarojs/plugin-platform-tt: 4.0.5 => 4.0.5
      @tarojs/plugin-platform-weapp: 4.0.5 => 4.0.5
      @tarojs/react: 4.0.5 => 4.0.5
      @tarojs/rn-runner: 4.0.5 => 4.0.5
      @tarojs/rn-supporter: 4.0.5 => 4.0.5
      @tarojs/runtime: 4.0.5 => 4.0.5
      @tarojs/runtime-rn: 4.0.5 => 4.0.5
      @tarojs/shared: 4.0.5 => 4.0.5
      @tarojs/taro: 4.0.5 => 4.0.5
      @tarojs/taro-loader: 4.0.5 => 4.0.5
      @tarojs/taro-rn: 4.0.5 => 4.0.5
      @tarojs/webpack5-runner: 4.0.5 => 4.0.5
      babel-preset-taro: 4.0.5 => 4.0.5
      eslint-config-taro: 4.0.5 => 4.0.5
      expo: 51 => 51.0.38
      react: ^18.3.1 => 18.3.1
      react-native: 0.75.2 => 0.75.2
```

---
### 补充信息
缺少  shell:true

**Comment by wikiMaji** [comment]
![image](https://github.com/user-attachments/assets/234da51b-9b84-4444-99b4-65beb6f37ea7)
每次  yarn 之后需要手动 添加:
shell:true

可以兼容下windows吗
mac不报错
