### ISSUE TITLE
@tarojs/helper 依赖的 @swc/core@1.10.1 存在异常

### ISSUE THREAD

**Issue by 2410655661** [NervJS/taro#17085]
### 相关平台
微信小程序

**小程序基础库: 3.7.3**
**使用框架: React**

### 复现步骤
taro init 初始化项目之后，运行yarn build:weapp 或者 yarn dev:weapp 即可复现

### 期望结果
@swc/core的这个依赖因为版本问题出现了N次问题了，能否将@swc/core依赖放置到peer依赖中，或者是锁定对应的版本号，而不是使用当前的最新大版本

### 实际结果
@swc/core安装争确的版本，不会影响编译

### 环境信息
```
 Taro v3.5.12

  Taro CLI 3.5.12 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.18.3 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - D:\Program Files\nodejs\yarn.CMD
      npm: 6.14.15 - D:\Program Files\nodejs\npm.CMD  
```

**Comment by 2410655661** [comment]
尽管出现了N遍了，还是补充一下报错信息：
thread '<unnamed>' panicked at C:\Users\runneradmin/.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc-9.0.0\src\plugin.rs:169:14:
failed to invoke plugin: failed to invoke plugin on 'Some("\\src\\app.config.ts")'

Caused by:
    0: failed to invoke `D:\WorkFiles\EZR.FE.KOS.Mini\node_modules\@tarojs\helper\swc\plugin-define-config\target\wasm32-wasi\release\swc_plugin_define_config.wasm` as js transform plugin at D:\WorkFiles\EZR.FE.KOS.Mini\node_modules\@tarojs\helper\swc\plugin-define-config\target\wasm32-wasi\release\swc_plugin_define_config.wasm
    1: wasm plugin bytecheck failed "failed without error information; enable debug assertions and the `alloc` feature in rancor for error information"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("\\src\\app.config.ts")'

Caused by:
    0: failed to invoke `D:\WorkFiles\EZR.FE.KOS.Mini\node_modules\@tarojs\helper\swc\plugin-define-config\target\wasm32-wasi\release\swc_plugin_define_config.wasm` as js transform plugin at D:\WorkFiles\EZR.FE.KOS.Mini\node_modules\@tarojs\helper\swc\plugin-define-config\target\wasm32-wasi\release\swc_plugin_define_config.wasm
    1: wasm plugin bytecheck failed "failed without error information; enable debug assertions and the `alloc` feature in rancor for error information"
    at Compiler.transformSync (D:\WorkFiles\EZR.FE.KOS.Mini\node_modules\@tarojs\helper\node_modules\@swc\core\index.js:249:29)
    at Object.transformSync (D:\WorkFiles\EZR.FE.KOS.Mini\node_modules\@tarojs\helper\node_modules\@swc\core\index.js:359:21)
    at compile (D:\WorkFiles\EZR.FE.KOS.Mini\node_modules\@tarojs\helper\node_modules\@swc\register\lib\node.js:76:22)
    at compileHook (D:\WorkFiles\EZR.FE.KOS.Mini\node_modules\@tarojs\helper\node_modules\@swc\register\lib\node.js:91:16)
    at Module._compile (D:\WorkFiles\EZR.FE.KOS.Mini\node_modules\pirates\lib\index.js:113:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .ts] (D:\WorkFiles\EZR.FE.KOS.Mini\node_modules\pirates\lib\index.js:121:7)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'GenericFailure'
}

**Comment by faimi** [comment]
我也遇到了这个问题Error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("D:/project/frontend-mobile-core/docs/docs/components/base/button/index.tsx")'
Caused by:
    0: failed to invoke `D:\project\frontend-mobile-core\docs\node_modules\dumi\compiled\crates\swc_plugin_react_demo.wasm` as js transform plugin at D:\project\frontend-mobile-core\docs\node_modules\dumi\compiled\crates\swc_plugin_react_demo.wasm
    1: failed to run Wasm plugin transform. Please ensure the version of `swc_core` used by the plugin is compatible with the host runtime. See the documentation for compatibility information. If you are an author of the plugin, please update `swc_core` to the compatible version.
                        
                       Note that if you want to use the os features like filesystem, you need to use `wasi`. Wasm itself does not have concept of filesystem.
                        
                       https://swc.rs/docs/plugin/selecting-swc-core
       
                       See https://plugins.swc.rs/versions/from-plugin-runner/4.0.0 for the list of the compatible versions.
                        
                       Build info: 
                           Date: 2024-11-11
                           Timestamp: 2024-11-11T02:32:26.458927800Z
                           
                       Version info: 
                           swc_plugin_runner: 4.0.0
                           Dependencies: anyhow 1.0.93,codspeed-criterion-compat 2.7.2,criterion 0.5.1,enumset 1.1.5,futures 0.3.31,once_cell 1.20.2,parking_lot 0.12.3,serde 1.0.214,serde_json 1.0.132,swc_atoms 2.0.0,swc_common 4.0.0,swc_css_ast 4.0.1,swc_css_parser 4.0.0,swc_ecma_ast 4.0.1,swc_ecma_loader 4.0.0,swc_ecma_parser 5.0.0,swc_ecma_visit 4.0.0,swc_malloc 1.0.0,swc_plugin_proxy 4.0.0,testing 4.0.0,tokio 1.41.1,tracing 0.1.40,vergen 9.0.1,virtual-fs 0.16.0,wasmer 4.3.7,wasmer-cache 4.3.7,wasmer-compiler-cranelift 4.3.7,wasmer-wasix 0.27.0
                       
    2: RuntimeError: unreachable
           at rust_panic (swc_plugin_react_demo.wasm[559]:0x69366)
           at std::panicking::rust_panic_with_hook::h6721eef20cf7d59d (swc_plugin_react_demo.wasm[469]:0x5f06a)
           at std::panicking::begin_panic_handler::{{closure}}::h472d22c5c2e3ea0d (swc_plugin_react_demo.wasm[568]:0x6984a)
           at std::sys::backtrace::__rust_end_short_backtrace::h4260713718d466f0 (swc_plugin_react_demo.wasm[567]:0x69784)
           at rust_begin_unwind (swc_plugin_react_demo.wasm[393]:0x52770)
           at core::panicking::panic_fmt::h122e1e6e072e1f66 (swc_plugin_react_demo.wasm[250]:0x4374e)
           at <swc_plugin_react_demo::ReactDemoVisitor as swc_ecma_visit::generated::VisitMut>::visit_mut_module_item::h092ff1436679c964 (swc_plugin_react_demo.wasm[671]:0x823ad)
           at __transform_plugin_process_impl (swc_plugin_react_demo.wasm[1539]:0x1b028e)
           at __transform_plugin_process_impl.command_export (swc_plugin_react_demo.wasm[1685]:0x1c5217)
