### ISSUE TITLE
Error: Cannot find module '../transformation/file'

### ISSUE THREAD

**Issue by Vibing** [NervJS/taro#1721]
**问题描述**
`npm run dev:weapp`后编译报错： Error: Cannot find module '../transformation/file'
```
{ Error: Cannot find module '../transformation/file'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Mac/web/ejia/weapp/packages/events_2019/node_modules/babel-core/lib/api/node.js:6:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3) code: 'MODULE_NOT_FOUND' }
```

### package.json
```json
"dependencies": {
    "@tarojs/async-await": "^1.2.2",
    "@tarojs/components": "^1.2.1",
    "@tarojs/mobx": "^1.2.1",
    "@tarojs/mobx-h5": "^1.2.1",
    "@tarojs/mobx-prop-types": "^1.2.2",
    "@tarojs/mobx-rn": "^1.2.1",
    "@tarojs/rn-runner": "^1.2.1",
    "@tarojs/router": "^1.2.1",
    "@tarojs/taro": "^1.2.1",
    "@tarojs/taro-alipay": "^1.2.1",
    "@tarojs/taro-h5": "^1.2.1",
    "@tarojs/taro-swan": "^1.2.1",
    "@tarojs/taro-tt": "^1.2.1",
    "@tarojs/taro-weapp": "^1.2.1",
    "mobx": "^5.5.2",
    "nerv-devtools": "^1.3.9",
    "nervjs": "^1.3.9"
  },
  "devDependencies": {
    "@tarojs/plugin-babel": "^1.2.2",
    "@tarojs/plugin-csso": "^1.2.1",
    "@tarojs/plugin-less": "^1.2.1",
    "@tarojs/plugin-uglifyjs": "^1.2.1",
    "@tarojs/webpack-runner": "^1.2.1",
    "@types/react": "16.3.14",
    "@types/webpack-env": "^1.13.6",
    "babel-eslint": "^8.2.3",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-jsx-stylesheet": "^0.6.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "eslint": "^4.19.1",
    "eslint-config-taro": "^1.2.1",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-taro": "^1.2.1",
    "typescript": "^3.0.1"
  }
```

**报错信息**
<img width="1074" alt="wx20181227-143415 2x" src="https://user-images.githubusercontent.com/10387532/50468782-84fedf00-09e4-11e9-93ab-90228c679e62.png">

**系统信息**
 - 操作系统: macOS 10.14
 - Taro 版本 Taro v1.2.1
 - Node.js 版本 v8.9.0
 - 报错平台 weapp

**Comment by Vibing** [comment]
找到原因了，是因为安装了`@tarojs/mobx-prop-types`，但是如何解决呢？

**Comment by nanjingboy** [comment]
@Vibing 我尝试了下，跟 `@tarojs/mobx-prop-types` 无关的。

**Comment by Tingglelaoo** [comment]
> 找到原因了，是因为安装了`@tarojs/mobx-prop-types`，但是如何解决呢？

我也遇到相同的问题了，是watchman版本过旧的问题。

```js
Error: watchman 4.6.0 is already installed
To upgrade to 4.9.0_2, run `brew upgrade watchman`.
```

可以运行下 `brew upgrade watchman`看看

**Comment by Vibing** [comment]
@Tingglelaoo 好的 谢谢

**Comment by yqwoe** [comment]
watchman 4.9.0_3 依然有这个问题
