### ISSUE TITLE
taro convet之后的项目打包成alipay失败

### ISSUE THREAD

**Issue by hu-qi** [NervJS/taro#1766]
本次操作以官方尝试的nideshop这个开源微信小程序为例，taro convert十分顺利，但是之后的转换成alipay就出现了各种问题
**前置操作**
` git clone https://github.com/tumobi/nideshop-mini-program `
`cd  nideshop-mini-program`
`taro convert`
![image](https://user-images.githubusercontent.com/17986122/50537454-a43f6d00-0b9a-11e9-8d66-795d74daa352.png)
![image](https://user-images.githubusercontent.com/17986122/50537467-dd77dd00-0b9a-11e9-9974-ea6edce8593a.png)
`cd  taroConvert`
`npm install`
一切顺利
接下来的操作就有些不顺利了，好像和taro convert生成的imports里边的文件有点关系
`npm run build：aliapy`

**问题描述**
- 显示·缺少`npm包showdown.js，开始安装...`等(经查证，是trao convert 处理wxParse目录时复制不完整)
- 错误  组件编译  组件src/imports/TaroParseaaTmpl.js编译失败！
- 错误  组件编译  组件src/imports/TaroParseaaTmpl.js编译失败！
- 错误  组件编译  组件src/imports/TaroParseiTmpl.js编译失败！
- 错误  组件编译  组件src/imports/TaroParseiTmpl.js编译失败！
**复现步骤**
一开始是缺少npm包，一直显示·缺少`npm包showdown.js，开始安装...`
![image](https://user-images.githubusercontent.com/17986122/50537553-f3d26880-0b9b-11e9-80cc-eda84f239c38.png)
查到是wxParse.js里面的问题
![image](https://user-images.githubusercontent.com/17986122/50537576-64798500-0b9c-11e9-97ba-e934dbe9b542.png)
一看吓一跳，wxParse里面的文件居然没复制全
![image](https://user-images.githubusercontent.com/17986122/50537588-a1457c00-0b9c-11e9-9f2f-2438acc7d2e2.png)
然后手动把html2json.js和showdown.js复制到taroConvert/src/lib/wxParse下，并修改wxParse.js
`
import showdown from './showdown.js'
import HtmlToJson from './html2json.js'
`
,继续 `npm run build：aliapy`
意料之中还是有错·缺少`npm包wxDiscode.js，开始安装...`,赶紧ctrl+c结束进程，修改html2json.js
`
var wxDiscode = require('./wxDiscode.js');
var HTMLParser = require('./htmlparser.js');
`
,继续 `npm run build：aliapy`
终极问题出现了
![image](https://user-images.githubusercontent.com/17986122/50537791-9213fd80-0b9f-11e9-9b34-9237cb1e6043.png)
`
错误  组件编译  组件src/imports/TaroParseaaTmpl.js编译失败！
{ Error: ENOENT: no such file or directory, open 'E:\learn\node\nideshop\nideshop-mini-program\taroConvert\src\imports\TaroParseabTmpl'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at buildSingleComponent (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1699:31)
    at Promise.all.componentPathList.map.componentObj (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1632:60)
    at Array.map (<anonymous>)
    at buildDepComponents (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1632:40)
    at buildSingleComponent (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1796:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path:
   'E:\\learn\\node\\nideshop\\nideshop-mini-program\\taroConvert\\src\\imports\\TaroParseabTmpl' }
生成  组件配置  dist/dist/imports/TaroParseazTmpl.json
生成  组件逻辑  dist/dist/imports/TaroParseazTmpl.js
生成  组件模板  dist/dist/imports/TaroParseazTmpl.axml
生成  组件样式  dist/dist/imports/TaroParseazTmpl.acss
错误  组件编译  组件src/imports/TaroParseazTmpl.js编译失败！
TypeError: Cannot read property 'wxss' of undefined
    at buildDepComponentsResult.map.item (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1639:23)
    at Array.map (<anonymous>)
    at getDepStyleList (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1638:44)
    at buildSingleComponent (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1835:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
生成  组件配置  dist/dist/imports/TaroParseiTmpl.json
生成  组件逻辑  dist/dist/imports/TaroParseiTmpl.js
生成  组件模板  dist/dist/imports/TaroParseiTmpl.axml
生成  组件样式  dist/dist/imports/TaroParseiTmpl.acss
错误  组件编译  组件src/imports/TaroParseiTmpl.js编译失败！
TypeError: Cannot read property 'wxss' of undefined
    at buildDepComponentsResult.map.item (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1639:23)
    at Array.map (<anonymous>)
    at getDepStyleList (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1638:44)
    at buildSingleComponent (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1835:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
生成  组件配置  dist/dist/imports/TaroParsehTmpl.json
生成  组件逻辑  dist/dist/imports/TaroParsehTmpl.js
生成  组件模板  dist/dist/imports/TaroParsehTmpl.axml
生成  组件样式  dist/dist/imports/TaroParsehTmpl.acss
错误  组件编译  组件src/imports/TaroParsehTmpl.js编译失败！
TypeError: Cannot read property 'wxss' of undefined
    at buildDepComponentsResult.map.item (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1639:23)
    at Array.map (<anonymous>)
    at getDepStyleList (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1638:44)
    at buildSingleComponent (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1835:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
生成  组件配置  dist/dist/imports/TaroParsegTmpl.json
生成  组件逻辑  dist/dist/imports/TaroParsegTmpl.js
生成  组件模板  dist/dist/imports/TaroParsegTmpl.axml
生成  组件样式  dist/dist/imports/TaroParsegTmpl.acss
错误  组件编译  组件src/imports/TaroParsegTmpl.js编译失败！
TypeError: Cannot read property 'wxss' of undefined
    at buildDepComponentsResult.map.item (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1639:23)
    at Array.map (<anonymous>)
    at getDepStyleList (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1638:44)
    at buildSingleComponent (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1835:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
生成  组件配置  dist/dist/imports/TaroParsefTmpl.json
生成  组件逻辑  dist/dist/imports/TaroParsefTmpl.js
生成  组件模板  dist/dist/imports/TaroParsefTmpl.axml
生成  组件样式  dist/dist/imports/TaroParsefTmpl.acss
错误  组件编译  组件src/imports/TaroParsefTmpl.js编译失败！
TypeError: Cannot read property 'wxss' of undefined
    at buildDepComponentsResult.map.item (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1639:23)
    at Array.map (<anonymous>)
    at getDepStyleList (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1638:44)
    at buildSingleComponent (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1835:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
生成  组件配置  dist/dist/imports/TaroParseeTmpl.json
生成  组件逻辑  dist/dist/imports/TaroParseeTmpl.js
生成  组件模板  dist/dist/imports/TaroParseeTmpl.axml
生成  组件样式  dist/dist/imports/TaroParseeTmpl.acss
错误  组件编译  组件src/imports/TaroParseeTmpl.js编译失败！
TypeError: Cannot read property 'wxss' of undefined
    at buildDepComponentsResult.map.item (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1639:23)
    at Array.map (<anonymous>)
    at getDepStyleList (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1638:44)
    at buildSingleComponent (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1835:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
生成  组件配置  dist/dist/imports/TaroParsedTmpl.json
生成  组件逻辑  dist/dist/imports/TaroParsedTmpl.js
生成  组件模板  dist/dist/imports/TaroParsedTmpl.axml
生成  组件样式  dist/dist/imports/TaroParsedTmpl.acss
错误  组件编译  组件src/imports/TaroParsedTmpl.js编译失败！
TypeError: Cannot read property 'wxss' of undefined
    at buildDepComponentsResult.map.item (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1639:23)
    at Array.map (<anonymous>)
    at getDepStyleList (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1638:44)
    at buildSingleComponent (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1835:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
生成  组件配置  dist/dist/imports/TaroParsecTmpl.json
生成  组件逻辑  dist/dist/imports/TaroParsecTmpl.js
生成  组件模板  dist/dist/imports/TaroParsecTmpl.axml
生成  组件样式  dist/dist/imports/TaroParsecTmpl.acss
错误  组件编译  组件src/imports/TaroParsecTmpl.js编译失败！
TypeError: Cannot read property 'wxss' of undefined
    at buildDepComponentsResult.map.item (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1639:23)
    at Array.map (<anonymous>)
    at getDepStyleList (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1638:44)
    at buildSingleComponent (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1835:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
生成  组件配置  dist/dist/imports/TaroParsebTmpl.json
生成  组件逻辑  dist/dist/imports/TaroParsebTmpl.js
生成  组件模板  dist/dist/imports/TaroParsebTmpl.axml
生成  组件样式  dist/dist/imports/TaroParsebTmpl.acss
错误  组件编译  组件src/imports/TaroParsebTmpl.js编译失败！
TypeError: Cannot read property 'wxss' of undefined
    at buildDepComponentsResult.map.item (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1639:23)
    at Array.map (<anonymous>)
    at getDepStyleList (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1638:44)
    at buildSingleComponent (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1835:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
生成  组件配置  dist/dist/imports/TaroParseaTmpl.json
生成  组件逻辑  dist/dist/imports/TaroParseaTmpl.js
生成  组件模板  dist/dist/imports/TaroParseaTmpl.axml
生成  组件样式  dist/dist/imports/TaroParseaTmpl.acss
错误  组件编译  组件src/imports/TaroParseaTmpl.js编译失败！
TypeError: Cannot read property 'wxss' of undefined
    at buildDepComponentsResult.map.item (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1639:23)
    at Array.map (<anonymous>)
    at getDepStyleList (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1638:44)
    at buildSingleComponent (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1835:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
生成  组件配置  dist/dist/imports/TaroParsezTmpl.json
生成  组件逻辑  dist/dist/imports/TaroParsezTmpl.js
生成  组件模板  dist/dist/imports/TaroParsezTmpl.axml
生成  组件样式  dist/dist/imports/TaroParsezTmpl.acss
错误  组件编译  组件src/imports/TaroParsezTmpl.js编译失败！
TypeError: Cannot read property 'wxss' of undefined
    at buildDepComponentsResult.map.item (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1639:23)
    at Array.map (<anonymous>)
    at getDepStyleList (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1638:44)
    at buildSingleComponent (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1835:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
生成  组件配置  dist/dist/imports/TaroParseTmpl.json
生成  组件逻辑  dist/dist/imports/TaroParseTmpl.js
生成  组件模板  dist/dist/imports/TaroParseTmpl.axml
生成  组件样式  dist/dist/imports/TaroParseTmpl.acss
错误  组件编译  组件src/imports/TaroParseTmpl.js编译失败！
TypeError: Cannot read property 'wxss' of undefined
    at buildDepComponentsResult.map.item (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1639:23)
    at Array.map (<anonymous>)
    at getDepStyleList (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1638:44)
    at buildSingleComponent (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1835:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
生成  页面配置  dist/pages/goods/goods.json
生成  页面逻辑  dist/pages/goods/goods.js
生成  页面模板  dist/pages/goods/goods.axml
生成  页面样式  dist/pages/goods/goods.acss
错误  页面编译  页面E:\learn\node\nideshop\nideshop-mini-program\taroConvert\src\pages\goods\goods编译失败！
TypeError: Cannot read property 'wxss' of undefined
    at buildDepComponentsResult.map.item (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1639:23)
    at Array.map (<anonymous>)
    at getDepStyleList (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1638:44)
    at buildSinglePage (C:\Users\huqi\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1397:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

**期望行为**
期望各位大佬有空帮忙看看，或者指点指点一下

**报错信息**

前文已经详细列举

**系统信息**
👽 Taro v1.2.3
  Taro CLI 1.2.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.14.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

 - 报错平台 [weapp2alipay]

**补充信息**
根据我的尝试以及愚见，最开的问题应该是taro convert的时候没有完整的复制(或处理)wxParse这个目录，导致后续的问题；然后就是对taroConvert生成的import目录里边的文件没能正常处理。目测和我手动复制过来的文件也有关系

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/taroize.html#%E8%BD%AC%E6%8D%A2-wxparse-%E6%8A%A5%E9%94%99%E4%B8%8D%E5%AD%98%E5%9C%A8%E6%96%87%E4%BB%B6
