### ISSUE TITLE
Taro v1.2.3 less css module 编译报错

### ISSUE THREAD

**Issue by zhangzhenfei** [NervJS/taro#1767]
**问题描述**
Taro v1.2.3 less css module 编译报错

编译  组件文件  src/components/mall/SearchBox/index.tsx
生成  替换代码  为文件 /workspace/mp-shopping-mall/src/components/mall/SearchBox/index.tsx 生成 css modules
错误  组件编译  组件src/components/mall/SearchBox/index.tsx编译失败！
TypeError: Cannot read property 'exports' of undefined
    at ImportDeclaration (/Users/zhangzhenfei/.config/yarn/global/node_modules/@tarojs/cli/src/weapp.js:447:36)
    at NodePath._call (/Users/zhangzhenfei/.config/yarn/global/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/zhangzhenfei/.config/yarn/global/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/zhangzhenfei/.config/yarn/global/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/zhangzhenfei/.config/yarn/global/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/zhangzhenfei/.config/yarn/global/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/zhangzhenfei/.config/yarn/global/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/zhangzhenfei/.config/yarn/global/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/zhangzhenfei/.config/yarn/global/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/zhangzhenfei/.config/yarn/global/node_modules/babel-traverse/lib/context.js:150:16)

SearchBox/index.tsx
```js
import Taro, { Component } from "@tarojs/taro";
import { View, Navigator, Input } from "@tarojs/components";

import styles from "./index.less";

class SearchBox extends Component {
  render() {
    return (
      <View className={styles.test}>
        <Navigator url="">
          sdf
          <Input type="text" />
        </Navigator>
      </View>
    );
  }
}

export default SearchBox;

```

SearchBox/index.less
```css
.test {
  color: red;
  .txt {
    font-size: 36px;
  }
}

```

config.js
```js
const config = {
  projectName: 'mp-shopping-mall',
  date: '2018-12-30',
  designWidth: 750,
  deviceRatio: {
    '640': 2.34 / 2,
    '750': 1,
    '828': 1.81 / 2
  },
  sourceRoot: 'src',
  outputRoot: 'dist',
  plugins: {
    babel: {
      sourceMap: true,
      presets: ['env'],
      plugins: ['transform-decorators-legacy', 'transform-class-properties', 'transform-object-rest-spread']
    }
  },
  defineConstants: {},
  alias: {
    // 定义别名
    '@': 'src',
    '@components': 'src/components',
    '@utils': 'src/utils'
  },
  copy: {
    patterns: [],
    options: {}
  },
  weapp: {
    module: {
      postcss: {
        autoprefixer: {
          enable: true,
          config: {
            browsers: ['last 3 versions', 'Android >= 4.1', 'ios >= 8']
          }
        },
        pxtransform: {
          enable: true,
          config: {}
        },
        url: {
          enable: true,
          config: {
            limit: 10240 // 设定转换尺寸上限
          }
        },
        // css modules 功能开关与相关配置
        cssModules: {
          enable: true, // 默认为 false，如需使用 css modules 功能，则设为 true
          config: {
            namingPattern: 'module', // 转换模式，取值为 global/module，下文详细说明
            generateScopedName: '[name]__[local]___[hash:base64:5]'
          }
        }
      }
    }
  },
  h5: {
    publicPath: '/',
    staticDirectory: 'static',
    module: {
      postcss: {
        autoprefixer: {
          enable: true,
          config: {
            browsers: ['last 3 versions', 'Android >= 4.1', 'ios >= 8']
          }
        },
        // css modules 功能开关与相关配置
        cssModules: {
          enable: true, // 默认为 false，如需使用 css modules 功能，则设为 true
          config: {
            namingPattern: 'module', // 转换模式，取值为 global/module，下文详细说明
            generateScopedName: '[name]__[local]___[hash:base64:5]'
          }
        }
      }
    }
  }
}

module.exports = function(merge) {
  if (process.env.NODE_ENV === 'development') {
    return merge({}, config, require('./dev'))
  }
  return merge({}, config, require('./prod'))
}

```

**Comment by zhangzhenfei** [comment]
备注：运行命令是dev weapp

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/50574214-c812e500-0e1e-11e9-9418-9dff776c20b7.png)
请仔细看下文档
