### ISSUE TITLE
组件 render 方法只返回 null 的时候编译错误

### ISSUE THREAD

**Issue by jo32** [NervJS/taro#1785]
**问题描述**
组件 render 方法只返回 null 的时候编译错误

**复现步骤**
```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

export default class TestComp extends Component {

    constructor() {
        this.state = {
            hello: undefined
        }
    }

    componentDidMount() {
        this.setState({
            hello: 'world!'
        });
        console.log(this.state.hello);
    }

    render() {
        return null
    }
}
```

当某处引用这个 component 的时候

```
import TestComp from "./testcomp";

<TestComp />
```

运行 npm run build:weapp

**期望行为**
编译正常

**报错信息**
```
错误  页面编译  页面/Users/jo32/Projects/demos/tarodemo3/src/pages/index/index编译失败！
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.relative (path.js:1265:5)
    at pageDepComponents.forEach.depComponent (/Users/jo32/.nvm/versions/node/v9.2.0/lib/node_modules/@tarojs/cli/src/weapp.js:1326:64)
    at Array.forEach (<anonymous>)
    at componentMap.forEach.component (/Users/jo32/.nvm/versions/node/v9.2.0/lib/node_modules/@tarojs/cli/src/weapp.js:1320:31)
    at Array.forEach (<anonymous>)
    at realComponentsPathList.forEach.component (/Users/jo32/.nvm/versions/node/v9.2.0/lib/node_modules/@tarojs/cli/src/weapp.js:1319:24)
    at Array.forEach (<anonymous>)
    at buildSinglePage (/Users/jo32/.nvm/versions/node/v9.2.0/lib/node_modules/@tarojs/cli/src/weapp.js:1316:30)
    at <anonymous>
```

**系统信息**
```
  Taro CLI 1.2.0 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.2.0 - ~/.nvm/versions/node/v9.2.0/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 6.5.0 - ~/.nvm/versions/node/v9.2.0/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.2.0 => 1.2.0
      @tarojs/components: ^1.2.0 => 1.2.0
      @tarojs/plugin-babel: ^1.2.0 => 1.2.0
      @tarojs/plugin-csso: ^1.2.0 => 1.2.0
      @tarojs/plugin-less: ^1.2.0 => 1.2.0
      @tarojs/plugin-uglifyjs: ^1.2.0 => 1.2.0
      @tarojs/redux: ^1.2.0 => 1.2.0
      @tarojs/redux-h5: ^1.2.0 => 1.2.0
      @tarojs/router: ^1.2.0 => 1.2.0
      @tarojs/taro: ^1.2.0 => 1.2.0
      @tarojs/taro-alipay: ^1.2.0 => 1.2.0
      @tarojs/taro-h5: ^1.2.0 => 1.2.0
      @tarojs/taro-swan: ^1.2.0 => 1.2.0
      @tarojs/taro-weapp: ^1.2.0 => 1.2.0
      @tarojs/webpack-runner: ^1.2.0 => 1.2.0
      eslint-config-taro: ^1.2.0 => 1.2.0
      eslint-plugin-taro: ^1.2.0 => 1.2.0
```

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/ecff4a6907a67db66fdc81fa9ab3a99906892a17
