### ISSUE TITLE
小程序转成taro，Error: slot 的值必须是一个字符串

### ISSUE THREAD

**Issue by xrr0520** [NervJS/taro#1835]
**问题描述**
小程序转成taro，Error: slot 的值必须是一个字符串

**复现步骤**
1.自定义组件，用到了slot

```js
// 这里可以贴代码
<view class="{{['button', size ? 'button-' + size : '', type ? 'button-' + type : '', block ? 'button-block' : '', plain ? 'button-' + type + '-plain' : '', pill ? 'border-pill' : '', disable ? 'button-disable' : '']}}"
  hover-class="button-hover" style="{{otherStyle}}">
  <icon wx:if="{{loading}}" type="loading-circle" size="{{size}}" />
  <slot></slot>
</view>
```

**报错信息**

错误  组件转换  common/components/button/index.js
Error: slot 的值必须是一个字符串
  -----
    1 | 
    at Object.codeFrameError (/Users/rongrongxiong/.config/yarn/global/node_modules/@tarojs/taroize/lib/src/utils.js:84:12)
    at enter (/Users/rongrongxiong/.config/yarn/global/node_modules/@tarojs/taroize/lib/src/wxml.js:117:39)
    at NodePath._call (/Users/rongrongxiong/.config/yarn/global/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/rongrongxiong/.config/yarn/global/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/rongrongxiong/.config/yarn/global/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/rongrongxiong/.config/yarn/global/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/rongrongxiong/.config/yarn/global/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/rongrongxiong/.config/yarn/global/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/rongrongxiong/.config/yarn/global/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/rongrongxiong/.config/yarn/global/node_modules/babel-traverse/lib/path/context.js:115:19)

**系统信息**
Taro CLI 1.2.4 environment info:
    System:
      OS: macOS High Sierra 10.13.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.1 - /usr/local/bin/node
      Yarn: 1.9.2 - /usr/local/bin/yarn
      npm: 6.4.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.4 => 1.2.4 
      @tarojs/plugin-babel: 1.2.4 => 1.2.4 
      @tarojs/plugin-csso: 1.2.4 => 1.2.4 
      @tarojs/plugin-sass: 1.2.4 => 1.2.4 
      @tarojs/plugin-uglifyjs: 1.2.4 => 1.2.4 
      @tarojs/router: 1.2.4 => 1.2.4 
      @tarojs/taro: 1.2.4 => 1.2.4 
      @tarojs/taro-alipay: 1.2.4 => 1.2.4 
      @tarojs/taro-h5: 1.2.4 => 1.2.4 
      @tarojs/taro-swan: 1.2.4 => 1.2.4 
      @tarojs/taro-weapp: 1.2.4 => 1.2.4 
      @tarojs/webpack-runner: 1.2.4 => 1.2.4 
      eslint-config-taro: 1.2.4 => 1.2.4 
      eslint-plugin-taro: 1.2.4 => 1.2.4

**Comment by xrr0520** [comment]
这是一个 component 其他代码我一起贴下

、、、js
Component({
  properties: {
    size: String,
    type: String,
    otherStyle: String,
    plain: {
      type: Boolean,
      value: false,
    },
    block: {
      type: Boolean,
      value: false,
    },
    pill: {
      type: Boolean,
      value: false,
    },
    disable: {
      type: Boolean,
      value: false,
    },
    loading: {
      type: Boolean,
      value: false,
    },
  },
})


、、、json
{
  "component": true
}

、、、wxml
<view class="{{['button', size ? 'button-' + size : '', type ? 'button-' + type : '', block ? 'button-block' : '', plain ? 'button-' + type + '-plain' : '', pill ? 'border-pill' : '', disable ? 'button-disable' : '']}}"
  hover-class="button-hover" style="{{otherStyle}}">
  <icon wx:if="{{loading}}" type="loading-circle" size="{{size}}" />
  <slot></slot>
</view>


bug截图
![image](https://user-images.githubusercontent.com/6417186/50754798-de42fa00-1291-11e9-9d8e-78481790b73d.png)

**Comment by xrr0520** [comment]
![image](https://user-images.githubusercontent.com/6417186/50755676-b903bb00-1294-11e9-928d-bf2c59618722.png)
hello 我找到你们相关转译的代码模块 方便教我怎么针对这部分代码 拿实际例子进行调试吗

**Comment by yuche** [comment]
你找到这个包的 index.js，他接受一个对象，

```
{
script: '你的 js',
wxml: '你的 wxml'
}
```

然后就是常规的 node.js 调试

**Comment by xrr0520** [comment]
![_1990f435-8926-4d4f-a769-2eb11aa3b959](https://user-images.githubusercontent.com/6417186/50883741-df0b9580-1423-11e9-9e92-d27cdbb5ffa1.png)
attrs = [] =>nameAttr = undefined 即slot中省略name 会报错

**Comment by xrr0520** [comment]
想问 187行 为啥要加上 else 讲道理不要也没有关系吧

**Comment by yuche** [comment]
的确是这样，我本地的包没有编译最新的代码

**Comment by xrr0520** [comment]
你们下一次发版 计划在什么时候

**Comment by yuche** [comment]
今天或明天
