### ISSUE TITLE
@tarojs/mobx相关的控件，用jest测试时存在问题

### ISSUE THREAD

**Issue by neoscript99** [NervJS/taro#1850]
**问题描述**
- 我的工程通过mobx做状态管理
- 用jest单元测试，配置参考taro-ui
- mobx的Provider时出现以下错误

**复现步骤**

```js
  it('with mobx', () => {
    const component = renderToString(
      <Provider store={stores}>
        <BaseInfo baseInfoStore={baseInfoStore} paramStore={paramStore} />
      </Provider>
    )
    expect(component)
      .toMatchSnapshot()
  })
```

**报错信息**
```
    TypeError: Cannot call a class as a function

      20 | 
      21 |   it('with mobx', () => {
    > 22 |     const component = renderToString(
         |                       ^
      23 |       <Provider store={stores}>
      24 |         <BaseInfo baseInfoStore={baseInfoStore} paramStore={paramStore} />
      25 |       </Provider>

      at _classCallCheck (node_modules/@tarojs/mobx/dist/index.js:9:11)
      at Provider (node_modules/@tarojs/mobx/dist/index.js:319:3)
      at renderVNodeToString (node_modules/nerv-server/src/index.ts:155:22)
      at Object.renderToString (node_modules/nerv-server/src/index.ts:161:10)
      at Object.it (src/pages/__tests__/ui.test.tsx:22:23)
```
**系统信息**
 - Taro 版本 [1.2.4]

**Comment by luckyadam** [comment]
看上去是没有配置好，提供一下你的工程的相关内容吧

**Comment by nanjingboy** [comment]
@neoscript99 来个完整的 demo，hzlhu.dargon@gmail.com

**Comment by neoscript99** [comment]
@nanjingboy 这个jest测试环境有点麻烦，需要点时间，我整理看看

**Comment by neoscript99** [comment]
- 这是nerv-server的代码，是不是不支持mobx、redux这种，需要注入props的框架的server-render？@yuche
```typescript
function renderVNodeToString (vnode, parent, context, firstChild) {
  const { tagName, props, children } = vnode
  if (isVText(vnode)) {
    return encodeEntities(vnode.text)
  } else if (isVNode(vnode)) {
    let renderedString = `<${tagName}`
    let html
    if (!isNullOrUndef(props)) {
      for (const prop in props) {
        const value = props[prop]
        if (skipAttributes[prop]) {
          continue
        }
        if (prop === 'dangerouslySetInnerHTML') {
          html = value.__html
        } else if (prop === 'style') {
          renderedString += ` style="${renderStylesToString(value)}"`
        } else if (prop === 'class' || prop === 'className') {
          renderedString += ` class="${isString(value) ? value : hashToClassName(value)}"`
        } else if (prop === 'defaultValue') {
          if (!props.value) {
            renderedString += ` value="${escapeText(value)}"`
          }
        } else if (prop === 'defaultChecked') {
          if (!props.checked) {
            renderedString += ` checked="${value}"`
          }
        } else {
          if (isString(value)) {
            renderedString += ` ${prop}="${escapeText(value)}"`
          } else if (isNumber(value)) {
            renderedString += ` ${prop}="${value}"`
          } else if (value === true) {
            renderedString += ` ${prop}`
          }
        }
      }
    }
    if (isVoidElements[tagName]) {
      renderedString += `/>`
    } else {
      renderedString += `>`
      if (!isInvalid(children)) {
        if (isString(children)) {
          renderedString += children === '' ? ' ' : escapeText(children)
        } else if (isNumber(children)) {
          renderedString += children + ''
        } else if (isArray(children)) {
          for (let i = 0, len = children.length; i < len; i++) {
            const child = children[i]
            if (isString(child)) {
              renderedString += child === '' ? ' ' : escapeText(child)
            } else if (isNumber(child)) {
              renderedString += child
            } else if (!isInvalid(child)) {
              renderedString += renderVNodeToString(
                child,
                vnode,
                context,
                i === 0
              )
            }
          }
        } else {
          renderedString += renderVNodeToString(children, vnode, context, true)
        }
      } else if (html) {
        renderedString += html
      }
      if (!isVoidElements[tagName]) {
        renderedString += `</${tagName}>`
      }
    }
    return renderedString
  } else if (isWidget(vnode)) {
    const { ComponentType: type } = vnode
    const instance = new type(props, context)
    instance._disable = true
    if (isFunction(instance.getChildContext)) {
      context = assign(assign({}, context), instance.getChildContext())
    }
    instance.context = context
    if (isFunction(instance.componentWillMount)) {
      instance.componentWillMount()
    }
    const nextVnode = instance.render(props, instance.state, context)

    if (isInvalid(nextVnode)) {
      return '<!--!-->'
    }
    return renderVNodeToString(nextVnode, vnode, context, true)
  } else if (isStateLess(vnode)) {
    const nextVnode = tagName(props, context)

    if (isInvalid(nextVnode)) {
      return '<!--!-->'
    }
    return renderVNodeToString(nextVnode, vnode, context, true)
  }
}
```

**Comment by nanjingboy** [comment]
@neoscript99 知道了，稍后我提一个 PR

**Comment by nanjingboy** [comment]
@neoscript99 https://github.com/NervJS/taro/pull/1852

**Comment by neoscript99** [comment]
demo工程已创建，可重现问题

https://github.com/neoscript99/taro-jest-starter/tree/master/taro-jest-babel-demo

**Comment by luckyadam** [comment]
@neoscript99 Tom 兄已提交 PR，可以下个版本试试

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/2aaf6d7e030fe95e3339aec13e873a68db427f54
