### ISSUE TITLE
未运行npm install的情况下build报错 RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by marskid** [NervJS/taro#1874]
**问题描述**
没有安装node_modules直接build导致报错
```
RangeError: Maximum call stack size exceeded
    at Object.normalize (path.js:284:32)
    at Object.join (path.js:488:18)
    at Object.exports.recursiveFindNodeModules (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\src\util\index.js:541:28)
    at Object.exports.recursiveFindNodeModules (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\src\util\index.js:545:18)
    at Object.exports.recursiveFindNodeModules (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\src\util\index.js:545:18)
```
**复现步骤**
```
taro convert
cd .\taroConvert\
yarn run build:weapp
```
导致出错

**期望行为**
期望提示信息更明确，提醒用户执行npm install

**报错信息**
```
yarn run build:weapp
yarn run v1.12.3
$ taro build --type weapp
👽 Taro v1.2.4

开始编译项目 taroConvert
path.js:284
  normalize: function normalize(path) {
                               ^

RangeError: Maximum call stack size exceeded
    at Object.normalize (path.js:284:32)
    at Object.join (path.js:488:18)
    at Object.exports.recursiveFindNodeModules (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\src\util\index.js:541:28)
    at Object.exports.recursiveFindNodeModules (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\src\util\index.js:545:18)
    at Object.exports.recursiveFindNodeModules (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\src\util\index.js:545:18)
    at Object.exports.recursiveFindNodeModules (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\src\util\index.js:545:18)
    at Object.exports.recursiveFindNodeModules (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\src\util\index.js:545:18)
    at Object.exports.recursiveFindNodeModules (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\src\util\index.js:545:18)
    at Object.exports.recursiveFindNodeModules (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\src\util\index.js:545:18)
    at Object.exports.recursiveFindNodeModules (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\src\util\index.js:545:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**系统信息**
👽 Taro v1.2.4

  Taro CLI 1.2.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**补充信息**
查找判断node_modules目录的代码有问题，没有判断目录不存在的情况

**Comment by crystal1990** [comment]
我也遇到了这样的问题，提示不明确，都不知道问题在哪里

**Comment by 1Crazy** [comment]
我也遇到了，突然发现，没有node_modules,哈哈哈哈哈哈，低级错误。。。。。。。。。。
