### ISSUE TITLE
taro升级到 1.2.5 启动出现错误

### ISSUE THREAD

**Issue by tomgao365** [NervJS/taro#1932]
**问题描述**
cli 和 项目的 taro 相关依赖，从 1.2.4 升级到 1.2.5，运行 `yarn dev:weapp` ，出现错误。

**复现步骤**
运行 `yarn dev:weapp` 

**期望行为**
运行正常

**报错信息**

```bash
开始编译项目 taro
生成  工具配置  dist/project.config.json
编译  入口文件  src/app.js
拷贝  NPM文件   dist/npm/promise-polyfill/lib/index.js
拷贝  NPM文件   dist/npm/regenerator-runtime/runtime.js
拷贝  NPM文件   dist/npm/@tarojs/async-await/index.js
拷贝  NPM文件   dist/npm/@tarojs/taro-weapp/dist/index.js
拷贝  NPM文件   dist/npm/@tarojs/taro-weapp/index.js
拷贝  NPM文件   dist/npm/@tarojs/redux/dist/index.js
拷贝  NPM文件   dist/npm/@tarojs/redux/index.js
TypeError: Cannot read property 'length' of undefined
    at NodePath.updateSiblingKeys (D:\Server\nodejs\nvm\v10.15.0\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\modification.js:186:29)
    at NodePath._remove (D:\Server\nodejs\nvm\v10.15.0\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\removal.js:56:10)
    at NodePath.remove (D:\Server\nodejs\nvm\v10.15.0\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\removal.js:30:8)
    at exports.hooks (D:\Server\nodejs\nvm\v10.15.0\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\lib\removal-hooks.js:8:12)
    at NodePath._callRemovalHooks (D:\Server\nodejs\nvm\v10.15.0\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\removal.js:49:9)
    at NodePath.remove (D:\Server\nodejs\nvm\v10.15.0\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\removal.js:24:12)
    at CallExpression (D:\Server\nodejs\nvm\v10.15.0\node_modules\@tarojs\cli\src\weapp.js:489:19)
    at NodePath._call (D:\Server\nodejs\nvm\v10.15.0\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (D:\Server\nodejs\nvm\v10.15.0\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (D:\Server\nodejs\nvm\v10.15.0\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:105:12)
编译  所有页面
(node:4616) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pages' of undefined
    at buildPages (D:\Server\nodejs\nvm\v10.15.0\node_modules\@tarojs\cli\src\weapp.js:1166:27)
    at Object.build (D:\Server\nodejs\nvm\v10.15.0\node_modules\@tarojs\cli\src\weapp.js:2181:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
(node:4616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 6.13s.

```

**系统信息**

 - 操作系统: [Windows 10]
 - Taro 版本 [e.g. v.1.2.5]
 - Node.js 版本 [v.10.15.0]
 - 报错平台 [weapp]

**补充信息**
`src/pages` 为项目页码代码的目录

**Comment by JaxXu** [comment]
同遇这个问题

**Comment by luckyadam** [comment]
已修复，请升级到 1.2.6 试试

**Comment by tomgao365** [comment]
@luckyadam OK 了

**Comment by gametheworld** [comment]
> @luckyadam好了
是所有的都升级到1.2.6 吗？

"@tarojs/async-await": "1.2.5",
    "@tarojs/components": "1.2.5",
    "@tarojs/redux": "1.2.5",
    "@tarojs/redux-h5": "1.2.5",
    "@tarojs/router": "1.2.5",
    "@tarojs/taro": "1.2.5",
    "@tarojs/taro-alipay": "1.2.5",
    "@tarojs/taro-h5": "1.2.5",
    "@tarojs/taro-swan": "1.2.5",
    "@tarojs/taro-tt": "1.2.5",
    "@tarojs/taro-weapp": "1.2.5",

**Comment by gametheworld** [comment]
npm install 
![image](https://user-images.githubusercontent.com/6021628/51157641-bc61fc80-18bb-11e9-9acb-31cdb51ada29.png)
再 npm install 报错一堆。。。。

**Comment by gametheworld** [comment]
![image](https://user-images.githubusercontent.com/6021628/51157768-63df2f00-18bc-11e9-8e09-bacabc4ae6ed.png)
这个是啥问题啊。。。
