### ISSUE TITLE
初始化的时候直接报错

### ISSUE THREAD

**Issue by seedDeno** [NervJS/taro#196]
我npm install -g @tarojs/cli，然后就直接报错， 
Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/bin/taro:4:44)
，然后也没有个论坛，或者群啥的去交流下

**Comment by zacksleo** [comment]
#111

**Comment by wangyupeng1-iri** [comment]
@seedDeno 估计是你node版本过低的原因，让node版本大于等于
![image](https://user-images.githubusercontent.com/3263356/41859217-4887d9fc-78ce-11e8-93e9-a85affe9878c.png)
