### ISSUE TITLE
安装flex 失败

### ISSUE THREAD

**Issue by BranceLee** [NervJS/taro#1977]
package.json:
```js
  "dependencies": {
    "@tarojs/async-await": "^1.2.4",
    "@tarojs/components": "1.2.4",
    "@tarojs/router": "1.2.4",
    "@tarojs/taro": "1.2.4",
    "@tarojs/taro-alipay": "1.2.4",
    "@tarojs/taro-h5": "1.2.4",
    "@tarojs/taro-swan": "1.2.4",
    "@tarojs/taro-tt": "1.2.4",
    "@tarojs/taro-weapp": "1.2.4",
    "nerv-devtools": "^1.3.9",
    "nervjs": "^1.3.9",
    "react": "^16.7.0",
    "taro-ui": "^2.0.0-beta.1"
  },
```
###  为了使用Taro-ui 里面的Flex 布局：在Index .scss 中 
@import "~taro-ui/dist/components/flex/index.scss";
@import "~taro-ui/dist/components/flex/item/index.scss";
运行后报错

缺少npm包taro-ui/dist/components/flex/index.scss，开始安装...
缺少npm包taro-ui/dist/components/flex/index.scss，开始安装...
缺少npm包taro-ui/dist/components/flex/index.scss，开始安装..
(node:86616) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at write (console.js:165:9)
    at Console.log (console.js:197:3)
    at resolveNpmPkgMainPath (/usr/local/lib/node_modules/@tarojs/cli/src/util/resolve_npm_files.js:53:15)
    at resolveNpmPkgMainPath (/usr/local/lib/node_modules/@tarojs/cli/src/util/resolve_npm_files.js:59:14)
    at resolveNpmPkgMainPath (/usr/local/lib/node_modules/@tarojs/cli/src/util/resolve_npm_files.js:59:14)
    at resolveNpmPkgMainPath (/usr/local/lib/node_modules/@tarojs/cli/src/util/resolve_npm_files.js:59:14)
    at resolveNpmPkgMainPath (/usr/local/lib/node_modules/@tarojs/cli/src/util/resolve_npm_files.js:59:14)
    at resolveNpmPkgMainPath (/usr/local/lib/node_modules/@tarojs/cli/src/util/resolve_npm_files.js:59:14)
    at resolveNpmPkgMainPath (/usr/local/lib/node_modules/@tarojs/cli/src/util/resolve_npm_files.js:59:14)
    at resolveNpmPkgMainPath (/usr/local/lib/node_modules/@tarojs/cli/src/util/resolve_npm_files.js:59:14)
(node:86616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:86616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled willterminate the Node.js process with a non-zero exit code.

**Comment by luckyadam** [comment]
taro 版本多少

**Comment by BranceLee** [comment]
嗯，您好，目前版本号 是1.2.4 版的

**Comment by xiaomiwujiecao** [comment]
now in the new version, we should import new css file :

```
@import "~taro-ui/dist/style/components/flex.scss";

```

**Comment by xiaomiwujiecao** [comment]
现在在新版本中，我们应该导入新的css文件：
```
@import "~taro-ui/dist/style/components/flex.scss";
```
