### ISSUE TITLE
微信小程序 @tarojs/taro-weapp/dist/index.js 编译报错

### ISSUE THREAD

**Issue by kooyooha** [NervJS/taro#2074]
**问题描述**
原h5项目，切换至微信小程序编译报错

**复现步骤**

执行命令 taro build --type weapp
报错片段如下：

拷贝  文件      dist/statics/img/assist/invite.png
生成  依赖文件  dist/npm/@tarojs/taro-weapp/index.js
错误  编译失败  node_modules/@tarojs/taro-weapp/dist/index.js
{ TypeError: unknown: Property id of VariableDeclarator expected node to be of a type ["LVal"] but instead got "StringLiteral"
    at Object.validate (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath.replaceWith (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/replacement.js:160:8)
    at replaceAndEvaluateNode (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-plugin-transform-define/lib/index.js:117:12)
    at processNode (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-plugin-transform-define/lib/index.js:143:5)
    at PluginPass.Identifier (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-plugin-transform-define/lib/index.js:23:9)
    at newFn (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:48:17) _babel: true }
生成  依赖文件  dist/npm/prop-types/index.js
生成  依赖文件  dist/npm/classnames/index.js

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 Taro CLI 1.2.10 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.4.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.10 => 1.2.10 
      @tarojs/components: 1.2.10 => 1.2.10 
      @tarojs/plugin-babel: 1.2.10 => 1.2.10 
      @tarojs/plugin-csso: 1.2.10 => 1.2.10 
      @tarojs/plugin-less: 1.2.10 => 1.2.10 
      @tarojs/plugin-sass: 1.2.10 => 1.2.10 
      @tarojs/plugin-uglifyjs: 1.2.10 => 1.2.10 
      @tarojs/redux: 1.2.10 => 1.2.10 
      @tarojs/redux-h5: 1.2.10 => 1.2.10 
      @tarojs/router: 1.2.10 => 1.2.10 
      @tarojs/taro: 1.2.10 => 1.2.10 
      @tarojs/taro-alipay: 1.2.10 => 1.2.10 
      @tarojs/taro-h5: 1.2.10 => 1.2.10 
      @tarojs/taro-swan: 1.2.10 => 1.2.10 
      @tarojs/taro-tt: 1.2.10 => 1.2.10 
      @tarojs/taro-weapp: 1.2.10 => 1.2.10 
      @tarojs/webpack-runner: 1.2.10 => 1.2.10 
      eslint-config-taro: 1.2.10 => 1.2.10 
      eslint-plugin-taro: 1.2.10 => 1.2.10 
      nervjs: ^1.3.9 => 1.3.11 

**补充信息**
原H5项目，通过npm run build:h5能正常编译通过，切至微信小程序报如上错误，编译信息无其他任何错误。

**Comment by kooyooha** [comment]
已发现问题出现原因，原config/prod.js 文件中添加了【defineConstants: {env: '"production"'}, 】这行配置，注释掉后错误消失，取消注释重现错误。该编译报错不仅出现在/taro-weapp/dist/index.js，其他引入的class中的方法如使用Taro.getEnv()并赋值于一个变量（const env = Taro.getEnv()）后，该class也会编译报错，错误与上面一致。

module.exports = {
    env: {
        NODE_ENV: '"production"'
    },
    // defineConstants: {env: '"production"'},   该行配置注释掉后错误消失
    weapp: {},
    h5: {}
}

**Comment by 349989153** [comment]
请问现在defineConstants里的变量要怎么取到呢？

**Comment by 349989153** [comment]
直接在代码里获取是可以的，但是使用typescript的情况下，typescript会报错，强迫症很难受，怎么办？
![1550483231909](https://user-images.githubusercontent.com/10381674/52942148-5fb79d00-33a5-11e9-8d5c-2b84499c4627.jpg)

**Comment by Chen-jj** [comment]
升级到 Taro2 或 3最新版试试吧
