### ISSUE TITLE
taro cli 创建项目报错

### ISSUE THREAD

**Issue by boxcc** [NervJS/taro#2103]
**问题描述**
使用taro/cli创建项目成功, 但是安装依赖报错

**复现步骤**
1. npm install -g @tarojs/cli
2. taro init taro_demo
3. ? 请输入项目介绍！
 ? 是否需要使用 TypeScript ？ No
 ? 请选择 CSS 预处理器（Sass/Less/Stylus） Less
 ? 请选择模板 默认模板

**期望行为**
项目创建成功, 安装依赖不报错, 项目能够运行

**报错信息**
```
× 安装项目依赖失败，请自行重新安装！
warning @tarojs/webpack-runner > webpack-format-messages > kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors'
if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
warning @tarojs/webpack-runner > node-sass > request > hawk > boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
warning @tarojs/webpack-runner > node-sass > request > hawk > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning @tarojs/webpack-runner > node-sass > request > hawk > boom > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning @tarojs/webpack-runner > node-sass > request > hawk > cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
warning @tarojs/webpack-runner > node-sass > request > hawk > cryptiles > boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
warning @tarojs/webpack-runner > node-sass > request > hawk > sntp > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
error E:\work\source\taro_demo\node_modules\node-sass: Command
failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: E:\work\source\taro_demo\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe E:\work\source\taro_demo\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'E:\\work\\source\\taro_demo\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.14.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2"
in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\work\source\taro_demo\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\work\source\taro_demo\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\work\source\taro_demo\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\work\source\taro_demo\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\work\source\taro_demo\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\work\source\taro_demo\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\work\source\taro_demo\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\work\source\taro_demo\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\work\source\taro_demo\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\work\source\taro_demo\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\work\source\taro_demo\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\work\source\taro_demo\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (E:\\work\\source\\taro_demo\\node_modules\\which\\which.js:13:12)\n    at F (E:\\work\\source\\taro_demo\\node_modules\\which\\which.js:68:19)\n    at E (E:\\work\\source\\taro_demo\\node_modules\\which\\which.js:80:29)\n    at E:\\work\\source\\taro_demo\\node_modules\\which\\which.js:89:16\n
at E:\\work\\source\\taro_demo\\node_modules\\isexe\\index.js:42:5\n    at E:\\work\\source\\taro_demo\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\work\source\taro_demo\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\work\source\taro_demo\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\work\source\taro_demo\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\work\source\taro_demo\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\work\source\taro_demo\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\work\source\taro_demo\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\work\source\taro_demo\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\work\source\taro_demo\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\work\source\taro_demo\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\work\source\taro_demo\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\work\source\taro_demo\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\work\source\taro_demo\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (E:\\work\\source\\taro_demo\\node_modules\\which\\which.js:13:12)\n    at F (E:\\work\\source\\taro_demo\\node_modules\\which\\which.js:68:19)\n    at E (E:\\work\\source\\taro_demo\\node_modules\\which\\which.js:80:29)\n    at E:\\work\\source\\taro_demo\\node_modules\\which\\which.js:89:16\n    at E:\\work\\source\\taro_demo\\node_modules\\isexe\\index.js:42:5\n    at E:\\work\\source\\taro_demo\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (E:\work\source\taro_demo\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (E:\work\source\taro_demo\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at E:\work\source\taro_demo\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\work\\source\\taro_demo\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\work\source\taro_demo\node_modules\node-sass
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
yarn install v1.13.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with
this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**系统信息**
```
 Taro CLI 1.2.12 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
```

**补充信息**
大概原因出在 taro-webpack-runner的node-sass依赖上, 使用命令npm install会报
``` 
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-64_binding.node":

HTTP error 404 Not Found
```

我见github上是没有所需的 4.8.3的 win32-x64-64_binding.node 文件

另外我是选用了less 没用sass

**Comment by Garfield550** [comment]
node-sass 4.8.x 不支持 node.js 10，你可以考虑用旧的 node.js 8，详细可以看下面几个链接。

https://github.com/sass/node-sass/issues/2579
https://github.com/sass/node-sass/issues/2357
https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#404s

**Comment by wangjq4214** [comment]
前几天我node.js 10.x还ok，不知道怎么的就不行了。
用nvm降到node.js 8.x，一脸懵逼

**Comment by Pecking** [comment]
@boxcc 这个问题你解决了嘛?

**Comment by luckyadam** [comment]
close via 809cf5d9a544da805ea09695e817ecdeebb8e8ff

**Comment by boxcc** [comment]
@Pecking 暂时降了node版本, 已经有新版升级了依赖版本
