### ISSUE TITLE
taro covert 页面转换 报错

### ISSUE THREAD

**Issue by xllily** [NervJS/taro#2191]
**执行 taro covert 部分页面转换 错误**
[问题描述：转换错误的这些页面都采用相同的语法形式，相同的代码共用形式]

**复现步骤**
1. 例如, 先写一个 common.js
```js
// common.js
module.exports = {
	obj: {
        str:'string',
        n: 1,
        arr: []
	},
        onLoad: function() {console.log(this._privateProp,this.name,this.data);},
	onShow: function() {console.log('life cycle from common');},
	onReady: function() {console.log('life cycle from common');},
	onHide: function() {console.log('life cycle from common');},
	onUnload: function() {console.log('life cycle from common');},
};
```
2. 微信小程序原生创建 page 时， 引用此 common.js

```js

// es6

//比如 pages/home/home.js 

const app = getApp();

const {
	obj,
        onLoad,
	onShow,
	onReady,
	onHide,
	onUnload,
} = require('../../assets/common.js');

Page({
	_privateProp:'private prop',
	name: 'home',
	data: {
	   obj 
	},
	onLoad,
	onShow,
	onReady,
	onHide,
	onUnload
});

```

**期望行为**
期望包容这种形式的可以正常运行的微信小程序的原生代码，支持其可以成功转换成 "taro"

**报错信息**
...
错误  页面转换  pages/home/home.js
TypeError: Property body of ClassMethod expected node to be of a type ["BlockStatement"] but instead got null
    at Object.validate (C:\Users\xiaoh\AppData\Roaming\nvm\v11.2.0\node_modules\@tarojs\cli\node_modules\_babel-types@6.26.0@babel-types\lib\definitions\index.js:109:13)
    at validate (C:\Users\xiaoh\AppData\Roaming\nvm\v11.2.0\node_modules\@tarojs\cli\node_modules\_babel-types@6.26.0@babel-types\lib\index.js:505:9)
    at Object.builder (C:\Users\xiaoh\AppData\Roaming\nvm\v11.2.0\node_modules\@tarojs\cli\node_modules\_babel-types@6.26.0@babel-types\lib\index.js:466:7)
    at properties.map.prop (C:\Users\xiaoh\AppData\Roaming\nvm\v11.2.0\node_modules\@tarojs\cli\node_modules\_@tarojs_taroize@1.2.13@@tarojs\taroize\lib\src\script.js:224:30)
    at Array.map (<anonymous>)
    at parsePage (C:\Users\xiaoh\AppData\Roaming\nvm\v11.2.0\node_modules\@tarojs\cli\node_modules\_@tarojs_taroize@1.2.13@@tarojs\taroize\lib\src\script.js:121:32)
    at CallExpression (C:\Users\xiaoh\AppData\Roaming\nvm\v11.2.0\node_modules\@tarojs\cli\node_modules\_@tarojs_taroize@1.2.13@@tarojs\taroize\lib\src\script.js:43:29)
    at NodePath._call (C:\Users\xiaoh\AppData\Roaming\nvm\v11.2.0\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Users\xiaoh\AppData\Roaming\nvm\v11.2.0\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\Users\xiaoh\AppData\Roaming\nvm\v11.2.0\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\context.js:105:12)
 ...

**系统信息**
👽 Taro v1.2.13
Taro CLI 1.2.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 11.2.0
      npm: 6.4.1

**Comment by yuche** [comment]
这种方式做不到，其实你这个写法这样还是复杂了，还可以：
```js
const test = require('..')
Page({
...test, {
 ...
}
})
```

但是这样也不行，因为 taro convert 是基于语法转换的，所以你必须显示地把所有内容都写出来。

**Comment by xllily** [comment]
Thanks a lot !

Yu Che <notifications@github.com> 于2019年2月18日周一 上午9:48写道：
