### ISSUE TITLE
存在ts类型强制转换编译出错

### ISSUE THREAD

**Issue by MikyChow** [NervJS/taro#2218]
**问题描述**
引用ts类型转换时报错

**复现步骤**
[复现问题的步骤]
1. 初始化新得taro项目
2. 添加ts文件如下：
```ts
class Test {
  a() {
    let b = <any> {
      "NN": 12
    }
  }
}
```
3. 引用并实例化'Test' 对象并编译报错
**期望行为**
正常编译

**报错信息**

```错误  编译失败  src\api\api.ts
{ SyntaxError: unknown: Unexpected token (7:10)
   5 |   }
   6 | }
>  7 |         </>;
     |           ^
   8 |     }
   9 | }
  10 |
    at Parser.pp$5.raise (C:\Users\56403\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (C:\Users\56403\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:1761:8)
    at Parser.pp$9.jsxParseIdentifier (C:\Users\56403\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:7029:10)
    at Parser.pp$9.jsxParseNamespacedName (C:\Users\56403\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:7040:19)
    at Parser.pp$9.jsxParseElementName (C:\Users\56403\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:7055:19)
    at Parser.pp$9.jsxParseClosingElementAt (C:\Users\56403\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:7158:20)
    at Parser.pp$9.jsxParseElementAt (C:\Users\56403\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:7179:35)
    at Parser.pp$9.jsxParseElement (C:\Users\56403\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:7224:15)
    at Parser.parseExprAtom (C:\Users\56403\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:7236:21)
    at Parser.pp$3.parseExprSubscripts (C:\Users\56403\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:3494:19)
  pos: 79,
  loc: Position { line: 7, column: 10 },
  _babel: true,
  codeFrame: '\u001b[0m \u001b[90m  5 | \u001b[39m  }\n \u001b[90m  6 | \u001b[39m}\n\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m  7 | \u001b[39m        \u001b[33m<\u001b[39m\u001b[33m/\u001b[39m\u001b[33m>\u001b[39m\u001b[33m;\u001b[39m\n \u001b[90m    | \u001b[39m          \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m  8 | \u001b[39m    }\n \u001b[90m  9 | \u001b[39m}\n \u001b[90m 10 | \u001b[39m\u001b[0m' }
```

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [Windows 10]
 - Taro 版本 [1.2.13]
 - Node.js 版本 [8.11.3]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
强制转换时将<>解析成了jsx导致错误

**Comment by yuche** [comment]
你这个语法有错误，参考：
https://github.com/NervJS/taro/issues/1851

正确的写法是：
```typescript
class Test {
  a() {
    let b =  {
      "NN": 12
    } as any
  }
}
```

**Comment by MikyChow** [comment]
@yuche  
···
新的 .tsx 文件扩展名和 as 运算符
TypeScript 1.6 引入了新的 .tsx 文件扩展名. 这一扩展名一方面允许 TypeScript 文件中的 JSX 语法, 一方面将 as 运算符作为默认的类型转换方式 (避免 JSX 表达式和 TypeScript 前置类型转换运算符之间的歧义).
···

这里的确说了tsx中会影响歧义、但是我的文件扩展名为ts呢？

**Comment by yuche** [comment]
目前 taro 的 ts 编译会一定选择 JSX 模式进行编译。
我觉得这个违法的写法不应该进入你的代码库，如果我是你就会修改自动代码生成器禁止这样的写法。

**Comment by MikyChow** [comment]
![image](https://user-images.githubusercontent.com/5389478/53062598-4412da80-34fc-11e9-9c58-030dcfaf32dd.png)

你好，谢谢你的关注。根据以上官方文档、只有在jsx中才只允许as风格的写法，但是在ts中时相同的语义。
 由于我这边是对其他部门的接口进行第三方调用、在这中间会有很多代码自动生成ts、比如后台的dto、接口等强类型的类。

**Comment by yuche** [comment]
你好，原文并没有说只有 JSX 才能使用 as 语法，而是说 JSX 只能使用 as 语法。

相反在 TypeScript Deep Dive 推荐一直使用 as 语法：https://basarat.gitbooks.io/typescript/docs/types/type-assertion.html

![image](https://user-images.githubusercontent.com/7202516/53093241-df826a80-3551-11e9-8f2a-004cbef4974d.png)
