### ISSUE TITLE
import(require) 路径中不能有 . 符号

### ISSUE THREAD

**Issue by blooddrunk** [NervJS/taro#226]
``` javascript
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./configureStore.prod');
} else {
  module.exports = require('./configureStore.dev');
}
```

以上代码会报错

```
VM11222:1 thirdScriptError 
 sdk uncaught third Error 
 module "store/configureStore.dev.js" is not defined 
 Error: module "store/configureStore.dev.js" is not defined
    at require (http://127.0.0.1:18114/appservice/__dev__/WAService.js:19:7163)
    at http://127.0.0.1:18114/appservice/__dev__/WAService.js:19:7018
    at http://127.0.0.1:18114/appservice/store/configureStore.js:6:20
    at require (http://127.0.0.1:18114/appservice/__dev__/WAService.js:19:7304)
    at http://127.0.0.1:18114/appservice/__dev__/WAService.js:19:7018
    at http://127.0.0.1:18114/appservice/app.js:17:23
    at require (http://127.0.0.1:18114/appservice/__dev__/WAService.js:19:7304)
    at http://127.0.0.1:18114/appservice/appservice?t=1530192839550:1196:9
```

更改文件名和代码去掉 *.* 后（比如`configureStoreDev`）正常

**Comment by luckyadam** [comment]
最新的 beta 版本解决了这个问题 b68b983e8ed469d2dcc25fdccfd5893c65bcae23
