### ISSUE TITLE
压缩失败；编译错误；works_threads

### ISSUE THREAD

**Issue by glazec** [NervJS/taro#2316]
**问题描述**
1.文件压缩失败
2.编译时出现错误
3.works_threads一直显示正在下载

**复现步骤**
[复现问题的步骤]
```js
firebase.js
export default function firebaseInit(){
const admin = require('firebase-admin');

var serviceAccount = require('../../config/total-array-182700-7d14cdcbbf54.json');

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});

var db = admin.firestore();
return db
}
```

```js
ticketHelpe.js
export default function readTicket(db){
    // const admin = require('firebase-admin');
    db.collection('tickets').get()
    .then((snapshot) => {
      snapshot.forEach((doc) => {
        console.log(doc.departure);
      });
    })
    .catch((err) => {
      console.log('Error getting documents', err);
    });
}
```
安装firebase-admin

**期望行为**
修复bug

**报错信息**
压缩错误报错范例（由于报错太多四千行，剩余的在附件里）
```
错误  压缩错误  文件C:\Users\***\Documents\Program\NASF\node_modules\firebase-admin\node_modules\node-forge\lib\ed25519.js
{ SyntaxError: Unexpected token: keyword (const)
    at JS_Parse_Error.get (eval at <anonymous> (C:\Users\***\Documents\Program\NASF\node_modules\uglify-js\tools\node.js:20:1), <anonymous>:71:23)
    at formatError (internal/util/inspect.js:817:16)
    at formatRaw (internal/util/inspect.js:616:14)
    at formatValue (internal/util/inspect.js:511:10)
    at inspect (internal/util/inspect.js:191:10)
    at Object.formatWithOptions (util.js:84:12)
    at Console.(anonymous function) (console.js:191:15)
    at Console.log (console.js:202:31)
    at recursiveRequire (C:\Users\***\AppData\Roaming\nvm\v10.15.1\node_modules\@tarojs\cli\src\util\resolve_npm_files.js:210:19)
    at CallExpression (C:\Users\***\AppData\Roaming\nvm\v10.15.1\node_modules\@tarojs\cli\src\util\resolve_npm_files.js:135:21)
  message: 'Unexpected token: keyword (const)',
  filename: '0',
  line: 188,
  col: 2,
  pos: 6953 }
```
---
编译报错 剩余的在附件里
```
错误  编译失败  src\service\firebase.js
TypeError: Property properties expected type of array but got object
    at validate (C:\Users\***\AppData\Roaming\nvm\v10.15.1\node_modules\@tarojs\cli\node_modules\babel-types\lib\definitions\index.js:161:13)
    at Object.validate (C:\Users\***\AppData\Roaming\nvm\v10.15.1\node_modules\@tarojs\cli\node_modules\babel-types\lib\definitions\index.js:190:10)
    at validate (C:\Users\***\AppData\Roaming\nvm\v10.15.1\node_modules\@tarojs\cli\node_modules\babel-types\lib\index.js:505:9)
    at Object.builder (C:\Users\***\AppData\Roaming\nvm\v10.15.1\node_modules\@tarojs\cli\node_modules\babel-types\lib\index.js:466:7)
    at CallExpression (C:\Users\***\AppData\Roaming\nvm\v10.15.1\node_modules\@tarojs\cli\src\weapp.js:689:45)
    at NodePath._call (C:\Users\***\AppData\Roaming\nvm\v10.15.1\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Users\***\AppData\Roaming\nvm\v10.15.1\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\Users\***\AppData\Roaming\nvm\v10.15.1\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (C:\Users\***\AppData\Roaming\nvm\v10.15.1\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (C:\Users\***\AppData\Roaming\nvm\v10.15.1\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:108:19)
```
**系统信息**
� Taro v1.2.15

  Taro CLI 1.2.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
平台：微信小程序

**补充信息**
wors_threads 为node的特性，因该不会存在没有安装的情况。
[编译错误.txt](https://github.com/NervJS/taro/files/2921887/default.txt)
[压缩错误.txt](https://github.com/NervJS/taro/files/2921888/default.txt)

**Comment by xPixv** [comment]
mishoo/UglifyJS2/#3275
webpack-contrib/uglifyjs-webpack-plugin/#362
https://stackoverflow.com/questions/47439067/uglifyjs-throws-unexpected-token-keyword-const-with-node-modules

UglifyJS 压缩的问题，似乎是它不支持压缩 ES6，`const` 是 ES6 关键字

**Comment by WangShuXian6** [comment]
> [mishoo/UglifyJS2#3275](https://github.com/mishoo/UglifyJS2/issues/3275)
> [webpack-contrib/uglifyjs-webpack-plugin#362](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/362)
> https://stackoverflow.com/questions/47439067/uglifyjs-throws-unexpected-token-keyword-const-with-node-modules
> 
> UglifyJS 压缩的问题，似乎是它不支持压缩 ES6，`const` 是 ES6 关键字
> 
> 我的解决办法是，把控制台日志里涉及的第三方包用 babel 先编译成 ES5，然后再 build _(:з)∠)_

我的页面都是函数式的
