### ISSUE TITLE
[question] 装饰器如何修改Components下config中的属性

### ISSUE THREAD

**Issue by Lionad-Morotar** [NervJS/taro#2318]
**问题描述**

如题所述, 我应该如何通过一个装饰器去修改Component中config内部的属性?

场景举例: 我需要写一个自动扩展下栏刷新功能的装饰器,
```javascript
export default function pullDownRefresh (fn, ...params) {
  return WrappedComponent => {
    return class PullDownRefreshComponent extends WrappedComponent {

      // ! method 1 会报错, 无法编译文件
      config = Object.assign(this.config, {
        enablePullDownRefresh: true,
      })

      onPullDownRefresh () {
        // ...
      }
    }
  }
}
```

** method 1 报错 **

```
TypeError: Cannot read property 'forEach' of undefined
    at traverseObjectNode (C:\Users\18062\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:140:16)
    at ClassProperty (C:\Users\18062\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:381:21)
    at NodePath._call (C:\Users\18062\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Users\18062\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\Users\18062\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (C:\Users\18062\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitMultiple (C:\Users\18062\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:103:17)
    at TraversalContext.visit (C:\Users\18062\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:190:19)
    at Function.traverse.node (C:\Users\18062\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\index.js:114:17)
    at NodePath.visit (C:\Users\18062\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:115:19)
```

**系统信息**

```
👽 Taro v1.2.13

  Taro CLI 1.2.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.8.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by luckyadam** [comment]
config 不能动态修改，只能写死，这个最终是要编译成配置的

**Comment by Lionad-Morotar** [comment]
> config 不能动态修改，只能写死，这个最终是要编译成配置的

ok
