### ISSUE TITLE
taro转换成支付宝小程序报这个错

### ISSUE THREAD

**Issue by Three-H** [NervJS/taro#2329]
(node:1552) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'F:\taroAlipay\WxFastBus\taroConvert\domain'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at recursiveRequire (C:\Users\hwhxy\AppData\Roaming\npm\node_modules\@tarojs\cli\src\util\resolve_npm_files.js:150:24)
    at resolveNpmFilesPath (C:\Users\hwhxy\AppData\Roaming\npm\node_modules\@tarojs\cli\src\util\resolve_npm_files.js:72:5)
    at CallExpression (C:\Users\hwhxy\AppData\Roaming\npm\node_modules\@tarojs\cli\src\util\resolve_npm_files.js:114:33)    at NodePath._call (C:\Users\hwhxy\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Users\hwhxy\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\Users\hwhxy\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (C:\Users\hwhxy\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (C:\Users\hwhxy\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:108:19)
(node:1552) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1552) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
-------------------------------------------------------------------------------------------------------------------
在支付宝编译器里面报的错是
Failed to compile.
(undefined) ./npm/asap/raw.js
Module not found: Can't resolve '../../domain' in 'F:\taroAlipay\WxFastBus\taroConvert\dist\npm\asap'

**Comment by luckyadam** [comment]
附一下相关代码，报错截图完整些

**Comment by Three-H** [comment]
这是编译成支付宝小程序时自动生成的npm文件里面的js，报错就是这里面引用domain模块没有
生成的目录机构为npm>asap>asap.js，npm>asap>raw.js。昨天所发报错就是这里全部报错信息
 @luckyadam 这是自动生成报错的js文件
https://github.com/Three-H/proplem/blob/master/asap.js
https://github.com/Three-H/proplem/blob/master/raw.js
