### ISSUE TITLE
子组件执行父组件方法是报错

### ISSUE THREAD

**Issue by chm2211912096** [NervJS/taro#2341]
**问题描述**
子组件中调用父组件的方法，报错：Cannot read property 'apply' of undefined; [Component] Event Listener Error @ components/bottom_button/index#(anonymous)
TypeError: Cannot read property 'apply' of undefined

**复现步骤**
[复现问题的步骤]
1. 进入页面
2. 点击子组件的按钮
3. 报错

```js
# 子组件代码（BottomButton）

submit() {
	(this.props as any).onSubmit();
}
	
cancel() {
	(this.props as any).onCancel();
}

<View className='content'>
	<View className='fixed' animation={(this.state as any).animationData}>
		<View className='button-cover'>
			{
				(this.props as any).showCancel ? (
					<Button className='btn' onClick={this.cancel.bind(this)}>(this.props as any).cancelTitle</Button>
				) : ''
			}
			<Button className='btn' onClick={this.submit.bind(this)}>{(this.props as any).submitTitle}</Button>
		</View>
	</View>
</View>

# 父组件代码

addBuyer() {
	navigate('/pages/buyer_add/index');
}

<BottomButton
	onSubmit={this.addBuyer.bind(this)}
	submitTitle='添加购买人'
	showCancel={false}
></BottomButton>

```

**期望行为**
点击子组件按钮执行父组件方法

**报错信息**

thirdScriptError
Cannot read property 'apply' of undefined; [Component] Event Listener Error @ components/bottom_button/index#(anonymous)
TypeError: Cannot read property 'apply' of undefined
    at z.obj.(anonymous function) [as addBuyer] (http://127.0.0.1:65126/appservice/npm/@tarojs/taro-weapp/dist/index.js:3316:35)
    at z.A.u.(anonymous function).(anonymous function).u.addListener.capture (http://127.0.0.1:65126/appservice/__dev__/WAService.js:1:813679)
    at r.safeCallback (http://127.0.0.1:65126/appservice/__dev__/WAService.js:1:718248)
    at r.call (http://127.0.0.1:65126/appservice/__dev__/WAService.js:1:718141)
    at n (http://127.0.0.1:65126/appservice/__dev__/WAService.js:1:720677)
    at http://127.0.0.1:65126/appservice/__dev__/WAService.js:1:721259
    at p (http://127.0.0.1:65126/appservice/__dev__/WAService.js:1:720224)
    at Function.c.dispatchEvent (http://127.0.0.1:65126/appservice/__dev__/WAService.js:1:721156)
    at Function.c.triggerEvent (http://127.0.0.1:65126/appservice/__dev__/WAService.js:1:721359)
    at n.w.triggerEvent (http://127.0.0.1:65126/appservice/__dev__/WAService.js:1:741444)

**系统信息**
 - typescript版本 [v3.2.2]
 - 操作系统: [macOs  High Sierra 10.13.6]
 - Taro 版本 [v1.2.13]
 - Node.js 版本 [v11.4.0]
 - 报错平台 [weapp]

**补充信息**
在其他的页面中也有一模一样的代码，那个页面执行正常，只有这个页面报错

**Comment by Chen-jj** [comment]
@chm2211912096 CLI 和依赖都升级到最新版本再试试

**Comment by chm2211912096** [comment]
感谢回复🙏🙏🙏，已更新，但还是同样的问题

**Comment by chm2211912096** [comment]
> @chm2211912096 CLI 和依赖都升级到最新版本再试试

>

**Comment by chm2211912096** [comment]
@Chen-jj  感谢回复🙏🙏🙏，已更新，还是相同的错误

**Comment by jsdchenye** [comment]
请问现在问题解决了吗？

**Comment by jsdchenye** [comment]
> @Chen-jj 感谢回复🙏🙏🙏，已更新，还是相同的错误

请问这个问题解决了吗
