### ISSUE TITLE
创建新项目h5模式下本地预览报错

### ISSUE THREAD

**Issue by xjf348060793** [NervJS/taro#2346]
**问题描述**
h5 预览模式报错
**复现步骤**
[复现问题的步骤]
1. 下载脚手架
2. init项目
3. 安装依赖
4. npm run dev:h5 报错

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
index.js?36eb:1505 Uncaught Invariant Violation: Can not find proper registered route for '/index'
    at invariant (webpack-internal:///./node_modules/_@tarojs_router@1.2.15@@tarojs/router/dist/index.js:2093:15)
    at Router.computeMatch (webpack-internal:///./node_modules/_@tarojs_router@1.2.15@@tarojs/router/dist/index.js:2657:7)
    at Router.push (webpack-internal:///./node_modules/_@tarojs_router@1.2.15@@tarojs/router/dist/index.js:2665:31)
    at Router.componentWillMount (webpack-internal:///./node_modules/_@tarojs_router@1.2.15@@tarojs/router/dist/index.js:2744:12)
    at eval (webpack-internal:///./node_modules/_nervjs@1.3.12@nervjs/dist/index.js:1529:23)
    at errorCatcher (webpack-internal:///./node_modules/_nervjs@1.3.12@nervjs/dist/index.js:1482:16)
    at mountComponent (webpack-internal:///./node_modules/_nervjs@1.3.12@nervjs/dist/index.js:1528:9)
    at ComponentWrapper.init (webpack-internal:///./node_modules/_nervjs@1.3.12@nervjs/dist/index.js:1871:12)
    at createElement (webpack-internal:///./node_modules/_nervjs@1.3.12@nervjs/dist/index.js:1385:29)
    at mountVNode (webpack-internal:///./node_modules/_nervjs@1.3.12@nervjs/dist/index.js:1517:12)
**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v1.2.0-beta.6]
 - Node.js 版本 [e.g. v10.14.1]
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by jinjinjin0731** [comment]
cli 和依赖需要版本一致，你更新下你的 taro 版本
