### ISSUE TITLE
引入taro ui 的组建后，编译报错

### ISSUE THREAD

**Issue by WangxinsHub** [NervJS/taro#2349]
引入taro ui 的组建后，编译报错

错误  编译失败  node_modules/@tarojs/taro-weapp/dist/index.js
{ TypeError: unknown: Property property of MemberExpression expected node to be of a type ["Identifier"] but instead got "ObjectExpression"
    at validate (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-types/lib/definitions/core.js:412:50)
    at Object.validate (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath.replaceWith (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/replacement.js:160:8)
    at replaceAndEvaluateNode (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-plugin-transform-define/lib/index.js:117:12)
    at processNode (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-plugin-transform-define/lib/index.js:143:5)
    at PluginPass.Identifier (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-plugin-transform-define/lib/index.js:23:9)
    at newFn (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:76:18) _babel: true }

**Comment by luckyadam** [comment]
麻烦提供一个可以复现的 demo

**Comment by WangxinsHub** [comment]
import SearchInput from '@components/search/searchInput'

import Taro, { Component } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
import { connect } from '@tarojs/redux'
import { AtSteps } from 'taro-ui'

import { add, minus, asyncAdd } from './actions'
import './index.less'
@connect(({ counter }) => ({
  counter
}), {
  add,
  minus,
  asyncAdd
})
class Index extends Component {

  config = {
    navigationBarTitleText: '首页'
  }

  constructor(props) {
    super(props)
    this.state = {
      current: 0,
    }
  }

  componentWillUnmount() {
  }

  componentDidShow() {
  }

  componentDidHide() {
  }


  render() {
    return (
      <View className='indexPage'>
        <AtSteps
          items={[
            { 'title': '步骤一', 'desc': '这里是额外的信息，最多两行' },
            { 'title': '步骤二', 'desc': '这里是额外的信息，最多两行' },
            { 'title': '步骤三', 'desc': '这里是额外的信息，最多两行' }
          ]}
          current={this.state.current}
        />
      </View>
    )
  }
}

export default Index

**Comment by WangxinsHub** [comment]
就是一个很普通的页面，引入taro ui 任意一个组件都会出现编译失败，无从下手

**Comment by WangxinsHub** [comment]
想了解一下 此类编译失败可能的原因是什么？

**Comment by WangxinsHub** [comment]
开发工具中是好的，只是在编译时出现此问题，是可以忽略继续开发的吗？
![image](https://user-images.githubusercontent.com/26586426/53792963-e654a880-3f67-11e9-8732-5aaf25d95049.png)
