### ISSUE TITLE
v1.2.15无法初始化项目，其他命令全都报错。

### ISSUE THREAD

**Issue by jasonwong1991** [NervJS/taro#2353]
**问题描述**
刚刚通过taro update self更新到了最新版本tarov1.2.15，结果执行build方法无法build项目，
于是重新想要重新初始化一个项目试试看，结果报错如下：

👽 Taro v1.2.15

error: taro-init(1) does not exist, try --help

👽 Taro v1.2.15

error: taro-info(1) does not exist, try --help

👽 Taro v1.2.15

error: taro-build(1) does not exist, try --help

因为之前使用npm下载的所以卸载重装发现如下报错：
```bash
➜  tantu git:(feature/3.2/applets) ✗ sudo npm install -g @tarojs/cli
npm WARN deprecated babel-plugin-remove-dead-code@1.3.2: use babel-plugin-minify-dead-code-elimination and babel-plugin-minify-guarded-expressions
/Users/Jason/.nvm/versions/node/v8.11.1/bin/taro -> /Users/Jason/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/bin/taro

> fsevents@1.2.7 install /Users/Jason/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.7 and node@8.11.1 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/Users/Jason/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/node_modules/fsevents/lib'
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/Jason/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/node_modules/fsevents/build'
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/Jason/.nvm/versions/node/v8.11.1/bin/node" "/Users/Jason/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/Jason/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/Jason/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64" "--napi_version=1" "--node_abi_napi=napi"
gyp ERR! cwd /Users/Jason/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/node_modules/fsevents
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/Jason/.nvm/versions/node/v8.11.1/bin/node /Users/Jason/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/Jason/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node --module_name=fse --module_path=/Users/Jason/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64 --napi_version=1 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/Jason/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/Users/Jason/.nvm/versions/node/v8.11.1/bin/node" "/Users/Jason/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/Jason/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/node_modules/fsevents
node-pre-gyp ERR! node -v v8.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/Users/Jason/.nvm/versions/node/v8.11.1/bin/node /Users/Jason/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/Jason/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node --module_name=fse --module_path=/Users/Jason/.nvm/versions/node/v8.11.1/lib/node_modules/@tarojs/cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64 --napi_version=1 --node_abi_napi=napi' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/@tarojs/cli/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ @tarojs/cli@1.2.15
updated 1 package in 41.058s
```
taro虽然安装成功，但依然报错，我马上就改用yarn重新安装，得出一样的结果。。

**复现步骤**
执行任何命令均报错
```bash
taro [command] [--option]
```

**期望行为**
希望功能正常使用

**报错信息**
![image](https://user-images.githubusercontent.com/8357581/53799583-a5fc2700-3f75-11e9-8b1b-3e8ee2e15430.png)

**系统信息**
由于taro info 不可用，因此手动打。

 - 操作系统: [macOS High Sierra 10.13.6 (17G65)]
 - Taro 版本 [v1.2.15]
 - Node.js 版本 [v8.11.1]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
Duplicate of #699
