### ISSUE TITLE
自定义组件无法继承 AtComponent 组件。

### ISSUE THREAD

**Issue by liuweiGL** [NervJS/taro#2369]
**问题描述**
在自定义组件继承了 `Taro-UI` 中的 `AtComponent` 组件，在 `weapp` 模式下编译正常，但是微信开发工具报错。

**复现步骤**

``` bash
1. git clone git@github.com:liuweiGL/taro-issue-reproduce.git
2. npm install
3. npm start
4. 使用微信开发工具打开项目
5. 查看控制台 

```

**期望行为**
微信开发工具不报错，自定义组件工作正常。

**报错信息**

``` js

VM2680:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token import 
 SyntaxError: Unexpected token import
console.error @ VM2680:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1551858416718:1630
window.onerror @ VM2680:1
VM2680:1 thirdScriptError 
 sdk uncaught third Error 
 module "npm/taro-ui/dist/weapp/index.js" is not defined 
 Error: module "npm/taro-ui/dist/weapp/index.js" is not defined
    at require (http://127.0.0.1:56439/appservice/__dev__/WAService.js:1:912710)
    at http://127.0.0.1:56439/appservice/__dev__/WAService.js:1:912460
    at http://127.0.0.1:56439/appservice/npm/taro-ui/dist/index.js:2:20
    at require (http://127.0.0.1:56439/appservice/__dev__/WAService.js:1:912851)
    at http://127.0.0.1:56439/appservice/__dev__/WAService.js:1:912460
    at http://127.0.0.1:56439/appservice/components/panel/index.js:23:15
    at require (http://127.0.0.1:56439/appservice/__dev__/WAService.js:1:912851)
    at <anonymous>:47:7
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:56439/appservice/appservice?t=1551858416718:1752:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:56439/appservice/appservice?t=1551858416718:1764:20)

```

**系统信息**

```
 Taro CLI 1.2.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - D:\nodejs\node.EXE
      npm: 6.4.1 - D:\nodejs\npm.CMD

```

**补充信息**
暂无

**Comment by yulrosy** [comment]
我也遇到这个问题了

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/49a97e9d9e57376fa82389975a253683eac1d577
