### ISSUE TITLE
npm run dev:h5 install dependencies fail

### ISSUE THREAD

**Issue by Rynxiao** [NervJS/taro#239]
I've tried redux version, when i run the command `npm run dev:h5` on my iterm, I got this error as follow:

```cmd
565 verbose stack @tarojs/async-await: No matching version found for @tarojs/async-await@^0.0.63
565 verbose stack     at pickManifest (/Users/yhhu/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/pacote/node_modules/npm-pick-manifest/index.js:65:11)
565 verbose stack     at fetchPackument.then.packument (/Users/yhhu/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:52:18)
565 verbose stack     at tryCatcher (/Users/yhhu/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
565 verbose stack     at Promise._settlePromiseFromHandler (/Users/yhhu/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
565 verbose stack     at Promise._settlePromise (/Users/yhhu/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
565 verbose stack     at Promise._settlePromise0 (/Users/yhhu/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
565 verbose stack     at Promise._settlePromises (/Users/yhhu/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
565 verbose stack     at Async._drainQueue (/Users/yhhu/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
565 verbose stack     at Async._drainQueues (/Users/yhhu/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
565 verbose stack     at Immediate.Async.drainQueues (/Users/yhhu/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
565 verbose stack     at runCallback (timers.js:810:20)
565 verbose stack     at tryOnImmediate (timers.js:768:5)
565 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
566 verbose cwd /Users/yhhu/Documents/coding/ddate/frontend
567 verbose Darwin 17.4.0
568 verbose argv "/Users/yhhu/.nvm/versions/node/v8.11.3/bin/node" "/Users/yhhu/.nvm/versions/node/v8.11.3/bin/npm" "install"
569 verbose node v8.11.3
570 verbose npm  v5.6.0
571 error code ETARGET
572 error notarget No matching version found for @tarojs/async-await@^0.0.63
573 error notarget In most cases you or one of your dependencies are requesting
573 error notarget a package version that doesn't exist.
573 error notarget
573 error notarget It was specified as a dependency of 'frontend'
574 verbose exit [ 1, true ]
```

**Comment by yuche** [comment]
原因在于 cnpm 没有同步，现在好了
