### ISSUE TITLE
taro convert报错 Error: wx:for 的值必须使用 "{{}}"  包裹

### ISSUE THREAD

**Issue by xiaohuilam** [NervJS/taro#2394]
## 报错
Error: wx:for 的值必须使用 "{{}}"  包裹

## 截图
![image](https://user-images.githubusercontent.com/6964962/54016800-0b8f2400-41bf-11e9-9173-599e411d1361.png)

```bash
转换  组件文件  components/vant/loading/index.js
转换  组件配置  components/vant/loading/index.json
转换  组件模板  components/vant/loading/index.wxml
转换  组件样式  components/vant/loading/index.wxss
错误  组件转换  components/vant/loading/index.js
Error: wx:for 的值必须使用 "{{}}"  包裹
    at transformLoop (/usr/local/lib/node_modules/.@tarojs/cli_npminstall/node_modules/.1.2.16@@tarojs/taroize/lib/src/wxml.js:318:19)
    at jsxAttrVisitor (/usr/local/lib/node_modules/.@tarojs/cli_npminstall/node_modules/.1.2.16@@tarojs/taroize/lib/src/wxml.js:52:26)
    at NodePath._call (/usr/local/lib/node_modules/.@tarojs/cli_npminstall/node_modules/.6.26.0@babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/usr/local/lib/node_modules/.@tarojs/cli_npminstall/node_modules/.6.26.0@babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/usr/local/lib/node_modules/.@tarojs/cli_npminstall/node_modules/.6.26.0@babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/.@tarojs/cli_npminstall/node_modules/.6.26.0@babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/usr/local/lib/node_modules/.@tarojs/cli_npminstall/node_modules/.6.26.0@babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/usr/local/lib/node_modules/.@tarojs/cli_npminstall/node_modules/.6.26.0@babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/usr/local/lib/node_modules/.@tarojs/cli_npminstall/node_modules/.6.26.0@babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/usr/local/lib/node_modules/.@tarojs/cli_npminstall/node_modules/.6.26.0@babel-traverse/lib/path/context.js:115:19)
```

## 代码
[components/vant/loading/index.wxml](https://github.com/youzan/vant-weapp/blob/dev/dist/loading/index.wxml)
```html
<view
  class="van-loading custom-class"
  style="width: {{ size }}; height: {{ size }}"
>
  <view
    class="van-loading__spinner van-loading__spinner--{{ type }}"
    style="color: {{ color }};"
  >
    <view
      wx:if="{{ type === 'spinner' }}"
      wx:for="item in 12"
      wx:key="index"
      class="van-loading__dot"
    />
  </view>
</view>
```

[components/vant/loading/index.js](https://github.com/youzan/vant-weapp/blob/dev/dist/loading/index.js)
```js
import baseBehavior from '../helpers/baseBehavior'
import mergeOptionsToData from '../helpers/mergeOptionsToData'
import { $wuxBackdrop } from '../index'

const defaults = {
    text: '数据加载中',
    mask: true,
}

Component({
    behaviors: [baseBehavior],
    externalClasses: ['wux-class'],
    data: mergeOptionsToData(defaults),
    methods: {
        /**
         * 隐藏
         */
        hide() {
            this.$$setData({ in: false })
            this.$wuxBackdrop && this.$wuxBackdrop.release()
        },
        /**
         * 显示
         */
        show(opts = {}) {
            const options = this.$$mergeOptionsAndBindMethods(Object.assign({}, defaults, opts))
            this.$$setData({ in: true, ...options })
            this.$wuxBackdrop && this.$wuxBackdrop.retain()
        },
    },
    created() {
        if (this.data.mask) {
            this.$wuxBackdrop = $wuxBackdrop('#wux-backdrop', this)
        }
    },
})
```

微信其实是支持 wx:for 为 `wx:for="item in 12"` 这种格式的

**Comment by yuche** [comment]
你得给出文档来才行，否则就只能当做不支持处理
