### ISSUE TITLE
weapp 模式下无法引用 json 文件。

### ISSUE THREAD

**Issue by liuweiGL** [NervJS/taro#2405]
**问题描述**
使用 `commonjs ` 规范编写的 `js` 文件无法引用 `json` 资源。

**复现步骤**

1.  git clone git@github.com:liuweiGL/taro-issue-reproduce-json.git
2.  npm install
3. npm run dev:weapp

**期望行为**
引用 `json` 文件正常。

**报错信息**

```

生成  页面模板  dist/pages/index/index.wxml
错误  编译失败  src\lib\index.js
TypeError: Property properties expected type of array but got object
    at validate (C:\Users\liuwei\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-types\lib\definitions\index.js:161:13)
    at Object.validate (C:\Users\liuwei\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-types\lib\definitions\index.js:190:10)
    at validate (C:\Users\liuwei\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-types\lib\index.js:505:9)
    at Object.builder (C:\Users\liuwei\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-types\lib\index.js:466:7)
    at CallExpression (C:\Users\liuwei\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:689:45)
    at NodePath._call (C:\Users\liuwei\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Users\liuwei\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\Users\liuwei\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (C:\Users\liuwei\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (C:\Users\liuwei\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:108:19)
生成  页面样式  dist/pages/index/index.wxss

```

**系统信息**

 Taro CLI 1.2.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - D:\nodejs\node.EXE
      npm: 6.4.1 - D:\nodejs\npm.CMD

**补充信息**
暂无

**Comment by luckyadam** [comment]
最新版本已修复
