### ISSUE TITLE
Unexpected token: name (Taro)

### ISSUE THREAD

**Issue by nevernet** [NervJS/taro#2411]
**问题描述**
`Unexpected token: name (Taro)`

执行npm run build:weapp的时候产生。 

```js
错误  压缩错误  文件***node_modules/taro-ui/dist/weapp/index.js
{ SyntaxError: Unexpected token: name (Taro)
    at JS_Parse_Error.get (eval at <anonymous> (***node_modules/uglify-js/tools/node.js:20:1), <anonymous>:71:23)
    at formatError (internal/util/inspect.js:814:16)
    at formatRaw (internal/util/inspect.js:613:14)
    at formatValue (internal/util/inspect.js:508:10)
    at inspect (internal/util/inspect.js:191:10)
    at Object.formatWithOptions (util.js:84:12)
    at Console.(anonymous function) (console.js:188:15)
    at Console.log (console.js:199:31)
    at recursiveRequire (/usr/local/lib/node_modules/@tarojs/cli/src/util/resolve_npm_files.js:210:19)
    at CallExpression (/usr/local/lib/node_modules/@tarojs/cli/src/util/resolve_npm_files.js:135:21)
  message: 'Unexpected token: name (Taro)',
  filename: '0',
  line: 1,
  col: 7,
  pos: 7 }

```

**系统信息**
```

  Taro CLI 1.2.17 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.6.2 - /usr/local/bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/opt/node@10/bin/node
      npm: 6.4.1 - /usr/local/opt/node@10/bin/npm
    npmPackages:
      @tarojs/components: 1.2.17 => 1.2.17 
      @tarojs/plugin-babel: 1.2.17 => 1.2.17 
      @tarojs/plugin-csso: 1.2.17 => 1.2.17 
      @tarojs/plugin-sass: 1.2.17 => 1.2.17 
      @tarojs/plugin-uglifyjs: 1.2.17 => 1.2.17 
      @tarojs/router: 1.2.17 => 1.2.17 
      @tarojs/taro: 1.2.17 => 1.2.17 
      @tarojs/taro-alipay: 1.2.17 => 1.2.17 
      @tarojs/taro-h5: 1.2.17 => 1.2.17 
      @tarojs/taro-swan: 1.2.17 => 1.2.17 
      @tarojs/taro-tt: 1.2.17 => 1.2.17 
      @tarojs/taro-weapp: 1.2.17 => 1.2.17 
      @tarojs/webpack-runner: 1.2.17 => 1.2.17 
      eslint-config-taro: 1.2.17 => 1.2.17 
      eslint-plugin-taro: 1.2.17 => 1.2.17 
      nervjs: ^1.3.9 => 1.3.9 
    npmGlobalPackages:
      typescript: 2.8.3
```

taro-ui版本`2.0.0`，尝试过最新的`2.0.2`，也是同样的问题。 

*其他补充*
尝试过重新taro init test
然后安装taro-ui，再编译npm run build:weapp， 此时无错误。可以正常。

**Comment by luckyadam** [comment]
没有复现啊，可以给个 demo 么

**Comment by nevernet** [comment]
@luckyadam 我也挺头疼的， 项目比较大，代码涉及太多了。 
我想想办法

**Comment by nevernet** [comment]
@luckyadam 
找到问题产生的原因：
`export const defaultFunc = () => {};`

然后在其他地方引用`defaultFunc`，引用的页面在编译的时候会报错误：`Unexpected token: name (Taro)`
