### ISSUE TITLE
Error: module "npm/taro-ui/dist/weapp/index.js" is not defined

### ISSUE THREAD

**Issue by nevernet** [NervJS/taro#2412]
**问题描述**
```
VM54:1 thirdScriptError 
 sdk uncaught third Error 
 module "npm/taro-ui/dist/weapp/index.js" is not defined 
 Error: module "npm/taro-ui/dist/weapp/index.js" is not defined
    at require (http://127.0.0.1:53676/appservice/__dev__/WAService.js:1:1001798)
    at http://127.0.0.1:53676/appservice/__dev__/WAService.js:1:1001548
    at http://127.0.0.1:53676/appservice/npm/taro-ui/dist/index.js:2:20
    at require (http://127.0.0.1:53676/appservice/__dev__/WAService.js:1:1001939)
    at http://127.0.0.1:53676/appservice/__dev__/WAService.js:1:1001548
    at http://127.0.0.1:53676/appservice/jd-ui/jd-input/index.js:12:15
    at require (http://127.0.0.1:53676/appservice/__dev__/WAService.js:1:1001939)
    at http://127.0.0.1:53676/appservice/__dev__/WAService.js:1:1001548
    at http://127.0.0.1:53676/appservice/jd-ui/index.js:43:15
    at require (http://127.0.0.1:53676/appservice/__dev__/WAService.js:1:1001939)
```
执行 npm run dev:weapp
重新打开微信开发者工具，每次必现。 

强调一下 `npm/taro-ui/dist/weapp/index.js`文件是真实存在的。 
但是我发现编译的时候，很多组件都生成到对应的"dist/dist/..."目录，很奇怪为啥有两成`dist`目录？
```
生成  组件配置  dist/dist/pages/today/components/today/index.json
生成  组件逻辑  dist/dist/pages/today/components/today/index.js
生成  组件模板  dist/dist/pages/today/components/today/index.wxml
生成  组件样式  dist/dist/pages/today/components/today/index.wxss
```
但实际生成到的真实目录依然是`dist/pages/today/components/today/....`

已经尝试过操作： 
rm -rf node_modules dist
npm install  (或者尝试安装taro update project)

清除开发者工具缓存等等

**系统信息**
```
Taro CLI 1.2.17 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.6.2 - /usr/local/bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/opt/node@10/bin/node
      npm: 6.4.1 - /usr/local/opt/node@10/bin/npm
    npmPackages:
      @tarojs/components: 1.2.17 => 1.2.17 
      @tarojs/plugin-babel: 1.2.17 => 1.2.17 
      @tarojs/plugin-csso: 1.2.17 => 1.2.17 
      @tarojs/plugin-sass: 1.2.17 => 1.2.17 
      @tarojs/plugin-uglifyjs: 1.2.17 => 1.2.17 
      @tarojs/router: 1.2.17 => 1.2.17 
      @tarojs/taro: 1.2.17 => 1.2.17 
      @tarojs/taro-alipay: 1.2.17 => 1.2.17 
      @tarojs/taro-h5: 1.2.17 => 1.2.17 
      @tarojs/taro-swan: 1.2.17 => 1.2.17 
      @tarojs/taro-tt: 1.2.17 => 1.2.17 
      @tarojs/taro-weapp: 1.2.17 => 1.2.17 
      @tarojs/webpack-runner: 1.2.17 => 1.2.17 
      eslint-config-taro: 1.2.17 => 1.2.17 
      eslint-plugin-taro: 1.2.17 => 1.2.17 
      nervjs: ^1.3.9 => 1.3.9 
    npmGlobalPackages:
      typescript: 2.8.3
```

**补充信息**
编译过程无错误， taro ui版本是2.0.0

config/index.js修改的别名配置可能对编译有影响？ 
```
'@/apis': path.resolve(__dirname, '..', 'src/apis'),
    '@/models': path.resolve(__dirname, '..', 'src/models'),
    '@/components': path.resolve(__dirname, '..', 'src/components'),
    '@/jd-ui': path.resolve(__dirname, '..', 'src/jd-ui'),
    '@/services': path.resolve(__dirname, '..', 'src/services'),
    '@/utils': path.resolve(__dirname, '..', 'src/utils'),
    '@/assets': path.resolve(__dirname, '..', 'src/assets'),
    '@/pages': path.resolve(__dirname, '..', 'src/pages'),
```

**Comment by giantss** [comment]
这个问题有怎么解决的啊@nevernet 我也遇到了

**Comment by nevernet** [comment]
@giantss 升级到最新版本试试吧

**Comment by archywillhe** [comment]
...我也遇到了

**Comment by ckyOL** [comment]
也许是讲多个组件写到一个文件引起
