### ISSUE TITLE
关于样式编译失败，还有postcss相关疑问

### ISSUE THREAD

**Issue by Topthinking** [NervJS/taro#2521]
刚下的安装包

使用`taro init myApp`初始化项目，全部回车完成创建

之后修改`src/pages/index/index.tsx`里面的代码
```
import style from './index.scss'
```

```
<View className={style.index}>
      <Text>Hello world!</Text>
</View>
```

执行`npm run build:weapp`

```
➜  myApp git:(master) ✗ npm run build:weapp

> myApp@1.0.0 build:weapp /Users/top/tool/taro/myApp
> taro build --type weapp

👽 Taro v1.2.20

开始编译项目 myApp
生成  工具配置  dist/project.config.json
编译  入口文件  src/app.tsx
拷贝  NPM文件   dist/npm/@tarojs/taro-weapp/dist/index.js
拷贝  NPM文件   dist/npm/@tarojs/taro-weapp/index.js
生成  入口配置  dist/app.json
生成  入口文件  dist/app.js
生成  入口样式  dist/app.wxss
编译  所有页面  
编译  页面文件  src/pages/index/index
生成  替换代码  为文件 /Users/top/tool/taro/myApp/src/pages/index/index.tsx 生成 css modules
错误  页面编译  页面/Users/top/tool/taro/myApp/src/pages/index/index编译失败！
TypeError: Cannot read property 'exports' of undefined
    at ImportDeclaration (/usr/local/lib/node_modules/@tarojs/cli/src/weapp.js:447:36)
    at NodePath._call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:150:16)
```

**Comment by Topthinking** [comment]
还有，我有个疑问，postcss的解析不是异步的么，你们怎么使用同步获取结果啊
weapp.js 443行
```
const result = processStyleUseCssModule({
          css: styleCode,
          filePath: styleFilePath
 })
```

weapp.js 1495行
```
const runner = postcss(postcssPlugins)
  const result = runner.process(styleObj.css, Object.assign({}, { from: styleObj.filePath }))
  return result
```

**Comment by Topthinking** [comment]
这是官方的`postcss`例子，好奇你们怎么做同步获取解析后的样式结果
```
const autoprefixer = require('autoprefixer')
const postcss = require('postcss')
const precss = require('precss')
const fs = require('fs')

fs.readFile('src/app.css', (err, css) => {
  postcss([precss, autoprefixer])
    .process(css, { from: 'src/app.css', to: 'dest/app.css' })
    .then(result => {
      fs.writeFile('dest/app.css', result.css, () => true)
      if ( result.map ) {
        fs.writeFile('dest/app.css.map', result.map, () => true)
      }
    })
})
```

**Comment by luckyadam** [comment]
看一下文档里 CSS Modules 的[使用教程](https://nervjs.github.io/taro/docs/css-modules.html)

**Comment by Topthinking** [comment]
> 看一下文档里CSS Modules的[使用教程](https://nervjs.github.io/taro/docs/css-modules.html)
> 关于异步编程，可以了解下async await的用法

？？我觉得你在敷衍，你哪里看到processStyleUseCssModule这个函数式 promise的？

**Comment by Topthinking** [comment]
> 看一下文档里CSS Modules的[使用教程](https://nervjs.github.io/taro/docs/css-modules.html)
> 关于异步编程，可以了解下async await的用法

**Comment by ivan-GM** [comment]
遇到了同样的问题，有解决的吗
