### ISSUE TITLE
if 表达式下的循环体内自定义组件属性引用 item 值的问题

### ISSUE THREAD

**Issue by vimcaw** [NervJS/taro#2523]
**问题描述**
if 表达式下的循环体内，自定义组件属性引用 item 值进行计算会出现问题

**复现步骤**
```js
export default class Test extends Component {
  constructor(props) {
    super(props);
    this.state = {
      listForTest: [
        {
          id: 1,
          content: 'test1'
        },
        {
          id: 2,
          content: 'test2'
        },
        {
          id: 3,
          content: 'test3'
        }
      ]
    }
  }
  
  config = {
    navigationBarTitleText: '测试'
  };
  
  render() {
    const {listForTest} = this.state;
    let listView;

    if (listForTest) {
      listView = listForTest.map(item=> (
        <UserCell key={item.id} text={'注册时间：' + item.content}>{item.content}</UserCell>
      ));
    }
    
    return (
      <View className='my-subordinate'>
        {listView}
      </View>
    )
  }
}
```

**期望行为**
正确编译

**报错信息**
```
VM6009:1 thirdScriptError
item is not defined;at "pages/distribution/my-subordinate/my-subordinate" page lifeCycleMethod onLoad function
ReferenceError: item is not defined
    at MySubordinate._createData (http://127.0.0.1:58446/appservice/pages/distribution/my-subordinate/my-subordinate.js:184:39)
    at doUpdate (http://127.0.0.1:58446/appservice/npm/@tarojs/taro-weapp/dist/index.js:3769:22)
    at updateComponent (http://127.0.0.1:58446/appservice/npm/@tarojs/taro-weapp/dist/index.js:3753:5)
    at z.initComponent (http://127.0.0.1:58446/appservice/npm/@tarojs/taro-weapp/dist/index.js:3553:3)
    at z.weappComponentConf.methods.onLoad (http://127.0.0.1:58446/appservice/npm/@tarojs/taro-weapp/dist/index.js:3645:21)
    at z.<anonymous> (http://127.0.0.1:58446/appservice/__dev__/WAService.js:1:940082)
    at z.p.__callPageLifeTime__ (http://127.0.0.1:58446/appservice/__dev__/WAService.js:1:939861)
    at Ct (http://127.0.0.1:58446/appservice/__dev__/WAService.js:1:955068)
    at xt (http://127.0.0.1:58446/appservice/__dev__/WAService.js:1:956114)
    at It (http://127.0.0.1:58446/appservice/__dev__/WAService.js:1:957427)
console.error @ VM6009:1
errorReport @ WAService.js:1
thirdErrorReport @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
p.__callPageLifeTime__ @ WAService.js:1
Ct @ WAService.js:1
xt @ WAService.js:1
It @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
Nt.emit @ WAService.js:1
emit @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1553135908112:10035
n.registerCallback.t @ appservice?t=1553135908112:10035
l.forEach.t @ appservice?t=1553135908112:10035
(anonymous) @ appservice?t=1553135908112:10035
s.onmessage @ appservice?t=1553135908112:10035

VM6009:1 thirdScriptError
item is not defined;at api nextTick callback function
ReferenceError: item is not defined
    at MySubordinate._createData (http://127.0.0.1:58446/appservice/pages/distribution/my-subordinate/my-subordinate.js:184:39)
    at doUpdate (http://127.0.0.1:58446/appservice/npm/@tarojs/taro-weapp/dist/index.js:3769:22)
    at updateComponent (http://127.0.0.1:58446/appservice/npm/@tarojs/taro-weapp/dist/index.js:3753:5)
    at rerender (http://127.0.0.1:58446/appservice/npm/@tarojs/taro-weapp/dist/index.js:3859:7)
    at http://127.0.0.1:58446/appservice/__dev__/WAService.js:1:101840
    at Function.Ul (http://127.0.0.1:58446/appservice/__dev__/WAService.js:1:483837)
    at http://127.0.0.1:58446/appservice/__dev__/WAService.js:1:101840
    at http://127.0.0.1:58446/appservice/__dev__/WAService.js:1:90235
console.error @ VM6009:1
errorReport @ WAService.js:1
thirdErrorReport @ WAService.js:1
(anonymous) @ WAService.js:1
Ul @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
setTimeout (async)
setTimeout @ WAService.js:1
nextTick @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
nextTick @ index.js:1853
enqueueRender @ index.js:3849
setState @ index.js:3938
success @ my-subordinate.js:79
handleSuccess @ ajax.js:122
(anonymous) @ ajax.js:234
Promise resolved (async)
request @ ajax.js:232
ajax @ ajax.js:300
componentWillMount @ my-subordinate.js:76
componentTrigger @ index.js:3511
updateComponent @ index.js:3749
initComponent @ index.js:3553
weappComponentConf.methods.onLoad @ index.js:3645
(anonymous) @ WAService.js:1
p.__callPageLifeTime__ @ WAService.js:1
Ct @ WAService.js:1
xt @ WAService.js:1
It @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
Nt.emit @ WAService.js:1
emit @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1553135908112:10035
n.registerCallback.t @ appservice?t=1553135908112:10035
l.forEach.t @ appservice?t=1553135908112:10035
(anonymous) @ appservice?t=1553135908112:10035
s.onmessage @ appservice?t=1553135908112:10035
```

报错附近的js: 
```js
  if (listForTest) {
    $loopState__temp2 = '注册时间：' + item.content;
    loopArray0 = listForTest.map(function (item) {
      item = {
        $original: (0, _index.internal_get_original)(item)
      };
      var $loopState__temp2 = null;
      return {
        $loopState__temp2: $loopState__temp2,
        $original: item.$original
      };
    });
  }
```
编译后的 wxml: 
```html
<block>
    <view class="my-subordinate">
        <block>
            <block wx:if="{{listForTest}}">
                <user-cell wx:key="$original.id" __triggerObserer="{{ _triggerObserer }}" text="{{item.$loopState__temp2}}" wx:for="{{loopArray0}}" wx:for-item="item" wx:for-index="_anonIdx">{{item.$original.content}}</user-cell>
            </block>
        </block>
    </view>
</block>
```
编译后完整的 js:
```js
define("pages/distribution/my-subordinate/my-subordinate.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,fetch,XMLHttpRequest,WebSocket,webkit,WeixinJSCore,Reporter,print,URL,DOMParser,upload,preview,build,showDecryptedInfo,syncMessage,checkProxy,showSystemInfo,openVendor,openToolsLog,showRequestInfo,help,showDebugInfoTable,closeDebug,showDebugInfo,__global,WeixinJSBridge){ "use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

var _get = function get(object, property, receiver) { if (object === null) object = Function.prototype; var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent === null) { return undefined; } else { return get(parent, property, receiver); } } else if ("value" in desc) { return desc.value; } else { var getter = desc.get; if (getter === undefined) { return undefined; } return getter.call(receiver); } };

var _class, _temp2;

var _index = require("../../../npm/@tarojs/taro-weapp/index.js");

var _index2 = _interopRequireDefault(_index);

var _ajax = require("../../../utils/ajax.js");

var _ajax2 = _interopRequireDefault(_ajax);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

var Test = (_temp2 = _class = function (_BaseComponent) {
  _inherits(Test, _BaseComponent);

  function Test() {
    var _ref;

    var _temp, _this, _ret;

    _classCallCheck(this, Test);

    for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
      args[_key] = arguments[_key];
    }

    return _ret = (_temp = (_this = _possibleConstructorReturn(this, (_ref = Test.__proto__ || Object.getPrototypeOf(Test)).call.apply(_ref, [this].concat(args))), _this), _this.$usedState = ["loopArray0", "listForTest"], _this.config = {
      navigationBarTitleText: '测试'
    }, _this.$$refs = [], _temp), _possibleConstructorReturn(_this, _ret);
  }

  _createClass(Test, [{
    key: "_constructor",
    value: function _constructor(props) {
      _get(Test.prototype.__proto__ || Object.getPrototypeOf(Test.prototype), "_constructor", this).call(this, props);
      this.state = {
        listForTest: [{
          id: 1,
          content: 'test1'
        }, {
          id: 2,
          content: 'test2'
        }, {
          id: 3,
          content: 'test3'
        }]
      };
    }
  }, {
    key: "_createData",
    value: function _createData() {
      this.__state = arguments[0] || this.state || {};
      this.__props = arguments[1] || this.props || {};
      var __runloopRef = arguments[2];
      ;
      var loopArray0 = void 0;

      var listForTest = this.__state.listForTest;

      var listView = void 0;

      if (listForTest) {
        $loopState__temp2 = '注册时间：' + item.content;
        loopArray0 = listForTest.map(function (item) {
          item = {
            $original: (0, _index.internal_get_original)(item)
          };
          var $loopState__temp2 = null;
          return {
            $loopState__temp2: $loopState__temp2,
            $original: item.$original
          };
        });
      }

      Object.assign(this.__state, {
        loopArray0: loopArray0
      });
      return this.__state;
    }
  }]);

  return Test;
}(_index.Component), _class.properties = {}, _class.$$events = [], _temp2);
exports.default = Test;

Component(require('../../../npm/@tarojs/taro-weapp/index.js').default.createComponent(Test, true));
});
``` 

**系统信息**
👽 Taro v1.2.20

  Taro CLI 1.2.20 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.20 => 1.2.20 
      @tarojs/cli: 1.2.20 => 1.2.20 
      @tarojs/components: 1.2.20 => 1.2.20 
      @tarojs/mobx: ^1.2.20 => 1.2.20 
      @tarojs/mobx-h5: ^1.2.20 => 1.2.20 
      @tarojs/plugin-babel: 1.2.20 => 1.2.20 
      @tarojs/plugin-csso: 1.2.20 => 1.2.20 
      @tarojs/plugin-sass: 1.2.20 => 1.2.20 
      @tarojs/plugin-uglifyjs: 1.2.20 => 1.2.20 
      @tarojs/router: 1.2.20 => 1.2.20 
      @tarojs/taro: 1.2.20 => 1.2.20 
      @tarojs/taro-h5: 1.2.20 => 1.2.20 
      @tarojs/taro-weapp: 1.2.20 => 1.2.20 
      @tarojs/webpack-runner: 1.2.20 => 1.2.20 
      eslint-config-taro: 1.2.20 => 1.2.20 
      eslint-plugin-taro: 1.2.20 => 1.2.20 
      nervjs: ^1.3.5 => 1.3.5 

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by zhangy2017** [comment]
我也出现了类似的问题,但是别人的环境编译后没有这个错误代码。应该和环境有关。
