### ISSUE TITLE
taro convert报错 Error: "onclick-nav" 不是一个有效 JavaScript 变量名

### ISSUE THREAD

**Issue by xiaohuilam** [NervJS/taro#2531]
**问题描述**
Error: "onclick-nav" 不是一个有效 JavaScript 变量名

**复现步骤**
- 在个人项目中运行 `taro convert`
- 出现报错

代码
```html
<van-tree-select bind:click-nav="onClickCountry" bind:click-item="onClickSchool"/>
```

**报错信息**

```bash
Error: "onclick-nav" 不是一个有效 JavaScript 变量名
    at handleAttrKey (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/taroize/lib/src/wxml.js:620:23)
    at parseAttribute (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/taroize/lib/src/wxml.js:598:20)
    at Array.map (<anonymous>)
    at parseElement (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/taroize/lib/src/wxml.js:500:65)
    at parseNode (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/taroize/lib/src/wxml.js:467:12)
    at Array.map (<anonymous>)
    at parseElement (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/taroize/lib/src/wxml.js:500:160)
    at parseNode (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/taroize/lib/src/wxml.js:467:12)
    at Array.map (<anonymous>)
    at parseElement (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/taroize/lib/src/wxml.js:500:160)
```
![image](https://user-images.githubusercontent.com/6964962/54742954-bced7b00-4bfd-11e9-8839-2e4ee4fa8f97.png)

**Comment by yuche** [comment]
这种情况没法转换，你需要改一下源码。

**Comment by xiaohuilam** [comment]
> 这种情况没法转换，你需要改一下源码。

昂插件是第三方的，我改下本地引用的试试

**Comment by yuche** [comment]
`click-nav` 对应的函数是 `clickNav` 吗

**Comment by xiaohuilam** [comment]
> `click-nav` 对应的函数是 `clickNav` 吗

不是，是有赞vant组件库的事件

**Comment by yuche** [comment]
那这样转出来很可能用不了，`taro convert` 这个功能不支持 relations 和 Behavior

**Comment by xiaohuilam** [comment]
> 那这样转出来很可能用不了，`taro convert` 这个功能不支持 relations 和 Behavior

Oops... 那... 只能转换部分后再调整了...
