### ISSUE TITLE
taro convert报错 SyntaxError: Unexpected token (323:11)

### ISSUE THREAD

**Issue by xiaohuilam** [NervJS/taro#2532]
**问题描述**
SyntaxError: Unexpected token (323:11)

 - 当生成的变量名为保留字时，建议转换一下

**源代码**
```typescript

Component({
    externalClasses: ['wux-class'],
    data: {
        animateCss: '', // 动画样式
        animateStatus: EXITED, // 动画状态，可选值 entering、entered、exiting、exited
        isMounting: false, // 是否首次挂载
    },
    properties: {
        // 触发组件进入或离开过渡的状态
        in: {
            type: Boolean,
            value: false,
            observer(newVal) {
                if (this.data.isMounting) {
                    this.updated(newVal)
                }
            },
        },
    },
}
```

**报错信息**
```bash
错误  组件转换  components/wux/animation-group/index.js
{ SyntaxError: Unexpected token (323:11)
  321 |   render() {
  322 |     const {
> 323 |       in: in,
      |           ^
  324 |       classNames: classNames,
  325 |       duration: duration,
  326 |       type: type,
    at t (/usr/local/lib/node_modules/@tarojs/cli/node_modules/prettier/parser-babylon.js:1:326)
    at Object.parse (/usr/local/lib/node_modules/@tarojs/cli/node_modules/prettier/parser-babylon.js:1:208490)
    at Object.parse$2 [as parse] (/usr/local/lib/node_modules/@tarojs/cli/node_modules/prettier/index.js:10639:19)
    at coreFormat (/usr/local/lib/node_modules/@tarojs/cli/node_modules/prettier/index.js:13856:23)
    at format (/usr/local/lib/node_modules/@tarojs/cli/node_modules/prettier/index.js:14115:73)
    at formatWithCursor (/usr/local/lib/node_modules/@tarojs/cli/node_modules/prettier/index.js:14131:12)
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/prettier/index.js:42399:15
    at Object.format (/usr/local/lib/node_modules/@tarojs/cli/node_modules/prettier/index.js:42418:12)
    at components.forEach.componentObj (/usr/local/lib/node_modules/@tarojs/cli/src/convertor.js:612:60)
    at Set.forEach (<anonymous>)
  loc: { start: { line: 323, column: 11 } },
  codeFrame:
   '\u001b[0m \u001b[90m 321 | \u001b[39m  render() {\u001b[0m\n\u001b[0m \u001b[90m 322 | \u001b[39m    \u001b[36mconst\u001b[39m {\u001b[0m\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 323 | \u001b[39m      \u001b[36min\u001b[39m\u001b[33m:\u001b[39m \u001b[36min\u001b[39m\u001b[33m,\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m     | \u001b[39m          \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 324 | \u001b[39m      classNames\u001b[33m:\u001b[39m classNames\u001b[33m,\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 325 | \u001b[39m      duration\u001b[33m:\u001b[39m duration\u001b[33m,\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 326 | \u001b[39m      type\u001b[33m:\u001b[39m type\u001b[33m,\u001b[39m\u001b[0m' }
```
![image](https://user-images.githubusercontent.com/6964962/54743743-f4f5bd80-4bff-11e9-9acc-9ef0c8513d2e.png)

**Comment by yuche** [comment]
转换是不能曲解源码的原意的，只会提醒
