### ISSUE TITLE
taro convert报错 ReferenceError: Container is falsy

### ISSUE THREAD

**Issue by xiaohuilam** [NervJS/taro#2535]
**问题描述**
ReferenceError: Container is falsy

**复现步骤**
[复现问题的步骤]
1. 在项目中运行 `taro convert`
2. 出现报错

 
**pages/user/index.js**
```js
Page({
    app: getApp(),
    data: {
        showTip: false,
    },
    onLoad(options) {
        wx.hideTabBar();
        wx.api({
            url: '/api/user/index',
            success: (res) => {
                this.setData(res.data.data);

                wx.getUserInfo({
                    success: (e) => {
                        this.onSyncUserInfo({ detail: e });
                    },
                    fail: (e) => {
                        this.setData({
                            wx_status: false,
                        });
                    },
                });
            },
        });
    },
    fresh() {
        const fn = () => {
            getApp().once('fresh_user_index', this.onLoad);
        };
        setInterval(fn, 100);
        fn();
    }
    onReady() {
        return this.fresh();
    },
    onShow() {
        return this.fresh();
    },
    onSyncUserInfo(e) {
        if (e.detail.errMsg != "getUserInfo:ok") {
            return wx.showToast({
                icon: 'none',
                title: '您取消了资料授权，会导致他人看不到头像昵称，建议重新授权',
            });
        }

        wx.api({
            url: '/api/user/profile/update',
            method: 'POST',
            data: e.detail.userInfo,
            header: {
                'Content-Type': 'application/json',
            },
            success: (res) => {
                if (!res.data.success) {
                    return wx.showToast({ icon: 'none', title: res.data.message });
                }
                if (e.currentTarget && e.currentTarget.dataset && e.currentTarget.dataset.isButton) {
                    wx.showToast({
                        icon: 'none',
                        title: '成功同步昵称和头像',
                    });
                }

                var data = res.data;
                data.initialized = 1;
                wx.api({
                    url: '/api/user/index',
                    success: (res) => {
                        for (let i in res.data.data) {
                            data[i] = res.data.data[i];
                        }
                        this.setData(data);
                    },
                });
            },
        });
    },
});
```

**pages/user/index.wxml**
```html
<tabbar />
<form report-submit="{{true}}" bindsubmit="logFormId" id="logFormId">
    <label>
        <button form-type="submit"></button>
        <view id="container">
            <wux-navigation title="个人中心" />
            <view wx:if="{{wx_status}}">
                <import src="user_info.wxml" />
                <template is="user-info" data="{{name,avatar}}" />
            </view>
            <view id="user-info" wx:if="{{!wx_status}}">
                <view style="display: block;vertical-align: middle;text-align: center;">
                    <button data-is-button="{{true}}" open-type="getUserInfo" bindgetuserinfo="onSyncUserInfo" plain="{{true}}" style="color: #fff;width: 300rpx;border: 0;font-size: 15px;background: #28a54c;border-radius: 6rpx;">
                        获取头像昵称
                    </button>
                </view>
            </view>

            <view class="cu-list grid col-4 no-border">
                <view class="cu-item">
                    <navigator class='content' hover-class='none' url="/pages/user/question" open-type="navigate">
                        <view class='icon-questionfill text-purple'>
                            <view class="cu-tag bg-purple badge" style="opacity: 0.6" wx:if="{{questions_count>0}}">
                                <block>{{questions_count>99?'99+':questions_count}}</block>
                            </view>
                        </view>
                        <text>问题</text>
                    </navigator>
                </view>
                <view class="cu-item">
                    <navigator class='content' hover-class='none' url="/pages/user/answer" open-type="navigate">
                        <view class='icon-communityfill text-orange'>
                            <view class="cu-tag bg-orange badge" style="opacity: 0.6" wx:if="{{answers_count>0}}">
                                <block>{{answers_count>99?'99+':answers_count}}</block>
                            </view>
                        </view>
                        <text>回答</text>
                    </navigator>
                </view>
                <view class="cu-item">
                    <navigator class='content' hover-class='none' url="/pages/user/comment" open-type="navigate">
                        <view class='icon-commentfill text-yellow'>
                            <view class="cu-tag bg-yellow badge" style="opacity: 0.6" wx:if="{{comments_count>0}}">
                                <block>{{comments_count>99?'99+':comments_count}}</block>
                            </view>
                        </view>
                        <text>评论</text>
                    </navigator>
                </view>
                <view class="cu-item">
                    <navigator class='content' hover-class='none' url="/pages/user/star" open-type="navigate">
                        <view class='icon-friendfill text-green'>
                            <view class="cu-tag bg-green badge" style="opacity: 0.6" wx:if="{{users_count>0}}">
                                <block>{{users_count>99?'99+':users_count}}</block>
                            </view>
                        </view>
                        <text>关注的人</text>
                    </navigator>
                </view>
                <view class="cu-item">
                    <navigator class='content' hover-class='none' url="/pages/user/star_answer" open-type="navigate">
                        <view class='icon-likefill text-mauve'>
                            <view class="cu-tag bg-mauve badge" style="opacity: 0.6" wx:if="{{star_answers_count>0}}">
                                <block>{{star_answers_count>99?'99+':star_answers_count}}</block>
                            </view>
                        </view>
                        <text>收藏回答</text>
                    </navigator>
                </view>
                <view class="cu-item">
                    <navigator class='content' hover-class='none' url="/pages/user/star_question" open-type="navigate">
                        <view class='icon-favorfill text-pink'>
                            <view class="cu-tag bg-pink badge" style="opacity: 0.6" wx:if="{{star_questions_count>0}}">
                                <block>{{star_questions_count>99?'99+':star_questions_count}}</block>
                            </view>
                        </view>
                        <text>收藏问题</text>
                    </navigator>
                </view>
                <view class="cu-item">
                    <navigator class='content' hover-class='none' url="/pages/user/tag" open-type="navigate">
                        <view class='icon-tagfill text-cyan'>
                            <view class="cu-tag bg-cyan badge" style="opacity: 0.6" wx:if="{{tags_count>0}}">
                                <block>{{tags_count>99?'99+':tags_count}}</block>
                            </view>
                        </view>
                        <text>关注标签</text>
                    </navigator>
                </view>
                <view class="cu-item">
                    <navigator class='content' hover-class='none' url="/pages/user/stargazers" open-type="navigate">
                        <view class='icon-group_fill text-blue'>
                            <view class="cu-tag bg-blue badge" style="opacity: 0.6" wx:if="{{stargazers_count>0}}">
                                <block>{{stargazers_count>99?'99+':stargazers_count}}</block>
                            </view>
                        </view>
                        <text>我的粉丝</text>
                    </navigator>
                </view>
            </view>
            <view class="cu-list menu sm-border">
                <view class="cu-item arrow">
                    <navigator class='content' hover-class='none' url="{{(!verifying&&!verified)?'/pages/user/verification':''}}" open-type="navigate">
                        <text class='icon-selection text-black'></text>
                        <text class='text-grey' wx:if="{{!verifying&&!verified}}">申请认证</text>
                        <text class='text-grey' wx:if="{{verified}}">已认证</text>
                        <text class='text-grey' wx:if="{{verifying}}">认证审核中</text>
                    </navigator>
                </view>
                <view class="cu-item arrow">
                    <button class='cu-btn content' hover-class='none' open-type="contact">
                        <text class='icon-service text-black'></text>
                        <text class='text-grey'>联系客服</text>
                    </button>
                </view>
                <view class="cu-item arrow">
                    <button class='cu-btn content' hover-class='none' open-type="feedback">
                        <text class='icon-new text-black'></text>
                        <text class='text-grey'>提交反馈</text>
                    </button>
                </view>
                <view class="cu-item arrow">
                    <button class='cu-btn content' hover-class='none' open-type="openSetting">
                        <text class='icon-settings text-black'></text>
                        <text class='text-grey'>权限设置</text>
                    </button>
                </view>
            </view>
            <navigator class="copyright" url="/pages/common/about">
                <view>Brings you with ❤️ by xiaohuilam.</view>
                <view>http://www.example.com</view>
            </navigator>
        </view>
    </label>
</form>
```

**报错信息**
```bash
转换  页面文件  pages/user/index.js
转换  页面配置  pages/user/index.json
转换  页面模板  pages/user/index.wxml
转换  页面样式  pages/user/index.wxss
错误  页面转换  pages/user/index.js
ReferenceError: Container is falsy
    at NodePath._replaceWith (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/replacement.js:170:11)
    at NodePath._remove (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/removal.js:58:10)
    at NodePath.remove (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/removal.js:30:8)
    at Object.parseModule (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/taroize/lib/src/template.js:147:13)
    at enter (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/taroize/lib/src/wxml.js:179:45)
    at NodePath._call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:103:17)
```
![image](https://user-images.githubusercontent.com/6964962/54744578-4ef78280-4c02-11e9-9225-fcaa882dfe67.png)

**系统信息**

👽 Taro v1.2.20

  Taro CLI 1.2.20 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.5.1 - /usr/local/bin/zsh
    Binaries:
      Node: 10.7.0 - /usr/local/bin/node
      npm: 6.3.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.0.3

**额外信息**
经过排除好像跟 template 有关系。我把 template 引用改为直接复制代码，就好了。

**Comment by yuche** [comment]
应该和 import 有关系，一半 import 会写在根节点

**Comment by xiaohuilam** [comment]
> 应该和 import 有关系，一半 import 会写在根节点

我试试看啊

**Comment by xiaohuilam** [comment]
> 应该和 import 有关系，一半 import 会写在根节点

果然是这问题
