### ISSUE TITLE
 npm run dev:weapp 报错

### ISSUE THREAD

**Issue by yangyiyuan** [NervJS/taro#255]
ReferenceError: Unknown plugin "transform-class-properties" specified in "base" at 0, attempted to resolve relative to "/Users/yangyiyuan/projects/ifire_ws"
    at /Users/yangyiyuan/projects/ifire_ws/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/yangyiyuan/projects/ifire_ws/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/yangyiyuan/projects/ifire_ws/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/yangyiyuan/projects/ifire_ws/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/yangyiyuan/projects/ifire_ws/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/yangyiyuan/projects/ifire_ws/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/yangyiyuan/projects/ifire_ws/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at babel (/Users/yangyiyuan/projects/ifire_ws/node_modules/@tarojs/plugin-babel/index.js:6:17)
    at Object.callPlugin (/Users/yangyiyuan/.config/yarn/global/node_modules/@tarojs/cli/src/util/npm.js:109:10)
编译  所有页面  
(node:47099) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pages' of undefined
    at buildPages (/Users/yangyiyuan/.config/yarn/global/node_modules/@tarojs/cli/src/weapp.js:674:27)
    at Object.build (/Users/yangyiyuan/.config/yarn/global/node_modules/@tarojs/cli/src/weapp.js:1167:9)
    at <anonymous>
(node:47099) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:47099) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by yangyiyuan** [comment]
执行了
taro update self
taro update project
后报错：
编译  页面文件  src/pages/index/index
{ SyntaxError: unknown: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead. (22:0)

  20 |   }
  21 | }))
> 22 | export default class Index extends Component {
     | ^
  23 |   config = {
  24 |     navigationBarTitleText: '首页'
  25 |   }
    at _class.raise (/Users/yangyiyuan/projects/ifire_ws/node_modules/@babel/parser/lib/index.js:3893:15)
    at _class.parseDecorators (/Users/yangyiyuan/projects/ifire_ws/node_modules/@babel/parser/lib/index.js:7274:14)
    at _class.parseStatement (/Users/yangyiyuan/projects/ifire_ws/node_modules/@babel/parser/lib/index.js:7112:12)
    at _class.parseBlockOrModuleBlockBody (/Users/yangyiyuan/projects/ifire_ws/node_modules/@babel/parser/lib/index.js:7666:23)
    at _class.parseBlockBody (/Users/yangyiyuan/projects/ifire_ws/node_modules/@babel/parser/lib/index.js:7653:10)
    at _class.parseTopLevel (/Users/yangyiyuan/projects/ifire_ws/node_modules/@babel/parser/lib/index.js:7080:10)
    at _class.parse (/Users/yangyiyuan/projects/ifire_ws/node_modules/@babel/parser/lib/index.js:8466:17)
    at parse (/Users/yangyiyuan/projects/ifire_ws/node_modules/@babel/parser/lib/index.js:10360:38)
    at parser (/Users/yangyiyuan/projects/ifire_ws/node_modules/@babel/core/lib/transformation/normalize-file.js:137:34)
    at normalizeFile (/Users/yangyiyuan/projects/ifire_ws/node_modules/@babel/core/lib/transformation/normalize-file.js:109:11)
  pos: 406,
  loc: Position { line: 22, column: 0 },
  code: 'BABEL_PARSE_ERROR' }

监听文件修改中...

**Comment by luckyadam** [comment]
@yangyiyuan 这个报错是因为 TC39 规范修改了，TS 里不能有 `@desc export default class` 这样的写法
你可以改写成
```javascript
@desc
class T extends Component {}

export default T
```
最新版本的模板已经改啦
