### ISSUE TITLE
编译项目 报错  告诉需要升级webpack4 怎么解决？

### ISSUE THREAD

**Issue by shirmin912** [NervJS/taro#257]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
PS D:\supplier-system-multistation> npm run dev:h5

> supplier-system-multistation@1.0.0 dev:h5 D:\supplier-system-multistation
> npm run build:h5 -- --watch


> supplier-system-multistation@1.0.0 build:h5 D:\supplier-system-multistation
> taro build --type h5 "--watch"

👽 Taro v0.0.62

开始编译项目 supplier-system-multistation

监听文件修改中...

- Starting development server, please wait🤡~> Listening at http://192.168.2.119:8080/
> Listening at http://localhost:8080/

(node:14296) UnhandledPromiseRejectionWarning: Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:14296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
× Compile failed!

./.temp/app.tsx
Module build failed: Error: You may be using an old version of webpack; please check you're using at least version 4


```
编辑项目提示升级webpack4版本  0.062版本

**Comment by zacksleo** [comment]
#237 same issue

**Comment by mindfocus** [comment]
猜测是因为taro-components 没有对typescript做适配[https://github.com/NervJS/taro/blob/master/packages/taro-components/webpack.prod.config.js](url)

更换回js应该是正常的吧

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/490e7cb36ca9b3ad9f80c4475d6c023e87b6561a

装最新的版本 0.0.68 应该就能解决了
