### ISSUE TITLE
自定义组件使用 @tarojs/redux 的 connect 后，this 指向了 connect 函数，无法访问到 mapDispathToProps 的函数

### ISSUE THREAD

**Issue by Dithub2016** [NervJS/taro#262]
**问题描述**
自定义组件使用 @tarojs/redux 的 connect 后，this 指向了 connect 函数

**复现步骤**
```js
import Taro, { Component } from '@tarojs/taro'
import { View,  Image } from '@tarojs/components'
import {connect} from '@tarojs/redux'

@connect(
  () => ({}),
  dispatch => ({
  })
)
export default class AddressWithOrder extends Component {

  componentWillMount () { }

  componentDidMount = () => {
    console.log(this)
    // this.props.getAddressList();
  }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='address-order'>
      </View>
    )
  }
}



```

**期望行为**
connect 函数的装饰行为应该是透明的

**报错信息**

![image](https://user-images.githubusercontent.com/23295172/42261082-775f63ea-7f99-11e8-9c9b-d9a07cf41255.png)

**系统信息**

 - 操作系统: win7 64bit
 - Taro 版本  v.0.0.65
 - Node.js 版本 v8.11.2

**补充说明**
无论是组件还是页面，有没使用 constructor，表现在小程序上都是一样的，不是说好的都得继承吗，没写也没有报错
在 `https://nervjs.github.io/taro/component.html` 文档里读出来的意思是和 `react` 一样是必须的才对吧 
```js
constructor(...rest) {
    super(...rest)
  }
```

**Comment by Dithub2016** [comment]
#247

**Comment by luckyadam** [comment]
Hello ，因为 `connect` 方法事实上是返回了一个组件的子类
https://github.com/NervJS/taro/blob/master/packages/taro-redux/src/connect/connect.js#L35
所以 `this` 会指向 `Connect `

**Comment by Dithub2016** [comment]
好吧，其实主要问题是这个，我绑定的方法，访问不到 props 的两个函数
```js
@connect(
  () => ({}),
  dispatch => ({
    asyncDeleteAddress: id => dispatch(asyncDeleteAddress(id)),
    asyncSetDefaultAddress: id => dispatch(asyncSetDefaultAddress(id)),
  })
)
export default class AddressWithOrder extends Component {
  onDeleteAddress = (e) => {
    e.stopPropagation();
    this.props.asyncDeleteAddress(this.props.id);
  }
  onSetDefaultAddress = (e) => {
    e.stopPropagation();
    this.props.asyncSetDefaultAddress(this.props.id);
  }

  render () {
    return (
      <View className='address-order'>
        <View className="address-item___edit">
          <View className="set-default" onClick={this.onSetDefaultAddress}>设为默认</View>
          <View className="delete" onClick={this.onDeleteAddress}>删除</View>
        </View>
      </View>
    )
  }
}
```
```bash
thirdScriptError
_this.props.asyncSetDefaultAddress is not a function;at pages/tools/addressList/index page AddressListItem__onSetDefaultAddress function
TypeError: _this.props.asyncSetDefaultAddress is not a function
    at Connect.AddressListItem._this.__event_AddressListItem__onSetDefaultAddress (http://127.0.0.1:42289/appservice/components/public/AddressListItem/AddressListItem.js:84:19)
    at e.obj.(anonymous function) (http://127.0.0.1:42289/appservice/npm/@tarojs/taro-weapp/dist/index.js:2667:38)
    at e.<anonymous> (http://127.0.0.1:42289/appservice/__dev__/WAService.js:1:28557)
    at e.i (http://127.0.0.1:42289/appservice/__dev__/WAService.js:1:18778)
    at oe (http://127.0.0.1:42289/appservice/__dev__/WAService.js:1:13049)
    at Function.<anonymous> (http://127.0.0.1:42289/appservice/__dev__/WAService.js:1:14722)
    at http://127.0.0.1:42289/appservice/__dev__/WAService.js:1:20277
    at http://127.0.0.1:42289/appservice/__dev__/WAService.js:9:25106
    at e.(anonymous function) (http://127.0.0.1:42289/appservice/__dev__/WAService.js:6:11169)
    at a (http://127.0.0.1:42289/appservice/appservice?t=1530758731524:1451:9472)
```

**Comment by Dithub2016** [comment]
@luckyadam 在 0.0.67 版本
自定义组件的 componentDidMount 没有执行，只有 componentWillMount 执行了
```js
import Taro, { Component } from '@tarojs/taro'
import {connect} from '@tarojs/redux'
import { View, Image } from '@tarojs/components'
import './AddressListItem.scss'

export default class AddressListItem extends Component {
  componentDidMount () { console.log(this)}
  render () {
    return (
      <View className={'address-item'}>

      </View>
    )
  }
}
```

**Comment by luckyadam** [comment]
76a397c

**Comment by Dithub2016** [comment]
感谢
