### ISSUE TITLE
微信原生小程序转换taro报错

### ISSUE THREAD

**Issue by zhangyt93** [NervJS/taro#2636]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**
转换过程出现两个报错：

## 报错 1：

```txt
错误  页面转换  pages/site/index.js
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.extname (path.js:830:5)
    at analyzeImportUrl (C:\Users\ZYT\AppData\Roaming\nvm\v10.15.3\node_modules\@tarojs\cli\src\convertor.js:47:29)
    at CallExpression (C:\Users\ZYT\AppData\Roaming\nvm\v10.15.3\node_modules\@tarojs\cli\src\convertor.js:221:19)
    at NodePath._call (C:\Users\ZYT\AppData\Roaming\nvm\v10.15.3\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Users\ZYT\AppData\Roaming\nvm\v10.15.3\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\Users\ZYT\AppData\Roaming\nvm\v10.15.3\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (C:\Users\ZYT\AppData\Roaming\nvm\v10.15.3\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitMultiple (C:\Users\ZYT\AppData\Roaming\nvm\v10.15.3\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:103:17)
    at TraversalContext.visit (C:\Users\ZYT\AppData\Roaming\nvm\v10.15.3\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:190:19)
```

```js
// pages/site/index.js
import http from '../../utils/http'
import P from '../../lib/wxpage'
import numeral from '../../utils/numeral.min'
import moment from '../../utils/moment.min'
import validator from '../../utils/validator'
import toast from '../../components/toast/index'

const app = getApp()

P('site', {
  onLoad() {
    app.getLocation(s => {
      this.setData({
        locationSite: s,
        locationSiteName: s.name
      })
    })

    let sites = app.globalData.sites
    let locationSite = app.globalData.locationSite
    let locationSiteName = locationSite ? locationSite.name : '定位中...'

    this.setData({
      sites,
      locationSite,
      locationSiteName
    })
  },
  handleClickSite(e) {
    var item = e.currentTarget.dataset.item
    if (item) {
      this.$emit('index:change:site', item)
    }
    this.$back()
  }
})
```

```xml
<!--pages/site/index.wxml-->
<scroll-view>
  <view class="panel">]
    <view class="panel-header">当前定位站点</view>
    <view
      class="panel-content"
      data-item="{{locationSite}}"
      catchtap="handleClickSite"
    >
      {{locationSiteName}}
    </view>
  </view>

  <view class="panel">
    <view class="panel-header">已开通站点</view>
    <view class="panel-content">
      <view
        wx:for="{{sites}}"
        wx:key="id"
        data-item="{{item}}"
        catchtap="handleClickSite"
      >
        {{item.name}}
      </view>
    </view>
  </view>
</scroll-view>
```

## 报错 2：

```txt
错误  页面转换  pages/destination/index.js
{ SyntaxError: Unexpected token, expected : (1:19)
    at Parser.pp$5.raise (C:\Users\ZYT\AppData\Roaming\nvm\v10.15.3\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (C:\Users\ZYT\AppData\Roaming\nvm\v10.15.3\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:1761:8)
    at Parser.pp.expect (C:\Users\ZYT\AppData\Roaming\nvm\v10.15.3\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:1749:33)
    at Parser.pp$3.parseConditional (C:\Users\ZYT\AppData\Roaming\nvm\v10.15.3\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:3392:10)
    at Parser.pp$3.parseMaybeConditional (C:\Users\ZYT\AppData\Roaming\nvm\v10.15.3\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:3384:15)
    at Parser.pp$3.parseMaybeAssign (C:\Users\ZYT\AppData\Roaming\nvm\v10.15.3\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:3344:19)
    at Parser.pp$3.parseExpression (C:\Users\ZYT\AppData\Roaming\nvm\v10.15.3\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:3306:19)
    at Parser.pp$3.getExpression (C:\Users\ZYT\AppData\Roaming\nvm\v10.15.3\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:3281:19)
    at Object.parseExpression (C:\Users\ZYT\AppData\Roaming\nvm\v10.15.3\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:7313:17)
    at parseAttribute (C:\Users\ZYT\AppData\Roaming\nvm\v10.15.3\node_modules\@tarojs\cli\node_modules\@tarojs\taroize\lib\src\wxml.js:587:97) pos: 19, loc: Position { line: 1, column: 19 } }
```

```js
// pages/destination/index.js
import http from '../../utils/http'
import P from '../../lib/wxpage'
import numeral from '../../utils/numeral.min'
import VillageItem from '../../components/village-item/index'

const app = getApp()

P('destination', {
  _pages: [],
  _share: null,
  _id: null,
  data: {
    height: '100%',
    activeIndex: 0
  },
  comps: [VillageItem],
  onLoad(o) {
    app.getLocation()

    this.$on('destination:change:city', res => {
      this.querySurroundingCities(res)
    })

    if (!o.id) {
      let g = app.globalData
      let c = g.destinationCity ? g.destinationCity : g.site.center
      o = c
    }
    this._id = o.id
    wx.hideShareMenu()
    wx.showLoading({
      title: ''
    })
    this.querySurroundingCities(o)
  },
  onShareAppMessage() {
    return this._share
  },
  afterLoad(o) {
    this.queryDistrictVillages(0)
    this._share = {
      title: decodeURIComponent(o.name),
      path: `pages/destination/index?id=${o.id}&name=${o.name}`
    }
    wx.hideLoading()
    wx.showShareMenu()
  },
  handleClickCity(e) {
    var index = +e.currentTarget.dataset.index
    var data = this.data.pages[index]
    if (data.status === 0) {
      this.queryDistrictVillages(index)
    }
    this.setData({
      activeIndex: index
    })
  },
  handleClickVillage(e) {
    let id = e.item.id
    this.$put('VillageDetail.preload.' + id, e.item)
    this.$route('village-detail?id=' + id)
  },
  handleLoadMore(e) {
    var data = e.currentTarget.dataset
    var index = data.index
    var data = this.data.pages[index]
    var _data = this._pages[index]
    if (_data.loading || !data.hasNext) {
      return
    }
    _data.loading = true
    this.queryDistrictVillages(index, () => {
      _data.loading = false
    })
  },
  handleClickMoreCities() {
    this.$route('city?from_page=destination&id=' + this._id)
  },
  handleClickSearch() {
    this.$route('search')
  },
  querySurroundingCities(o) {
    if (this.data.city && this.data.city.id === o.id) {
      return
    }
    o.name = decodeURIComponent(o.name)
    this.setData({
      city: o
    })
    http
      .querySurroundingCities(o.id)
      .then(res => {
        var pages = []
        this._pages = []
        res.forEach(c => {
          pages.push({
            hasNext: true,
            status: 0,
            id: c.id
          })
          this._pages.push({ loading: false })
        })

        this.setData({
          cities: res,
          pages,
          activeIndex: 0
        })
        this.afterLoad(o)
      })
      .catch(err => {
        wx.hideLoading()
      })
  },
  queryDistrictVillages(index, cb) {
    var that = this
    var data = this.data.pages[index]
    http
      .queryDistrictVillages(data.id, data.next || 1)
      .then(res => {
        if (res) {
          let list = res.list.map(v => {
            v.currentPriceText = numeral(v.currentPrice)
              .divide(100)
              .format('0,0')
            return v
          })
          var villages = data.list
          if (res.start === 1) {
            villages = list
          } else {
            villages.push.apply(villages, list)
          }
          var _data = {}
          if (cb) {
            _data = cb(true, res)
          }
          data['hasNext'] = res.hasNext
          data['next'] = res.next
          data['list'] = villages
          data['status'] = 1
          var params = {}
          params[`pages[${index}]`] = data
          that.setData(Object.assign(params, _data))
        } else {
          that.setData({
            status: 1
          })
        }
      })
      .catch(err => {
        if (start === 1) {
          that.setData({
            status: 2
          })
        }
        cb && cb(false)
      })
  },
  handleOnlineChat() {
    var url = escape(app.globalData.onlineChatUrl)
    this.$route('web-view?title=在线客服&url=' + url)
  }
})
```

```xml
<!--pages/destination/index.wxml-->
<import src="/components/village-item/index.wxml" />
<import src="/components/loadmore/index.wxml" />

<view class="box online-chat" catchtap="handleOnlineChat">
  <label class="iconfont icon-online-chat online-chat-icon"></label>
  <label class="online-chat-font">
    咨询
  </label>
</view>

<view class="view-header box">
  <view class="header-toolbar box row">
    <view class="col search-input box" catchtap="handleClickSearch">
      搜索关键字/城市/别墅名
      <view class="right-search">
        <label class="iconfont icon-search"></label>
      </view>
    </view>
    <view class="col current-city">
      <view class="box" catchtap="handleClickMoreCities">
        {{city.name}}
        <label class="iconfont icon-down"></label>
      </view>
    </view>
  </view>
  <view class="header-cities row">
    <view class="col cities-left">
      周边城市：
    </view>
    <view class="col cities-right">
      <scroll-view scroll-x="true">
        <view wx:for="{{cities}}" wx:key="id" data-item="{{item}}" data-index="{{index}}" class="city-text box {{activeIndex===index?'active':''}}" catchtap="handleClickCity">{{item.name}}</view>
      </scroll-view>
    </view>
  </view>
</view>

<view class="view-content box">
  <scroll-view scroll-y enable-back-to-top wx:for="{{cities}}" wx:key="id" data-index="{{index}}" style="height:100%" hidden="{{activeIndex!==index}}" bindscrolltolower="handleLoadMore">
    <block wx:for="{{pages[index].list}}" wx:key="id">
      <template is="VillageItem" data="{{item,itemClass:index > 0 ? 'mt20' : ''}}" />
    </block>
    <template is="loadmore" data="{{loading:pages[index].hasNext}}" />
  </scroll-view>
</view>


<!-- <wxs module="m">
  module.exports = {
    getItemClass: function(i) {
      return i > 0 ? 'mt20' : ''
    }
  }
</wxs> -->
```

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
你这个转不了，注意看文档:
https://nervjs.github.io/taro/docs/taroize.html#%E4%B8%8D%E6%94%AF%E6%8C%81-relations-%E5%92%8C-behavior
