### ISSUE TITLE
在小程序中 Canvas无法使用

### ISSUE THREAD

**Issue by guirenpei** [NervJS/taro#2645]
**问题描述**
 在引入Canvas组件的时候报错. 然后应用的时候报错
```js
import { View, Button, Canvas } from '@tarojs/components'
//..createClass

render() {
  if (process.env.TARO_ENV === 'weapp') {
      CC = <Canvas style={`width: ${width}px; height: ${height}px;`} canvasId='canvas' />
    } else {
      // CC = <canvas className='canvas' width={width} height={height}></canvas>
    }
   return (
    <View>
      <Text>test</Text>
      <CC />
    </View>
  )
}

```

**期望行为**
能在小程序中成功应用Canvas

**报错信息**

TypeError: Cannot read property 'findParent' of null
    at RenderParser.handleJSXInIfStatement (/Users/xutengfeng/.nvm/versions/node/v9.7.1/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_transformer-wx@1.2.17@@tarojs/transformer-wx/lib/src/render.js:1219:55)
    at JSXElement.handleJSXElement (/Users/xutengfeng/.nvm/versions/node/v9.7.1/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_transformer-wx@1.2.17@@tarojs/transformer-wx/lib/src/render.js:272:26)
    at RenderParser.handleJSXElement (/Users/xutengfeng/.nvm/versions/node/v9.7.1/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_transformer-wx@1.2.17@@tarojs/transformer-wx/lib/src/render.js:75:17)
    at JSXElement (/Users/xutengfeng/.nvm/versions/node/v9.7.1/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_transformer-wx@1.2.17@@tarojs/transformer-wx/lib/src/render.js:270:22)
    at NodePath._call (/Users/xutengfeng/.nvm/versions/node/v9.7.1/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/xutengfeng/.nvm/versions/node/v9.7.1/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/xutengfeng/.nvm/versions/node/v9.7.1/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/xutengfeng/.nvm/versions/node/v9.7.1/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/xutengfeng/.nvm/versions/node/v9.7.1/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/xutengfeng/.nvm/versions/node/v9.7.1/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:192:19)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
 - 报错平台 [weapp]
 - System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.7.1 - ~/.nvm/versions/node/v9.7.1/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v9.7.1/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.17 => 1.2.17
      @tarojs/components: 1.2.17 => 1.2.17
      @tarojs/plugin-babel: ^1.2.17 => 1.2.17
      @tarojs/plugin-csso: 1.2.17 => 1.2.17
      @tarojs/plugin-sass: 1.2.17 => 1.2.17
      @tarojs/plugin-uglifyjs: ^1.2.20 => 1.2.20
      @tarojs/redux: 1.2.17 => 1.2.17
      @tarojs/redux-h5: 1.2.17 => 1.2.17
      @tarojs/router: 1.2.17 => 1.2.17
      @tarojs/taro: 1.2.17 => 1.2.17
      @tarojs/taro-alipay: 1.2.17 => 1.2.17
      @tarojs/taro-h5: 1.2.17 => 1.2.17
      @tarojs/taro-swan: 1.2.17 => 1.2.17
      @tarojs/taro-tt: 1.2.17 => 1.2.17
      @tarojs/taro-weapp: 1.2.17 => 1.2.17
      @tarojs/webpack-runner: 1.2.17 => 1.2.17
      eslint-config-taro: ^1.2.17 => 1.2.17
      eslint-plugin-taro: 1.2.17 => 1.2.17
      nervjs: ^1.3.9 => 1.3.12

**Comment by Garfield550** [comment]
写法不对。

```tsx
public render(): JSX.Element {
    const env = Taro.getEnv() === Taro.ENV_TYPE.WEAPP;
    let element: JSX.Element;
    if (env) {
      element = <View>假设这是你小程序里的 Canvas</View>;
    } else {
      element = <View>假设这是其他的 Canvas</View>;
    }

    return (
      <View>
        {element}
        {process.env.TARO_ENV === 'weapp' && (
          <View>这是你小程序里的另一个 Canvas</View>
        )}
      </View>
    );
  }
```

![image](https://user-images.githubusercontent.com/3471836/55389662-4a1ec100-5568-11e9-9129-07b4d3dc573a.png)

![image](https://user-images.githubusercontent.com/3471836/55389690-586cdd00-5568-11e9-85a2-17fa08ce3c36.png)

https://nervjs.github.io/taro/docs/envs.html
https://nervjs.github.io/taro/docs/env.html

**Comment by luckyadam** [comment]
```
<View>
      <Text>test</Text>
      {CC}
    </View>
 
```

改成这样
