### ISSUE TITLE
创建模板项目报错

### ISSUE THREAD

**Issue by freecodemans** [NervJS/taro#268]
![Uploading 360截图165406046671114.png…]()

**Comment by freecodemans** [comment]
taro init myApp
D:\Program Files(x86)\nodejs\node_modules\@tarojs\cli\src\util\index.js:112
exports.replaceAsync = async function (str, regex, asyncFn) {
                             ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Program Files(x86)\nodejs\node_modules\@tarojs\cli\bin\taro:4:44)

**Comment by yuche** [comment]
Node 版本太低了，升级到 node 8
