### ISSUE TITLE
微信小程序下，process.env.TARO_ENV跟自定义常量一起用就编译不通过

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#2689]
**问题描述**
微信小程序下，process.env.TARO_ENV跟自定义常量一起用就编译不通过

**复现步骤**

这个代码编译不过：
```
/**
 * 获取系统基础URL
 */
const getBaseUrl = () => {
  if (process.env.TARO_ENV === 'h5') {
    if (window.API_URL) {
      return window.API_URL;
    }
  }
  // TODO 获取第三方平台自定义的数据字段的同步接口
  // const extConfig = Taro.getExtConfigSync()
  return `${API_URL}`;
};

export default getBaseUrl;
```

注释了h5那部分判断，代码就可以编译通过：
```
/**
 * 获取系统基础URL
 */
const getBaseUrl = () => {
  // if (process.env.TARO_ENV === 'h5') {
  //   if (window.API_URL) {
  //     return window.API_URL;
  //   }
  // }
  // TODO 获取第三方平台自定义的数据字段的同步接口
  // const extConfig = Taro.getExtConfigSync()
  return `${API_URL}`;
};

export default getBaseUrl;
```

**期望行为**
不应该编译错误

**报错信息**
```
错误  编译失败  src/utils/getBaseUrl.js
{ TypeError: unknown: Property property of MemberExpression expected node to be of a type ["Identifier"] but instead got "StringLiteral"
    at validate (/Users/lzp/work/docker/www/pengpai_diy_app/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/Users/lzp/work/docker/www/pengpai_diy_app/node_modules/babel-types/lib/definitions/core.js:412:50)
    at Object.validate (/Users/lzp/work/docker/www/pengpai_diy_app/node_modules/babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (/Users/lzp/work/docker/www/pengpai_diy_app/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath.replaceWith (/Users/lzp/work/docker/www/pengpai_diy_app/node_modules/babel-traverse/lib/path/replacement.js:160:8)
    at replaceAndEvaluateNode (/Users/lzp/work/docker/www/pengpai_diy_app/node_modules/babel-plugin-transform-define/lib/index.js:117:12)
    at processNode (/Users/lzp/work/docker/www/pengpai_diy_app/node_modules/babel-plugin-transform-define/lib/index.js:143:5)
    at PluginPass.Identifier (/Users/lzp/work/docker/www/pengpai_diy_app/node_modules/babel-plugin-transform-define/lib/index.js:23:9)
    at newFn (/Users/lzp/work/docker/www/pengpai_diy_app/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/lzp/work/docker/www/pengpai_diy_app/node_modules/babel-traverse/lib/path/context.js:76:18) _babel: true }
```

**系统信息**
👽 Taro v1.2.23

  Taro CLI 1.2.23 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 2.4.2

**Comment by tourze** [comment]
常量的配置：
![image](https://user-images.githubusercontent.com/13899502/55638302-73a24b80-57f9-11e9-98e7-47ff0d9a9fdf.png)

defineConstants那里使用JSON.stringify也解决不了问题。

**Comment by tourze** [comment]
= = 应该是因为window.API_URL被替换了的原因。。。
