### ISSUE TITLE
taro convert转换后的代码，编译成其他平台代码时，报错

### ISSUE THREAD

**Issue by gu-xiaohui** [NervJS/taro#2693]
**问题描述**
taro _convert转换后的代码，编译成其他平台代码时，报错，报错内容如下：
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/25246071/55670228-7d3cb980-58b4-11e9-9ec6-c8abcd053961.png">

**复现步骤**
[复现问题的步骤]
1. taro convert 微信小程序项目
2. taro build --type weapp或者其他平台
3. 报错

`path.js:57
function normalizeString(path, allowAboveRoot, separator, isPathSeparator) {
                        ^

RangeError: Maximum call stack size exceeded
    at normalizeString (path.js:57:25)
    at Object.normalize (path.js:1132:12)
    at Object.join (path.js:1167:18)
    at Object.exports.recursiveFindNodeModules (/usr/local/lib/node_modules/@tarojs/cli/src/util/index.js:558:28)
    at Object.exports.recursiveFindNodeModules (/usr/local/lib/node_modules/@tarojs/cli/src/util/index.js:562:18)
    at Object.exports.recursiveFindNodeModules (/usr/local/lib/node_modules/@tarojs/cli/src/util/index.js:562:18)
    at Object.exports.recursiveFindNodeModules (/usr/local/lib/node_modules/@tarojs/cli/src/util/index.js:562:18)
    at Object.exports.recursiveFindNodeModules (/usr/local/lib/node_modules/@tarojs/cli/src/util/index.js:562:18)
    at Object.exports.recursiveFindNodeModules (/usr/local/lib/node_modules/@tarojs/cli/src/util/index.js:562:18)
    at Object.exports.recursiveFindNodeModules (/usr/local/lib/node_modules/@tarojs/cli/src/util/index.js:562:18)`

**系统信息**
👽 Taro v1.2.23
  Taro CLI 1.2.23 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
      npm: 6.5.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 2.6.2

**Comment by luckyadam** [comment]
有没有在 taroConvert 目录下安装依赖

**Comment by gu-xiaohui** [comment]
装了的。

**Comment by luckyadam** [comment]
没有复现啊，有相关 demo 么

**Comment by gu-xiaohui** [comment]
没事了，我把node_modules删了重新安装依赖就好了。
