### ISSUE TITLE
利用taro build --type weapp --watch 后更改项目代码编译失败

### ISSUE THREAD

**Issue by iisbigfish** [NervJS/taro#27]
症状是：我仅仅改了将示例代码由 1 变成 2。然后就报错了。
具体报错信息是：
`$ taro build --type weapp --watch
Taro v0.0.40

开始编译项目 myApp
编译  入口文件  src/app.js
拷贝  NPM文件   dist/npm/@tarojs/taro-weapp/dist/index.js
拷贝  NPM文件   dist/npm/@tarojs/taro-weapp/index.js
生成  入口配置  dist/app.json
生成  入口文件  dist/app.js
生成  入口样式  dist/app.wxss
编译  所有页面
编译  页面文件  src/pages/index/index
生成  页面JSON  dist/pages/index/index.json
生成  页面JS    dist/pages/index/index.js
生成  页面WXML  dist/pages/index/index.wxml
生成  页面WXSS  dist/pages/index/index.wxss

监听文件修改中...

修改  组件文件  src/pages/index/index.js
错误  编译失败  src\pages\index\index.js
{ SyntaxError: unknown: Unexpected token (18:11)
  16 |
  17 |   render() {
> 18 |     return <View className="index">
     |            ^
  19 |         <Text className="test">2</Text>
  20 |       </View>;
  21 |   }
    at Parser.pp$5.raise (C:\Users\Administrator\Desktop\Taro\myApp\node_modules\_babylon@6.18.0@babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (C:\Users\Administrator\Desktop\Taro\myApp\node_modules\_babylon@6.18.0@babylon\lib\index.js:1761:8)
    at Parser.pp$3.parseExprAtom (C:\Users\Administrator\Desktop\Taro\myApp\node_modules\_babylon@6.18.0@babylon\lib\index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (C:\Users\Administrator\Desktop\Taro\myApp\node_modules\_babylon@6.18.0@babylon\lib\index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (C:\Users\Administrator\Desktop\Taro\myApp\node_modules\_babylon@6.18.0@babylon\lib\index.js:3474:19)
    at Parser.pp$3.parseExprOps (C:\Users\Administrator\Desktop\Taro\myApp\node_modules\_babylon@6.18.0@babylon\lib\index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (C:\Users\Administrator\Desktop\Taro\myApp\node_modules\_babylon@6.18.0@babylon\lib\index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (C:\Users\Administrator\Desktop\Taro\myApp\node_modules\_babylon@6.18.0@babylon\lib\index.js:3344:19)
    at Parser.pp$3.parseExpression (C:\Users\Administrator\Desktop\Taro\myApp\node_modules\_babylon@6.18.0@babylon\lib\index.js:3306:19)
    at Parser.pp$1.parseReturnStatement (C:\Users\Administrator\Desktop\Taro\myApp\node_modules\_babylon@6.18.0@babylon\lib\index.js:2078:26)
  pos: 295,
  loc: Position { line: 18, column: 11 },
  _babel: true,
  codeFrame: '  16 | \n  17 |   render() {\n> 18 |     return <View className="index">\n     |            ^\n  19 |         <Text className="test">2</Text>\n  20 |       </View>;\n  21 |   }' }`

另一个问题是，内联 css 样式会直接覆盖css选择器。如
组件内容
`  render () {
    return (
      <View className='index'>
        <Text className='test' style='font-size: 24px;'>2</Text>
      </View>
    )
  }`
index,scss
`.test {
  color: red;
  font-size: 60px;
}
`
这样子color样式不生效

**Comment by yuche** [comment]
这个是 Windows 平台的特有问题，我们还在解决中。

**Comment by zhangchao828** [comment]
+1，没解决之前，window上几乎没没办法开发了

**Comment by wanrengang** [comment]
+2啊  window上几乎没没办法开发了

**Comment by luckyadam** [comment]
#16

**Comment by luckyadam** [comment]
请升级 @tarojs/cli 到 `0.0.42` 试试~

**Comment by xiaoreign** [comment]
确实,在编译路径的时候有问题
