### ISSUE TITLE
weapp slatejs 引用报错

### ISSUE THREAD

**Issue by accaolei** [NervJS/taro#2750]
**问题描述**
要在小程序中实现一个内容编辑器，使用slatejs作为依赖，引入后npm run build:weapp报错
```
(node:10015) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'tty'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at recursiveRequire (/usr/local/lib/node_modules/@tarojs/cli/src/util/resolve_npm_files.js:150:24)
    at resolveNpmFilesPath (/usr/local/lib/node_modules/@tarojs/cli/src/util/resolve_npm_files.js:72:5)
    at CallExpression (/usr/local/lib/node_modules/@tarojs/cli/src/util/resolve_npm_files.js:114:33)
    at NodePath._call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:108:19)
```
**复现步骤**
[复现问题的步骤]
1. taro init slate-test
2. npm install slate slate-react
3. pages/index/index.js 引用
4. npm run build:weapp

[或者可以直接贴源代码，能贴文字就不要截图]

```js
import Taro, { Component } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
// import './index.scss'
import { Editor } from 'slate-react';

export default class Index extends Component {
  state = {
    value: ''
  }
  config = {
    navigationBarTitleText: '首页'
  }
  
  onChange(value) {
    this.setState({
      value: value
    })
  }

  render() {
    return (
      <View className='index'>
        <Editor value={this.state.value} onChange={this.onChange} />
      </View>
    )
  }
}

```

**期望行为**
slate-react 能在tarojs中使用

**报错信息**
```
错误  组件编译  组件node_modules/slate-react/lib/slate-react.js编译失败！
{ Error: ENOENT: no such file or directory, open '/Users/cary/Code/slate-test/node_modules/slate-react/lib/memoize-one'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at buildSingleComponent (/usr/local/lib/node_modules/@tarojs/cli/src/weapp.js:1731:31)
    at buildSingleComponent (/usr/local/lib/node_modules/@tarojs/cli/src/weapp.js:1767:20)
    at Promise.all.componentPathList.map.componentObj (/usr/local/lib/node_modules/@tarojs/cli/src/weapp.js:1664:60)
    at Array.map (<anonymous>)
    at buildDepComponents (/usr/local/lib/node_modules/@tarojs/cli/src/weapp.js:1664:40)
    at buildSinglePage (/usr/local/lib/node_modules/@tarojs/cli/src/weapp.js:1390:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path:
   '/Users/cary/Code/slate-test/node_modules/slate-react/lib/memoize-one' }
错误  页面编译  页面/Users/cary/Code/slate-test/src/pages/index/index编译失败！
TypeError: Cannot read property 'wxss' of undefined
    at buildDepComponentsResult.map.item (/usr/local/lib/node_modules/@tarojs/cli/src/weapp.js:1671:23)
    at Array.map (<anonymous>)
    at getDepStyleList (/usr/local/lib/node_modules/@tarojs/cli/src/weapp.js:1670:44)
    at buildSinglePage (/usr/local/lib/node_modules/@tarojs/cli/src/weapp.js:1429:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**系统信息**
  Taro CLI 1.2.20 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.10.1 - ~/.yarn/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.20 => 1.2.20 
      @tarojs/plugin-babel: 1.2.20 => 1.2.20 
      @tarojs/plugin-csso: 1.2.20 => 1.2.20 
      @tarojs/plugin-sass: 1.2.20 => 1.2.20 
      @tarojs/plugin-uglifyjs: 1.2.20 => 1.2.20 
      @tarojs/router: 1.2.20 => 1.2.20 
      @tarojs/taro: 1.2.20 => 1.2.20 
      @tarojs/taro-alipay: 1.2.20 => 1.2.20 
      @tarojs/taro-h5: 1.2.20 => 1.2.20 
      @tarojs/taro-swan: 1.2.20 => 1.2.20 
      @tarojs/taro-tt: 1.2.20 => 1.2.20 
      @tarojs/taro-weapp: 1.2.20 => 1.2.20 
      @tarojs/webpack-runner: 1.2.20 => 1.2.20 
      eslint-config-taro: 1.2.20 => 1.2.20 
      eslint-plugin-taro: 1.2.20 => 1.2.20 
      nervjs: ^1.3.9 => 1.3.13 

**补充信息**

**Comment by luckyadam** [comment]
使用 react 组件请参考 https://github.com/NervJS/taro/issues/2731

**Comment by yuche** [comment]
小程序用不了非 Taro 标准的 web 组件
