### ISSUE TITLE
继承父类组件的命名必须为Component的问题

### ISSUE THREAD

**Issue by jammacn** [NervJS/taro#280]
**问题描述**

继承父类组件的命名必须为Component，否则运行时会报错

**复现步骤**

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里写报错
import { App as AppComponent } from './common/components'
class App extends AppComponent {

// 这里写不会报错
import { App as Component } from './common/components'
class App extends Component {
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

```
VM308:1 thirdScriptError 
 sdk uncaught third Error 
 AppClass is not a constructor 
 TypeError: AppClass is not a constructor
    at Object.createApp (http://127.0.0.1:65136/appservice/npm/@tarojs/taro-weapp/dist/index.js:3500:13)
    at http://127.0.0.1:65136/appservice/app.js:38:58
    at require (http://127.0.0.1:65136/appservice/__dev__/WAService.js:18:16253)
    at http://127.0.0.1:65136/appservice/appservice:1311:9
console.error @ VM308:1
(anonymous) @ WAService.js:4
(anonymous) @ WAService.js:4
a @ appservice:1271
window.onerror @ VM308:1

```

**系统信息**

 - 操作系统: [Windows 10]
 - Taro 版本 [v.0.0.67]
 - Node.js 版本 [e.g. v8.1.1]

**补充信息**

**Comment by luckyadam** [comment]
收到~ 这是编译时写死了 Component ，后续版本修复
