### ISSUE TITLE
压缩错误

### ISSUE THREAD

**Issue by ccqgithub** [NervJS/taro#2812]
**问题描述**

打包生成环境报压缩错误, 错误信息如下
```
错误  压缩错误  文件/Users/season/Documents/work/pusihotels/node_modules/query-string/index.js
{ SyntaxError: Unexpected token: keyword «const»
    at JS_Parse_Error.get (eval at <anonymous> (/Users/season/Documents/work/pusihotels/node_modules/uglify-js/tools/node.js:20:1), <anonymous>:71:23)
    at formatError (internal/util/inspect.js:817:16)
    at formatRaw (internal/util/inspect.js:616:14)
    at formatValue (internal/util/inspect.js:511:10)
    at inspect (internal/util/inspect.js:191:10)
    at Object.formatWithOptions (util.js:84:12)
    at Console.(anonymous function) (console.js:191:15)
    at Console.log (console.js:202:31)
    at recursiveRequire (/Users/season/.nvm/versions/node/v10.15.1/lib/node_modules/@tarojs/cli/src/util/resolve_npm_files.js:210:19)
    at resolveNpmFilesPath (/Users/season/.nvm/versions/node/v10.15.1/lib/node_modules/@tarojs/cli/src/util/resolve_npm_files.js:72:5)
  message: 'Unexpected token: keyword «const»',
  filename: '0',
  line: 3,
  col: 0,
  pos: 15 }
```

**复现步骤**
项目中用了`query-string` npm包，里面好像有es6代码没有转换位es5，压缩报错

**期望行为**
不报错，正确压缩

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 ```
Taro CLI 1.2.26 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
```

**Comment by code-artisan** [comment]
我也遇到了，官方没计划修复这个问题么？

**Comment by Darmody** [comment]
+1

**Comment by laiyaoWeb** [comment]
+1

**Comment by melote** [comment]
我也遇到了，请问有什么办法可以解决吗？

**Comment by zephyrpersonal** [comment]
`query-string`可以通过安装`query-string@5`解决

暴力方案：

在`config/prod.js`里关闭uglifyJS

```js
module.exports = {
  //...other
  plugins: {
    uglify: {
      enable: false,
      config: {
        // 配置项同 https://github.com/mishoo/UglifyJS2#minify-options
      },
    },
  }
}
```

**Comment by yuche** [comment]
这个问题一般是 node_modules 使用了 ES6 模块的缘故，这在 Taro 中是不行的

**Comment by frankgo81** [comment]
对的，需要安装query-string 5
query-strinstring 6不行的

![image](https://user-images.githubusercontent.com/33563058/64366269-77582980-d048-11e9-9f45-df04e6332314.png)

**Comment by wenxiayili** [comment]
我安装了 query-string5也不管用？？？

**Comment by LJJCherry** [comment]
> 这个问题一般是 node_modules 使用了 ES6 模块的缘故，这在 Taro 中是不行的

https://github.com/NervJS/taro/issues/871#issuecomment-445524043 支持了这个配置也不行吗
