### ISSUE TITLE
scss 书写错误导致 taro-cli 进程中断

### ISSUE THREAD

**Issue by huixisheng** [NervJS/taro#2852]
**问题描述**
scss 书写错误导致 taro-cli 进程中断

**复现步骤**
对 scss 文件，书写错误的语法

**期望行为**
 taro-cli 进程不中断

**报错信息**

```
修改  样式文件  src/pages/guide-test/index.wxss
{ Error: Expected expression.
   ╷
12 │     margin-bottom: 
   │                    ^
   ╵
  src/pages/guide-test/index.scss 12:20  root stylesheet
    at Object.BI (${Workspace}/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:5233:30)
    at Object.Ei (${Workspace}/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:5149:34)
    at nF.E8 (${Workspace}/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:5135:5)
    at Object.GZ (${Workspace}/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:463:69)
    at Object.hA (${Workspace}/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:2191:27)
    at HV (${Workspace}/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:2991:27)
    at Object.renderSync (${Workspace}/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:2980:42)
    at Promise (${Workspace}/node_modules/@tarojs/plugin-sass/index.js:34:21)
    at new Promise (<anonymous>)
    at compileSass (${Workspace}/node_modules/@tarojs/plugin-sass/index.js:5:10)
  formatted:
   'Error: Expected expression.\n   ╷\n12 │     margin-bottom: \n   │                    ^\n   ╵\n  src/pages/guide-test/index.scss 12:20  root stylesheet',
  line: 12,
  column: 20,
  file:
   '${Workspace}/src/pages/guide-test/index.scss',
  status: 1 }
```

**系统信息**
```
👽 Taro v1.2.23


  Taro CLI 1.2.23 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.2.23 => 1.2.26 
      @tarojs/cli: ^1.2.23 => 1.2.26 
      @tarojs/components: ^1.2.26 => 1.2.26 
      @tarojs/mobx: ^1.2.26 => 1.2.26 
      @tarojs/mobx-h5: ^1.2.26 => 1.2.26 
      @tarojs/mobx-rn: ^1.2.26 => 1.2.26 
      @tarojs/plugin-babel: 1.2.26 => 1.2.26 
      @tarojs/plugin-csso: 1.2.26 => 1.2.26 
      @tarojs/plugin-sass: 1.2.26 => 1.2.26 
      @tarojs/plugin-uglifyjs: 1.2.26 => 1.2.26 
      @tarojs/rn-runner: ^1.2.26 => 1.2.26 
      @tarojs/router: ^1.2.26 => 1.2.26 
      @tarojs/taro: ^1.2.26 => 1.2.26 
      @tarojs/taro-alipay: ^1.2.26 => 1.2.26 
      @tarojs/taro-h5: ^1.2.26 => 1.2.26 
      @tarojs/taro-swan: ^1.2.26 => 1.2.26 
      @tarojs/taro-tt: ^1.2.26 => 1.2.26 
      @tarojs/taro-weapp: ^1.2.26 => 1.2.26 
      @tarojs/webpack-runner: 1.2.26 => 1.2.26 
      eslint-config-taro: 1.2.26 => 1.2.26 
      eslint-plugin-taro: 1.2.26 => 1.2.26 
      nervjs: ^1.3.9 => 1.3.13 
```

**Comment by guozilin** [comment]
遇到了同样的问题，scss 书写错误，cli 进程直接退出

**Comment by Garfield550** [comment]
这个问题是 taro 换用 dart-sass 以后出现的问题，怀疑是没有 handle dart-sass 的错误输出

**Comment by Garfield550** [comment]
@luckyadam 另外在 taro-sample-weapp 里面引入 wxss 文件，dart-sass 无法处理，由于都是 dart-sass 相关的问题我就不开新 issue 了

https://github.com/NervJS/taro-sample-weapp/blob/42f2d1b09c073105c5e9f8456fec7133dc1deec2/src/pages/wxParse/wxParse.scss#L1

```
生成  依赖文件  dist/utils/util.js
{ Error: Can't find stylesheet to import.
  ╷
1 │ @import "../../components/wxParse/wxParse.wxss";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/pages/wxParse/wxParse.scss 1:9  root stylesheet
    at Object.BI (/Users/<NAME>/Downloads/taro-sample-weapp-master/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:5233:30)
    at Object.Ei (/Users/<NAME>/Downloads/taro-sample-weapp-master/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:5149:34)
    at nF.E8 (/Users/<NAME>/Downloads/taro-sample-weapp-master/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:5135:5)
    at Object.GZ (/Users/<NAME>/Downloads/taro-sample-weapp-master/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:463:69)
    at Object.hB (/Users/<NAME>/Downloads/taro-sample-weapp-master/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:2191:27)
    at HV (/Users/<NAME>/Downloads/taro-sample-weapp-master/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:2991:27)
    at Object.renderSync (/Users/<NAME>/Downloads/taro-sample-weapp-master/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:2980:42)
    at Promise (/Users/<NAME>/Downloads/taro-sample-weapp-master/node_modules/@tarojs/plugin-sass/index.js:34:21)
    at new Promise (<anonymous>)
    at compileSass (/Users/<NAME>/Downloads/taro-sample-weapp-master/node_modules/@tarojs/plugin-sass/index.js:5:10)
  formatted:
   `Error: Can't find stylesheet to import.\n  ╷\n1 │ @import "../../components/wxParse/wxParse.wxss";\n  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  ╵\n  src/pages/wxParse/wxParse.scss 1:9  root stylesheet`,
  line: 1,
  column: 9,
  file:
   '/Users/<NAME>/Downloads/taro-sample-weapp-master/src/pages/wxParse/wxParse.scss',
  status: 1 }
✨  Done in 8.12s.
~/Downloads/taro-sample-weapp-master> 
```

**Comment by YTU94** [comment]
解决办法是什么，现在用的less, 也是这样的

**Comment by YTU94** [comment]
坐等更新

**Comment by sufaith** [comment]
这个问题困扰了好多天,每次都要重新运行,相当麻烦~

**Comment by flyrui316** [comment]
遇到同样的问题
