### ISSUE TITLE
缺少npm包@tarojs/plugin-uglifyjs

### ISSUE THREAD

**Issue by caffelab** [NervJS/taro#2860]
**问题描述**
本问题手工尝试安装两个出错的插件后依然报错(包括yarn和cnpm)。
同一环境在MacOS下似乎是可以过的，但是Windows和Ubuntu下编译似乎都出现此问题。
重装并升级nodejs从8.*到11.*没有解决。
**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
此处不断报错，cnpm或者yarn add @tarojs/plugin-uglifyjs 则报“缺少npm包@tarojs/plugin-babel”
安装了@tarojs/plugin-babel则报‘缺少npm包@tarojs/plugin-uglifyjs’
babel 7.4.3 (@babel/core 7.4.3)

**报错信息**

编译  入口文件  src/app.tsx
缺少npm包@tarojs/plugin-uglifyjs，开始安装...
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning " > @typescript-eslint/parser@1.7.0" has incorrect peer dependency "eslint@^5.0.0".
拷贝  NPM文件   dist/npm/@tarojs/taro-weapp/dist/index.js
拷贝  NPM文件   dist/npm/@tarojs/taro-weapp/index.js
缺少npm包@tarojs/plugin-babel，开始安装...
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning " > @typescript-eslint/parser@1.7.0" has incorrect peer dependency "eslint@^5.0.0".
ReferenceError: Unknown plugin "transform-decorators-legacy" specified in "base" at 0, attempted to resolve relative to "D:\\anquansuo\\kaisuo\\src"
    at D:\anquansuo\kaisuo\node_modules\@tarojs\plugin-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (D:\anquansuo\kaisuo\node_modules\@tarojs\plugin-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (D:\anquansuo\kaisuo\node_modules\@tarojs\plugin-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (D:\anquansuo\kaisuo\node_modules\@tarojs\plugin-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (D:\anquansuo\kaisuo\node_modules\@tarojs\plugin-babel\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (D:\anquansuo\kaisuo\node_modules\@tarojs\plugin-babel\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (D:\anquansuo\kaisuo\node_modules\@tarojs\plugin-babel\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at babel (D:\anquansuo\kaisuo\node_modules\@tarojs\plugin-babel\index.js:8:17)
    at Object.callPlugin (C:\Users\69541\AppData\Roaming\npm\node_modules\@tarojs\cli\src\util\npm.js:122:10)
编译  所有页面
(node:13040) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pages' of undefined
    at buildPages (C:\Users\69541\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1194:27)
    at Object.build (C:\Users\69541\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:2230:9)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
(node:13040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:13040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 11.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.15.2 - C:\Users\69541\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**补充信息**
本问题也许跟环境有关，本人升级了babel至7.4.3

**Comment by Littly** [comment]
在项目目录下手动安装吧 不行就删掉`package-lock.json`和`node_modules`再来 网络问题只有电信/联通/移动客服能帮你了..
