### ISSUE TITLE
请问如何引入小程序自定义组件？

### ISSUE THREAD

**Issue by TooBug** [NervJS/taro#288]
小程序已经支持了自定义组件，taro是否支持引入已经写好的自定义组件？如果支持的话要如何引入。

我尝试在页面中使用import引入，会报错误

```
编译  组件文件  src/pages/components/wemark/wemark
{ Error: ENOENT: no such file or directory, open '/wemark/taro/src/pages/components/wemark/wemark'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at buildSingleComponent (/wemark/taro/node_modules/@tarojs/cli/src/weapp.js:879:31)
    at Promise.all.componentPathList.map.componentPath (/wemark/taro/node_modules/@tarojs/cli/src/weapp.js:854:61)
    at Array.map (<anonymous>)
    at buildDepComponents (/wemark/taro/node_modules/@tarojs/cli/src/weapp.js:854:40)
    at buildSinglePage (/wemark/taro/node_modules/@tarojs/cli/src/weapp.js:752:40)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/wemark/taro/src/pages/components/wemark/wemark' }
```

尝试使用小程序的页面配置`usingComponents`，发现taro并不会将组件代码复制到`dist`目录。

**Comment by yuche** [comment]
遗憾的是我们现在还不支持从 NPM 引入自定义组件，计划专门做一个命令打包发布到 NPM 组件。

**Comment by TooBug** [comment]
不需要从npm包，我拷文件进去也可以接受。就是微信小程序的自定义组件，是否支持在taro中直接引用呢？

**Comment by TooBug** [comment]
好的，期待……

**Comment by shenqihui** [comment]
战略性关注
