### ISSUE TITLE
小程序taro 组件好像不支持 import {Demo} from '../components'写法

### ISSUE THREAD

**Issue by joe2wang** [NervJS/taro#2883]
------------------------

**问题描述**
1、公用组件components下写了个Demo组件，代码如下：
```

import Taro, { Component } from '@tarojs/taro'
import PropTypes from "prop-types"
import { View} from '@tarojs/components'
class DemoComp extends Component {
  render() {
    const { num = 1 } = this.props;
    return (
      <View>
        这是一个测试的共用组件{num}
      </View>
    );
  }
}

DemoComp.propTypes = {
  num: PropTypes.number
};

export default DemoComp;

```
2、公用组件components下写了index.js收录所有公用组件，代码如下：
```
export Demo from './Demo'
```
3、然后就在page/index/index.js的页面中调用这个组件：
```

import Taro, { Component } from '@tarojs/taro'
import { View, Button, Text } from '@tarojs/components'
import { connect } from '@tarojs/redux'
import mapDispatchToProps from '../../actions/counter'
import {Demo } from '../components'
import './index.scss'

class Index extends Component {

  config = {
    navigationBarTitleText: '首页'
  }

  componentWillMount() {
  }

  componentWillUnmount() {}


  add() {
    this.props.onAdd({ type: '"REFUND"' })
  }

  componentDidHide() { }

  render() {
    return (
      <View className='index'>
        <Button className='add_btn' onClick={this.add}>+</Button>
        <View><Text>Hello, World</Text></View>
        <Demo num={2}/>
      </View>
    )
  }
}
function mapStateToProps({counter}){
  return counter
}
export default connect(mapStateToProps,mapDispatchToProps)(Index)

```
目录结构如下：
```
└─src
    ├─actions            
    ├─constants          
    ├─pages                
    │  ├─components       
    │  └─index             
    ├─reducers            
    ├─store               
    └─utils                
```
**报错信息**
```
修改  组件文件  src/pages/components/index.js
编译  组件文件  src/pages/components/index.js
错误  组件编译  组件src/pages/components/index.js编译失败！
{ SyntaxError: unknown: Unexpected token, expected { (1:7)
> 1 | export Demo from './Demo'
    |        ^
  2 |
    at Parser.pp$5.raise (C:\Users\0865\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (C:\Users\0865\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:1761:8)
    at Parser.pp.expect (C:\Users\0865\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:1749:33)
    at Parser.pp$1.parseExportSpecifiers (C:\Users\0865\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:2830:8)
    at Parser.pp$1.parseExport (C:\Users\0865\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:2658:28)
    at Parser.parseExport (C:\Users\0865\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:6000:20)
    at Parser.pp$1.parseStatement (C:\Users\0865\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:1884:74)
    at Parser.parseStatement (C:\Users\0865\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:5910:22)
    at Parser.pp$1.parseBlockBody (C:\Users\0865\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:2268:21)
    at Parser.pp$1.parseTopLevel (C:\Users\0865\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babylon\lib\index.js:1778:8)
  pos: 7,
  loc: Position { line: 1, column: 7 },
  _babel: true,
  codeFrame:
   '\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 1 | \u001b[39m\u001b[36mexport\u001b[39m \u001b[33mDemo\u001b[39m from \u001b[32m\'./Demo\'\u001b[39m\n \u001b[90m   | \u001b[39m       \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 2 | \u001b[39m\u001b[0m' }
```

**复现步骤**
npm dev:weapp 编译报错

**系统信息**
操作系统: [e.g. Windows 10]
Taro 版本 [e.g. v.1.2.17]
Node.js 版本 [e.g. v10.15.3]
报错平台 [weapp]

期望能解答这个问题，谢谢~

**Comment by Garfield550** [comment]
可以看看这个文件的写法

https://github.com/NervJS/taro-ui/blob/b63eb1aebb366046e3416ab806e76a6f3bddca43/src/index.js#L8-L20

**Comment by Littly** [comment]
这是个单纯的语法错误

**Comment by joe2wang** [comment]
这个是react的写法，用过的，taro就写就不行了，请实践后再回答吧，亲

**Comment by Garfield550** [comment]
@joe2wang 试试这样？

```
// index.js
import HtmlParser from './WxParser/Index';

export { HtmlParser };
```

**Comment by joe2wang** [comment]
> @joe2wang 试试这样？
> 
> ```
> // index.js
> import HtmlParser from './WxParser/Index';
> 
> export { HtmlParser };
> ```

component/index.js里是这样引入
```
import Demo from './Demo/index';
export default {Demo}
```

其实和我上面的写法是一样的，都不可以

page/index/index.js里
```
import {demo} '@components' 
```
这样写应该是可以的，可问题taro报错

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/56710353-4d1c6400-6758-11e9-8f3d-e28dca47a9a8.png)

export default 没有 {} 这种语法，
参见：
https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export

**Comment by joe2wang** [comment]
我脑子抽了
import Demo from './Demo/index';
export default {Demo}；
这个写法其实拆分开是：
const components={Demo}
export default components；

components是个对象了，Demo这个组件已经是这个对象下面的属性了，这样写是没问题的，问题是调用的写法不对

import  components  from '@components' 
只能components["Demo"]这样取Demo组件,
