### ISSUE TITLE
更新 68 版本后，h5 编译出错

### ISSUE THREAD

**Issue by Dithub2016** [NervJS/taro#289]
**问题描述**
项目是在 版本 60 的时候用 `taro init` 创建的 js 项目，68版本之前 `npm run dev:h5` 编译没报错，但也没正常运作，`build:h5` 完全正常，小程序的编译正常。
更新到 68 后，`dev:h5` 和 `build:h5` 都出错了，每个 `js` 文件都报了同一个错误最后还输出了个 `module not found`

**复现步骤**
略

**期望行为**
未知

**报错信息**
以下为 运行 `build:h5` 的结果
```js
创建  发现文件  src\pages\tools\expressDetails\index.js
TypeError: Cannot read property '0' of undefined
    at new Parser (C:\git\weapp\node_modules\babylon\lib\index.js:1577:45)
    at Object.parse (C:\git\weapp\node_modules\babylon\lib\index.js:7305:10)
    at getAst (C:\git\weapp\node_modules\babel-template\lib\index.js:29:21)
    at C:\git\weapp\node_modules\babel-template\lib\index.js:53:24
    at exit (C:\git\weapp\node_modules\@tarojs\cli\src\h5.js:330:63)
    at NodePath._call (C:\git\weapp\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\git\weapp\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\git\weapp\node_modules\babel-traverse\lib\path\context.js:117:8)
    at TraversalContext.visitQueue (C:\git\weapp\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (C:\git\weapp\node_modules\babel-traverse\lib\context.js:108:19)from
    at exports.default (C:\git\weapp\node_modules\babel-template\lib\index.js:12:11)
    at exit (C:\git\weapp\node_modules\@tarojs\cli\src\h5.js:330:24)
    at NodePath._call (C:\git\weapp\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\git\weapp\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\git\weapp\node_modules\babel-traverse\lib\path\context.js:117:8)
    at TraversalContext.visitQueue (C:\git\weapp\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (C:\git\weapp\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (C:\git\weapp\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (C:\git\weapp\node_modules\babel-traverse\lib\index.js:114:17)
    at traverse (C:\git\weapp\node_modules\babel-traverse\lib\index.js:79:12)
```
```js
./.temp/app.js
Module not found: Can't resolve './pages/login/index' in 'C:\git\weapp\.temp'
```

**系统信息**

 - 操作系统: Windows 7
 - Taro 版本  v0.0.68
- Node.js 版本 v8.11.2

**Comment by luckyadam** [comment]
@Littly

**Comment by Lin-YingYu** [comment]
同上~
 Taro v0.0.68
TypeError: Cannot read property '0' of undefined
var getPage = function getPage(pathname) {
  if (pathname in registeredPages) {
    return registeredPages[pathname];
  } else {
    return registeredPagesArr[0][1];
  }
};
// 应该注册页面这~。。。

**Comment by nooldey** [comment]
同上~
Taro v0.0.70
```
TypeError: Cannot read property '0' of undefined
...
创建  发现文件  src\pages\index\index.scss

�   Compile failed!

./.temp/app.js
Module not found: Can't resolve './pages/index/index' in 'D:\nooldey\GIT\boilerplates\miniapp\MTools\.temp'
```

---

**但是！**以上报错是出现在项目用`npx @tarojs/cli init MTools`后，运行`npx taro build --type h5 --watch`，进行编译开发时报的错。

报错信息关键字：`babylon babel-template @tarojs/cli`

而采用全局安装`@tarojs/cli`后，用常规的指令初始化一个项目，配置完全相同的，运行完全正常。

**Comment by yuche** [comment]
https://github.com/NervJS/taro/issues/332
给出的解决方案是否可行？

**Comment by nooldey** [comment]
@yuche  
重命名`src/pages/index/` 为`src/pages/home/`
或
重命名`src/pages/index/index.js` 为`src/pages/index/main.js`
并修改`app.js`中的引用路径。

目前暂未解决该问题。

不太理解#332中所说的缩短名称具体是指什么，是缩短`js`文件名还是缩短引用的路径长度？

**Comment by yuche** [comment]
https://github.com/NervJS/taro/commit/c2e2184e871e00d300e2a1c6f12cc99e32cf8ba4
修复了这个问题。下一个版本 0.0.71 就可以了。
