### ISSUE TITLE
同一目录下不同js引用同一css.module，其中一个编译失败

### ISSUE THREAD

**Issue by DougFlands** [NervJS/taro#2904]
**问题描述**
同一目录下的index.js 与 Dialog.js 同时引用index.module.scss
index.js编译成功
Dialog.js编译提示编译失败。

**复现步骤**
只贴出关键代码
index.js
```js
import styles from './index.module.scss'
import Dialog from './dialog';

  render () {
    return (
      <View className={styles.index}>
        <Dialog />
      </View>
    )
  }

```

dialog.js
```js
import styles from './index.modules.scss';
render () {
    return (
      <View className={styles.dialog}>
        Dialog
      </View>
    )
  }
```

index.modules.scss
```css
.index {
  .title {

  }

  .btnQusetion {

  }
}

.dialog {

}
```

**期望行为**
能正确编译

**报错信息**

错误  组件编译  组件src/pages/index/dialog.js编译失败！
{ Error: ENOENT: no such file or directory, open 'E:\code\taro\app\src\pages\index\index.modules.scss'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at ImportDeclaration (C:\Users\62789\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:444:30)
    at NodePath._call (C:\Users\62789\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Users\62789\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\Users\62789\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (C:\Users\62789\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitMultiple (C:\Users\62789\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:103:17)
    at TraversalContext.visit (C:\Users\62789\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:190:19)
    at Function.traverse.node (C:\Users\62789\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\index.js:114:17)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'E:\\code\\taro\\app\\src\\pages\\index\\index.modules.scss' }

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 8.11.4 - D:\nodejs\node.EXE
      Yarn: 1.10.1 - C:\Users\62789\AppData\Roaming\npm\yarn.CMD
      npm: 5.6.0 - D:\nodejs\npm.CMD
 weapp

**Comment by DougFlands** [comment]
文件名写错，请关闭。抱歉。
