### ISSUE TITLE
When i use nervjs.renderToString for ssr,it throw an arror `window is not defined `

### ISSUE THREAD

**Issue by dzfrontend** [NervJS/taro#2917]
When i use nervjs.renderToString for ssr,it throw an arror like this:

`js
ReferenceError: window is not defined
    at D:\omyga-projects\OMyGa.Mobile\dist\js\serverEntry.js:1:5895
    at Object.<anonymous> (D:\omyga-projects\OMyGa.Mobile\dist\js\serverEntry.js:1:6111)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\omyga-projects\OMyGa.Mobile\ssr\index.js:5:21)
`

this is my code:

`js
const express = require('express');
const fs = require('fs');
const path = require('path');
const ReactSSR = require('nervjs')
const serverEntry = require('../dist/js/serverEntry')
const app = express()

app.get('*', function (req, res) {
  let appString = ReactSSR.renderToString(serverEntry.default);
  res.send(appString);
})
app.listen(0001, function () {
 console.log('server is listening on 3000 port');
})
`

and the file of `../dist/js/serverEntry` is generated by running commands `npm run build:h5`

**Comment by yuche** [comment]
把你 serverEntry  的源码贴出来

**Comment by dzfrontend** [comment]
[serverEntry.zip](https://github.com/NervJS/taro/files/3126066/serverEntry.zip)

打包文件很大，上传成了zip压缩格式

**Comment by yuche** [comment]
如果你要 debug，应该在用 dev 模式打包源码，然后在调用栈查看具体报错的是哪行代码

**Comment by dzfrontend** [comment]
代码没有报错，打包后，用服务端渲染会报这个错误

**Comment by dzfrontend** [comment]
麻烦了，准备不用taro做h5服务端渲染了

**Comment by yuche** [comment]
就是让你找的服务端渲染的堆栈
