### ISSUE TITLE
SyntaxError: unknown: Unexpected token

### ISSUE THREAD

**Issue by ypli0629** [NervJS/taro#292]
**问题描述**
自己写了个Home组件，替换默认的Index组件
**复现步骤**
```js
// 这里可以贴代码
import Taro, { Component } from '@tarojs/taro';
import { View } from '@tarojs/components';

export default class Home extends Component {
  componentWillUnmount() {}

  componentDidShow() {}
  componentDidHide() {}
  render() {
    return <View>hello taro</View>;
  }
}
```

**期望行为**

**报错信息**
```
错误  编译失败  src/pages/home/index.js
{ SyntaxError: unknown: Unexpected token (9:11)
   7 |   componentDidHide() {}
   8 |   render() {
>  9 |     return <View>hello taro</View>;
     |            ^
  10 |   }
  11 | }
  12 |
    at Parser.pp$5.raise (/Users/ypli/other-work/ameng/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/ypli/other-work/ameng/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/Users/ypli/other-work/ameng/node_modules/babylon/lib/index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (/Users/ypli/other-work/ameng/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/ypli/other-work/ameng/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/ypli/other-work/ameng/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/ypli/other-work/ameng/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/ypli/other-work/ameng/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExpression (/Users/ypli/other-work/ameng/node_modules/babylon/lib/index.js:3306:19)
    at Parser.pp$1.parseReturnStatement (/Users/ypli/other-work/ameng/node_modules/babylon/lib/index.js:2078:26)
  pos: 206,
  loc: Position { line: 9, column: 11 },
  _babel: true,
  codeFrame: '\u001b[0m \u001b[90m  7 | \u001b[39m  componentDidHide() {}\n \u001b[90m  8 | \u001b[39m  render() {\n\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m  9 | \u001b[39m    \u001b[36mreturn\u001b[39m \u001b[33m<\u001b[39m\u001b[33mView\u001b[39m\u001b[33m>\u001b[39mhello taro\u001b[33m<\u001b[39m\u001b[33m/\u001b[39m\u001b[33mView\u001b[39m\u001b[33m>\u001b[39m\u001b[33m;\u001b[39m\n \u001b[90m    | \u001b[39m           \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 10 | \u001b[39m  }\n \u001b[90m 11 | \u001b[39m}\n \u001b[90m 12 | \u001b[39m\u001b[0m' }
```
**系统信息**

 - 操作系统: OSX 10.13.5
 - Taro 版本v.0.0.67
 - Node.js 版本 v8.11.2

**补充信息**

**Comment by ypli0629** [comment]
错误根本看不懂啊🤕

**Comment by luckyadam** [comment]
`home ` 页面有没有在 `app.js` 里的 `pages` 里配置

**Comment by ypli0629** [comment]
@luckyadam ok了，错误的提示有待改进

**Comment by luckyadam** [comment]
@ypli0629 嗯嗯~这块错误提示要改
