### ISSUE TITLE
有个需求：请问 Taro 可以做到对某些目录只进行拷贝，而不要进行编译吗？

### ISSUE THREAD

**Issue by CPPAlien** [NervJS/taro#2927]
我现在想引入一些三方的小程序库放到 Taro 中， `copy.patterns` 虽然可以进行拷贝，但一旦我 require 了该库，则该库会被强制进行编译操作，请问是否有配置可以忽略掉？

因为直接编译环信的 sdk 会报错
```
TypeError: Cannot read property 'slice' of undefined
    at getExactedNpmFilePath (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/src/weapp.js:113:61)
    at CallExpression (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/src/weapp.js:541:33)
    at NodePath._call (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:115:19)
错误  编译失败  src/sdk/libs/strophe.js
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.extname (path.js:1223:5)
    at CallExpression (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/src/weapp.js:653:41)
    at NodePath._call (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/index.js:114:17)
```

#1110

**Comment by lk-chan** [comment]
请问这个

> 
> 
> 我现在想引入一些三方的小程序库放到 Taro 中， `copy.patterns` 虽然可以进行拷贝，但一旦我 require 了该库，则该库会被强制进行编译操作，请问是否有配置可以忽略掉？
> 
> 因为直接编译环信的 sdk 会报错
> 
> ```
> TypeError: Cannot read property 'slice' of undefined
>     at getExactedNpmFilePath (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/src/weapp.js:113:61)
>     at CallExpression (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/src/weapp.js:541:33)
>     at NodePath._call (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:76:18)
>     at NodePath.call (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:48:17)
>     at NodePath.visit (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:105:12)
>     at TraversalContext.visitQueue (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:150:16)
>     at TraversalContext.visitSingle (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:108:19)
>     at TraversalContext.visit (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:192:19)
>     at Function.traverse.node (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/index.js:114:17)
>     at NodePath.visit (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:115:19)
> 错误  编译失败  src/sdk/libs/strophe.js
> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
>     at validateString (internal/validators.js:107:11)
>     at Object.extname (path.js:1223:5)
>     at CallExpression (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/src/weapp.js:653:41)
>     at NodePath._call (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:76:18)
>     at NodePath.call (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:48:17)
>     at NodePath.visit (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:105:12)
>     at TraversalContext.visitQueue (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:150:16)
>     at TraversalContext.visitSingle (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:108:19)
>     at TraversalContext.visit (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:192:19)
>     at Function.traverse.node (/Users/qunhe/.nvm/versions/node/v9.8.0/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/index.js:114:17)
> ```
> 
> #1110

请问这个问题有解决吗？我现在也遇到同样的问题，怎么在taro里面使用环信im

**Comment by laiyaoWeb** [comment]
我也遇到这个同样的问题, 麻烦技术大牛能看看是什么原因造成的

**Comment by laiyaoWeb** [comment]
题已解决, strophe.js中require路径不对造成编译错误

**Comment by indown** [comment]
@laiyaoWeb 请问是如何解决的
