### ISSUE TITLE
[1.3.0beta.0]RN编译报错：Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.23, but stylelint uses 7.0.14. Perhaps this is the source of the error below.

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#2934]
**问题描述**
RN编译报错：

```
Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.23, but stylelint uses 7.0.14. Perhaps this is the source of the error below.
(node:54781) UnhandledPromiseRejectionWarning: Error: Error: No configuration provided for /Users/lzp/work/docker/www/pengpai_diy_app/src/theme.scss
    at Promise.all.then.then.then.catch (/Users/lzp/work/docker/www/pengpai_diy_app/node_modules/@tarojs/cli/dist/rn.js:95:15)
(node:54781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:54781) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.23, but stylelint uses 7.0.14. Perhaps this is the source of the error below.
```

**复现步骤**
[复现问题的步骤]
1. 旧项目是1.2.26
2. 直接修改package.json升到1.3.0beta版
3. npm run dev:rn 报错信息如上

**期望行为**
不要编译报错

**系统信息**
👽 Taro v1.2.26

  Taro CLI 1.2.26 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/cli: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/components: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/components-rn: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/plugin-babel: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/plugin-csso: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/plugin-sass: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/plugin-uglifyjs: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/redux: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/redux-h5: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/rn-runner: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/router: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/taro: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/taro-alipay: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/taro-h5: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/taro-redux-rn: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/taro-rn: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/taro-router-rn: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/taro-swan: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/taro-tt: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/taro-weapp: 1.3.0-beta.0 => 1.3.0-beta.0 
      @tarojs/webpack-runner: 1.3.0-beta.0 => 1.3.0-beta.0 
      eslint-config-taro: 1.3.0-beta.0 => 1.3.0-beta.0 
      eslint-plugin-taro: 1.3.0-beta.0 => 1.3.0-beta.0 
      nervjs: ^1.3.0 => 1.3.2 
      react: ^16.4.1 => 16.4.1 
    npmGlobalPackages:
      typescript: 2.4.2

**Comment by Pines-Cheng** [comment]
感谢反馈。

**Comment by biaomingzhong** [comment]
@Pines-Cheng 这个有临时解决方案吗？

**Comment by Pines-Cheng** [comment]
我这边怎样重现？

**Comment by biaomingzhong** [comment]
- 重现源码：

[myApp.tar.gz](https://github.com/NervJS/taro/files/3148157/myApp.tar.gz)

无论使用 yarn, cnpm 或 npm 安装依赖和执行 scripts，都会有问题

- 机器环境：

![image](https://user-images.githubusercontent.com/5178619/57229067-d3ce1c80-7047-11e9-931b-6db8ba4bd574.png)

- 执行命令：

```
myApp yarn dev:rn
```

- 运行结果：

```
yarn run v1.13.0
$ npm run build:rn -- --watch
npm WARN lifecycle The node binary used for scripts is /var/folders/bq/wnj7p4hs63ldg26_7vpy20tr0000gn/T/yarn--1557150189741-0.3971185198168783/node but npm is using /Users/quinlanzhong/.nvm/versions/node/v10.8.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> myApp@1.0.0 build:rn /Users/quinlanzhong/TaroProjects/myApp
> taro build --type rn "--watch"

👽 Taro v1.3.0-beta.0

开始编译项目 myApp
编译  JS        /Users/quinlanzhong/TaroProjects/myApp/src/app.js
编译  LESS      /Users/quinlanzhong/TaroProjects/myApp/src/app.less
拷贝  HTML      /Users/quinlanzhong/TaroProjects/myApp/src/index.html
编译  JS        /Users/quinlanzhong/TaroProjects/myApp/src/pages/index/index.js
编译  LESS      /Users/quinlanzhong/TaroProjects/myApp/src/pages/index/index.less
生成  index.js  /Users/quinlanzhong/TaroProjects/myApp/.rn_temp/index.js
生成  app.json  /Users/quinlanzhong/TaroProjects/myApp/.rn_temp/app.json
生成  package.json  /Users/quinlanzhong/TaroProjects/myApp/.rn_temp/package.json

开始安装依赖~
warning package.json: No license field
info No lockfile found.
warning myApp: No license field
[1/4] Resolving packages...
warning @tarojs/components-rn > @ant-design/react-native > react-native-swipeout > create-react-class > fbjs > core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @tarojs/components-rn@1.3.0-beta.0" has incorrect peer dependency "react@^16.4.1".
warning "@tarojs/taro-router-rn > react-navigation > create-react-context@0.2.2" has unmet peer dependency "prop-types@^15.0.0".
warning "react-native > eslint-plugin-react-native@3.7.0" has unmet peer dependency "eslint@^3.17.0 || ^4 || ^5".
[4/4] Building fresh packages...
success Saved lockfile.
编译  编译完成，花费19833 ms

初始化完毕，监听文件修改中...

Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.23, but stylelint uses 7.0.16. Perhaps this is the source of the error below.
(node:61657) UnhandledPromiseRejectionWarning: Error: Error: No configuration provided for /Users/quinlanzhong/TaroProjects/myApp/src/app.less
at Promise.all.then.then.then.catch (/Users/quinlanzhong/TaroProjects/myApp/node_modules/@tarojs/cli/dist/rn.js:95:15)
(node:61657) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:61657) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.23, but stylelint uses 7.0.16. Perhaps this is the source of the error below.
(node:61657) UnhandledPromiseRejectionWarning: Error: Error: No configuration provided for /Users/quinlanzhong/TaroProjects/myApp/src/pages/index/index.less
    at Promise.all.then.then.then.catch (/Users/quinlanzhong/TaroProjects/myApp/node_modules/@tarojs/cli/dist/rn.js:95:15)
(node:61657) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by tourze** [comment]
尝试在package.json中锁死 stylelint 版本来绕过，发现还是报错：

```
  "resolutions": {
    "stylelint": "9.3.0"
  }
```

报错：
(node:92260) UnhandledPromiseRejectionWarning: Error: Error: No configuration provided for /Users/lzp/work/docker/www/pengpai_diy_app/src/iconfont/iconfont.css
    at Promise.all.then.then.then.catch (/Users/lzp/work/docker/www/pengpai_diy_app/node_modules/@tarojs/cli/dist/rn.js:95:15)
(node:92260) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by Pines-Cheng** [comment]
重现了。
