### ISSUE TITLE
Taro Cli编译问题

### ISSUE THREAD

**Issue by soqt** [NervJS/taro#2945]
**问题描述**
在weapp dev环境下，只要有CSS样式书写不正确，自动退出编译模式

**复现步骤**
1.2.26中用watch mode编译代码，然后故意写一行错误css代码即可。比如 `color:`但不加具体值，然后保存

**期望行为**
之前的版本只是会报错，但不会退出。项目每次编译都要半分钟，不小心点css保存后然后自动退出编译非常崩溃。

**报错信息**
```bash
  src/pages/nameCard/index.scss 62:24  root stylesheet
    at Object.BI (/Users/samwang/Developer/yoogas/yoogas-taro/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:5233:30)
    at Object.Ei (/Users/samwang/Developer/yoogas/yoogas-taro/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:5149:34)
    at nF.E8 (/Users/samwang/Developer/yoogas/yoogas-taro/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:5135:5)
    at Object.GZ (/Users/samwang/Developer/yoogas/yoogas-taro/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:463:69)
    at Object.hB (/Users/samwang/Developer/yoogas/yoogas-taro/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:2191:27)
    at HV (/Users/samwang/Developer/yoogas/yoogas-taro/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:2991:27)
    at Object.renderSync (/Users/samwang/Developer/yoogas/yoogas-taro/node_modules/@tarojs/plugin-sass/node_modules/dart-sass/sass.dart.js:2980:42)
    at Promise (/Users/samwang/Developer/yoogas/yoogas-taro/node_modules/@tarojs/plugin-sass/index.js:34:21)
    at new Promise (<anonymous>)
    at compileSass (/Users/samwang/Developer/yoogas/yoogas-taro/node_modules/@tarojs/plugin-sass/index.js:5:10)
  formatted:
   'Error: Expected expression.\n   ╷\n62 │         margin-bottom: \n   │                        ^\n   ╵\n  src/pages/nameCard/index.scss 62:24  root stylesheet',
  line: 62,
  column: 24,
  file:
   '/Users/samwang/Developer/yoogas/yoogas-taro/src/pages/nameCard/index.scss',
  status: 1 }

```

**系统信息**
 - 操作系统: macOS 10.14.4
 - Taro 版本 1.2.26
 - Node.js 版本10.15.1
 - 报错平台 weapp

**Comment by luckyadam** [comment]
有道理，可以改成 watch 时不中断

**Comment by Garfield550** [comment]
建议 ref 到 https://github.com/NervJS/taro/issues/2852，因为同样是换用 dart-sass 的问题
