### ISSUE TITLE
升级1.3.0之后，typescript 中的connect第一次报错： Cannot read property 'dispatch' of null 

### ISSUE THREAD

**Issue by 378978764** [NervJS/taro#2964]
**问题描述**
官方的`Typescript`+`Redux`模板，升级`taro 1.3.0`之后，在使用`@connect`的页面，小程序初次运行之后就会提示` Cannot read property 'dispatch' of null `的错误，但是后续继续使用`dispatch`的方法能够正常使用，只有刚加载的时候，报错。

**复现步骤**
[复现问题的步骤]
1. 使用1.3.0之前的版本，新建一个`Typescript`+`Redux`模板。
2. 升级到1.3.0
3. 重新编译
4. 报错

其中，`app.tsx`创建`store`如下：
```js
import { Provider } from '@tarojs/redux'
import configStore from './store'
const store = configStore()
...
render () {
    return (
      <Provider store={store}>
        <Index />
      </Provider>
    )
  }
```

`./store`文件如下：
```js
import { createStore, applyMiddleware, compose } from 'redux'
import thunkMiddleware from 'redux-thunk'
import rootReducer from '../reducers'

const composeEnhancers =
  typeof window === 'object' &&
  window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ ?   
    window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({
      // Specify extension’s options like name, actionsBlacklist, actionsCreators, serialize...
    }) : compose

const middlewares = [
  thunkMiddleware
]

if (process.env.NODE_ENV === 'development') {
  middlewares.push(require('redux-logger').createLogger())
}

const enhancer = composeEnhancers(
  applyMiddleware(...middlewares),
  // other store enhancers if any
)

export default function configStore () {
  const store = createStore(rootReducer, enhancer)
  return store
}

```
**期望行为**
第一次能够不报错。

**报错信息**
```
VM831:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'dispatch' of null 
 TypeError: Cannot read property 'dispatch' of null
    at connect (http://127.0.0.1:44566/appservice/weapp/npm/@tarojs/redux/dist/index.js:230:23)
    at http://127.0.0.1:44566/appservice/weapp/components/NavBar/index.js:198:50
    at require (http://127.0.0.1:44566/appservice/__dev__/WAService.js:1:1001939)
    at <anonymous>:1103:7
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:44566/appservice/appservice?t=1557129109045:10624:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:44566/appservice/appservice?t=1557129109045:10636:20)
console.error @ VM831:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1557129109045:9062
window.onerror @ VM831:1
scriptLoaded @ appservice?t=1557129109045:10624
script.onload @ appservice?t=1557129109045:10636
```

**系统信息**
`1.30`执行`taro info`居然报错了。。。，报错信息如下：
```
👽 Taro v1.3.0-beta.0

/usr/local/lib/node_modules/@tarojs/cli/bin/taro-info:9
const npmPackages = UPDATE_PACKAGE_LIST.concat(['react', 'react-native', 'nervjs', 'expo'])
                                        ^

TypeError: Cannot read property 'concat' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/bin/taro-info:9:41)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

**补充信息**
既然后来都没有报错，只是第一次加载的时候报错了，可能是`app.tsx`中初次使用`score`的时候，`store`还没有创建好？

**Comment by 378978764** [comment]
进展：发现这次`taro`编译的目录居然变了。。。变成了`dist`文件夹下的`weapp`文件夹，修改`project.config.json`文件中的`miniprogramRoot`为新文件夹之后，重新编译，问题消失。
但是带来了更加令人失望的问题，就是组件传递的函数中的`this`实例，原来是指向父组件的，现在变成子组件了。。。导致没法在传递的函数中，将数据绑定到父组件上。
详情见：[https://github.com/NervJS/taro/issues/2965](另一个issue)

**Comment by Nodewebzsz** [comment]
请问楼主，我也遇到相同的问题，你说的 修改project.config.json文件中的miniprogramRoot为新文件夹“具体是改成什么呢

**Comment by 378978764** [comment]
@Nodewebzsz dist下的weapp
