### ISSUE TITLE
用ts开发taro,引入taro-ui, babel编译发生了问题

### ISSUE THREAD

**Issue by feikool** [NervJS/taro#3140]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  taro init dirname
2. yarn add taro-ui
3. cd /src/pages/index.tsx
```
import { AtNavBar } from 'taro-ui'
<AtButton type='primary'>按钮</AtButton> 
```

```js
错误  编译失败  node_modules/@tarojs/taro-weapp/dist/index.js
TypeError: unknown: Property id of FunctionDeclaration expected node to be of a type ["Identifier"] but instead got "BooleanLiteral"
    at Object.validate (/Users/renlimin/.config/yarn/global/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/Users/renlimin/.config/yarn/global/node_modules/babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (/Users/renlimin/.config/yarn/global/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath.replaceWith (/Users/renlimin/.config/yarn/global/node_modules/babel-traverse/lib/path/replacement.js:160:8)
    at replaceAndEvaluateNode (/Users/renlimin/.config/yarn/global/node_modules/babel-plugin-transform-define/lib/index.js:117:12)
    at processNode (/Users/renlimin/.config/yarn/global/node_modules/babel-plugin-transform-define/lib/index.js:143:5)
    at PluginPass.Identifier (/Users/renlimin/.config/yarn/global/node_modules/babel-plugin-transform-define/lib/index.js:23:9)
    at newFn (/Users/renlimin/.config/yarn/global/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/renlimin/.config/yarn/global/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/renlimin/.config/yarn/global/node_modules/babel-traverse/lib/path/context.js:48:17) {
  _babel: true
}
生成  依赖文件  dist/npm/prop-types/index.js
错误  编译失败  node_modules/prop-types/factoryWithTypeCheckers.js
TypeError: unknown: Property id of FunctionDeclaration expected node to be of a type ["Identifier"] but instead got "BooleanLiteral"
    at Object.validate (/Users/renlimin/.config/yarn/global/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/Users/renlimin/.config/yarn/global/node_modules/babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (/Users/renlimin/.config/yarn/global/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath.replaceWith (/Users/renlimin/.config/yarn/global/node_modules/babel-traverse/lib/path/replacement.js:160:8)
    at replaceAndEvaluateNode (/Users/renlimin/.config/yarn/global/node_modules/babel-plugin-transform-define/lib/index.js:117:12)
    at processNode (/Users/renlimin/.config/yarn/global/node_modules/babel-plugin-transform-define/lib/index.js:143:5)
    at PluginPass.Identifier (/Users/renlimin/.config/yarn/global/node_modules/babel-plugin-transform-define/lib/index.js:23:9)
    at newFn (/Users/renlimin/.config/yarn/global/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/renlimin/.config/yarn/global/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/renlimin/.config/yarn/global/node_modules/babel-traverse/lib/path/context.js:48:17) {
  _babel: true
}
```

**期望行为**
希望能早日适配ts
**报错信息**
![image](https://user-images.githubusercontent.com/24382285/58176441-d8940100-7cd4-11e9-9de7-1ef77a54b84c.png)

**系统信息**
 - 操作系统: [macOS 10.14.5]
 - Taro 版本 [ v.1.2.26]
 - Node.js 版本 [v12.1.0]
 - 报错平台 [weapp]
 - Yarn版本 [v 1.15.2]
 - typescript: [v 3.3.4000]

**补充信息**
感觉taro 很多以来都没有适配ts

**Comment by luckyadam** [comment]
没有复现，最好提供一个 demo
