### ISSUE TITLE
在小程序 中 有时候加载 'invoke'  of undefined

### ISSUE THREAD

**Issue by Joyee** [NervJS/taro#3235]
VM4144:1 TypeError: Cannot read property 'invoke' of undefined
    at Object.Xe [as traceBeginEvent] (:63045/__pageframe__/__dev__/WAWebview.js:1)
    at :63045/__pageframe__/__dev__/WAWebview.js:1
    at HTMLDocument.<anonymous> (:63045/__pageframe__/__dev__/WAWebview.js:1)
    at <anonymous>:15:16
    at <anonymous>:32:21
console.error @ VM4144:1
(anonymous) @ VM4206:2
VM4207:1 Wed May 29 2019 14:40:45 GMT+0800 (中国标准时间) 渲染层错误
VM4144:1 exparserScriptError
Cannot read property 'invoke' of undefined
TypeError: Cannot read property 'invoke' of undefined
    at Object.Xe [as traceBeginEvent] (http://127.0.0.1:63045/__pageframe__/__dev__/WAWebview.js:1:112679)
    at http://127.0.0.1:63045/__pageframe__/__dev__/WAWebview.js:1:1154783
    at HTMLDocument.<anonymous> (http://127.0.0.1:63045/__pageframe__/__dev__/WAWebview.js:1:1142992)
    at <anonymous>:15:16
    at <anonymous>:32:21

**Comment by Garfield550** [comment]
你是不是遇到这个问题了

https://developers.weixin.qq.com/community/develop/doc/000cec3fa38bc82105a8669305b400

![image](https://user-images.githubusercontent.com/3471836/58536602-a67a2600-8223-11e9-9b10-4657cb9c5753.png)
