### ISSUE TITLE
根据`taro-ui-sample`项目配置jest，测试时会报错

### ISSUE THREAD

**Issue by biliGates** [NervJS/taro#3257]
**问题描述**
根据`taro-ui-sample`项目来配置 jest 后，使用单元测试报错。

**复现步骤**
示例代码地址
https://github.com/biliGates/taro_test_example

```js

// babel.config.js
const apis = require('@tarojs/taro-h5/dist/taroApis')

module.exports = {
  presets: [['@babel/env', { spec: true, useBuiltIns: false }]],
  plugins: [
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    '@babel/plugin-proposal-class-properties',
    [
      '@babel/plugin-transform-react-jsx',
      {
        pragma: 'Nerv.createElement',
      },
    ],
    ['@babel/plugin-proposal-object-rest-spread'],
    [
      'babel-plugin-transform-taroapi',
      {
        apis,
        packageName: '@tarojs/taro-h5',
      },
    ],
  ],
}

// jest.config.js
module.exports = {
  verbose: true,
  moduleFileExtensions: ['js', 'jsx', 'json'],
  rootDir: __dirname,
  testMatch: ['<rootDir>/src/**/*.test.js', '<rootDir>/src/**/test.js'],
  transform: {
    '^.+\\.jsx?$': 'babel-jest',
  },
  transformIgnorePatterns: ['<rootDir>/node_modules/'],
  moduleNameMapper: {
    react: 'nervjs',
    'react-addons-test-utils': 'nerv-test-utils',
    'react-dom': 'nervjs',
    '\\.(css|less|sass|scss)$': '<rootDir>/config/styleMock.js',
    weui: '<rootDir>/config/styleMock.js',
    '^@/(.*)$': '<rootDir>/src/$1',
  },
}


// src/example/index.test.js
import Nerv from 'nervjs'
import { renderToString } from 'nerv-server'

import Index from '../../.temp/example/PureComponent'

describe('canary test', () => {
  it('true must to equal true', () => {
    expect(true).toBe(true)
  })

  it('jsx render test', () => {
    const component = renderToString(<Index />)
    expect(component).toEqual('<div></div>')
  })
})


// .temp/example/PureComponent.js
import Nerv from "nervjs";
import Taro, { Component } from "@tarojs/taro-h5";
import { View } from '@tarojs/components';

class PureComponent extends Component {
  render() {
    return <View>{this.props.text}</View>;
  }
}

export default PureComponent;
```

**报错信息**
运行 npm run test
```js
src/example/index.test.js
  ● Test suite failed to run

    TypeError: Super expression must either be null or a function

      1 | import Nerv from "nervjs";
      2 | import Taro, { Component } from "@tarojs/taro-h5";
    > 3 | import { View } from '@tarojs/components';
        | ^
      4 | 
      5 | class PureComponent extends Component {
      6 |   render() {

      at _inherits (node_modules/@tarojs/components/dist/index.js:17459:113)
      at node_modules/@tarojs/components/dist/index.js:17480:3
      at Object._this2 (node_modules/@tarojs/components/dist/index.js:17556:2)
      at __webpack_require__ (node_modules/@tarojs/components/dist/index.js:30:30)
      at Object.__webpack_exports__.a (node_modules/@tarojs/components/dist/index.js:16892:70)
      at __webpack_require__ (node_modules/@tarojs/components/dist/index.js:30:30)
      at Object.<anonymous> (node_modules/@tarojs/components/dist/index.js:1087:78)
      at __webpack_require__ (node_modules/@tarojs/components/dist/index.js:30:30)
      at node_modules/@tarojs/components/dist/index.js:73:18
      at node_modules/@tarojs/components/dist/index.js:76:10
      at webpackUniversalModuleDefinition (node_modules/@tarojs/components/dist/index.js:3:20)
      at Object.<anonymous> (node_modules/@tarojs/components/dist/index.js:10:3)
      at Object.<anonymous> (.temp/example/PureComponent.js:3:1)
      at Object.<anonymous> (src/example/index.test.js:4:1)
```

**系统信息**
```bash
👽 Taro v1.3.0-beta.5


  Taro CLI 1.3.0-beta.5 environment info:
    System:
      OS: Linux 4.15 Deepin 15 15.10.1
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/bin/node
      Yarn: 1.16.0 - /usr/bin/yarn
      npm: 6.4.1 - /usr/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/cli: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/components: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-babel: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-csso: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-sass: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-uglifyjs: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/redux: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/redux-h5: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/router: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-alipay: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-h5: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-swan: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-tt: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-weapp: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/webpack-runner: 1.3.0-beta.5 => 1.3.0-beta.5 
      eslint-config-taro: 1.3.0-beta.5 => 1.3.0-beta.5 
      eslint-plugin-taro: 1.3.0-beta.5 => 1.3.0-beta.5 
      nervjs: ^1.4.0-beta.3 => 1.4.0-beta.5 


```

**Comment by PARADISELIN** [comment]
而且1.3.0-beta.6在做快照测试的会报ReactIs.isElement is not a function

**Comment by luckyadam** [comment]
可以升级到 1.3.0-beta.6 试一下 #3288

**Comment by PARADISELIN** [comment]
> 可以升级到 1.3.0-beta.6 试一下 #3288

在1.3.0-beta.6，使用过装饰器的组件，仍热会报`TypeError: Super expression must either be null or a function`这个错误
