### ISSUE TITLE
微信小程序转 Taro 时子组件路径不对，报错找不到子组件的JS文件

### ISSUE THREAD

**Issue by vecold** [NervJS/taro#3260]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
微信小程序转 Taro 时子组件路径不对，报错找不到子组件的JS文件

**复现步骤**
[复现问题的步骤]
我将原生微信小程序转Taro时报错子组件AddPrice路径不对，找不到JS文件
错误  组件转换  /Users/luzhengyong/Documents/workspace/react/wxstore_client/AddPrice/AddPrice.js
Error: 组件 /Users/luzhengyong/Documents/workspace/react/wxstore_client/AddPrice/AddPrice 没有 JS 文件！
    at components.forEach.componentObj (/usr/local/lib/node_modules/@tarojs/cli/dist/convertor/index.js:494:27)
    at Set.forEach (<anonymous>)
    at Convertor.traverseComponents (/usr/local/lib/node_modules/@tarojs/cli/dist/convertor/index.js:480:20)
    at pages.forEach.page (/usr/local/lib/node_modules/@tarojs/cli/dist/convertor/index.js:468:22)
    at Set.forEach (<anonymous>)
    at Convertor.traversePages (/usr/local/lib/node_modules/@tarojs/cli/dist/convertor/index.js:406:20)
    at Convertor.run (/usr/local/lib/node_modules/@tarojs/cli/dist/convertor/index.js:643:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/bin/taro-convert:12:11)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)

我在微信小程序中是这么引用的而且没有问题
{
  "usingComponents": {
      "addTitle": "../addTitle/addTitle",
      "AddPrice": "../AddPrice/AddPrice",
      "addcategory": "../addcategory/addcategory",
      "addSku": "../addSku/addSku",
      "mainpic":"../../../components/mainpic/mainpic"
  }
}

```

**期望行为**
希望能够支持相对路径转换
**报错信息**

![image](https://user-images.githubusercontent.com/22338845/58634527-17056d80-831e-11e9-8462-c7538d28246e.png)


**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

👽 Taro v1.3.0-beta.5


  Taro CLI 1.3.0-beta.5 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.3.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
可能是相对路径有问题

**Comment by luckyadam** [comment]
可以提供一个 demo 看看么

**Comment by twinklexp** [comment]
我遇到相同问题，
解决方案：组件文件夹名称首字母修改成大写的，就可以了。
@luckyadam @vecold
