### ISSUE TITLE
1.2.26 升级 1.3.0-beta.6 成功  run H5 失败

### ISSUE THREAD

**Issue by giantss** [NervJS/taro#3321]
## 我的升级步骤

1. 
![image](https://user-images.githubusercontent.com/13778798/58928054-8b5b6900-8783-11e9-9cee-7e28c3175f52.png)

2. 删除 `node_modules/`

3. `npm install` 

4. `npm run dev:h5` 报错  `TypeError: Cannot read property 'isWatch' of undefined`. 下面是升级和 run H5 console 日志。

## 解决方案

5.  `taro update self`
6.  `taro update project`

## 日志
```
^CEdugaming $npm install
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).

> fsevents@1.2.9 install /Users/zhongpeng/file/code/applet/taro/wrok/Edugaming/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/zhongpeng/file/code/applet/taro/wrok/Edugaming/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> node-sass@4.12.0 install /Users/zhongpeng/file/code/applet/taro/wrok/Edugaming/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/zhongpeng/.npm/node-sass/4.12.0/darwin-x64-64_binding.node

> swiper@4.5.0 postinstall /Users/zhongpeng/file/code/applet/taro/wrok/Edugaming/node_modules/swiper
> node -e "console.log('\u001b[35m\u001b[1mLove Swiper? Support Vladimir\'s work by donating or pledging on patreon:\u001b[22m\u001b[39m\n > \u001b[32mhttps://patreon.com/vladimirkharlampidi\u001b[0m\n')"

Love Swiper? Support Vladimir's work by donating or pledging on patreon:
 > https://patreon.com/vladimirkharlampidi


> node-sass@4.12.0 postinstall /Users/zhongpeng/file/code/applet/taro/wrok/Edugaming/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/zhongpeng/file/code/applet/taro/wrok/Edugaming/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine
npm WARN @tarojs/components@1.3.0-beta.6 requires a peer of nervjs@^1.4.0-beta.4 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-taro@1.3.0-beta.6 requires a peer of eslint@^5.16.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-taro@1.3.0-beta.6 requires a peer of eslint@^5.16.0 but none is installed. You must install peer dependencies yourself.

added 1252 packages from 891 contributors and audited 17286 packages in 35.73s
found 0 vulnerabilities



   ╭───────────────────────────────────────────────────────────────╮
   │                                                               │
   │       New minor version of npm available! 6.4.1 → 6.9.0       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.9.0   │
   │               Run npm install -g npm to update!               │
   │                                                               │
   ╰───────────────────────────────────────────────────────────────╯

Edugaming $npm run dev:h5

> Edugaming@1.0.0 dev:h5 /Users/zhongpeng/file/code/applet/taro/wrok/Edugaming
> npm run build:h5 -- --watch


> Edugaming@1.0.0 build:h5 /Users/zhongpeng/file/code/applet/taro/wrok/Edugaming
> taro build --type h5 "--watch"

👽 Taro v1.2.26

开始编译项目 Edugaming
创建  发现文件  src/app.css
创建  发现文件  src/app.css.map
创建  发现文件  src/app.js
创建  发现文件  src/app.scss
创建  发现文件  src/icon.css
创建  发现文件  src/icon.css.map
创建  发现文件  src/icon.scss
创建  发现文件  src/index.html
创建  发现文件  src/assets/fonts/iconfont.eot
创建  发现文件  src/assets/fonts/iconfont.ttf
创建  发现文件  src/assets/fonts/iconfont.woff
创建  发现文件  src/assets/fonts/iconfont.woff2
创建  发现文件  src/components/CusAudio/index.css
创建  发现文件  src/components/CusAudio/index.css.map
创建  发现文件  src/components/CusAudio/index.js
创建  发现文件  src/components/CusAudio/index.scss
创建  发现文件  src/components/CusRadio/index.css
创建  发现文件  src/components/CusRadio/index.css.map
创建  发现文件  src/components/CusRadio/index.js
创建  发现文件  src/components/CusRadio/index.scss
创建  发现文件  src/pages/index/index.js
创建  发现文件  src/pages/index/index.scss
创建  发现文件  src/pages/progress/index.css
创建  发现文件  src/pages/progress/index.css.map
创建  发现文件  src/pages/progress/index.js
创建  发现文件  src/pages/progress/index.scss
创建  发现文件  src/pages/template/index.css
创建  发现文件  src/pages/template/index.css.map
创建  发现文件  src/pages/template/index.js
创建  发现文件  src/pages/template/index.scss
创建  发现文件  src/pages/user/index.css
创建  发现文件  src/pages/user/index.css.map
创建  发现文件  src/pages/user/index.js
创建  发现文件  src/pages/user/index.scss
创建  发现文件  src/pages/progress/detail/index.css
创建  发现文件  src/pages/progress/detail/index.css.map
创建  发现文件  src/pages/progress/detail/index.js
创建  发现文件  src/pages/progress/detail/index.scss
创建  发现文件  src/pages/user/add/index.css
创建  发现文件  src/pages/user/add/index.css.map
创建  发现文件  src/pages/user/add/index.js
创建  发现文件  src/pages/user/add/index.scss
创建  发现文件  src/pages/user/add/res/default_avatar.png
(node:10920) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isWatch' of undefined
    at Object.<anonymous> (/Users/zhongpeng/file/code/applet/taro/wrok/Edugaming/node_modules/@tarojs/webpack-runner/dist/index.js:99:16)
    at Generator.next (<anonymous>)
    at /Users/zhongpeng/file/code/applet/taro/wrok/Edugaming/node_modules/@tarojs/webpack-runner/dist/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/zhongpeng/file/code/applet/taro/wrok/Edugaming/node_modules/@tarojs/webpack-runner/dist/index.js:3:12)
    at exports.default (/Users/zhongpeng/file/code/applet/taro/wrok/Edugaming/node_modules/@tarojs/webpack-runner/dist/index.js:98:40)
    at buildDist (/Users/zhongpeng/.config/yarn/global/node_modules/@tarojs/cli/src/h5.js:1085:3)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:10920) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10920) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by AllanChen** [comment]
### update node and npm 
`taro update self`
`taro update project`

**Comment by giantss** [comment]
> ### update node and npm
> `taro update self`
> `taro update project`

嗯 可以了 谢谢
@luckyadam 麻烦把这两个命令也写在文档中更新步骤下面啊

**Comment by MessageBoy** [comment]
我也出现这个问题，然后我update project之后并没有好，还是出现‘isWatch’的报错
