### ISSUE TITLE
编译的时候某些和nodejs自带库重名的包不会被打包

### ISSUE THREAD

**Issue by skymoonya** [NervJS/taro#3347]
**问题描述**
比如querystring，比如Buffer

**复现步骤**
`package.json`中有如下包，在项目某个js中import这些包，会报错
```json
{ "dependencies": { "querystring": "^0.2.0", "buffer": "^5.2.1" } }
```
在`node_modules`文件夹中可以找到这些包，但是在`dist/npm`中找不到

**期望行为**
在`dist/npm`中可以找到这些包

**报错信息**
```
(node:83811) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'querystring'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at /Users/moon/.nvm/versions/node/v10.15.3/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:175:30
    at Generator.next (<anonymous>)
    at /Users/moon/.nvm/versions/node/v10.15.3/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/moon/.nvm/versions/node/v10.15.3/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:3:12)
    at recursiveRequire (/Users/moon/.nvm/versions/node/v10.15.3/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:174:12)
    at Object.resolveNpmFilesPath (/Users/moon/.nvm/versions/node/v10.15.3/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:53:9)
    at Object.getExactedNpmFilePath (/Users/moon/.nvm/versions/node/v10.15.3/lib/node_modules/@tarojs/cli/dist/util/npmExact.js:22:45)
(node:83811) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:83811) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**系统信息**
```
MacBook-Pro-2:c-mini-program moon$ taro info
👽 Taro v1.3.0-beta.6


  Taro CLI 1.3.0-beta.6 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/components: ^1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/plugin-babel: ^1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/plugin-csso: ^1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/plugin-less: ^1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/plugin-uglifyjs: ^1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/redux: ^1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/redux-h5: ^1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/router: ^1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/taro: ^1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/taro-alipay: ^1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/taro-h5: ^1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/taro-swan: ^1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/taro-tt: ^1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/taro-weapp: ^1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/webpack-runner: ^1.3.0-beta.6 => 1.3.0-beta.6 
      eslint-config-taro: ^1.3.0-beta.6 => 1.3.0-beta.6 
      eslint-plugin-taro: ^1.3.0-beta.6 => 1.3.0-beta.6 
      nervjs: ^1.4.0 => 1.4.0
```

**Comment by luckyadam** [comment]
那就不要用这些包吧。。。找替代物

**Comment by skymoonya** [comment]
> 那就不要用这些包吧。。。找替代物

我现在就是这么解决的，但感觉这样是绕过了这个问题，官方文档也没找到相关说明

**Comment by luckyadam** [comment]
后续会加入说明，node 的包不要使用

**Comment by drizzlezxy** [comment]
在调用的时候可以显式引用依赖，告诉taro这个是npm依赖包，不是node的模块。

修改方式如下：
把`require('buffer')`改成`require('buffer/')`，import也是同理。
