### ISSUE TITLE
微信小程序转taro报错

### ISSUE THREAD

**Issue by yanluohao** [NervJS/taro#3378]
**问题描述**
在全局安装了tarojs后，进入到微信小程序项目目录，使用taro convert，发生报错

**复现步骤**
[复现问题的步骤]
1. 先npm i -g @tarojs/cli
2. 然后进入微信小程序项目文件
3. taro convert，然后显示开始代码转换
4. 转换过程中发生如下错误，转换被中断

**期望行为**
我希望taro convert能够成功

**报错信息**

```js
/Users/ylh/.nvm/versions/node/v10.15.3/lib/node_modules/@tarojs/cli/node_modules/ejs/lib/ejs.js:352
  throw err;
  ^

ReferenceError: /Users/ylh/.nvm/versions/node/v10.15.3/lib/node_modules/@tarojs/cli/templates/default/pkg:7
    5|   "description": "<%= description %>",
    6|   "templateInfo": {
 >> 7|     "name": "<%= template %>",
    8|     "typescript": <%= typescript %>,
    9|     "css": "<%= css %>"
    10|   },

template is not defined
    at eval (eval at compile (/Users/ylh/.nvm/versions/node/v10.15.3/lib/node_modules/@tarojs/cli/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:17:26)
    at returnedFn (/Users/ylh/.nvm/versions/node/v10.15.3/lib/node_modules/@tarojs/cli/node_modules/ejs/lib/ejs.js:653:17)
    at Object.exports.render (/Users/ylh/.nvm/versions/node/v10.15.3/lib/node_modules/@tarojs/cli/node_modules/ejs/lib/ejs.js:416:37)
    at render (/Users/ylh/.nvm/versions/node/v10.15.3/lib/node_modules/@tarojs/cli/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:14:18)
    at process (/Users/ylh/.nvm/versions/node/v10.15.3/lib/node_modules/@tarojs/cli/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:31:14)
    at applyProcessingFunc (/Users/ylh/.nvm/versions/node/v10.15.3/lib/node_modules/@tarojs/cli/node_modules/mem-fs-editor/lib/actions/copy.js:14:16)
    at EditionInterface.exports._copySingle (/Users/ylh/.nvm/versions/node/v10.15.3/lib/node_modules/@tarojs/cli/node_modules/mem-fs-editor/lib/actions/copy.js:64:16)
    at files.forEach.file (/Users/ylh/.nvm/versions/node/v10.15.3/lib/node_modules/@tarojs/cli/node_modules/mem-fs-editor/lib/actions/copy.js:51:10)
    at Array.forEach (<anonymous>)
    at EditionInterface.exports.copy (/Users/ylh/.nvm/versions/node/v10.15.3/lib/node_modules/@tarojs/cli/node_modules/mem-fs-editor/lib/actions/copy.js:50:9)
```

**系统信息**

 - 操作系统: macOS 10.14
 - Taro 版本: v1.3.0-beta.8
 - Node.js 版本: 10.15.3
 - 报错平台: 微信小程序taro convert转为taro

**补充信息**
报错信息指向ejs，后来我用nvm切换到node 8.9.4以后就正常了，应该是node版本问题

**Comment by Garfield550** [comment]
你可以试试 1.3.0 正式版，昨天也有人提这个问题 #3370，已经在 1.3.0 修复了。

**Comment by yanluohao** [comment]
> 你可以试试 1.3.0 正式版，昨天也有人提这个问题 #3370，已经在 1.3.0 修复了。
👌
