### ISSUE TITLE
微信小程序转taro后，再通过taro转微信小程序时出现报错

### ISSUE THREAD

**Issue by yanluohao** [NervJS/taro#3385]
**问题描述**
现有微信小程序通过taro convert转成taro后，执行npm run dev:weapp，编译过程产生报错，但是webpack的watch依旧存在，然后此时去编辑文件，会出现
警告  JS文件    src/pages/index/index.js 没有被引用到，不会被编译

**复现步骤**
1. 微信小程序转taro
2. 在taro文件夹下执行npm run dev:weapp
3. 编译过程产生报错

**期望行为**
希望taro转微信小程序成功

**报错信息**

```js
开始编译项目 taroConvert
生成  工具配置  dist/project.config.json
编译  入口文件  src/app.js
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
拷贝  NPM文件   dist/npm/nervjs/dist/index.js
拷贝  NPM文件   dist/npm/nervjs/index.js
拷贝  NPM文件   dist/npm/@tarojs/taro-weapp/dist/index.js
拷贝  NPM文件   dist/npm/@tarojs/taro-weapp/index.js
TypeError: Cannot read property 'forEach' of undefined
    at Object.traverseObjectNode (/Users/ylh/.nvm/versions/node/v8.9.4/lib/node_modules/@tarojs/cli/dist/util/index.js:405:20)
    at ClassProperty (/Users/ylh/.nvm/versions/node/v8.9.4/lib/node_modules/@tarojs/cli/dist/mini/astProcess.js:299:36)
    at NodePath._call (/Users/ylh/.nvm/versions/node/v8.9.4/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/ylh/.nvm/versions/node/v8.9.4/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/ylh/.nvm/versions/node/v8.9.4/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/ylh/.nvm/versions/node/v8.9.4/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/ylh/.nvm/versions/node/v8.9.4/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/ylh/.nvm/versions/node/v8.9.4/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/ylh/.nvm/versions/node/v8.9.4/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/ylh/.nvm/versions/node/v8.9.4/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:115:19)
编译  所有页面  

监听文件修改中...

警告  JS文件    src/pages/index/index.js 没有被引用到，不会被编译

```

**系统信息**

 - 操作系统: macOS 10.14
 - Taro 版本  1.3.0
 - Node.js 版本 8.9.4
 - 报错平台 weapp

**补充信息**
h5版本是可以成功的
traverseObjectNode方法执行时，通过node.value.properties获取的为undefined，所以后续forEach报错了

**Comment by zjxpcyc** [comment]
我也出现了类似的错误

**Comment by Chen-jj** [comment]
缺少 demo
