### ISSUE TITLE
can't find module : ../node_modules/@tarojs/taro-weapp/index.js

### ISSUE THREAD

**Issue by cikichen** [NervJS/taro#3395]
**问题描述**

使用CLI创建云开发模板

```
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Less
? 请选择模板 云开发模板
```

用微信开发者工具打开client报错

**报错信息**

```
thirdScriptError 
 sdk uncaught third Error 
 can't find module : ../node_modules/@tarojs/taro-weapp/index.js 
 Error: can't find module : ../node_modules/@tarojs/taro-weapp/index.js
    at http://127.0.0.1:42348/appservice/__dev__/WAService.js:1:1110388
    at http://127.0.0.1:42348/appservice/app.js:9:14
    at require (http://127.0.0.1:42348/appservice/__dev__/WAService.js:1:1111566)
    at <anonymous>:1:1
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:42348/appservice/appservice?t=1560310068822:1153:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:42348/appservice/appservice?t=1560310068822:1165:20)
```

**系统信息**
```
 Taro v1.3.0


  Taro CLI 1.3.0 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
    npmPackages:
      @tarojs/components: 1.3.0 => 1.3.0
      @tarojs/plugin-babel: 1.3.0 => 1.3.0
      @tarojs/plugin-csso: 1.3.0 => 1.3.0
      @tarojs/plugin-less: 1.3.0 => 1.3.0
      @tarojs/plugin-uglifyjs: 1.3.0 => 1.3.0
      @tarojs/router: 1.3.0 => 1.3.0
      @tarojs/taro: 1.3.0 => 1.3.0
      @tarojs/taro-alipay: 1.3.0 => 1.3.0
      @tarojs/taro-h5: 1.3.0 => 1.3.0
      @tarojs/taro-swan: 1.3.0 => 1.3.0
      @tarojs/taro-tt: 1.3.0 => 1.3.0
      @tarojs/taro-weapp: ^1.3.0 => 1.3.0
      @tarojs/webpack-runner: 1.3.0 => 1.3.0
      eslint-config-taro: 1.3.0 => 1.3.0
      eslint-plugin-taro: 1.3.0 => 1.3.0
      nervjs: ^1.4.0 => 1.4.0
    npmGlobalPackages:
      typescript: 3.5.1
```

**Comment by jinjinjin0731** [comment]
看下文档[小程序云开发模板](https://nervjs.github.io/taro/docs/wxcloud.html)

> 1. 开发时，进入 client 目录，在此目录下运行相关编译预览或打包命令
> 2. 使用微信开发者工具调试项目，请将项目整个文件夹作为运行目录。 注意： 不是 client 中生成的 dist 文件夹
