### ISSUE TITLE
npm run dev:weapp 未将when拷贝到dist/npm 导致小程序无法预览

### ISSUE THREAD

**Issue by tongjun741** [NervJS/taro#340]
**问题描述**
npm run dev:weapp 未将when拷贝到dist/npm
使用微信开发者工具预览时报错：
``` module "npm/when/when.js" is not defined ```

使用npm run dev:h5 预览无此问题

**复现步骤**
```
taro init testWxApp1
cd testWxApp1
```

修改 src/pages/index/index.js，增加：

```import when from 'when'```

render方法中增加：

```
when().then(()=>{
    console.log('when loaded');
});
```

保存并执行npm run dev:weapp

**期望行为**
控制台中应该打印出'when loaded'

**报错信息**

```
VM6833:1 thirdScriptError 
 sdk uncaught third Error 
 module "npm/when/when.js" is not defined 
 Error: module "npm/when/when.js" is not defined
    at require (http://127.0.0.1:14249/appservice/__dev__/WAService.js:19:7163)
    at http://127.0.0.1:14249/appservice/__dev__/WAService.js:19:7018
    at http://127.0.0.1:14249/appservice/app.js:17:13
    at require (http://127.0.0.1:14249/appservice/__dev__/WAService.js:19:7304)
    at http://127.0.0.1:14249/appservice/appservice?t=1531818011946:1151:9
```

**系统信息**

 - 操作系统: macOS 10.12.2
 - Taro 版本 v0.069
 - Node.js 版本 v8.9.2
- when: v3.6.4
- lodash: v4.17.10

**补充信息**
 同样方式引用 lodash 没有问题

初始化参数：
```
? 请输入项目介绍！ ddd
? 是否需要使用 TypeScript ？ No
? 请选择 CSS 预处理器（Sass/Less/Stylus） Less
? 请选择模板 默认模板
```

**Comment by shenghanqin** [comment]
@luckyadam 这个问题未来还解决吗？
