### ISSUE TITLE
taro + ts + echarts 编译报错‘echarts.js’编译失败

### ISSUE THREAD

**Issue by misszoessmile** [NervJS/taro#3404]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
项目的技术框架是Taro+TypeScript，引入echarts.js的时候报‘echarts.js编译失败’的错。

**复现步骤**
项目的技术框架是taro+TypeScript，引入使用echarts-for-weixin组件，按说明文档正确引入。如图：
![image](https://user-images.githubusercontent.com/35720631/59341613-ca1c9080-8d3a-11e9-8171-4a1de2b943a4.png)

**报错信息**
微信开发者工具报错如下：
![image](https://user-images.githubusercontent.com/35720631/59341425-66926300-8d3a-11e9-8da6-48f0a4e81c59.png)
Taro报错如下：
![image](https://user-images.githubusercontent.com/35720631/59341028-ab69ca00-8d39-11e9-8ce4-e04e6a4bfe28.png)
错误  编译失败  src\report\components\ec-canvas\echarts.js
{ TypeError: unknown: Property id of VariableDeclarator expected node to be of a type ["LVal"] but instead got "NumericLiteral"
    at Object.validate (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-types\lib\definitions\index.js:109:19)
    at Object.validate (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-types\lib\index.js:505:9)
    at NodePath._replaceWith (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\replacement.js:176:7)
    at NodePath.replaceWith (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\replacement.js:160:8)
    at replaceAndEvaluateNode (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-plugin-transform-define\lib\index.js:117:12)
    at processNode (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-plugin-transform-define\lib\index.js:143:5)
    at PluginPass.Identifier (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-plugin-transform-define\lib\index.js:23:9)
    at newFn (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:48:17) _babel: true }

**系统信息**

![image](https://user-images.githubusercontent.com/35720631/59341084-cccab600-8d39-11e9-9890-dc9e49979450.png)

**Comment by misszoessmile** [comment]
盼复！谢谢！

**Comment by luckyadam** [comment]
升级到 1.3.0 试试呢

**Comment by misszoessmile** [comment]
> 升级到 1.3.0 试试呢

早上好！升级到1.3.0，依然编译不通过。报错信息一致。如下：
![image](https://user-images.githubusercontent.com/35720631/59400659-c7697c00-8dca-11e9-84b8-329dcda5a3b8.png)

版本信息：
![image](https://user-images.githubusercontent.com/35720631/59400704-ef58df80-8dca-11e9-9c04-17e05aa6edf3.png)

**Comment by misszoessmile** [comment]
> 升级到 1.3.0 试试呢

@luckyadam
