### ISSUE TITLE
小程序1.30 beta 版 类函数式组件下的 jsx元素无法根据this.state条件语句改变

### ISSUE THREAD

**Issue by imlinqin** [NervJS/taro#3446]
**问题描述**
小程序 1.30 beta 版  类函数式组件下的 jsx 元素无法根据this.state的状态改变

**复现步骤**
[复现问题的步骤]
1.引入本页面并 npm run dev:weapp
2.对比本页面内容状态变化

```js


 ```js
import Taro, { Component } from '@tarojs/taro'
import { View, Text, ScrollView, Image, Input, Textarea } from '@tarojs/components'
export default class InputView extends Component {
  constructor(props) {
    super(props)
    this.state = {
      isText:  false,
    }
  }

  static defaultProps = {
    isText: false
  }

  componentDidMount() {

    setTimeout(() => {
        this.setState({
          isText:true
        })
    }, 5000);

  }

  //由于 1.30 beta 版  类函数式组件下的 jsx 无法根据this.state的状态改变
  renderRight() {
    console.log('isTextState', this.state.isTextState) //打印 isTextState 是有变化的
    return <View>
      <Text>renderRight() 状态</Text>
      {this.state.isText ? <View><Text>isText</Text></View> : <View><Text>为空</Text></View>}
    </View>
  }
  render() {
    let renderRight = <View>
      <Text>renderRight 状态</Text>
      {this.state.isText ? <View><Text>isText</Text></View> : <View><Text>null</Text></View>}
    </View>

    return <View
      >
      {/* this.renderRight() 组件下不会根据 this.sate状态 渲染更新 */}
       {this.renderRight()}

       {/* 渲染更新正常  */}
       {renderRight}
      </View>
  }
}
 ```

```

**期望行为**
修复类函数式组件下jsx元素根据this.state条件语句显示

**报错信息**

无报错信息

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOS 10.14.2]
 - Taro 版本 [Taro v1.3.0]
 - Node.js 版本 [8.11.1]
 - 报错平台 [weapp]

Taro v1.3.0
 Taro CLI 1.3.0 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.1 - /usr/local/bin/node
      Yarn: yarn install v0.27.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.92s. - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.0-beta.8 => 1.3.0-beta.8 
      @tarojs/mobx: 1.3.0-beta.8 => 1.3.0-beta.8 
      @tarojs/mobx-h5: 1.3.0-beta.8 => 1.3.0-beta.8 
      @tarojs/mobx-rn: 1.3.0-beta.8 => 1.3.0-beta.8 
      @tarojs/plugin-babel: 1.3.0-beta.8 => 1.3.0-beta.8 
      @tarojs/plugin-csso: 1.3.0-beta.8 => 1.3.0-beta.8 
      @tarojs/plugin-sass: 1.3.0-beta.8 => 1.3.0-beta.8 
      @tarojs/plugin-uglifyjs: 1.3.0-beta.8 => 1.3.0-beta.8 
      @tarojs/rn-runner: 1.3.0-beta.8 => 1.3.0-beta.8 
      @tarojs/router: 1.3.0-beta.8 => 1.3.0-beta.8 
      @tarojs/taro: 1.3.0-beta.8 => 1.3.0-beta.8 
      @tarojs/taro-alipay: 1.3.0-beta.8 => 1.3.0-beta.8 
      @tarojs/taro-h5: 1.3.0-beta.8 => 1.3.0-beta.8 
      @tarojs/taro-swan: 1.3.0-beta.8 => 1.3.0-beta.8 
      @tarojs/taro-tt: 1.3.0-beta.8 => 1.3.0-beta.8 
      @tarojs/taro-weapp: 1.3.0-beta.8 => 1.3.0-beta.8 
      @tarojs/webpack-runner: 1.3.0-beta.8 => 1.3.0-beta.8 
      eslint-config-taro: 1.3.0-beta.8 => 1.3.0-beta.8 
      eslint-plugin-taro: 1.3.0-beta.8 => 1.3.0-beta.8 
      nervjs: ^1.3.9 => 1.3.13 
      react-native: ^0.59.9 => 0.59.9 
    npmGlobalPackages:
      typescript: 2.1.6

**补充信息**
只测试 weapp 平台

**Comment by yuche** [comment]
更新下 1.3.1

**Comment by imlinqin** [comment]
> 更新下 1.3.1

taro升级到1.3.1 时，本地的依赖版本号要怎么填写 ，是修改成1.3.1-beta.0 吗

**Comment by imlinqin** [comment]
> 更新下 1.3.1

我的项目是 taro mobx 升级到 1.3.1 ，导致报错，本地依赖版本是否改成相应的版本号
 ```js
sdk uncaught third Error 
 Cannot read property 'Provider' of undefined 
 TypeError: Cannot read property 'Provider' of undefined
    at http://127.0.0.1:62019/appservice/app.js:29:26
    at require (http://127.0.0.1:62019/appservice/__dev__/WAService.js:1:1113027)
    at <anonymous>:1:1
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:62019/appservice/appservice?t=1560740824333:1904:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:62019/appservice/appservice?t=1560740824333:1916:20)
 ```js

**Comment by yuche** [comment]
那你就用 1.3.0 吧，
在 renderXX 中使用 state 和 props，先解构出来再用。
```js
const { isTextState } = this.state
```

**Comment by xuzhibin** [comment]
升级到1.3.1后，我也是报这个错 
Cannot read property 'Provider' of undefined

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/8d99a2bacb1624b12de1f10c9b3fec2df75ff31f and https://github.com/NervJS/taro/commit/8d99a2bacb1624b12de1f10c9b3fec2df75ff31f
