### ISSUE TITLE
@taro/cli "resolve_npm_files", 自定义组件库，提示dist/weapp/index不存在

### ISSUE THREAD

**Issue by nevernet** [NervJS/taro#3449]
```
(node:57023) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '<省略全路径>/node_modules/@jd/apis/dist/weapp/index'
    at Object.openSync (fs.js:447:3)
    at Object.readFileSync (fs.js:349:35)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:175:30
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:3:12)
    at recursiveRequire (/usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:174:12)
    at CallExpression (/usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:148:41)
    at NodePath._call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:76:18)
(node:57023) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:57023) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

实际上 /node_modules/@jd/apis/dist/weapp/index.ts(`注意，是index.ts文件，该文件是真实存在的。`)

taro info: 

```

  Taro CLI 1.3.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.6.2 - /usr/local/bin/zsh
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 1.3.1 => 1.3.1 
      @tarojs/components: 1.3.1 => 1.3.1 
      @tarojs/plugin-babel: 1.3.1 => 1.3.1 
      @tarojs/plugin-csso: 1.3.1 => 1.3.1 
      @tarojs/plugin-sass: 1.3.1 => 1.3.1 
      @tarojs/plugin-uglifyjs: 1.3.1 => 1.3.1 
      @tarojs/router: 1.3.1 => 1.3.1 
      @tarojs/taro: 1.3.1 => 1.3.1 
      @tarojs/taro-alipay: 1.3.1 => 1.3.1 
      @tarojs/taro-h5: 1.3.1 => 1.3.1 
      @tarojs/taro-swan: 1.3.1 => 1.3.1 
      @tarojs/taro-tt: 1.3.1 => 1.3.1 
      @tarojs/taro-weapp: 1.3.1 => 1.3.1 
      @tarojs/webpack-runner: 1.3.1 => 1.3.1 
      eslint-config-taro: 1.3.1 => 1.3.1 
      eslint-plugin-taro: 1.3.1 => 1.3.1 
      nerv-devtools: ^1.4.1 => 1.4.1 
      nervjs: ^1.4.1 => 1.4.1 
    npmGlobalPackages:
      typescript: 3.3.3333
```

**Comment by nevernet** [comment]
@luckyadam @yuche 帮忙给点意见，😄

**Comment by only4ly** [comment]
我也中招了

**Comment by DBvc** [comment]
有解决方案了吗
