### ISSUE TITLE
升级到1.3.1之后，执行npm run dev:h5 报错

### ISSUE THREAD

**Issue by cllgeek** [NervJS/taro#3454]
**问题描述**
[问题描述：升级到1.3.1之后，执行npm run dev:h5 报错

**复现步骤**
[复现问题的步骤]
执行npm run dev:h5 报错

```js
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1251:7)
    at Object.exports.default (/Users/chenlili/weixin/taro-xyly6/node_modules/@tarojs/webpack-runner/dist/config/base.conf.js:14:22)
    at Object.default_1 [as default] (/Users/chenlili/weixin/taro-xyly6/node_modules/@tarojs/webpack-runner/dist/config/dev.conf.js:9:38)
    at Promise (/Users/chenlili/weixin/taro-xyly6/node_modules/@tarojs/webpack-runner/dist/index.js:62:48)
    at new Promise (<anonymous>)
    at Object.<anonymous> (/Users/chenlili/weixin/taro-xyly6/node_modules/@tarojs/webpack-runner/dist/index.js:54:12)
    at Generator.next (<anonymous>)
    at /Users/chenlili/weixin/taro-xyly6/node_modules/@tarojs/webpack-runner/dis
```

**期望行为**
能正常npm run dev:h5

**报错信息**

<img width="567" alt="WX20190617-135339@2x" src="https://user-images.githubusercontent.com/15187909/59581464-91e4cb80-9107-11e9-9812-b63d07c7ffef.png">

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 Taro CLI 1.3.1 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.9.3 - ~/.nvm/versions/node/v8.9.3/bin/node
      Yarn: 1.7.0 - ~/.nvm/versions/node/v8.9.3/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v8.9.3/bin/npm

**Comment by nevernet** [comment]
根据你这个错误提示，应该是某个地方的Path输入错误了

**Comment by cllgeek** [comment]
@nevernet 那为什么之前的版本不会报这个错呢，应该是工具内部出错了

**Comment by nevernet** [comment]
@cllgeek 估计是cli升级后导致的不兼容等等。看不到你的代码，无法调试

**Comment by cllgeek** [comment]
@nevernet 你看webpack-runner 哪里出错，  问一下，你们升级后没这个问题吗

**Comment by nevernet** [comment]
@cangku 我目前1.3.0-beta5下的h5项目编译还没这个问题，正在升级1.3.1

**Comment by nevernet** [comment]
@cllgeek 你最好 跟 #3458 一样，创建一个测试项目

**Comment by luckyadam** [comment]
最好提供一个 demo 吧，这样看不出什么问题

**Comment by Littly** [comment]
看起来还是cli和项目依赖没有匹配上的问题

**Comment by cllgeek** [comment]
@Littly 对，就是本地的node_modules 没有更新版本的问题，重新npm install 就可以了， 所以这里建议@luckyadam 在文档补充，执行$ taro update project 之后，再执行npm install

**Comment by nevernet** [comment]
@cllgeek 如果升级了node的版本，node_modules是必须删除再重新安装的。 

`taro update project ` 其实已经包含了npm install的过程。
