### ISSUE TITLE
Cannot read property '_$indexKey' of undefined TypeError: Cannot read property '_$indexKey' of undefined

### ISSUE THREAD

**Issue by thisSillyCow** [NervJS/taro#3495]
**问题描述**
<View className='novelBookFourMutiLine' >
{
	bookList.map((bookInfoItem, index) => {
		return (
				<View className='bookItem' onClick={() => { console.log('1111111') }}></View>
			)
	})
}
</View>
加上onClick事件就报 _$indexKey 为undefined，不加上onClick事件就没事

undefined:4: TypeError: Cannot read property '_$indexKey' of undefined
TypeError: Cannot read property '_$indexKey' of undefined
    at e.dataEOnclickAA (eval at Sn (unknown source), <anonymous>:6570:72)
    at Pi.get (<anonymous>:4:14335)
    at new Pi (<anonymous>:4:14262)
    at qr (<anonymous>:2:19523)
    at Jr (<anonymous>:2:19359)
    at Wr (<anonymous>:2:19302)
    at Dr (<anonymous>:2:18422)
    at Cr (<anonymous>:2:14617)
    at cn (<anonymous>:2:24654)
    at Vr (<anonymous>:2:21468)
com.eclipsesource.v8.V8ScriptExecutionException
	at com.eclipsesource.v8.V8._executeFunction(Native Method)
	at com.eclipsesource.v8.V8.executeFunction(SourceFile:1125)
	at com.eclipsesource.v8.V8Object.executeFunction(SourceFile:370)
	at org.hapjs.render.jsruntime.JsBridgeTimer$a.run(SourceFile:60)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by yuche** [comment]
你需要把整段代码贴出来，就目前这部分还是不能复现

**Comment by thisSillyCow** [comment]
这是代码截图
![SJB78ZZ(R8J`6~RZ`(OX675](https://user-images.githubusercontent.com/30546278/59987023-d1fa0000-966b-11e9-9b1f-e7a462b5b63f.png)
目前这边的测试代码：
import Taro, { Component, Config } from '@tarojs/taro'
import { View, Text, Image } from '@tarojs/components'
import './index.scss'
export default class Home extends Component {
	constructor(props) {
		super(props)
		this.state = {
			bookList: [{ bookId: 1 }, { bookId: 2 }, { bookId: 3 }, { bookId: 4 }],
		}
	}
	componentWillMount() { }
	componentWillUnmount() { }
	componentDidShow() { }
	componentDidHide() { }
	componentDidMount() { }
	render() {
		const bookList = this.state
		return (
			<View className='novelBookFourMutiLine' >
				{bookList.map((bookInfoItem) => {
					return (
					<View className='bookItem' onClick={() => { console.log('1111111') }}></View>
						)
					})
				}
			</View>
		)
	}
}
这是报错的信息
![F79B0577178793E41884B9C004590F40](https://user-images.githubusercontent.com/30546278/59987027-d6261d80-966b-11e9-9cd8-d3e3d4a3ebf6.jpg)

**Comment by yuche** [comment]
你的贴出来语法错了，return 后面多了一对花括号。升级你 taro cli 可以避免 indexKey 的问题

**Comment by thisSillyCow** [comment]
我试试看啊 我根据跟return 后面多了一对花括号没有关系的 我当前的版本是Taro v1.3.2  贴出来语法有些view被清空了 你看我的截图 那些view没有被清空过

**Comment by yuche** [comment]
你的代码写错了：
```
const bookList = this.state
```
state 是一个对象，原型上没有 map 方法

**Comment by thisSillyCow** [comment]
写错了？  那我这样子写也不行啊
![RYURP3%V) 17YW9M(`BIBKS](https://user-images.githubusercontent.com/30546278/59989525-243e1f80-9672-11e9-8110-1f99aa603915.png)
请你在重新建个项目试一下 版本更新也是没有用啊

**Comment by thisSillyCow** [comment]
我这个是快应用项目

**Comment by yuche** [comment]
> 我这个是快应用项目

你这样报什么错？

**Comment by thisSillyCow** [comment]
undefined:4: TypeError: Cannot read property '$indexKey' of undefined
TypeError: Cannot read property '$indexKey' of undefined
at e.dataEOnclickAA (eval at Sn (unknown source), :6570:72)
at Pi.get (:4:14335)
at new Pi (:4:14262)
at qr (:2:19523)
at Jr (:2:19359)
at Wr (:2:19302)
at Dr (:2:18422)
at Cr (:2:14617)
at cn (:2:24654)
at Vr (:2:21468)
com.eclipsesource.v8.V8ScriptExecutionException
at com.eclipsesource.v8.V8._executeFunction(Native Method)
at com.eclipsesource.v8.V8.executeFunction(SourceFile:1125)
at com.eclipsesource.v8.V8Object.executeFunction(SourceFile:370)
at org.hapjs.render.jsruntime.JsBridgeTimer$a.run(SourceFile:60)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:207)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by yuche** [comment]
你编译出来的代码是怎么样?

**Comment by thisSillyCow** [comment]
我把编译之后的代码提交在这个文本里面了 你可以看一下   taro cli  更新了也是没有解决问题

[new 2.txt](https://github.com/NervJS/taro/files/3319097/new.2.txt)

**Comment by yuche** [comment]
先不要在快应用里写箭头函数把

**Comment by thisSillyCow** [comment]
不用写箭头函数是没有问题的嘛

**Comment by thisSillyCow** [comment]
![ZW$AF Y$G`Z6`A)$9$RI1}W](https://user-images.githubusercontent.com/30546278/59994757-9ec56a00-9687-11e9-9334-32ef232c0850.png)
也是不行啊  你们尽快抽时间解决这个问题吧

**Comment by yuche** [comment]
写一个类函数的引用

**Comment by thisSillyCow** [comment]
可以提供一个例子嘛 我这边不是怎么写比较好

**Comment by yuche** [comment]
```jsx
import Taro, { Component, Config } from '@tarojs/taro'
import { View, Text, Image } from '@tarojs/components'
import './index.scss'
export default class Home extends Component {
  constructor (props) {
    super(props)
    this.state = {
      bookList: [{ bookId: 1 }, { bookId: 2 }, { bookId: 3 }, { bookId: 4 }]
    }
  }
 fuck () {
    console.log('ss')
  }
  render () {
    const bookList = this.state
    return bookList.map(bookInfoItem => {
      return <View className='bookItem' onClick={this.fuck} />
    })
  }
}

```

**Comment by thisSillyCow** [comment]
这样子是解决了 报错的问题 但是点击事件还是没有啊

**Comment by yuche** [comment]
你什么内容都没渲染吧

**Comment by thisSillyCow** [comment]
是我的问题  确实没有内容渲染  那现在还有一个问题 就是我怎么把我的数据传过去啊
我遍历的时候 有个id 我要把这个id传给这个方法  但是现在 onClick={this.fuck} 这种写法是没有没有传参的 你有什么好的意见嘛

**Comment by yuche** [comment]
文档搜索事件

**Comment by thisSillyCow** [comment]
好的 谢谢啦 我这边实现了  还有一个 issues 请帮我看一下啊
