### ISSUE TITLE
使用了Taro.memo的组件编译成小程序出错

### ISSUE THREAD

**Issue by loveonelong** [NervJS/taro#3527]
**问题描述**

使用了Taro.memo的hooks组件编译成小程序出错，编译为h5没有问题.

**复现步骤**

```javascript
const PlayerList = Taro.memo(props => (<View />))
export default PlayerList
```

**报错信息**

```
错误  组件错误  组件PlayerList路径错误，请检查！（可能原因是导出的组件名不正确）
错误  页面编译  页面/Users/onelong/work/ilisten-taro-pack/src/pages/playing/index编译失败！
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.relative (path.js:1171:5)
    at pageDepComponents.forEach.depComponent (/usr/local/lib/node_modules/@tarojs/cli/dist/mini/page.js:172:84)
    at Array.forEach (<anonymous>)
    at componentMap.forEach.component (/usr/local/lib/node_modules/@tarojs/cli/dist/mini/page.js:163:47)
    at Array.forEach (<anonymous>)
    at realComponentsPathList.forEach.component (/usr/local/lib/node_modules/@tarojs/cli/dist/mini/page.js:162:54)
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/mini/page.js:159:40
    at Generator.next (<anonymous>)
```
**系统信息**
> Taro v1.3.3

**Comment by yuche** [comment]
Memo 只能传入一个函数式组件的引用

**Comment by loveonelong** [comment]
了解
