### ISSUE TITLE
使用Node12.4.0编译后，如果使用Redux的Provider会报错

### ISSUE THREAD

**Issue by LinYouYuan** [NervJS/taro#3531]
```
thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'Provider' of undefined 
 TypeError: Cannot read property 'Provider' of undefined
    at http://127.0.0.1:39784/appservice/app.js:39:25
    at require (http://127.0.0.1:39784/appservice/__dev__/WAService.js:1:1113027)
    at <anonymous>:1:1
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:39784/appservice/appservice?t=1561444547753:1176:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:39784/appservice/appservice?t=1561444547753:1188:20)
console.error @ VM4284:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1561444547753:1135
window.onerror @ VM4284:1
scriptLoaded @ appservice?t=1561444547753:1176
script.onload @ appservice?t=1561444547753:1188
```

**Comment by yuche** [comment]
得带上复现

**Comment by LinYouYuan** [comment]
复现步骤 
1、使用Node12以上的版本
2、`npm run dev:weapp`
3、使用了redux,在目录src/app里如下添加Provider
```js
<Provider store={store}>
        <Index />
 </Provider>
```
会报错，报错信息如下
```
thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'Provider' of undefined 
 TypeError: Cannot read property 'Provider' of undefined
    at http://127.0.0.1:39784/appservice/app.js:39:25
    at require (http://127.0.0.1:39784/appservice/__dev__/WAService.js:1:1113027)
    at <anonymous>:1:1
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:39784/appservice/appservice?t=1561444547753:1176:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:39784/appservice/appservice?t=1561444547753:1188:20)
console.error @ VM4284:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1561444547753:1135
window.onerror @ VM4284:1
scriptLoaded @ appservice?t=1561444547753:1176
script.onload @ appservice?t=1561444547753:1188
```

**Comment by LinYouYuan** [comment]
如果使用低版本的Node不会出现此问题

**Comment by Garfield550** [comment]
建议还是用 LTS 版本比较省心。

> Production applications should only use Active LTS or Maintenance LTS releases.

Ref: https://nodejs.org/en/about/releases/

**Comment by summer-yyyn** [comment]
node v8.9.1 出现同样问题

**Comment by chm1n9** [comment]
node v10.16.0 也出现这个问题，应该不是node原因

**Comment by summer-yyyn** [comment]
windows node v10.14.2 正常编译，Mac 同样版本同样代码，还是报错

**Comment by yuche** [comment]
具体 taro 哪个版本，报错的代码是哪一行

**Comment by summer-yyyn** [comment]
Taro v1.3.2  
src/app.js  中

`
render () {
    return (
      <Provider store={store}>
        <Index />
      </Provider>
    )
  }
`
报错信息

`
VM6914:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'Provider' of undefined 
 TypeError: Cannot read property 'Provider' of undefined
    at http://127.0.0.1:17515/appservice/app.js:54:25
    at require (http://127.0.0.1:17515/appservice/__dev__/WAService.js:1:912851)
    at <anonymous>:1:1
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:17515/appservice/appservice?t=1561516610390:6374:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:17515/appservice/appservice?t=1561516610390:6386:20)
console.error @ VM6914:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1561516610390:5622
window.onerror @ VM6914:1
scriptLoaded @ appservice?t=1561516610390:6374
script.onload @ appservice?t=1561516610390:6386

`

**Comment by summer-yyyn** [comment]
Taro v1.3.2 
src / app.js中
```
render () {
    return ( <Provider store={store}> <Index /> </Provider> ) 
}
```

报错信息

```
VM6914：1 thirdScriptError 
sdk未捕获第三个错误
无法读取未定义的属性'Provider'TypeError 
：无法
在http://127.0.0.1:17515/appservice/app.js:54:25
处读取undefined的属性'Provider' （http://127.0.0.1:17515/appservice/__dev__/WAService.js:1:912851）
在：1：1 
在HTMLScriptElement.scriptLoaded（http://127.0.0.1:17515/appservice/appservice?t=1561516610390： 6374：21）
在HTMLScriptElement.script.onload（http://127.0.0.1:17515/appservice/appservice?t=1561516610390:6386:20）
console.error @ VM6914：1 
（匿名）@ WAService.js：1 
（匿名）@ WAService.js：1
e @ appservice？t = 1561516610390：5622 
window.onerror @ VM6914：1 
scriptLoaded @ appservice？t = 1561516610390：6374 
script.onload @ appservice？t = 1561516610390：6386
```

**Comment by yuche** [comment]
升级到最新版本再看看

**Comment by summer-yyyn** [comment]
taro v1.3.4 还是不行

**Comment by yuche** [comment]
还是没办法复现，能做一个复现仓库吗

**Comment by LinYouYuan** [comment]
之前就mac会出现，现在删除package-lock.json，把有关taro的版本都切换到1.3.3，已经解决了

**Comment by yuche** [comment]
保证项目依赖和 cli 版本一致，应该不会出现这个问题。

**Comment by Yill625** [comment]
需要Taro版本与项目Taro版本保持一致

**Comment by hnliyuan** [comment]
node v10.16.0 同出现该问题 taro版本v1.3.5

**Comment by TheHappyLeon** [comment]
node v8.12.0 同出现该问题 taro版本v1.3.6

**Comment by qianyanyan** [comment]
怎么保持一致啊，
