### ISSUE TITLE
app.js的config里面的tabbar编译成rn时候有icon路径引用问题

### ISSUE THREAD

**Issue by Slngle** [NervJS/taro#3588]
**问题描述**
 app.js的config里面的tabbar编译成rn时候有icon路径引用问题,显示找不到图片

**复现步骤**

代码如下
```js
config:{
    tabBar: {
      color: '#666',
      selectedColor: '#b4282d',
      backgroundColor: '#fafafa',
      borderStyle: 'black',
      list: [
        {
          pagePath: 'pages/home-page/index',
          iconPath: './static/images/icon_fenlei@2x.png',
          selectedIconPath: './static/images/icon_fenlei_pre@2x.png',
          text: '首页'
        },
        {
          pagePath: 'pages/activity-list/index',
          iconPath: './static/images/icon_fenlei@2x.png',
          selectedIconPath: './static/images/icon_fenlei_pre@2x.png',
          text: '分类'
        }
      ]
    }
}
```
在小程序上完全正常，在ios上打bundle的时候抛出异常
```js
{
  "originModulePath": "/Users/gushunnae/Documents/WAIBAO/qua-app/rn_temp/app.js",
  "targetModuleName": "././static/images/icon_fenlei_pre@2x.png",
  "message": "Unable to resolve module `././static/images/icon_fenlei_pre@2x.png` from `/Users/gushunnae/Documents/WAIBAO/qua-app/rn_temp/app.js`: The module `././static/images/icon_fenlei_pre@2x.png` could not be found from `/Users/gushunnae/Documents/WAIBAO/qua-app/rn_temp/app.js`. Indeed, none of these files exist:\n\n  * `icon_fenlei_pre@2x.png`\n  * `/Users/gushunnae/Documents/WAIBAO/qua-app/rn_temp/static/images/icon_fenlei_pre@2x.png/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`",
  "errors": [
    {
      "description": "Unable to resolve module `././static/images/icon_fenlei_pre@2x.png` from `/Users/gushunnae/Documents/WAIBAO/qua-app/rn_temp/app.js`: The module `././static/images/icon_fenlei_pre@2x.png` could not be found from `/Users/gushunnae/Documents/WAIBAO/qua-app/rn_temp/app.js`. Indeed, none of these files exist:\n\n  * `icon_fenlei_pre@2x.png`\n  * `/Users/gushunnae/Documents/WAIBAO/qua-app/rn_temp/static/images/icon_fenlei_pre@2x.png/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`"
    }
  ],
  "name": "Error",
  "stack": "Error: Unable to resolve module `././static/images/icon_fenlei_pre@2x.png` from `/Users/gushunnae/Documents/WAIBAO/qua-app/rn_temp/app.js`: The module `././static/images/icon_fenlei_pre@2x.png` could not be found from `/Users/gushunnae/Documents/WAIBAO/qua-app/rn_temp/app.js`. Indeed, none of these files exist:\n\n  * `icon_fenlei_pre@2x.png`\n  * `/Users/gushunnae/Documents/WAIBAO/qua-app/rn_temp/static/images/icon_fenlei_pre@2x.png/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`\n    at ModuleResolver.resolveDependency (/Users/gushunnae/Documents/WAIBAO/qua-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:161:851)\n    at ResolutionRequest.resolveDependency (/Users/gushunnae/Documents/WAIBAO/qua-app/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:91:16)\n    at DependencyGraph.resolveDependency (/Users/gushunnae/Documents/WAIBAO/qua-app/node_modules/metro/src/node-haste/DependencyGraph.js:272:4579)\n    at dependencies.map.relativePath (/Users/gushunnae/Documents/WAIBAO/qua-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:376:19)\n    at Array.map (<anonymous>)\n    at resolveDependencies (/Users/gushunnae/Documents/WAIBAO/qua-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:374:16)\n    at /Users/gushunnae/Documents/WAIBAO/qua-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:212:33\n    at Generator.next (<anonymous>)\n    at step (/Users/gushunnae/Documents/WAIBAO/qua-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:313)\n    at /Users/gushunnae/Documents/WAIBAO/qua-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:473"
}
```
我的项目名称为qua-app

我的项目路径为
WAIBAO => qua-app

打包壳子taro-native-shell的路径为
WAIBAO => taro-native-shell
Appdelegate.m里面没动过 如下

```js
jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"rn_temp/index" fallbackResource:nil];
```

**期望行为**
期望可以像小程序一样正常展示tabbar

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
  - Taro CLI 1.3.2 environment info:
    - System:
      - OS: macOS 10.14.1
      - Shell: 5.3 - /bin/zsh
    - Binaries:
      - Node: 11.14.0 - /usr/local/bin/node
      - Yarn: 1.16.0 - /usr/local/bin/yarn
      - npm: 6.9.0 - /usr/local/bin/npm

**补充信息**
这个问题应该是路径的原因 但是我实在不知道问题出在哪里

**Comment by Slngle** [comment]
我了个草草啊 这个我把文件夹的名称 static换成assets就好了 天啊 我都快怀疑人生了

**Comment by Slngle** [comment]
蛋疼 是图片文件名称有@2x.png 就有问题

**Comment by Pines-Cheng** [comment]
RN 是不支持路径中包含 @2x  这样的字符串。
