### ISSUE TITLE
app.js 使用函数式模块，config 配置失败

### ISSUE THREAD

**Issue by demohi** [NervJS/taro#3596]
**问题描述**
app.js 使用函数式组件 & hooks，config 配置失败

**复现步骤**
[复现问题的步骤]
将 app.js 改造为下面代码

```js
import Taro, { useEffect } from "@tarojs/taro";
import Index from "./pages/index";

import "./app.scss";

function App() {
  useEffect(() => {
    Taro.cloud.init();
  }, []);
  return <Index />;
}
App.config = {
  pages: ["pages/index/index"],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "WeChat",
    navigationBarTextStyle: "black"
  },
  cloud: true
};

Taro.render(<App />, document.getElementById("app"));


```

**期望行为**
config 可以正常被构建至 app.json

**报错信息**
```
(node:64149) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:207:11)
    at Object.checksum (/Users/demohi/.nvs/node/10.15.3/x64/lib/node_modules/@tarojs/cli/dist/util/index.js:224:22)
    at Object.<anonymous> (/Users/demohi/.nvs/node/10.15.3/x64/lib/node_modules/@tarojs/cli/dist/mini/watch.js:54:29)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/demohi/.nvs/node/10.15.3/x64/lib/node_modules/@tarojs/cli/dist/mini/watch.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:64149) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:64149) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

app.json为空

**系统信息**
```
Taro CLI 1.3.4 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvs/default/bin/node
      npm: 6.4.1 - ~/.nvs/default/bin/npm
    npmPackages:
      @tarojs/components: 1.3.4 => 1.3.4 
      @tarojs/plugin-babel: 1.3.4 => 1.3.4 
      @tarojs/plugin-csso: 1.3.4 => 1.3.4 
      @tarojs/plugin-sass: 1.3.4 => 1.3.4 
      @tarojs/plugin-uglifyjs: 1.3.4 => 1.3.4 
      @tarojs/router: 1.3.4 => 1.3.4 
      @tarojs/taro: 1.3.4 => 1.3.4 
      @tarojs/taro-alipay: 1.3.4 => 1.3.4 
      @tarojs/taro-h5: 1.3.4 => 1.3.4 
      @tarojs/taro-swan: 1.3.4 => 1.3.4 
      @tarojs/taro-tt: 1.3.4 => 1.3.4 
      @tarojs/taro-weapp: 1.3.4 => 1.3.4 
      @tarojs/webpack-runner: 1.3.4 => 1.3.4 
      eslint-config-taro: 1.3.4 => 1.3.4 
      eslint-plugin-taro: 1.3.4 => 1.3.4 
      nerv-devtools: ^1.4.0 => 1.4.3 
      nervjs: ^1.4.0 => 1.4.3 
```
**补充信息**

页面组件的 config 修改表现正常

**Comment by luckyadam** [comment]
app 比较特殊，暂时不要使用函数式组件

**Comment by Cuixote** [comment]
@luckyadam 3.x版本app可以使用函数式组件了吗

**Comment by Chen-jj** [comment]
> @luckyadam 3.x版本app可以使用函数式组件了吗

可以，Taro 3 是运行真实的 React
