### ISSUE TITLE
快应用 tabBar不可用，直接报错

### ISSUE THREAD

**Issue by uxwine** [NervJS/taro#3652]
**问题描述**
我在App中按照小程序的配置，配置好tabBar，就会报错；不配置tabBar就没问题。

**复现步骤**
1. 创建两个页面
2.配置tabBar

```js

tabBar: {
      color: "#8D9CAD",
      selectedColor: "#0083FF",
      backgroundColor: '#ffffff',
      borderStyle: "black",
      position: "bottom",
      list: [{
        pagePath: "pages/Home/index",
        text: "首页",
        iconPath: '/assets/images/bar/home.png',
        selectedIconPath: '/assets/images/bar/home_active@2x.png',
      }, {
        pagePath: "pages/Mine/index",
        text: "我的",
        iconPath: '/assets/images/bar/mine.png',
        selectedIconPath: '/assets/images/bar/mine_active@2x.png',
      }]
    }

```

**期望行为**
跟小程序一样，正常使用tabBar

**报错信息**

pages/Home/index.js:686: TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Xo.data (pages/Home/index.js:686:41)
    at new Xo (<anonymous>:1:99130)
    at <anonymous>:1:91703
    at Ro (<anonymous>:1:91949)
    at new Xo (<anonymous>:1:100978)
    at tr (<anonymous>:1:108673)
    at i (<anonymous>:1:110916)
    at Object../src/pages/Home/index.ux?uxType=page (pages/Home/index.js:6300:1)
    at __webpack_require__ (pages/Home/index.js:23:30)
    at ./node_modules/hap-toolkit/packager/lib/webpack/loader/json-loader.js!./node_modules/hap-toolkit/packager/lib/webpack/loader/style-loader.js?index=0&type=style!./node_modules/hap-toolkit/packager/lib/webpack/loader/fragment-loader.js?index=0&type=style!./src/npm/@tarojs/components-qa/src/components/taro-page/index.ux?uxType=comp.module.exports..taro-tabbar.borderStyle (pages/Home/index.js:87:18)
com.eclipsesource.v8.V8ScriptExecutionException
	at com.eclipsesource.v8.V8._executeVoidFunction(Native Method)
	at com.eclipsesource.v8.V8.executeVoidFunction(SourceFile:1133)
	at com.eclipsesource.v8.V8Object.executeVoidFunction(SourceFile:435)
	at org.hapjs.render.jsruntime.JsThread.b(SourceFile:664)
	at org.hapjs.render.jsruntime.JsThread.a(SourceFile:69)
	at org.hapjs.render.jsruntime.JsThread$a.handleMessage(SourceFile:240)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

Taro CLI 1.3.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.4 => 1.3.4 
      @tarojs/components-qa: ^1.3.4 => 1.3.4 
      @tarojs/plugin-babel: 1.3.4 => 1.3.4 
      @tarojs/plugin-csso: ^1.3.4 => 1.3.4 
      @tarojs/plugin-less: ^1.3.4 => 1.3.4 
      @tarojs/plugin-uglifyjs: 1.3.4 => 1.3.4 
      @tarojs/router: 1.3.4 => 1.3.4 
      @tarojs/taro: 1.3.4 => 1.3.4 
      @tarojs/taro-alipay: 1.3.4 => 1.3.4 
      @tarojs/taro-h5: 1.3.4 => 1.3.4 
      @tarojs/taro-quickapp: ^1.3.4 => 1.3.4 
      @tarojs/taro-swan: 1.3.4 => 1.3.4 
      @tarojs/taro-tt: 1.3.4 => 1.3.4 
      @tarojs/taro-weapp: 1.3.4 => 1.3.4 
      @tarojs/webpack-runner: 1.3.4 => 1.3.4 
      eslint-config-taro: 1.3.4 => 1.3.4 
      eslint-plugin-taro: 1.3.4 => 1.3.4 
      nerv-devtools: ^1.4.0 => 1.4.3 
      nervjs: ^1.4.0 => 1.4.3 
    npmGlobalPackages:
      typescript: 3.4.5

**补充信息**
对应错误：at Xo.data (pages/Home/index.js:686:41)的行数代码：

```js

if (this.tabbar && this.tabbar.list.length) {    //686 行
      this.tabbar.list.forEach(function (item) {
        if (item.pagePath === _this.pagepath) {
          showTabBar = true;
        }
      });
    }

```

**Comment by uxwine** [comment]
补充信息是编译之后的代码，应该是tabbar.list为空对象。但是我的App.tsx里面是配置了tabbar的

**Comment by luckyadam** [comment]
升级到 1.3.5
