### ISSUE TITLE
0.0.71 启动报错

### ISSUE THREAD

**Issue by nick121212** [NervJS/taro#366]
**问题描述**
使用0.0.71版本的cli创建完项目，执行 npm run dev:h5

![image](https://user-images.githubusercontent.com/5179901/43060185-6adfb320-8e82-11e8-9cd3-9eefa5449bc9.png)

**复现步骤**
[复现问题的步骤]
1. taro init weapp
2. cd weapp
3. npm run dev:h5

**期望行为**
项目正常启动

**报错信息**

创建  发现文件  src/pages/index/index.js
TypeError: Cannot read property '0' of undefined
    at new Parser (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babylon/lib/index.js:1577:45)
    at Object.parse (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babylon/lib/index.js:7305:10)
    at getAst (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-template/lib/index.js:29:21)
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-template/lib/index.js:53:24
    at exit (/usr/local/lib/node_modules/@tarojs/cli/src/h5.js:330:63)
    at NodePath._call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:108:19)from
    at exports.default (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-template/lib/index.js:12:11)
    at exit (/usr/local/lib/node_modules/@tarojs/cli/src/h5.js:330:24)
    at NodePath._call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/index.js:114:17)
    at traverse (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/index.js:79:12)

**系统信息**

 - 操作系统: [mac]
 - Taro 版本 [v.0.0.71]
 - Node.js 版本 [v8.11.1]

**Comment by NatPagle** [comment]
千万别升级，cli都报错了。

**Comment by Varavarforvar** [comment]
升级了微信开发工具编译报错、、、

**Comment by luckyadam** [comment]
hello，0.0.72 修复了这个问题~
