### ISSUE TITLE
条件渲染在小程序下报错

### ISSUE THREAD

**Issue by canvasT** [NervJS/taro#3663]
**问题描述**
根据[官方文档](https://taro-docs.jd.com/taro/docs/condition.html)，我使用变量存储元素，根据不同条件渲染不同的节点，在H5下正常，但是在小程序下报错。

**复现步骤**

```js
let icon = <View>1</View>;
  if (props.unExecutable) {
    icon = <View>2</View>;
  } else if (props.disabled) {
    icon = <View>3</View>;
  } else if (props.selectedValue === props.value) {
    icon = <View>4</View>;
  }

  return (
    <View className={
      classNames([rootClassName, classObject])
    } onClick={() => onClickOption(props)}>
      {icon}
    </View>
  );
```

**期望行为**
能够在小程序内正常运行

**报错信息**
- 编译错误
```
错误  组件编译  组件src/components/radio/option/index.tsx编译失败！
Error: 请将 JSX 赋值表达式初始化为 null，然后再进行 if 条件表达式赋值。
-----
  25 |     let icon = <View>1</View>;
  26 |     if (props.unExecutable) {
> 27 |         icon = <View>2</View>;
     |               ^^^^^^^^^^^^^^
  28 |     }
  29 |     else if (props.disabled) {
  30 |         icon = <View>3</View>;
    at Object.codeFrameError (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_transformer-wx@1.3.4@@tarojs/transformer-wx/lib/src/utils.js:365:12)
    at RenderParser.handleJSXInIfStatement (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_transformer-wx@1.3.4@@tarojs/transformer-wx/lib/src/render.js:1672:35)
    at JSXElement.handleJSXElement (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_transformer-wx@1.3.4@@tarojs/transformer-wx/lib/src/render.js:398:26)
    at RenderParser.handleJSXElement (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_transformer-wx@1.3.4@@tarojs/transformer-wx/lib/src/render.js:96:17)
    at JSXElement (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_transformer-wx@1.3.4@@tarojs/transformer-wx/lib/src/render.js:396:22)
    at NodePath._call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:108:19)
```
- 开发者工具console报错
![image](https://user-images.githubusercontent.com/1745014/60604281-ebc4e100-9de9-11e9-9d37-d870e5e8c7bc.png)

**系统信息**
```
Taro CLI 1.3.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.4 => 1.3.4 
      @tarojs/plugin-babel: 1.3.4 => 1.3.4 
      @tarojs/plugin-csso: 1.3.4 => 1.3.4 
      @tarojs/plugin-sass: 1.3.4 => 1.3.4 
      @tarojs/plugin-uglifyjs: 1.3.4 => 1.3.4 
      @tarojs/router: 1.3.4 => 1.3.4 
      @tarojs/taro: 1.3.4 => 1.3.4 
      @tarojs/taro-alipay: 1.3.4 => 1.3.4 
      @tarojs/taro-h5: 1.3.4 => 1.3.4 
      @tarojs/taro-swan: 1.3.4 => 1.3.4 
      @tarojs/taro-tt: 1.3.4 => 1.3.4 
      @tarojs/taro-weapp: 1.3.4 => 1.3.4 
      @tarojs/webpack-runner: 1.3.4 => 1.3.4 
      eslint-config-taro: 1.3.4 => 1.3.4 
      eslint-plugin-taro: 1.3.4 => 1.3.4 
      nerv-devtools: ^1.4.3 => 1.4.3 
      nervjs: ^1.4.3 => 1.4.3 
```

**Comment by yuche** [comment]
按照报错改不就完了吗

**Comment by canvasT** [comment]
@yuche 为什么必须设置为null？总得知道原因吧

**Comment by yuche** [comment]
因为 JSX 初始值不设置为 null，就会打乱 control flow graph 导致无法编译，你这样情况在 else 把初始值补上就行了

**Comment by canvasT** [comment]
OK，感谢
