### ISSUE TITLE
小程序内存栈溢出 RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by gebilaofan** [NervJS/taro#3680]
**问题描述**
小程序编译完之后，会出现内存栈溢出。吧所有页面所有组件关闭，重新编译执行，打开开发者工具就好了。但是过一会，再进到这个页面还是会报错。严重的情况会出现开发者工具卡死，或者是闪退问题。

**复现步骤**
点击列表，跳转到展示页面，页面进去了，但是报错。
网上说的 列表循环时，循环的key传入到this中，也不明白什么意思。

列表渲染代码
```js
  renderList() {

    const { orderList } = this.state
    return orderList.map(item => {
      let price = item.price
      let priceColor = 'width:50px;color:#ff8a00;'
      if (item.price == 0) {
        price = '免费查询'
        priceColor = 'width:50px;color:#32b16c;'
      }
      if (item.score === '0') {
        item.score = '优'
      }
      return (
        <View data-orderId={item.id} onClick={this.toProfessional.bind(this)} taroKey={item.id}>
          <View className='at-row richhtmltpl-title'>
            <View className='at-col at-col-1 at-col--auto' style='float:left;margin-left:10px;color:#adadadad;'>报告单号：
                <Text style='color:#333333;'>{item.id}</Text>
            </View>
            <View className='at-co at-col--autol' style='float:left;margin-left:55px;color:#adadadad;'>申请报告时间：
                <Text style='color:#333333;'>{item.createTime}</Text>
            </View>
            <View className='at-col at-icon at-icon-chevron-right chevronRight'></View>
          </View>
          <View style='font-size:12px;margin-top:1px;margin-bottom:10px;background-color:#ffffff;height:60px;line-height:25px;text-align:center;overflow:hidden;'>
            <View style='display:inline-block;margin-left:20px;'>
              <View style='color:#adadadad;'>姓名</View>
              <View>{item.name}</View>
            </View>
            <View style='display:inline-block;margin-left:35px;'>
              <View style='color:#adadadad;'>手机号</View>
              <View>{item.phone}</View>
            </View>
            <View style='display:inline-block;margin-left:25px;'>
              <View style='color:#adadadad;'>信用评分</View>
              <View style='color:#0788ed;'>{item.score}</View>
            </View>
            <View style='display:inline-block;margin-left:40px;'>
              <View style='color:#adadadad;'>价格</View>
              <View style={priceColor}>{price}</View>
            </View>
          </View>
        </View>
      )
    })
  }

```

展示页全部都是组件

**报错信息**
```js

thirdScriptError 
 sdk uncaught third Error 
 Maximum call stack size exceeded 
 RangeError: Maximum call stack size exceeded
    at s (http://127.0.0.1:49313/appservice/__dev__/WAService.js:1:785252)
    at s (http://127.0.0.1:49313/appservice/__dev__/WAService.js:1:785420)
    at s (http://127.0.0.1:49313/appservice/__dev__/WAService.js:1:785488)
    at s (http://127.0.0.1:49313/appservice/__dev__/WAService.js:1:785488)
    at s (http://127.0.0.1:49313/appservice/__dev__/WAService.js:1:785488)
    at s (http://127.0.0.1:49313/appservice/__dev__/WAService.js:1:785488)
    at s (http://127.0.0.1:49313/appservice/__dev__/WAService.js:1:785488)
    at s (http://127.0.0.1:49313/appservice/__dev__/WAService.js:1:785488)
    at s (http://127.0.0.1:49313/appservice/__dev__/WAService.js:1:785488)
    at s (http://127.0.0.1:49313/appservice/__dev__/WAService.js:1:785488)
```
![image](https://user-images.githubusercontent.com/46524158/60677926-7292c000-9eb5-11e9-8616-274aa682220b.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [ Windows 7]
 - Taro 版本 [e.g. v.1.3.4]
 - Node.js 版本 [e.g. v10.16.0]
 - 报错平台 [weapp]

**补充信息**
个人觉得还是哪里有个循环，一直在往内存里面添加值。

**Comment by gebilaofan** [comment]
刚刚跟同事讨论说，是不是我展示页的内容太多，里面都是导入子组件，还有十个setState操作。是不是因为set多了，然后造成的内存问题。

**Comment by gebilaofan** [comment]
我吧页面数据都清空，只留下一个文本，然后就没有报错
![image](https://user-images.githubusercontent.com/46524158/60678655-d0280c00-9eb7-11e9-94bc-e982f76cbbfa.png)
![image](https://user-images.githubusercontent.com/46524158/60678652-cd2d1b80-9eb7-11e9-9104-4eff88131dc2.png)

**Comment by Chen-jj** [comment]
@gebilaofan setData 的值太大，超过微信的限制。这里打断点可以看到每次被 setData 的值，自己找到过大的值然后优化吧。https://nervjs.github.io/taro/docs/debug.html#debug-diff

**Comment by gebilaofan** [comment]
> @gebilaofan setData 的值太大，超过微信的限制。这里打断点可以看到每次被 setData 的值，自己找到过大的值然后优化吧。https://nervjs.github.io/taro/docs/debug.html#debug-diff

刚调试发现，并不是页面setData值太大，而是一个echarts表格问题，一打开echarts组件就报错。

**Comment by Chen-jj** [comment]
@gebilaofan 哦，是死循环了，打断点看看把。
