### ISSUE TITLE
app.js中的config无法单独抽离出来

### ISSUE THREAD

**Issue by yangbo5207** [NervJS/taro#369]
**问题描述**

我希望能够把大量的配置抽离到单独的配置文件中
```js
// config.js
export default {
  pages: [...],
  window: {...},
  tabBar: {...}
}
```

并且在app.js中引入

```js
import config from './config'

class App extends Component {
  config = config
  ....
}
```

但是会报错

```js
TypeError: Cannot read property 'forEach' of undefined
    at traverseObjectNode (/Users/yangbo/develop/feewee/wx-mcar/node_modules/@tarojs/cli/src/weapp.js:90:18)
    at ClassProperty (/Users/yangbo/develop/feewee/wx-mcar/node_modules/@tarojs/cli/src/weapp.js:139:21)
    at NodePath._call (/Users/yangbo/develop/feewee/wx-mcar/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/yangbo/develop/feewee/wx-mcar/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/yangbo/develop/feewee/wx-mcar/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/yangbo/develop/feewee/wx-mcar/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/yangbo/develop/feewee/wx-mcar/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/yangbo/develop/feewee/wx-mcar/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/yangbo/develop/feewee/wx-mcar/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/yangbo/develop/feewee/wx-mcar/node_modules/babel-traverse/lib/path/context.js:115:19)
(node:18555) UnhandledPromiseRejectionWarning: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at Object.exports.checksum (/Users/yangbo/develop/feewee/wx-mcar/node_modules/@tarojs/cli/src/util/index.js:280:18)
    at FSWatcher.watcher.on.on.on (/Users/yangbo/develop/feewee/wx-mcar/node_modules/@tarojs/cli/src/weapp.js:1062:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:18555) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18555) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**系统信息**

 - 操作系统: mac 最新系统
 - Taro 版本: v0.0.71
 - Node.js 版本: v8.11.3

**Comment by luckyadam** [comment]
暂时不支持这样做哦~

**Comment by jiabinxu** [comment]
希望后续能添加这个功能

**Comment by luckyadam** [comment]
这个功能没有添加的计划，因为感觉没有太大价值

**Comment by YikaJ** [comment]
在我这里，因为 pages/subPackages 都是通过配置生成的，也十分需要该功能。

**Comment by Andrewuetyang** [comment]
> 这个功能没有添加的计划，因为感觉没有太大价值

有价值哦，产品同学对不同端会做不同的需求，有些页面可能根本就不会出现在特定端，config可抽离可组装意味着包体积的最小化。
