### ISSUE TITLE
快应用不支持Taro组件Canvas

### ISSUE THREAD

**Issue by YouthBaby** [NervJS/taro#3723]
**问题描述**
无法使用Taro组件Canvas写快应用（快应用原生是支持canvas的）

**复现步骤**
1、在一个组件中引入Canvas
```js
import { Canvas } from '@tarojs/components'
```
2、执行 taro build --type quickapp --watch
3、编译报错

**期望行为**
支持Canvas组件，编译成功

**报错信息**
```js
{ Error: ENOENT: no such file or directory, scandir 'E:\project\miniapp\node_modules\@tarojs\components-qa\src\components\taro-canvas'
    at Object.readdirSync (fs.js:790:3)
    at taroSelfComponents.forEach.c (C:\Users\YouthBaby\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\mini\helper.js:285:27)
    at Set.forEach (<anonymous>)
    at Object.getImportTaroSelfComponents (C:\Users\YouthBaby\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\mini\helper.js:282:24)
    at C:\Users\YouthBaby\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\mini\component.js:203:59
    at Generator.next (<anonymous>)
    at C:\Users\YouthBaby\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\mini\component.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\YouthBaby\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\mini\component.js:3:12)
    at buildSingleComponent (C:\Users\YouthBaby\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\mini\component.js:84:12)
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path:
   'E:\\project\\miniapp\\node_modules\\@tarojs\\components-qa\\src\\components\\taro-canvas' }
```
**系统信息**
Taro CLI 1.3.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**Comment by luckyadam** [comment]
快应用的 Canvas 组件正在支持中
