### ISSUE TITLE
taro 1.3.7 Textarea 不显示placeholder的内容，输入一次就报value is not defined 错误

### ISSUE THREAD

**Issue by 963072676** [NervJS/taro#3762]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

> Taro 使用上的问题请提到 [Taro 社区——让每一次交流被沉淀](https://taro-club.jd.com/)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
Textarea 不显示placeholder的内容，输入一次就报value is not defined 错误

**复现步骤**
[复现问题的步骤]

[代码只贴截图，不贴文字会被视为无效issue]
[代码只贴截图，不贴文字会被视为无效issue]
[代码只贴截图，不贴文字会被视为无效issue]

```js

// 这里可以贴代码
```ruby
<Textarea  class='feedbackContentInput' value={value} placeholder='简要描述您需要反馈的问题或建议（必填）' maxlength='500' onChange={(e) => {this.handleInput(e)}} />```
// 点击链接查看如何插入代码：
// https://coding.net/help/doc/project/markdown.html#i-5

// ```js
// 代码放这里（前后的 "```" 有助 Mardown 整理代码格式和加入代码高亮）
// ```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。

```

**期望行为**
Taro 快应用里可以完美使用Textarea，显示placeholder内容，不报value错误

**报错信息**

```ruby
pages/feedback/index.js:1041: TypeError: Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
    at FeedBack.handleInput (pages/feedback/index.js:1041:34)
    at FeedBack.anonymousFunc2 (pages/feedback/index.js:1075:16)
    at Qo.obj.(anonymous function) [as anonymousFunc2] (pages/feedback/index.js:6827:36)
    at Qo.<anonymous> (native.js:1:85796)
    at n.forEach.e (native.js:1:105066)
    at Array.forEach (<anonymous>)
    at Qo.$emit (native.js:1:105045)
    at Qo.handleChange (pages/feedback/index.js:1575:10)
    at kt.<anonymous> (native.js:1:76667)
    at Ge (native.js:1:25961)
com.eclipsesource.v8.V8ScriptExecutionException
	at com.eclipsesource.v8.V8._executeVoidFunction(Native Method)
	at com.eclipsesource.v8.V8.executeVoidFunction(SourceFile:1154)
	at com.eclipsesource.v8.V8Object.executeVoidFunction(SourceFile:435)
	at org.hapjs.render.jsruntime.JsThread.a(SourceFile:850)
	at org.hapjs.render.jsruntime.JsThread.a(SourceFile:77)
	at org.hapjs.render.jsruntime.JsThread$a.handleMessage(SourceFile:264)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:224)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
  Taro CLI 1.3.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
 - 操作系统: [ Windows 10]
 - Taro 版本 [ v.1.3.7]
 - Node.js 版本 [ v.10.16.0]
 - 报错平台 [ quick-app]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
倒是把 handleInput 的代码贴出来啊

**Comment by 963072676** [comment]
handleDesc(e){
        const handle = e.target.attr.value
        const len = e.target.attr.value.length
        this.setState({ desc: handle, len:len})
    }
后来把handleInput更名为handleDesc了

**Comment by Chen-jj** [comment]
升级到最新版再试试吧
