### ISSUE TITLE
创建项目出错

### ISSUE THREAD

**Issue by NikolaChen2017** [NervJS/taro#3817]
```
D:\Taro>taro init myapp
👽 Taro v1.3.9

Taro即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

√ 拉取远程模板仓库成功！
? 请输入项目介绍！ none
? 是否需要使用 TypeScript ？ No
? 请选择 CSS 预处理器（Sass/Less/Stylus） Less
? 请选择模板 默认模板
{ AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: D:\node\node_global\node_modules\@tarojs\cli\templates\default\.npmrc
    at EditionInterface.exports.copy (D:\node\node_global\node_modules\@tarojs\cli\node_modules\mem-fs-editor\lib\actions\copy.js:48:3)
    at EditionInterface.module.exports [as copyTpl] (D:\node\node_global\node_modules\@tarojs\cli\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:29:8)
    at Project.template (D:\node\node_global\node_modules\@tarojs\cli\dist\create\creator.js:56:17)
    at Object.<anonymous> (D:\node\node_global\node_modules\@tarojs\cli\dist\create\init.js:118:21)
    at Generator.next (<anonymous>)
    at D:\node\node_global\node_modules\@tarojs\cli\dist\create\init.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (D:\node\node_global\node_modules\@tarojs\cli\dist\create\init.js:3:12)
    at Object.createApp (D:\node\node_global\node_modules\@tarojs\cli\dist\create\init.js:105:12)
    at Project.write (D:\node\node_global\node_modules\@tarojs\cli\dist\create\project.js:187:16)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
```

D:\Taro>taro info

************************************************

👽 Taro v1.3.9

  Taro CLI 1.3.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - D:\node\node.EXE
      npm: 6.10.1 - D:\node\npm.CMD

**Comment by kunjiang** [comment]
现有的模板中, default, wxcloud 两个模板缺少 `.npmrc` 文件, 但其他几个模板中有这个文件, default 模板拷贝进去即可. 但是 wxclound 项目在创建项目, 拉取远程模板时会被跟新, 导致 `.npmrc` ` 文件被覆盖.

**Comment by LarenDorr** [comment]
Same

**Comment by LarenDorr** [comment]
从你的`node_modules/@tarojs/cli/templates/`目录下的其他模版中拷贝一份`.npmr`到`default`模版中即可

**Comment by Chinegoodman** [comment]
新手一枚，遇到同样的问题。官方不该优化好。新手直接拉取才可以的吗？为啥还得去其他模板拷贝啊？关键我新手没有其他模板可用啊。。。。这咋整啊

**Comment by lonelyant** [comment]
> 新手一枚，遇到同样的问题。官方不该优化好。新手直接拉取才可以的吗？为啥还得去其他模板拷贝啊？关键我新手没有其他模板可用啊。。。。这咋整啊

`npm install -g @tarojs/cli` 之后就会有`.../node_modules/@tarojs/cli/templates/`这个目录存在的，目录下有`default`、`wxcloud`、`mobx`等文件夹，把其它文件夹下的`.npmrc`复制一份到`default`就好了

**Comment by Chinegoodman** [comment]
> > 新手一枚，遇到同样的问题。官方不该优化好。新手直接拉取才可以的吗？为啥还得去其他模板拷贝啊？关键我新手没有其他模板可用啊。。。。这咋整啊
> 
> `npm install -g @tarojs/cli` 之后就会有`.../node_modules/@tarojs/cli/templates/`这个目录存在的，目录下有`default`、`wxcloud`、`mobx`等文件夹，把其它文件夹下的`.npmrc`复制一份到`default`就好了

收到。谢谢指导。哈哈
