### ISSUE TITLE
[bug] cli install is broken

### ISSUE THREAD

**Issue by dcsan** [NervJS/taro#3836]
trying to install the CLI based on:

https://nervjs.github.io/taro/docs/GETTING-STARTED.html#cli-%E5%B7%A5%E5%85%B7%E5%AE%89%E8%A3%85

maybe this is not a taro issue since the below says:
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

```
npm install -g @tarojs/cli
Unhandled rejection RangeError: Maximum call stack size exceededill install loadIdealTree
    at /usr/local/lib/node_modules/npm/node_modules/aproba/index.js:39:16
    at Array.forEach (<anonymous>)
    at validate (/usr/local/lib/node_modules/npm/node_modules/aproba/index.js:34:11)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:37:3)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dc/.npm/_logs/2019-07-15T17_36_12_618Z-debug.log

```
env: using OS-X

```
➜  stack git:(master) node -v
v12.6.0
➜  stack git:(master) npm -v
6.9.0
➜  stack git:(master) yarn -v
1.16.0
```

**Comment by dcsan** [comment]
broken:
X npm install -g @tarojs/cli

working:
√ yarn global add @tarojs/cli

**Comment by dcsan** [comment]
after installing taro with yarn:

```
 taro info
👽 Taro v1.3.9


  Taro CLI 1.3.9 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/components: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/plugin-babel: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/plugin-csso: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/plugin-stylus: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/plugin-uglifyjs: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/redux: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/redux-h5: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/router: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/taro: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/taro-alipay: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/taro-h5: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/taro-swan: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/taro-tt: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/taro-weapp: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/webpack-runner: 1.3.0-beta.3 => 1.3.0-beta.3
      eslint-config-taro: 1.3.0-beta.3 => 1.3.0-beta.3
      eslint-plugin-taro: 1.3.0-beta.3 => 1.3.0-beta.3
      nerv-devtools: ^1.4.0-beta.3 => 1.4.3
      nervjs: ^1.4.0-beta.3 => 1.4.3
    npmGlobalPackages:
      typescript: 3.5.2
```

**Comment by luckyadam** [comment]
安装的问题请自行解决
