### ISSUE TITLE
初始化选择默认模板出错

### ISSUE THREAD

**Issue by fool-yf** [NervJS/taro#3853]
**问题描述**
项目初始化时，在选择模板这一步选择默认模板，然后报错。

**复现步骤**
1. taro init hello
2.  请输入项目介绍！ test
3. 是否需要使用 TypeScript ？ Yes
4. 请选择模板 默认模板
5. 错误如下

```js
{ AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:\Users\yinfan\AppData\Roaming\nvm\v10.16.0\node_modules\@tarojs\cli\templates\default\.npmrc
    at EditionInterface.exports.copy (C:\Users\yinfan\AppData\Roaming\nvm\v10.16.0\node_modules\@tarojs\cli\node_modules\mem-fs-editor\lib\actions\copy.js:48:3)
    at EditionInterface.module.exports [as copyTpl] (C:\Users\yinfan\AppData\Roaming\nvm\v10.16.0\node_modules\@tarojs\cli\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:29:8)
    at Project.template (C:\Users\yinfan\AppData\Roaming\nvm\v10.16.0\node_modules\@tarojs\cli\dist\create\creator.js:56:17)
    at Object.<anonymous> (C:\Users\yinfan\AppData\Roaming\nvm\v10.16.0\node_modules\@tarojs\cli\dist\create\init.js:118:21)
    at Generator.next (<anonymous>)
    at C:\Users\yinfan\AppData\Roaming\nvm\v10.16.0\node_modules\@tarojs\cli\dist\create\init.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\yinfan\AppData\Roaming\nvm\v10.16.0\node_modules\@tarojs\cli\dist\create\init.js:3:12)
    at Object.createApp (C:\Users\yinfan\AppData\Roaming\nvm\v10.16.0\node_modules\@tarojs\cli\dist\create\init.js:105:12)
    at Project.write (C:\Users\yinfan\AppData\Roaming\nvm\v10.16.0\node_modules\@tarojs\cli\dist\create\project.js:187:16)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
```

**期望行为**
可以顺利创建模板

**报错信息**
```js
{ AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:\Users\yinfan\AppData\Roaming\nvm\v10.16.0\node_modules\@tarojs\cli\templates\default\.npmrc
    at EditionInterface.exports.copy (C:\Users\yinfan\AppData\Roaming\nvm\v10.16.0\node_modules\@tarojs\cli\node_modules\mem-fs-editor\lib\actions\copy.js:48:3)
    at EditionInterface.module.exports [as copyTpl] (C:\Users\yinfan\AppData\Roaming\nvm\v10.16.0\node_modules\@tarojs\cli\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:29:8)
    at Project.template (C:\Users\yinfan\AppData\Roaming\nvm\v10.16.0\node_modules\@tarojs\cli\dist\create\creator.js:56:17)
    at Object.<anonymous> (C:\Users\yinfan\AppData\Roaming\nvm\v10.16.0\node_modules\@tarojs\cli\dist\create\init.js:118:21)
    at Generator.next (<anonymous>)
    at C:\Users\yinfan\AppData\Roaming\nvm\v10.16.0\node_modules\@tarojs\cli\dist\create\init.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\yinfan\AppData\Roaming\nvm\v10.16.0\node_modules\@tarojs\cli\dist\create\init.js:3:12)
    at Object.createApp (C:\Users\yinfan\AppData\Roaming\nvm\v10.16.0\node_modules\@tarojs\cli\dist\create\init.js:105:12)
    at Project.write (C:\Users\yinfan\AppData\Roaming\nvm\v10.16.0\node_modules\@tarojs\cli\dist\create\project.js:187:16)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
```

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

👽 Taro v1.3.9

  Taro CLI 1.3.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**补充信息**
去 @tarojs\cli\templates\default\ 目录下确实没有发现.npmrc文件

**Comment by Takeos** [comment]
你这个解决了吗？我好像也遇到这个问题了

**Comment by fool-yf** [comment]
@Takeos   没有解决，我目前采用的模板是redux，这个可以正常创建。

**Comment by Chen-jj** [comment]
@fool-yf 提供控制台截图。

这个路径中 default 文件夹是否路径正确，如果正确，截图一下 default 文件夹 ls -a 或者编辑器目录结构：C:\Users\yinfan\AppData\Roaming\nvm\v10.16.0\node_modules\@tarojs\cli\templates\default\.npmrc

**Comment by Chen-jj** [comment]
@fool-yf @Takeos  下个版本修复。

**Comment by fool-yf** [comment]
@Chen-jj  有临时解决方案吗？

**Comment by Chen-jj** [comment]
@fool-yf 退版本 init

**Comment by fool-yf** [comment]
@Chen-jj  好的，谢谢

**Comment by zhmfe** [comment]
我也遇到这个问题了，请问是怎么解决的？

**Comment by guoranliaoran** [comment]
> 我也遇到这个问题了，请问是怎么解决的？

Try v1.3.7, remove v1.3.9 and install v1.3.7, it works.

**Comment by crazyshakalaka** [comment]
我也遇到了 版本3.3.14
