### ISSUE TITLE
将小程序转换成taro出现问题 Trying to copy from a source that does not exist

### ISSUE THREAD

**Issue by lvxiaoweiCHN** [NervJS/taro#3861]
assert.js:375
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/xiaoweilv/.nvm/versions/node/v12.6.0/lib/node_modules/@tarojs/cli/templates/default/pkg
    at EditionInterface.exports.copy (/Users/xiaoweilv/.nvm/versions/node/v12.6.0/lib/node_modules/@tarojs/cli/node_modules/_mem-fs-editor@4.0.3@mem-fs-editor/lib/actions/copy.js:48:3)
    at EditionInterface.module.exports [as copyTpl] (/Users/xiaoweilv/.nvm/versions/node/v12.6.0/lib/node_modules/@tarojs/cli/node_modules/_mem-fs-editor@4.0.3@mem-fs-editor/lib/actions/copy-tpl.js:29:8)
    at Creator.template (/Users/xiaoweilv/.nvm/versions/node/v12.6.0/lib/node_modules/@tarojs/cli/dist/create/creator.js:56:17)
    at Convertor.generateConfigFiles (/Users/xiaoweilv/.nvm/versions/node/v12.6.0/lib/node_modules/@tarojs/cli/dist/convertor/index.js:600:17)
    at Convertor.run (/Users/xiaoweilv/.nvm/versions/node/v12.6.0/lib/node_modules/@tarojs/cli/dist/convertor/index.js:645:14)
    at Object.<anonymous> (/Users/xiaoweilv/.nvm/versions/node/v12.6.0/lib/node_modules/@tarojs/cli/bin/taro-convert:12:11)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
bogon:wxapp-huazhu xiaoweilv$ 
bogon:wxapp-huazhu xiaoweilv$ 
bogon:wxapp-huazhu xiaoweilv$ cat /Users/xiaoweilv/.nvm/versions/node/v12.6.0/lib/node_modules/@tarojs/cli/templates/default/pkg
cat: /Users/xiaoweilv/.nvm/versions/node/v12.6.0/lib/node_modules/@tarojs/cli/templates/default/pkg: No such file or directory
bogon:wxapp-huazhu xiaoweilv$ taro info
👽 Taro v1.3.9

  Taro CLI 1.3.9 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm

**Comment by Jayson1004** [comment]
同样碰到这个问题。 用的最新的taro 1.3.9

**Comment by zbbtstudioworkspace** [comment]
同样碰到这个问题。 用的最新的taro 1.3.9   怎么解决呢？

**Comment by Chen-jj** [comment]
缺少 demo
