### ISSUE TITLE
生成一个taro项目Trying to copy from a source that does not exist

### ISSUE THREAD

**Issue by lvxiaoweiCHN** [NervJS/taro#3862]
? 是否需要使用 TypeScript ？ No
? 请选择 CSS 预处理器（Sass/Less/Stylus） Less
? 请选择模板 默认模板
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/xiaoweilv/.nvm/versions/node/v12.6.0/lib/node_modules/@tarojs/cli/templates/default/.npmrc
    at EditionInterface.exports.copy (/Users/xiaoweilv/.nvm/versions/node/v12.6.0/lib/node_modules/@tarojs/cli/node_modules/_mem-fs-editor@4.0.3@mem-fs-editor/lib/actions/copy.js:48:3)
    at EditionInterface.module.exports [as copyTpl] (/Users/xiaoweilv/.nvm/versions/node/v12.6.0/lib/node_modules/@tarojs/cli/node_modules/_mem-fs-editor@4.0.3@mem-fs-editor/lib/actions/copy-tpl.js:29:8)
    at Project.template (/Users/xiaoweilv/.nvm/versions/node/v12.6.0/lib/node_modules/@tarojs/cli/dist/create/creator.js:56:17)
    at Object.<anonymous> (/Users/xiaoweilv/.nvm/versions/node/v12.6.0/lib/node_modules/@tarojs/cli/dist/create/init.js:118:21)
    at Generator.next (<anonymous>)
    at /Users/xiaoweilv/.nvm/versions/node/v12.6.0/lib/node_modules/@tarojs/cli/dist/create/init.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/xiaoweilv/.nvm/versions/node/v12.6.0/lib/node_modules/@tarojs/cli/dist/create/init.js:3:12)
    at Object.createApp (/Users/xiaoweilv/.nvm/versions/node/v12.6.0/lib/node_modules/@tarojs/cli/dist/create/init.js:105:12)
    at Project.write (/Users/xiaoweilv/.nvm/versions/node/v12.6.0/lib/node_modules/@tarojs/cli/dist/create/project.js:187:16) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
xiaoweideMacBook-Pro:WeChatProjects xiaoweilv$ taro info
👽 Taro v1.3.9

  Taro CLI 1.3.9 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm

**Comment by Chen-jj** [comment]
#3853

**Comment by Chen-jj** [comment]
same issue

**Comment by guoranliaoran** [comment]
try v1.3.7, it works.
