### ISSUE TITLE
[支付宝小程序](node:96981) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'events'

### ISSUE THREAD

**Issue by hao-li** [NervJS/taro#3933]
**问题描述**
编译失败

**复现步骤**
1. git clone git@github.com:hao-li/taro-problem-sample.git
2. yarn
3. yarn build:alipay（yarn dev:alipay）

**期望行为**
编译正常结束

**报错信息**
```
(node:96981) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'events'
    at Object.openSync (fs.js:448:3)
    at Object.readFileSync (fs.js:348:35)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:227:30
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:3:12)
    at recursiveRequire (/usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:226:12)
    at resolveNpmFilesPath (/usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:54:9)
    at analyzeImportUrl (/usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:86:29)
(node:96981) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:96981) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**系统信息**
```
👽 Taro v1.3.10


  Taro CLI 1.3.10 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.10 => 1.3.10
      @tarojs/plugin-babel: 1.3.10 => 1.3.10
      @tarojs/plugin-csso: 1.3.10 => 1.3.10
      @tarojs/plugin-sass: 1.3.10 => 1.3.10
      @tarojs/plugin-uglifyjs: 1.3.10 => 1.3.10
      @tarojs/router: 1.3.10 => 1.3.10
      @tarojs/taro: 1.3.10 => 1.3.10
      @tarojs/taro-alipay: 1.3.10 => 1.3.10
      @tarojs/taro-h5: 1.3.10 => 1.3.10
      @tarojs/taro-swan: 1.3.10 => 1.3.10
      @tarojs/taro-tt: 1.3.10 => 1.3.10
      @tarojs/taro-weapp: 1.3.10 => 1.3.10
      @tarojs/webpack-runner: 1.3.10 => 1.3.10
      eslint-config-taro: 1.3.10 => 1.3.10
      eslint-plugin-taro: 1.3.10 => 1.3.10
      nerv-devtools: ^1.4.3 => 1.4.3
      nervjs: ^1.4.3 => 1.4.3
      stylelint-config-taro-rn: 1.3.10 => 1.3.10
      stylelint-taro-rn: 1.3.10 => 1.3.10
```

**Comment by luckyadam** [comment]
不要使用 node 原生的包，比如这里的 events

**Comment by hao-li** [comment]
@luckyadam 之前一直是正常的（至少到1.3.0-beta.6），升级到1.3.10后突然不行了，可以支持回去吗？

`mini-html-parser2`是[支付宝小程序官方文档 rich-text ](https://docs.alipay.com/mini/component/rich-text)的介绍中推荐使用的，用于将富文本字符串转为 html node，如果确实不能使用，有什么替代的方法可以推荐下吗？

**Comment by hao-li** [comment]
@luckyadam 升到最新的 1.3.12 还是存在这问题，因为要使用 rich-text 支付宝小程序已经阻塞很久了，请问 Taro 对于这种情况未来打算如何处理？

**Comment by hao-li** [comment]
看来和 #3771 是同一个问题，而且目前还没有什么可行的解决方案
