### ISSUE TITLE
函数式组件异常

### ISSUE THREAD

**Issue by canvasT** [NervJS/taro#3937]
**问题描述**
使用Hooks的写法模仿tarojs的Picker组件，函数组件内部无法使用函数组件

**复现步骤**
```js
export default function Index(props: OsDatePickerProps) {
  console.log('init');
  const rootClassName = 'date-picker';//组件
  const classObject = getClassObject(props);//组件修饰
  const styleObject = getStyleObj(props);

  const [popupShow, setPopupShow] = useState(false);
  const [indexArr, setIndexArr] = useState([0]);
  const [offsetYArr, setOffsetYArr] = useState([0]);
  useEffect(() => {
    console.log('useEffect,', props.value);
    const time = props.value.split(':').map(n => +n)
    setIndexArr(time);
  }, [props.value])

  const getTimeRange = (begin, end) => {
    const range: string[] = []
    for (let i = begin; i <= end; i++) {
      range.push(`${i < 10 ? '0' : ''}${i}`)
    }
    return range
  }

  const onClose = () => {
    setPopupShow(false);
  }

  const onCancel = () => {
    setPopupShow(false);
    props.onCancel && props.onCancel();
    onClose();
  }

  const onConfirm = () => {
    setPopupShow(false);
    props.onConfirm && props.onConfirm('')
    onClose();
  }

  const showPopup = () => {

  }

  const onGroupOffsetChange = (value) => {

  }

  // 时间
  const renderTimeSelector = function() {
    const hourRange = [
      '20',
      '21',
      '22',
      '23',
      ...getTimeRange(0, 23),
      '00',
      '01',
      '02',
      '03'
    ]
    const minRange = [
      '56',
      '57',
      '58',
      '59',
      ...getTimeRange(0, 59),
      '00',
      '01',
      '02',
      '03'
    ]
    return [
      <OsPickerGroup
        mode='time'
        range={hourRange}
        offsetY={offsetYArr[0]}
        onOffsetYUpdate={() => {}}
        columnId='0'
      />,
      <OsPickerGroup
        mode='time'
        range={minRange}
        offsetY={this.state.height[0]}
        onOffsetYUpdate={() => {}}
        columnId='1'
      />
    ]
  }

  if (indexArr.length <= 1) {
    return null;
  }

  return (
    <View
      className={classNames(rootClassName, classObject, props.className)}
      style={styleObject}
    >
      <View onClick={() => setPopupShow(true)}>{props.children}</View>
      <OsPickerPopup
        isShow={popupShow}
        onCancel={onCancel}
        onConfirm={onConfirm}
      >
        {renderTimeSelector()}
      </OsPickerPopup>
    </View>
  )
}

```

**期望行为**
无报错，正常显示组件

**报错信息**
![image](https://user-images.githubusercontent.com/1745014/61780214-b46bb200-ae34-11e9-917f-498b7d97269d.png)

**系统信息**
👽 Taro v1.3.4

  Taro CLI 1.3.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.5.3

**Comment by yuche** [comment]
现在还没有 Fragments 支持，`renderTimeSelector ` 需要用一个 Block 包起来。

**Comment by canvasT** [comment]
> 现在还没有 Fragments 支持，`renderTimeSelector ` 需要用一个 Block 包起来。

Block包起来指的是？能不能给个具体点的例子？

**Comment by yuche** [comment]
```
  const renderTimeSelector = function() {
    const hourRange = [
      '20',
      '21',
      '22',
      '23',
      ...getTimeRange(0, 23),
      '00',
      '01',
      '02',
      '03'
    ]
    const minRange = [
      '56',
      '57',
      '58',
      '59',
      ...getTimeRange(0, 59),
      '00',
      '01',
      '02',
      '03'
    ]
    return <Block>
      <OsPickerGroup
        mode='time'
        range={hourRange}
        offsetY={offsetYArr[0]}
        onOffsetYUpdate={() => {}}
        columnId='0'
      />,
      <OsPickerGroup
        mode='time'
        range={minRange}
        offsetY={this.state.height[0]}
        onOffsetYUpdate={() => {}}
        columnId='1'
      />
    </Block>
  }
```

**Comment by canvasT** [comment]
@yuche 按照你的加你，我在外层包了一个View，但是依然报错，报错信息：
```
错误  组件编译  组件src/components/datePicker/index.tsx编译失败！
TypeError: Cannot read property 'isCallExpression' of null
    at handleJSXElement (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_transformer-wx@1.3.4@@tarojs/transformer-wx/lib/src/render.js:171:46)
    at RenderParser.handleJSXElement (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_transformer-wx@1.3.4@@tarojs/transformer-wx/lib/src/render.js:96:17)
    at exit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_transformer-wx@1.3.4@@tarojs/transformer-wx/lib/src/render.js:164:26)
    at NodePath._call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_babel-traverse@6.26.0@babel-traverse/lib/index.js:114:17)
```
改用class的方式写组件，将renderTimeSelector提取到实例方法后正常。

**Comment by yuche** [comment]
升级你的 taro-cli

**Comment by canvasT** [comment]
@yuche 升级到1.3.10后正常，感谢
