### ISSUE TITLE
jest renderToString Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by BrookShuihuaLee** [NervJS/taro#3962]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

运行jest之后，renderToString报错：Cannot read property 'forEach' of undefined

**复现步骤**
[复现问题的步骤]
1. 如下配置
2. 运行jest

babel.config.js
```js
const apis = require('@tarojs/taro-h5/dist/taroApis')

module.exports = {
  presets: [
    [
      '@babel/env',
      {
        spec: true,
        useBuiltIns: 'usage',
      },
    ],
    '@babel/preset-typescript',
  ],
  plugins: [
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    ['@babel/plugin-proposal-class-properties', { loose: true }],
    [
      '@babel/plugin-transform-react-jsx',
      {
        pragma: 'require("nervjs").createElement',
      },
    ],
    ['@babel/plugin-proposal-object-rest-spread'],
    [
      'babel-plugin-transform-taroapi',
      {
        apis,
        packageName: '@tarojs/taro-h5',
      },
    ],
  ],
}

```
jest.config.js
```js
module.exports = {
  verbose: true,
  moduleFileExtensions: ['tsx', 'ts', 'jsx', 'js', 'json'],
  rootDir: __dirname,
  testMatch: ['<rootDir>/src/**/*.test.ts?(x)'],
  transform: {
    '^.+\\.[jt]sx?$': 'babel-jest',
  },
  transformIgnorePatterns: ['<rootDir>/node_modules/'],
  moduleNameMapper: {
    // 下面这三个开了会影响普通ts的测试
    react: 'nervjs',
    'react-addons-test-utils': 'nerv-test-utils',
    'react-dom': 'nervjs',
    'weui': '<rootDir>/__test__/mock-to-empty-object.js',
    '\\.(css|less|sass|scss)$': '<rootDir>/__test__/mock-to-empty-object.js',
    '\\.(png|svg|gif|jpg)$': '<rootDir>/__test__/mock-to-empty-object.js',
    '@/(.+)': '<rootDir>/src/$1',
  },
  resolver: 'jest-pnp-resolver',
  globals: {
    wx: {
      request() {
        return null
      }
    },
  },
  coverageReporters: ['text', 'text-summary'],
}

```

index.tsx
```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

import './index.less'

export default class ApprovalDivider extends Component {
  public render() {
    return <View className="approval-divider" />
  }
}

```

index.test.tsx
```js
import Taro from '@tarojs/taro'
import { renderToString } from 'nerv-server'

import ApprovalDivider from '.'

it('render', () => {
  renderToString(<ApprovalDivider />)
})

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

jest能正常运行

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

```
render

    TypeError: Cannot read property 'forEach' of undefined

      5 | 
      6 | it('render', () => {
    > 7 |   renderToString(<ApprovalDivider />)
        |   ^
      8 | })
      9 | 

      at forEach (node_modules/nerv-server/node_modules/nervjs/src/hooks.ts:118:11)
      at Object.renderComponent (node_modules/nerv-server/node_modules/nervjs/dist/index.js:1760:5)
      at renderComponent (node_modules/nerv-server/src/index.ts:155:22)
      at renderToString (node_modules/nerv-server/src/index.ts:164:10)
      at src/components/common/approval-divider/index.test.tsx:7:3
```

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

👽 Taro v1.3.0

  Taro CLI 1.3.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.1 - ~/.nvm/versions/node/v11.10.1/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.10.2 - ~/.nvm/versions/node/v11.10.1/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.0 => 1.3.0 
      @tarojs/components: 1.3.0 => 1.3.0 
      @tarojs/mobx: 1.3.0 => 1.3.0 
      @tarojs/mobx-h5: 1.3.0 => 1.3.0 
      @tarojs/mobx-rn: 1.3.0 => 1.3.0 
      @tarojs/plugin-babel: 1.3.0 => 1.3.0 
      @tarojs/plugin-csso: 1.3.0 => 1.3.0 
      @tarojs/plugin-less: 1.3.0 => 1.3.0 
      @tarojs/plugin-uglifyjs: 1.3.0 => 1.3.0 
      @tarojs/rn-runner: 1.3.0 => 1.3.0 
      @tarojs/router: 1.3.0 => 1.3.0 
      @tarojs/taro: 1.3.0 => 1.3.0 
      @tarojs/taro-alipay: 1.3.0 => 1.3.0 
      @tarojs/taro-h5: 1.3.0 => 1.3.0 
      @tarojs/taro-swan: 1.3.0 => 1.3.0 
      @tarojs/taro-tt: 1.3.0 => 1.3.0 
      @tarojs/taro-weapp: 1.3.0 => 1.3.0 
      @tarojs/webpack-runner: 1.3.0 => 1.3.0 
      eslint-config-taro: 1.3.0 => 1.3.0 
      eslint-plugin-taro: 1.3.0 => 1.3.0 
      nervjs: ^1.4.0 => 1.4.0

**Comment by BrookShuihuaLee** [comment]
更新：`Nerv.render`有一样的问题。

index.test.tsx
```js
import Taro from '@tarojs/taro'
import Nerv from 'nervjs'

import ApprovalDivider from '.'

it('render', () => {
  const div = document.createElement('div')
  Nerv.render(<ApprovalDivider />, div)
})

```

```
render

    TypeError: Cannot read property 'forEach' of undefined

       6 | it('render', () => {
       7 |   const div = document.createElement('div')
    >  8 |   Nerv.render(<ApprovalDivider />, div)
         |        ^
       9 | })
      10 | 

      at forEach (node_modules/nervjs/src/hooks.ts:118:11)
      at renderComponent (node_modules/nervjs/dist/index.js:1760:5)
      at renderComponent (node_modules/nervjs/src/lifecycle.ts:116:20)
      at ComponentWrapper.mountComponent [as init] (node_modules/nervjs/src/full-component.ts:51:17)
      at init (node_modules/nervjs/src/vdom/create-element.ts:27:47)
      at createElement (node_modules/nervjs/src/lifecycle.ts:75:10)
      at Object.mountVNode [as render] (node_modules/nervjs/src/render.ts:21:11)
      at render (src/components/common/approval-divider/index.test.tsx:8:8)
```

**Comment by yuche** [comment]
用 Jest 23
