### ISSUE TITLE
Taro v1.3.11  Property value expected type of string but got null 

### ISSUE THREAD

**Issue by zhangchenna** [NervJS/taro#4013]
👽 Taro v1.3.11 
Property value expected type of string but got null

```
TypeError: Property value expected type of string but got null
    at Object.validate (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-types/lib/definitions/index.js:161:13)
    at validate (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-types/lib/index.js:505:9)
    at Object.builder (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-types/lib/index.js:466:7)
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/render.js:1287:77
    at Array.map (<anonymous>)
    at RenderParser.handleConditionExpr (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/render.js:1285:58)
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/render.js:148:30
    at RenderParser.handleJSXElement (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/render.js:95:17)
    at enter (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/render.js:147:26)
    at NodePath._call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:76:18)
```

```
Taro CLI 1.3.11 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.11 => 1.3.11 
      @tarojs/components: 1.3.11 => 1.3.11 
      @tarojs/mobx: 1.3.11 => 1.3.11 
      @tarojs/plugin-babel: 1.3.11 => 1.3.11 
      @tarojs/plugin-csso: 1.3.11 => 1.3.11 
      @tarojs/plugin-sass: 1.3.11 => 1.3.11 
      @tarojs/plugin-uglifyjs: 1.3.11 => 1.3.11 
      @tarojs/router: 1.3.11 => 1.3.11 
      @tarojs/taro: 1.3.11 => 1.3.11 
      @tarojs/taro-weapp: 1.3.11 => 1.3.11 
      @tarojs/webpack-runner: 1.3.11 => 1.3.11 
      eslint-config-taro: 1.3.11 => 1.3.11 
      eslint-plugin-taro: 1.3.11 => 1.3.11 
      nerv-devtools: 1.4.3 => 1.4.3 
      nervjs: 1.4.3 => 1.4.3 
```

1.3.10 正常

**Comment by zhangchenna** [comment]
> 👽 Taro v1.3.11
> Property value expected type of string but got null
TypeError: Property value expected type of string but got null
    at Object.validate (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-types/lib/definitions/index.js:161:13)
    at validate (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-types/lib/index.js:505:9)
    at Object.builder (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-types/lib/index.js:466:7)
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/render.js:1287:77
    at Array.map (<anonymous>)
    at RenderParser.handleConditionExpr (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/render.js:1285:58)
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/render.js:148:30
    at RenderParser.handleJSXElement (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/render.js:95:17)
    at enter (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/render.js:147:26)
    at NodePath._call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:76:18)
> 
> Taro CLI 1.3.11 environment info:
> System:
> OS: macOS 10.14.5
> Shell: 3.2.57 - /bin/bash
> Binaries:
> Node: 12.6.0 - /usr/local/bin/node
> Yarn: 1.17.3 - /usr/local/bin/yarn
> npm: 6.9.0 - /usr/local/bin/npm
> npmPackages:
> @tarojs/async-await: 1.3.11 => 1.3.11
> @tarojs/components: 1.3.11 => 1.3.11
> @tarojs/mobx: 1.3.11 => 1.3.11
> @tarojs/plugin-babel: 1.3.11 => 1.3.11
> @tarojs/plugin-csso: 1.3.11 => 1.3.11
> @tarojs/plugin-sass: 1.3.11 => 1.3.11
> @tarojs/plugin-uglifyjs: 1.3.11 => 1.3.11
> @tarojs/router: 1.3.11 => 1.3.11
> @tarojs/taro: 1.3.11 => 1.3.11
> @tarojs/taro-weapp: 1.3.11 => 1.3.11
> @tarojs/webpack-runner: 1.3.11 => 1.3.11
> eslint-config-taro: 1.3.11 => 1.3.11
> eslint-plugin-taro: 1.3.11 => 1.3.11
> nerv-devtools: 1.4.3 => 1.4.3
> nervjs: 1.4.3 => 1.4.3
> 
> 1.3.10 正常

**Comment by yuche** [comment]
复现代码

**Comment by zhangchenna** [comment]
renderContent() {
        const { current, reachBottom } = this.state;
        return {
            0: <Home reachBottom={reachBottom} />,
            1: <Shop />,
            2: <Publisher />,
            3: <Mine />
        }[current];
    }

    render() {
        return (
            <View>
                {this.renderContent()}
                <View className="index-placeholder" />
                <AtTabBar
                    fixed
                    fontSize="10"
                    color="#333"
                    selectedColor="#ee4b00"
                    tabList={[
                        { title: '首页', iconType: 'home' },
                        { title: '店家', iconType: 'money' },
                        { title: '工作室', iconType: 'shopping-bag-2' },
                        { title: '我的', iconType: 'bullet-list' }
                    ]}
                    onClick={this.switchTab.bind(this)}
                    current={this.state.current}
                />
            </View>
        );
    }
1.3.11cli  这里报错 Property value expected type of string but got null

**Comment by zhangchenna** [comment]
@yuche  taro-cli v1.3.11 的问题

**Comment by yuche** [comment]
```jsx
        return {
            0: <Home reachBottom={reachBottom} />,
            1: <Shop />,
            2: <Publisher />,
            3: <Mine />
        }[current];
```

0,1,2,3 用引号包起来试试

**Comment by zhangchenna** [comment]
```
 let title = {
            '0': '剧本杀',
            '1': '店家总列表',
            '2': '工作室列表',
            '3': '我的'
        };
```
依然提示 Property value expected type of string but got null

**Comment by zhangchenna** [comment]
v1.3.11 cli 新版本jsx 枚举 有问题

**Comment by zhangchenna** [comment]
@yuche

**Comment by yuche** [comment]
```jsx
    renderContent() {
        const { current, reachBottom } = this.state;
        return {
            '0': <Home reachBottom={reachBottom} />,
            '1': <Shop />,
            '2': <Publisher />,
            '3': <Mine />
        }[current];
    }
```

就这样写

**Comment by zhangchenna** [comment]
> ```js-jsx
>     renderContent() {
>         const { current, reachBottom } = this.state;
>         return {
>             '0': <Home reachBottom={reachBottom} />,
>             '1': <Shop />,
>             '2': <Publisher />,
>             '3': <Mine />
>         }[current];
>     }
> ```
> 
> 就这样写

可以了。。。
