### ISSUE TITLE
dev:h5 raise TypeError: Cannot read property 'charAt' of undefined

### ISSUE THREAD

**Issue by broven** [NervJS/taro#4219]
**问题描述**
在跑h5平台时报错 `TypeError: Cannot read property 'charAt' of undefined`, 之前跑过 tt / swan /weapp 都可以正常使用, 麻烦看下

**复现步骤**
```bash
$ yarn run dev:h5
```
- app.tsx
```js
config: Config = {
   pages: preval`
      let basePages = [
        'pages/index/index',
     ]
     // ....
    module.exports=basePages
   `
}
```

**期望行为**
正常运行 不报错

**报错信息**
```bash
创建  发现文件  src/app.tsx
TypeError: Cannot read property 'charAt' of undefined
    at Object.exports.addLeadingSlash (/Users/zhangyao/project/miniapp/taro/node_modules/@tarojs/cli/dist/h5/helper.js:51:40)
    at exit (/Users/zhangyao/project/miniapp/taro/node_modules/@tarojs/cli/dist/h5/index.js:603:42)
    at NodePath._call (/Users/zhangyao/project/miniapp/taro/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/zhangyao/project/miniapp/taro/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/zhangyao/project/miniapp/taro/node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (/Users/zhangyao/project/miniapp/taro/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/zhangyao/project/miniapp/taro/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/zhangyao/project/miniapp/taro/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/zhangyao/project/miniapp/taro/node_modules/babel-traverse/lib/index.js:114:17)
    at Object.traverse [as default] (/Users/zhangyao/project/miniapp/taro/node_modules/babel-traverse/lib/index.js:79:12)

```

**系统信息**
```bash
Taro CLI 1.3.14 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /var/folders/cn/frsq2rx14s12b8cvv25n4v8h0000gn/T/yarn--1566269363791-0.08363909418256732/node
      Yarn: 1.17.3 - /var/folders/cn/frsq2rx14s12b8cvv25n4v8h0000gn/T/yarn--1566269363791-0.08363909418256732/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
    npmPackages:
      @tarojs/async-await: ~1.3.11 => 1.3.14
      @tarojs/cli: ~1.3.11 => 1.3.14
      @tarojs/components: ~1.3.11 => 1.3.14
      @tarojs/mobx: ~1.3.11 => 1.3.14
      @tarojs/mobx-h5: ~1.3.11 => 1.3.14
      @tarojs/plugin-babel: ~1.3.10 => 1.3.14
      @tarojs/plugin-csso: ~1.3.10 => 1.3.14
      @tarojs/plugin-less: ~1.3.11 => 1.3.14
      @tarojs/plugin-sass: ~1.3.11 => 1.3.14
      @tarojs/plugin-uglifyjs: ~1.3.11 => 1.3.14
      @tarojs/router: ~1.3.11 => 1.3.14
      @tarojs/taro: ~1.3.11 => 1.3.14
      @tarojs/taro-alipay: ~1.3.11 => 1.3.14
      @tarojs/taro-h5: ~1.3.11 => 1.3.14
      @tarojs/taro-swan: ~1.3.11 => 1.3.14
      @tarojs/taro-tt: ~1.3.11 => 1.3.14
      @tarojs/taro-weapp: ~1.3.11 => 1.3.14
      @tarojs/webpack-runner: ~1.3.11 => 1.3.14
      eslint-config-taro: 1.3.11 => 1.3.11
      eslint-plugin-taro: 1.3.11 => 1.3.11
      nerv-devtools: ~1.4.3 => 1.4.4
      nervjs: ~1.4.3 => 1.4.4
      react: ^16.8.6 => 16.9.0
```
 - 报错平台 h5

**补充信息**

**Comment by broven** [comment]
#2592

**Comment by broven** [comment]
#3867

**Comment by Troynew** [comment]
请问下这个问题有解决方案嘛？我在Taro 1.3.18上面也遇到这个问题，小程序跑的好好地，在H5编译通过了，页面报错了！

**Comment by worldlove** [comment]
这个问题还没有解决吗？ Taro 1.3.19上面还有这个问题？

**Comment by 18978909244** [comment]
同报错

**Comment by suiyi8760** [comment]
reopen吧，新版本又出现了

**Comment by broven** [comment]
@Littly

**Comment by ChangerHe** [comment]
同出现此问题  项目taro版本1.3.20

**Comment by seekcx** [comment]
+1，同样的问题 @Littly ，但是没有使用 preval，
![image](https://user-images.githubusercontent.com/8244814/67653933-a757e500-f986-11e9-929f-8a07e5663327.png)

**Comment by Garfield550** [comment]
各位出现问题的可以提供一下复现吗？
在最新版 Taro H5 上直接使用 charAt 没有问题。

```tsx
componentDidMount () {
  const sentence = 'The quick brown fox jumps over the lazy dog.';
  const index = 4;
  console.log('The character at index ' + index + ' is ' + sentence.charAt(index));
  // expected output: "The character at index 4 is q"
}
```

![image](https://user-images.githubusercontent.com/3471836/67654302-0bc77400-f988-11e9-9798-1d6d001e86c2.png)

**Comment by seekcx** [comment]
刚才我出现问题是cli 版本是 1.3.9，项目依赖版本是 1.3.21。都降到 1.3.9 就没有这个问题了

**Comment by Garfield550** [comment]
CLI 版本一定要和项目依赖版本保持完全一致。

**Comment by Garfield550** [comment]
1.3.21 H5 使用 `preval` 也没有问题。

![image](https://user-images.githubusercontent.com/3471836/67655935-51d30680-f98d-11e9-82d3-1e5f597cda70.png)

**Comment by suiyi8760** [comment]
我到时是升级到1.3.19之后dev:h5出现这段报错，然后程序就没运行下去了，回退到1.3.13正常使用

**Comment by Garfield550** [comment]
@suiyi8760 现在尝试把 CLI 和依赖都升级到 1.3.22 试一下？

**Comment by zzyundragon** [comment]
同样的问题
将依赖包 "@tarojs/cli" 升级到1.3.22版本解决了

**Comment by Garfield550** [comment]
没有更多的复现和反馈，这个 Issue 将关闭。

**Comment by Garfield550** [comment]
没有更多的复现和反馈，这个 Issue 将关闭。
