### ISSUE TITLE
typescript下自定义函数添加泛型时的编译bug

### ISSUE THREAD

**Issue by ZodiacSyndicate** [NervJS/taro#422]
**问题描述**
使用typescript泛型定义函数类型时，ts无报错， 但是编译不成功

**复现步骤**
request.ts
```ts
import { Observable } from 'rxjs/observable'
import { fromPromise } from 'rxjs/observable/fromPromise'
import { of } from 'rxjs/observable/of'
import { map, catchError } from 'rxjs/operators'

export const createError = (code: number, msg: string) => {
  const err = new Error(msg)
  return {
    code,
    name: err.name,
    stack: err.stack,
    message: err.message
  }
}

export const handleRequest = <T>(req: Promise<any>): Observable<T> =>
  fromPromise(req).pipe(
    map(({data}) => {
      if (!data.success || !data) {
        return createError(400, data.msg)
      }
      return data.data
    }),
    catchError(err => {
      const { response } = err
      if (response.status === 401) {
        return of(createError(401, 'Unauthorized'))
      }
      return of(createError(err.status, err.message))
    })
  )

```

**期望行为**
编译成功

**报错信息**
错误  编译失败  src\api\request.ts
{ SyntaxError: unknown: Unexpected token (43:2)
  41 |     })
  42 |   )
> 43 | </></></>;
     |   ^
  44 |
    at Parser.pp$5.raise (D:\projects\ts-car-rent\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (D:\projects\ts-car-rent\node_modules\babylon\lib\index.js:1761:8
)
    at Parser.pp$9.jsxParseIdentifier (D:\projects\ts-car-rent\node_modules\babylon\lib\index
.js:7029:10)
    at Parser.pp$9.jsxParseNamespacedName (D:\projects\ts-car-rent\node_modules\babylon\lib\i
ndex.js:7040:19)
    at Parser.pp$9.jsxParseElementName (D:\projects\ts-car-rent\node_modules\babylon\lib\inde
x.js:7055:19)
    at Parser.pp$9.jsxParseClosingElementAt (D:\projects\ts-car-rent\node_modules\babylon\lib
\index.js:7158:20)
    at Parser.pp$9.jsxParseElementAt (D:\projects\ts-car-rent\node_modules\babylon\lib\index.
js:7179:35)
    at Parser.pp$9.jsxParseElementAt (D:\projects\ts-car-rent\node_modules\babylon\lib\index.
js:7182:30)
    at Parser.pp$9.jsxParseElementAt (D:\projects\ts-car-rent\node_modules\babylon\lib\index.
js:7182:30)
    at Parser.pp$9.jsxParseElement (D:\projects\ts-car-rent\node_modules\babylon\lib\index.js
:7224:15)
  pos: 1270,
  loc: Position { line: 43, column: 2 },
  _babel: true,
  codeFrame: '\u001b[0m \u001b[90m 41 | \u001b[39m    })\n \u001b[90m 42 | \u001b[39m  )\n\u0
01b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 43 | \u001b[39m\u001b[33m<\u001b[39m\u001b[35
m/></\u001b[39m\u001b[33m>\u001b[39m\u001b[33m<\u001b[39m\u001b[33m/\u001b[39m\u001b[33m>\u00
1b[39m\u001b[33m;\u001b[39m\n \u001b[90m    | \u001b[39m  \u001b[31m\u001b[1m^\u001b[22m\u001
b[39m\n \u001b[90m 44 | \u001b[39m\u001b[0m' }

**系统信息**

 - 操作系统: [Windows 10]
 - Taro 版本 [v1.0.0-beta.6]
 - Node.js 版本 [v8.11.3]

**补充信息**
当去掉handleRequest函数的泛型时，编译可以通过。有可能是编译器将泛型当做JSX编译的缘故。

**Comment by AlexStacker** [comment]
这个是typescript官方编译器的问题，只在编译的时候有问题。可以暂时对泛型参数使用扩展的方式解决来让编译器通过 `<T extends any>(req: Promise<any>): Observable<T> =>`y
