### ISSUE TITLE
快应用Taro.getApp(),未获取app文件里面的内容

### ISSUE THREAD

**Issue by chaojiangcn** [NervJS/taro#4246]
**问题描述**
Taro转到快应用，无法通过Taro.getApp()和快应用自己的this.$app.$def获取到app文件的内容

**复现步骤**
使用Taro1.3.13转

试图获取app文件代码
```
app = Taro.getApp(),
// app = this.$app.$def
```

报错信息
```
index.ux?e1f7:881 Uncaught TypeError: _index2.default.getApp is not a function
    at __scriptModule__ (eval at c:\Program Files (x86)\Quickapp\resources\app\extensions\hap-debugger\node_modules.asar\@hap-toolkit\dsl-xvm\lib\loader\script-loader.js!c:\Program Files (x86)\Quickapp\resources\app\extensions\hap-debugger\node_modules.asar\@hap-toolkit\dsl-xvm\lib\loader\module-loader.js!./node_modules/babel-loader/lib/index.js?cwd=e:\workspace\taro\quickapp&cacheDirectory&plugins[]=c:\Program Files (x86)\Quickapp\resources\app\extensions\hap-debugger\node_modules.asar\@hap-toolkit\dsl-xvm\lib\loader\babel-plugin-jsx.js&comments=false!c:\Program Files (x86)\Quickapp\resources\app\extensions\hap-debugger\node_modules.asar\@hap-toolkit\dsl-xvm\lib\loader\access-loader.js!c:\Program Files (x86)\Quickapp\resources\app\extensions\hap-debugger\node_modules.asar\@hap-toolkit\dsl-xvm\lib\loader\fragment-loader.js?index=0&type=script!./src/bda_cardcrm/pages/index/index.ux?uxType=page (http://192.168.7.157:10000/preview/bda_cardcrm/pages/index/index.js:675:1), <anonymous>:81:30)
    at eval (webpack-internal:///./src/bda_cardcrm/pages/index/index.ux?uxType=page:27:6)
    at ny (https://statres.quickapp.cn/quickapp/ide/web.js:1:483060)
    at r (https://statres.quickapp.cn/quickapp/ide/web.js:1:484911)
```

**期望行为**
有什么替代或者解决方法可以处理现阶段的问题，急

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 7]
 - Taro 版本 [e.g. v.1.3.13]
 - Node.js 版本 [e.g. 10.15.3]
 - 报错平台 [快应用]

**补充信息**
又没有其他关于快应用开发的知道性文章

**Comment by chaojiangcn** [comment]
什么意思？求提示
