### ISSUE TITLE
【快应用】mobx使用在apptsx

### ISSUE THREAD

**Issue by M075097** [NervJS/taro#4248]
**问题描述**
[问题描述：mobx使用，在app.tsx中的入口处使用Provider，在具体组件中inject时报错：MobX injector: Store 'XXX' is not available! Make sure it is provided by some Provider]

```js
//app.tsx
 render() {
    return (
      <Provider store={store}>
        <Index/>
      </Provider>
    );

```

**期望行为**
[可以正常使用mobx]

**报错信息**
pages/index/index.js:14579: Error: MobX injector: Store 'store' is not available! Make sure it is provided by some Provider
Error: MobX injector: Store 'store' is not available! Make sure it is provided by some Provider
    at pages/index/index.js:14577:21
    at Array.forEach (<anonymous>)
    at pages/index/index.js:14575:16
    at Object.mapStoreToProps (pages/index/index.js:14603:34)
    at new Injector (pages/index/index.js:13980:169)
    at Object.createComponent (pages/index/index.js:17283:27)
    at __scriptModule__ (pages/index/index.js:6477:191)
    at pages/index/index.js:42021:6
    at nr (<anonymous>:1:108995)
    at s (<anonymous>:1:110893)
com.eclipsesource.v8.V8ScriptExecutionException
	at com.eclipsesource.v8.V8._executeVoidFunction(Native Method)
	at com.eclipsesource.v8.V8.executeVoidFunction(SourceFile:1133)
	at com.eclipsesource.v8.V8Object.executeVoidFunction(SourceFile:435)
	at org.hapjs.render.jsruntime.JsThread.b(SourceFile:664)
	at org.hapjs.render.jsruntime.JsThread.a(SourceFile:69)
	at org.hapjs.render.jsruntime.JsThread$a.handleMessage(SourceFile:240)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - Taro 版本 [1.3.13]

**补充信息**
1.可以确定的是在app.tsx中声明的Provider，最终会调用@tarojs/mobx/index.js 中的setStore，此调用是正常且store值是set成功的，但是实际在Index页面中调用inject时，此处再次import ：@tarojs/mobx/index.js 时里面的store实际值为{},导致最终不匹配报错，这个问题不知道是不是快应用JS引擎的原因

**Comment by nanjingboy** [comment]
@M075097 信息太少了

**Comment by Fantasy9527** [comment]
我也碰到了同样的问题

**Comment by nanjingboy** [comment]
@Fantasy9527 1.x 更新到 1.3.43，2.x 更新到 2.2.5 就可以了。
