### ISSUE TITLE
SyntaxError: unknown: Unexpected token

### ISSUE THREAD

**Issue by vimcaw** [NervJS/taro#428]
**问题描述**
我新建一个组件，出现了这个报错，我把这个组件改成很简单的形式确依然报错。

**复现步骤**
[复现问题的步骤]
1. 新建一个组件
2. 在`render`函数里插入一点内容

```js
import Taro, {Component} from '@tarojs/taro'
import {View} from '@tarojs/components'

export default class Button extends Component {
  render() {
    return (
      <View>a</View>
    )
  }
}
```

**期望行为**
成功运行

**报错信息**
```bash
{ SyntaxError: unknown: Unexpected token (5:11)
  3 | class Button extends Component {
  4 |   render() {
> 5 |     return <View>a</View>;
    |            ^
  6 |   }
  7 | }
  8 | 
    at Parser.pp$5.raise (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\babylon\lib\index.js:1761:8)
    at Parser.pp$3.parseExprAtom (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\babylon\lib\index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\babylon\lib\index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\babylon\lib\index.js:3474:19)
    at Parser.pp$3.parseExprOps (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\babylon\lib\index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\babylon\lib\index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\babylon\lib\index.js:3344:19)
    at Parser.pp$3.parseExpression (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\babylon\lib\index.js:3306:19)
    at Parser.pp$1.parseReturnStatement (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\babylon\lib\index.js:2078:26)
  pos: 131,
  loc: Position { line: 5, column: 11 },
  _babel: true,
  codeFrame: '\u001b[0m \u001b[90m 3 | \u001b[39m\u001b[36mclass\u001b[39m \u001b[33mButton\u001b[39m \u001b[36mextends\u001b[39m \u001b[33mComponent\u001b[39m {\n \u001b[90m 4 | \u001b[39m  render() {\n\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 5 | \u001b[39m    \u001b[36mreturn\u001b[39m \u001b[33m<\u001b[39m\u001b[33mView\u001b[39m\u001b[33m>\u001b[39ma\u001b[33m<\u001b[39m\u001b[33m/\u001b[39m\u001b[33mView\u001b[39m\u001b[33m>\u001b[39m\u001b[33m;\u001b[39m\n \u001b[90m   | \u001b[39m           \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 6 | \u001b[39m  }\n \u001b[90m 7 | \u001b[39m}\n \u001b[90m 8 | \u001b[39m\u001b[0m' }
at Parser.pp.unexpected (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\babylon\lib\index.js:1761:8)
    at Parser.pp$3.parseExprAtom (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\babylon\lib\index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\babylon\lib\index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\babylon\lib\index.js:3474:19)
    at Parser.pp$3.parseExprOps (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\babylon\lib\index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\babylon\lib\index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\babylon\lib\index.js:3344:19)
    at Parser.pp$3.parseExpression (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\babylon\lib\index.js:3306:19)
    at Parser.pp$1.parseReturnStatement (C:\Users\vimcaw\Documents\Work\kcshop-taro\node_modules\babylon\lib\index.js:2078:26)
  pos: 131,
  loc: Position { line: 5, column: 11 },
  _babel: true,
  codeFrame: '\u001b[0m \u001b[90m 3 | \u001b[39m\u001b[36mclass\u001b[39m \u001b[33mButton\u001b[39m \u001b[36mextends\u001b[39m \u001b[33mComponent\u001b[39m {\n \u001b[90m 4 | \u001b[39m  render() {\n\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 5 | \u001b[39m    \u001b[36mreturn\u001b[39m \u001b[33m<\u001b[39m\u001b[33mView\u001b[39m\u001b[33m>\u001b[39ma\u001b[33m<\u001b[39m\u001b[33m/\u001b[39m\u001b[33mView\u001b[39m\u001b[33m>\u001b[39m\u001b[33m;\u001b[39m\n \u001b[90m   | \u001b[39m           \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 6 | \u001b[39m  }\n \u001b[90m 7 | \u001b[39m}\n \u001b[90m 8 | \u001b[39m\u001b[0m' }
```

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本: v0.0.73
 - Node.js 版本: v8.11.2

**补充信息**

那个位置并没有什么奇怪的字符，我已经删掉重新写，还是一样。

我感觉这种报错有点问题，有一次在头部引入了一个文件，路径写错了，竟然也是报`render`函数返回的`React 元素`第一个字符有语法错误。

**Comment by yuche** [comment]
这个组件的名义 Button 和内置组件的名字重复了，所以编译不了。

换最新的beta版本会有ESLint提醒你

**Comment by vimcaw** [comment]
@yuche 原来是这样，谢谢。
