### ISSUE TITLE
wx:开启cssmodule报错

### ISSUE THREAD

**Issue by Lpbzzz** [NervJS/taro#4315]
**问题描述**
初始化项目，不安装ts、less等等选项，默认模板。以微信小程序编译项目，打开cssModules的enable。重启watch，报错

**复现步骤**
[复现问题的步骤]
如上所示

  ```js
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'exports' of undefined 

at ImportDeclaration.compileStyle_1.processStyleUseCssModule.then.result (C:\Users\***\AppData\Roaming\nvm\v10.15.3\node_modules\@tarojs\cli\dist\mini\astProcess.js:417:48)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:13836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**期望行为**
能正常启动，并且使用cssmodule

**报错信息**

如上

**系统信息**
```

"name": "taro-app-1",
  "version": "1.0.0",
  "private": true,
  "description": "taro",
  "templateInfo": {
    "name": "default",
    "typescript": false,
    "css": "none"
  },
  "scripts": {
    "build:weapp": "taro build --type weapp",
    "build:swan": "taro build --type swan",
    "build:alipay": "taro build --type alipay",
    "build:tt": "taro build --type tt",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "build:qq": "taro build --type qq",
    "build:quickapp": "taro build --type quickapp",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:swan": "npm run build:swan -- --watch",
    "dev:alipay": "npm run build:alipay -- --watch",
    "dev:tt": "npm run build:tt -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch",
    "dev:qq": "npm run build:qq -- --watch",
    "dev:quickapp": "npm run build:quickapp -- --watch"
  },
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@tarojs/components": "1.3.15",
    "@tarojs/router": "1.3.15",
    "@tarojs/taro": "1.3.15",
    "@tarojs/taro-alipay": "1.3.15",
    "@tarojs/taro-h5": "1.3.15",
    "@tarojs/taro-qq": "1.3.15",
    "@tarojs/taro-quickapp": "1.3.15",
    "@tarojs/taro-swan": "1.3.15",
    "@tarojs/taro-tt": "1.3.15",
    "@tarojs/taro-weapp": "1.3.15",
    "nervjs": "^1.4.0",
    "nerv-devtools": "^1.4.0"
  },
  "devDependencies": {
    "@types/react": "^16.4.6",
    "@types/webpack-env": "^1.13.6",
    "@tarojs/plugin-babel": "1.3.15",
    "@tarojs/plugin-csso": "1.3.15",
    "@tarojs/plugin-uglifyjs": "1.3.15",
    "@tarojs/webpack-runner": "1.3.15",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-jsx-stylesheet": "^0.6.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-eslint": "^8.2.3",
    "eslint": "^5.16.0",
    "eslint-config-taro": "1.3.15",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^1.6.1",
    "eslint-plugin-import": "^2.12.0",
    "stylelint": "9.3.0",
    "stylelint-config-taro-rn": "1.3.15",
    "stylelint-taro-rn": "1.3.15",
    "eslint-plugin-taro": "1.3.15"
  }
```

- 操作系统: [e.g. Windows 10]
- Taro 版本 [e.g. v.0.0.64]
- Node.js 版本 [e.g. v9.0.0]
- 报错平台 [h5, weapp]

**补充信息**
[可选]
  [根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
https://taro-docs.jd.com/taro/docs/css-modules.html
请阅读一下 CSS Modules 的文档
