### ISSUE TITLE
【快应用】Taroize之后转快应用大量组件报错

### ISSUE THREAD

**Issue by Qiyu8** [NervJS/taro#4336]
问题描述
  微信小程序的组件生态是比较完善的，而快应用组件在不断的发展中，有很多小程序组件快应用都是不支持的，比如Form、CheckboxGroup、CoverView、Ad等，目前的做法是直接报错，整个页面转换失败，最终的快应用也是无法预览的。

在taro build --type quickapp的过程中会报错
```
错误  页面编译  页面C:\taro\packages\taro-cli\jisu\taroConvert\src\pages\tabbarShoppingCart\tabbarShoppingCart编译失败！
Error: ENOENT: no such file or directory, scandir 'C:\taro\packages\taro-cli\jisu\taroConvert\node_modules\@tarojs\components-qa\src\components\form'
    at Object.readdirSync (fs.js:795:3)
    at C:\taro\packages\taro-cli\dist\mini\helper.js:285:27
    at Set.forEach (<anonymous>)
    at Object.getImportTaroSelfComponents (C:\taro\packages\taro-cli\dist\mini\helper.js:282:24)
    at C:\taro\packages\taro-cli\dist\mini\page.js:129:59
    at Generator.next (<anonymous>)
    at C:\taro\packages\taro-cli\dist\mini\page.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\taro\packages\taro-cli\dist\mini\page.js:3:12)
    at buildSinglePage (C:\taro\packages\taro-cli\dist\mini\page.js:25:12) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\taro\\packages\\taro-cli\\jisu\\taroConvert\\node_modules\\@tarojs\\components-qa\\src\\components\\form'
}
```

复现步骤
1.在微信小程序根目录执行 taro convert
2.在taroConvert目录执行 taro build --type quickapp

期望行为
快应用不支持的组件可以自动注释掉或者使用快应用支持的组件替换掉

报错信息
cli\jisu\taroConvert\src\pages\tabbarShoppingCart\tabbarShoppingCart编译失败！
Error: ENOENT: no such file or directory, scandir 'C:\taro\packages\taro-cli\jisu\taroConvert\node_modules\@tarojs\components-qa\src\components\form'

系统信息
操作系统: Windows 10
Taro 版本 v1.3.15
Node.js 版本 v12.7.0
报错平台 quickapp
补充信息
优化点：在转换过程中如果能将快应用不支持的组件可以自动注释掉或者使用快应用支持的组件替换掉就更好，至少先保证页面可以预览，在预览的过程中进行调试体验更佳

**Comment by luckyadam** [comment]
> 在转换过程中如果能将快应用不支持的组件可以自动注释掉或者使用快应用支持的组件替换掉就更好，至少先保证页面可以预览，在预览的过程中进行调试体验更佳

收到~
