### ISSUE TITLE
企业版微信小程序使用WebView组件报错:TypeError: Cannot read property 'appId' of undefined

### ISSUE THREAD

**Issue by starunaway** [NervJS/taro#4541]
**问题描述**
使用企业认证的小程序appId打开项目，使用WebView组件回报错
**复现步骤**
[复现问题的步骤]
1. `taro init test`
2.
 ```
  TS   ×
  Less  √
  Redux √
 
```
3. 引入 `WebView组件`，修改`pages/index/index.jsx`文件`render`的返回值为
 `  <WebView src='https://mp.weixin.qq.com/'  />`

**期望行为**
正确打开页面

**报错信息**

```
VM53:1 webviewScriptError
Cannot read property 'appId' of undefined;[Exparser] [Error] [Component] Property Observer Error @ wx-web-view#srcChange
TypeError: Cannot read property 'appId' of undefined
    at n.srcChange (WAWebview.js:1:908244)
    at Function.i.safeCallback (WAWebview.js:1:139878)
    at n.<anonymous> (WAWebview.js:1:231858)
    at a.doUpdates (WAWebview.js:1:247651)
    at e (WAWebview.js:1:1283668)
    at s (WAWebview.js:1:1286351)
    at e (WAWebview.js:1:1271776)
    at e (WAWebview.js:1:1271907)
    at w (WAWebview.js:1:1238338)
    at p (WAWebview.js:1:1239364)
```

**系统信息**
 - 操作系统: [ Windows 7]
 - Taro 版本 [ v.1.3.19]
 - Node.js 版本 [e.g. v10.16.1]
 - 报错平台 [weapp]

**补充信息**
[参考地址](https://github.com/starunaway/taro-WebView/tree/master)

**Comment by Chen-jj** [comment]
@starunaway 建议写个原生 demo 测试一下，应该是微信小程序自身的问题。
