### ISSUE TITLE
第三方引用路径解析错误

### ISSUE THREAD

**Issue by liuwuhaoo** [NervJS/taro#4581]
**问题描述**
使用 [posthtml](https://www.npmjs.com/package/posthtml) 这个库的时候出错。posthtml 引用了 posthtml-parser 这个库，posthtml-parser 又引用了 htmlparser2。   

在 htmlparser2 里的 Tokenizer 这个文件里这句代码 `var decodeCodePoint = require("entities/lib/decode_codepoint.js");`, entities 是 htmlparser2 引用的另外一个库，安装在 node_modules 下面。   
这里应该会引用到 node_modules 的正确路径，但是编译出来在微信开发者工具里报错   
![image](https://user-images.githubusercontent.com/19514172/66635749-723b5b00-ec42-11e9-987e-a83a139a8cf8.png)     

同时控制台里报错    
![image](https://user-images.githubusercontent.com/19514172/66635918-b7f82380-ec42-11e9-94ed-1d5ac6f4fbed.png)
但貌似暴露的信息不多，只是解析出错

**复现步骤**
[复现问题的步骤]
1. 安装 posthtml
2. 
```
useEffect(() => {
    posthtml().process('<p>test</p>')
  }, [])
```
3. See error
控制台
```
(node:16534) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'util'
    at Object.openSync (fs.js:449:3)
    at Object.readFileSync (fs.js:349:35)
    at /Users/zhihu/.config/yarn/global/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:267:30
    at Generator.next (<anonymous>)
    at /Users/zhihu/.config/yarn/global/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/zhihu/.config/yarn/global/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:3:12)
    at recursiveRequire (/Users/zhihu/.config/yarn/global/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:266:12)
    at resolveNpmFilesPath (/Users/zhihu/.config/yarn/global/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:55:9)
    at analyzeImportUrl (/Users/zhihu/.config/yarn/global/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:87:29)
(node:16534) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16534) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:16534) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'events'
    at Object.openSync (fs.js:449:3)
    at Object.readFileSync (fs.js:349:35)
    at /Users/zhihu/.config/yarn/global/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:267:30
    at Generator.next (<anonymous>)
    at /Users/zhihu/.config/yarn/global/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/zhihu/.config/yarn/global/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:3:12)
    at recursiveRequire (/Users/zhihu/.config/yarn/global/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:266:12)
    at resolveNpmFilesPath (/Users/zhihu/.config/yarn/global/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:55:9)
    at analyzeImportUrl (/Users/zhihu/.config/yarn/global/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:87:29)
(node:16534) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```
微信开发者工具里   
![image](https://user-images.githubusercontent.com/19514172/66636292-7fa51500-ec43-11e9-9212-e430f131a43a.png)

**期望行为**
不报错，能输出解析后的 html tree

**系统信息**
> Taro v1.3.19 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
```
👽 Taro v1.3.19


  Taro CLI 1.3.19 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.1 - ~/.nvm/versions/node/v11.10.1/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.10.1/bin/npm

```
**补充信息**
另外我发现 htmlparser2 的 Parser.js 里的 `require('events')` 也会报错，不过这就是另外一个错误了。

**Comment by liuwuhaoo** [comment]
这个什么时候能有个结论（是否是 taro bug，如果是的话什么时候能修复）

**Comment by luckyadam** [comment]
经过测试，由于 posthtml 引用了 htmlparser2 ，htmlparser2 里引用了 node 原生的包，所以不能在小程序里使用，建议换一个 npm 包吧
