### ISSUE TITLE
全局安装taro/cli之后创建项目，npm run dev:weapp报错

### ISSUE THREAD

**Issue by xslshr** [NervJS/taro#4602]
当前taro版本1.3.14 node:10.16.3 npm 6.9.0

报错信息：
Error: Couldn't find preset "react-app" relative to directory "E:\\"
    at E:\AClapp\myApp\node_modules\@tarojs\plugin-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (E:\AClapp\myApp\node_modules\@tarojs\plugin-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (E:\AClapp\myApp\node_modules\@tarojs\plugin-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (E:\AClapp\myApp\node_modules\@tarojs\plugin-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (E:\AClapp\myApp\node_modules\@tarojs\plugin-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\AClapp\myApp\node_modules\@tarojs\plugin-babel\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (E:\AClapp\myApp\node_modules\@tarojs\plugin-babel\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (E:\AClapp\myApp\node_modules\@tarojs\plugin-babel\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at babel (E:\AClapp\myApp\node_modules\@tarojs\plugin-babel\index.js:8:17)

**Comment by luckyadam** [comment]
删了依赖重新安装，另外检查一下你的项目所在目录，以及父级目录有没有 babel 配置文件，有就删掉

**Comment by xslshr** [comment]
> 删了依赖重新安装，另外检查一下你的项目所在目录，以及父级目录有没有 babel 配置文件，有就删掉

删了依赖重新装了 父级目录没有babel配置 就是不行 不能启动

**Comment by luckyadam** [comment]
检查一下自己的环境吧，这是你自己环境的问题
