### ISSUE TITLE
taro版本1.3.21和@antv/f2不兼容问题

### ISSUE THREAD

**Issue by xxyGoTop** [NervJS/taro#4673]
**问题描述**
taro从1,3,19升级到最近版本1.3.21，编译代码@antv/f2出现异常

taro-f2的版本和@antv/f2的版本
```json
"@antv/f2": "^3.4.2",
"taro-f2": "^2.1.2",
````

**报错信息**
```js
拷贝  NPM文件   dist/npm/@antv/f2/lib/attr/color.js
拷贝  NPM文件   dist/npm/@antv/f2/lib/attr/index.js
拷贝  NPM文件   dist/npm/@antv/f2/lib/geom/shape/shape.js
Error: Couldn't find preset "@babel/preset-env" relative to directory "D:\\work\\minishopvrm\\node_modules\\@antv\\adjust"
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transform (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\transformer-wx\lib\src\index.js:172:30)
```

**系统信息**
 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.3.21]
 - Node.js 版本 [e.g. v12.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
可能是webpack-runner 和 plugin-babel的兼容问题

**Comment by shenghanqin** [comment]
感觉还需要补充源码、示例、截图等
