### ISSUE TITLE
taro-components-rn 安装依赖失败

### ISSUE THREAD

**Issue by Issacpeng** [NervJS/taro#4693]
**问题描述**
taro-components-rn 安装依赖失败

**复现步骤**
[复现问题的步骤]
1. 下载最新taro 13.21源码包，进入根目录
2. 运行npm install
3. 运行npm run bootstrap

```js

PS D:\mywork\taro-1.3.21> npm run bootstrap

> @tarojs/taro@ bootstrap D:\mywork\taro-1.3.21
> npm-run-all clear-all bootstrap:lerna


> @tarojs/taro@ clear-all D:\mywork\taro-1.3.21
> rimraf package-lock.json packages/*/node_modules packages/*/package-lock.json


> @tarojs/taro@ bootstrap:lerna D:\mywork\taro-1.3.21
> lerna bootstrap -- --ignore-engines

lerna info version 2.11.0
lerna WARN ECYCLE Encountered a cycle in the dependency graph.This may cause instability! Packages in cycle are: "@tarojs/components", "@tarojs/taro-h5", "@tarojs/redux-h5", "@tarojs/router", "@tarojs/webpack-runner", "babel-plugin-transform-taroapi", "@tarojs/mobx-h5"
lerna info Bootstrapping 47 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna info lifecycle prepare
lerna ERR! execute Error occured with '@tarojs/components-rn' while running 'npm run prepare'
lerna ERR! npm run prepare [@tarojs/components-rn] Output from stdout:

> @tarojs/components-rn@1.3.21 prepare D:\mywork\taro-1.3.21\packages\taro-components-rn
> npm run build


> @tarojs/components-rn@1.3.21 build D:\mywork\taro-1.3.21\packages\taro-components-rn
> rm -rf ./dist && gulp


lerna ERR! npm run prepare [@tarojs/components-rn] Output from stderr:
'rm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tarojs/components-rn@1.3.21 build: `rm -rf ./dist && gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tarojs/components-rn@1.3.21 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pengzhouhu\AppData\Roaming\npm-cache\_logs\2019-10-26T07_46_51_034Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tarojs/components-rn@1.3.21 prepare: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tarojs/components-rn@1.3.21 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pengzhouhu\AppData\Roaming\npm-cache\_logs\2019-10-26T07_46_51_061Z-debug.log

lerna ERR! execute Error occured with '@tarojs/components-rn' while running 'npm run prepare'
Error: Command failed: npm run prepare
'rm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tarojs/components-rn@1.3.21 build: `rm -rf ./dist && gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tarojs/components-rn@1.3.21 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pengzhouhu\AppData\Roaming\npm-cache\_logs\2019-10-26T07_46_51_034Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tarojs/components-rn@1.3.21 prepare: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tarojs/components-rn@1.3.21 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pengzhouhu\AppData\Roaming\npm-cache\_logs\2019-10-26T07_46_51_061Z-debug.log

> @tarojs/components-rn@1.3.21 prepare D:\mywork\taro-1.3.21\packages\taro-components-rn
> npm run build


> @tarojs/components-rn@1.3.21 build D:\mywork\taro-1.3.21\packages\taro-components-rn
> rm -rf ./dist && gulp


    at D:\mywork\taro-1.3.21\node_modules\lerna\node_modules\execa\index.js:236:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 1,
  killed: false,
  stdout: '\n' +
    '> @tarojs/components-rn@1.3.21 prepare D:\\mywork\\taro-1.3.21\\packages\\taro-components-rn\n' +
    '> npm run build\n' +
    '\n' +
    '\n' +
    '> @tarojs/components-rn@1.3.21 build D:\\mywork\\taro-1.3.21\\packages\\taro-components-rn\n' +
    '> rm -rf ./dist && gulp\n' +
    '\n',
  stderr: "'rm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���\r\n" +
    '���������ļ���\r\n' +
    'npm ERR! code ELIFECYCLE\n' +
    'npm ERR! errno 1\n' +
    'npm ERR! @tarojs/components-rn@1.3.21 build: `rm -rf ./dist && gulp`\n' +
    'npm ERR! Exit status 1\n' +
    'npm ERR! \n' +
    'npm ERR! Failed at the @tarojs/components-rn@1.3.21 build script.\n' +
    'npm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     C:\\Users\\pengzhouhu\\AppData\\Roaming\\npm-cache\\_logs\\2019-10-26T07_46_51_034Z-debug.log\n' +
    'npm ERR! code ELIFECYCLE\n' +
    'npm ERR! errno 1\n' +
    'npm ERR! @tarojs/components-rn@1.3.21 prepare: `npm run build`\n' +
    'npm ERR! Exit status 1\n' +
    'npm ERR! \n' +
    'npm ERR! Failed at the @tarojs/components-rn@1.3.21 prepare script.\n' +
    'npm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     C:\\Users\\pengzhouhu\\AppData\\Roaming\\npm-cache\\_logs\\2019-10-26T07_46_51_061Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm run prepare',
  timedOut: false,
  pkg: Package {
    _package: {
      name: '@tarojs/components-rn',
      version: '1.3.21',
      description: '多端解决方案基础组件（RN）',
      main: './dist/index.js',
      scripts: [Object],
      files: [Array],
      'pre-commit': [Array],
      repository: [Object],
      keywords: [Array],
      author: 'O2Team',
      license: 'MIT',
      dependencies: [Object],
      peerDependencies: [Object],
      devDependencies: [Object]
    },
    _location: 'D:\\mywork\\taro-1.3.21\\packages\\taro-components-rn'
  },
  exitCode: 1
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tarojs/taro@ bootstrap:lerna: `lerna bootstrap -- --ignore-engines`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tarojs/taro@ bootstrap:lerna script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pengzhouhu\AppData\Roaming\npm-cache\_logs\2019-10-26T07_46_51_178Z-debug.log
ERROR: "bootstrap:lerna" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tarojs/taro@ bootstrap: `npm-run-all clear-all bootstrap:lerna`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tarojs/taro@ bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

// ```js


// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。

```

**期望行为**
正常安装和编译

**报错信息**
![image](https://user-images.githubusercontent.com/11417652/67616218-c16bb900-f808-11e9-98b8-bede678e50ed.png)

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.3.21]
 - Node.js 版本 [e.g. v10.12.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
最新的package包依赖更新导致

**Comment by Garfield550** [comment]
从你的 Log 上看不出什么关键信息，建议保存你的本地更改，然后运行一下 `git clean -dfx` 让 git 还原代码库状态之后重新运行 `npm install && npm run bootstrap` 。

现在所有的代码， CI 安装依赖时都通过了。
