### ISSUE TITLE
@antv/f2 编译失败 

### ISSUE THREAD

**Issue by b1ngx** [NervJS/taro#4713]
**问题描述**
@antv/f2 编译失败 

**复现步骤**
@taro-cli >= 1.3.21

**报错信息**

```
拷贝  NPM文件   dist/npm/@antv/f2/lib/util/dom.js
ReferenceError: Unknown plugin "transform-remove-strict-mode" specified in "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util/.babelrc" at 0, attempted to resolve relative to "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util"
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/index.js:172:30)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:297:41
拷贝  NPM文件   dist/npm/@antv/f2/npm/@antv/util/lib/string/upper-first.js
ReferenceError: Unknown plugin "transform-remove-strict-mode" specified in "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util/.babelrc" at 0, attempted to resolve relative to "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util"
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/index.js:172:30)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:297:41
拷贝  NPM文件   dist/npm/@antv/f2/npm/@antv/util/lib/string/lower-first.js
ReferenceError: Unknown plugin "transform-remove-strict-mode" specified in "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util/.babelrc" at 0, attempted to resolve relative to "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util"
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/index.js:172:30)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:297:41
拷贝  NPM文件   dist/npm/@antv/f2/npm/@antv/util/lib/type/is-string.js
ReferenceError: Unknown plugin "transform-remove-strict-mode" specified in "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util/.babelrc" at 0, attempted to resolve relative to "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util"
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/index.js:172:30)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:297:41
拷贝  NPM文件   dist/npm/@antv/f2/npm/@antv/util/lib/type/is-number.js
ReferenceError: Unknown plugin "transform-remove-strict-mode" specified in "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util/.babelrc" at 0, attempted to resolve relative to "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util"
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/index.js:172:30)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:297:41
拷贝  NPM文件   dist/npm/@antv/f2/npm/@antv/util/lib/type/is-boolean.js
ReferenceError: Unknown plugin "transform-remove-strict-mode" specified in "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util/.babelrc" at 0, attempted to resolve relative to "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util"
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/index.js:172:30)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:297:41
拷贝  NPM文件   dist/npm/@antv/f2/npm/@antv/util/lib/type/is-function.js
ReferenceError: Unknown plugin "transform-remove-strict-mode" specified in "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util/.babelrc" at 0, attempted to resolve relative to "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util"
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/index.js:172:30)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:297:41
拷贝  NPM文件   dist/npm/@antv/f2/npm/@antv/util/lib/type/is-date.js
ReferenceError: Unknown plugin "transform-remove-strict-mode" specified in "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util/.babelrc" at 0, attempted to resolve relative to "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util"
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/index.js:172:30)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:297:41
拷贝  NPM文件   dist/npm/@antv/f2/npm/@antv/util/lib/type/is-array.js
ReferenceError: Unknown plugin "transform-remove-strict-mode" specified in "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util/.babelrc" at 0, attempted to resolve relative to "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util"
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/index.js:172:30)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:297:41
拷贝  NPM文件   dist/npm/@antv/f2/npm/@antv/util/lib/type/is-nil.js
ReferenceError: Unknown plugin "transform-remove-strict-mode" specified in "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util/.babelrc" at 0, attempted to resolve relative to "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util"
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/index.js:172:30)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:297:41
拷贝  NPM文件   dist/npm/@antv/f2/npm/@antv/util/lib/type/is-object.js
ReferenceError: Unknown plugin "transform-remove-strict-mode" specified in "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util/.babelrc" at 0, attempted to resolve relative to "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util"
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/index.js:172:30)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:297:41
拷贝  NPM文件   dist/npm/@antv/f2/npm/@antv/util/lib/type/is-plain-object.js
ReferenceError: Unknown plugin "transform-remove-strict-mode" specified in "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util/.babelrc" at 0, attempted to resolve relative to "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util"
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/index.js:172:30)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:297:41
拷贝  NPM文件   dist/npm/@antv/f2/npm/@antv/util/lib/deep-mix.js
ReferenceError: Unknown plugin "transform-remove-strict-mode" specified in "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util/.babelrc" at 0, attempted to resolve relative to "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util"
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/index.js:172:30)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:297:41
拷贝  NPM文件   dist/npm/@antv/f2/npm/@antv/util/lib/mix.js
ReferenceError: Unknown plugin "transform-remove-strict-mode" specified in "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util/.babelrc" at 0, attempted to resolve relative to "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util"
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/index.js:172:30)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:297:41
拷贝  NPM文件   dist/npm/@antv/f2/npm/@antv/util/lib/each.js
ReferenceError: Unknown plugin "transform-remove-strict-mode" specified in "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util/.babelrc" at 0, attempted to resolve relative to "/Users/b1ng/WeChatProjects/erp/node_modules/@antv/f2/node_modules/@antv/util"
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/index.js:172:30)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:297:41
```

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

```
👽 Taro v1.3.22


  Taro CLI 1.3.22 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.12.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.12.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.22 => 1.3.22
      @tarojs/plugin-babel: 1.3.22 => 1.3.22
      @tarojs/plugin-csso: 1.3.22 => 1.3.22
      @tarojs/plugin-sass: 1.3.22 => 1.3.22
      @tarojs/plugin-uglifyjs: 1.3.22 => 1.3.22
      @tarojs/router: 1.3.22 => 1.3.22
      @tarojs/taro: 1.3.22 => 1.3.22
      @tarojs/taro-weapp: 1.3.22 => 1.3.22
      @tarojs/webpack-runner: 1.3.22 => 1.3.22
      eslint-config-taro: 1.3.22 => 1.3.22
      eslint-plugin-taro: 1.3.22 => 1.3.22
      nerv-devtools: ^1.5.2 => 1.5.2
      nervjs: ^1.5.2 => 1.5.2
```
 
**补充信息**
Taro v1.3.20 is ok

**Comment by Garfield550** [comment]
看一下 @antv/f2 的包里是不是有包含 .babelrc 文件？

**Comment by b1ngx** [comment]
有的 .babelrc
```
{
  "plugins": [
    "transform-remove-strict-mode"
  ],
  "presets": [
    [
      "@babel/preset-env",
      {
        "loose": true,
        "modules": false
      }
    ]
  ]
}
```

**Comment by Garfield550** [comment]
@b1ngx 删了试一下

**Comment by b1ngx** [comment]
删除后可以

**Comment by wangruiStart** [comment]
同样的问题，求解
