### ISSUE TITLE
微信小程序转化的require 变量地址问题 

### ISSUE THREAD

**Issue by yreme** [NervJS/taro#4749]
## 问题描述
[wx-helloword-to-multi.zip](https://github.com/NervJS/taro/files/3801635/wx-helloword-to-multi.zip)

所用的代码 ： 微信小程序的默认demo  helloword。

根目录下 `app.js` 在处理 require的时候，
```javascript
var pathTest = 'utils/test.js';
var test = require(pathTest); // error
//var test = require('utils/test.js'); //ok
```
上面这段代码，在微信小程序可以正常运行。但如果运行
> taro convert

就会报错
```bash
 taro convert
👽 Taro v1.3.22

开始代码转换...
转换  入口文件  app.js
转换  入口配置  app.json
转换  入口样式  app.wxss
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.extname (path.js:1231:5)
    at Object.analyzeImportUrl (/usr/local/lib/node_modules/@tarojs/cli/dist/convertor/helper.js:34:31)
    at CallExpression (/usr/local/lib/node_modules/@tarojs/cli/dist/convertor/index.js:162:46)
    at NodePath._call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:192:19) {
  code: 'ERR_INVALID_ARG_TYPE'
}
转换  页面文件  pages/index/index.js
转换  页面配置  pages/index/index.json
转换  页面模板  pages/index/index.wxml
转换  页面样式  pages/index/index.wxss
生成  页面文件  taroConvert/src/pages/index/index.js
转换  页面文件  pages/logs/logs.js
转换  页面配置  pages/logs/logs.json
转换  页面模板  pages/logs/logs.wxml
转换  页面样式  pages/logs/logs.wxss
生成  页面文件  taroConvert/src/pages/logs/logs.js
拷贝  JS 文件   taroConvert/src/utils/util.js
生成  样式文件  taroConvert/src/pages/index/index.scss
生成  样式文件  taroConvert/src/pages/logs/logs.scss
生成  文件      taroConvert/config/index.js
生成  文件      taroConvert/config/dev.js
生成  文件      taroConvert/config/prod.js
生成  文件      taroConvert/package.json
生成  文件      taroConvert/project.config.json
生成  文件      taroConvert/.gitignore
生成  文件      taroConvert/.editorconfig
生成  文件      taroConvert/.eslintrc
生成  文件      taroConvert/src/index.html

✔  转换成功，请进入 taroConvert 目录下使用 npm 或者 yarn 安装项目依赖后再运行！
```

出现问题的原因是` require`的文件地址使用了变量。
根目录下 `app.js` 在处理 require的时候，
```javascript
var pathTest = 'utils/test.js';
var test = require(pathTest); // error
//var test = require('utils/test.js'); //ok
```
如果使用下面代码，则` taro convert`不会出现问题。
```javascript
var pathTest = 'utils/test.js';
var test = require('utils/test.js'); //ok
```

## 希望得到的解决效果
因为我的工程比较大，require 需要尽可能使用变量加载文件。请问：
> 在微信小程序转为 taro多端的情况下，有没有可以 用变量加载文件模块的方法？

## 代码bug重现

请解压文件， 然后在文件根目录 执行
> taro convert

[wx-helloword-to-multi.zip](https://github.com/NervJS/taro/files/3801636/wx-helloword-to-multi.zip)

**Comment by yreme** [comment]
app.js 的完整代码为
```javascript
//app.js


var pathTest = 'utils/test.js';
var test = require(pathTest); // error
//var test = require('utils/test.js'); //ok

App({
  onLaunch: function () {
    // 展示本地存储能力
    var logs = wx.getStorageSync('logs') || []
    logs.unshift(Date.now())
    wx.setStorageSync('logs', logs)

    // 登录
    wx.login({
      success: res => {
        // 发送 res.code 到后台换取 openId, sessionKey, unionId
      }
    })
    // 获取用户信息
    wx.getSetting({
      success: res => {
        if (res.authSetting['scope.userInfo']) {
          // 已经授权，可以直接调用 getUserInfo 获取头像昵称，不会弹框
          wx.getUserInfo({
            success: res => {
              // 可以将 res 发送给后台解码出 unionId
              this.globalData.userInfo = res.userInfo

              // 由于 getUserInfo 是网络请求，可能会在 Page.onLoad 之后才返回
              // 所以此处加入 callback 以防止这种情况
              if (this.userInfoReadyCallback) {
                this.userInfoReadyCallback(res)
              }
            }
          })
        }
      }
    })
  },
  globalData: {
    userInfo: null
  }
})

```
