### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by secularworld** [NervJS/taro#4845]
微信原生小程序转h5报错，看不出是什么问题
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.extname (path.js:835:5)
    at Object.analyzeImportUrl (C:\Users\hujianming\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\convertor\helper.js:34:31)
    at CallExpression (C:\Users\hujianming\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\convertor\index.js:162:46)
    at NodePath._call (C:\Users\hujianming\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Users\hujianming\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\Users\hujianming\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\context.js:105:12)

**Comment by shenghanqin** [comment]
Taro info信息没有提供。
请问是第一次转换吗？
有木有原生小程序转换成Taro小程序后在小程序环境内跑一下，看效果如何？

定位到问题的代码行，也就截图看出错的行了？

**Comment by wangshouren-cn** [comment]
同样的问题+1

**Comment by xhwgood** [comment]
遇到了一样的问题，非常神奇

**Comment by Jairwin-L** [comment]
好奇怪，我这边也碰到了这个报错，导致无法启动。cc @shenghanqin 
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
<img width="403" alt="image" src="https://user-images.githubusercontent.com/32570960/225023884-a99165f4-fb1d-4b54-b81f-f192532bcbc2.png">
package.json
```json
"@tarojs/taro": "3.6.2",
```
repo：https://github.com/Jairwin-L/taro-react-wxmini-template

**Comment by secularworld** [comment]
您的来信在下已经收到，十分感谢您，稍后我会尽快给您回复。
