### ISSUE TITLE
打包编译后 提示  UnhandledPromiseRejectionWarning 怎么解决 

### ISSUE THREAD

**Issue by xiaoForest** [NervJS/taro#4854]
`使用npm 安装mqtt 能看到监听文件中，可是监听下边 ` 

生成 页面样式 dist/pages/hvideo/hvideo.wxss
生成 页面配置 dist/pages/index/index.json
生成 页面逻辑 dist/pages/index/index.js
生成 页面模板 dist/pages/index/index.wxml
生成 页面样式 dist/pages/index/index.wxss

监听文件修改中...

```
(node:10052) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'events'
at Object.openSync (fs.js:443:3)
at Object.readFileSync (fs.js:343:35)
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:267:30
at Generator.next ()
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:7:71
at new Promise ()
at __awaiter (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:3:12)
at recursiveRequire (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:266:12)
at resolveNpmFilesPath (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:55:9)
at analyzeImportUrl (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:87:29)
(node:10052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10052) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:10052) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'stream'
at Object.openSync (fs.js:443:3)
at Object.readFileSync (fs.js:343:35)
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:267:30
at Generator.next ()
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:7:71
at new Promise ()
at __awaiter (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:3:12)
at recursiveRequire (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:266:12)
at resolveNpmFilesPath (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:55:9)
at analyzeImportUrl (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:87:29)
(node:10052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10052) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'buffer'
at Object.openSync (fs.js:443:3)
at Object.readFileSync (fs.js:343:35)
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:267:30
at Generator.next ()
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:7:71
at new Promise ()
at __awaiter (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:3:12)
at recursiveRequire (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:266:12)
at resolveNpmFilesPath (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:55:9)
at analyzeImportUrl (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:87:29)
(node:10052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:10052) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'util'
at Object.openSync (fs.js:443:3)
at Object.readFileSync (fs.js:343:35)
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:267:30
at Generator.next ()
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:7:71
at new Promise ()
at __awaiter (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:3:12)
at recursiveRequire (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:266:12)
at resolveNpmFilesPath (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:55:9)
at analyzeImportUrl (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:87:29)
(node:10052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:10052) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'url'
at Object.openSync (fs.js:443:3)
at Object.readFileSync (fs.js:343:35)
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:267:30
at Generator.next ()
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:7:71
at new Promise ()
at __awaiter (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:3:12)
at recursiveRequire (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:266:12)
at resolveNpmFilesPath (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:55:9)
at analyzeImportUrl (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:87:29)
(node:10052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:10052) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'net'
at Object.openSync (fs.js:443:3)
at Object.readFileSync (fs.js:343:35)
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:267:30
at Generator.next ()
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:7:71
at new Promise ()
at __awaiter (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:3:12)
at recursiveRequire (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:266:12)
at resolveNpmFilesPath (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:55:9)
at analyzeImportUrl (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:87:29)
(node:10052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:10052) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'tls'
at Object.openSync (fs.js:443:3)
at Object.readFileSync (fs.js:343:35)
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:267:30
at Generator.next ()
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:7:71
at new Promise ()
at __awaiter (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:3:12)
at recursiveRequire (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:266:12)
at resolveNpmFilesPath (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:55:9)
at analyzeImportUrl (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:87:29)
(node:10052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:10052) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'crypto'
at Object.openSync (fs.js:443:3)
at Object.readFileSync (fs.js:343:35)
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:267:30
at Generator.next ()
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:7:71
at new Promise ()
at __awaiter (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:3:12)
at recursiveRequire (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:266:12)
at resolveNpmFilesPath (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:55:9)
at analyzeImportUrl (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:87:29)
(node:10052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:10052) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'https'
at Object.openSync (fs.js:443:3)
at Object.readFileSync (fs.js:343:35)
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:267:30
at Generator.next ()
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:7:71
at new Promise ()
at __awaiter (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:3:12)
at recursiveRequire (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:266:12)
at resolveNpmFilesPath (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:55:9)
at analyzeImportUrl (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:87:29)
(node:10052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
(node:10052) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'http'
at Object.openSync (fs.js:443:3)
at Object.readFileSync (fs.js:343:35)
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:267:30
at Generator.next ()
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:7:71
at new Promise ()
at __awaiter (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:3:12)
at recursiveRequire (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:266:12)
at resolveNpmFilesPath (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:55:9)
at analyzeImportUrl (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:87:29)
(node:10052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
(node:10052) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'zlib'
at Object.openSync (fs.js:443:3)
at Object.readFileSync (fs.js:343:35)
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:267:30
at Generator.next ()
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:7:71
at new Promise ()
at __awaiter (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:3:12)
at recursiveRequire (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:266:12)
at resolveNpmFilesPath (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:55:9)
at analyzeImportUrl (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:87:29)
(node:10052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:10052) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'fs'
at Object.openSync (fs.js:443:3)
at Object.readFileSync (fs.js:343:35)
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:267:30
at Generator.next ()
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:7:71
at new Promise ()
at __awaiter (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:3:12)
at recursiveRequire (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:266:12)
at resolveNpmFilesPath (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:55:9)
at analyzeImportUrl (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:87:29)
(node:10052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:10052) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'path'
at Object.openSync (fs.js:443:3)
at Object.readFileSync (fs.js:343:35)
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:267:30
at Generator.next ()
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:7:71
at new Promise ()
at __awaiter (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:3:12)
at recursiveRequire (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:266:12)
at resolveNpmFilesPath (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:55:9)
at analyzeImportUrl (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:87:29)
(node:10052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
(node:10052) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'os'
at Object.openSync (fs.js:443:3)
at Object.readFileSync (fs.js:343:35)
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:267:30
at Generator.next ()
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:7:71
at new Promise ()
at __awaiter (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:3:12)
at recursiveRequire (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:266:12)
at resolveNpmFilesPath (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:55:9)
at analyzeImportUrl (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:87:29)
(node:10052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
(node:10052) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'assert'
at Object.openSync (fs.js:443:3)
at Object.readFileSync (fs.js:343:35)
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:267:30
at Generator.next ()
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:7:71
at new Promise ()
at __awaiter (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:3:12)
at recursiveRequire (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:266:12)
at resolveNpmFilesPath (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:55:9)
at analyzeImportUrl (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:87:29)
(node:10052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
(node:10052) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
at Object.readSync (fs.js:498:3)
at tryReadSync (fs.js:332:20)
at Object.readFileSync (fs.js:369:19)
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:267:30
at Generator.next ()
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:7:71
at new Promise ()
at __awaiter (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:3:12)
at recursiveRequire (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:266:12)
at analyzeImportUrl (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:123:17)
(node:10052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
(node:10052) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'string_decoder'
at Object.openSync (fs.js:443:3)
at Object.readFileSync (fs.js:343:35)
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:267:30
at Generator.next ()
at C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:7:71
at new Promise ()
at __awaiter (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:3:12)
at recursiveRequire (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:266:12)
at resolveNpmFilesPath (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:55:9)
at analyzeImportUrl (C:\Users\Administrator\AppData\Roaming\nvm\v10.15.1\node_modules@tarojs\cli\dist\util\resolve_npm_files.js:87:29)
(node:10052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a ca(node:10052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
```

**Comment by tourze** [comment]
我最近也在研究这个，主要是mqtt.js这个lib有问题

**Comment by drizzlezxy** [comment]
Duplicate of #3347
是否也是因为引用了nodejs自带库重名的包？
