### ISSUE TITLE
框架中是否有wx.onKeyBoardHeightChange监听键盘高度的方法？

### ISSUE THREAD

**Issue by dreamthen** [NervJS/taro#4909]
### 问题描述

Taro.onKeyBoardHeightChange方法报错。

### 复现步骤

直接在didShow中使用监听键盘高度的方法
[https://developers.weixin.qq.com/miniprogram/dev/api/ui/keyboard/wx.onKeyboardHeightChange.html](https://developers.weixin.qq.com/miniprogram/dev/api/ui/keyboard/wx.onKeyboardHeightChange.html)

```js
componentDidShow() {
    Taro.showShareMenu({
      withShareTicket: false
    });
    Taro.onKeyboardHeightChange(res => {
      console.log(res);
    });
  }
```
发现会报错: 
```js
VM36169:1 thirdScriptError
_index3.default.onKeyboardHeightChange is not a function;at "pages/topicsDetail/index" page lifeCycleMethod onShow function
TypeError: _index3.default.onKeyboardHeightChange is not a function
    at Connect.componentDidShow (http://127.0.0.1:61276/appservice/pages/topicsDetail/index.js:380:23)
```

### 期望行为

能够使用onKeyboardHeightChange这个方法

### 报错信息

```js
VM36169:1 thirdScriptError
_index3.default.onKeyboardHeightChange is not a function;at "pages/topicsDetail/index" page lifeCycleMethod onShow function
TypeError: _index3.default.onKeyboardHeightChange is not a function
    at Connect.componentDidShow (http://127.0.0.1:61276/appservice/pages/topicsDetail/index.js:380:23)
```

### 系统信息
system: macOS 10.15.1
node: v12.13.0
taro: v1.3.25
taro-ui: v2.2.4

**Comment by luckyadam** [comment]
你可以直接用 `wx.onKeyBoardHeightChange`

**Comment by Chen-jj** [comment]
https://nervjs.github.io/taro/docs/debug.html#api-%E8%B0%83%E7%94%A8%E6%8A%A5%E9%94%99
