### ISSUE TITLE
新建 mobx 模板报错

### ISSUE THREAD

**Issue by arronf2e** [NervJS/taro#4915]
### 复现步骤

taro init myApp

回车

less 

mobx 

![image](https://user-images.githubusercontent.com/15780058/69518613-fcd9de80-0f92-11ea-8520-89154e9f0c10.png)

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Garfield550** [comment]
麻烦提供以下信息：
1. `taro info` 的结果
2. `cat ~/.taro/index.json` 的结果，如果是 Taro 2.0 则 `cat ~/.taro2/index.json`

**Comment by arronf2e** [comment]
![image](https://user-images.githubusercontent.com/15780058/69617566-59142f80-1073-11ea-86b3-e7deffacecc6.png)
![image](https://user-images.githubusercontent.com/15780058/69617591-60d3d400-1073-11ea-8167-3ef28a6d7cad.png)
@Garfield550

**Comment by Garfield550** [comment]
可能你本地安装的 `@tarojs/cli` 有问题，先用 `npx @tarojs/cli init new-app` 代替一下本地的 CLI 试一下。

```shell
➜  GitHub npx @tarojs/cli init new-mobx-less-app
👽 Taro v1.3.25

Taro即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

✔ 拉取远程模板仓库成功！
? 请输入项目介绍！ new-mobx-less-app
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Less
? 请选择模板 mobx

✔ 创建项目: new-mobx-less-app
✔ 创建文件: new-mobx-less-app/.editorconfig
✔ 创建文件: new-mobx-less-app/.eslintrc
✔ 创建文件: new-mobx-less-app/.gitignore
✔ 创建文件: new-mobx-less-app/global.d.ts
✔ 创建文件: new-mobx-less-app/package.json
✔ 创建文件: new-mobx-less-app/project.config.json
✔ 创建文件: new-mobx-less-app/tsconfig.json
✔ 创建文件: new-mobx-less-app/config/dev.js
✔ 创建文件: new-mobx-less-app/config/index.js
✔ 创建文件: new-mobx-less-app/config/prod.js
✔ 创建文件: new-mobx-less-app/src/app.less
✔ 创建文件: new-mobx-less-app/src/app.tsx
✔ 创建文件: new-mobx-less-app/src/index.html
✔ 创建文件: new-mobx-less-app/src/store/counter.ts
✔ 创建文件: new-mobx-less-app/src/pages/index/index.less
✔ 创建文件: new-mobx-less-app/src/pages/index/index.tsx

✔ cd new-mobx-less-app, 执行 git init
✔ 安装成功
yarn install v1.19.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 150.88s.

创建项目 new-mobx-less-app 成功！
请进入项目目录 new-mobx-less-app 开始工作吧！😝
```

**Comment by arronf2e** [comment]
<img width="644" alt="图片" src="https://user-images.githubusercontent.com/15780058/69741420-fa83aa00-1175-11ea-96bf-5646a5fc5392.png">
@Garfield550  ~~

**Comment by Garfield550** [comment]
发现是 Node.js 13+ 的问题。

```shell
~/Projects/GitHub> node -v
v13.2.0
~/Projects/GitHub> npx @tarojs/cli init new-mobx-app
👽 Taro v1.3.26

Taro即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

✔ 拉取远程模板仓库成功！
? 请输入项目介绍！ new-mobx-app
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Less
? 请选择模板 mobx
SyntaxError: Error parsing ~/.npm/_npx/1923/lib/node_modules/@tarojs/cli/templates/mobx/package.json: Unexpected token < in JSON at position 183
    at JSON.parse (<anonymous>)
    at readPackage (internal/modules/cjs/loader.js:247:25)
    at readPackageScope (internal/modules/cjs/loader.js:272:19)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1133:17)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> 
```

麻烦您按照这条评论降级 Node 版本试一下？https://github.com/NervJS/taro/issues/4967#issuecomment-559687315

**Comment by Garfield550** [comment]
已修复。

```shell
~/Projects/GitHub> node -v
v13.2.0
~/Projects/GitHub> npx @tarojs/cli init new-app-test
👽 Taro v1.3.26

Taro即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

✔ 拉取远程模板仓库成功！
? 请输入项目介绍！ new-app-test
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Less
? 请选择模板 mobx

✔ 创建项目: new-app-test
✔ 创建文件: new-app-test/.editorconfig
✔ 创建文件: new-app-test/.eslintrc
✔ 创建文件: new-app-test/.gitignore
✔ 创建文件: new-app-test/global.d.ts
✔ 创建文件: new-app-test/package.json
✔ 创建文件: new-app-test/project.config.json
✔ 创建文件: new-app-test/tsconfig.json
✔ 创建文件: new-app-test/config/dev.js
✔ 创建文件: new-app-test/config/index.js
✔ 创建文件: new-app-test/config/prod.js
✔ 创建文件: new-app-test/src/app.less
✔ 创建文件: new-app-test/src/app.tsx
✔ 创建文件: new-app-test/src/index.html
✔ 创建文件: new-app-test/src/store/counter.ts
✔ 创建文件: new-app-test/src/pages/index/index.less
✔ 创建文件: new-app-test/src/pages/index/index.tsx

✔ cd new-app-test, 执行 git init
⠹ 执行安装项目依赖 yarn install, 需要一会儿...
```

**Comment by arronf2e** [comment]
@Garfield550 可以了，谢谢
