### ISSUE TITLE
taro 1.3.9  taro convert 报错

### ISSUE THREAD

**Issue by zbbtstudioworkspace** [NervJS/taro#4946]
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /usr/local/share/.config/yarn/global/node_modules/@tarojs/cli/templates/default/pkg
    at EditionInterface.exports.copy (/usr/local/share/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy.js:48:3)
    at EditionInterface.module.exports [as copyTpl] (/usr/local/share/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:29:8)
    at Creator.template (/usr/local/share/.config/yarn/global/node_modules/@tarojs/cli/dist/create/creator.js:56:17)
    at Convertor.generateConfigFiles (/usr/local/share/.config/yarn/global/node_modules/@tarojs/cli/dist/convertor/index.js:600:17)
    at Convertor.run (/usr/local/share/.config/yarn/global/node_modules/@tarojs/cli/dist/convertor/index.js:645:14)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/@tarojs/cli/bin/taro-convert:12:11)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='

**Comment by Garfield550** [comment]
请提供以下信息：

1. `taro info` 的结果
2. 出问题的复现代码

**Comment by zbbtstudioworkspace** [comment]
> 请提供以下信息：
> 
> 1. `taro info` 的结果
> 2. 出问题的复现代码


localhost:~ kangle$ taro info
👽 Taro v1.3.9


  Taro CLI 1.3.9 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.19.2 - /usr/local/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm

只要微信小程序转Taro  都会报这个错  哪怕是新建一个默认的小程序   使用
taro convert都会报这个错
