### ISSUE TITLE
TS 函数编译报错

### ISSUE THREAD

**Issue by zaaack** [NervJS/taro#495]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
编译 TS 函数
```ts

export const Ok = <T, E = any>(data: T) => new OkCls<T, E>(data)
export const Err = <T = any, E = void>(err?: E) => new ErrCls<T, E>(err as any)


export function throttle(fn, wait = 3000) {
  let timer: number = 0
  let wrapped = (...args: any[]) => {
    timer && clearTimeout(timer)
    timer = setTimeout(fn as any, wait, ...args)
  }
  return wrapped
}

```

**期望行为**
不报错

**报错信息**
```ts
修改  JS文件    src/utils/index.ts
错误  编译失败  src/utils/index.ts
{ SyntaxError: unknown: Unexpected token (142:3)
  140 |   fn: F,
  141 |   wait: number = 3000,
> 142 | ) {let} = null as any
      |    ^
  143 |   let wrapped = (...args: any[]) => {timer && clearTimeout(timer)} = setTimeout(fn as any, wait, ...args)
  144 |   }
  145 |   return wrapped as any as F
    at Parser.pp$5.raise (/Users/z/Projects/Douban/mole-taro/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/z/Projects/Douban/mole-taro/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/Users/z/Projects/Douban/mole-taro/node_modules/babylon/lib/index.js:3750:12)
    at Parser.parseExprAtom (/Users/z/Projects/Douban/mole-taro/node_modules/babylon/lib/index.js:7238:22)
    at Parser.pp$3.parseExprSubscripts (/Users/z/Projects/Douban/mole-taro/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/z/Projects/Douban/mole-taro/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/z/Projects/Douban/mole-taro/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/z/Projects/Douban/mole-taro/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/z/Projects/Douban/mole-taro/node_modules/babylon/lib/index.js:3344:19)
    at Parser.parseMaybeAssign (/Users/z/Projects/Douban/mole-taro/node_modules/babylon/lib/index.js:6474:20)
  pos: 3854,
  loc: Position { line: 142, column: 3 },
  _babel: true,
  codeFrame:
   '\u001b[0m \u001b[90m 140 | \u001b[39m  fn\u001b[33m:\u001b[39m \u001b[33mF\u001b[39m\u001b[33m,\u001b[39m\n \u001b[90m 141 | \u001b[39m wait\u001b[33m:\u001b[39m number \u001b[33m=\u001b[39m \u001b[35m3000\u001b[39m\u001b[33m,\u001b[39m\n\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 142 | \u001b[39m) {let} \u001b[33m=\u001b[39m \u001b[36mnull\u001b[39m as any\n \u001b[90m     | \u001b[39m   \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 143 | \u001b[39m  let wrapped \u001b[33m=\u001b[39m (\u001b[33m...\u001b[39margs\u001b[33m:\u001b[39many[]) \u001b[33m=>\u001b[39m {timer \u001b[33m&&\u001b[39m clearTimeout(timer)} \u001b[33m=\u001b[39m setTimeout(fn as any\u001b[33m,\u001b[39m wait\u001b[33m,\u001b[39m \u001b[33m...\u001b[39margs)\n \u001b[90m 144 | \u001b[39m  }\n \u001b[90m 145 | \u001b[39m  \u001b[36mreturn\u001b[39m wrapped as any as \u001b[33mF\u001b[39m\u001b[0m' }
```

**系统信息**

 - 操作系统: macos 10.13.5
 - Taro 版本 v1.0.0-beta.11
 - Node.js 版本 10

**补充信息**

**Comment by AlexStacker** [comment]
应该和[issue 422](https://github.com/NervJS/taro/issues/422)是一样的错误，属于Ts的bug，已经在版本3.1的修复计划中。

**Comment by zaaack** [comment]
👌
