### ISSUE TITLE
JSX 循环中单项返回 `null` 在编译时报语法错误。

### ISSUE THREAD

**Issue by mytharcher** [NervJS/taro#4951]
### 问题描述

JSX 循环中单项返回 `null` 在编译时报语法错误。

### 复现步骤

1. 使用循环输出；
2. `return null`
3. 编译报错。

`pages/test/index.jsx`：

~~~jsx
import Taro, { Component } from '@tarojs/taro';
import { View } from '@tarojs/components';

class Page extends Component {
  render() {
    return (
      <View>
        {[1,2,3].map(() => {
          return null;
        })}
      </View>
    );
  }
}

export default Page;
~~~

### 期望行为

编译通过。

### 报错信息

~~~
错误  页面编译  页面/Users/me/test/weapp/src/pages/route/test编译失败！
{ SyntaxError: /Users/me/test/weapp/src/pages/route/test.jsx: Unexpected token, expected } (24:26)
  22 |     });
  23 |     Object.assign(this.__state, {
> 24 |       anonymousState__temp: anonymousState__temp
     |                           ^
  25 |     });
  26 |     return this.__state;
  27 |   }
    at Parser.pp$5.raise (/Users/me/test/weapp/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/me/test/weapp/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp.expect (/Users/me/test/weapp/node_modules/babylon/lib/index.js:1749:33)
    at Parser.pp$9.jsxParseExpressionContainer (/Users/me/test/weapp/node_modules/babylon/lib/index.js:7121:8)
    at Parser.pp$9.jsxParseElementAt (/Users/me/test/weapp/node_modules/babylon/lib/index.js:7193:32)
    at Parser.pp$9.jsxParseElement (/Users/me/test/weapp/node_modules/babylon/lib/index.js:7224:15)
    at Parser.parseExprAtom (/Users/me/test/weapp/node_modules/babylon/lib/index.js:7236:21)
    at Parser.pp$3.parseExprSubscripts (/Users/me/test/weapp/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/me/test/weapp/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/me/test/weapp/node_modules/babylon/lib/index.js:3404:19)
  pos: 769,
  loc: Position { line: 24, column: 26 },
  _babel: true,
  codeFrame:
   '\u001b[0m \u001b[90m 22 | \u001b[39m    })\u001b[33m;\u001b[39m\n \u001b[90m 23 | \u001b[39m    \u001b[33mObject\u001b[39m\u001b[33m.\u001b[39massign(\u001b[36mthis\u001b[39m\u001b[33m.\u001b[39m__state\u001b[33m,\u001b[39m {\n\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 24 | \u001b[39m      anonymousState__temp\u001b[33m:\u001b[39m anonymousState__temp\n \u001b[90m    | \u001b[39m                          \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 25 | \u001b[39m    })\u001b[33m;\u001b[39m\n \u001b[90m 26 | \u001b[39m    \u001b[36mreturn\u001b[39m \u001b[36mthis\u001b[39m\u001b[33m.\u001b[39m__state\u001b[33m;\u001b[39m\n \u001b[90m 27 | \u001b[39m  }\u001b[0m' }
~~~

### 系统信息

~~~
👽 Taro v1.3.25


  Taro CLI 1.3.25 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.7.0 - /usr/local/bin/node
      npm: 6.11.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.25 => 1.3.25 
      @tarojs/cli: ^1.3.25 => 1.3.25 
      @tarojs/components: 1.3.25 => 1.3.25 
      @tarojs/mobx: 1.3.25 => 1.3.25 
      @tarojs/mobx-h5: 1.3.25 => 1.3.25 
      @tarojs/mobx-rn: 1.3.25 => 1.3.25 
      @tarojs/plugin-babel: 1.3.25 => 1.3.25 
      @tarojs/plugin-csso: 1.3.25 => 1.3.25 
      @tarojs/plugin-less: 1.3.25 => 1.3.25 
      @tarojs/plugin-uglifyjs: 1.3.25 => 1.3.25 
      @tarojs/rn-runner: 1.3.25 => 1.3.25 
      @tarojs/router: 1.3.25 => 1.3.25 
      @tarojs/taro: 1.3.25 => 1.3.25 
      @tarojs/taro-alipay: 1.3.25 => 1.3.25 
      @tarojs/taro-h5: 1.3.25 => 1.3.25 
      @tarojs/taro-swan: 1.3.25 => 1.3.25 
      @tarojs/taro-tt: 1.3.25 => 1.3.25 
      @tarojs/taro-weapp: 1.3.25 => 1.3.25 
      @tarojs/webpack-runner: 1.3.25 => 1.3.25 
      eslint-config-taro: 1.3.25 => 1.3.25 
      eslint-plugin-taro: 1.3.25 => 1.3.25 
      nerv-devtools: ^1.4.0 => 1.5.5 
      nervjs: ^1.4.0 => 1.5.5 
      stylelint-config-taro-rn: 1.3.25 => 1.3.25 
      stylelint-taro-rn: 1.3.25 => 1.3.25 
~~~

### 补充信息

如果不返回 `null` 而改成返回空串 `''` 则不报错。

**Comment by shenghanqin** [comment]
taro里面请返回<block></block>

**Comment by mytharcher** [comment]
> taro里面请返回block></block

这个没太看明白，是不是被吞特殊字符了？猜测说的是返回字符串还是说一个空的 `Block` 组件？

~~~jsx
render() {
  return <Block />;
}
~~~

测试了可以编译通过，感谢！

**Comment by shenghanqin** [comment]
> > taro里面请返回block></block
> 
> 这个没太看明白，是不是被吞特殊字符了？猜测说的是返回字符串还是说一个空的 `Block` 组件？
> 
> ```js-jsx
> render() {
>   return <Block />;
> }
> ```
> 
> 测试了可以编译通过，感谢！

嘻嘻，对的。昨晚用的手机看的，Markdown的`代码`这个标点出不来。
