### ISSUE TITLE
使用 export * from './xxx' 来导出多个文件报错

### ISSUE THREAD

**Issue by zaaack** [NervJS/taro#496]
这是 ts 文件结构
![image](https://user-images.githubusercontent.com/5233940/44320341-1331ea00-a474-11e8-99df-faa25282edca.png)

这是 编译后的结构

![image](https://user-images.githubusercontent.com/5233940/44320332-fbf2fc80-a473-11e8-821c-020bb152ab93.png)

base.ts 等文件里定义都只有类型，在编译时忽略了，但是 domains/index.js 并没有，结果就是报错找不到模块。。orz

```ts
thirdScriptError 
 sdk uncaught third Error 
 module "domains/base.js" is not defined 
 Error: module "domains/base.js" is not defined
    at require (http://127.0.0.1:47704/appservice/__dev__/WAService.js:16:7026)
    at http://127.0.0.1:47704/appservice/__dev__/WAService.js:16:6881
    at http://127.0.0.1:47704/appservice/domains/index.js:13:10
    at require (http://127.0.0.1:47704/appservice/__dev__/WAService.js:16:7132)
    at http://127.0.0.1:47704/appservice/__dev__/WAService.js:16:6881
    at http://127.0.0.1:47704/appservice/widgets/SubscribeBar/index.js:40:15
    at require (http://127.0.0.1:47704/appservice/__dev__/WAService.js:16:7132)
    at http://127.0.0.1:47704/appservice/appservice?t=1534738887920:1121:9
```

**Comment by zaaack** [comment]
所有的 export * from 貌似都有问题，

**Comment by honpery** [comment]
我也遇到了相同问题。
这里感觉是因为export * from这种形式为判断为依赖项，所以没有进行编译，怀疑是tree-shaking的问题，期待解决。

我暂时用的hack方法是先导入，之后在导出：

```ts
import {Demo} from '';
export {
    Demo
}
```

**Comment by youngluo** [comment]
+1
