### ISSUE TITLE
TARO_BUILD_TYPE=ui  编译模式为 UI 库的时候，cli 不会处理 sass 的外部依赖

### ISSUE THREAD

**Issue by geraldlrh** [NervJS/taro#4968]
# 问题描述
使用的是 https://github.com/NervJS/taro-ui-sample 这里的模板，改了下 scss 文件，依赖外部npm 包的变量，然后打包，就报错了。

### 复现步骤

```scss
// xxx.scss 依赖 npm 包里的变量定义
@import '~@taro-ui/dist/style/variables/default.scss';

.demo {
color: $some-color;
}
```

### 期望行为

对于 npm 外部依赖，应该忽略不处理
### 报错信息

报错信息如下：
```bash
{ Error: ENOENT: no such file or directory, copyfile 'xxx/.temp/pages/result/~@taroui/dist/style/variables/default.scss' -> 'xxx/dist/h5/pages/result/~@taroui/dist/style/variables/default.scss'
    at Object.copyFileSync (fs.js:1723:3)
    at copyFileToDist (/usr/local/lib/node_modules/@tarojs/cli/dist/ui/common.js:181:8)
    at imports.map.importItem (/usr/local/lib/node_modules/@tarojs/cli/dist/ui/common.js:240:17)
    at Array.map (<anonymous>)
    at styleFiles.forEach.item (/usr/local/lib/node_modules/@tarojs/cli/dist/ui/common.js:238:31)
    at Array.forEach (<anonymous>)
    at analyzeStyleFilesImport (/usr/local/lib/node_modules/@tarojs/cli/dist/ui/common.js:221:16)
    at files.forEach.file (/usr/local/lib/node_modules/@tarojs/cli/dist/ui/common.js:213:17)
    at Array.forEach (<anonymous>)
    at Object.analyzeFiles (/usr/local/lib/node_modules/@tarojs/cli/dist/ui/common.js:188:11)
```

### 系统信息
  Taro CLI 2.0.0-beta.4 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm

**Comment by luckyadam** [comment]
最新版本已处理
