### ISSUE TITLE
微信小程序发布到线上后在 pc 端打开页面空白

### ISSUE THREAD

**Issue by ttsy** [NervJS/taro#5039]
### 问题描述

微信小程序发布到线上后在 pc 端打开页面空白。

### 复现步骤

小程序搜索【星火教育|专注中小学全科辅导】，进入首页后分享给另一个微信，然后另一个微信在 windows pc 端微信打开，页面是空白的。

### 期望行为

页面正常显示。

### 报错信息

线上小程序无法看到报错信息。

### 系统信息

![image](https://user-images.githubusercontent.com/14883651/70412517-edc55700-1a8f-11ea-84b4-2f3d975b880d.png)

### 补充信息

个人感觉是部分编译后的代码无法在 pc 端兼容导致的，但是无法确定是哪部分代码。

**Comment by Chen-jj** [comment]
@ttsy 这个只能在你的小程序中埋点上报报错信息来判断了，例如 componentDidCatchError 生命周期里上报，单凭白屏无法判断。

**Comment by shenghanqin** [comment]
@ttsy 这个建议你用Taro.showToast来慢慢寻找问题吧。有问题可以及时提出。

**Comment by BinZhiZhu** [comment]
这个问题关闭了么 同样的问题 体验版打开调试看到报错信息

```
thirdScriptError
TypeError
TypeError: Function("r","regeneratorRuntime = r") is not a function. (In 'Function("r","regeneratorRuntime = r")(e)', 'Function("r","regeneratorRuntime = r")' is undefined) 
at (app-service.js:8459:8589)
at 20 (app-service.js:8459:8600)
at __webpack_require__ (app-service.js:8449:684)
at 9 (app-service.js:8459:40832)
at __webpack_require__ (app-service.js:8449:684)
at 59 (app-service.js:8462:7864)
at __webpack_require__ (app-service.js:8449:684)
at 218 (app-service.js:8462:179)
at __webpack_require__ (app-service.js:8449:684)
at 572 (app-service.js:8462:7663)
at __webpack_require__ (app-service.js:8449:684)
at checkDeferredModules (app-service.js:8449:506)
at webpackJsonpCallback (app-service.js:8449:332)
at (app-service.js:8462:123)
at require (WAService.js:2:1717964)
at global code (app-service.js:8463:17)
```

这边报错貌似是babel-transform-runtime的问题 但是我们项目已经引入 仅pc打开会空白页面
