### ISSUE TITLE
运行H5项目报错

### ISSUE THREAD

**Issue by kk412027247** [NervJS/taro#5049]
### 问题描述

初始化项目之后，运行H5项目报错。

### 复现步骤

taro init demo3
yarn dev:h5

### 期望行为
正常运行H5项目

### 报错信息

```
开始编译项目 demo3
创建  发现文件  src\app.jsx
创建  发现文件  src\app.scss
创建  发现文件  src\index.html
创建  发现文件  src\actions\counter.js
创建  发现文件  src\constants\counter.js
创建  发现文件  src\reducers\counter.js
创建  发现文件  src\reducers\index.js
创建  发现文件  src\store\index.js
创建  发现文件  src\pages\index\index.jsx
创建  发现文件  src\pages\index\index.scss
{ ValidationError: CopyPlugin Invalid Options

options should NOT have fewer than 1 items

    at validateOptions (E:\tmd\demo3\node_modules\_schema-utils@1.0.0@schema-utils\src\validateOptions.js:32:11)
    at new CopyPlugin (E:\tmd\demo3\node_modules\_copy-webpack-plugin@5.1.0@copy-webpack-plugin\dist\index.js:26:30)
    at init (E:\tmd\demo3\node_modules\_webpack-chain@4.9.0@webpack-chain\src\Plugin.js:13:18)
    at Object.toConfig (E:\tmd\demo3\node_modules\_webpack-chain@4.9.0@webpack-chain\src\Plugin.js:47:22)
    at clean.Object.assign.plugins.plugins.values.map.plugin (E:\tmd\demo3\node_modules\_webpack-chain@4.9.0@webpack-chain\src\Config.js:125:61)
    at Array.map (<anonymous>)
    at module.exports.toConfig (E:\tmd\demo3\node_modules\_webpack-chain@4.9.0@webpack-chain\src\Config.js:125:40)
    at Object.<anonymous> (E:\tmd\demo3\node_modules\_@tarojs_webpack-runner@1.3.27@@tarojs\webpack-runner\dist\index.js:96:40)
    at Generator.next (<anonymous>)
    at fulfilled (E:\tmd\demo3\node_modules\_@tarojs_webpack-runner@1.3.27@@tarojs\webpack-runner\dist\index.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'ValidationError',
  message:
   'CopyPlugin Invalid Options\n\noptions should NOT have fewer than 1 items\n',
  errors:
   [ { keyword: 'minItems',
       dataPath: '',
       schemaPath: '#/minItems',
       params: [Object],
       message: 'should NOT have fewer than 1 items' } ] }
```

### 系统信息

```
  Taro CLI 1.3.27 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
```

**Comment by ninetowns** [comment]
有解决方案了吗，我也遇到了

**Comment by luckyadam** [comment]
删掉 config 配置中空的 `copy` 配置，模板已经更新了
![image](https://user-images.githubusercontent.com/1782542/70503694-f2a50c00-1b5e-11ea-9ae0-dcad62dcc27e.png)

**Comment by luckyadam** [comment]
Close via 7274ce2f9c644b9c1ad1770d447325a852deafe0

**Comment by xuesongde** [comment]
> 删掉 config 配置中空的 `copy` 配置，模板已经更新了
> ![image](https://user-images.githubusercontent.com/1782542/70503694-f2a50c00-1b5e-11ea-9ae0-dcad62dcc27e.png)

It's the right solution

**Comment by zhangkaidi** [comment]
Uncaught TypeError: Cannot read property 'charAt' of undefined
    at stripTrailingSlash (index.esm.js?debf:1687)
    at mountApis (index.esm.js?debf:2932)
    at eval (app.js?d0a8:30)
    at Module../.temp/app.js (app.js:915)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at Object.0 (app.js:2146)
    at __webpack_require__ (app.js:767)
    at app.js:902
    at app.js:905
浏览器还是报错呢

**Comment by luckyadam** [comment]
> Uncaught TypeError: Cannot read property 'charAt' of undefined
> at stripTrailingSlash (index.esm.js?debf:1687)
> at mountApis (index.esm.js?debf:2932)
> at eval (app.js?d0a8:30)
> at Module../.temp/app.js (app.js:915)
> at **webpack_require** (app.js:767)
> at fn (app.js:130)
> at Object.0 (app.js:2146)
> at **webpack_require** (app.js:767)
> at app.js:902
> at app.js:905
> 浏览器还是报错呢

cli 与项目依赖版本保持一致

**Comment by liyan0411** [comment]
我也遇到同样问题。
Uncaught TypeError: Cannot read property 'charAt' of undefined
    at stripTrailingSlash (index.esm.js?eb04:1687)
    at mountApis (index.esm.js?eb04:2932)
    at eval (app.js?d0a8:25)
    at Module../.temp/app.js (app.js:915)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at Object.0 (app.js:3742)
    at __webpack_require__ (app.js:767)
    at app.js:902
    at app.js:905

**Comment by cloudZQY** [comment]
检查一下cli的版本号和@tarojs/router的版本号是否对应，否则mountApis这个方法里面会报错

**Comment by yulrosy** [comment]
> 我也遇到同样问题。
> Uncaught TypeError: Cannot read property 'charAt' of undefined
> at stripTrailingSlash (index.esm.js?eb04:1687)
> at mountApis (index.esm.js?eb04:2932)
> at eval (app.js?d0a8:25)
> at Module../.temp/app.js (app.js:915)
> at **webpack_require** (app.js:767)
> at fn (app.js:130)
> at Object.0 (app.js:3742)
> at **webpack_require** (app.js:767)
> at app.js:902
> at app.js:905
> 
> 我本地检查版本了，是一致的，但是运行还是浏览器报这个错。什么问题呢

我也遇到了
