### ISSUE TITLE
全局安装或卸载taro-cli，报Maximum call stack size exceeded错误

### ISSUE THREAD

**Issue by litong534** [NervJS/taro#5077]
### 问题描述

I need to downgrade taro version from 1.3.26 to 1.2.26, but error happens

```sh
npm uninstall -g @tarojs/cli
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/litong/.npm/_logs/2019-12-13T03_14_37_025Z-debug.log
➜  ~ npm install @tarojs/cli@1.2.26 -g
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/litong/.npm/_logs/2019-12-13T03_15_06_157Z-debug.log
```

### 复现步骤

just like above

### 期望行为

I hope to downgrade correctly

### 系统信息

~ taro info
👽 Taro v2.0.0-beta.8

  Taro CLI 2.0.0-beta.8 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.1.6

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
npm不好用的话，你可以换成cnpm仓库，
我之前还发现了，如果网络环境不好的情况，也会出现这个问题。

**Comment by litong534** [comment]
> npm不好用的话，你可以换成cnpm仓库，
> 我之前还发现了，如果网络环境不好的情况，也会出现这个问题。

cnpm同样会遇到这个问题

```sh
cnpm uninstall -g @tarojs/cli
Unhandled rejection RangeError: Maximum call stack size exceededill install loa
    at RegExp.test (<anonymous>)
    at schemas.forEach.schema (/usr/local/lib/node_modules/cnpm/node_modules/npm/node_modules/aproba/index.js:39:16)
    at Array.forEach (<anonymous>)
    at validate (/usr/local/lib/node_modules/cnpm/node_modules/npm/node_modules/aproba/index.js:34:11)
    at flatNameFromTree (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install/flatten-tree.js:37:3)
    at flatNameFromTree (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install/flatten-tree.js:39:14)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
```

**Comment by litong534** [comment]
刚尝试了一下
```sh
cnpm install -g @tarojs/cli@1.2.26
```
成功了
