### ISSUE TITLE
TaroUI快应用构建错误 Module build failed

### ISSUE THREAD

**Issue by EngrZhou** [NervJS/taro#5152]
### 问题描述

使用 `yarn dev:quickapp`命令编译快应用时，出现构建错误；
而使用 `yarn dev:h5`命令编译，是能正常工作的。

### 复现步骤

1. 进入项目根目录，使用` yarn dev:quickapp`命令编译；
2. 观察控制台；

### 期望行为

快应用下能正常使用TaroUI

### 报错信息

```shell
[INFO] hap-toolkit: 0.6.11; babel: 7.7.7; webpack: 4.41.4;
[LOG] 当前minPlatformVersion >= 1040，平台采用v8版本为6.5+（对应chrome版本为65版+），工具将不再对V8 6.5版本支持的ES6代码进行转换
[INFO] 配置环境：{"NODE_PLATFORM":"native","NODE_PHASE":"dev"}
[INFO] 获取到app文件后缀: ux
[INFO] ### App Server ### 完成创建adb调试器。您可以通过usb线连入手机调试
[INFO] ### App Server ### 服务器地址: http://localhost:12306, http://10.18.49.79:12306
[INFO] ### App Server ### 请确保手机与App Server处于相同网段

生成HTTP服务器的二维码: http://0.0.0.0:12306
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄

█▄▄▄▄▄▄▄█▄▄▄▄██▄▄▄▄▄██▄██▄█

[INFO] ### App Server ### 手机设备(c813415f)被连入
[WARN] 标签slot的属性 `name` 值为空, 默认设置为缺省值 `default` /home/zhou/Project/QuickApps/TaroBug/dist/src/npm/@tarojs/components-qa/src/components/taro-page/index.ux@6,13
[WARN] 标签slot的属性 `name` 值为空, 默认设置为缺省值 `default` /home/zhou/Project/QuickApps/TaroBug/dist/src/npm/@tarojs/components-qa/src/components/taro-page/index.ux@15,15
[WARN] 标签slot的属性 `name` 值为空, 默认设置为缺省值 `default` /home/zhou/Project/QuickApps/TaroBug/dist/src/npm/@tarojs/components-qa/src/components/taro-page/index.ux@20,11
[LOG] ### App Loader ### build 目录构建完成
[LOG] ### App Loader ### dist目录签名并生成rpk文件：com.application.demo.debug.rpk
[ERRO] 构建错误 Module build failed (from ./node_modules/@hap-toolkit/dsl-xvm/lib/loader/ux-loader.js):
Error: 未知文件格式：.js
    at Object.loader (/home/zhou/Project/QuickApps/TaroBug/dist/node_modules/@hap-toolkit/dsl-xvm/lib/loader/ux-loader.js:1:2817)
[ERRO] 构建错误 Module build failed (from ./node_modules/@hap-toolkit/dsl-xvm/lib/loader/ux-loader.js):
Error: 未知文件格式：.js
    at Object.loader (/home/zhou/Project/QuickApps/TaroBug/dist/node_modules/@hap-toolkit/dsl-xvm/lib/loader/ux-loader.js:1:2817)
[ERRO] 构建错误 Module build failed (from ./node_modules/@hap-toolkit/dsl-xvm/lib/loader/ux-loader.js):
Error: 未知文件格式：.js
    at Object.loader (/home/zhou/Project/QuickApps/TaroBug/dist/node_modules/@hap-toolkit/dsl-xvm/lib/loader/ux-loader.js:1:2817)

```

### 系统信息

```shell
zhou@optiplex-7010:~/Project/QuickApps/TaroBug$ taro info
👽 Taro v2.0.0-beta.10


  Taro CLI 2.0.0-beta.10 environment info:
    System:
      OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 3.5.2 - /usr/bin/npm
    npmPackages:
      @tarojs/components: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/components-qa: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/mini-runner: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/router: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/taro: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/taro-alipay: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/taro-h5: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/taro-qq: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/taro-quickapp: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/taro-rn: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/taro-swan: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/taro-tt: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/taro-weapp: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/webpack-runner: 2.0.0-beta.10 => 2.0.0-beta.10 
      eslint-config-taro: 2.0.0-beta.10 => 2.0.0-beta.10 
      eslint-plugin-taro: 2.0.0-beta.10 => 2.0.0-beta.10 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.0.0-beta.10 => 2.0.0-beta.10 
      stylelint-taro-rn: 2.0.0-beta.10 => 2.0.0-beta.10 
    npmGlobalPackages:
      typescript: 3.7.4


```

### 补充信息

源码：`https://github.com/EngrZhou/TaroBug`

错误跟 [https://github.com/NervJS/taro/issues/5094](https://github.com/NervJS/taro/issues/5094)很像，但是使用了[https://github.com/NervJS/taro/pull/5147](https://github.com/NervJS/taro/pull/5147)本地修改测试依旧存在此问题。
@Issacpeng

**Comment by Issacpeng** [comment]
@EngrZhou  看了DEMO，与#5147是有关系，并且TARO-UI 快应用转换,还需要待这个PRhttps://github.com/NervJS/taro/pull/5058  REVIEW完之后才可以正常转换，AtTabsPane、AtSearchBar 还在适配中，会有一些属性丢失。
