### ISSUE TITLE
taro 2.0.0-beta.12编译小程序总报错，不能使用taro-ui的组件，提示找不到路径 

### ISSUE THREAD

**Issue by s2265681** [NervJS/taro#5209]
### 问题描述

taro编译小程序总报错，不能使用taro-ui的组件，提示找不到路径
### 复现步骤

![image](https://user-images.githubusercontent.com/41536679/71538300-b72e7e00-2963-11ea-9712-03a6ca33a3d2.png)
1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */
jsEnginScriptError
Component is not found in path "npm/taro-ui/dist/weapp/components/button/index" (using by "pages/me/me");onAppRoute
Error: Component is not found in path "npm/taro-ui/dist/weapp/components/button/index" (using by "pages/me/me")
    at G (http://127.0.0.1:40274/appservice/__dev__/WAService.js:1:1471356)
    at G (http://127.0.0.1:40274/appservice/__dev__/WAService.js:1:1471560)
    at http://127.0.0.1:40274/appservice/__dev__/WAService.js:1:1492600
    at Module.We (http://127.0.0.1:40274/appservice/__dev__/WAService.js:1:1493179)
    at Function.value (http://127.0.0.1:40274/appservice/__dev__/WAService.js:1:1578189)
    at Tt (http://127.0.0.1:40274/appservice/__dev__/WAService.js:1:1593990)
    at http://127.0.0.1:40274/appservice/__dev__/WAService.js:1:1597928
    at xt (http://127.0.0.1:40274/appservice/__dev__/WAService.js:1:1597995)
    at Function.<anonymous> (http://127.0.0.1:40274/appservice/__dev__/WAService.js:1:1602278)
    at i.<anonymous> (http://127.0.


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by s2265681** [comment]
版本信息
	  "@tarojs/components": "2.0.0-beta.12",
	  "@tarojs/components-qa": "2.0.0-beta.12",
	  "@tarojs/mobx": "2.0.0-beta.12",
	  "taro-ui": "^2.2.4"

**Comment by s2265681** [comment]
昨天还能使用，今天发现只要使用taro-ui的组件就会出这个问题，去掉时没有报错

**Comment by Chen-jj** [comment]
@s2265681 请按 issue 模板提供一切必要信息

**Comment by luckyadam** [comment]
没有复现问题，麻烦提供一个 demo 看看

**Comment by s2265681** [comment]
已解决 版本问题

**Comment by Norbert-Nayman** [comment]
> 已解决 版本问题

怎么解决的？

**Comment by jinjinwa** [comment]
总是遇到这个问题。。。

**Comment by zpzxgcr** [comment]
我也是啊 总是反复出现 而且这个错误根本无法定位追踪啊

**Comment by AizT** [comment]
这个怎么了，从官网一步步复制也能错？
