### ISSUE TITLE
v2.0.0-beta.14 taro.getIsUsingDiff is not a function

### ISSUE THREAD

**Issue by GaoYuJian** [NervJS/taro#5274]
### 报错信息

VM344:1 thirdScriptError
taro.getIsUsingDiff is not a function;at "pages/home/index" page lifeCycleMethod onLoad function
TypeError: taro.getIsUsingDiff is not a function
    at doUpdate (http://127.0.0.1:64854/appservice/vendors.js:4732:23)
    at mountComponent (http://127.0.0.1:64854/appservice/vendors.js:4660:3)
    at ge.initComponent (http://127.0.0.1:64854/appservice/vendors.js:4378:3)
    at ge.weappComponentConf.methods.onLoad (http://127.0.0.1:64854/appservice/vendors.js:4484:21)
    at ge.<anonymous> (WAService.js:1:1405397)
    at ge.p.__callPageLifeTime__ (WAService.js:1:1405142)
    at kt (WAService.js:1:1420451)
    at WAService.js:1:1423785
    at At (WAService.js:1:1424278)
    at Function.<anonymous> (WAService.js:1:1427668)

### 系统信息
Taro v2.0.0-beta.14

  Taro CLI 2.0.0-beta.14 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
    npmPackages:
      @tarojs/cli: 2.0.0-beta.14 => 2.0.0-beta.14 
      @tarojs/plugin-babel: 2.0.0-beta.14 => 2.0.0-beta.14 
      @tarojs/plugin-csso: 2.0.0-beta.14 => 2.0.0-beta.14 
      @tarojs/plugin-sass: 2.0.0-beta.14 => 2.0.0-beta.14 
      @tarojs/plugin-uglifyjs: 2.0.0-beta.14 => 2.0.0-beta.14 
      @tarojs/taro-weapp: ^2.0.0-beta.14 => 2.0.0-beta.14 
      @tarojs/webpack-runner: 2.0.0-beta.14 => 2.0.0-beta.14 
      eslint-config-taro: 2.0.0-beta.14 => 2.0.0-beta.14 
      eslint-plugin-taro: 2.0.0-beta.14 => 2.0.0-beta.14

**Comment by GaoYuJian** [comment]
应该是一些分包的版本没有正确安装，卸载重装保证所有包安装成2.0.0后好了
