### ISSUE TITLE
将taro代码打包成react native代码遇到错误

### ISSUE THREAD

**Issue by shebaoting** [NervJS/taro#5287]
### 问题描述

将taro代码打包成react native代码遇到错误。在cmd里运行yarn dev:rn之后，报以下错误

```js
D:\WWW\taro\class_miniprogram>yarn dev:rn
yarn run v1.15.0
$ npm run build:rn -- --watch

> newJsTaroApp@1.0.0 build:rn D:\WWW\taro\class_miniprogram
> taro build --type rn "--watch"

👽 Taro v1.3.35

开始编译项目 newJsTaroApp
编译  JSX       D:\WWW\taro\class_miniprogram\src\app.jsx
生成  JSX       D:\WWW\taro\class_miniprogram\rn_temp\app.js
编译  LESS      D:\WWW\taro\class_miniprogram\src\app.less

src/app.less
1:1     ‼  通配选择器会被 React Native 忽略 [stylelint]
70:1    ‼  通配选择器会被 React Native 忽略 [stylelint]

生成  生成样式文件  D:\WWW\taro\class_miniprogram\rn_temp\app_styles.js
编译  JS        D:\WWW\taro\class_miniprogram\src\dva.js
生成  JS        D:\WWW\taro\class_miniprogram\rn_temp\dva.js
拷贝  HTML      D:\WWW\taro\class_miniprogram\src\index.html
生成  HTML      D:\WWW\taro\class_miniprogram\rn_temp\index.html
编译  JS        D:\WWW\taro\class_miniprogram\src\models\index.js
生成  JS        D:\WWW\taro\class_miniprogram\rn_temp\models\index.js
编译  JS        D:\WWW\taro\class_miniprogram\src\request\request.js
生成  JS        D:\WWW\taro\class_miniprogram\rn_temp\request\request.js
编译  JS        D:\WWW\taro\class_miniprogram\src\utils\api.js
生成  JS        D:\WWW\taro\class_miniprogram\rn_temp\utils\api.js
编译  JS        D:\WWW\taro\class_miniprogram\src\utils\utils.js
生成  JS        D:\WWW\taro\class_miniprogram\rn_temp\utils\utils.js
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\index\banner1.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\banner1.svg
拷贝  PNG       D:\WWW\taro\class_miniprogram\src\img\index\bg.png
生成  PNG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\bg.png
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\index\bofang.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\bofang.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\index\bofang2.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\bofang2.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\index\bottomright.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\bottomright.svg
拷贝  PNG       D:\WWW\taro\class_miniprogram\src\img\index\china.png
生成  PNG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\china.png
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\index\download.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\download.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\index\free.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\free.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\index\headimg.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\headimg.svg
拷贝  PNG       D:\WWW\taro\class_miniprogram\src\img\index\history.png
生成  PNG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\history.png
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\index\hot.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\hot.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\index\hottem.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\hottem.svg
拷贝  PNG       D:\WWW\taro\class_miniprogram\src\img\index\living.png
生成  PNG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\living.png
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\index\living.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\living.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\index\menu.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\menu.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\index\more.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\more.svg
拷贝  PNG       D:\WWW\taro\class_miniprogram\src\img\index\sbg.png
生成  PNG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\sbg.png
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\index\searcher.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\searcher.svg
拷贝  PNG       D:\WWW\taro\class_miniprogram\src\img\index\short.png
生成  PNG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\short.png
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\index\shortswiper.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\shortswiper.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\index\tehui.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\tehui.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\index\topright.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\topright.svg
拷贝  JPG       D:\WWW\taro\class_miniprogram\src\img\index\tu.jpg
生成  JPG       D:\WWW\taro\class_miniprogram\rn_temp\img\index\tu.jpg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\mine\bucket.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\mine\bucket.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\mine\downman.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\mine\downman.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\mine\logout.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\mine\logout.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\mine\myorder.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\mine\myorder.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\mine\phone.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\mine\phone.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\mine\shezhi.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\mine\shezhi.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\mine\youhuiquan.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\mine\youhuiquan.svg
拷贝  PNG       D:\WWW\taro\class_miniprogram\src\img\study\222.png
生成  PNG       D:\WWW\taro\class_miniprogram\rn_temp\img\study\222.png
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\study\bofang3.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\study\bofang3.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\study\classdetail.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\study\classdetail.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\study\dianzan.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\study\dianzan.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\study\headimg.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\study\headimg.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\study\intro.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\study\intro.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\study\kongxin.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\study\kongxin.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\study\nostudy.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\study\nostudy.svg
拷贝  MP4       D:\WWW\taro\class_miniprogram\src\img\study\video.mp4
生成  MP4       D:\WWW\taro\class_miniprogram\rn_temp\img\study\video.mp4
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\study\wz.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\study\wz.svg
拷贝  SVG       D:\WWW\taro\class_miniprogram\src\img\study\xin.svg
生成  SVG       D:\WWW\taro\class_miniprogram\rn_temp\img\study\xin.svg
拷贝  PNG       D:\WWW\taro\class_miniprogram\src\img\tabbar\index.png
生成  PNG       D:\WWW\taro\class_miniprogram\rn_temp\img\tabbar\index.png
拷贝  PNG       D:\WWW\taro\class_miniprogram\src\img\tabbar\mine.png
生成  PNG       D:\WWW\taro\class_miniprogram\rn_temp\img\tabbar\mine.png
拷贝  PNG       D:\WWW\taro\class_miniprogram\src\img\tabbar\selectIndex.png
生成  PNG       D:\WWW\taro\class_miniprogram\rn_temp\img\tabbar\selectIndex.png
拷贝  PNG       D:\WWW\taro\class_miniprogram\src\img\tabbar\selectMine.png
生成  PNG       D:\WWW\taro\class_miniprogram\rn_temp\img\tabbar\selectMine.png
拷贝  PNG       D:\WWW\taro\class_miniprogram\src\img\tabbar\selectStudy.png
生成  PNG       D:\WWW\taro\class_miniprogram\rn_temp\img\tabbar\selectStudy.png
拷贝  PNG       D:\WWW\taro\class_miniprogram\src\img\tabbar\study.png
生成  PNG       D:\WWW\taro\class_miniprogram\rn_temp\img\tabbar\study.png
编译  JSX       D:\WWW\taro\class_miniprogram\src\pages\course\course.jsx
编译  JSX       D:\WWW\taro\class_miniprogram\src\pages\index\index.jsx
编译  JS        D:\WWW\taro\class_miniprogram\src\pages\index\models.js
生成  JS        D:\WWW\taro\class_miniprogram\rn_temp\pages\index\models.js
编译  JSX       D:\WWW\taro\class_miniprogram\src\pages\mine\mine.jsx
编译  JS        D:\WWW\taro\class_miniprogram\src\pages\mine\models.js
生成  JS        D:\WWW\taro\class_miniprogram\rn_temp\pages\mine\models.js
编译  JS        D:\WWW\taro\class_miniprogram\src\pages\study\model.js
生成  JS        D:\WWW\taro\class_miniprogram\rn_temp\pages\study\model.js
编译  JSX       D:\WWW\taro\class_miniprogram\src\pages\study\study.jsx
(node:4540) UnhandledPromiseRejectionWarning: TypeError: unknown: Cannot read property 'type' of undefined
    at PluginPass.JSXOpeningElement (C:\Users\th9th\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-plugin-transform-jsx-to-stylesheet@1.3.35@babel-plugin-transform-jsx-to-stylesheet\src\index.js:216:45)
    at newFn (C:\Users\th9th\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (C:\Users\th9th\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Users\th9th\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\Users\th9th\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (C:\Users\th9th\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (C:\Users\th9th\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (C:\Users\th9th\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (C:\Users\th9th\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\index.js:114:17)
    at NodePath.visit (C:\Users\th9th\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\context.js:115:19)
(node:4540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:4540) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 6.42s.
```

**Comment by Julyyq** [comment]
@shebaoting Taro用的这个库`babel-plugin-transform-jsx-stylesheet`是阿里的[rax](https://github.com/alibaba/rax)里的，在转换行内样式的时候有bug，你可以找到`src/index.js`里面的这块，稍加改动，让编译通过：
```
let expression = styleAttribute.value.expression;
if(!expression) return (加上这句，可以跳过这个bug，编译成功)
let expressionType = expression.type;
```

**Comment by Pines-Cheng** [comment]
问题已解决，使用了不规范的行列样式的写法：`style = "width:100px"`，改成对象的写法就好了。
