### ISSUE TITLE
[taro-2.0.1][ERRO] 构建错误 Module build failed

### ISSUE THREAD

**Issue by jiongrui** [NervJS/taro#5379]
### 问题描述

构建项目代码报错

### 复现步骤

yarn dev:quickapp

### 期望行为

能正常构建

### 报错信息

[ERRO] 构建错误 Module build failed (from ./node_modules/@hap-toolkit/dsl-xvm/lib/loader/style-loader.js):
Error: ENOENT: no such file or directory, open '/Users/cai/Documents/code/pepc-mp/dist/quickapp/src/npm/@tarojs/components-qa/src/common/css/common.css'
    at Object.openSync (fs.js:448:3)
    at Object.readFileSync (fs.js:348:35)
    at n.length.n.forEach.e (/Users/cai/Documents/code/pepc-mp/dist/quickapp/node_modules/@hap-toolkit/compiler/lib/style/process.js:1:1536)
    at Array.forEach (<anonymous>)
    at processImport (/Users/cai/Documents/code/pepc-mp/dist/quickapp/node_modules/@hap-toolkit/compiler/lib/style/process.js:1:1412)
    at Object.parse (/Users/cai/Documents/code/pepc-mp/dist/quickapp/node_modules/@hap-toolkit/compiler/lib/style/index.js:1:597)
    at parseStyle (/Users/cai/Documents/code/pepc-mp/dist/quickapp/node_modules/@hap-toolkit/compiler/lib/index.js:1:1776)
    at Object.module.exports (/Users/cai/Documents/code/pepc-mp/dist/quickapp/node_modules/@hap-toolkit/dsl-xvm/lib/loader/style-loader.js:1:665)

### 系统信息

 Taro v1.3.13

  Taro CLI 1.3.13 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
      Yarn: 1.21.1 - ~/.nvm/versions/node/v11.15.0/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.15.0/bin/npm
    npmPackages:
      @tarojs/components: 1.3.14 => 1.3.14 
      @tarojs/components-qa: ^2.0.1 => 2.0.1 
      @tarojs/plugin-babel: 1.3.14 => 1.3.14 
      @tarojs/plugin-csso: 1.3.14 => 1.3.14 
      @tarojs/plugin-sass: 1.3.14 => 1.3.14 
      @tarojs/plugin-uglifyjs: 1.3.14 => 1.3.14 
      @tarojs/router: 1.3.14 => 1.3.14 
      @tarojs/taro: ^2.0.1 => 2.0.1 
      @tarojs/taro-alipay: 1.3.14 => 1.3.14 
      @tarojs/taro-h5: 1.3.14 => 1.3.14 
      @tarojs/taro-qq: 1.3.14 => 1.3.14 
      @tarojs/taro-quickapp: 1.3.14 => 1.3.14 
      @tarojs/taro-swan: 1.3.14 => 1.3.14 
      @tarojs/taro-tt: 1.3.14 => 1.3.14 
      @tarojs/taro-weapp: 1.3.14 => 1.3.14 
      @tarojs/webpack-runner: 1.3.14 => 1.3.14 
      eslint-config-taro: 1.3.14 => 1.3.14 
      eslint-plugin-taro: 1.3.14 => 1.3.14 
      nerv-devtools: ^1.4.0 => 1.5.6 
      nervjs: ^1.4.0 => 1.5.6 
      stylelint-config-taro-rn: 1.3.14 => 1.3.14 
      stylelint-taro-rn: 1.3.14 => 1.3.14

**Comment by luckyadam** [comment]
升级到 1.3.35 试试

**Comment by jiongrui** [comment]
> cli 与项目依赖版本保持一致，你这里 `@tarojs/components-qa` 版本都 2.0.1 了

好的。试了一下，解决了，谢谢！
