### ISSUE TITLE
[taro-2.0.2]QQ小程序编译后空白，微信可以

### ISSUE THREAD

**Issue by Jetereting** [NervJS/taro#5386]
taro info:
```
terMaker2 git:(master) ✗ taro info
👽 Taro v2.0.2


  Taro CLI 2.0.2 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 13.6.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.0.2 => 2.0.2
      @tarojs/components-qa: 2.0.2 => 2.0.2
      @tarojs/mini-runner: 2.0.2 => 2.0.2
      @tarojs/router: 2.0.2 => 2.0.2
      @tarojs/taro: 2.0.2 => 2.0.2
      @tarojs/taro-alipay: 2.0.2 => 2.0.2
      @tarojs/taro-h5: 2.0.2 => 2.0.2
      @tarojs/taro-qq: 2.0.2 => 2.0.2
      @tarojs/taro-quickapp: 2.0.2 => 2.0.2
      @tarojs/taro-rn: 2.0.2 => 2.0.2
      @tarojs/taro-swan: 2.0.2 => 2.0.2
      @tarojs/taro-tt: 2.0.2 => 2.0.2
      @tarojs/taro-weapp: 2.0.2 => 2.0.2
      @tarojs/webpack-runner: 2.0.2 => 2.0.2
      eslint-config-taro: 2.0.2 => 2.0.2
      eslint-plugin-taro: 2.0.2 => 2.0.2
      nerv-devtools: ^1.5.6 => 1.5.6
      nervjs: ^1.5.6 => 1.5.6
      stylelint-config-taro-rn: 2.0.2 => 2.0.2
      stylelint-taro-rn: 2.0.2 => 2.0.2
```

![image](https://user-images.githubusercontent.com/11585188/73048632-c8ac6c80-3eb4-11ea-8869-eec4188b549e.png)

```
VM20:206 thirdScriptError 
 sdk uncaught third Error 
 regeneratorRuntime is not defined 
 ReferenceError: regeneratorRuntime is not defined
    at http://127.0.0.1:51564/appservice/vendors.js:8550:52
    at Object.srcConstantConstantTsx (http://127.0.0.1:51564/appservice/vendors.js:8582:8)
    at __webpack_require__ (http://127.0.0.1:51564/appservice/runtime.js:99:31)
    at Object.srcComponentsUserHeadIndexTsx (http://127.0.0.1:51564/appservice/components/userHead/index.js:88:21)
    at __webpack_require__ (http://127.0.0.1:51564/appservice/runtime.js:99:31)
    at checkDeferredModules (http://127.0.0.1:51564/appservice/runtime.js:61:26)
    at Array.webpackJsonpCallback [as push] (http://127.0.0.1:51564/appservice/runtime.js:46:20)
    at http://127.0.0.1:51564/appservice/components/userHead/index.js:5:49
    at require (http://127.0.0.1:51564/appservice/__dev__/QLogic.js:1:857033)
    at <anonymous>:63:9
```

components/userHead/index.tsx :
```
import Taro from '@tarojs/taro'
import { ClCard, ClAvatar } from 'mp-colorui'
import { View, Text } from '@tarojs/components'
import constant from '../../constant/constant'
import iconImg from '../../assets/images/icon.jpg'

export default function UserHead(props) {
    this.state = ({
        uid: constant.getUserInfo().uid
    })
    return (
        <ClCard>
            <View style='display: flex;justify-content: center;align-items: stretch;'>
                <ClAvatar headerArray={[{ url: JSON.parse(constant.getUserInfo().thirdInfo).avatarUrl || iconImg }]} shape='round' size='xlarge' shadow />
                <View style='display: flex;flex-direction: column;margin-left: 27PX;'>
                    {/* 已登录 */}
                    <View style={'height:50%;display: ' + (this.state.uid ? 'flex;' : 'none;') + 'align-items: center;'}>
                        <Text style={'font-size:15PX;'}>{JSON.parse(constant.getUserInfo().thirdInfo).nickName || constant.getUserInfo().name || '昵称'}</Text>
                    </View>
                    <View style={'height:50%;display: ' + (this.state.uid ? 'flex;' : 'none;') + 'align-items: center;'}>
                        <Text style='font-size:24PX;'>解析券: {props.points || '0'}</Text>
                    </View>
                    {/* 未登录 */}
                    <View style={'display: ' + (this.state.uid ? 'none;' : 'flex;') + 'height:100%;align-items: center;'} onClick={() => {
                        Taro.redirectTo({
                            url: '/pages/user/chooseLogin'
                        })
                    }}>
                        <Text style={'font-size:20PX;color: #0081ff;'}>{'登录'}</Text>
                    </View>
                </View>
            </View>
        </ClCard>
    )
}


UserHead.defaultProps = {
    points: 0,
}
```

编译后的userHeard>index.js:
```js
(qq["webpackJsonp"] = qq["webpackJsonp"] || []).push([["components/userHead/index"],{

/***/ "./src/assets/images/icon.jpg":
/*!************************************!*\
  !*** ./src/assets/images/icon.jpg ***!
  \************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAoHBwgHBgoICAgLCgoLDhgQDg0NDh0VFhEYIx8lJCIfIiEmKzcvJik0KSEiMEExNDk7Pj4+JS5ESUM8SDc9Pjv/2wBDAQoLCw4NDhwQEBw7KCIoOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozv/wgARCADIAMgDAREAAhEBAxEB/8QAHAABAAIDAQEBAAAAAAAAAAAAAAYHAQQFAgMI/8QAGgEBAAIDAQAAAAAAAAAAAAAAAAEDAgQGBf/aAAwDAQACEAMQAAAAuYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGEV0x4s1SdbOYzAAAAAAAAAAwfm3PzOvdz/iLLH1+vnAAAAAAAAAAPKPzVZ5fYu57bmudandToAAAAAAAAAHlH5ps8vs3c9tzVOtTu50AAAAAAAAADEPzPn5fa2Oe25qmep3PcTxDyifJ9mQAAAADBpnDOGjkThAs/L7V3hdCdWM1+3vNfcy1cMt6nqbtw2spAAAAArqFUW+H1s9Dbz1fup9zH0mv1NWEggfLV7C8MPUykAAAACuJis7ualNvi4yrxEDJgAA+Wr2F4YeplIAAAAFbzFaXc1KbvD8sAAAAPlq9heGHqZSAAAABW8xWl3NSm7w/LAAAAD5avYXhh6mUgAAAAVtMVrdzUpu8PywAAAA+Wr2F4YeplIAAAAFbTFa3c1KbvD8sAAAAPlq9heGHqZSAAAABWsxW13NSm7w/LAZZEEgjMPM2eNXrbtw9L0kAAAACtJiububk1vhYnHOOe3F+1GzuxsbWG3uNnbr2dtfBottUyAAAAAVocJVN8tHbbO3jsZSSANc+xBS1gAAAAAVmccspJiSMFenTOiQAssixawAAAAAKzOOWUcM4hNyBFhHxIwahHz2XUAAAAACAkBJYbp3SBE0JeADWPsewAAAAACLn0JIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//EAEgQAAEDAgICDAkJBgcAAAAAAAECAwQFBgARB7IQEiEwMTM2QVFyc3QTFTI3YXWCscEUICI0NUBHcZFCYqGz0dIkUFJggZLi/9oACAEBAAE/AP8APatpipNNqcuAxSp8p+I8tlfAE5pw/pkrrv1K1Qjtnir4DFs6U6DXyIso+Kp/OxJOqv7vJWtF5XGtBIPjJ7+YrFOUiWF+GSc0ZbqDln/D0Yq9JgvwH1uR0rcQhSkOEkKTkMxujGiN117R3BLrpWQt3X+7S+V1xesXv5isUXge9n44qH2ZK7JeqcaHPNxC7V7X+7P8qrg9YO66sUXge9n44qH2ZK7JeqcaHPNxC7V7X+7O8p69393XViicL3s/HFQ+zZXZL1TjRTPhwdGsFcuWwwNu9xywj9s4maQ7QhcbcUE9ivwupniZpps9jiXZkzsGP7ynFG0x21VJxiSfD0z/AELl5BBwhxLiAtCgpKhmCDmCN+lVemwfrlRiR+1fSj3nErSVZsLjK/GX2ObuqDiXputNjiBPldRjD+nFb32dbD7vavYiR50ufUJ7sUtmS+p7adYk5DnOWeKLwvez8cPsh+O60TtQtBTn0ZjLDVoQuh93DFtwU7qISPb/APRwzTG2xm20y36Epy9wxKo0acztXwFnq7qfyOeNHUypUW/GLeanvLpj7S1+BX6Ek77pscWzYyC0sgma3qrxGoNMPGlwr/eVuH9MM21DT5MJv2z/AHHDNLQjyUsNEcwTl7hgQ07XddIV0BOY9+PkrO1/bz6wy92AlAJUlCUqPlKGeavz2CczmfmWj54qd3VzUXvunHkI139vVXgYc4xX5nerR88VO7q5qL33TlyFZ7+3qr2HONV1jvVo+eKnd1c1F77pz5Cs9/b1F7C+NX1jvVo+eKnd1c1F77p05Csd/b1F7C+NX1jvVo+eKnd1c1F77p15Dsd/RqL2HONX1jvVo+eKnd1c1F77p15Dsd/RqObDnGr6x+bubP8AzgAqOQBJ6Bi1mi3phgBYKCYrmovfdOvIeN6xRqOYcacZcKHUFChzEYWc3FHpJ2EpUs5JSVHoAzw3Sqi7ltIT5B5y2QP1OG7XqznCwlsdKnB8MNWbLPGyWUdUFX9MNWWwONmOL6gCf64atWlN+UhxzrrPwyw1RaYz5EJn2k7b34babaGTbaUDoSMsfj5TvV51XN9078hovrFGo5h5hqQjaOoC0+nmw3a9KRwsKcPStw/DLDdIpzQARBY/MoBP6nCUJQnaoSEjoAy+dPnNU+KqQ8dwbgTzqPRhtaXW0uIOaVgEHpBx+PtO9XK1XN9078honrFGo584kJBJIAG6ScO3/XZ9ZmLtmhmr0iBkh0gHbrV0oIxR9J9vVI+AlvLpcrgLUz6A/wC2Lqu6Ba9I+WOrDzrv1ZkHddP9uKNctUroks1gqEqM6SWlDabUK/d5ssW9J+U0ZnnU1m2fRlwfwyx+PtO9XK1XN908ciIfrJGo5s3NdtKtaH4ae9m8sEtMI8tzFp36/Uqs9Sq/E8WzHcnoiF5pC21AEJ2LyrM6uVZFk28v/Eyfrr/Mw3i3KBCtmis0uDxbXCvnWrnUcV206FcjZFVpjL6+ZzgcH5LGRxRdEFDo1dFSLz8xlndYiv8AA2vF7aNajOrD9xW1PDE53joy/IdxQr+NrLl066abLhP8KQhGLZrzF16Y4FVgMPoYREW0S8joSvfdL9DqVfs9pilRDKeYlpfWhHCUBC8Uy5YVQX4BzOLK4FMPbhz6AcXPfxjTPEVtsGqVlf0MkbqGcWlo1+STPHt1P+NKwvmXuoYxdlkUe8WAJ7S0SWgQzJZ8tGJ0bSNZTDkVg+PoKxtGH+F1nFgWcLVpRdlZO1Wb9OY/82TBiTNoZMVl8tnNHhWwrI+jPCEJbSEoSEpHAAMgN+umwqDdqCZ0XaSuaWzkHMWlZVIs+H4KAzm+ePlOeW7/AL1//8QAIxEAAgECBgMBAQAAAAAAAAAAAAECETADEhMhMkAQIDFQcP/aAAgBAgEBPwD91GXsRI7k4deJEl868SI/nXiIl89KCXSiRGZDIZDIhql1CRkFAoU98XldQreLyuoVvF5XUK3i8rqFbxeV1Ct4vK6he2/nYoib3FcQvNSpqo1UahqFWVZW/qM1H2Koqv5//8QALREAAQIEBAQFBQEAAAAAAAAAAAECAwQRQQUSMDETNEBRECAhMjMiI0JQcIH/2gAIAQMBAT8A/eviI0Wahdxrs23Tzy0JhcmxJzkXMjaidL3J6xOWJX529N3J6xOWJX529PPelCc9qEqn3WiIpQX0uNo65ToKixWtuTkZr9lJv2oQomR6KOxSIo6fjuuPmnO3cQ510NaopJTHHZmL6iLlqRJ56VoOxF63HTKu3U4ynFHvzCeXCeXLalNx1KqOcnkp5sJ5ctquHCaOE8uW1XDtxNHCeXLarh24mjhPLltVw7cTRwnly2q4dv40Two4+kop/gjUUwtHNg0UTfVcijtxEURjnWGyj3DcNjrYbg713dQbgrLvG4TLpulRsnAT8RsGElhMrUogmog+EiiYbASw2Tlm2MjexROlqVUov8//AP/Z"

/***/ }),

/***/ "./src/components/userHead/index.tsx":
/*!*******************************************!*\
  !*** ./src/components/userHead/index.tsx ***!
  \*******************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";


Object.defineProperty(exports, "__esModule", {
  value: true
});

var _slicedToArray = function () { function sliceIterator(arr, i) { var _arr = []; var _n = true; var _d = false; var _e = undefined; try { for (var _i = arr[Symbol.iterator](), _s; !(_n = (_s = _i.next()).done); _n = true) { _arr.push(_s.value); if (i && _arr.length === i) break; } } catch (err) { _d = true; _e = err; } finally { try { if (!_n && _i["return"]) _i["return"](); } finally { if (_d) throw _e; } } return _arr; } return function (arr, i) { if (Array.isArray(arr)) { return arr; } else if (Symbol.iterator in Object(arr)) { return sliceIterator(arr, i); } else { throw new TypeError("Invalid attempt to destructure non-iterable instance"); } }; }();

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

var _get = function get(object, property, receiver) { if (object === null) object = Function.prototype; var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent === null) { return undefined; } else { return get(parent, property, receiver); } } else if ("value" in desc) { return desc.value; } else { var getter = desc.get; if (getter === undefined) { return undefined; } return getter.call(receiver); } };

var _taroQq = __webpack_require__(/*! @tarojs/taro-qq */ "./node_modules/@tarojs/taro-qq/index.js");

var _taroQq2 = _interopRequireDefault(_taroQq);

var _constant = __webpack_require__(/*! ../../constant/constant */ "./src/constant/constant.tsx");

var _constant2 = _interopRequireDefault(_constant);

var _icon = __webpack_require__(/*! ../../assets/images/icon.jpg */ "./src/assets/images/icon.jpg");

var _icon2 = _interopRequireDefault(_icon);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

var UserHead = function (_Taro$Component) {
  _inherits(UserHead, _Taro$Component);

  function UserHead() {
    _classCallCheck(this, UserHead);

    var _this = _possibleConstructorReturn(this, (UserHead.__proto__ || Object.getPrototypeOf(UserHead)).apply(this, arguments));

    _this.$usedState = ["anonymousState__temp", "anonymousState__temp2", "$compid__16", "props", "uid"];
    _this.customComponents = ["ClCard", "ClAvatar"];
    return _this;
  }

  _createClass(UserHead, [{
    key: '_constructor',
    value: function _constructor(props) {
      _get(UserHead.prototype.__proto__ || Object.getPrototypeOf(UserHead.prototype), '_constructor', this).call(this, props);
      this.$$refs = new _taroQq2.default.RefsArray();
    }
  }, {
    key: '_createData',
    value: function _createData() {
      this.__state = arguments[0] || this.state || {};
      this.__props = arguments[1] || this.props || {};
      var __isRunloopRef = arguments[2];
      var __prefix = this.$prefix;
      ;

      var _genCompid = (0, _taroQq.genCompid)(__prefix + "$compid__16"),
          _genCompid2 = _slicedToArray(_genCompid, 2),
          $prevCompid__16 = _genCompid2[0],
          $compid__16 = _genCompid2[1];

      var props = this.__props;
      this.__state = {
        uid: _constant2.default.getUserInfo().uid
      };
      var anonymousState__temp = [{ url: JSON.parse(_constant2.default.getUserInfo().thirdInfo).avatarUrl || _icon2.default }];
      var anonymousState__temp2 = JSON.parse(_constant2.default.getUserInfo().thirdInfo).nickName || _constant2.default.getUserInfo().name || '昵称';
      this.anonymousFunc0 = function () {
        _taroQq2.default.redirectTo({
          url: '/pages/user/chooseLogin'
        });
      };
      _taroQq.propsManager.set({
        "headerArray": anonymousState__temp,
        "shape": "round",
        "size": "xlarge",
        "shadow": true
      }, $compid__16, $prevCompid__16);
      Object.assign(this.__state, {
        anonymousState__temp: anonymousState__temp,
        anonymousState__temp2: anonymousState__temp2,
        $compid__16: $compid__16,
        props: props
      });
      return this.__state;
    }
  }, {
    key: 'anonymousFunc0',
    value: function anonymousFunc0(e) {
      ;
    }
  }]);

  return UserHead;
}(_taroQq2.default.Component);

UserHead.$$events = ["anonymousFunc0"];
UserHead.$$componentPath = "components/userHead/index";
UserHead.defaultProps = {
  points: 0
};
exports.default = UserHead;

Component(__webpack_require__(/*! @tarojs/taro-qq */ "./node_modules/@tarojs/taro-qq/index.js").default.createComponent(UserHead));

/***/ })

},[["./src/components/userHead/index.tsx","runtime","vendors"]]]);
```

**Comment by Jetereting** [comment]
不知道是不是QQ小程序工具的原因，我记得没升级工具和 taro 的时候还可以

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/async-await.html

**Comment by Jetereting** [comment]
> https://nervjs.github.io/taro/docs/async-await.html

Thanks for your guidance,I read the document, but it still doesn't work.
![image](https://user-images.githubusercontent.com/11585188/73148808-216c4700-40f9-11ea-8985-4ebe289de2f4.png)


![image](https://user-images.githubusercontent.com/11585188/73148478-8b83ec80-40f7-11ea-85cf-c21b11d15703.png)

one of constant.tsx
```tsx
  //更新用户完成任务
  async upDoneCount() {
    await Taro.request({
      method: 'POST',
      url: baseUrl + '/doneCountPoints',
      data: {
        uid: this.getUserInfo().uid,
      },
    }).then(res => {
      if (res.statusCode != 200) {
        return
      }
      Taro.setStorage({ key: 'doneCountPoints', data: res.data })
    })
  },
```
babel of config/index.js
```js
  plugins: {
    babel: {
      sourceMap: true,
      presets: [
        ['env', {
          modules: false
        }]
      ],
      plugins: [
        'transform-decorators-legacy',
        'transform-class-properties',
        'transform-object-rest-spread',
        ['transform-runtime', {
          "helpers": false,
          "polyfill": false,
          "regenerator": true,
          "moduleName": 'babel-runtime'
        }]
      ]
    }
  },
```
![image](https://user-images.githubusercontent.com/11585188/73148904-93449080-40f9-11ea-92c9-13c04aee3dfe.png)

**Comment by Jetereting** [comment]
I read https://nervjs.github.io/taro/docs/migrate-to-2.html 
It work! thanks

**Comment by Jetereting** [comment]
@luckyadam  我发现 用 npm run dev:qq  在QQ运行效果反而不好 经常用莫名的问题，而用 npm run dev:weapp 却可以微信端呈现的一致

**Comment by Jetereting** [comment]
npm run build:weapp 效果也很差，还是 npm run dev:weapp 好
