### ISSUE TITLE
【taro2.0.3】微信开发工具打开，有错误TypeError: Cannot read property 'Array' of undefined

### ISSUE THREAD

**Issue by alpha-hxb** [NervJS/taro#5450]
### 问题描述

升级taro2.0.3后，编译成

### 复现步骤
使用默认模版和mobx的模版，出现的是同样的问题
暂时不知道如何复现
目前是引入了公司自己的一个js库@xxxxxxx/query_condition_helper/uglified.js 
但是之前再1.3的taro中没有这个问题

```js

```

### 期望行为

可以在微信发工具中，正常查看

### 报错信息

thirdScriptError
Cannot read property 'Array' of undefined
TypeError: Cannot read property 'Array' of undefined
    at runInContext (http://127.0.0.1:13104/appservice/vendors.js:11307:198)
    at http://127.0.0.1:13104/appservice/vendors.js:20258:7
    at Object.<anonymous> (http://127.0.0.1:13104/appservice/vendors.js:20270:14)
    at Object../node_modules/lodash/lodash.js (http://127.0.0.1:13104/appservice/vendors.js:20271:30)
    at __webpack_require__ (http://127.0.0.1:13104/appservice/runtime.js:225:23)
    at Object../node_modules/@xxxxxxx/query_condition_helper/uglified.js (http://127.0.0.1:13104/appservice/vendors.js:1465:9)
    at __webpack_require__ (http://127.0.0.1:13104/appservice/runtime.js:225:23)
    at Object.srcServicesApiJs (http://127.0.0.1:13104/appservice/app.js:435:35)
    at __webpack_require__ (http://127.0.0.1:13104/appservice/runtime.js:225:23)
    at Object.srcModelsPersonJs (http://127.0.0.1:13104/appservice/app.js:267:16)

### 系统信息

 Taro CLI 2.0.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.21.1 - C:\Users\xxxx\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD

**Comment by luckyadam** [comment]
项目依赖也升级到 2.0.3 了么

**Comment by alpha-hxb** [comment]
> 项目依赖也升级到 2.0.3 了么

升级了，h5和的页面可以生成，没啥问题。单独建了个页面生成想做成小程序的时候，微信开发工具里报的错误

**Comment by alpha-hxb** [comment]
升级到2.0.4没有这个错误了
