### ISSUE TITLE
taro 从1.3升级到2.0.4后 编译报错了

### ISSUE THREAD

**Issue by a821262922** [NervJS/taro#5496]
编译报错
`编译  发现组件  src/components/sale/addFriendModal.tsx
⠴ 正在编译...SyntaxError: Unexpected token (1:5)
    at Parser.pp$4.raise (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:2825:15)
    at Parser.pp.unexpected (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:689:10)
    at Parser.pp.expect (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:683:28)
    at Parser.pp$3.parseParenAndDistinguishExpression (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:2311:38)
    at Parser.pp$3.parseExprAtom (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:2230:43)
    at Parser.pp$3.parseExprSubscripts (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:2089:21)
    at Parser.pp$3.parseMaybeUnary (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:2066:19)
    at Parser.pp$3.parseExprOps (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:2010:21)
    at Parser.pp$3.parseMaybeConditional (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:1993:21)
    at Parser.pp$3.parseMaybeAssign (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:1968:21)
    at Parser.pp$3.parseExpression (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:1933:21)
    at Parser.pp$1.parseStatement (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:877:47)
    at Parser.pp$1.parseTopLevel (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:746:23)
    at Parser.parse (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:553:17)
    at Function.parse (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:576:37)
    at Function.parse (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/lib/Parser.js:2396:22) {
  pos: 5,
  loc: Position { line: 1, column: 5 },
  raisedAt: 6
}
SyntaxError: Unexpected token (1:5)
    at Parser.pp$4.raise (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:2825:15)
    at Parser.pp.unexpected (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:689:10)
    at Parser.pp.expect (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:683:28)
    at Parser.pp$3.parseParenAndDistinguishExpression (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:2311:38)
    at Parser.pp$3.parseExprAtom (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:2230:43)
    at Parser.pp$3.parseExprSubscripts (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:2089:21)
    at Parser.pp$3.parseMaybeUnary (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:2066:19)
    at Parser.pp$3.parseExprOps (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:2010:21)
    at Parser.pp$3.parseMaybeConditional (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:1993:21)
    at Parser.pp$3.parseMaybeAssign (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:1968:21)
    at Parser.pp$3.parseExpression (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:1933:21)
    at Parser.pp$1.parseStatement (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:877:47)
    at Parser.pp$1.parseTopLevel (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:746:23)
    at Parser.parse (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:553:17)
    at Function.parse (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/node_modules/acorn/dist/acorn.js:576:37)
    at Function.parse (/Users/shensz/Documents/grow/grow_mp/node_modules/webpack/lib/Parser.js:2396:22) {
  pos: 5,
  loc: Position { line: 1, column: 5 },
  raisedAt: 6
}
✅  编译成功，请打开微信小程序开发者工具进行查看

监听文件修改中...

`
是按着官方文档更新库的
还有跟着文档去覆盖babel的，
也尝试过 ` npm i --save regenerator-runtime@0.11.1`
一样失败了

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/migrate-to-2.html
看下文档，如果还是有问题，提供一个 demo 看下

**Comment by xuchong0211** [comment]
我也出现同样的错误
![image](https://user-images.githubusercontent.com/17978432/74944371-e546b080-5430-11ea-8c56-7153943d57f1.png)

**Comment by xuchong0211** [comment]
编译  发现组件  src/component/products/tabScrollView.js
编译  发现页面  src/pages/events/index.js
编译  发现组件  src/component/event/announcement/index.js
⠹ 正在编译...{ SyntaxError: Unexpected token (1:6)
    at Parser.pp$4.raise (/Users/PRB/demo/taroHooks/demo/node_modules/@tarojs/mini-runner/node_modules/acorn/dist/acorn.js:2825:15)
    at Parser.pp.unexpected (/Users/PRB/demo/taroHooks/demo/node_modules/@tarojs/mini-runner/node_modules/acorn/dist/acorn.js:689:10)
    at Parser.pp.expect (/Users/PRB/demo/taroHooks/demo/node_modules/@tarojs/mini-runner/node_modules/acorn/dist/acorn.js:683:28)
    at Parser.pp$3.parseParenAndDistinguishExpression (/Users/PRB/demo/taroHooks/demo/node_modules/@tarojs/mini-runner/node_modules/acorn/dist/acorn.js:2311:38)
    at Parser.pp$3.parseExprAtom (/Users/PRB/demo/taroHooks/demo/node_modules/@tarojs/mini-runner/node_modules/acorn/dist/acorn.js:2230:43)
    at Parser.pp$3.parseExprSubscripts (/Users/PRB/demo/taroHooks/demo/node_modules/@tarojs/mini-runner/node_modules/acorn/dist/acorn.js:2089:21)
    at Parser.pp$3.parseMaybeUnary (/Users/PRB/demo/taroHooks/demo/node_modules/@tarojs/mini-runner/node_modules/acorn/dist/acorn.js:2066:19)
    at Parser.pp$3.parseExprOps (/Users/PRB/demo/taroHooks/demo/node_modules/@tarojs/mini-runner/node_modules/acorn/dist/acorn.js:2010:21)
    at Parser.pp$3.parseMaybeConditional (/Users/PRB/demo/taroHooks/demo/node_modules/@tarojs/mini-runner/node_modules/acorn/dist/acorn.js:1993:21)
    at Parser.pp$3.parseMaybeAssign (/Users/PRB/demo/taroHooks/demo/node_modules/@tarojs/mini-runner/node_modules/acorn/dist/acorn.js:1968:21)
    at Parser.pp$3.parseExpression (/Users/PRB/demo/taroHooks/demo/node_modules/@tarojs/mini-runner/node_modules/acorn/dist/acorn.js:1933:21)
    at Parser.pp$1.parseStatement (/Users/PRB/demo/taroHooks/demo/node_modules/@tarojs/mini-runner/node_modules/acorn/dist/acorn.js:877:47)
    at Parser.pp$1.parseTopLevel (/Users/PRB/demo/taroHooks/demo/node_modules/@tarojs/mini-runner/node_modules/acorn/dist/acorn.js:746:23)
    at Parser.parse (/Users/PRB/demo/taroHooks/demo/node_modules/@tarojs/mini-runner/node_modules/acorn/dist/acorn.js:553:17)
    at Function.parse (/Users/PRB/demo/taroHooks/demo/node_modules/@tarojs/mini-runner/node_modules/acorn/dist/acorn.js:576:37)
    at Function.parse (/Users/PRB/demo/taroHooks/demo/node_modules/@tarojs/mini-runner/node_modules/webpack/lib/Parser.js:2396:22) pos: 6, loc: Position { line: 1, column: 6 }, raisedAt: 7 }

**Comment by xuchong0211** [comment]
demo@1.0.0 /Users/PRB/demo/taroHooks/demo
├─┬ @tarojs/cli@2.0.4
│ └─┬ @tarojs/transformer-wx@2.0.4
│   └─┬ eslint@5.16.0
│     └─┬ espree@5.0.1
│       ├── acorn@6.4.0 
│       └─┬ acorn-jsx@5.1.0
│         └── acorn@7.1.0  extraneous
├─┬ @tarojs/mini-runner@2.0.4
│ └─┬ webpack@4.41.6
│   └── acorn@6.4.0 
├─┬ @tarojs/webpack-runner@2.0.4
│ └─┬ webpack@4.28.4
│   ├── acorn@5.7.3 
│   └─┬ acorn-dynamic-import@3.0.0
│     └── acorn@5.7.3  deduped
└─┬ eslint@6.8.0
  └─┬ espree@6.1.2
    └── acorn@7.1.0 

npm ERR! extraneous: acorn@7.1.0 /Users/PRB/demo/taroHooks/demo/node_modules/@tarojs/transformer-wx/node_modules/acorn-jsx/node_modules/acorn
PRB:demo PRB$

**Comment by youngluo** [comment]
+1

**Comment by igauch** [comment]
+1

**Comment by Garfield550** [comment]
不要总是 +1 啊，也要把升级时做了什么操作，改了什么文件，配置文件信息，会复现的代码发上来呀。

**Comment by xuzpeng** [comment]
defineConstants 配置改下，改成类似：defineConstants: {a: JSON.stringify('a')}，就可以了
