### ISSUE TITLE
Taro v3.0.0-alpha.4 初始化vue/ts版 报错

### ISSUE THREAD

**Issue by libn-net** [NervJS/taro#5512]
/Users/libn/.nvm/versions/node/v12.14.1/bin/node /Users/libn/.nvm/versions/node/v12.14.1/lib/node_modules/npm/bin/npm-cli.js run dev:h5 --scripts-prepend-node-path=auto

To debug the "dev:h5" script, make sure the $NODE_DEBUG_OPTION string is specified as the first argument for the node command you'd like to debug.
For example:
  "scripts": {
    "start": "node $NODE_DEBUG_OPTION server.js"
  }

> tgd-taro@1.0.0 dev:h5 /Users/libn/dev/IdeaProjects/me/tgd-taro
> npm run build:h5 -- --watch

> tgd-taro@1.0.0 build:h5 /Users/libn/dev/IdeaProjects/me/tgd-taro
> taro build --type h5 "--watch"

👽 Taro v3.0.0-alpha.4

开始编译项目 tgd-taro
创建  发现文件  src/app.config.ts
TypeError: transformer_wx_1.default is not a function
    at Compiler.processOthers (/Users/libn/.nvm/versions/node/v12.14.1/lib/node_modules/@tarojs/cli/dist/h5/index.js:759:43)
    at Compiler.processFiles (/Users/libn/.nvm/versions/node/v12.14.1/lib/node_modules/@tarojs/cli/dist/h5/index.js:1240:39)
    at Walker.<anonymous> (/Users/libn/.nvm/versions/node/v12.14.1/lib/node_modules/@tarojs/cli/dist/h5/index.js:125:30)
    at Walker.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Walker.Readable.push (_stream_readable.js:224:10)
    at /Users/libn/.nvm/versions/node/v12.14.1/lib/node_modules/@tarojs/cli/node_modules/klaw/src/index.js:32:19
    at callback (/Users/libn/.nvm/versions/node/v12.14.1/lib/node_modules/@tarojs/cli/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqCallback.oncomplete (fs.js:159:5)
创建  发现文件  src/app.scss
创建  发现文件  src/app.ts
TypeError: transformer_wx_1.default is not a function
    at Compiler.processEntry (/Users/libn/.nvm/versions/node/v12.14.1/lib/node_modules/@tarojs/cli/dist/h5/index.js:234:43)
    at Compiler.processFiles (/Users/libn/.nvm/versions/node/v12.14.1/lib/node_modules/@tarojs/cli/dist/h5/index.js:1229:41)
    at Walker.<anonymous> (/Users/libn/.nvm/versions/node/v12.14.1/lib/node_modules/@tarojs/cli/dist/h5/index.js:125:30)
    at Walker.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Walker.Readable.push (_stream_readable.js:224:10)
    at /Users/libn/.nvm/versions/node/v12.14.1/lib/node_modules/@tarojs/cli/node_modules/klaw/src/index.js:32:19
    at callback (/Users/libn/.nvm/versions/node/v12.14.1/lib/node_modules/@tarojs/cli/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqCallback.oncomplete (fs.js:159:5)
创建  发现文件  src/index.html
创建  发现文件  src/pages/index/index.config.ts
TypeError: transformer_wx_1.default is not a function
    at Compiler.processOthers (/Users/libn/.nvm/versions/node/v12.14.1/lib/node_modules/@tarojs/cli/dist/h5/index.js:759:43)
    at Compiler.processFiles (/Users/libn/.nvm/versions/node/v12.14.1/lib/node_modules/@tarojs/cli/dist/h5/index.js:1240:39)
    at Walker.<anonymous> (/Users/libn/.nvm/versions/node/v12.14.1/lib/node_modules/@tarojs/cli/dist/h5/index.js:125:30)
    at Walker.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Walker.Readable.push (_stream_readable.js:224:10)
    at /Users/libn/.nvm/versions/node/v12.14.1/lib/node_modules/@tarojs/cli/node_modules/klaw/src/index.js:32:19
    at callback (/Users/libn/.nvm/versions/node/v12.14.1/lib/node_modules/@tarojs/cli/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqCallback.oncomplete (fs.js:159:5)
创建  发现文件  src/pages/index/index.scss
创建  发现文件  src/pages/index/index.vue

ℹ️  Listening at http://0.0.0.0:10086/

监听文件修改中...

multi ./node_modules/webpack-dev-server/client?http://0.0.0.0:10086 ./node_modules/webpack/hot/dev-server.js ./.temp/app.js
Module not found: Can't resolve '/Users/libn/dev/IdeaProjects/me/tgd-taro/.temp/app.js' in '/Users/libn/dev/IdeaProjects/me/tgd-taro'

**Comment by yuche** [comment]
看：https://juejin.im/post/5e4487b3e51d4527214ba6b1

现在 Taro Next 只有小程序端

**Comment by libn-net** [comment]
有计划支持的时间吗？

**Comment by libn-net** [comment]
@yuche

**Comment by yuche** [comment]
> 有计划支持的时间吗？

3 月某个时间会支持 h5
