### ISSUE TITLE
脚手架build路径有问题

### ISSUE THREAD

**Issue by hujingyuki** [NervJS/taro#5535]
# 问题描述

执行npm run build:rn 报错，找不到index.js文件

### 复现步骤

1. npm run build:rn
2. 观察控制台

### 期望行为

成功唤起metro bundle server

### 报错信息
编译  编译完成，花费15323 ms  
```shell
Loading dependency graph...error The resource `.../project/taro-project/rn_temp/rn_temp/index.js` was not found.. Run CLI with --verbose flag for more details.
(node:93495) UnhandledPromiseRejectionWarning: Error: Command failed: node ../node_modules/react-native/local-cli/cli.js bundle --entry-file ./rn_temp/index.js --bundle-output ./bundle/index.bundle --assets-dest ./bundle --dev false
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at Compiler.buildBundle (/usr/local/lib/node_modules/@tarojs/cli/dist/rn.js:220:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/dist/rn.js:361:22)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/@tarojs/cli/dist/rn.js:4:58)
(node:93495) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:93495) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 17.99s.
```

### 系统信息

  Taro CLI 2.0.4 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm

### 补充信息

编译完成后的index.js文件直接位于rn_temp目录中，但报错信息里却指向rn_temp/rn_temp/index.js

**Comment by Pines-Cheng** [comment]
正在 fix

**Comment by Pines-Cheng** [comment]
打离线包 bundle ，直接使用

iOS：

```shell
node ./node_modules/react-native/local-cli/cli.js bundle --entry-file /rn_temp/index.js --bundle-output ./bundle --platform ios --assets-dest ./bundle --dev false
```

Android：

```shell
node ./node_modules/react-native/local-cli/cli.js bundle --entry-file /rn_temp/index.js --bundle-output ./bundle --platform android --assets-dest ./bundle --dev false
```
打出离线包，更快更方便。
