### ISSUE TITLE
请问如何在 StoryBook 里 mount Taro 组件

### ISSUE THREAD

**Issue by Jeff-Tian** [NervJS/taro#5536]
### 问题描述
想使用 Storybook 来管理 Taro 组件，发现会报 
Cannot call a class as a function
这样的错误。

### 复现步骤

1.  比如这份代码，很简单的 Taro 组件：  [https://github.com/Jeff-Tian/uni-user/blob/master/src/containers/taro-container.tsx](https://github.com/Jeff-Tian/uni-user/blob/master/src/containers/taro-container.tsx)   
2.  在Storybook 里 mount:
```
import React, { useState, useEffect } from 'react';
import TaroTest from '../src/containers/taro-container';

export default {
    title: 'Taro 兼容',
    component: TaroTest
};

export const TaroTestStory = () => {
    return <TaroTest />
}

TaroTestStory.story = {
    name: 'Taro 兼容',
};

```
3.  结果如： [https://uni-user-story.pa-ca.me/?path=/story/taro-%E5%85%BC%E5%AE%B9--taro-test-story](https://uni-user-story.pa-ca.me/?path=/story/taro-%E5%85%BC%E5%AE%B9--taro-test-story)    
4. 

```
Cannot call a class as a function
TypeError: Cannot call a class as a function
    at _classCallCheck (https://uni-user-story.pa-ca.me/vendors~main.9609800ff992b0ac62cd.bundle.js:1:143565)
    at Component (https://uni-user-story.pa-ca.me/vendors~main.9609800ff992b0ac62cd.bundle.js:1:148362)
    at TaroTest (https://uni-user-story.pa-ca.me/main.9609800ff992b0ac62cd.bundle.js:1:12948)
    at hg (https://uni-user-story.pa-ca.me/vendors~main.9609800ff992b0ac62cd.bundle.js:1:1304397)
    at Tg (https://uni-user-story.pa-ca.me/vendors~main.9609800ff992b0ac62cd.bundle.js:1:1316570)
    at bi (https://uni-user-story.pa-ca.me/vendors~main.9609800ff992b0ac62cd.bundle.js:1:1341657)
    at ci (https://uni-user-story.pa-ca.me/vendors~main.9609800ff992b0ac62cd.bundle.js:1:1342031)
    at Di (https://uni-user-story.pa-ca.me/vendors~main.9609800ff992b0ac62cd.bundle.js:1:1349010)
    at Yh (https://uni-user-story.pa-ca.me/vendors~main.9609800ff992b0ac62cd.bundle.js:1:1348397)
    at Xh (https://uni-user-story.pa-ca.me/vendors~main.9609800ff992b0ac62cd.bundle.js:1:1347434)
```

### 系统信息
```
taro info
👽 Taro v2.0.0


  Taro CLI 2.0.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.0.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - C:\Users\Jeff\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.6 - C:\Users\Jeff\AppData\Roaming\npm\npm.CMD


```

### 补充信息

感觉 Taro component 和 react component 不太兼容？也试过在 Taro 里 mount 别的 react 组件，也是失败。

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Garfield550** [comment]
Storybook 似乎对每个框架都做了一些定制的编译配置文件 https://github.com/storybookjs/storybook/blob/next/app/react/README.md

**Comment by Jeff-Tian** [comment]
> Storybook 似乎对每个框架都做了一些定制的编译配置文件 https://github.com/storybookjs/storybook/blob/next/app/react/README.md

谢谢，不过并没有 Taro 的编译配置例子，希望 Taro 团队能给一个例子。

**Comment by Garfield550** [comment]
我猜测可能不只是 Taro 给个配置例子那么简单，可能需要 Storybook 主动支持。

**Comment by ZakaryCode** [comment]
[参考文档](https://nervjs.github.io/taro/docs/next/external-libraries#storybook)
