### ISSUE TITLE
Taro next Map组件还是无法使用

### ISSUE THREAD

**Issue by Singloo** [NervJS/taro#5565]
### 问题描述
Taro next alpha 5
mobx ts模板

使用Map组件时出现错误, 组件不显示

### 复现步骤

```js
const coordinate = { lat: 31.2494, lng: 121.397 };
    return (
      <View className={'index'}>
        <Button onClick={this.increment}>+</Button>
        <Button onClick={this.decrement}>-</Button>
        <Button onClick={this.incrementAsync}>Add Async</Button>
        <Text>{count}</Text>
        <Map
          style={{ width: 300, height: 400 }}
          longitude={coordinate!.lng}
          latitude={coordinate!.lat}
         layerStyle={1}
        />
      </View>
    );
```

### 报错信息

```
VM406:1 TypeError: Cannot read property 'layerStyle' of null
    at i._insertIframeMap (:12326/__pageframe__/__dev__/WAWebview.js:2)
    at window.__map_jssdk_init (:12326/__pageframe__/__dev__/WAWebview.js:2)
    at eval (eval at <anonymous> (3gimg.qq.com/lightmap/api_v2/2/4/128/main.js:1), <anonymous>:1:21)
    at 3gimg.qq.com/lightmap/api_v2/2/4/128/main.js:1
```

```
VM406:1 webviewScriptError
Cannot read property 'layerStyle' of null
TypeError: Cannot read property 'layerStyle' of null
    at i._insertIframeMap (http://127.0.0.1:12326/__pageframe__/__dev__/WAWebview.js:2:658997)
    at window.__map_jssdk_init (http://127.0.0.1:12326/__pageframe__/__dev__/WAWebview.js:2:656254)
    at eval (eval at <anonymous> (https://3gimg.qq.com/lightmap/api_v2/2/4/128/main.js:1:61434), <anonymous>:1:21)
    at https://3gimg.qq.com/lightmap/api_v2/2/4/128/main.js:1:61434
```
```

  | console.error | @ | VM406:1
-- | -- | -- | --
  | (anonymous) | @ | VM432:2

```
### 系统信息

```
👽 Taro v3.0.0-alpha.5
  Taro CLI 3.0.0-alpha.5 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.21.1 - ~/.nvm/versions/node/v12.13.1/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
```

**Comment by Singloo** [comment]
@yuche

**Comment by yuche** [comment]
https://developers.weixin.qq.com/miniprogram/dev/component/map.html

给 props setting 按文档设置一个默认值
