### ISSUE TITLE
Taro Next配置DVA运行错误

### ISSUE THREAD

**Issue by TtTRz** [NervJS/taro#5595]
### 问题描述
TaroNext中使用DVA时，小程序会报 defualt.createContext is not a function

### 复现步骤
`app.ts`
```
import React, { Component } from 'react'

import { Provider} from "@tarojs/redux";
import dva from './utils/dva';

import models from './models';

import './app.scss'

const dvaApp = dva.createApp({
  initialState: {},
  models: models,
});

const store = dvaApp.getStore();
class App extends Component {

  componentDidMount () {}

  componentDidShow () {}

  componentDidHide () {}

  componentDidCatchError () {}

  // 在Taro Next中 config改为外部文件配置 在.config.ts

  // this.props.children 是将要会渲染的页面
  render () {
    console.log(store);
    return (
      <Provider store={store}>
        {this.props.children}
      </Provider>
    )
  }
}

export default App

```
`dva.ts`
```
import { create } from "dva-core";
// import { createLogger } from "redux-logger";
import  createLoading  from "dva-loading";



let app;
let store;
let dispatch;
let registered;

function createApp(opt) {
  // redux 的日志
  // opt.onAction = [createLogger()];
  app = create(opt);
  app.use(createLoading({}));

  if (!registered) {
    opt.models.forEach(model => app.model(model));
  }
  registered = true;
  app.start();

  store = app._store;
  app.getStore = () => store;
  app.use({
    onError(err){
      console.log(err);
    }
  });

  dispatch = store.dispatch;
  app.dispatch = dispatch;
  return app;
}

export default{
  createApp,
  getDispatch(){
    return app.dispatch
  }
}

```

### 报错信息
```
Taro__default.createContext is not a function
TypeError: Taro__default.createContext is not a function
    at Object.<anonymous> (http://127.0.0.1:28372/appservice/vendors.js:1144:34)
    at Object../node_modules/@tarojs/redux/dist/index.js (http://127.0.0.1:28372/appservice/vendors.js:1490:30)
    at __webpack_require__ (http://127.0.0.1:28372/appservice/runtime.js:80:30)
    at Object../node_modules/@tarojs/redux/index.js (http://127.0.0.1:28372/appservice/vendors.js:1502:18)
    at __webpack_require__ (http://127.0.0.1:28372/appservice/runtime.js:80:30)
    at Object../node_modules/babel-loader/lib/index.js!./src/app.tsx (http://127.0.0.1:28372/appservice/app.js:22:71)
    at __webpack_require__ (http://127.0.0.1:28372/appservice/runtime.js:80:30)
    at Module../src/app.tsx (http://127.0.0.1:28372/appservice/app.js:106:195)
    at __webpack_require__ (http://127.0.0.1:28372/appservice/runtime.js:80:30)
    at checkDeferredModules (http://127.0.0.1:28372/appservice/runtime.js:46:23)
``` 
### 系统信息

```
 Taro v3.0.0-alpha.5


  Taro CLI 3.0.0-alpha.5 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.6.0 - ~/.nvm/versions/node/v11.6.0/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v11.6.0/bin/yarn
      npm: 6.14.1 - ~/.nvm/versions/node/v11.6.0/bin/npm
    npmPackages:
      @tarojs/components: ^3.0.0-alpha.5 => 3.0.0-alpha.5 
      @tarojs/redux: 2.0.5 => 2.0.5 
      @tarojs/redux-h5: 2.0.5 => 2.0.5 
      @tarojs/taro: ^3.0.0-alpha.5 => 3.0.0-alpha.5 
      @tarojs/taro-weapp: 2.0.5 => 2.0.5 
      eslint-config-taro: 2.0.5 => 2.0.5 
      react: ^16.13.0 => 16.13.0 

```

**Comment by yuche** [comment]
把迁移文档好好看一看：https://taro-docs.jd.com/taro/next/docs/migration.html

@tarojs/redux 已经没有了，直接用 react-redux

**Comment by Tammy-zting** [comment]
如何解决？？
