### ISSUE TITLE
PickerViewColumn 使用提示路径错误

### ISSUE THREAD

**Issue by lizhoukai** [NervJS/taro#562]
**问题描述**
引入PickerView，PickerViewColumn同时使用会出现这个问题
copy 官网示例代码也出现这个问题~

**复现步骤**
具体看taro 示例代码

**期望行为**

**报错信息**
```
错误  组件错误  组件PickerViewColumn路径错误，请检查！（可能原因是导出的组件名不正确）
错误  页面编译  页面/Users/leon/Desktop/weapp2/src/pages/index/index编译失败！
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.relative (path.js:1173:5)
    at pageDepComponents.forEach.depComponent (/Users/leon/Desktop/weapp2/node_modules/_@tarojs_cli@1.0.0-beta.22@@tarojs/cli/src/weapp.js:1197:64)
    at Array.forEach (<anonymous>)
    at componentMap.forEach.component (/Users/leon/Desktop/weapp2/node_modules/_@tarojs_cli@1.0.0-beta.22@@tarojs/cli/src/weapp.js:1191:31)
    at Array.forEach (<anonymous>)
    at realComponentsPathList.forEach.component (/Users/leon/Desktop/weapp2/node_modules/_@tarojs_cli@1.0.0-beta.22@@tarojs/cli/src/weapp.js:1190:24)
    at Array.forEach (<anonymous>)
    at buildSinglePage (/Users/leon/Desktop/weapp2/node_modules/_@tarojs_cli@1.0.0-beta.22@@tarojs/cli/src/weapp.js:1187:30)
    at process._tickCallback (internal/process/next_tick.js:178:7)
```

**系统信息**

 - 操作系统: [macos]
 - Taro 版本 [1.0.0-beta.22]
 - Node.js 版本 [10]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
贴一下文件的代码

**Comment by lizhoukai** [comment]
@luckyadam 
```js
import Taro, { Component } from '@tarojs/taro'
import { View, PickerView, PickerViewColumn } from '@tarojs/components'

export default class Picks extends Component {

  constructor() {
    super(...arguments)
    const date = new Date()
    const years = []
    const months = []
    const days = []
    for (let i = 1990; i <= date.getFullYear(); i++) {
      years.push(i)
    }
    for (let i = 1; i <= 12; i++) {
      months.push(i)
    }
    for (let i = 1; i <= 31; i++) {
      days.push(i)
    }
    this.state = {
      years: years,
      year: date.getFullYear(),
      months: months,
      month: 2,
      days: days,
      day: 2,
      value: [9999, 1, 1],
    }
  }

  onChange = e => {
    const val = e.detail.value
    this.setState({
      year: this.state.years[val[0]],
      month: this.state.months[val[1]],
      day: this.state.days[val[2]],
      value: val
    })
  }

  render() {
    return (
      <View>
        <View>{this.state.year}年{this.state.month}月{this.state.day}日</View>
        <PickerView indicatorStyle="height: 50px;" style="width: 100%; height: 300px;" value={this.state.value} onChange={this.onChange}>
          <PickerViewColumn>
            {this.state.years.map(item => {
              return (
                <View>{item}年</View>
              );
            })}
          </PickerViewColumn>
          <PickerViewColumn>
            {this.state.months.map(item => {
              return (
                <View>{item}月</View>
              );
            })}
          </PickerViewColumn>
          <PickerViewColumn>
            {this.state.days.map(item => {
              return (
                <View>{item}日</View>
              );
            })}
          </PickerViewColumn>
        </PickerView>
      </View>
    )
  }
}
```

**Comment by luckyadam** [comment]
已修复，下个版本发布~
