### ISSUE TITLE
快应用容器版本获取失败！

### ISSUE THREAD

**Issue by yuyongyu08** [NervJS/taro#5624]
### 问题描述
构建快应用时总是报“快应用容器版本获取失败！”

### 复现步骤
taro build --type quickapp

<img width="985" alt="WeChat65c7f8739adce5c83f5e943a51fac77e" src="https://user-images.githubusercontent.com/9265231/75997354-2fa05500-5f3a-11ea-9ed4-f2970683933c.png">

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为
取消快应用容器版本的实时校验

### 报错信息
Error: 快应用容器版本请求失败，请重试！

### 系统信息
taro版本: 1.3.29
mac: 10.15.3

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
删掉 dist 重试即可

**Comment by yuyongyu08** [comment]
试了，不可用。
```
⠸ 开始下载快应用运行容器...undefined:6
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 5
    at JSON.parse (<anonymous>)
```

**Comment by yuyongyu08** [comment]
试了，不可用。
```
⠸ 开始下载快应用运行容器...undefined:6
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 5
    at JSON.parse (<anonymous>)
    at Request.request [as _callback] (/Users/yuyongyu/Documents/58/mini-program/mp-fang-ultimate/node_modules/@tarojs/cli/dist/util/dowload.js:28:30)
    at Request.self.callback (/Users/yuyongyu/Documents/58/mini-program/mp-fang-ultimate/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/Users/yuyongyu/Documents/58/mini-program/mp-fang-ultimate/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/Users/yuyongyu/Documents/58/mini-program/mp-fang-ultimate/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by yuyongyu08** [comment]
应该是在校验容器时获取版本号的请求失败:https://api.github.com/repos/NervJS/quickapp-container/releases/latest。此接口返回404.

**Comment by yuyongyu08** [comment]
> 应该是在校验容器时获取版本号的请求失败:[https://api.github.com/repos/NervJS/quickapp-container/releases/latest。此接口返回404](https://api.github.com/repos/NervJS/quickapp-container/releases/latest%E3%80%82%E6%AD%A4%E6%8E%A5%E5%8F%A3%E8%BF%94%E5%9B%9E404).

可能和公司网络有关，换成手机4G就行了。

**Comment by cyh-93** [comment]
有代理 github 的，关掉代理重试即可
