### ISSUE TITLE
按照demo 配置 webpack 插件报错

### ISSUE THREAD

**Issue by PlutoCA** [NervJS/taro#5650]
### 问题描述
按照demo 配置 webpack 插件报错

### 复现步骤
直接新建项目配置
配置插件后台 dev:weapp

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */
const config = {
  projectName: 'demo-css',
  date: '2020-3-9',
  designWidth: 750,
  deviceRatio: {
    '640': 2.34 / 2,
    '750': 1,
    '828': 1.81 / 2
  },
  sourceRoot: 'src',
  outputRoot: 'dist',
  babel: {
    sourceMap: true,
    presets: [
      ['env', {
        modules: false
      }]
    ],
    plugins: [
      'transform-decorators-legacy',
      'transform-class-properties',
      'transform-object-rest-spread'
    ]
  },
  plugins: [],
  defineConstants: {
  },
  mini: {
    webpackChain (chain, webpack) { // 直接复制文档示例https://taro-docs.jd.com/taro/docs/next/config-detail.html#miniwebpackchain
      chain.merge({
        plugin: {
          install: {
            plugin: require('npm-install-webpack-plugin'),
            args: [{
              // Use --save or --save-dev
              dev: false,
              // Install missing peerDependencies
              peerDependencies: true,
              // Reduce amount of console logging
              quiet: false,
              // npm command used inside company, yarn is not supported yet
              npm: 'cnpm'
            }]
          }
        }
      })
    },
    postcss: {
      pxtransform: {
        enable: true,
        config: {}
      },
      url: {
        enable: true,
        config: {
          limit: 10240 // 设定转换尺寸上限
        }
      },
      cssModules: {
        enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
        config: {
          namingPattern: 'module', // 转换模式，取值为 global/module
          generateScopedName: '[name]__[local]___[hash:base64:5]'
        }
      }
    },
  },
  h5: {
    publicPath: '/',
    staticDirectory: 'static',
    postcss: {
      autoprefixer: {
        enable: true,
        config: {
          browsers: [
            'last 3 versions',
            'Android >= 4.1',
            'ios >= 8'
          ]
        }
      },
      cssModules: {
        enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
        config: {
          namingPattern: 'module', // 转换模式，取值为 global/module
          generateScopedName: '[name]__[local]___[hash:base64:5]'
        }
      }
    }
  }
}

module.exports = function (merge) {
  if (process.env.NODE_ENV === 'development') {
    return merge({}, config, require('./dev'))
  }
  return merge({}, config, require('./prod'))
}


```

### 期望行为

正常运行

### 报错信息
```
生成  工具配置  dist/project.config.json
(node:18964) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:18964) UnhandledPromiseRejectionWarning: TypeError: compiler.resolvers.loader.plugin is not a function
    at NpmInstallPlugin.<anonymous> (F:\work\demo-css\node_modules\_npm-install-webpack-plugin@4.0.5@npm-install-webpack-plugin\src\plugin.js:51:31)
    at SyncHook.eval [as call] (eval at create (F:\work\demo-css\node_modules\_tapable@1.1.3@tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (F:\work\demo-css\node_modules\_tapable@1.1.3@tapable\lib\Hook.js:154:20)
    at WebpackOptionsApply.process (F:\work\demo-css\node_modules\_webpack@4.41.6@webpack\lib\WebpackOptionsApply.js:541:33)
    at webpack (F:\work\demo-css\node_modules\_webpack@4.41.6@webpack\lib\webpack.js:57:48)
    at makeConfig.then.config (F:\work\demo-css\node_modules\_@tarojs_mini-runner@2.0.6@@tarojs\mini-runner\dist\index.js:39:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
(node:18964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### 系统信息

� Taro v2.0.6

  Taro CLI 2.0.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
这个插件不适用于 webpack4 ，请按需配置你需要的插件
