### ISSUE TITLE
taro v2.0.6转换已有有小程序时报错

### ISSUE THREAD

**Issue by rockcitystore** [NervJS/taro#5654]
### 问题描述

taro转换小程序自定义组件时获取的路径不对，例如转换自定义组件item-list，但在转换原生组件时没问题。经过debug 发现taro读取的是`/Users/bar/code/weapp-taro/component/item-list.js`
而实际文件位置是`/Users/bar/code/weapp-taro/component/item-list/index.js`
进一步发现以下路径都不对
```
 const componentJSPath = component + this.fileTypes.SCRIPT;
 const componentDistJSPath = this.getDistFilePath(componentJSPath);
 const componentConfigPath = component + this.fileTypes.CONFIG;
 const componentStylePath = component + this.fileTypes.STYLE;
 const componentTemplPath = component + this.fileTypes.TEMPL;
```

### 报错信息
```js

错误  组件转换  component/item-list.js
Error: 组件 /Users/bar/code/weapp-taro/component/item-list 没有 JS 文件！
    at components.forEach.componentObj (/Users/bar/.nvm/versions/node/v8.9.1/lib/node_modules/@tarojs/cli/dist/convertor/index.js:521:27)
    at Set.forEach (<anonymous>)
    at Convertor.traverseComponents (/Users/bar/.nvm/versions/node/v8.9.1/lib/node_modules/@tarojs/cli/dist/convertor/index.js:506:20)
    at pages.forEach.page (/Users/bar/.nvm/versions/node/v8.9.1/lib/node_modules/@tarojs/cli/dist/convertor/index.js:494:22)
    at Set.forEach (<anonymous>)
    at Convertor.traversePages (/Users/bar/.nvm/versions/node/v8.9.1/lib/node_modules/@tarojs/cli/dist/convertor/index.js:419:20)
    at Convertor.run (/Users/bar/.nvm/versions/node/v8.9.1/lib/node_modules/@tarojs/cli/dist/convertor/index.js:677:14)
    at Object.<anonymous> (/Users/bar/.nvm/versions/node/v8.9.1/lib/node_modules/@tarojs/cli/bin/taro-convert:12:11)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)

```

### 期望行为

建议增加对自定义组件判断逻辑

### 系统信息

Taro v2.0.6

  Taro CLI 2.0.6 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.1 - ~/.nvm/versions/node/v8.9.1/bin/node
      Yarn: 1.7.0 - ~/.nvm/versions/node/v8.9.1/bin/yarn
      npm: 5.5.1 - ~/.nvm/versions/node/v8.9.1/bin/npm
### 补充信息

![taro-issue1](https://user-images.githubusercontent.com/11556355/76630127-70bbe900-657a-11ea-84f2-6d81643a7e8e.png)

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
有没有一个示例的例子

**Comment by rockcitystore** [comment]
你好 更新了一张图片说明

**Comment by Chen-jj** [comment]
最新版本应该已经修复了
