### ISSUE TITLE
[Taro v3.0.0-alpha.6] 编译出现错误 Module not found: Can't resolve './app.jsx"'

### ISSUE THREAD

**Issue by Psli** [NervJS/taro#5675]
### 问题描述
```
taro init test

taro build --type weapp --watch

👽Taro v3.0.0-alpha.6

开始编译项目 test
生成  工具配置  dist/project.config.json

编译  发现入口  src/app.jsx
编译  发现页面  src/pages/index/index.jsx
⠧ 正在编译...[BABEL] Note: The code generator has deoptimised the styling of /prjs/test/node_modules/react-reconciler/cjs/react-reconciler.development.js as it exceeds the max of 500KB.
🙅  编译失败.

./src/app.jsx
Module not found: Can't resolve './app.jsx"' in '/prjs/test/src'


监听文件修改中...
```

### 出错信息
```
Cannot find module '"../node_modules/@tarojs/mini-runner/node_modules/babel-loader/lib/index.js!./app.jsx"'
Error: Cannot find module '"../node_modules/@tarojs/mini-runner/node_modules/babel-loader/lib/index.js!./app.jsx"'
    at webpackMissingModule (http://127.0.0.1:17172/appservice/app.js:18:45)
    at Module../src/app.jsx (http://127.0.0.1:17172/appservice/app.js:18:208)
    at __webpack_require__ (http://127.0.0.1:17172/appservice/runtime.js:80:30)
    at checkDeferredModules (http://127.0.0.1:17172/appservice/runtime.js:46:23)
    at Array.webpackJsonpCallback [as push] (http://127.0.0.1:17172/appservice/runtime.js:33:19)
    at http://127.0.0.1:17172/appservice/app.js:5:49
    at require (http://127.0.0.1:17172/appservice/__dev__/WAService.js:2:1680701)
    at <anonymous>:1:1
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:17172/appservice/appservice?t=1583936178302:36731:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:17172/appservice/appservice?t=1583936178302:36743:20)
```
### 系统信息
```
👽 Taro v3.0.0-alpha.6


  Taro CLI 3.0.0-alpha.6 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.19.0 - /usr/local/opt/node@10/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/opt/node@10/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-alpha.6 => 3.0.0-alpha.6
      @tarojs/taro: 3.0.0-alpha.6 => 3.0.0-alpha.6
      eslint-config-taro: 3.0.0-alpha.6 => 3.0.0-alpha.6
      react: ^16.10.0 => 16.13.0
```

**Comment by yuche** [comment]
你在 alpha.5 没有遇到这个问题吗

**Comment by Psli** [comment]
> 你在 alpha.5 没有遇到这个问题吗

没有遇到这情况

**Comment by Psli** [comment]
@yuche 
出错信息如下
```
Cannot find module '"../node_modules/@tarojs/mini-runner/node_modules/babel-loader/lib/index.js!./app.jsx"'
Error: Cannot find module '"../node_modules/@tarojs/mini-runner/node_modules/babel-loader/lib/index.js!./app.jsx"'
    at webpackMissingModule (http://127.0.0.1:17172/appservice/app.js:18:45)
    at Module../src/app.jsx (http://127.0.0.1:17172/appservice/app.js:18:208)
    at __webpack_require__ (http://127.0.0.1:17172/appservice/runtime.js:80:30)
    at checkDeferredModules (http://127.0.0.1:17172/appservice/runtime.js:46:23)
    at Array.webpackJsonpCallback [as push] (http://127.0.0.1:17172/appservice/runtime.js:33:19)
    at http://127.0.0.1:17172/appservice/app.js:5:49
    at require (http://127.0.0.1:17172/appservice/__dev__/WAService.js:2:1680701)
    at <anonymous>:1:1
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:17172/appservice/appservice?t=1583936178302:36731:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:17172/appservice/appservice?t=1583936178302:36743:20)
```

**Comment by JaxXu** [comment]
Vue 模板同遇到这种问题 @yuche 

```bash

👽 Taro v3.0.0-alpha.6

开始编译项目 next
生成  工具配置  dist/project.config.json

编译  发现入口  src/app.js
编译  发现页面  src/pages/index/index.vue
🙅   编译失败.

./src/app.js
Module not found: Can't resolve './app.js"' in '/XXXXXX/src'
```

**Comment by yuche** [comment]
不好意思 loader 多写了一个双引号，try alpha.7
