### ISSUE TITLE
Taro v2.0.5 下各端build报错   dev正常

### ISSUE THREAD

**Issue by ywanhzy** [NervJS/taro#5685]
### 问题描述
从1.3版本升级到2.0.5  build到微信小程序 支付宝小程序 h5报错，dev正常

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 报错信息
/ 正在编译...SyntaxError: Unexpected token (1:1)
    at Parser.pp$4.raise (D:\taro_project\TaroMeishiliu\node_modules\_acorn@6.4.1@acorn\dist\acorn.js:2825:15)
    at Parser.pp.unexpected (D:\taro_project\TaroMeishiliu\node_modules\_acorn@6.4.1@acorn\dist\acorn.js:689:10)
    at Parser.pp$3.parseParenAndDistinguishExpression (D:\taro_project\TaroMeishiliu\node_modules\_acorn@6.4.1@acorn\dist\acorn.js:2335:51)
    at Parser.pp$3.parseExprAtom (D:\taro_project\TaroMeishiliu\node_modules\_acorn@6.4.1@acorn\dist\acorn.js:2230:43)
    at Parser.pp$3.parseExprSubscripts (D:\taro_project\TaroMeishiliu\node_modules\_acorn@6.4.1@acorn\dist\acorn.js:2089:21)
    at Parser.pp$3.parseMaybeUnary (D:\taro_project\TaroMeishiliu\node_modules\_acorn@6.4.1@acorn\dist\acorn.js:2066:19)
    at Parser.pp$3.parseExprOps (D:\taro_project\TaroMeishiliu\node_modules\_acorn@6.4.1@acorn\dist\acorn.js:2010:21)
    at Parser.pp$3.parseMaybeConditional (D:\taro_project\TaroMeishiliu\node_modules\_acorn@6.4.1@acorn\dist\acorn.js:1993:21)
    at Parser.pp$3.parseMaybeAssign (D:\taro_project\TaroMeishiliu\node_modules\_acorn@6.4.1@acorn\dist\acorn.js:1968:21)
    at Parser.pp$3.parseExpression (D:\taro_project\TaroMeishiliu\node_modules\_acorn@6.4.1@acorn\dist\acorn.js:1933:21)
    at Parser.pp$1.parseStatement (D:\taro_project\TaroMeishiliu\node_modules\_acorn@6.4.1@acorn\dist\acorn.js:877:47)
    at Parser.pp$1.parseTopLevel (D:\taro_project\TaroMeishiliu\node_modules\_acorn@6.4.1@acorn\dist\acorn.js:746:23)
    at Parser.parse (D:\taro_project\TaroMeishiliu\node_modules\_acorn@6.4.1@acorn\dist\acorn.js:553:17)
    at Function.parse (D:\taro_project\TaroMeishiliu\node_modules\_acorn@6.4.1@acorn\dist\acorn.js:576:37)
    at Function.parse (D:\taro_project\TaroMeishiliu\node_modules\_webpack@4.41.6@webpack\lib\Parser.js:2396:22)
    at Parser.evaluate (D:\taro_project\TaroMeishiliu\node_modules\_webpack@4.41.6@webpack\lib\Parser.js:2293:22) {
  pos: 1,
  loc: Position { line: 1, column: 1 },
  raisedAt: 2
}
�   编译失败.

common.js from UglifyJs
Unexpected token: punc «;» [common.js:501,32]

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meishiliu@3.1.1 build:alipay: `taro build --type alipay`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meishiliu@3.1.1 build:alipay script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### 系统信息
PS D:\taro_project\TaroMeishiliu> taro info
� Taro v2.0.5

  Taro CLI 2.0.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\liumu\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/76595183-008b7400-6536-11ea-9319-b0a186d8cfbe.png)
看起来是代码里的某种错误导致了压缩失败

**Comment by ywanhzy** [comment]
dev 运行微信小程序不报错 能正常访问 ，h5运行不报错 打开是空白页面。找不到是什么原因引起的？   
在1.3.37版本支付宝、微信、h5编译都是正常的

**Comment by luckyadam** [comment]
目前信息太少，能不能先确定一下报错的页面，或者弄一个最小复现的 demo 看看

**Comment by ywanhzy** [comment]
/ 正在编译...SyntaxError: Unexpected token (1:1)
    at Parser.pp$4.raise (D:\taro_project\TaroMeishiliu\node_modules\webpack\node_modules\acorn\dist\acorn.js:2825:15)
    at Parser.pp.unexpected (D:\taro_project\TaroMeishiliu\node_modules\webpack\node_modules\acorn\dist\acorn.js:689:10)
    at Parser.pp$3.parseParenAndDistinguishExpression (D:\taro_project\TaroMeishiliu\node_modules\webpack\node_modules\acorn\dist\acorn.js:2335:51)
    at Parser.pp$3.parseExprAtom (D:\taro_project\TaroMeishiliu\node_modules\webpack\node_modules\acorn\dist\acorn.js:2230:43)
    at Parser.pp$3.parseExprSubscripts (D:\taro_project\TaroMeishiliu\node_modules\webpack\node_modules\acorn\dist\acorn.js:2089:21)
    at Parser.pp$3.parseMaybeUnary (D:\taro_project\TaroMeishiliu\node_modules\webpack\node_modules\acorn\dist\acorn.js:2066:19)
    at Parser.pp$3.parseExprOps (D:\taro_project\TaroMeishiliu\node_modules\webpack\node_modules\acorn\dist\acorn.js:2010:21)
    at Parser.pp$3.parseMaybeConditional (D:\taro_project\TaroMeishiliu\node_modules\webpack\node_modules\acorn\dist\acorn.js:1993:21)
    at Parser.pp$3.parseMaybeAssign (D:\taro_project\TaroMeishiliu\node_modules\webpack\node_modules\acorn\dist\acorn.js:1968:21)
    at Parser.pp$3.parseExpression (D:\taro_project\TaroMeishiliu\node_modules\webpack\node_modules\acorn\dist\acorn.js:1933:21)
    at Parser.pp$1.parseStatement (D:\taro_project\TaroMeishiliu\node_modules\webpack\node_modules\acorn\dist\acorn.js:877:47)
    at Parser.pp$1.parseTopLevel (D:\taro_project\TaroMeishiliu\node_modules\webpack\node_modules\acorn\dist\acorn.js:746:23)
    at Parser.parse (D:\taro_project\TaroMeishiliu\node_modules\webpack\node_modules\acorn\dist\acorn.js:553:17)
    at Function.parse (D:\taro_project\TaroMeishiliu\node_modules\webpack\node_modules\acorn\dist\acorn.js:576:37)
    at Function.parse (D:\taro_project\TaroMeishiliu\node_modules\webpack\lib\Parser.js:2396:22)
    at Parser.evaluate (D:\taro_project\TaroMeishiliu\node_modules\webpack\lib\Parser.js:2293:22)
    at D:\taro_project\TaroMeishiliu\node_modules\webpack\lib\DefinePlugin.js:180:29
    at SyncBailHook.eval (eval at create (D:\taro_project\TaroMeishiliu\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:16)
    at SyncBailHook.lazyCompileHook (D:\taro_project\TaroMeishiliu\node_modules\tapable\lib\Hook.js:154:20)
    at D:\taro_project\TaroMeishiliu\node_modules\webpack\lib\Parser.js:544:26
    at SyncBailHook.eval (eval at create (D:\taro_project\TaroMeishiliu\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:16)
    at Parser.evaluateExpression (D:\taro_project\TaroMeishiliu\node_modules\webpack\lib\Parser.js:2144:25) {
  pos: 1,
  loc: Position { line: 1, column: 1 },
  raisedAt: 2
}

**Comment by luckyadam** [comment]
麻烦给个 demo 看看吧

**Comment by ywanhzy** [comment]
问题解决了 ，没有认真看文档   prod.js里  配置 defineConstants  全局常量的时候 没有JSON.stringify 就会报这个错误  dev和1.3版本里是没有这个问题的

**Comment by frankgo81** [comment]
yes, please read here. https://nervjs.github.io/taro/docs/config-detail#defineconstants
