### ISSUE TITLE
h5 build failed (Error: spawn taro ENOENT)

### ISSUE THREAD

**Issue by xgqfrms** [NervJS/taro#5767]
### 问题描述

>  Error: spawn taro ENOENT

![image](https://user-images.githubusercontent.com/7291672/77283773-21a74e00-6d08-11ea-96d0-b693174f6315.png)

```sh
➜  mini-program-all git:(feature/travel-have-fun) ✗ yarn run dev:h5
yarn run v1.21.1
$ cross-env PROJECT=h5 taro build --type h5 --watch
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn taro ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  mini-program-all git:(feature/travel-have-fun) ✗ 

```

### 复现步骤

无

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

build success

### 报错信息

同上

### 系统信息

```sh
$ taro info

```

![image](https://user-images.githubusercontent.com/7291672/77286973-7ac6b000-6d0f-11ea-96af-5eec8b3012d1.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by xgqfrms** [comment]
https://taro-club.jd.com/search?term=Error%3A%20spawn%20&in=titlesposts&matchWords=all&sortBy=relevance&sortDirection=desc&showAs=posts

**Comment by Littly** [comment]
检查项目依赖有没有安装好

**Comment by xgqfrms** [comment]
# I'm sorry for that

> just missing install `@taro/cli`

## taro cli

```sh
# install latest version
$ yarn global add @tarojs/cli

# install specific version

# $ yarn add package-name@x.x.x
$ yarn global add @tarojs/cli@1.3.34

$ yarn global remove @tarojs/cli

$ sudo npm i -g @tarojs/cli@1.3.34

```
