### ISSUE TITLE
taro代码报错

### ISSUE THREAD

**Issue by yanping-jessie** [NervJS/taro#59]
用npm install -g @tarojs/cli安装，然后安装成功之后运行任何命令都报错
exports.replaceAsync = async function (str, regex, asyncFn) {
                             ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\nodejs\node\node_modules\npm\node_modules\@tarojs\
cli\bin\taro:7:5)

**Comment by cllgeek** [comment]
这是node版本问题吧，把你的node版本升级到7以上

**Comment by phobal** [comment]
需要升级到 7.6 以上，async 、 await 需要 7.6 才支持
