### ISSUE TITLE
第一步都没顺利跑起来taro init taro01

### ISSUE THREAD

**Issue by topsoft-support** [NervJS/taro#5972]
### 问题描述
使用`npx @tarojs/cli init taro01`或则`taro init taro01`都是一样初始化成功后，使用`dev:h5`packages里面的脚本报错:
```
PS D:\dev\workspace\test\taro\taro01> yarn dev:h5
yarn run v1.22.0
$ npm run build:h5 -- --watch

> taro01@1.0.0 build:h5 D:\dev\workspace\test\taro\taro01
> taro build --type h5 "--watch"

文件名、目录名或卷标语法不正确。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taro01@1.0.0 build:h5: `taro build --type h5 "--watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the taro01@1.0.0 build:h5 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\dev\node12\cache\_logs\2020-04-13T17_18_18_064Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### 复现步骤

1. `taro init taro01`
2. `yarn dev:h5`
3.
 ```
PS D:\dev\workspace\test\taro\taro01> yarn dev:h5
yarn run v1.22.0
$ npm run build:h5 -- --watch

> taro01@1.0.0 build:h5 D:\dev\workspace\test\taro\taro01
> taro build --type h5 "--watch"

文件名、目录名或卷标语法不正确。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taro01@1.0.0 build:h5: `taro build --type h5 "--watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the taro01@1.0.0 build:h5 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\dev\node12\cache\_logs\2020-04-13T17_18_18_064Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
4. 使用`taro build --type h5 "--watch"`或者`taro build --type h5 --watch`正常启动

附上`debug.log`

> 2020-04-13T17_18_18_064Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\dev\\node12\\nodejs\\node.exe',
1 verbose cli   'D:\\dev\\node12\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:h5',
1 verbose cli   '--',
1 verbose cli   '--watch'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'prebuild:h5', 'build:h5', 'postbuild:h5' ]
5 info lifecycle taro01@1.0.0~prebuild:h5: taro01@1.0.0
6 info lifecycle taro01@1.0.0~build:h5: taro01@1.0.0
7 verbose lifecycle taro01@1.0.0~build:h5: unsafe-perm in lifecycle true
8 verbose lifecycle taro01@1.0.0~build:h5: PATH: 
.....
9 verbose lifecycle taro01@1.0.0~build:h5: CWD: D:\dev\workspace\test\taro\taro01
10 silly lifecycle taro01@1.0.0~build:h5: Args: [ '/d /s /c', 'taro build --type h5 "--watch"' ]
11 silly lifecycle taro01@1.0.0~build:h5: Returned: code: 1  signal: null
12 info lifecycle taro01@1.0.0~build:h5: Failed to exec build:h5 script
13 verbose stack Error: taro01@1.0.0 build:h5: `taro build --type h5 "--watch"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\dev\node12\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (D:\dev\node12\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid taro01@1.0.0
15 verbose cwd D:\dev\workspace\test\taro\taro01
16 verbose Windows_NT 10.0.18363
17 verbose argv "D:\\dev\\node12\\nodejs\\node.exe" "D:\\dev\\node12\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:h5" "--" "--watch"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error taro01@1.0.0 build:h5: `taro build --type h5 "--watch"`
22 error Exit status 1
23 error Failed at the taro01@1.0.0 build:h5 script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
https://www.google.com/search?sxsrf=ALeKk00dlX990MOyacfx27IkSiii-ey21w%3A1586831482260&ei=eiCVXsy-D4-1mAWFjqG4DA&q=%E6%96%87%E4%BB%B6%E5%90%8D%E3%80%81%E7%9B%AE%E5%BD%95%E5%90%8D%E6%88%96%E5%8D%B7%E6%A0%87%E8%AF%AD%E6%B3%95%E4%B8%8D%E6%AD%A3%E7%A1%AE%E3%80%82+yarn&oq=%E6%96%87%E4%BB%B6%E5%90%8D%E3%80%81%E7%9B%AE%E5%BD%95%E5%90%8D%E6%88%96%E5%8D%B7%E6%A0%87%E8%AF%AD%E6%B3%95%E4%B8%8D%E6%AD%A3%E7%A1%AE%E3%80%82+yarn&gs_lcp=CgZwc3ktYWIQAzoECCMQJzoGCAAQBxAeOgIIADoECAAQHjoFCAAQzQI6BggAEAUQHjoFCCEQoAFKDggXEgoxMS0xNzBnMTcwSgoIGBIGMTEtNmczUI5GWLJcYI1haAJwAHgAgAHCAYgB2QuSAQMwLjmYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwjM48X27-boAhWPGqYKHQVHCMcQ4dUDCAw&uact=5
