### ISSUE TITLE
Taro初始化后的云开发模板在微信开发者工具中预览提示无法找到组件

### ISSUE THREAD

**Issue by hejinguo** [NervJS/taro#6008]
### 问题描述
Taro初始化后的云开发模板在微信开发者工具中预览提示无法找到组件

### 复现步骤

1. 初始化云开发模板
2. 在微信开发者工具中预览
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 报错信息
![image](https://user-images.githubusercontent.com/19966301/79403786-6d28e100-7fc2-11ea-9f35-0c6c3c8324e3.png)
VM256:1 jsEnginScriptError
Component is not found in path "components/login/index.weapp" (using by "pages/index/index");onAppRoute
Error: Component is not found in path "components/login/index.weapp" (using by "pages/index/index")
    at q (http://127.0.0.1:15296/appservice/__dev__/WAService.js:2:1564920)
    at q (http://127.0.0.1:15296/appservice/__dev__/WAService.js:2:1565124)
    at http://127.0.0.1:15296/appservice/__dev__/WAService.js:2:1586994
    at Module.He (http://127.0.0.1:15296/appservice/__dev__/WAService.js:2:1587573)
    at Function.value (http://127.0.0.1:15296/appservice/__dev__/WAService.js:2:1677988)
    at At (http://127.0.0.1:15296/appservice/__dev__/WAService.js:2:1694140)
    at http://127.0.0.1:15296/appservice/__dev__/WAService.js:2:1698402
    at Dt (http://127.0.0.1:15296/appservice/__dev__/WAService.js:2:1698895)
    at Function.<anonymous> (http://127.0.0.1:15296/appservice/__dev__/WAService.js:2:1702482)
    at i.<anonymous> (http://127.0.0.1:15296/appservice/__dev__/WAService.js:2:1670825)

### 系统信息
![image](https://user-images.githubusercontent.com/19966301/79403922-d4469580-7fc2-11ea-9d27-128f0cda9e2a.png)

👽 Taro v2.1.0

  Taro CLI 2.1.0 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.1.0 => 2.1.0 
      @tarojs/components-qa: 2.1.0 => 2.1.0 
      @tarojs/mini-runner: 2.1.0 => 2.1.0 
      @tarojs/router: 2.1.0 => 2.1.0 
      @tarojs/taro: 2.1.0 => 2.1.0 
      @tarojs/taro-alipay: 2.1.0 => 2.1.0 
      @tarojs/taro-h5: 2.1.0 => 2.1.0 
      @tarojs/taro-qq: 2.1.0 => 2.1.0 
      @tarojs/taro-quickapp: 2.1.0 => 2.1.0 
      @tarojs/taro-swan: 2.1.0 => 2.1.0 
      @tarojs/taro-tt: 2.1.0 => 2.1.0 
      @tarojs/taro-weapp: 2.1.0 => 2.1.0 
      @tarojs/webpack-runner: 2.1.0 => 2.1.0 
      eslint-config-taro: 2.1.0 => 2.1.0 
      eslint-plugin-taro: 2.1.0 => 2.1.0 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by hejinguo** [comment]
@Chen-jj   
我怀疑是这里有问题。
![image](https://user-images.githubusercontent.com/19966301/79457117-3e425780-8022-11ea-8bef-34d35593d275.png)
