### ISSUE TITLE
yarn dev:alipay 或 build:alipay 报错 EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by dxiuxiu** [NervJS/taro#6065]
### 复现步骤

1.  yarn dev:alipay 或 build:alipay 报错 EBUSY: resource busy or locked，这个错误提示一般是使用一段时间编辑器（vsCode）后才会出现
2. 
3. 
4. 

```js
/**
 * 这里是完整的 2020-04-20T08_50_32_895Z-debug.log 内容
 */

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:alipay',
1 verbose cli   '--',
1 verbose cli   '--watch'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose run-script [ 'prebuild:alipay', 'build:alipay', 'postbuild:alipay' ]
5 info lifecycle kuxueyuan-cross-platform@1.0.0~prebuild:alipay: kuxueyuan-cross-platform@1.0.0
6 info lifecycle kuxueyuan-cross-platform@1.0.0~build:alipay: kuxueyuan-cross-platform@1.0.0
7 verbose lifecycle kuxueyuan-cross-platform@1.0.0~build:alipay: unsafe-perm in lifecycle true
8 verbose lifecycle kuxueyuan-cross-platform@1.0.0~build:alipay: PATH: C:\Users\11958\AppData\Roaming\nvm\v12.16.2\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\code\多端适配\200416\B\kuxueyuan-cross-platform\node_modules\.bin;C:\Users\11958\AppData\Local\Temp\yarn--1587372522288-0.1383179972770936;D:\code\多端适配\200416\B\kuxueyuan-cross-platform\node_modules\.bin;C:\Users\11958\AppData\Local\Yarn\Data\link\node_modules\.bin;C:\Users\11958\AppData\Local\Yarn\bin;C:\Program Files\libexec\lib\node_modules\npm\bin\node-gyp-bin;C:\Program Files\lib\node_modules\npm\bin\node-gyp-bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\11958\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Git\cmd;C:\Users\11958\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\11958\AppData\Local\Microsoft\WindowsApps;C:\Users\11958\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\11958\AppData\Roaming\nvm;C:\Program Files\nodejs
9 verbose lifecycle kuxueyuan-cross-platform@1.0.0~build:alipay: CWD: D:\code\多端适配\200416\B\kuxueyuan-cross-platform
10 silly lifecycle kuxueyuan-cross-platform@1.0.0~build:alipay: Args: [ '/d /s /c', 'taro build --type alipay "--watch"' ]
11 silly lifecycle kuxueyuan-cross-platform@1.0.0~build:alipay: Returned: code: 1  signal: null
12 info lifecycle kuxueyuan-cross-platform@1.0.0~build:alipay: Failed to exec build:alipay script
13 verbose stack Error: kuxueyuan-cross-platform@1.0.0 build:alipay: `taro build --type alipay "--watch"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\11958\AppData\Roaming\nvm\v12.16.2\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\11958\AppData\Roaming\nvm\v12.16.2\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid kuxueyuan-cross-platform@1.0.0
15 verbose cwd D:\code\多端适配\200416\B\kuxueyuan-cross-platform
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:alipay" "--" "--watch"
18 verbose node v12.16.2
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error kuxueyuan-cross-platform@1.0.0 build:alipay: `taro build --type alipay "--watch"`
22 error Exit status 1
23 error Failed at the kuxueyuan-cross-platform@1.0.0 build:alipay script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
尝试过重启编辑器但不能解决，
尝试过重启电脑可以解决
### 期望行为

希望 dev/build:alipay 可以正常启动项目
### 报错信息
yarn dev:alipay 或 build:alipay 报错 EBUSY: resource busy or locked

### 系统信息

$ npx taro info
� Taro v2.1.5

  Taro CLI 2.1.5 environment info: 
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by dxiuxiu** [comment]
尝试关闭钉钉小程序调试工具后再次 yarn dev/build:alipay 可以解决

**Comment by luckyadam** [comment]
应该是钉钉工具导致文件被锁了
