### ISSUE TITLE
初始化redux模板报错

### ISSUE THREAD

**Issue by guanjp** [NervJS/taro#6066]
### 问题描述

项目初始化时，选择redux模板报错

### 复现步骤

1. 执行 初始化命令
2. 输入项目介绍，选择TypeScript - Sass - redux
3. 报错

```js
npx @tarojs/cli init decorator_applet
? 请输入项目介绍！
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板 redux

```

### 期望行为

初始化

### 报错信息

```

👽 Taro v2.1.5

Taro 即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

√ 拉取远程模板仓库成功！
? 请输入项目介绍！
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板 redux
SyntaxError: Error parsing C:\Users\nineg\AppData\Roaming\npm-cache\_npx\7348\node_modules\@tarojs\cli\templates\redux\package.json: Unexpected token < in JSON at position 183
    at parse (<anonymous>)
    at readPackage (internal/modules/cjs/loader.js:257:20)
    at readPackageScope (internal/modules/cjs/loader.js:282:19)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1169:17)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\nineg\AppData\Roaming\npm-cache\_npx\7348\node_modules\@tarojs\cli\dist\create\init.
js:153:54)
    at Generator.next (<anonymous>) {
  path: 'C:\\Users\\nineg\\AppData\\Roaming\\npm-cache\\_npx\\7348\\node_modules\\@tarojs\\cli\\templates\\redux\\packag
e.json'
}
```

### 系统信息

```
 Taro CLI 2.1.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.1 - C:\Users\nineg\AppData\Local\nvs\default\node.EXE
      Yarn: 1.22.4 - C:\Users\nineg\.npm-global\yarn.CMD
      npm: 6.14.4 - C:\Users\nineg\.npm-global\npm.CMD
```

**Comment by Garfield550** [comment]
删掉 `C:\Users\nineg\taro` 和 `C:\Users\nineg\taro2` 这类文件夹，然后再试一下
