### ISSUE TITLE
taro 微信小程序 useImperativeHandle 问题

### ISSUE THREAD

**Issue by WuYunlong** [NervJS/taro#6069]
### 问题描述

组件代码
```javascript
import Taro,{useImperativeHandle} from '@tarojs/taro';
import {View} from '@tarojs/components';

const Demo = ({childRef}) => {
  useImperativeHandle(childRef, () => ({
    stop () {
      console.log("======")
    }
  }))
  return (
      <View className="demo">111</View>
  )
}

export default Demo;
```

页面代码

```javascript
import Taro,{useRef} from '@tarojs/taro';
import {View, Button} from '@tarojs/components';
import Demo from '../components/Demo';

const User = () => {
  let childRef = useRef();

  const handelClick = () => {
    console.log(childRef.current);
    childRef.current.stop()
  }

  return(
      <View className="wrap wrap-user">
        <Button onClick={handelClick}>测试</Button>
        <Demo childRef={childRef} />
      </View>
  )
}

export default User;
```

页面点击测试按钮控制台报错

![image](https://user-images.githubusercontent.com/3301446/79945211-ea12f980-849f-11ea-97f0-75f9eb8b80ca.png)

```

### 期望行为

能够正常执行到子组件到stop方法。

### 系统信息

```bash
👽 Taro v2.1.5


  Taro CLI 2.1.5 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v13.12.0/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
    npmPackages:
      @tarojs/components: 2.1.5 => 2.1.5 
      @tarojs/components-qa: 2.1.5 => 2.1.5 
      @tarojs/mini-runner: 2.1.5 => 2.1.5 
      @tarojs/mobx: 2.1.5 => 2.1.5 
      @tarojs/mobx-h5: 2.1.5 => 2.1.5 
      @tarojs/router: 2.1.5 => 2.1.5 
      @tarojs/taro: 2.1.5 => 2.1.5 
      @tarojs/taro-alipay: 2.1.5 => 2.1.5 
      @tarojs/taro-h5: 2.1.5 => 2.1.5 
      @tarojs/taro-qq: 2.1.5 => 2.1.5 
      @tarojs/taro-quickapp: 2.1.5 => 2.1.5 
      @tarojs/taro-swan: 2.1.5 => 2.1.5 
      @tarojs/taro-tt: 2.1.5 => 2.1.5 
      @tarojs/taro-weapp: 2.1.5 => 2.1.5 
      @tarojs/webpack-runner: 2.1.5 => 2.1.5 
      eslint-config-taro: 2.1.5 => 2.1.5 
      eslint-plugin-taro: 2.1.5 => 2.1.5 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.1.5 => 2.1.5 
      stylelint-taro-rn: 2.1.5 => 2.1.5 
```

**Comment by WuYunlong** [comment]
控制台报错信息如下
```javascript
Cannot read property 'stop' of undefined; [Component] Event Handler Error @ pages/user#(anonymous)
TypeError: Cannot read property 'stop' of undefined
    at User.handelClick [as anonymousFunc0] (http://127.0.0.1:21945/appservice/pages/user.js:79:26)
    at Se.obj.<computed> [as anonymousFunc0] (http://127.0.0.1:21945/appservice/taro.js:2454:36)
    at Object.r.safeCallback (http://127.0.0.1:21945/appservice/__dev__/WAService.js:2:1467232)
    at http://127.0.0.1:21945/appservice/__dev__/WAService.js:2:1586042
    at c (http://127.0.0.1:21945/appservice/__dev__/WAService.js:2:1593979)
    at http://127.0.0.1:21945/appservice/__dev__/WAService.js:2:1585967
    at r (http://127.0.0.1:21945/appservice/__dev__/WAService.js:2:1538494)
    at http://127.0.0.1:21945/appservice/__dev__/WAService.js:2:1538616
    at http://127.0.0.1:21945/appservice/__dev__/WAService.js:2:726082
    at n (http://127.0.0.1:21945/appservice/__dev__/asdebug.js:1:27118)
```

**Comment by WuYunlong** [comment]
@luckyadam 这个问题一直没有解决掉  能否看一下

**Comment by WuYunlong** [comment]
@luckyadam 这个问题一直没有解决掉 能否看一下

**Comment by yuwanlin** [comment]
3.0.8 有这个问题
