### ISSUE TITLE
通过模板初始化时taro init，错误提示

### ISSUE THREAD

**Issue by acharzuo** [NervJS/taro#6082]
### 问题描述
在项目初始化时，提示模板中的json错误。

### 复现步骤

1.   更新最新版的taro
```
$ yarn global add @tarojs/cli
yarn global v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@tarojs/cli > @typescript-eslint/parser > @typescript-eslint/typescript-estree > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] 🔨  Building fresh packages...
success Installed "@tarojs/cli@2.1.5" with binaries:
      - taro
✨  Done in 38.55s.
```
2.   创建一个本地项目
```
 taro init lmc_kids_app
👽 Taro v2.1.5

Taro 即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

✔ 拉取远程模板仓库成功！
? 请输入项目介绍！ 绿满仓儿童社区
? 是否需要使用 TypeScript ？ No
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板 redux
SyntaxError: Error parsing /Users/achar/.config/yarn/global/node_modules/@tarojs/cli/templates/redux/package.json: Unexpected token < in JSON at position 183
    at parse (<anonymous>)
    at readPackage (internal/modules/cjs/loader.js:257:20)
    at readPackageScope (internal/modules/cjs/loader.js:282:19)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1168:17)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/achar/.config/yarn/global/node_modules/@tarojs/cli/dist/create/init.js:153:54)
    at Generator.next (<anonymous>) {
  path: '/Users/achar/.config/yarn/global/node_modules/@tarojs/cli/templates/redux/package.json'
}
```
3. 错误提示
Unexpected token < in JSON at position 183
提示错误。
4. 
同样的设置，使用，默认模板可以建立

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
rm -rf ~/.taro2
然后重试
