### ISSUE TITLE
h5 启动 Error: Cyclic dependency

### ISSUE THREAD

**Issue by lian0121** [NervJS/taro#6153]
### 问题描述
h5启动报错。config里面如果只配置了一个页面，可以编译成功，如果多个就会报这个问题。

这是我的config，pages和subPackages这些都注释了，才能编译成功，取消注释就会报依赖循环，为什么？
config: Config = {
    pages: [
      "pages/index/index",
      // "pages/orderList/order",
      // "pages/userBar/user",
      // "pages/cart/cart",
    ],
    subPackages: [
      // {
      //   root: "subPackages/order",
      //   pages: [
      //     "order.pay",
      //     "order.pay.remark",
      //     "order.pay.coupon",
      //     "order.detail",
      //     "order.cancel",
      //     "order.refund",
      //     "order.refund.schedule"
      //   ]
      // },
      // {
      //   root: "subPackages/product",
      //   pages: [
      //     "product.detail",
      //     "product.search",
      //   ]
      // },
      // {
      //   root: "subPackages/user",
      //   pages: [
      //     "user.set",
      //     "user.coupon",
      //     "user.code",
      //   ]
      // },
      // {
      //   root: "subPackages/address",
      //   pages: [
      //     "address.list",
      //     "address.add",
      //     "address.edit",
      //     "address.change.index"
      //   ]
      // },
      // {
      //   root: "subPackages/login",
      //   pages: ["login", "login.userinfo"]
      // }
    ],
    window: {
      backgroundTextStyle: "light",
      navigationBarBackgroundColor: "#2a86fc",
      navigationBarTitleText: "WeChat",
      navigationBarTextStyle: "white"
    },
    tabBar: {
      color: "#ACACAC",
      selectedColor: "#2EAAF8",
      backgroundColor: "#ffffff",
      borderStyle: "black",
      list: [
        {
          pagePath: "pages/index/index",
          iconPath: "./assets/tab-bar/icon_nav_home.png",
          selectedIconPath: "./assets/tab-bar/icon_nav_home_selected.png",
          text: "首页"
        },
        {
          pagePath: "pages/orderList/order",
          iconPath: "./assets/tab-bar/icon_nav_order.png",
          selectedIconPath: "./assets/tab-bar/icon_nav_order_selected.png",
          text: "订单"
        },
        {
          pagePath: "pages/cart/cart",
          iconPath: "./assets/tab-bar/icon_nav_cart.png",
          selectedIconPath: "./assets/tab-bar/icon_nav_cart_selected.png",
          text: "购物车"
        },
        {
          pagePath: "pages/user/user",
          iconPath: "./assets/tab-bar/icon_nav_mine.png",
          selectedIconPath: "./assets/tab-bar/icon_nav_mine_selected.png",
          text: "我的"
        }
      ]
    },
    permission: {
      "scope.userLocation": {
        desc: "你的位置信息将用于小程序位置接口的效果展示" // 高速公路行驶持续后台定位
      }
    }
  };
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 报错信息

Compiling...E:\workspace\Jxc-sy-web\h5\github\scanbar-costom\node_modules\toposort\index.js:35
      throw new Error('Cyclic dependency' + nodeRep)
      ^

Error: Cyclic dependency
    at visit (E:\workspace\Jxc-sy-web\h5\github\scanbar-costom\node_modules\toposort\index.js:35:13)
    at visit (E:\workspace\Jxc-sy-web\h5\github\scanbar-costom\node_modules\toposort\index.js:53:9)
    at visit (E:\workspace\Jxc-sy-web\h5\github\scanbar-costom\node_modules\toposort\index.js:53:9)
    at Function.toposort [as array] (E:\workspace\Jxc-sy-web\h5\github\scanbar-costom\node_modules\toposort\index.js:22:22)
    at Object.module.exports.dependency (E:\workspace\Jxc-sy-web\h5\github\scanbar-costom\node_modules\html-webpack-plugin\lib\chunksorter.js:50:35)
    at HtmlWebpackPlugin.sortChunks (E:\workspace\Jxc-sy-web\h5\github\scanbar-costom\node_modules\html-webpack-plugin\index.js:364:35)
    at E:\workspace\Jxc-sy-web\h5\github\scanbar-costom\node_modules\html-webpack-plugin\index.js:113:21
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\workspace\Jxc-sy-web\h5\github\scanbar-costom\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:5:1)
    at AsyncSeriesHook.lazyCompileHook (E:\workspace\Jxc-sy-web\h5\github\scanbar-costom\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.emitAssets (E:\workspace\Jxc-sy-web\h5\github\scanbar-costom\node_modules\webpack\lib\Compiler.js:367:19)
    at onCompiled (E:\workspace\Jxc-sy-web\h5\github\scanbar-costom\node_modules\webpack\lib\Watching.js:50:19)     
    at E:\workspace\Jxc-sy-web\h5\github\scanbar-costom\node_modules\webpack\lib\Compiler.js:556:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\workspace\Jxc-sy-web\h5\github\scanbar-costom\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at AsyncSeriesHook.lazyCompileHook (E:\workspace\Jxc-sy-web\h5\github\scanbar-costom\node_modules\tapable\lib\Hook.js:154:20)
    at E:\workspace\Jxc-sy-web\h5\github\scanbar-costom\node_modules\webpack\lib\Compiler.js:553:30
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\workspace\Jxc-sy-web\h5\github\scanbar-costom\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by lian0121** [comment]
@Littly 可以帮我看看么

**Comment by singlehcc** [comment]
我也遇到了

**Comment by ZakaryCode** [comment]
未能复现该问题，如确实存在，可以提交一个能够复现的样例
