### ISSUE TITLE
taro init 初始化项目报错

### ISSUE THREAD

**Issue by harrisoff** [NervJS/taro#6170]
### 问题描述

`taro init` 初始化项目报错

### 复现步骤

1. `npm install -g @tarojs/cli`
2. `taro init test`

### 报错信息

![impicture_20200429_214808](https://user-images.githubusercontent.com/29137942/80603909-98e8a400-8a63-11ea-9494-075b9bb7496a.png)

### 系统信息

λ taro info
� Taro v2.2.1

(node:13212) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at normalizePath (C:\Users\admin\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\dist\utils.js:25:37)
    at recursiveFindNodeModules (C:\Users\admin\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\dist\utils.js:120:9)
    at recursiveFindNodeModules (C:\Users\admin\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\dist\utils.js:133:12)
    at recursiveFindNodeModules (C:\Users\admin\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\dist\utils.js:133:12)
    at recursiveFindNodeModules (C:\Users\admin\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\dist\utils.js:133:12)
    at recursiveFindNodeModules (C:\Users\admin\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\dist\utils.js:133:12)
    at recursiveFindNodeModules (C:\Users\admin\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\dist\utils.js:133:12)
    at recursiveFindNodeModules (C:\Users\admin\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\dist\utils.js:133:12)
    at recursiveFindNodeModules (C:\Users\admin\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\dist\utils.js:133:12)
(node:13212) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13212) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by HanleyCN** [comment]
同样报错 +1

**Comment by luckyadam** [comment]
试试 2.2.2

**Comment by HanleyCN** [comment]
> 试试 2.2.2

已经正常

**Comment by luckyadam** [comment]
ok

**Comment by harrisoff** [comment]
2.2.x 不兼容 2.1.x 创建的项目。minor 版本升级也会不兼容，一直都是这样的吗，还是 bug？
