### ISSUE TITLE
引入 Taro UI  小程序端提示报错

### ISSUE THREAD

**Issue by aq76472220** [NervJS/taro#6197]
引入 Taro UI
小程序端提示报错

VM3292:1 jsEnginScriptError
Component is not found in path "npm/taro-ui/dist/weapp/components/tabs/index" (using by "pages/otherClassify/otherClassify");onAppRoute
Error: Component is not found in path "npm/taro-ui/dist/weapp/components/tabs/index" (using by "pages/otherClassify/otherClassify")
    at q (http://127.0.0.1:39247/appservice/__dev__/WAService.js:2:1631416)
    at q (http://127.0.0.1:39247/appservice/__dev__/WAService.js:2:1631620)
    at http://127.0.0.1:39247/appservice/__dev__/WAService.js:2:1653569
    at Module.He (http://127.0.0.1:39247/appservice/__dev__/WAService.js:2:1654148)
    at Function.value (http://127.0.0.1:39247/appservice/__dev__/WAService.js:2:1744838)
    at xt (http://127.0.0.1:39247/appservice/__dev__/WAService.js:2:1761097)
    at http://127.0.0.1:39247/appservice/__dev__/WAService.js:2:1765354
    at Mt (http://127.0.0.1:39247/appservice/__dev__/WAService.js:2:1765847)
    at Function.<anonymous> (http://127.0.0.1:39247/appservice/__dev__/WAService.js:2:1773952)
    at i.<anonymous> (http://127.0.0.1:39247/appservice/__dev__/WAService.js:2:1737576)

**Comment by beilunyang** [comment]
我也遇到了相同的问题。经过排查，是cnpm导致的
### 解决方法
把通过cnpm install安装的node_modules全部删除，然后用npm install或yarn安装

**Comment by aq76472220** [comment]
试了 不行&nbsp;

用的 是 最新版本 的 taro-cli 脚手架 和最新的 taro-ui

**Comment by aq76472220** [comment]
cpm 不行 用 npm&nbsp; 是吧 npm 我试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "悖论"<notifications@github.com&gt;; 
发送时间: 2020年5月2日(星期六) 下午4:14
收件人: "NervJS/taro"<taro@noreply.github.com&gt;; 
抄送: "旋风"<793198567@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [NervJS/taro] 引入 Taro UI  小程序端提示报错 (#6197)





 
我也遇到了相同的问题。经过排查，是cnpm导致的
 
解决方法
 
把通过cnpm install安装的node_modules全部删除，然后用npm install或yarn安装

**Comment by aq76472220** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"悖论"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月2日(星期六) 下午4:14
收件人:&nbsp;"NervJS/taro"<taro@noreply.github.com&gt;;
抄送:&nbsp;"旋风"<793198567@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NervJS/taro] 引入 Taro UI  小程序端提示报错 (#6197)





 
我也遇到了相同的问题。经过排查，是cnpm导致的
 
解决方法
 
把通过cnpm install安装的node_modules全部删除，然后用npm install或yarn安装
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.




非常感谢 解决了

**Comment by yulrosy** [comment]
我是升到2.2.14遇到了这个问题，降回2.2.13了
