### ISSUE TITLE
v2.2.3 ===> 引入@tarojs/plugin-mock插件编译错误

### ISSUE THREAD

**Issue by HanZhaorz** [NervJS/taro#6227]
### 问题描述
Taro v2.2.3
引入@tarojs/plugin-mock时编译错误

### 复现步骤
```js
// /config/index.js
const config = {
  ...,
  plugins: [
    [
      '@tarojs/plugin-mock',
      {
        mocks: {
          '/api/mock': {
            name: 'hanzhaorz',
            desc: 'author',
          },
        },
      },
    ],
  ],
  ...
}
```

### 期望行为

编译通过，可以使用数据mock

### 报错信息

(node:74996) UnhandledPromiseRejectionWarning: Error: Cannot find module './dist/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/oliver/Projects/template/taro-template/node_modules/@tarojs/plugin-mock/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module._compile (/Users/oliver/.nvm/versions/node/v10.16.0/lib/node_modules/@tarojs/cli/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.newLoader [as .js] (/Users/oliver/.nvm/versions/node/v10.16.0/lib/node_modules/@tarojs/cli/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
(node:74996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:74996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### 系统信息
使用`taro info`也是同样的报错

### 补充信息

**Comment by luckyadam** [comment]
遗憾，发出的 @tarojs/plugin-mock 包有点问题，你把它升级到 0.0.4 试试

**Comment by HanZhaorz** [comment]
@luckyadam 升级到0.0.4之后可以使用了，但是每次保存重新编译都会重启服务 端口也会变化
![image](https://user-images.githubusercontent.com/51203752/81249584-8cf77600-9051-11ea-8bdf-a5516544e29c.png)

**Comment by HanZhaorz** [comment]
@luckyadam 多次保存后就直接报错了
![image](https://user-images.githubusercontent.com/51203752/81249659-c203c880-9051-11ea-9236-64a37929dfd8.png)

**Comment by luckyadam** [comment]
了解，看来还是插件写得有点问题，待我再更新一个版本

**Comment by luckyadam** [comment]
https://github.com/NervJS/taro-plugin-mock/commit/8af10cdf891caed262b4846b7550b10c9cd4e6b2
可以升级到 0.0.5 试试

**Comment by HanZhaorz** [comment]
可以了 完美 大佬🐂🍺

**Comment by luckyadam** [comment]
OJBK
