### ISSUE TITLE
build 过程中下载快应用运行容器错误

### ISSUE THREAD

**Issue by izhangshaolin** [NervJS/taro#6239]
### 问题描述

根据官网进行配置 打包quickapp出错, 下载快应用容器过程中报错

### 复现步骤

执行yarn dev:quickapp

### 报错信息

$ npm run build:quickapp -- --watch
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1588844060965-0.1616723816240171/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> myApp@1.0.0 build:quickapp /home/mi/zsl/myApp
> taro build --type quickapp "--watch"

👽 Taro v2.2.3

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
编译  发现入口  src/app.jsx
编译  发现页面  src/pages/index/index.jsx
✅  编译成功

监听文件修改中...

⠙ 开始下载快应用运行容器.../home/mi/.config/yarn/global/node_modules/@tarojs/cli/node_modules/fs-extra/lib/move-sync/index.js:46
        throw err
        ^

Error: EEXIST: file already exists, link '/home/mi/zsl/myApp/download_temp.zip' -> '/home/mi/zsl/myApp/dist/download_temp.zip'
    at Object.linkSync (fs.js:934:3)
    at tryRenameSync (/home/mi/.config/yarn/global/node_modules/@tarojs/cli/node_modules/fs-extra/lib/move-sync/index.js:40:12)
    at Object.moveSync (/home/mi/.config/yarn/global/node_modules/@tarojs/cli/node_modules/fs-extra/lib/move-sync/index.js:22:3)
    at Request.request.on.on (/home/mi/.config/yarn/global/node_modules/@tarojs/cli/dist/util/dowload.js:51:24)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/mi/.config/yarn/global/node_modules/request/request.js:1091:14)
    at Request.emit (events.js:187:15)
    at IncomingMessage.<anonymous> (/home/mi/.config/yarn/global/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myApp@1.0.0 build:quickapp: `taro build --type quickapp "--watch"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myApp@1.0.0 build:quickapp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mi/.npm/_logs/2020-05-07T09_34_30_847Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### 系统信息

 Taro v2.2.3

  Taro CLI 2.2.3 environment info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.3 => 2.2.3 
      @tarojs/components-qa: 2.2.3 => 2.2.3 
      @tarojs/mini-runner: 2.2.3 => 2.2.3 
      @tarojs/router: 2.2.3 => 2.2.3 
      @tarojs/taro: 2.2.3 => 2.2.3 
      @tarojs/taro-alipay: 2.2.3 => 2.2.3 
      @tarojs/taro-h5: 2.2.3 => 2.2.3 
      @tarojs/taro-qq: 2.2.3 => 2.2.3 
      @tarojs/taro-quickapp: 2.2.3 => 2.2.3 
      @tarojs/taro-rn: 2.2.3 => 2.2.3 
      @tarojs/taro-swan: 2.2.3 => 2.2.3 
      @tarojs/taro-tt: 2.2.3 => 2.2.3 
      @tarojs/taro-weapp: 2.2.3 => 2.2.3 
      @tarojs/webpack-runner: 2.2.3 => 2.2.3 
      eslint-config-taro: 2.2.3 => 2.2.3 
      eslint-plugin-taro: 2.2.3 => 2.2.3 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.2.3 => 2.2.3 
      stylelint-taro-rn: 2.2.3 => 2.2.3

**Comment by paulloo** [comment]
`
开始下载快应用运行容器...D:\MyConfiguration\xxx\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\util\dowload.js:26
                throw new Error('快应用容器版本请求失败，请重试！');
Error: 快应用容器版本请求失败，请重试！
at Request.request [as _callback] (D:\MyConfiguration\xxx\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\util\dowload.js:26:23)`

**Comment by izhangshaolin** [comment]
thanks
