### ISSUE TITLE
进行小程序插件开发报错（taro ）

### ISSUE THREAD

**Issue by HaloWang** [NervJS/taro#6243]
### 问题描述

我依照[官方文档](https://nervjs.github.io/taro/docs/miniprogram-plugin.html)进行小程序插件开发报错

### 复现步骤

执行 taro init，并按照提示选择

_TypeScript(Y/n) 不论是不是 typescript 都不行_

1. 创建项目

```
taro init
👽 Taro v2.2.3

Taro 即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

✔ 拉取远程模板仓库成功！
? 请输入项目名称！ address
? 请输入项目介绍！ 
? 是否需要使用 TypeScript ？ No
? 请选择 CSS 预处理器（Sass/Less/Stylus） Less
? 请选择模板 wxplugin

✔ 创建项目: address
✔ 创建文件: address/.editorconfig
✔ 创建文件: address/.eslintrc
✔ 创建文件: address/.gitignore
✔ 创建文件: address/pkg
✔ 创建文件: address/project.config.json
✔ 创建文件: address/config/dev.js
✔ 创建文件: address/config/index.js
✔ 创建文件: address/config/prod.js
✔ 创建文件: address/src/app.less
✔ 创建文件: address/src/app.jsx
✔ 创建文件: address/src/pages/index/index.less
✔ 创建文件: address/src/pages/index/index.jsx
✔ 创建文件: address/src/plugin/index.js
✔ 创建文件: address/src/plugin/plugin.json
✔ 创建文件: address/src/plugin/doc/README.md
✔ 创建文件: address/src/plugin/doc/example.jpeg
✔ 创建文件: address/src/plugin/components/avatar/avatar.less
✔ 创建文件: address/src/plugin/components/avatar/avatar.jsx
✔ 创建文件: address/src/plugin/components/listItem/listItem.less
✔ 创建文件: address/src/plugin/components/listItem/listItem.jsx
✔ 创建文件: address/src/plugin/pages/list/list.less
✔ 创建文件: address/src/plugin/pages/list/list.jsx

✔ cd address, 执行 git init
✔ 安装成功
warning @tarojs/components > omit.js > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @tarojs/mini-runner > babel-plugin-preval > babel-register > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @tarojs/mini-runner > scss-bundle > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @tarojs/mini-runner > webpack > watchpack > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @tarojs/webpack-runner > webpack-format-messages > kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
warning @tarojs/webpack-runner > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
warning "@tarojs/mini-runner > babel-loader@8.1.0" has unmet peer dependency "@babel/core@^7.0.0".
yarn install v1.22.4
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 44.33s.

创建项目 address 成功！
请进入项目目录 address 开始工作吧！😝
```
2. 编译

```
taro build --plugin weapp
```

### 期望行为

不出错

### 报错信息

```
➜  Desktop cd address
➜  address git:(master) ✗ taro build --plugin weapp
👽 Taro v2.2.3

开始编译微信小程序插件
生成  工具配置  /Users/USER_NAME/Desktop/address/miniprogram/project.config.json

The "path" argument must be of type string or an instance of Buffer or URL. Received undefined


The "path" argument must be of type string or an instance of Buffer or URL. Received undefined


(node:21282) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (fs.js:450:10)
    at Object.readFileSync (fs.js:360:35)
    at MiniPlugin.getPages (/Users/USER_NAME/Desktop/address/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:465:25)
    at MiniPlugin.run (/Users/USER_NAME/Desktop/address/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:1007:18)
    at MiniPlugin.<anonymous> (/Users/USER_NAME/Desktop/address/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:160:24)
    at Generator.next (<anonymous>)
    at /Users/USER_NAME/Desktop/address/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/USER_NAME/Desktop/address/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:4:12)
    at /Users/USER_NAME/Desktop/address/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:159:78
    at MiniPlugin.<anonymous> (/Users/USER_NAME/Desktop/address/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:100:23)
    at Generator.next (<anonymous>)
    at /Users/USER_NAME/Desktop/address/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/USER_NAME/Desktop/address/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:4:12)
    at /Users/USER_NAME/Desktop/address/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:98:50
(node:21282) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:21282) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### 系统信息

```
  Taro CLI 2.2.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.3 => 2.2.3 
      @tarojs/components-qa: 2.2.3 => 2.2.3 
      @tarojs/mini-runner: 2.2.3 => 2.2.3 
      @tarojs/router: 2.2.3 => 2.2.3 
      @tarojs/taro: 2.2.3 => 2.2.3 
      @tarojs/taro-alipay: 2.2.3 => 2.2.3 
      @tarojs/taro-h5: 2.2.3 => 2.2.3 
      @tarojs/taro-qq: 2.2.3 => 2.2.3 
      @tarojs/taro-quickapp: 2.2.3 => 2.2.3 
      @tarojs/taro-swan: 2.2.3 => 2.2.3 
      @tarojs/taro-tt: 2.2.3 => 2.2.3 
      @tarojs/taro-weapp: 2.2.3 => 2.2.3 
      @tarojs/webpack-runner: 2.2.3 => 2.2.3 
      eslint-config-taro: 2.2.3 => 2.2.3 
      eslint-plugin-taro: 2.2.3 => 2.2.3 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
    npmGlobalPackages:
      typescript: 3.8.3
```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by HaloWang** [comment]
```javascript
MiniPlugin.appEntry // undefined
```

**Comment by zxjBigPower** [comment]
我这边手动给miniprogram/plugin下添加了一个index.js,但遇到了新的问题，插件页面中无法引入taro UI 组件，会报：
Component is not found in path "plugin-private://wx2b61b5040da8f2b9/pages/components/input/index" (using by "plugin-private://wx2b61b5040da8f2b9/pages/list/list");`onAppRoute`
这个错误

**Comment by easonzhuyi** [comment]
遇到同样的问题，求解

**Comment by PennHan** [comment]
遇到同样的问题，求解，taro版本2.2.6
