### ISSUE TITLE
不支持ES6模块的export 和from混写的方式

### ISSUE THREAD

**Issue by yuyongyu08** [NervJS/taro#6259]
### 复现步骤

1. 
taro init

2. 
在工程中新增页面mylist，里面只有hello world

3. 
新增一个list页面，意欲完全复用mylist的逻辑
list.jsx:
```
export * from '../mylist/mylist'
```
并在app.jsx中配置:
```
pages: [
      'pages/index/index',
      'pages/mylist/mylist',
      'pages/list/list'
    ]
```
4. 
执行taro build，报错如下：
```
👽 Taro v2.1.0

开始编译项目 taro-weapp
生成  工具配置  dist/project.config.json

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
编译  发现入口  src/app.jsx
编译  发现页面  src/pages/index/index.jsx
编译  发现页面  src/pages/mylist/mylist.jsx
编译  发现组件  src/components/ListItem/ListItem.jsx
编译  发现页面  src/pages/list/list.jsx
⠙ 正在编译...{ SyntaxError: Unexpected token (1:64)
    at Parser.pp$5.raise (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babylon/lib/index.js:3750:12)
    at Parser.parseExprAtom (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babylon/lib/index.js:7238:22)
    at Parser.pp$3.parseExprSubscripts (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExprListItem (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babylon/lib/index.js:4312:16)
    at Parser.pp$3.parseCallExpressionArguments (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babylon/lib/index.js:3573:20)
    at Parser.pp$3.parseSubscripts (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babylon/lib/index.js:3533:31)
    at Parser.pp$3.parseExprSubscripts (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babylon/lib/index.js:3504:15)
    at Parser.pp$3.parseMaybeUnary (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babylon/lib/index.js:3381:19)from
    at exports.default (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babel-template/lib/index.js:12:11)
    at exit (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/@tarojs/mini-runner/dist/utils/processAst.js:493:44)
    at NodePath._call (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babel-traverse/lib/index.js:114:17)
    at Object.traverse [as default] (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/babel-traverse/lib/index.js:79:12)
    at Object.processAst [as default] (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/@tarojs/mini-runner/dist/utils/processAst.js:33:29)
    at Object.wxTransformerLoader (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/@tarojs/mini-runner/dist/loaders/wxTransformerLoader.js:80:48)
    at LOADER_EXECUTION (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/yuyongyu/Documents/codes/Taro/taro-weapp/node_modules/loader-runner/lib/LoaderRunner.js:205:4) pos: 64, loc: Position { line: 1, column: 64 } }
🙅   编译失败.

./src/pages/list/list.jsx
Module Error (from ./node_modules/@tarojs/mini-runner/dist/loaders/wxTransformerLoader.js):
Unexpected token (1:64)
```

### 系统信息

```
👽 Taro v2.1.0


  Taro CLI 2.1.0 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.1 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: ^2.1.0 => 2.1.0 
      @tarojs/components: 2.1.0 => 2.1.0 
      @tarojs/components-qa: 2.1.0 => 2.1.0 
      @tarojs/mini-runner: 2.1.0 => 2.1.0 
      @tarojs/router: 2.1.0 => 2.1.0 
      @tarojs/taro: 2.1.0 => 2.1.0 
      @tarojs/taro-alipay: 2.1.0 => 2.1.0 
      @tarojs/taro-h5: 2.1.0 => 2.1.0 
      @tarojs/taro-qq: 2.1.0 => 2.1.0 
      @tarojs/taro-quickapp: 2.1.0 => 2.1.0 
      @tarojs/taro-rn: 2.1.0 => 2.1.0 
      @tarojs/taro-swan: 2.1.0 => 2.1.0 
      @tarojs/taro-tt: 2.1.0 => 2.1.0 
      @tarojs/taro-weapp: 2.1.0 => 2.1.0 
      @tarojs/webpack-runner: 2.1.0 => 2.1.0 
      eslint-config-taro: 2.1.0 => 2.1.0 
      eslint-plugin-taro: 2.1.0 => 2.1.0 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.1.0 => 2.1.0 
      stylelint-taro-rn: 2.1.0 => 2.1.0 
```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
不支持这么用，如果是两个一样的页面，建议把公共内容抽成组件，然后两个页面分别引用
