### ISSUE TITLE
taro快应用调试器报错

### ISSUE THREAD

**Issue by YunySun** [NervJS/taro#6305]
### 问题描述

快应用虽然启动IDE没问题 但是 放到调试器报错

```js
webpack-internal:///./node_modules/@hap-toolkit/dsl-xvm/lib/loader/script-loader.js!./node_modules/@hap-toolkit/dsl-xvm/lib/loader/module-loader.js!./node_modules/babel-loader/lib/index.js?cwd=/Users/lichang/Learning/Taro/yanqingkong/dist&cacheDirectory&plugins[]=/Users/lichang/Learning/Taro/yanqingkong/dist/node_modules/@hap-toolkit/dsl-xvm/lib/loader/babel-plugin-jsx.js&comments=false!./node_modules/@hap-toolkit/dsl-xvm/lib/loader/fragment-loader.js?index=0&type=script!./src/npm/@tarojs/components-qa/src/components/taro-page/index.ux?uxType=comp:50: TypeError: Cannot read property '' of undefined
TypeError: Cannot read property '' of undefined
    at Ne.data (webpack-internal:///./node_modules/@hap-toolkit/dsl-xvm/lib/loader/script-loader.js!./node_modules/@hap-toolkit/dsl-xvm/lib/loader/module-loader.js!./node_modules/babel-loader/lib/index.js?cwd=/Users/lichang/Learning/Taro/yanqingkong/dist&cacheDirectory&plugins[]=/Users/lichang/Learning/Taro/yanqingkong/dist/node_modules/@hap-toolkit/dsl-xvm/lib/loader/babel-plugin-jsx.js&comments=false!./node_modules/@hap-toolkit/dsl-xvm/lib/loader/fragment-loader.js?index=0&type=script!./src/npm/@tarojs/components-qa/src/components/taro-page/index.ux?uxType=comp:50:50)
    at new Ne (<anonymous>:1:30559)
    at <anonymous>:1:20096
    at _e (<anonymous>:1:20342)
    at new Ne (<anonymous>:1:32219)
    at gt (<anonymous>:1:49712)
    at s (<anonymous>:1:53976)
    at eval (webpack-internal:///./src/pages/index/index.ux?uxType=page:15:1)
    at Object../src/pages/index/index.ux?uxType=page (pages/index/index.js:224:1)
    at __webpack_require__ (pages/index/index.js:23:30)
com.eclipsesource.v8.V8ScriptExecutionException
	at com.eclipsesource.v8.V8._executeVoidFunction(Native Method)
	at com.eclipsesource.v8.V8.executeVoidFunction(SourceFile:1154)
	at com.eclipsesource.v8.V8Object.executeVoidFunction(SourceFile:435)
	at org.hapjs.render.jsruntime.JsThread.b(SourceFile:963)
	at org.hapjs.render.jsruntime.JsThread.a(SourceFile:82)
	at org.hapjs.render.jsruntime.JsThread$a.handleMessage(SourceFile:264)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:165)
	at android.os.HandlerThread.run(HandlerThread.java:61)

```

### 系统信息

  Taro CLI 2.2.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.npm-global/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.3 => 2.2.3 
      @tarojs/components-qa: 2.2.3 => 2.2.3 
      @tarojs/mini-runner: 2.2.3 => 2.2.3 
      @tarojs/router: 2.2.3 => 2.2.3 
      @tarojs/taro: 2.2.3 => 2.2.3 
      @tarojs/taro-alipay: 2.2.3 => 2.2.3 
      @tarojs/taro-h5: 2.2.3 => 2.2.3 
      @tarojs/taro-qq: 2.2.3 => 2.2.3 
      @tarojs/taro-quickapp: 2.2.3 => 2.2.3 
      @tarojs/taro-rn: 2.2.3 => 2.2.3 
      @tarojs/taro-swan: 2.2.3 => 2.2.3 
      @tarojs/taro-tt: 2.2.3 => 2.2.3 
      @tarojs/taro-weapp: 2.2.3 => 2.2.3 
      @tarojs/webpack-runner: 2.2.3 => 2.2.3 
      eslint-config-taro: 2.2.3 => 2.2.3 
      eslint-plugin-taro: 2.2.3 => 2.2.3 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.2.3 => 2.2.3 
      stylelint-taro-rn: 2.2.3 => 2.2.3 
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by zhiqingchen** [comment]
升级到2.2.7
https://github.com/NervJS/taro/commit/15f40f019e745e4fb8e173c2615fe035b4f85a84
