### ISSUE TITLE
@tarojs/cli@2.2.3 编译小程序报错

### ISSUE THREAD

**Issue by wujunchuan** [NervJS/taro#6321]
### 问题描述

执行 `yarn run dev:weapp`会报错

Cannot read property 'hooks' of undefined

### 复现步骤

1.  `yarn global add @tarojs/cli@2.2.3`
2. `yarn run dev:weapp`

### 报错信息

```
Cannot read property 'hooks' of undefined


Cannot read property 'hooks' of undefined


(node:57689) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hooks' of undefined
    at Watching.handler (/Users/wujunchuan/Project/source/taro-did/node_modules/@tarojs/mini-runner/dist/index.js:50:33)
    at /Users/wujunchuan/Project/source/taro-did/node_modules/@tarojs/mini-runner/node_modules/webpack/lib/Watching.js:99:9
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/wujunchuan/Project/source/taro-did/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/wujunchuan/Project/source/taro-did/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._done (/Users/wujunchuan/Project/source/taro-did/node_modules/@tarojs/mini-runner/node_modules/webpack/lib/Watching.js:98:28)
    at /Users/wujunchuan/Project/source/taro-did/node_modules/@tarojs/mini-runner/node_modules/webpack/lib/Watching.js:73:19
    at Compiler.emitRecords (/Users/wujunchuan/Project/source/taro-did/node_modules/@tarojs/mini-runner/node_modules/webpack/lib/Compiler.js:499:39)
    at /Users/wujunchuan/Project/source/taro-did/node_modules/@tarojs/mini-runner/node_modules/webpack/lib/Watching.js:54:20
    at /Users/wujunchuan/Project/source/taro-did/node_modules/@tarojs/mini-runner/node_modules/webpack/lib/Compiler.js:485:14
    at eval (eval at create (/Users/wujunchuan/Project/source/taro-did/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at MiniPlugin.<anonymous> (/Users/wujunchuan/Project/source/taro-did/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:109:17)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/wujunchuan/Project/source/taro-did/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:5:58)
(node:57689) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:57689) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 22.66s.
```

### 系统信息

```
👽 Taro v2.2.4


  Taro CLI 2.2.4 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
    npmPackages:
      @tarojs/components: 2.1.6 => 2.1.6 
      @tarojs/components-qa: 2.1.6 => 2.1.6 
      @tarojs/mini-runner: 2.1.6 => 2.1.6 
      @tarojs/redux: 2.1.6 => 2.1.6 
      @tarojs/redux-h5: 2.1.6 => 2.1.6 
      @tarojs/router: 2.1.6 => 2.1.6 
      @tarojs/taro: 2.1.6 => 2.1.6 
      @tarojs/taro-alipay: 2.1.6 => 2.1.6 
      @tarojs/taro-h5: 2.1.6 => 2.1.6 
      @tarojs/taro-qq: 2.1.6 => 2.1.6 
      @tarojs/taro-quickapp: 2.1.6 => 2.1.6 
      @tarojs/taro-swan: 2.1.6 => 2.1.6 
      @tarojs/taro-tt: 2.1.6 => 2.1.6 
      @tarojs/taro-weapp: 2.1.6 => 2.1.6 
      @tarojs/webpack-runner: 2.1.6 => 2.1.6 
      eslint-config-taro: 2.1.6 => 2.1.6 
      eslint-plugin-taro: 2.1.6 => 2.1.6 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.1.6 => 2.1.6 
      stylelint-taro-rn: 2.1.6 => 2.1.6 
      taro-ui: ^2.3.4 => 2.3.4 


```

### 补充信息

降级 `yarn global add @tarojs/cli@2.1.6` 后就不会有这个错误

由于时间有限, 只测试了@2.1.6 与 @2.2.3版本,其他版本没试过

**Comment by luckyadam** [comment]
首先，cli 与项目依赖版本保持一致
其次，看下文档中 plugins 是如何配置的
https://nervjs.github.io/taro/docs/config-detail.html#plugins

**Comment by liuwei0514** [comment]
"dependencies 加一行  "@tarojs/cli": "2.1.0",
编译的时候就会使用项目node_modules下的taro cli  运行后看到的taro版本就对了 
> taro build --type weapp "--watch"
👽 Taro v2.1.0

这样不用每次切换全局版本 暂时没发现什么问题
