### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by manyhelp** [NervJS/taro#6323]
### 安装报错

```js
cnpm install -g @tarojs/cli
Downloading @tarojs/cli to D:\nodejs\node_global\node_modules\@tarojs\cli_tmp
Copying D:\nodejs\node_global\node_modules\@tarojs\cli_tmp\_@tarojs_cli@2.2.4@@tarojs\cli to D:\nodejs\node_global\node_modules\@tarojs\cli
Installing @tarojs/cli's dependencies to D:\nodejs\node_global\node_modules\@tarojs\cli/node_modules
Install fail! Error: [@tarojs/service@2.2.4 › @tarojs/taro@^2.2.4] Can't find package @tarojs/taro@^2.2.4
Error: [@tarojs/service@2.2.4 › @tarojs/taro@^2.2.4] Can't find package @tarojs/taro@^2.2.4
    at resolve (D:\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\lib\download\npm.js:80:11)
    at resolve.next (<anonymous>)
    at onFulfilled (D:\nodejs\node_global\node_modules\cnpm\node_modules\co\index.js:65:19)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
npminstall version: 3.25.2
npminstall args: D:\nodejs\node.exe D:\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\12121\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://r.npm.taobao.org -g @tarojs/cli

```

**Comment by luckyadam** [comment]
可以再试试，2.2.4 刚发的包

**Comment by cheneywan** [comment]
![image](https://user-images.githubusercontent.com/2441562/81889766-f7bb2b00-95d6-11ea-8864-4c2abfff90d9.png)
用 yarn 好像也是报 没有找到 2.2.4 的版本

**Comment by huanlirui** [comment]
> ![image](https://user-images.githubusercontent.com/2441562/81889766-f7bb2b00-95d6-11ea-8864-4c2abfff90d9.png)
> 用 yarn 好像也是报 没有找到 2.2.4 的版本

我也是这样。什么情况。怎么解决的？

**Comment by Garfield550** [comment]
等几个小时，CNPM 和 Yarn 都需要抓 NPM 的数据才能找到今天新发的包
