### ISSUE TITLE
2.2.5 下快应用真机调试报错

### ISSUE THREAD

**Issue by nanjingboy** [NervJS/taro#6379]
### 问题描述

升级到 2.2.5 后，快应用真机调试报以下错误：

```
webpack-internal:///../../../../../Applications/快应用开发工具.app/Contents/Resources/app/extensions/hap-debugger/node_modules/@hap-toolkit/dsl-xvm/lib/loader/script-loader.js!../../../../../Applications/快应用开发工具.app/Contents/Resources/app/extensions/hap-debugger/node_modules/@hap-toolkit/dsl-xvm/lib/loader/module-loader.js!./node_modules/babel-loader/lib/index.js?cwd=/Users/Tom/workspace/taro-demo/dist&cacheDirectory&plugins[]=/Applications/快应用开发工具.app/Contents/Resources/app/extensions/hap-debugger/node_modules/@hap-toolkit/dsl-xvm/lib/loader/babel-plugin-jsx.js&comments=false!../../../../../Applications/快应用开发工具.app/Contents/Resources/app/extensions/hap-debugger/node_modules/@hap-toolkit/dsl-xvm/lib/loader/fragment-loader.js?index=0&type=script!./src/npm/@tarojs/components-qa/src/components/taro-page/index.ux?uxType=comp:51: TypeError: Cannot read property '' of undefined
TypeError: Cannot read property '' of undefined
    at Re.data (webpack-internal:///../../../../../Applications/快应用开发工具.app/Contents/Resources/app/extensions/hap-debugger/node_modules/@hap-toolkit/dsl-xvm/lib/loader/script-loader.js!../../../../../Applications/快应用开发工具.app/Contents/Resources/app/extensions/hap-debugger/node_modules/@hap-toolkit/dsl-xvm/lib/loader/module-loader.js!./node_modules/babel-loader/lib/index.js?cwd=/Users/Tom/workspace/taro-demo/dist&cacheDirectory&plugins[]=/Applications/快应用开发工具.app/Contents/Resources/app/extensions/hap-debugger/node_modules/@hap-toolkit/dsl-xvm/lib/loader/babel-plugin-jsx.js&comments=false!../../../../../Applications/快应用开发工具.app/Contents/Resources/app/extensions/hap-debugger/node_modules/@hap-toolkit/dsl-xvm/lib/loader/fragment-loader.js?index=0&type=script!./src/npm/@tarojs/components-qa/src/components/taro-page/index.ux?uxType=comp:51:48)
    at new Re (<anonymous>:1:30547)
    at <anonymous>:1:20071
    at _e (<anonymous>:1:20317)
    at new Re (<anonymous>:1:32163)
    at gt (<anonymous>:1:49570)
    at i (<anonymous>:1:53714)
    at eval (webpack-internal:///./src/pages/index/index.ux?uxType=page:16:1)
    at Object../src/pages/index/index.ux?uxType=page (pages/index/index.js:268:1)
    at __webpack_require__ (pages/index/index.js:23:30)
com.eclipsesource.v8.V8ScriptExecutionException
 at com.eclipsesource.v8.V8._executeVoidFunction(Native Method)
 at com.eclipsesource.v8.V8.executeVoidFunction(SourceFile:1154)
 at com.eclipsesource.v8.V8Object.executeVoidFunction(SourceFile:435)
 at org.hapjs.render.jsruntime.JsThread.b(SourceFile:881)
 at org.hapjs.render.jsruntime.JsThread.a(SourceFile:90)
 at org.hapjs.render.jsruntime.JsThread$a.handleMessage(SourceFile:266)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:192)
 at android.os.HandlerThread.run(HandlerThread.java:65)
```

### 复现步骤

1. 将 cli 升级到 2.2.5 后，执行 taro init，其选项设置为：

    <img width="339" alt="屏幕快照 2020-05-19 上午9 13 27" src="https://user-images.githubusercontent.com/1390888/82273822-16436c80-99b1-11ea-811d-ad82e5c4a7a5.png">

2. 执行 yarn dev:quickapp，用真机调试即报以上错误。

### 期望行为

希望能够在快应用下正常运行。

### 报错信息

如上所述。

### 系统信息

```
👽 Taro v2.2.5


  Taro CLI 2.2.5 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.19.1 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
    npmPackages:
      @tarojs/components: 2.2.5 => 2.2.5
      @tarojs/components-qa: 2.2.5 => 2.2.5
      @tarojs/mini-runner: 2.2.5 => 2.2.5
      @tarojs/router: 2.2.5 => 2.2.5
      @tarojs/taro: 2.2.5 => 2.2.5
      @tarojs/taro-alipay: 2.2.5 => 2.2.5
      @tarojs/taro-h5: 2.2.5 => 2.2.5
      @tarojs/taro-qq: 2.2.5 => 2.2.5
      @tarojs/taro-quickapp: 2.2.5 => 2.2.5
      @tarojs/taro-rn: 2.2.5 => 2.2.5
      @tarojs/taro-swan: 2.2.5 => 2.2.5
      @tarojs/taro-tt: 2.2.5 => 2.2.5
      @tarojs/taro-weapp: 2.2.5 => 2.2.5
      @tarojs/webpack-runner: 2.2.5 => 2.2.5
      eslint-config-taro: 2.2.5 => 2.2.5
      eslint-plugin-taro: 2.2.5 => 2.2.5
      nerv-devtools: ^1.5.5 => 1.5.6
      nervjs: ^1.5.5 => 1.5.6
      stylelint-config-taro-rn: 2.2.5 => 2.2.5
      stylelint-taro-rn: 2.2.5 => 2.2.5
```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by zhiqingchen** [comment]
升级到2.2.7
https://github.com/NervJS/taro/commit/15f40f019e745e4fb8e173c2615fe035b4f85a84

**Comment by nanjingboy** [comment]
@zhiqingchen 又来了这个问题：

```
webpack-internal:///../node_modules/@tarojs/taro/dist/index.esm.js:2365: ReferenceError: process is not defined
ReferenceError: process is not defined
    at eval (webpack-internal:///../node_modules/@tarojs/taro/dist/index.esm.js:2365:1)
    at Object.../node_modules/@tarojs/taro/dist/index.esm.js (pages/index/index.js:124:1)
    at __webpack_require__ (pages/index/index.js:23:30)
    at eval (webpack-internal:///../node_modules/@tarojs/taro-quickapp/dist/index.js:11:12)
    at Object.../node_modules/@tarojs/taro-quickapp/dist/index.js (pages/index/index.js:100:1)
    at __webpack_require__ (pages/index/index.js:23:30)
    at eval (webpack-internal:///../node_modules/@tarojs/taro-quickapp/index.js:3:18)
    at Object.../node_modules/@tarojs/taro-quickapp/index.js (pages/index/index.js:112:1)
    at __webpack_require__ (pages/index/index.js:23:30)
    at __scriptModule__ (webpack-internal:///./node_modules/@hap-toolkit/dsl-xvm/lib/loaders/script-loader.js!./node_modules/@hap-toolkit/dsl-xvm/lib/loaders/module-loader.js!./node_modules/babel-loader/lib/index.js?cwd=/Users/Tom/workspace/taro-demo/dist&cacheDirectory&plugins[]=/Users/Tom/workspace/taro-demo/dist/node_modules/@hap-toolkit/dsl-xvm/lib/loaders/babel-plugin-jsx.js&comments=false!./node_modules/@hap-toolkit/dsl-xvm/lib/loaders/fragment-loader.js?index=0&type=script!./src/npm/@tarojs/components-qa/src/components/taro-page/index.ux?uxType=comp:8:44)
com.eclipsesource.v8.V8ScriptExecutionException
 at com.eclipsesource.v8.V8._executeVoidFunction(Native Method)
 at com.eclipsesource.v8.V8.executeVoidFunction(SourceFile:1154)
 at com.eclipsesource.v8.V8Object.executeVoidFunction(SourceFile:435)
 at org.hapjs.render.jsruntime.JsThread.b(SourceFile:881)
 at org.hapjs.render.jsruntime.JsThread.a(SourceFile:90)
 at org.hapjs.render.jsruntime.JsThread$a.handleMessage(SourceFile:266)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:192)
 at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by zhiqingchen** [comment]
这个是另外的问题，还没深入研究，把dist下的package.json 改下，重新install一下
@nanjingboy 

```js
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.4.0",
    "@babel/plugin-proposal-decorators": "^7.4.0",
    "hap-toolkit": "0.7.0"
  },
```

**Comment by zhiqingchen** [comment]
这个坑挺深的
hap-toolkit 这几天有更新，dist里配的latest，更新后打包就异常了😓

**Comment by zhiqingchen** [comment]
还在查，先删下可能的误导

**Comment by jiongrui** [comment]
> @zhiqingchen 又来了这个问题：
> 
> ```
> webpack-internal:///../node_modules/@tarojs/taro/dist/index.esm.js:2365: ReferenceError: process is not defined
> ReferenceError: process is not defined
>     at eval (webpack-internal:///../node_modules/@tarojs/taro/dist/index.esm.js:2365:1)
>     at Object.../node_modules/@tarojs/taro/dist/index.esm.js (pages/index/index.js:124:1)
>     at __webpack_require__ (pages/index/index.js:23:30)
>     at eval (webpack-internal:///../node_modules/@tarojs/taro-quickapp/dist/index.js:11:12)
>     at Object.../node_modules/@tarojs/taro-quickapp/dist/index.js (pages/index/index.js:100:1)
>     at __webpack_require__ (pages/index/index.js:23:30)
>     at eval (webpack-internal:///../node_modules/@tarojs/taro-quickapp/index.js:3:18)
>     at Object.../node_modules/@tarojs/taro-quickapp/index.js (pages/index/index.js:112:1)
>     at __webpack_require__ (pages/index/index.js:23:30)
>     at __scriptModule__ (webpack-internal:///./node_modules/@hap-toolkit/dsl-xvm/lib/loaders/script-loader.js!./node_modules/@hap-toolkit/dsl-xvm/lib/loaders/module-loader.js!./node_modules/babel-loader/lib/index.js?cwd=/Users/Tom/workspace/taro-demo/dist&cacheDirectory&plugins[]=/Users/Tom/workspace/taro-demo/dist/node_modules/@hap-toolkit/dsl-xvm/lib/loaders/babel-plugin-jsx.js&comments=false!./node_modules/@hap-toolkit/dsl-xvm/lib/loaders/fragment-loader.js?index=0&type=script!./src/npm/@tarojs/components-qa/src/components/taro-page/index.ux?uxType=comp:8:44)
> com.eclipsesource.v8.V8ScriptExecutionException
>  at com.eclipsesource.v8.V8._executeVoidFunction(Native Method)
>  at com.eclipsesource.v8.V8.executeVoidFunction(SourceFile:1154)
>  at com.eclipsesource.v8.V8Object.executeVoidFunction(SourceFile:435)
>  at org.hapjs.render.jsruntime.JsThread.b(SourceFile:881)
>  at org.hapjs.render.jsruntime.JsThread.a(SourceFile:90)
>  at org.hapjs.render.jsruntime.JsThread$a.handleMessage(SourceFile:266)
>  at android.os.Handler.dispatchMessage(Handler.java:106)
>  at android.os.Looper.loop(Looper.java:192)
>  at android.os.HandlerThread.run(HandlerThread.java:65)
> ```


解决了吗，我也遇到了

**Comment by wayung** [comment]
> > @zhiqingchen 又来了这个问题：
> > ```
> > webpack-internal:///../node_modules/@tarojs/taro/dist/index.esm.js:2365: ReferenceError: process is not defined
> > ReferenceError: process is not defined
> >     at eval (webpack-internal:///../node_modules/@tarojs/taro/dist/index.esm.js:2365:1)
> >     at Object.../node_modules/@tarojs/taro/dist/index.esm.js (pages/index/index.js:124:1)
> >     at __webpack_require__ (pages/index/index.js:23:30)
> >     at eval (webpack-internal:///../node_modules/@tarojs/taro-quickapp/dist/index.js:11:12)
> >     at Object.../node_modules/@tarojs/taro-quickapp/dist/index.js (pages/index/index.js:100:1)
> >     at __webpack_require__ (pages/index/index.js:23:30)
> >     at eval (webpack-internal:///../node_modules/@tarojs/taro-quickapp/index.js:3:18)
> >     at Object.../node_modules/@tarojs/taro-quickapp/index.js (pages/index/index.js:112:1)
> >     at __webpack_require__ (pages/index/index.js:23:30)
> >     at __scriptModule__ (webpack-internal:///./node_modules/@hap-toolkit/dsl-xvm/lib/loaders/script-loader.js!./node_modules/@hap-toolkit/dsl-xvm/lib/loaders/module-loader.js!./node_modules/babel-loader/lib/index.js?cwd=/Users/Tom/workspace/taro-demo/dist&cacheDirectory&plugins[]=/Users/Tom/workspace/taro-demo/dist/node_modules/@hap-toolkit/dsl-xvm/lib/loaders/babel-plugin-jsx.js&comments=false!./node_modules/@hap-toolkit/dsl-xvm/lib/loaders/fragment-loader.js?index=0&type=script!./src/npm/@tarojs/components-qa/src/components/taro-page/index.ux?uxType=comp:8:44)
> > com.eclipsesource.v8.V8ScriptExecutionException
> >  at com.eclipsesource.v8.V8._executeVoidFunction(Native Method)
> >  at com.eclipsesource.v8.V8.executeVoidFunction(SourceFile:1154)
> >  at com.eclipsesource.v8.V8Object.executeVoidFunction(SourceFile:435)
> >  at org.hapjs.render.jsruntime.JsThread.b(SourceFile:881)
> >  at org.hapjs.render.jsruntime.JsThread.a(SourceFile:90)
> >  at org.hapjs.render.jsruntime.JsThread$a.handleMessage(SourceFile:266)
> >  at android.os.Handler.dispatchMessage(Handler.java:106)
> >  at android.os.Looper.loop(Looper.java:192)
> >  at android.os.HandlerThread.run(HandlerThread.java:65)
> > ```
> 
> 解决了吗，我也遇到了

我也遇到这个问题了，解决了吗？

**Comment by GitHub-WF** [comment]
> > > @zhiqingchen 又来了这个问题：
> > > ```
> > > webpack-internal:///../node_modules/@tarojs/taro/dist/index.esm.js:2365: ReferenceError: process is not defined
> > > ReferenceError: process is not defined
> > >     at eval (webpack-internal:///../node_modules/@tarojs/taro/dist/index.esm.js:2365:1)
> > >     at Object.../node_modules/@tarojs/taro/dist/index.esm.js (pages/index/index.js:124:1)
> > >     at __webpack_require__ (pages/index/index.js:23:30)
> > >     at eval (webpack-internal:///../node_modules/@tarojs/taro-quickapp/dist/index.js:11:12)
> > >     at Object.../node_modules/@tarojs/taro-quickapp/dist/index.js (pages/index/index.js:100:1)
> > >     at __webpack_require__ (pages/index/index.js:23:30)
> > >     at eval (webpack-internal:///../node_modules/@tarojs/taro-quickapp/index.js:3:18)
> > >     at Object.../node_modules/@tarojs/taro-quickapp/index.js (pages/index/index.js:112:1)
> > >     at __webpack_require__ (pages/index/index.js:23:30)
> > >     at __scriptModule__ (webpack-internal:///./node_modules/@hap-toolkit/dsl-xvm/lib/loaders/script-loader.js!./node_modules/@hap-toolkit/dsl-xvm/lib/loaders/module-loader.js!./node_modules/babel-loader/lib/index.js?cwd=/Users/Tom/workspace/taro-demo/dist&cacheDirectory&plugins[]=/Users/Tom/workspace/taro-demo/dist/node_modules/@hap-toolkit/dsl-xvm/lib/loaders/babel-plugin-jsx.js&comments=false!./node_modules/@hap-toolkit/dsl-xvm/lib/loaders/fragment-loader.js?index=0&type=script!./src/npm/@tarojs/components-qa/src/components/taro-page/index.ux?uxType=comp:8:44)
> > > com.eclipsesource.v8.V8ScriptExecutionException
> > >  at com.eclipsesource.v8.V8._executeVoidFunction(Native Method)
> > >  at com.eclipsesource.v8.V8.executeVoidFunction(SourceFile:1154)
> > >  at com.eclipsesource.v8.V8Object.executeVoidFunction(SourceFile:435)
> > >  at org.hapjs.render.jsruntime.JsThread.b(SourceFile:881)
> > >  at org.hapjs.render.jsruntime.JsThread.a(SourceFile:90)
> > >  at org.hapjs.render.jsruntime.JsThread$a.handleMessage(SourceFile:266)
> > >  at android.os.Handler.dispatchMessage(Handler.java:106)
> > >  at android.os.Looper.loop(Looper.java:192)
> > >  at android.os.HandlerThread.run(HandlerThread.java:65)
> > > ```
> > 
> > 
> > 解决了吗，我也遇到了
> 
> 我也遇到这个问题了，解决了吗？

解决了吗？

**Comment by a526672351** [comment]
`[ERROR] Module build failed (from ./node_modules/@hap-toolkit/dsl-xvm/lib/loaders/style-loader.js):
Error: ENOENT: no such file or directory, open 'E:\wgPlatform\miniapp_taro\dist\src\npm\_@tarojs_components-qa@2.2.16@@tarojs\components-qa\src\common\css\common.css'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at E:\wgPlatform\miniapp_taro\dist\node_modules\@hap-toolkit\compiler\lib\style\process.js:1:1524
    at Array.forEach (<anonymous>)
    at processImport (E:\wgPlatform\miniapp_taro\dist\node_modules\@hap-toolkit\compiler\lib\style\process.js:1:1400)
    at Object.parse (E:\wgPlatform\miniapp_taro\dist\node_modules\@hap-toolkit\compiler\lib\style\index.js:1:597)
    at parseStyle (E:\wgPlatform\miniapp_taro\dist\node_modules\@hap-toolkit\compiler\lib\index.js:1:1902)
    at Object.module.exports (E:\wgPlatform\miniapp_taro\dist\node_modules\@hap-toolkit\dsl-xvm\lib\loaders\style-loader.js:1:682)`

**Comment by shenmissing** [comment]
解决了吗 哪个版本可以？

**Comment by fortune1992** [comment]
手动在项目根目录//node_modules/@tarojs/taro/dist/index.esm.js添加import process from 'process'可以解决问题。

不知道各位大佬还有别的解决办法吗
