### ISSUE TITLE
Unknown plugin "transform-decorators-legacy"

### ISSUE THREAD

**Issue by wsdo** [NervJS/taro#644]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
ReferenceError: Unknown plugin "transform-decorators-legacy" specified in "base" at 1, attempted to resolve relative to "/Users/stark/item/xcx/taroinit"
    at /Users/stark/item/xcx/taroinit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/stark/item/xcx/taroinit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/stark/item/xcx/taroinit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/stark/item/xcx/taroinit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/stark/item/xcx/taroinit/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/stark/item/xcx/taroinit/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/stark/item/xcx/taroinit/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at babel (/Users/stark/item/xcx/taroinit/node_modules/@tarojs/plugin-babel/index.js:6:17)
    at Object.callPlugin (/Users/stark/.config/yarn/global/node_modules/@tarojs/cli/src/util/npm.js:110:10)
编译  所有页面
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
项目依赖没有装好，重新安装下依赖~ 
另外，你的 Taro 版本太低了哦，现在都 `1.0.0-beta.30` 了

**Comment by wsdo** [comment]
昨天刚下载的.. 就这么低了吗，一直运行着，重启了一下，就出现这个问题了。

**Comment by luckyadam** [comment]
刚刚发布了 1.0.0 版本
还是依赖没有装好的问题，可以删了 node_modules 再清一下 npm 缓存然后再重装
