### ISSUE TITLE
taro cli 升级至2.2.1 后执行 taro info 报错

### ISSUE THREAD

**Issue by xuxiaoxiao312** [NervJS/taro#6508]
### 问题描述
taro cli 升级至2.2.1 后执行 taro info 报错。
### 复现步骤
taro cli 1.3.33 升级 至 2.2.1 
执行 
```
taro update self 2.2.1
taro info
```
### 报错信息
```
👽 Taro v2.2.1

(node:27751) UnhandledPromiseRejectionWarning: TypeError: items.forEach is not a function
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_service@2.2.1@@tarojs/service/dist/utils/index.js:17:15
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_service@2.2.1@@tarojs/service/dist/utils/index.js:33:51
    at Kernel.initPresetsAndPlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_service@2.2.1@@tarojs/service/dist/Kernel.js:72:107)
    at Kernel.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_service@2.2.1@@tarojs/service/dist/Kernel.js:40:18)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_service@2.2.1@@tarojs/service/dist/Kernel.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_service@2.2.1@@tarojs/service/dist/Kernel.js:4:12)
    at Kernel.init (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_service@2.2.1@@tarojs/service/dist/Kernel.js:36:16)
    at Kernel.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_service@2.2.1@@tarojs/service/dist/Kernel.js:239:24)
(node:27751) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:27751) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
报错指向代码：
![image](https://user-images.githubusercontent.com/24541297/83219198-528d7e80-a1a2-11ea-8693-defe726cc69f.png)

### 系统信息

👽 Taro v2.2.1

  Taro CLI 2.2.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.12.0 - /usr/local/bin/npm
### 补充信息
推测是由于config中的plugin配置导致的
```
  plugins: {
    babel: {
      sourceMap: true,
      presets: [
        'env'
      ],
      plugins: [
        'transform-class-properties',
        'transform-decorators-legacy',
        'transform-object-rest-spread'
      ]
    }
  },
```
去除后taro info 可以执行，但是项目还是跑不起来，请问 plugin 要怎么配置？

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/config-detail#plugins
plugins 配置已经调整了
可以升级到 2.2.6，修复了直接报错的问题
