### ISSUE TITLE
快应用真机调试问题

### ISSUE THREAD

**Issue by gitubzuky** [NervJS/taro#6610]
### 问题描述

新建helloworld项目，执行npm run dev:quickapp后，在小米9手机上运行，出现以下报错

`undefined:51: TypeError: Cannot read property '' of undefined
TypeError: Cannot read property '' of undefined
    at Re.data (eval at d:\Program Files (x86)\Quickapp\resources\app\extensions\hap-debugger\node_modules.asar\@hap-toolkit\dsl-xvm\lib\loader\script-loader.js!d:\Program Files (x86)\Quickapp\resources\app\extensions\hap-debugger\node_modules.asar\@hap-toolkit\dsl-xvm\lib\loader\module-loader.js!./node_modules/babel-loader/lib/index.js?cwd=e:\study\taro\test\myApp\dist&cacheDirectory&plugins[]=d:\Program Files (x86)\Quickapp\resources\app\extensions\hap-debugger\node_modules.asar\@hap-toolkit\dsl-xvm\lib\loader\babel-plugin-jsx.js&comments=false!d:\Program Files (x86)\Quickapp\resources\app\extensions\hap-debugger\node_modules.asar\@hap-toolkit\dsl-xvm\lib\loader\fragment-loader.js?index=0&type=script!./src/npm/@tarojs/components-qa/src/components/taro-page/index.ux?uxType=comp (pages/index/index.js:201:1), <anonymous>:51:48)
    at new Re (<anonymous>:1:30534)
    at <anonymous>:1:20071
    at _e (<anonymous>:1:20317)
    at new Re (<anonymous>:1:32150)
    at gt (<anonymous>:1:49420)
    at i (<anonymous>:1:53502)
    at eval (webpack-internal:///./src/pages/index/index.ux?uxType=page:15:1)
    at Object../src/pages/index/index.ux?uxType=page (pages/index/index.js:135:1)
    at __webpack_require__ (pages/index/index.js:23:30)
com.eclipsesource.v8.V8ScriptExecutionException
 at com.eclipsesource.v8.V8._executeVoidFunction(Native Method)
 at com.eclipsesource.v8.V8.executeVoidFunction(SourceFile:1154)
 at com.eclipsesource.v8.V8Object.executeVoidFunction(SourceFile:435)
 at org.hapjs.render.jsruntime.JsThread.b(SourceFile:797)
 at org.hapjs.render.jsruntime.JsThread.a(SourceFile:77)
 at org.hapjs.render.jsruntime.JsThread$a.handleMessage(SourceFile:253)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:214)
 at android.os.HandlerThread.run(HandlerThread.java:67)`

### 复现步骤
1. **执行 npm install -g @tarojs/cli**
2. **执行 taro init myAp**
3. **添加project.quickapp.json文件**
文件内容：
{
  "package": "com.test.myApp",
  "name": "myApp",
  "versionName": "1.0.0",
  "versionCode": 100,
  "minPlatformVersion": 1050,
  "features": [
    { "name": "system.prompt" },
    { "name": "system.router" },
    { "name": "system.shortcut" },
    { "name": "system.fetch" },
    { "name": "system.storage" },
    { "name": "system.barcode" },
    { "name": "system.vibrator" },
    { "name": "system.clipboard" },
    { "name": "system.sensor" },
    { "name": "system.geolocation" },
    { "name": "system.share" },
    { "name": "system.notification" },
    { "name": "system.device" },
    { "name": "system.webview" },
    { "name": "system.request" },
    { "name": "system.audio" },
    { "name": "system.record" },
    { "name": "system.contact" },
    { "name": "system.sms" }
  ],
  "icon": "logo.png",
  "permissions": [
    { "origin": "*" }
  ],
  "config": {
    "logLevel": "debug"
  }
}
4. **执行 npm run dev:quickapp**
5. **真机报错**
**vscode 中ps shell log如下：**
PS E:\study\taro\test\myApp> npm run dev:quickapp

\> myApp@1.0.0 dev:quickapp E:\study\taro\test\myApp
\> npm run build:quickapp -- --watch

\> myApp@1.0.0 build:quickapp E:\study\taro\test\myApp
\> taro build --type quickapp "--watch"

�👽 Taro v2.2

编译  发现入口  src/app.tsx
编译  发现页面  src/pages/index/index.tsx
✅  编译成功

监听文件修改中...

✔  快应用容器已经准备好

- 安装快应用依赖环境, 需要一会儿...npm WARN quickapp@1.0.0 No description
npm WARN quickapp@1.0.0 No repository field.
npm WARN quickapp@1.0.0 scripts['server'] should probably be scripts['start'].
npm WARN quickapp@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

√ 安装成功
up to date in 5.499s

13 packages are looking for funding
  run `npm fund` for details

[INFO] hap-toolkit: 0.7.3; babel: 7.10.2; webpack: 4.43.0;
[LOG] 当前minPlatformVersion >= 1040，平台采用v8版本为6.5+（对应chrome版本为65版+），工具将不再对V8 6.5版本支持的ES6代码进行转换
[INFO] 配置环境：{"NODE_PLATFORM":"native","NODE_PHASE":"dev"}
[INFO] 获取到app文件后缀: ux
[INFO] ### App Server ### 完成创建adb调试器。您可以通过usb线连入手机调试
[INFO] ### App Server ### 服务器地址: http://localhost:12306, http://192.168.4.193:12306
[INFO] ### App Server ### 请确保手机与App Server处于相同网段

生成HTTP服务器的二维码: http://192.168.4.193:12306
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▄▄▄ ▀ ▀█▄█ ▄▄▄▄▄ █
█ █   █ ██▄▀ █  ▀▀█ █   █ █
█ █▄▄▄█ ██▀▄ ▄▄██▀█ █▄▄▄█ █
█▄▄▄▄▄▄▄█ ▀▄█ ▀▄█ █▄▄▄▄▄▄▄█
█  █ ▄█▄▀▀▄▀█▄██ ▀▀▄█▀▀▀▀▄█
█▀▀█ ██▄█ ▄██▄▄  █ ▄▄  ▀▀ █
█  █▀█▀▄▀▀▄ █ █▄▀▄▄▄▀▀██▀▄█
█ ▄█▄ ▄▄▀▀  ▀▄█▀▄ ▄██▀▄ ▄ █
█▄█▄▄▄█▄▄▀ █▄▀▄ ▀ ▄▄▄ █▄ ██
█ ▄▄▄▄▄ ██▄█▄  ▄█ █▄█ ▄██▄█
█ █   █ █ ▄▀▀▀██▄▄▄  ▄ █▀▀█
█ █▄▄▄█ █▀ ▄▄▀▄▄▀█▀▀▀ █   █
█▄▄▄▄▄▄▄█▄█▄▄██▄▄▄█▄██▄██▄█

[INFO] ### App Server ### 手机设备(463c50a8)被连入
[WARN] 标签slot的属性 `name` 值为空, 默认设置为缺省值 `default` E:\study\taro\test\myApp\dist\src\npm\@tarojs\components-qa\src\components\taro-page\index.ux@6,13
[WARN] 标签slot的属性 `name` 值为空, 默认设置为缺省值 `default` E:\study\taro\test\myApp\dist\src\npm\@tarojs\components-qa\src\components\taro-page\index.ux@15,15
[WARN] 标签slot的属性 `name` 值为空, 默认设置为缺省值 `default` E:\study\taro\test\myApp\dist\src\npm\@tarojs\components-qa\src\components\taro-page\index.ux@20,11
[INFO] Build Time Cost: 2.372s
[LOG] ### App Loader ### 项目构建启用了debug签名
[LOG] ### App Loader ### 项目构建并生成文件：com.test.myApp.debug.rpk
[LOG] ### App Loader ### 通知手机更新rpk文件
[LOG] ### App Server ### 通知手机更新rpk文件成功: http://192.168.113.143:39517/update 

```
手机中的报错在问题描述中
```

### 期望行为

项目在真机中正确运行

### 报错信息

undefined:51: TypeError: Cannot read property '' of undefined
TypeError: Cannot read property '' of undefined
    at Re.data (eval at d:\Program Files (x86)\Quickapp\resources\app\extensions\hap-debugger\node_modules.asar\@hap-toolkit\dsl-xvm\lib\loader\script-loader.js!d:\Program Files (x86)\Quickapp\resources\app\extensions\hap-debugger\node_modules.asar\@hap-toolkit\dsl-xvm\lib\loader\module-loader.js!./node_modules/babel-loader/lib/index.js?cwd=e:\study\taro\test\myApp\dist&cacheDirectory&plugins[]=d:\Program Files (x86)\Quickapp\resources\app\extensions\hap-debugger\node_modules.asar\@hap-toolkit\dsl-xvm\lib\loader\babel-plugin-jsx.js&comments=false!d:\Program Files (x86)\Quickapp\resources\app\extensions\hap-debugger\node_modules.asar\@hap-toolkit\dsl-xvm\lib\loader\fragment-loader.js?index=0&type=script!./src/npm/@tarojs/components-qa/src/components/taro-page/index.ux?uxType=comp (pages/index/index.js:201:1), <anonymous>:51:48)
    at new Re (<anonymous>:1:30534)
    at <anonymous>:1:20071
    at _e (<anonymous>:1:20317)
    at new Re (<anonymous>:1:32150)
    at gt (<anonymous>:1:49420)
    at i (<anonymous>:1:53502)
    at eval (webpack-internal:///./src/pages/index/index.ux?uxType=page:15:1)
    at Object../src/pages/index/index.ux?uxType=page (pages/index/index.js:135:1)
    at __webpack_require__ (pages/index/index.js:23:30)
com.eclipsesource.v8.V8ScriptExecutionException
 at com.eclipsesource.v8.V8._executeVoidFunction(Native Method)
 at com.eclipsesource.v8.V8.executeVoidFunction(SourceFile:1154)
 at com.eclipsesource.v8.V8Object.executeVoidFunction(SourceFile:435)
 at org.hapjs.render.jsruntime.JsThread.b(SourceFile:797)
 at org.hapjs.render.jsruntime.JsThread.a(SourceFile:77)
 at org.hapjs.render.jsruntime.JsThread$a.handleMessage(SourceFile:253)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:214)
 at android.os.HandlerThread.run(HandlerThread.java:67)

### 系统信息

👽 Taro v2.2.6

  Taro CLI 2.2.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.3 - D:\Program Files\nodejs\node.EXE
      npm: 6.13.4 - D:\Program Files\nodejs\npm.CMD

### 补充信息

项目dist目录在快应用官方ide中运行没有报错，预览可以正常预览
![image](https://user-images.githubusercontent.com/10329144/84104697-d66c2400-aa48-11ea-9ded-68a27ac64e82.png)
备注：console中的报错可以无视，与项目无关，是未连接手机时的一个报错而已

**Comment by zhiqingchen** [comment]
升级到2.2.7
https://github.com/NervJS/taro/commit/15f40f019e745e4fb8e173c2615fe035b4f85a84
