### ISSUE TITLE
[Taro3 rc4] 在 config/index.ts 中特殊写法会引起 ERR_REQUIRE_ESM 异常

### ISSUE THREAD

**Issue by cncolder** [NervJS/taro#6635]
### 问题描述

最近更新的版本里 config/index.ts 允许使用 typescript 了, 应该是使用 babel-preset-typescript 转换的文件, 特殊写法会引起 ERR_REQUIRE_ESM 异常, 这个异常太有迷惑性了, 让我以为不支持 typescript 文件类型.

### 复现步骤

1. 使用 config/index.ts 配置项目
2. 插入如下代码

```js
// 可以触发这个异常的最短代码
console.log(...[].map)
```

### 报错信息

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:
	~/demo/node_modules/@babel/runtime/helpers/esm/toConsumableArray.js
	require() of ES modules is not supported.

require() of ~/demo/node_modules/@babel/runtime/helpers/esm/toConsumableArray.js
	from ~/demo/config/index.ts is an ES module file as it is a .js file
	whose nearest parent package.json contains "type": "module"
	which defines all .js files in that package scope as ES modules.

Instead rename toConsumableArray.js to end in .cjs,
	change the requiring code to use import(),
	or remove "type": "module" from
	~/demo/node_modules/@babel/runtime/helpers/esm/package.json.
```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by AdonLee** [comment]
3.6.20也会出现类似的问题
针对微信小程序增加一个alias, 就会报Cannot use import statement outside a module
```javascript

  if (getEnv() === ENV_TYPE.WEAPP) {
    baseConfig.alias = baseConfig.alias = {}
    baseConfig.alias['date-fns/locale$'] = path.resolve(
      __dirname,
      './date-fns-locale.weapp.js'
    );
  }
```
```bash
.../node_modules/@tarojs/runtime/dist/runtime.esm.js:1
import { noop, isFunction, getComponentsAlias as getComponentsAlias$1, internalComponents, isWebPlatform, EMPTY_OBJ, hooks, toCamelCase, isObject, warn, isArray, ensure, isNull, isUndefined, toDashed, isString, controlledComponent, Events, isNumber } from '@tarojs/shared';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1124:15)
    at Module._compile (node:internal/modules/cjs/loader:1160:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Object.newLoader [as .js] (/Users/..../node_modules/pirates/lib/index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/Users/.../node_modules/@tarojs/taro/index.js:1:19)
找不到项目配置文件config/index，请确定当前目录是 Taro 项目根目录!
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ZakaryCode** [comment]
> 最近更新的版本里 config/index.ts 允许使用 typescript 了, 应该是使用 babel-preset-typescript 转换的文件, 特殊写法会引起 ERR_REQUIRE_ESM 异常, 这个异常太有迷惑性了, 让我以为不支持 typescript 文件类型.

最新版本内使用的是 esbuild 来做解析，但是所述的代码本身就会有问题（TS2488），补全后无类似问题

```ts
console.log(...[].map(() => {}))
```

**Comment by ZakaryCode** [comment]
> 3.6.20也会出现类似的问题 针对微信小程序增加一个alias, 就会报Cannot use import statement outside a module

此处所说与 issue 并非同一个问题，而是由于代码本身解析的依赖错误导致，应当在 `date-fns-locale.weapp.js` 使用了 `@tarojs/runtime` 但错误使用了 esm 模块，可以自行将引用改为 `@tarojs/runtime/dist/index.cjs`，如依旧存在问题请在新的 issue 内提交并附上完整示例。
