### ISSUE TITLE
新建项目选默认模板报错

### ISSUE THREAD

**Issue by believeZJP** [NervJS/taro#6678]
Taro 即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

✔ 拉取远程模板仓库成功！
? 请输入项目介绍！ d
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Less
? 请选择模板 默认模板
SyntaxError: Missing catch or finally after try in /Users/aa/.config/yarn/global/node_modules/@tarojs/cli/templates/default/pkg while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/Users/aa/.config/yarn/global/node_modules/ejs/lib/ejs.js:652:12)
    at Object.compile (/Users/aa/.config/yarn/global/node_modules/ejs/lib/ejs.js:392:16)
    at handleCache (/Users/aa/.config/yarn/global/node_modules/ejs/lib/ejs.js:215:18)
    at Object.exports.render (/Users/aa/.config/yarn/global/node_modules/ejs/lib/ejs.js:419:10)
    at render (/Users/aa/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:14:18)
    at process (/Users/aa/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:31:14)
    at applyProcessingFunc (/Users/aa/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy.js:14:16)
    at EditionInterface.exports._copySingle (/Users/aa/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy.js:64:16)
    at /Users/aa/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy.js:51:10

**Comment by luckyadam** [comment]
43cf194c1d6a9e0cdab7c2b5431d5c6f4120d186
已修复，暂时可以先用其他模板~

**Comment by sn01615** [comment]
```
× 安装项目依赖失败，请自行重新安装！
Error: Command failed: npm install
npm ERR! code EJSONPARSE
npm ERR! file D:\xxxxxx\package.json
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected token } in JSON at position 662 while parsing near '...d:qq -- --watch",
npm ERR! JSON.parse   },
npm ERR! JSON.parse   "author": "",
npm ERR! JSON.parse  ...'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.
```

**Comment by sn01615** [comment]
![{F9165FA8-92F0-42A0-A90C-A5F99E733862}_20200615221149](https://user-images.githubusercontent.com/7794149/84667685-44d34980-af55-11ea-8c49-47c6f1c82f44.jpg)

**Comment by luckyadam** [comment]
自行安装项目依赖就行

**Comment by luckyadam** [comment]
已修复
