### ISSUE TITLE
初始化项目出错 

### ISSUE THREAD

**Issue by Cabzer-x** [NervJS/taro#6685]
PS D:\gitDxy> taro init demo-app
� Taro v2.2.8

Taro 即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

√ 拉取远程模板仓库成功！
? 请输入项目介绍！ demo-app
? 是否需要使用 TypeScript ？ No
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板 默认模板
SyntaxError: Missing catch or finally after try in C:\Users\Admin\AppData\Roaming\npm\node_modules\@tarojs\cli\templates\default\pkg while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (C:\Users\Admin\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_ejs@2.7.4@ejs\lib\ejs.js:652:12)
    at Object.compile (C:\Users\Admin\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_ejs@2.7.4@ejs\lib\ejs.js:392:16)
    at handleCache (C:\Users\Admin\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_ejs@2.7.4@ejs\lib\ejs.js:215:18)
    at Object.exports.render (C:\Users\Admin\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_ejs@2.7.4@ejs\lib\ejs.js:419:10)
    at render (C:\Users\Admin\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_mem-fs-editor@4.0.3@mem-fs-editor\lib\actions\copy-tpl.js:14:18)
    at process (C:\Users\Admin\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_mem-fs-editor@4.0.3@mem-fs-editor\lib\actions\copy-tpl.js:31:14)
    at applyProcessingFunc (C:\Users\Admin\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_mem-fs-editor@4.0.3@mem-fs-editor\lib\actions\copy.js:14:16)
    at EditionInterface.exports._copySingle (C:\Users\Admin\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_mem-fs-editor@4.0.3@mem-fs-editor\lib\actions\copy.js:64:16)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_mem-fs-editor@4.0.3@mem-fs-editor\lib\actions\copy.js:51:10

**Comment by dreamerDH** [comment]
我也遇到了 这个问题 之前第一次初始init时 是好使的 但是css预处理器选错了 就删掉了项目，再重新init就一直报这个错了

**Comment by yuy1guo** [comment]
我也遇到了

**Comment by dreamerDH** [comment]
试了一下 模板不要使用默认模板 现在有点问题，选择redux模板就可以

**Comment by yuy1guo** [comment]
模板不适用默认是没问题 但是h5模式下预览又出问题了

**Comment by luckyadam** [comment]
> 模板不适用默认是没问题 但是h5模式下预览又出问题了

H5 有啥问题

**Comment by zhiqingchen** [comment]
https://github.com/NervJS/taro/commit/43cf194c1d6a9e0cdab7c2b5431d5c6f4120d186

老李已修复了
