### ISSUE TITLE
Taro v2.2.1 初始化出现问题

### ISSUE THREAD

**Issue by joshuaxing** [NervJS/taro#6690]
### 问题描述

taro init myApp 初始化报错

### 复现步骤

中断 taro init myApp ,
又进行了 taro init myApp

### 期望行为

初始化成功

### 报错信息

(node:11032) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at normalizePath (C:\Users\yuanzhou\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\dist\utils.js:25:37)
    at recursiveFindNodeModules (C:\Users\yuanzhou\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\dist\utils.js:120:9)
    at recursiveFindNodeModules (C:\Users\yuanzhou\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\dist\utils.js:133:12)
    at recursiveFindNodeModules (C:\Users\yuanzhou\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\dist\utils.js:133:12)
    at recursiveFindNodeModules (C:\Users\yuanzhou\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\dist\utils.js:133:12)
    at recursiveFindNodeModules (C:\Users\yuanzhou\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\dist\utils.js:133:12)
    at recursiveFindNodeModules (C:\Users\yuanzhou\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\dist\utils.js:133:12)
    at recursiveFindNodeModules (C:\Users\yuanzhou\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\dist\utils.js:133:12)
    at recursiveFindNodeModules (C:\Users\yuanzhou\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\dist\utils.js:133:12)
(node:11032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:11032) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### 系统信息
 Taro v2.2.1
 Node v10.16.3
 NPM 6.9.0

**Comment by luckyadam** [comment]
重新装一下依赖
然后建议用 2.2.8 版本
