### ISSUE TITLE
安装报错!

### ISSUE THREAD

**Issue by cikichen** [NervJS/taro#67]
```
npm install -g @tarojs/cli                                                           INT(-2) ↵  3045  14:25:02
events.js:165░░░░░░⸩ ⠸ extract:css-mediaquery: sill extract isobject@3.0.1
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:241:12)
    at PassThrough.Writable.write (_stream_writable.js:291:5)
    at PassThrough.Writable.end (_stream_writable.js:576:10)
```

**Comment by Littly** [comment]
尝试用taobao源，或者爬个木弟子
