### ISSUE TITLE
Taro v3.0.0-rc.4  cli配合cross-env，打包出来页面报错

### ISSUE THREAD

**Issue by 99414041** [NervJS/taro#6723]
### 问题描述
使用了cross-env进行区分dev和test环境，打包出来页面报错

### 复现步骤
1. package.json 添加命令 
"test:weapp": "cross-env NODE_ENV=test npm run build:weapp -- --watch",
2. 编译通过
但是会报一个
正在编译...[BABEL] Note: The code generator has deoptimised the styling of /Users/houyuguang/hbc/f2e/hbc-taro-mini/node_modules/react-reconciler/cjs/react-reconciler.development.js as it exceeds the max of 500KB.
3. 页面报错
找不到test

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为
页面正常

### 报错信息
VM715:1 thirdScriptError
test is not defined
ReferenceError: test is not defined
    at warn (http://127.0.0.1:30599/appservice/taro.js:1418:3)
    at new TaroElement (http://127.0.0.1:30599/appservice/taro.js:3371:5)
    at new TaroDocument (http://127.0.0.1:30599/appservice/taro.js:3718:5)
    at createDocument (http://127.0.0.1:30599/appservice/taro.js:3756:15)
    at Object.<anonymous> (http://127.0.0.1:30599/appservice/taro.js:3769:38)
    at Object../node_modules/@tarojs/runtime/dist/runtime.esm.js (http://127.0.0.1:30599/appservice/taro.js:4696:30)
    at __webpack_require__ (http://127.0.0.1:30599/appservice/runtime.js:81:30)
    at Module../src/app.jsx (http://127.0.0.1:30599/appservice/app.js:16231:73)
    at __webpack_require__ (http://127.0.0.1:30599/appservice/runtime.js:81:30)
    at checkDeferredModules (http://127.0.0.1:30599/appservice/runtime.js:47:23)

### 系统信息
Taro CLI 3.0.0-rc.4 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-rc.4 => 3.0.0-rc.4 
      @tarojs/mini-runner: 3.0.0-rc.4 => 3.0.0-rc.4 
      @tarojs/react: 3.0.0-rc.4 => 3.0.0-rc.4 
      @tarojs/runtime: 3.0.0-rc.4 => 3.0.0-rc.4 
      @tarojs/taro: 3.0.0-rc.4 => 3.0.0-rc.4 
      @tarojs/webpack-runner: 3.0.0-rc.4 => 3.0.0-rc.4 
      babel-preset-taro: 3.0.0-rc.4 => 3.0.0-rc.4 
      eslint-config-taro: 3.0.0-rc.4 => 3.0.0-rc.4 
      react: ^16.10.0 => 16.13.1 
      taro-ui: ^2.3.4 => 2.3.4

### 补充信息
可能是react-reconciler 引起的问题

**Comment by ksbaozi** [comment]
请问解决了吗？
