### ISSUE TITLE
项目taro版本1.3.9升级到2.2.9报Cannot read property 'sassLoaderOption' of undefined

### ISSUE THREAD

**Issue by BigKarel** [NervJS/taro#6729]
### 问题描述

0.原项目taro版本1.3.9，本地taro 2.2.9，升级原项目taro版本到1.3.9 编译出现问题

### 复现步骤

1.升级项目taro版本和本地2.2.9一致
2.config增加
plugins: [
    '@tarojs/plugin-sass'
  ]，
3.npm install 拉取依赖
4.npm run dev:weapp 编译
5.遇到异常
(node:52404) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sassLoaderOption' of undefined

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 报错信息

生成  工具配置  /Users/.../xxx-miniprogram/dist/project.config.json
(node:52404) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sassLoaderOption' of undefined
    at /Users/.../xxx-miniprogram/node_modules/@tarojs/plugin-sass/dist/index.js:33:50
    at Generator.next (<anonymous>)
    at /Users/.../xxx-miniprogram/node_modules/@tarojs/plugin-sass/dist/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/.../xxx-miniprogram/node_modules/@tarojs/plugin-sass/dist/index.js:4:12)
    at Object.fn (/Users/.../xxx-miniprogram/node_modules/@tarojs/plugin-sass/dist/index.js:14:43)
    at Kernel.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/Kernel.js:199:48)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/Kernel.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/Kernel.js:4:12)
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/Kernel.js:198:33
    at eval (eval at create (/usr/local/lib/node_modules/@tarojs/cli/node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:14:17)
    at new Promise (<anonymous>)
    at AsyncSeriesWaterfallHook.eval [as promise] (eval at create (/usr/local/lib/node_modules/@tarojs/cli/node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:2:8)
    at AsyncSeriesWaterfallHook.lazyCompileHook (/usr/local/lib/node_modules/@tarojs/cli/node_modules/tapable/lib/Hook.js:154:20)
(node:52404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:52404) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/migrate-to-2
看下迁移指南

**Comment by BigKarel** [comment]
解决了，多谢

**Comment by d393911462** [comment]
怎么解决的，我2.2.7 升级 2.2.9 就出了问题

**Comment by lancerfox** [comment]
> 怎么解决的，我2.2.7 升级 2.2.9 就出了问题
https://github.com/NervJS/taro/issues/6750

**Comment by JL-Code** [comment]
> https://nervjs.github.io/taro/docs/migrate-to-2
> 看下迁移指南
链接失效了
