### ISSUE TITLE
项目初始化并依赖安装完成后，启动项目失败 UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by sdchuang** [NervJS/taro#6738]
### 问题描述
项目初始化并依赖安装完成后，启动项目失败
npm run dev:xxx  命令都会报错
node v=8.11

### 复现步骤

1. 安装cli工具
2. taro init 初始化项目
3. npm run dev:xxx 任意一端 启动项目
4. 报错  项目启动失败

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 报错信息
npm run dev:tt

> taroApp@1.0.0 dev:tt E:\program\taroApp
> npm run build:tt -- --watch

> taroApp@1.0.0 build:tt E:\program\taroApp
> taro build --type tt "--watch"

👽 Taro v2.2.9

(node:11664) UnhandledPromiseRejectionWarning: E:\program\taroApp\node_modules\_jest-worker@26.0.0@jest-worker\build\WorkerPool.js:25
  } catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._compile (C:\Users\sdc\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_pirates@4.0.1@pirates\lib\index.js:99:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (C:\Users\sdc\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_pirates@4.0.1@pirates\lib\index.js:104:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\program\taroApp\node_modules\_jest-worker@26.0.0@jest-worker\build\index.js:18:42)
    at Module._compile (module.js:652:30)
    at Module._compile (C:\Users\sdc\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_pirates@4.0.1@pirates\lib\index.js:99:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (C:\Users\sdc\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_pirates@4.0.1@pirates\lib\index.js:104:7)
(node:11664) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:11664) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### 系统信息

taro info
👽 Taro v2.2.9

  Taro CLI 2.2.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 8.11.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\sdc\AppData\Roaming\npm\yarn.CMD
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
### 补充信息

会不会是因为node或者项目版本等问题引起的异步编程的语法错误

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by HMY314** [comment]
遇到同样问题

**Comment by yanguoyu** [comment]
同样的问题，看来一下好像是 node_modules/jest-worker/build/WorkerPool.js 这个里面的代码对于不同的 node 版本有点兼容性问题。
我测试了一下，好像 node v8.12.0 的 try catch 里面的catch必须要后面那个参数，我把node切换到10.10.0不会有这个问题。
如果你的 node 版本在 8.12.0 以下，可以尝试像下面手动修改一下。
原本是这样的
`const canUseWorkerThreads = () => {
  try {
    require('worker_threads');

    return true;
  } catch {
    return false;
  }
};`
手动改成下面测试ok
`const canUseWorkerThreads = () => {
  try {
    require('worker_threads');

    return true;
  } catch(e) {
    return false;
  }
};`

**Comment by sept08** [comment]
遇到同样的问题，确实是`node`版本的问题，用`nvm`将`node`切到8.12.0以上版本就可以了

**Comment by xren0085** [comment]
实测升级node版本有效
