### ISSUE TITLE
[bug]: taro的配置项outputRoot不能够正确使用

### ISSUE THREAD

**Issue by jeasonnow** [NervJS/taro#674]
**问题描述**
在taro项目中配置了outputRoot之后，进行weapp编译，不能够正确执行。

**复现步骤**
[复现问题的步骤]
1. `> taro init testOutputRoot` 初始化一个名为testOutputRoot的taro项目
2. 修改`config/index.js`中的outputRoot配置为`temp`
3. `> npm run dev:weapp`
4. 编译报错

**期望行为**
testOutputRoot项目的构建目录变更为temp

**报错信息**
```js
(node:32023) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/santree/Desktop/myself_work/testOutputRoot/temp/project.config.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at buildProjectConfig (/Users/santree/.config/yarn/global/node_modules/@tarojs/cli/src/weapp.js:924:6)
    at Object.build (/Users/santree/.config/yarn/global/node_modules/@tarojs/cli/src/weapp.js:1818:3)
    at buildForWeapp (/Users/santree/.config/yarn/global/node_modules/@tarojs/cli/src/build.js:37:22)
    at build (/Users/santree/.config/yarn/global/node_modules/@tarojs/cli/src/build.js:23:7)
    at Object.<anonymous> (/Users/santree/.config/yarn/global/node_modules/@tarojs/cli/bin/taro-build:49:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
(node:32023) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32023) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**系统信息**

 - 操作系统: [e.g. macOS High Sierra 10.13.1]
 - Taro 版本 [e.g. v.1.0.2]
 - Node.js 版本 [e.g. v8.10.1]

**补充信息**
在讨论群里说这个问题的时候，有群友回复说只要新建一个`temp/`文件夹即可解决该问题，猜测问题出现在创建目录的时候没有先去创建从config文件中读取到的outputRoot，而是先去读取了outputRoot/project.config.json，此时没有创建目录并打入该文件，顾编译失败（纯属猜测

**Comment by Qiu800820** [comment]
刚发了PR才看到你也发了:joy:

**Comment by jeasonnow** [comment]
> 刚发了PR才看到你也发了😂

😂然后看了你的发现我的做法治标不治本，有点尴尬

**Comment by Qiu800820** [comment]
我也是偷懒不想写这么多js代码， 我那个PR会照成merge config 两次

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/pull/676
