### ISSUE TITLE
微信小程序转 Taro 报错 css is not defined

### ISSUE THREAD

**Issue by sn01615** [NervJS/taro#6754]
### 问题描述

```
生成  样式文件  taroConvert/src/app.scss
生成  样式文件  taroConvert/src/pages/index/index.scss
生成  样式文件  taroConvert/src/pages/page/page.scss
生成  样式文件  taroConvert/src/components/parser/parser.scss
生成  样式文件  taroConvert/src/components/parser/trees/trees.scss
生成  样式文件  taroConvert/src/pages/logs/logs.scss
(node:82308) UnhandledPromiseRejectionWarning: ReferenceError: C:\Users\xxxx\AppData\Roaming\npm\node_modules\@tarojs\cli\templates\default\config\index.js:31
    29|     ]
    30|   },
 >> 31|   plugins: [<% if (css !== 'none') {%>
    32|     '@tarojs/plugin-<%= css %>',<%}%>
    33|     '@tarojs/plugin-terser'
    34|   ],

css is not defined
    at eval (C:\Users\xxxx\AppData\Roaming\npm\node_modules\@tarojs\cli\templates\default\config\index.js:16:8)
    at index (C:\Users\xxxx\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\ejs\lib\ejs.js:682:17)
    at Object.exports.render (C:\Users\xxxx\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\ejs\lib\ejs.js:419:37)
    at render (C:\Users\xxxx\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:14:18)
    at process (C:\Users\xxxx\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:31:14)
    at applyProcessingFunc (C:\Users\xxxx\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\mem-fs-editor\lib\actions\copy.js:14:16)
    at EditionInterface.exports._copySingle (C:\Users\xxxx\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\mem-fs-editor\lib\actions\copy.js:64:16)
    at C:\Users\xxxx\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\mem-fs-editor\lib\actions\copy.js:51:10
    at Array.forEach (<anonymous>)
    at EditionInterface.exports.copy (C:\Users\xxxx\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\mem-fs-editor\lib\actions\copy.js:50:9)
(node:82308) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:82308) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PS D:\Desktop\xx>
```

### 复现步骤

1. 
原生小程序执行`taro convert`
2. 
3. 
4. 
执行到一半报错的样子

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by feng20068** [comment]
同问，mac 环境


node:55994) UnhandledPromiseRejectionWarning: ReferenceError: /usr/local/lib/node_modules/@tarojs/cli/templates/default/config/index.js:31
    29|     ]
    30|   },
 >> 31|   plugins: [<% if (css !== 'none') {%>
    32|     '@tarojs/plugin-<%= css %>',<%}%>
    33|     '@tarojs/plugin-terser'
    34|   ],

css is not defined
    at eval (/usr/local/lib/node_modules/@tarojs/cli/templates/default/config/index.js:16:8)
    at index (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_ejs@2.7.4@ejs/lib/ejs.js:682:17)
    at Object.exports.render (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_ejs@2.7.4@ejs/lib/ejs.js:419:37)
    at render (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_mem-fs-editor@4.0.3@mem-fs-editor/lib/actions/copy-tpl.js:14:18)
    at process (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_mem-fs-editor@4.0.3@mem-fs-editor/lib/actions/copy-tpl.js:31:14)
    at applyProcessingFunc (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_mem-fs-editor@4.0.3@mem-fs-editor/lib/actions/copy.js:14:16)
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_mem-fs-editor@4.0.3@mem-fs-editor/lib/actions/copy.js:64:16)
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/_mem-fs-editor@4.0.3@mem-fs-editor/lib/actions/copy.js:51:10
    at Array.forEach (<anonymous>)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_mem-fs-editor@4.0.3@mem-fs-editor/lib/actions/copy.js:50:9)
(node:55994) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:55994) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Frankeyfeng** [comment]
Same.

**Comment by ANM699** [comment]
same

**Comment by kaldr** [comment]
同样的问题

**Comment by yinshuwei** [comment]
修改 node_modules/@tarojs/cli/templates/default/config/index.js 第31行

```javascript
  plugins: [<% if (css !== 'none') {%>
    '@tarojs/plugin-<%= css %>',<%}%>
    '@tarojs/plugin-terser'
  ],
```

```javascript
plugins: [<% var css = 'sass';if (css !== 'none') {%>
    '@tarojs/plugin-<%= css %>',<%}%>
    '@tarojs/plugin-terser'
  ],
```

**Comment by luckyadam** [comment]
下个版本修复
