### ISSUE TITLE
点击小程序主页键后出现Maximum call stack size exceeded

### ISSUE THREAD

**Issue by susdevlop** [NervJS/taro#6792]
### 问题描述
点击小程序主页键后出现Maximum call stack size exceeded

### 复现步骤
页面载入过程都正常，但是在点击小程序主页键后出现Maximum call stack size exceeded，参考了 [此贴](https://github.com/NervJS/taro/issues/3680)但是好像没有setState啊

另外， 一下代码为子组件， 我把其父父组件注释 报错消失， 把父父组件的隔壁那行注释 报错也消失了。 但是两条不注释就是报错

```js
<View className='content'>
        {props.billList && props.billList.bills.map((item: I_bills, index: number) => {
          let nameText;
          let dateText;
          let dataStyle;
          if(item.type === '0'){
            dateText = `${strDateToFormat(item.start_time)}-${strDateFormat(item.time, 'HH:mm')}`;
            dataStyle = 'none'
          }else {
            dateText = `${strDateToFormat(item.time)}`;
            dataStyle = 'auto'
          }
          if(item.commodity_name === '回合消费'){
            if(modeType === CARD){
              nameText = roundCost
            }else{
              if(item.previous_table){
                nameText = `${doneRoundCost}-${item.previous_table}`;
              }else{
                nameText = doneRoundCost
              }
            }
          }else{
            nameText = item.commodity_name
          }
          let priceText;
          let discountText;
          if(+item.type===0&&+item.origin_price>+item.price){
            const discount = +changeToDecimal(+item.price/+item.origin_price*10);
            priceText = ` ${item.price+'  元'}`;
            discountText = `${discount.toFixed(1)}`;
          }else{
            priceText = item.price+'  元';
            discountText = ''
          }
          return <View key={index} className='item-box'>
            <View className='item'>
              <View className='left'>
                <View className='userAvatar' style={{display:isShowAvatar?'block':'none'}} >
                  <Image src={user_info[item.account].avatar} mode="widthFix"/>
                </View>
                <View className='leftText'>
                  {/*<View className='name'><Text>{nameText}</Text></View>*/}
                  <View className='name'>
                    <TextOverFlowAnimation text={nameText} style={{margin: dataStyle}} />
                  </View>
                  <View className='date'>
                    {/*<TextOverFlowAnimation text={dateText} style={{margin: dataStyle}} />*/}
                    <Text style={{margin: dataStyle}}>{dateText}</Text>
                  </View>
                </View>
              </View>
              <View className='right'>
                {/*<TextOverFlowAnimation style={{padding: '0 20px',margin:'0 auto'}} text={item.price+'  元'} />*/}
                {/*<Text style={{padding: '0 20px',margin:'0 auto'}}>{item.price+'  元'}</Text>*/}
                <Text className='priceText'>{priceText}</Text>
                <Text className='discountText'>{discountText}</Text>
              </View>
            </View>
          </View>
          }
        )}


```

### 报错信息
MiniProgramError
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at s (http://127.0.0.1:10047/appservice/__dev__/WAService.js:2:1756246)
    at s (http://127.0.0.1:10047/appservice/__dev__/WAService.js:2:1756482)
    at s (http://127.0.0.1:10047/appservice/__dev__/WAService.js:2:1756482)
    at s (http://127.0.0.1:10047/appservice/__dev__/WAService.js:2:1756482)
    at s (http://127.0.0.1:10047/appservice/__dev__/WAService.js:2:1756482)
    at s (http://127.0.0.1:10047/appservice/__dev__/WAService.js:2:1756482)
    at s (http://127.0.0.1:10047/appservice/__dev__/WAService.js:2:1756482)
    at s (http://127.0.0.1:10047/appservice/__dev__/WAService.js:2:1756482)
    at s (http://127.0.0.1:10047/appservice/__dev__/WAService.js:2:1756482)
    at s (http://127.0.0.1:10047/appservice/__dev__/WAService.js:2:1756482)

console.error | @ | VM9668:1
-- | -- | --
  | errorReport | @ | VM9674 WAService.js:2
  | thirdErrorReport | @ | VM9674 WAService.js:2
  | (anonymous) | @ | VM9674 WAService.js:2
  | h | @ | VM9674 WAService.js:2
  | (anonymous) | @ | VM9674 WAService.js:2
  | Mc | @ | VM9674 WAService.js:2
  | h | @ | VM9674 WAService.js:2
  | (anonymous) | @ | VM9674 WAService.js:2
  | (anonymous) | @ | VM9674 WAService.js:2
  | setTimeout (async) |   |  
  | setTimeout | @ | VM9674 WAService.js:2
  | Nc | @ | VM9674 WAService.js:2
  | p.<computed> | @ | VM9674 WAService.js:2
  | (anonymous) | @ | VM9674 WAService.js:2
  | (anonymous) | @ | VM9674 WAService.js:2
  | s | @ | VM9674 WAService.js:2
  | (anonymous) | @ | VM9674 WAService.js:2
  | nextTick | @ | taro.js:391
  | enqueueRender | @ | taro.js:3018
  | setState | @ | taro.js:3118
  | hook.state | @ | taro.js:6070
  | checkForUpdates | @ | vendors.js:700
  | (anonymous) | @ | vendors.js:705
  | (anonymous) | @ | taro.js:6094
  | invokeEffects | @ | taro.js:6089
  | (anonymous) | @ | taro.js:6119
  | (anonymous) | @ | taro.js:6117
  | h | @ | VM9674 WAService.js:2
  | (anonymous) | @ | VM9674 WAService.js:2
  | (anonymous) | @ | VM9674 WAService.js:2
  | setTimeout (async) |   |  
  | setTimeout | @ | VM9674 WAService.js:2
  | (anonymous) | @ | taro.js:6116
  | Promise.then (async) |   |  
  | invokeScheduleEffects | @ | taro.js:6115
  | useEffectImpl | @ | taro.js:6141
  | useEffect | @ | taro.js:6149
  | useSelector | @ | vendors.js:677
  | _createData | @ | index.js:152
  | doUpdate | @ | taro.js:2914
  | mountComponent | @ | taro.js:2872
  | initComponent | @ | taro.js:2590
  | attached | @ | taro.js:2662
  | r.safeCallback | @ | VM9674 WAService.js:2
  | r.call | @ | VM9674 WAService.js:2
  | r | @ | VM9674 WAService.js:2
  | m | @ | VM9674 WAService.js:2
  | y.pretendAttached | @ | VM9674 WAService.js:2
  | bt | @ | VM9674 WAService.js:2
  | jt | @ | VM9674 WAService.js:2
  | Mt | @ | VM9674 WAService.js:2
  | (anonymous) | @ | VM9674 WAService.js:2
  | (anonymous) | @ | VM9674 WAService.js:2
  | i.emit | @ | VM9674 WAService.js:2
  | emit | @ | VM9674 WAService.js:2
  | (anonymous) | @ | VM9674 WAService.js:2
  | i.emit | @ | VM9674 WAService.js:2
  | emit | @ | VM9674 WAService.js:2
  | (anonymous) | @ | VM9674 WAService.js:2
  | (anonymous) | @ | VM9674 WAService.js:2
  | n | @ | VM9672 asdebug.js:1
  | (anonymous) | @ | VM9672 asdebug.js:1
  | (anonymous) | @ | VM9672 asdebug.js:1
  | _ws.onmessage | @ | VM9672 asdebug.js:1

### 系统信息
  Taro CLI 2.2.9 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.3 => 2.2.3 
      @tarojs/components-qa: 2.2.3 => 2.2.3 
      @tarojs/components-rn: 2.2.3 => 2.2.3 
      @tarojs/mini-runner: 2.2.3 => 2.2.3 
      @tarojs/plugin-sass: ^2.2.9 => 2.2.9 
      @tarojs/plugin-uglify: ^2.2.9 => 2.2.9 
      @tarojs/redux: 2.2.3 => 2.2.3 
      @tarojs/redux-h5: 2.2.3 => 2.2.3 
      @tarojs/rn-runner: 2.2.3 => 2.2.3 
      @tarojs/router: 2.2.3 => 2.2.3 
      @tarojs/taro: 2.2.3 => 2.2.3 
      @tarojs/taro-alipay: 2.2.3 => 2.2.3 
      @tarojs/taro-h5: 2.2.3 => 2.2.3 
      @tarojs/taro-qq: 2.2.3 => 2.2.3 
      @tarojs/taro-quickapp: 2.2.3 => 2.2.3 
      @tarojs/taro-redux-rn: 2.2.3 => 2.2.3 
      @tarojs/taro-router-rn: 2.2.3 => 2.2.3 
      @tarojs/taro-swan: 2.2.3 => 2.2.3 
      @tarojs/taro-tt: 2.2.3 => 2.2.3 
      @tarojs/taro-weapp: 2.2.3 => 2.2.3 
      @tarojs/webpack-runner: 2.2.3 => 2.2.3 
      eslint-config-taro: 2.2.3 => 2.2.3 
      eslint-plugin-taro: 2.2.3 => 2.2.3 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      react: 16.8.0 => 16.8.0 
      react-native: 0.59.9 => 0.59.9 
      stylelint-config-taro-rn: 2.2.3 => 2.2.3 
      stylelint-taro-rn: 2.2.3 => 2.2.3 

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by susdevlop** [comment]
已解决，问题在于 ref没有正常赋值，然后就出现爆栈了 ref改成函数式赋值就没事了
