### ISSUE TITLE
Module AppRegistry is not a registered callable module (calling runApplication)

### ISSUE THREAD

**Issue by sapphirezzz** [NervJS/taro#6815]
### 问题描述

现有的`iOS`项目，加载`Taro`转换后的`React-Native`页面，提示错误:
```
Module AppRegistry is not a registered callable module (calling runApplication)
```

### 复现步骤

1. 在现有`iOS`工程目录下，初始化项目`taro init mjbTaro`
2. 在`config/index.js`中添加`rn`配置
3. 执行`React-Native`调试代码`yarn dev:rn`
4. 现有`iOS`工程中，修改`Podfile`文件，执行`pod install`
5. `iOS`项目中，点击按钮加载`React-Native`页面

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */
/* config/index.js */
rn: {
    appJson: {
      name: 'mjbTaro',
    }
}

/* Podfile */
target "xxx" do

    # React-Native
    pod 'React', :path => './mjbTaro/node_modules/react-native', :subspecs => [
      'Core',
      'CxxBridge', # Include this for RN >= 0.47
      'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
      'RCTText',
      'RCTNetwork',
      'RCTWebSocket', # needed for debugging
      # Add any other subspecs you want to use in your project
    ]
    # Explicitly include Yoga if you are using RN >= 0.42.0
    pod "yoga", :path => "./mjbTaro/node_modules/react-native/ReactCommon/yoga"

    # Third party deps podspec link
    pod 'DoubleConversion', :podspec => './mjbTaro/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => './mjbTaro/node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => './mjbTaro/node_modules/react-native/third-party-podspecs/Folly.podspec'
end

/* 加载`React-Native`页面的调用代码 */
var urlString = URL(string: "http://127.0.0.1:8081/rn_temp/index.bundle?platform=ios")
if let jsCodeLocation = urlString {
    
    let rootView = RCTRootView.init(bundleURL: jsCodeLocation, moduleName: "mjbTaro", initialProperties: [
        "scores": [
            [
                "name": "Alex",
                "value": "42"
            ],
            [
                "name": "Joel",
                "value": "10"
            ],
        ]
    ], launchOptions: nil)
    let vc = UIViewController()
    vc.view = rootView
    controller.present(vc, animated: true, completion: nil)
}

```

### 期望行为

正常显示`React-Native`页面

### 报错信息

```
2020-06-29 12:00:19.430 [warn][tid:com.facebook.react.JavaScript] The "UMNativeModulesProxy" native module is not exported through NativeModules; verify that @unimodules/react-native-adapter's native code is linked properly
2020-06-29 12:00:19.438 [warn][tid:com.facebook.react.JavaScript] The "UMNativeModulesProxy" native module is not exported through NativeModules; verify that @unimodules/react-native-adapter's native code is linked properly
2020-06-29 12:00:19.439 [warn][tid:com.facebook.react.JavaScript] Require cycle: node_modules/@tarojs/taro-rn/node_modules/@unimodules/react-native-adapter/build/index.js -> node_modules/@tarojs/taro-rn/node_modules/@unimodules/react-native-adapter/build/errors/UnavailabilityError.js -> node_modules/@tarojs/taro-rn/node_modules/@unimodules/react-native-adapter/build/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
2020-06-29 12:00:19.442 [warn][tid:com.facebook.react.JavaScript] No native ExponentConstants module found, are you sure the expo-constants's module is linked properly?
2020-06-29 12:00:19.447 [error][tid:com.facebook.react.JavaScript] Native module cannot be null.
2020-06-29 12:00:19.467 [error][tid:com.facebook.react.JavaScript] Module AppRegistry is not a registered callable module (calling runApplication)
2020-06-29 12:00:19.479 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Native module cannot be null.
2020-06-29 12:00:19.578 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Module AppRegistry is not a registered callable module (calling runApplication)
```

### 系统信息

```
👽 Taro v2.2.9


  Taro CLI 2.2.9 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.9 => 2.2.9 
      @tarojs/components-qa: 2.2.9 => 2.2.9 
      @tarojs/components-rn: ^2.2.9 => 2.2.9 
      @tarojs/mini-runner: 2.2.9 => 2.2.9 
      @tarojs/plugin-sass: 2.2.9 => 2.2.9 
      @tarojs/plugin-terser: 2.2.9 => 2.2.9 
      @tarojs/rn-runner: ^2.2.9 => 2.2.9 
      @tarojs/router: 2.2.9 => 2.2.9 
      @tarojs/taro: 2.2.9 => 2.2.9 
      @tarojs/taro-alipay: 2.2.9 => 2.2.9 
      @tarojs/taro-h5: 2.2.9 => 2.2.9 
      @tarojs/taro-qq: 2.2.9 => 2.2.9 
      @tarojs/taro-quickapp: 2.2.9 => 2.2.9 
      @tarojs/taro-redux-rn: ^2.2.9 => 2.2.9 
      @tarojs/taro-rn: ^2.2.9 => 2.2.9 
      @tarojs/taro-router-rn: ^2.2.9 => 2.2.9 
      @tarojs/taro-swan: 2.2.9 => 2.2.9 
      @tarojs/taro-tt: 2.2.9 => 2.2.9 
      @tarojs/taro-weapp: 2.2.9 => 2.2.9 
      @tarojs/webpack-runner: 2.2.9 => 2.2.9 
      eslint-config-taro: 2.2.9 => 2.2.9 
      eslint-plugin-taro: 2.2.9 => 2.2.9 
      nerv-devtools: ^1.5.5 => 1.5.7 
      nervjs: ^1.5.5 => 1.5.7 
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
      stylelint-config-taro-rn: 2.2.9 => 2.2.9 
      stylelint-taro-rn: 2.2.9 => 2.2.9 
```

### 补充信息

【1】该`iOS`项目加载直接用`React-Native`写生成的页面是没问题的，下面是两个相关的文件：
```
/ * package.json */
{
  "name": "MJB",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "yarn react-native start"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-unimodules": "0.6.0"
  }
}

/* index.js */
import React from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

class RNHighScores extends React.Component {

  render() {
    var contents = this.props['scores'].map((score) => (
      <Text key={score.name}>
        {score.name}:{score.value}
        {'\n'}
      </Text>
    ));
    return (
      <View style={styles.container}>
        <Text style={styles.highScoresTitle}>
          2048 High Scores!
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF'
  },
  highScoresTitle: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10
  },
  scores: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5
  }
});

// Module name
AppRegistry.registerComponent('mjbTaro', () => RNHighScores);

```

【2】
```
    import {AppRegistry} from 'react-native';
    import App from './app.js';
    import {name as appName} from './app.json';
    AppRegistry.registerComponent(appName, () => App);
```
上面是`Taro`生成的`rn_temp/index.js`文件，直接将其改成以下代码，是可以加载的。

```
/* index.js */
import React from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

class RNHighScores extends React.Component {

  render() {
    var contents = this.props['scores'].map((score) => (
      <Text key={score.name}>
        {score.name}:{score.value}
        {'\n'}
      </Text>
    ));
    return (
      <View style={styles.container}>
        <Text style={styles.highScoresTitle}>
          2048 High Scores!
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF'
  },
  highScoresTitle: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10
  },
  scores: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5
  }
});

// Module name
AppRegistry.registerComponent('mjbTaro', () => RNHighScores);
```

所以，猜测是`Taro`生成的`rn_temp/pages/index/index.js`多了些别的依赖库或者别的逻辑。

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Pines-Cheng** [comment]
当前 Taro 的项目是基于 [react-native-unimodules](https://github.com/expo/expo/tree/master/packages/react-native-unimodules) 的，原声的项目需要参照 README 自行集成。

**Comment by sapphirezzz** [comment]
> 当前 Taro 的项目是基于 [react-native-unimodules](https://github.com/expo/expo/tree/master/packages/react-native-unimodules) 的，原声的项目需要参照 README 自行集成。

按照该文档，在Taro项目中，安装了`react-native-unimodules`
```
yarn add react-native-unimodules
```
并在`iOS`项目中添加依赖和安装。但编译提示：

```
Build operation failed without specifying any errors. Individual build tasks may have failed for unknown reasons.
One possible cause is if there are too many (possibly zombie) processes; in this case, rebooting may fix the problem.
Some individual build task failures (up to 12) may be listed below.
```

cocoaPods 是最新的1.9.3，降级到1.8.4也没用～

**Comment by sapphirezzz** [comment]
> 当前 Taro 的项目是基于 [react-native-unimodules](https://github.com/expo/expo/tree/master/packages/react-native-unimodules) 的，原声的项目需要参照 README 自行集成。

另外，我看该文档指向的[`Podfile `示例](https://github.com/expo/expo/blob/master/templates/expo-template-bare-minimum/ios/Podfile)，里面加了`require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'`，和`  use_native_modules!`。

是否需要呢？我加了之后报错如下：
```
[!] Invalid `Podfile` file: [!] /usr/local/bin/node -e try {console.log(require('@react-native-community/cli').bin);} catch (e) {console.log(require('react-native/cli').bin);}

internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'react-native/cli'
Require stack:
- /Users/mooyoo/Desktop/MJB-iOS/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at [eval]:1:87
    at Script.runInThisContext (vm.js:131:18)
    at Object.runInThisContext (vm.js:295:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at evalScript (internal/process/execution.js:98:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/mooyoo/Desktop/MJB-iOS/[eval]' ]
}
.

 #  from /Users/mooyoo/Desktop/MJB-iOS/Podfile:123
 #  -------------------------------------------
 #      use_unimodules!
 >      use_native_modules!
 #  
 #  -------------------------------------------
```

**Comment by sapphirezzz** [comment]
我参考壳工程处理下先吧，不用RN的新版本了～

https://github.com/NervJS/taro-native-shell
