### ISSUE TITLE
Taro 2.2.7 & 2.2.9 dev:weapp 编译错误 unknown: Unexpected token

### ISSUE THREAD

**Issue by Remering** [NervJS/taro#6820]
### 问题描述

taro 2.2.7 dev:weapp 编译错误 unknown: Unexpected token

升级到最新版本2.2.9后依然出现此错误

### 复现步骤

代码片段：
```ts
import Taro, { DownloadTask } from '@tarojs/taro'
import { View } from '@tarojs/components'
import { connect } from '@tarojs/redux'
import { ClMenuList, ClAccordion } from 'mp-colorui'


import { contentIcons, MessageType, ActionSheetOption, ActionSheetHandler, SubChapter } from '../../../types'
import { showMessage as showMessageAction } from '../../../stores/message'
import { State } from '../../../stores'
import {
  showActionSheet as showActionSheetAction,
  setActionSheetHandler as setActionSheetHandlerAction,
  setActionSheetOptions as setActionSheetOptionsAction
} from '../../../stores/actionSheet/actions'


interface InjectedSubChapterViewProps {
    showMessage(type: MessageType, message: string)
    showActionSheet()
    setActionSheetOptions(options: ActionSheetOption[])
    setActionSheetHandler(handler: ActionSheetHandler)
}

interface SubChapterViewProps {
    chapterIndex: number
    subChapterIndex: number
    subChapter: SubChapter
}


class SubChapterView extends Taro.Component<SubChapterViewProps & InjectedSubChapterViewProps> {
  render() {
    const {
      chapterIndex,
      subChapterIndex,
      subChapter,
      showMessage,
      showActionSheet,
      setActionSheetHandler,
      setActionSheetOptions
    } = this.props;

    if (!subChapter || !subChapter.contents) {
      return (
        <View />
      )
    }

    const prefix = `${chapterIndex + 1}.${subChapterIndex + 1}`

    const itemList =
      Object.entries(subChapter.contents)
        .map((entry, contentIndex) => {
          const [contentUUID, content] = entry;
          const {url, type} = content;
          return {
            title: `${prefix}.${contentIndex + 1} ${content.name}`,
            uuid: contentUUID,
            icon: {
              iconName: contentIcons[content.type]
            },
            url,
            type,
            downloadTask: null as DownloadTask | null
          }
        });

    const handleClick = (itemIndex: number) => {
      const content = itemList[itemIndex]
      const {url, title, type} = content
      if (type === 'video') {
        return
      }

      const fileName = `${title}.pdf`

      const filePath = `${Taro.env.USER_DATA_PATH}/${fileName}`


      if (content.downloadTask) {
        setActionSheetOptions([
          {
            text: '取消下载',
            bgColor: 'red',
          }
        ])
        setActionSheetHandler(() => {
          if (content.downloadTask) {
            content.downloadTask.abort()
            content.downloadTask = null
          }
        })
        showActionSheet()
        return
      }

      const options = [
        {
          text: '下载',
          bgColor: 'green',
          handler() {
            content.downloadTask = Taro.downloadFile({
              url,
              filePath,
              success() {
                showMessage('success', `${fileName}下载完成`)
                handleClick(itemIndex)
              },
              fail() {
                showMessage('error', `${fileName}下载失败`)
              },
              complete() {
                content.downloadTask = null
              }
            })
          }
        },
        {
          text: '打开',
          bgColor: 'yellow',
          handler: () => Taro.openDocument({
            filePath,
            fail() {
              showMessage('error', `打开${fileName}失败，请尝试重新下载`)
            }
          })

        },
        {
          text: '校验',
          bgColor: 'green',
          handler() {
            console.log('校验')
          }
        }
      ]

      setActionSheetOptions(options)

      setActionSheetHandler((optionIndex) => options[optionIndex].handler())

      showActionSheet()

    };


    return (
      <ClAccordion title={`${prefix} ${subChapter.name}`}>
        <ClMenuList
          shortBorder
          list={itemList}
          onClick={handleClick}
        />
      </ClAccordion>

    )
  }
}

const mapStateToProps = (_state: State, props) => props

const mapDispatchToProps: InjectedSubChapterViewProps = {
    showMessage: showMessageAction,
    showActionSheet: showActionSheetAction,
    setActionSheetHandler: setActionSheetHandlerAction,
    setActionSheetOptions: setActionSheetOptionsAction

}

export default connect(mapStateToProps, mapDispatchToProps)(SubChapterView) as Taro.ComponentClass<SubChapterViewProps>;
```
完整项目见[这里](https://github.com/Remering/internet-of-things-and-smart-mine/blob/master/src/pages/chapter/view/SubChapterView.tsx)
### 期望行为

编译成功

### 报错信息

```
./src/pages/chapter/view/SubChapterView.tsx
Module Error (from ./node_modules/@tarojs/mini-runner/dist/loaders/wxTransformerLoader.js):
unknown: Unexpected token (47:6)

SyntaxError: unknown: Unexpected token (47:6)
  45 |     });
  46 |     const handleClick = itemIndex => {
> 47 |       const content = itemList[itemIndex];
     |       ^
  48 |       const { url, title, type } = content;
  49 |       if (type === 'video') {
  50 |         return;
    at Parser.pp$5.raise (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:1761:8)
    at Parser.pp$3.parseExprAtom (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:3750:12)
    at Parser.parseExprAtom (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:7238:22)
    at Parser.pp$3.parseExprSubscripts (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:3474:19)
    at Parser.pp$3.parseExprOps (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:3344:19)
    at Parser.pp$3.parseExpression (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:3306:19)
    at Parser.pp$9.jsxParseExpressionContainer (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:7119:28)
    at Parser.pp$9.jsxParseElementAt (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:7193:32)
    at Parser.pp$9.jsxParseElement (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:7224:15)
    at Parser.parseExprAtom (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:7236:21)
    at Parser.pp$3.parseExprSubscripts (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:3474:19) {
  pos: 2049,
  loc: Position { line: 47, column: 6 },
  _babel: true,
  codeFrame: '\u001b[0m \u001b[90m 45 | \u001b[39m    })\u001b[33m;\u001b[39m\n' +
    ' \u001b[90m 46 | \u001b[39m    \u001b[36mconst\u001b[39m handleClick \u001b[33m=\u001b[39m itemIndex \u001b[33m=>\u001b[39m {\n' +
    '\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 47 | \u001b[39m      \u001b[36mconst\u001b[39m content \u001b[33m=\u001b[39m itemList[item
Index]\u001b[33m;\u001b[39m\n' +
    ' \u001b[90m    | \u001b[39m      \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n' +
    ' \u001b[90m 48 | \u001b[39m      \u001b[36mconst\u001b[39m { url\u001b[33m,\u001b[39m title\u001b[33m,\u001b[39m type } \u001b[33m=\u001b[39m
 content\u001b[33m;\u001b[39m\n' +
    " \u001b[90m 49 | \u001b[39m      \u001b[36mif\u001b[39m (type \u001b[33m===\u001b[39m \u001b[32m'video'\u001b[39m) {\n" +
    ' \u001b[90m 50 | \u001b[39m        \u001b[36mreturn\u001b[39m\u001b[33m;\u001b[39m\u001b[0m'
}
�   编译失败.

./src/pages/chapter/view/SubChapterView.tsx
Module Error (from ./node_modules/@tarojs/mini-runner/dist/loaders/wxTransformerLoader.js):
unknown: Unexpected token (47:6)

```

### 系统信息

 Taro CLI 2.2.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.6.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.17.3 - C:\Users\mafumafu\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

### 补充信息
当我把出问题的`handler`部分注释掉后依然出现编译错误

注释掉后的代码
```tsx
import Taro, {DownloadTask} from '@tarojs/taro'
import {View} from '@tarojs/components'
import {connect} from '@tarojs/redux'
import {ClAccordion, ClMenuList} from 'mp-colorui'


import {ActionSheetHandler, ActionSheetOption, contentIcons, MessageType, SubChapter} from '../../../types'
import {showMessage as showMessageAction} from '../../../stores/message'
import {State} from '../../../stores'
import {
  setActionSheetHandler as setActionSheetHandlerAction,
  setActionSheetOptions as setActionSheetOptionsAction,
  showActionSheet as showActionSheetAction
} from '../../../stores/actionSheet/actions'


interface InjectedSubChapterViewProps {
    showMessage(type: MessageType, message: string)
    showActionSheet()
    setActionSheetOptions(options: ActionSheetOption[])
    setActionSheetHandler(handler: ActionSheetHandler)
}

interface SubChapterViewProps {
    chapterIndex: number
    subChapterIndex: number
    subChapter: SubChapter
}


const SubChapterView: Taro.FC<SubChapterViewProps & InjectedSubChapterViewProps> =
  ({
     chapterIndex,
     subChapterIndex,
     subChapter,
     showMessage,
     showActionSheet,
     setActionSheetHandler,
     setActionSheetOptions
   }) => {

  if (!subChapter || !subChapter.contents) {
    return (
      <View />
    )
  }

  const prefix = `${chapterIndex + 1}.${subChapterIndex + 1}`

  const itemList =
    Object.entries(subChapter.contents)
      .map((entry, contentIndex) => {
        const [contentUUID, content] = entry;
        const {url, type} = content;
        return {
          title: `${prefix}.${contentIndex + 1} ${content.name}`,
          uuid: contentUUID,
          icon: {
            iconName: contentIcons[content.type]
          },
          url,
          type,
          downloadTask: null as DownloadTask | null
        }
      })

  // const handleClick = (itemIndex: number) => {
  //   const content = itemList[itemIndex]
  //   const {url, title, type} = content
  //   if (type === 'video') {
  //     return
  //   }
  //
  //   const fileName = `${title}.pdf`
  //
  //   const filePath = `${Taro.env.USER_DATA_PATH}/${fileName}`
  //
  //
  //   if (content.downloadTask) {
  //     setActionSheetOptions([
  //       {
  //         text: '取消下载',
  //         bgColor: 'red',
  //       }
  //     ])
  //     setActionSheetHandler(() => {
  //       if (content.downloadTask) {
  //         content.downloadTask.abort()
  //         content.downloadTask = null
  //       }
  //     })
  //     showActionSheet()
  //     return
  //   }
  //
  //   const options = [
  //     {
  //       text: '下载',
  //       bgColor: 'green',
  //       handler() {
  //         content.downloadTask = Taro.downloadFile({
  //           url,
  //           filePath,
  //           success() {
  //             showMessage('success', `${fileName}下载完成`)
  //             handleClick(itemIndex)
  //           },
  //           fail() {
  //             showMessage('error', `${fileName}下载失败`)
  //           },
  //           complete() {
  //             content.downloadTask = null
  //           }
  //         })
  //       }
  //     },
  //     {
  //       text: '打开',
  //       bgColor: 'yellow',
  //       handler: () => Taro.openDocument({
  //         filePath,
  //         fail() {
  //           showMessage('error', `打开${fileName}失败，请尝试重新下载`)
  //         }
  //       })
  //
  //     },
  //     {
  //       text: '校验',
  //       bgColor: 'green',
  //       handler() {
  //         console.log('校验')
  //       }
  //     }
  //   ]
  //
  //   setActionSheetOptions(options)
  //
  //   setActionSheetHandler((optionIndex) => options[optionIndex].handler())
  //
  //   showActionSheet()
  //
  // };


  return (
    <ClAccordion title={`${prefix} ${subChapter.name}`}>
      <ClMenuList
        shortBorder
        list={itemList}
        // onClick={handleClick}
      />
    </ClAccordion>

  )
}

const mapStateToProps = (_state: State, props) => props

const mapDispatchToProps: InjectedSubChapterViewProps = {
    showMessage: showMessageAction,
    showActionSheet: showActionSheetAction,
    setActionSheetHandler: setActionSheetHandlerAction,
    setActionSheetOptions: setActionSheetOptionsAction

}

// @ts-ignore
export default connect(mapStateToProps, mapDispatchToProps)(SubChapterView) as Taro.ComponentClass<SubChapterViewProps>;
```
注释掉后的报错信息
```
SyntaxError: unknown: Unexpected token (124:4)
  122 |     //
  123 |     // };
> 124 |     const anonymousState__temp = prefix + " " + subChapter.name;
      |     ^
  125 |     propsManager.set({
  126 |       "title": anonymousState__temp
  127 |     }, $compid__122, $prevCompid__122);
    at Parser.pp$5.raise (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:1761:8)
    at Parser.pp$3.parseExprAtom (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:3750:12)
    at Parser.parseExprAtom (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:7238:22)
    at Parser.pp$3.parseExprSubscripts (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:3474:19)
    at Parser.pp$3.parseExprOps (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:3344:19)
    at Parser.pp$3.parseExpression (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:3306:19)
    at Parser.pp$9.jsxParseExpressionContainer (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:7119:28)
    at Parser.pp$9.jsxParseElementAt (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:7193:32)
    at Parser.pp$9.jsxParseElement (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:7224:15)
    at Parser.parseExprAtom (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:7236:21)
    at Parser.pp$3.parseExprSubscripts (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (C:\WorkPlace\Taro\internet-of-things-and-smart-mine\node_modules\babylon\lib\index.js:3474:19) {
  pos: 4060,
  loc: Position { line: 124, column: 4 },
  _babel: true,
  codeFrame: '\u001b[0m \u001b[90m 122 | \u001b[39m    \u001b[90m//\u001b[39m\n' +
    ' \u001b[90m 123 | \u001b[39m    \u001b[90m// };\u001b[39m\n' +
    '\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 124 | \u001b[39m    \u001b[36mconst\u001b[39m anonymousState__temp \u001b[33m=\u001b[39m p
refix \u001b[33m+\u001b[39m \u001b[32m" "\u001b[39m \u001b[33m+\u001b[39m subChapter\u001b[33m.\u001b[39mname\u001b[33m;\u001b[39m\n' +
    ' \u001b[90m     | \u001b[39m    \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n' +
    ' \u001b[90m 125 | \u001b[39m    propsManager\u001b[33m.\u001b[39mset({\n' +
    ' \u001b[90m 126 | \u001b[39m      \u001b[32m"title"\u001b[39m\u001b[33m:\u001b[39m anonymousState__temp\n' +
    ' \u001b[90m 127 | \u001b[39m    }\u001b[33m,\u001b[39m $compid__122\u001b[33m,\u001b[39m $prevCompid__122)\u001b[33m;\u001b[39m\u001b[0m'
}
�   编译失败.

./src/pages/chapter/view/SubChapterView.tsx
Module Error (from ./node_modules/@tarojs/mini-runner/dist/loaders/wxTransformerLoader.js):
unknown: Unexpected token (124:4)
```
但是当我把本文件内容全部删除后可以通过编译

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
https://github.com/Remering/internet-of-things-and-smart-mine/pull/1
提交了一个 pr，可以这样调整一下写法来绕过

**Comment by Remering** [comment]
感谢大佬，不过这个是我写法的问题还是taro的一个bug？如果是bug的话希望以后能够修复

**Comment by luckyadam** [comment]
> 感谢大佬，不过这个是我写法的问题还是taro的一个bug？如果是bug的话希望以后能够修复

应该是个 bug

**Comment by hcxmj** [comment]
> ### [Jun 30, 2020](#issuecomment-651499346)
请问在2.2.19版本里引入Taro调用Taro.eventCenter.trigger出现跟这个问题几乎一样怎么解呢

**Comment by hcxmj** [comment]
@luckyadam 
请问在2.2.19版本里引入Taro调用Taro.eventCenter.trigger出现跟这个问题报错一模一样一样怎么解呢

**Comment by hcxmj** [comment]
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/58494807/203737429-f03eaa43-e12d-49a8-ad9f-fe540a24dd58.png">
