### ISSUE TITLE
[3.0.0-rc.6] Map 组件报错

### ISSUE THREAD

**Issue by viewweiwu** [NervJS/taro#6859]
![image](https://user-images.githubusercontent.com/14287892/86225538-f3fe5a80-bbbc-11ea-9f55-2b4aad59cfe3.png)

```
VM699:1 微信小程序 map 组件的 `setting` 属性需要传递一个默认值。详情：
 https://developers.weixin.qq.com/miniprogram/dev/component/map.html
console.warn @ VM699:1
warn @ runtime.esm.js:57
TaroElement @ runtime.esm.js:2070
createElement @ runtime.esm.js:2357
createInstance @ react.esm.js:164
completeWork @ app.js:10921
completeUnitOfWork @ app.js:14794
performUnitOfWork @ app.js:14770
workLoopSync @ app.js:14735
performSyncWorkOnRoot @ app.js:14331
(anonymous) @ app.js:2011
unstable_runWithPriority @ app.js:18719
runWithPriority @ app.js:1961
flushSyncCallbackQueueImpl @ app.js:2006
flushSyncCallbackQueue @ app.js:1994
scheduleUpdateOnFiber @ app.js:13770
enqueueForceUpdate @ app.js:3889
push../node_modules/react/cjs/react.development.js.Component.forceUpdate @ react.development.js:490
mount @ runtime.esm.js:2897
mount @ runtime.esm.js:2952
onLoad @ runtime.esm.js:2620
(anonymous) @ VM705 WAService.js:2
p.__callPageLifeTime__ @ VM705 WAService.js:2
jt @ VM705 WAService.js:2
(anonymous) @ VM705 WAService.js:2
Mt @ VM705 WAService.js:2
(anonymous) @ VM705 WAService.js:2
(anonymous) @ VM705 WAService.js:2
i.emit @ VM705 WAService.js:2
emit @ VM705 WAService.js:2
(anonymous) @ VM705 WAService.js:2
i.emit @ VM705 WAService.js:2
emit @ VM705 WAService.js:2
(anonymous) @ VM705 WAService.js:2
(anonymous) @ VM705 WAService.js:2
n @ VM703 asdebug.js:1
(anonymous) @ VM703 asdebug.js:1
(anonymous) @ VM703 asdebug.js:1
_ws.onmessage @ VM703 asdebug.js:1
Show 9 more frames
VM720:1 Wed Jul 01 2020 17:01:26 GMT+0800 (中国标准时间) 渲染层错误
VM699:1 TypeError: Cannot read property 'layerStyle' of null
    at i._insertIframeMap (:27805/__pageframe__/__dev__/WAWebview.js:2)
    at window.__map_jssdk_init (:27805/__pageframe__/__dev__/WAWebview.js:2)
    at eval (eval at <anonymous> (mapapi.qq.com/jsapi_v2/2/4/132/main.js:1), <anonymous>:1:21)
    at mapapi.qq.com/jsapi_v2/2/4/132/main.js:1
console.error @ VM699:1
(anonymous) @ VM720:2
VM721:1 Wed Jul 01 2020 17:01:26 GMT+0800 (中国标准时间) 渲染层错误
VM699:1 SystemError (webviewScriptError)
Cannot read property 'layerStyle' of null
TypeError: Cannot read property 'layerStyle' of null
    at i._insertIframeMap (http://127.0.0.1:27805/__pageframe__/__dev__/WAWebview.js:2:1124472)
    at window.__map_jssdk_init (http://127.0.0.1:27805/__pageframe__/__dev__/WAWebview.js:2:1121729)
    at eval (eval at <anonymous> (https://mapapi.qq.com/jsapi_v2/2/4/132/main.js:1:61434), <anonymous>:1:21)
    at https://mapapi.qq.com/jsapi_v2/2/4/132/main.js:1:61434
```

```javascript
import React from 'react'
import { View, Map } from '@tarojs/components'
import './index.scss'

export default function Index () {
  const handleTap = () => {
    console.log(1)
  }
  return (
    <View>
      666
      <Map onTap={handleTap}></Map>
    </View>
  )
}

```

**Comment by yuche** [comment]
```
微信小程序 map 组件的 `setting` 属性需要传递一个默认值。详情：
 https://developers.weixin.qq.com/miniprogram/dev/component/map.html
```
这个提示还不够明显吗

**Comment by viewweiwu** [comment]
看到了，只是在 taro2 的时候不传也不会有影响。

**Comment by Kopei** [comment]
这只是一个warning, 奇怪的是, 我加上了setting还是warning.
```
    this.state = {
      mapSettings: {
        skew: 0,
        rotate: 0,
        showLocation: true,
        showScale: true,
        subKey: key,
        layerStyle: 1,
        enableZoom: true,
        enableScroll: true,
        enableRotate: false,
        showCompass: false,
        enable3D: false,
        enableOverlooking: false,
        enableSatellite: false,
        enableTraffic: false,
      }}


 <Map
          class="mapDom"
          subkey={mapParams.qMapKey}
          longitude={mapParams.longitude}
          latitude={mapParams.latitude}
          scale={mapParams.scale}
          markers={mapParams.markers}
          showScale={mapParams.showScale}
          style={mapParams.style}
          showLocation={mapParams.showLocation}
          showCompass={mapParams.showCompass}
          setting={this.state.mapSettings}
        >
  </Map>


```
