### ISSUE TITLE
小程序真机调试 redux-saga报错 dispatch不生效 开发工具没问题 2.11.3

### ISSUE THREAD

**Issue by benmi** [NervJS/taro#6952]
### 相关平台
微信小程序

**小程序基础库: 2.11.3**
**使用框架: React**

### 复现步骤
线上运行的小程序四月下旬就打不开了，
小程序开发工具没问题，真机运行不可以
···
redux-saga error: uncaught at _callee3
at _callee3
at _callee6
at takeEvery(home/wxLogs, _callee)
at _callee
at _callee
Error: [object Object]
at https://usr/app-service.js:12928:17
at https://usr/app-service.js:12024:26
at onError (https://usr/app-service.js:12929:11)
at sagaWithCatch$ (https://usr/app-service.js:12496:13)
at tryCatch (https://usr/app-service.js:15619:40)
at Generator.invoke [as _invoke] (https://usr/app-service.js:15838:22)
at Generator.prototype.<computed> [as throw] (https://usr/app-service.js:15667:21)
at next (https://usr/app-service.js:17584:32)
at Object.currCb [as cont] (https://usr/app-service.js:17683:7)
···
原来版本是1.3.42 后来升级了2.2.8还不可以
线上运行的小程序四月下旬就打不开了，
小程序开发工具没问题，真机运行不可以

### 期望结果
在真机运行环境中接口dispatch正常使用

### 实际结果
在真机运行环境中接口访问不了

### 环境信息
```
  Taro CLI 2.2.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.14.2 - C:\Program Files\nodejs\node.EXE
      npm: 6.8.0 - C:\Program Files\nodejs\npm.CMD

```

**Comment by Chen-jj** [comment]
提供一下可复现代码吧。
