### ISSUE TITLE
Taro3创建小程序插件时，执行相关命令会出现“Cannot read property '0' of undefined”

### ISSUE THREAD

**Issue by Silence-kzp** [NervJS/taro#6959]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/Silence-kzp/taro_test](https://github.com/Silence-kzp/taro_test)
**小程序基础库: 无，程序未能运行起来**
**使用框架: React**

### 复现步骤
创建小程序插件项目后，执行
```
taro build --plugin weapp --watch
```

### 期望结果
正常编译

### 实际结果
(node:6416) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at TaroMiniPlugin.getAppEntry (D:\Code\mini-mall\node_modules\@tarojs\mini-runner\src\plugins\MiniPlugin.ts:297:56)
    at TaroMiniPlugin.apply (D:\Code\mini-mall\node_modules\@tarojs\mini-runner\src\plugins\MiniPlugin.ts:142:26)
    at webpack (D:\Code\mini-mall\node_modules\webpack\lib\webpack.js:51:13)
    at Promise (D:\Code\mini-mall\node_modules\@tarojs\mini-runner\src\index.ts:40:22)
    at new Promise (<anonymous>)
    at D:\Code\mini-mall\node_modules\@tarojs\mini-runner\src\index.ts:39:10
    at Generator.next (<anonymous>)
    at fulfilled (D:\Code\mini-mall\node_modules\@tarojs\mini-runner\dist\index.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
(node:6416) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6416) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### 环境信息
```
  Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
使用2.2.8的版本可以正常运行

**Comment by Chen-jj** [comment]
@Silence-kzp 3.0 还没完全兼容编写小程序插件，将在未来的某个 minor 版本支持。

**Comment by Silence-kzp** [comment]
好的，那只能先切回2版本进行插件的开发，到时再做升级迁移~

**Comment by jaring** [comment]
同遇到此问题。等待未来的某个 minor 版本中。。。

**Comment by vee2046** [comment]
坑，不要在文档里加插件开发啊

**Comment by vee2046** [comment]
@Silence-kzp 后来用2.2.8开发的插件吗？能引用taro-ui吗

**Comment by Silence-kzp** [comment]
@vee2046 对的，我项目中没用到taro-ui，不过2.2.8开发插件巨坑，很多莫名其妙的错误。

**Comment by Chen-jj** [comment]
3.2.6 支持
