### ISSUE TITLE
拉取模版生成工程失败

### ISSUE THREAD

**Issue by youlingred** [NervJS/taro#6968]
Taro即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

⠇ 正在从 github:NervJS/taro-project-templates#v3 拉取远程模板...GotError [RequestError]: connect ETIMEDOUT 192.30.253.113:443
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/node_modules/got/index.js:182:22)
    at Object.onceWrapper (events.js:418:26)
    at ClientRequest.emit (events.js:311:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'RequestError',
  code: 'ETIMEDOUT',
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/NervJS/taro-project-templates/archive/v3.zip',
  protocol: 'https:',
  url: 'https://github.com/NervJS/taro-project-templates/archive/v3.zip'
}
✖ 拉取远程模板仓库失败！

**Comment by youlingred** [comment]
close
