### ISSUE TITLE
拉取模版生成工程失败

### ISSUE THREAD

**Issue by youlingred** [NervJS/taro#6969]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
➜  demo taro init taroApp
👽 Taro v3.0.2

Taro即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

⠇ 正在从 github:NervJS/taro-project-templates#v3 拉取远程模板...GotError [RequestError]: connect ETIMEDOUT 192.30.253.113:443
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/node_modules/got/index.js:182:22)
    at Object.onceWrapper (events.js:418:26)
    at ClientRequest.emit (events.js:311:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'RequestError',
  code: 'ETIMEDOUT',
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/NervJS/taro-project-templates/archive/v3.zip',
  protocol: 'https:',
  url: 'https://github.com/NervJS/taro-project-templates/archive/v3.zip'
}
✖ 拉取远程模板仓库失败！

### 期望结果
能够正常拉取

### 实际结果
拉取失败

### 环境信息
```
Taro CLI 3.0.2 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.2 => 3.0.2 
      @tarojs/mini-runner: 3.0.2 => 3.0.2 
      @tarojs/webpack-runner: 3.0.2 => 3.0.2 
      babel-preset-taro: 3.0.2 => 3.0.2 
      eslint-config-taro: 3.0.2 => 3.0.2 
      react: 16.3.1 => 16.3.1 
      react-native: 0.55.4 => 0.55.4
```

**Comment by Chen-jj** [comment]
网络问题，再试试咯

**Comment by vampireXia** [comment]
我也这样 网络肯定是好的 翻墙什么办法都试了 一直卡在啦取模版这一步 然后过了很久 提示啦取失败
