### ISSUE TITLE
示例项目中安装 taro-ui 后会将 tarojs/runtime 等包删掉，重新安装后小程序运行错误

### ISSUE THREAD

**Issue by baby1990** [NervJS/taro#7108]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/baby1990/wx-app](https://github.com/baby1990/wx-app)
**小程序基础库: 2.11.3**
**使用框架: React**

### 复现步骤
1.taro init 创建一个 react 项目，js版本，less样式预处理工具
2.项目创建完毕后，npm run dev:weapp 可以正常运行
3.npm i taro-ui -s 安装 taro-ui
4.安装完毕后，编译报错 ，@babel/runtime  @tarojs/runtime @tarojs/taro 三个包会被删掉
5.重新执行 npm i 安装缺失的包
6.可编译成功，但页面提示   
The above error occurred in the <AppWrapper> component:
    in AppWrapper

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

MiniProgramError
没有找到页面实例。
如有疑问，请提交 issue 至：https://github.com/nervjs/taro/issues
Error: 没有找到页面实例。
如有疑问，请提交 issue 至：https://github.com/nervjs/taro/issues
    at ensure (http://127.0.0.1:59950/appservice/taro.js:8298:9)
    at AppWrapper.<anonymous> (http://127.0.0.1:59950/appservice/taro.js:11166:9)
    at callCallback (http://127.0.0.1:59950/appservice/app.js:3685:12)
    at commitUpdateEffects (http://127.0.0.1:59950/appservice/app.js:3723:7)
    at commitUpdateQueue (http://127.0.0.1:59950/appservice/app.js:3711:3)
    at commitLifeCycles (http://127.0.0.1:59950/appservice/app.js:12196:11)
    at commitLayoutEffects (http://127.0.0.1:59950/appservice/app.js:15399:7)
    at Object.invokeGuardedCallbackImpl (http://127.0.0.1:59950/appservice/app.js:11629:10)
    at invokeGuardedCallback (http://127.0.0.1:59950/appservice/app.js:11806:31)
    at commitRootImpl (http://127.0.0.1:59950/appservice/app.js:15137:9)

即使将 taro-ui 包卸载了也无法成功运行了！

### 期望结果
安装 taro-ui 不能删除原有包，就算删除了重新安装不应该出现无法运行的情况

### 实际结果
安装完 taro-ui 以后，无论卸载如否，项目编译完，页面均报错，无法运行

### 环境信息
```
 Taro CLI 3.0.0-rc.6 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-rc.6 => 3.0.0-rc.6 
      @tarojs/mini-runner: 3.0.0-rc.6 => 3.0.0-rc.6 
      @tarojs/react: 3.0.0-rc.6 => 3.0.0-rc.6 
      @tarojs/runtime: 3.0.0-rc.6 => 3.0.0-rc.6 
      @tarojs/taro: 3.0.0-rc.6 => 3.0.0-rc.6 
      @tarojs/webpack-runner: 3.0.0-rc.6 => 3.0.0-rc.6 
      babel-preset-taro: 3.0.0-rc.6 => 3.0.0-rc.6 
      eslint-config-taro: 3.0.0-rc.6 => 3.0.0-rc.6 
      react: ^16.10.0 => 16.13.1 
      taro-ui: ^2.3.4 => 2.3.4 
    npmGlobalPackages:
      typescript: 3.6.3

```

**Comment by baby1990** [comment]
已解决，taro-ui 包会改变 package-lock.json，导致就算清理掉后续安装的包的版本也不对，因此，需要将 package-lock.json和 yarn-lock.json 删除掉，再清空 node_modules，重新 npm install 安装依赖，方可运行成功

**Comment by Chen-jj** [comment]
@baby1990 Taro UI alpha 版本才支持 Taro3，可以去他们的仓库下提问

**Comment by zhangwen1932** [comment]
我重新装了，依然报错。。。。。

**Comment by sheyingxin1204** [comment]
球也不是了，我快给它奶装进去了也不行
