### ISSUE TITLE
初始化完app运行dev报错

### ISSUE THREAD

**Issue by xxzj990** [NervJS/taro#7130]
### 相关平台
React Native

**使用框架: Vue2**

### 复现步骤
npm run dev:rn

### 期望结果
可以运行

### 实际结果
无法运行

### 环境信息
```
� Taro v3.0.5


  Taro CLI 3.0.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD

```

---
### 补充信息
报错如下：

� Taro v3.0.5

生成  package.json  D:\web\mini-program\dsm-web\package.json

开始安装依赖~
(node:7280) UnhandledPromiseRejectionWarning: Error: Command failed: npm install
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @tarojs/components-rn@^3.0.5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'dsm-web'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxzj990\AppData\Roaming\npm-cache\_logs\2020-07-21T10_07_39_935Z-debug.log

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:7280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by xxzj990** [comment]
npm run dev:h5

这个可以
