### ISSUE TITLE
1.3.45 升级到taro2.2.11 编译微信小程序报错

### ISSUE THREAD

**Issue by ywanhzy** [NervJS/taro#7132]
### 相关平台
微信小程序

**小程序基础库: 2.9.0**
**使用框架: React**

### 复现步骤
从1.3.45升级到2.2.11  按迁移文档的配置来的  
   npm run dev:weapp报错 

### 期望结果
能正常运行

### 实际结果
⠦ 正在编译...events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8888
    at Server.setupListenHandle [as _listen2] (net.js:1286:14)
    at listenInCluster (net.js:1334:12)
    at doListen (net.js:1460:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)

### 环境信息
```
Taro CLI 2.2.11 environment info:
    System:
      OS: macOS 10.15
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 2.2.11 => 2.2.11 
      @tarojs/components: 2.2.11 => 2.2.11 
      @tarojs/components-qa: 2.2.11 => 2.2.11 
      @tarojs/mini-runner: 2.2.11 => 2.2.11 
      @tarojs/mobx: 2.2.11 => 2.2.11 
      @tarojs/mobx-h5: 2.2.11 => 2.2.11 
      @tarojs/mobx-rn: 2.2.11 => 2.2.11 
      @tarojs/plugin-babel: 2.2.11 => 2.2.11 
      @tarojs/plugin-csso: 2.2.11 => 2.2.11 
      @tarojs/plugin-sass: 2.2.11 => 2.2.11 
      @tarojs/plugin-terser: 2.2.11 => 2.2.11 
      @tarojs/rn-runner: 2.2.11 => 2.2.11 
      @tarojs/router: 2.2.11 => 2.2.11 
      @tarojs/taro: 2.2.11 => 2.2.11 
      @tarojs/taro-alipay: 2.2.11 => 2.2.11 
      @tarojs/taro-h5: 2.2.11 => 2.2.11 
      @tarojs/taro-swan: 2.2.11 => 2.2.11 
      @tarojs/taro-tt: 2.2.11 => 2.2.11 
      @tarojs/taro-weapp: 2.2.11 => 2.2.11 
      @tarojs/webpack-runner: 2.2.11 => 2.2.11 
      eslint-config-taro: 2.2.11 => 2.2.11 
      eslint-plugin-taro: 2.2.11 => 2.2.11 
      nerv-devtools: ^1.5.7 => 1.5.7 
      nervjs: ^1.5.7 => 1.5.7 
      stylelint-config-taro-rn: 2.2.11 => 2.2.11 
      stylelint-taro-rn: 2.2.11 => 2.2.11 
      taro-ui: 2.3.1 => 2.3.1 
```

**Comment by ywanhzy** [comment]
是使用了webpack-bundle-analyzer 插件  才报错的   
 mini: {
    webpackChain (chain, webpack) {
      chain.plugin('analyzer')
        .use(require('webpack-bundle-analyzer').BundleAnalyzerPlugin, [])
    }
  }
找不到啥原因

**Comment by luckyadam** [comment]
端口冲突了，换个端口就行
