### ISSUE TITLE
快应用代码运行正常，真机扫码报错

### ISSUE THREAD

**Issue by jiongrui** [NervJS/taro#7205]
### 相关平台
快应用

**小程序基础库: 1070**
**使用框架: React**

### 复现步骤
yarn dev:quickapp  之后，扫码真机调试，报错

### 期望结果
正常运行

### 实际结果
webpack-internal:///../../node_modules/@tarojs/taro/dist/index.esm.js:2303: ReferenceError: process is not defined
ReferenceError: process is not defined
    at eval (webpack-internal:///../../node_modules/@tarojs/taro/dist/index.esm.js:2303:1)
    at Object.../../node_modules/@tarojs/taro/dist/index.esm.js (pages/index/index.js:124:1)
    at __webpack_require__ (pages/index/index.js:23:30)
    at eval (webpack-internal:///../../node_modules/@tarojs/taro-quickapp/dist/index.js:11:12)
    at Object.../../node_modules/@tarojs/taro-quickapp/dist/index.js (pages/index/index.js:100:1)
    at __webpack_require__ (pages/index/index.js:23:30)
    at eval (webpack-internal:///../../node_modules/@tarojs/taro-quickapp/index.js:3:18)
    at Object.../../node_modules/@tarojs/taro-quickapp/index.js (pages/index/index.js:112:1)
    at __webpack_require__ (pages/index/index.js:23:30)
    at __scriptModule__ (webpack-internal:///./node_modules/@hap-toolkit/dsl-xvm/lib/loaders/script-loader.js!./node_modules/@hap-toolkit/dsl-xvm/lib/loaders/module-loader.js!./node_modules/babel-loader/lib/index.js?cwd=/Users/cai/Documents/codes/lookboard/dist/quickapp&cacheDirectory&plugins[]=/Users/cai/Documents/codes/lookboard/dist/quickapp/node_modules/@hap-toolkit/dsl-xvm/lib/loaders/babel-plugin-jsx.js&comments=false!./node_modules/@hap-toolkit/dsl-xvm/lib/loaders/fragment-loader.js?index=0&type=script!./src/npm/@tarojs/components-qa/src/components/taro-page/index.ux?uxType=comp:8:44)
com.eclipsesource.v8.V8ScriptExecutionException
	at com.eclipsesource.v8.V8._executeVoidFunction(Native Method)
	at com.eclipsesource.v8.V8.executeVoidFunction(SourceFile:1154)
	at com.eclipsesource.v8.V8Object.executeVoidFunction(SourceFile:435)
	at org.hapjs.render.jsruntime.JsThread.b(SourceFile:963)
	at org.hapjs.render.jsruntime.JsThread.a(SourceFile:82)
	at org.hapjs.render.jsruntime.JsThread$a.handleMessage(SourceFile:264)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.os.HandlerThread.run(HandlerThread.java:65)

### 环境信息
```
👽 Taro v3.0.6


  Taro CLI 3.0.6 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    npmPackages:
      @tarojs/cli: 2.0.6 => 2.0.6 
      @tarojs/components: 2.0.6 => 2.0.6 
      @tarojs/mini-runner: 2.0.6 => 2.0.6 
      @tarojs/router: 2.0.6 => 2.0.6 
      @tarojs/taro: 2.0.6 => 2.0.6 
      @tarojs/taro-h5: 2.0.6 => 2.0.6 
      @tarojs/webpack-runner: 2.0.6 => 2.0.6 
      eslint-config-taro: 2.0.6 => 2.0.6 
      eslint-plugin-taro: 2.0.6 => 2.0.6 
      nerv-devtools: ^1.5.6 => 1.5.7 
      nervjs: ^1.5.6 => 1.5.7
```

**Comment by luckyadam** [comment]
3.x 还没有支持快应用，可以用 2.2.11 版本～

**Comment by jiongrui** [comment]
> 3.x 还没有支持快应用，可以用 2.2.11 版本～

用了2.2.1.1版本，还是一样的报错

```
👽 Taro v2.2.11


  Taro CLI 2.2.11 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    npmPackages:
      @tarojs/cli: 2.2.11 => 2.2.11 
      @tarojs/components: 2.2.11 => 2.2.11 
      @tarojs/components-qa: 2.2.11 => 2.2.11 
      @tarojs/mini-runner: 2.2.11 => 2.2.11 
      @tarojs/plugin-sass: ^2.2.10 => 2.2.10 
      @tarojs/router: 2.2.11 => 2.2.11 
      @tarojs/taro: 2.2.11 => 2.2.11 
      @tarojs/taro-alipay: 2.2.11 => 2.2.11 
      @tarojs/taro-h5: 2.2.11 => 2.2.11 
      @tarojs/taro-qq: 2.2.11 => 2.2.11 
      @tarojs/taro-quickapp: 2.2.11 => 2.2.11 
      @tarojs/taro-rn: 2.2.11 => 2.2.11 
      @tarojs/taro-swan: 2.2.11 => 2.2.11 
      @tarojs/taro-tt: 2.2.11 => 2.2.11 
      @tarojs/taro-weapp: 2.2.11 => 2.2.11 
      @tarojs/webpack-runner: 2.2.11 => 2.2.11 
      eslint-config-taro: 2.2.11 => 2.2.11 
      eslint-plugin-taro: 2.2.11 => 2.2.11 
      nerv-devtools: ^1.5.7 => 1.5.7 
      nervjs: ^1.5.7 => 1.5.7 
      stylelint-config-taro-rn: 2.2.11 => 2.2.11 
      stylelint-taro-rn: 2.2.11 => 2.2.11 

```

**Comment by xiaopanshi** [comment]
同问

**Comment by jiongrui** [comment]
这个问题是修复不了了吗，提了好久了。看别人之前也提过了。 @luckyadam

**Comment by xieyihao** [comment]
同问，尝试过taro/cli 2.2.7和2.2.15 2个版本，node v10.15.0 在快应用真机调试直接出错了，提示webpack-internal:///../../node_modules/@tarojs/taro/dist/index.esm.js:2303: ReferenceError: process is not defined
ReferenceError: process is not defined

**Comment by xieyihao** [comment]
“快应用预览版”降级为1.4.0可避免此报错“process is not defined”。

**Comment by hexiaochun** [comment]
> 3.x 还没有支持快应用，可以用 2.2.11 版本～

@luckyadam 为啥3.x不支持快应用啊，是没有计划支持还是有什么问题
