### ISSUE TITLE
执行npm run build:H5打包报错

### ISSUE THREAD

**Issue by yuy1guo** [NervJS/taro#7457]
### 相关平台
H5

**浏览器版本: chrome62**
**使用框架: React**

### 复现步骤
1.执行npm run build:h5
2.报错
```

缺少 app 全局配置，请检查！


缺少 app 全局配置，请检查！


Error: 缺少 app 全局配置，请检查！
    at MainPlugin.getAppConfig (D:\ynhtBank\project\smartLoan\SmartLoan_Salary\node_modules\@tarojs\webpack-runner\dist\plugins\MainPlugin.js:140:19)
    at MainPlugin.run (D:\ynhtBank\project\smartLoan\SmartLoan_Salary\node_modules\@tarojs\webpack-runner\dist\plugins\MainPlugin.js:79:14)
    at compiler.hooks.run.tapAsync.tryAsync (D:\ynhtBank\project\smartLoan\SmartLoan_Salary\node_modules\@tarojs\webpack-runner\dist\plugins\MainPlugin.js:42:18)
    at MainPlugin.<anonymous> (D:\ynhtBank\project\smartLoan\SmartLoan_Salary\node_modules\@tarojs\webpack-runner\dist\plugins\MainPlugin.js:22:23)
    at Generator.next (<anonymous>)
    at D:\ynhtBank\project\smartLoan\SmartLoan_Salary\node_modules\@tarojs\webpack-runner\dist\plugins\MainPlugin.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\ynhtBank\project\smartLoan\SmartLoan_Salary\node_modules\@tarojs\webpack-runner\dist\plugins\MainPlugin.js:4:12)
    at D:\ynhtBank\project\smartLoan\SmartLoan_Salary\node_modules\@tarojs\webpack-runner\dist\plugins\MainPlugin.js:20:50
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\ynhtBank\project\smartLoan\SmartLoan_Salary\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (D:\ynhtBank\project\smartLoan\SmartLoan_Salary\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.beforeRun.callAsync.err (D:\ynhtBank\project\smartLoan\SmartLoan_Salary\node_modules\webpack\lib\Compiler.js:315:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\ynhtBank\project\smartLoan\SmartLoan_Salary\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (D:\ynhtBank\project\smartLoan\SmartLoan_Salary\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.run (D:\ynhtBank\project\smartLoan\SmartLoan_Salary\node_modules\webpack\lib\Compiler.js:312:24)
    at Promise (D:\ynhtBank\project\smartLoan\SmartLoan_Salary\node_modules\@tarojs\webpack-runner\dist\index.js:50:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mebi_client@1.0.0 build:h5: `taro build --type h5`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mebi_client@1.0.0 build:h5 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-08-27T06_42_01_767Z-debug.log
``` 

### 期望结果
正常打包

### 实际结果
报错

### 环境信息
```
👽 Taro v1.3.27


  Taro CLI 1.3.27 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.19.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.0 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
版本为V1.3.27 版本选择无法选择此项了。

**Comment by luckyadam** [comment]
CLI 和项目依赖版本保持一致
