### ISSUE TITLE
Redmi k30 pro变焦版 今日头条 app 打开taro创建的小程序报错

### ISSUE THREAD

**Issue by raoxb** [NervJS/taro#7471]
### 相关平台
字节跳动小程序

**小程序基础库: 1.75.0.9**
**使用框架: React**

### 复现步骤
打不开小程序，报错详情

tma-core.js:17 t: Cannot assign to read only property 'onLaunch' of object '#<Object>'
    at tma-core.js:1:261569
    at q_ (tma-core.js:1:149034)
    at ew (tma-core.js:1:150720)
    at new e (tma-core.js:1:261516)
    at App (tma-core.js:17:56759)
    at Module.69 (app.js:4:93347)
    at l (runtime.js:2:563)
    at r (runtime.js:2:432)
    at Array.t [as push] (runtime.js:2:295)
    at app.js:4:125
tP.forEach.console.(anonymous function) @ tma-core.js:17

tma-core.js:17 t: Cannot read property 'mount' of undefined
    at Object.mount (taro.js:3:55584)
    at Object.onLoad (taro.js:3:49728)
    at tryCatch (tma-core.js:1:265097)
    at t.n.callMethod (tma-core.js:1:271028)
    at t.n.callLifetime (tma-core.js:1:271290)
    at t.n.onLoad (tma-core.js:1:270103)
    at cA (tma-core.js:1:288785)
    at tma-core.js:1:287033
    at aA (tma-core.js:1:287043)
    at PS.hA (tma-core.js:1:289918)

### 期望结果
可以正常打开

### 实际结果
打开小程序报错

### 环境信息
```
 Taro v3.0.7


  Taro CLI 3.0.7 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.7 => 3.0.7
      @tarojs/mini-runner: 3.0.7 => 3.0.7
      @tarojs/react: 3.0.7 => 3.0.7
      @tarojs/runtime: 3.0.7 => 3.0.7
      @tarojs/taro: 3.0.7 => 3.0.7
      @tarojs/webpack-runner: 3.0.7 => 3.0.7
      babel-preset-taro: 3.0.7 => 3.0.7
      eslint-config-taro: 3.0.7 => 3.0.7
      react: ^16.10.0 => 16.13.1
```

**Comment by taajason** [comment]
不止是Redmi k30 pro变焦版，小米手机，华为真机都出现了该问题

**Comment by taajason** [comment]
@Chen-jj

**Comment by taajason** [comment]
用官方 react demo 可以复现，相关版本和工具已升级到最新

**Comment by Chen-jj** [comment]
@raoxb @taajason 这个 [PR](https://github.com/NervJS/taro/pull/7438/files) 把小程序配置 Object 的 writable 设置为 true 了，猜测是同一个问题，可以等这周中发了下一个版本后再试试。

**Comment by wasabia** [comment]
还没有修复啊

**Comment by MR-L-2015** [comment]
更新Taro 版本，重新编译，可以修复这个BUG。测试3.0.10可以搞定。

最新版本
npm install -g @tarojs/cli
或某个版本
npm install -g @tarojs/cli@3.0.10

在工程目录内运行
taro update project 3.0.10

然后编译，问题解决。
