### ISSUE TITLE
头条小程序运行报错：Cannot read property 'code' of undefined

### ISSUE THREAD

**Issue by Fangsiyu** [NervJS/taro#7480]
### 相关平台
字节跳动小程序

**小程序基础库: 1.75.0.9**
**使用框架: Vue 2**

### 复现步骤
打开头条小程序开发工具即出现报错，实际没有  ./base 文件

### 期望结果
正常运行

### 实际结果
in file ./pages/home/index

Error:

in file ./base

./utils.wxs not found:
> 1 | <wxs module="xs" src="./utils.wxs" />
    |                       ^
  2 | <template name="taro_tmpl">
  3 |   <block wx:for="{{root.cn}}" wx:key="id">
  4 |     <template is="tmpl_0_container" data="{{i: item}}" />
TypeError: Cannot read property 'code' of undefined
    at currentPageBuild (C:\Users\onlyf\AppData\Local\Programs\bytedanceide\resources\app.asar.unpacked\node_modules\byted-tma-pack\dest\worker.js:1:144177)
    at CallExpression (C:\Users\onlyf\AppData\Local\Programs\bytedanceide\resources\app.asar.unpacked\node_modules\byted-tma-pack\dest\worker.js:1:144450)
    at NodePath._call (C:\Users\onlyf\AppData\Local\Programs\bytedanceide\resources\app.asar\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Users\onlyf\AppData\Local\Programs\bytedanceide\resources\app.asar\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\Users\onlyf\AppData\Local\Programs\bytedanceide\resources\app.asar\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (C:\Users\onlyf\AppData\Local\Programs\bytedanceide\resources\app.asar\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (C:\Users\onlyf\AppData\Local\Programs\bytedanceide\resources\app.asar\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (C:\Users\onlyf\AppData\Local\Programs\bytedanceide\resources\app.asar\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (C:\Users\onlyf\AppData\Local\Programs\bytedanceide\resources\app.asar\node_modules\babel-traverse\lib\index.js:114:17)
    at NodePath.visit (C:\Users\onlyf\AppData\Local\Programs\bytedanceide\resources\app.asar\node_modules\babel-traverse\lib\path\context.js:115:19)

### 环境信息
```
Taro v3.0.8


  Taro CLI 3.0.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.3 - D:\Program Files\nodejs\node.EXE
      npm: 6.14.6 - D:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
运行头条就出现问题，头条开发工具2.0.1版本

**Comment by Chen-jj** [comment]
@Fangsiyu 怎样复现？我用 3.0.8 创建 vue2 项目没有复现。dist/base.ttml 没有发现引用了微信小程序的 wxs：

![image](https://user-images.githubusercontent.com/11807297/91732111-5df5a900-ebda-11ea-9b6f-6cb3c94dd029.png)

**Comment by Fangsiyu** [comment]
> @Fangsiyu 怎样复现？我用 3.0.8 创建 vue2 项目没有复现。dist/base.ttml 没有发现引用了微信小程序的 wxs：
> 
> ![image](https://user-images.githubusercontent.com/11807297/91732111-5df5a900-ebda-11ea-9b6f-6cb3c94dd029.png)

目前不知道怎么重现，这个挺不好搞出来，还有这个报错，你圈出来文件这边也是有的
`in file ./pages/home/index

Error:

in file ./base

./utils.wxs not found:
> 1 | <wxs module="xs" src="./utils.wxs" />
    |                       ^
  2 | <template name="taro_tmpl">
  3 |   <block wx:for="{{root.cn}}" wx:key="id">
  4 |     <template is="tmpl_0_container" data="{{i: item}}" />`

**Comment by Chen-jj** [comment]
@Fangsiyu 偶现还是必现，必现的话你扔个项目就行了。

**Comment by Fangsiyu** [comment]
> @Fangsiyu 偶现还是必现，必现的话你扔个项目就行了。

[初步怀疑是build头条的项目，base.ttml 第一行里面引入了 <wxs module="xs" src="./utils.wxs" /> 这个导致的，但是项目里面没有这个文件，这个是微信小程序里面的

**Comment by Chen-jj** [comment]
没有代码无法定位

**Comment by Fangsiyu** [comment]
> 没有代码无法定位

嗯嗯，目前只在我这项目里面出现，等等在看，不清楚为什么我这边编译后的 base.ttml 文件第一行会出现引入微信小程序的文件问题<wxs module="xs" src="./utils.wxs" />

**Comment by lzs2000131** [comment]
我也出现了这种情况，是飞书小程序，应该跟字节跳动小程序是一个平台。编译生成的comp.ttml里面import了base.wxml，但实际应该是base.ttml，生成的base.ttml第一行import了 utils.wxs，会报错。手动更改掉这两处错误后可以正常运行
