### ISSUE TITLE
taro next 没升级的小伙伴别升级了，全是坑！！！！！！！

### ISSUE THREAD

**Issue by ztfstar** [NervJS/taro#7513]
### 相关平台
微信小程序

**小程序基础库: 2.5.2**
**使用框架: React**

### 复现步骤
yarn build:weapp报错：
TypeError: Cannot read property 'uglify' of undefined

### 期望结果
正常运行

### 实际结果
无法正常运行

### 环境信息
```
aro CLI 3.0.8 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.8 => 3.0.8 
      @tarojs/components: 3.0.8 => 3.0.8 
      @tarojs/mini-runner: 3.0.8 => 3.0.8 
      @tarojs/react: 3.0.8 => 3.0.8 
      @tarojs/router: 3.0.8 => 3.0.8 
      @tarojs/runtime: 3.0.8 => 3.0.8 
      @tarojs/taro: 3.0.8 => 3.0.8 
      @tarojs/taro-h5: 3.0.8 => 3.0.8 
      @tarojs/webpack-runner: 3.0.8 => 3.0.8 
      eslint-config-taro: 3.0.8 => 3.0.8 
      eslint-plugin-taro: 3.0.8 => 3.0.8 
      nerv-devtools: ^1.5.7 => 1.5.7 
      nervjs: ^1.5.7 => 1.5.7 
      react: ^16.13.1 => 16.13.1 
      taro-ui: ^2.2.4 => 2.2.4 
```

**Comment by luckyadam** [comment]
升级指南不好好看能怪谁呢

**Comment by zzh3319** [comment]
全是坑

**Comment by luckyadam** [comment]
> 全是坑

倒是把坑说出来看看

**Comment by Chen-jj** [comment]
https://nervjs.github.io/taro/docs/next/migration
https://aotu.io/notes/2020/08/31/taro-versions/
先看文档吧，文档有遗漏再提出来

**Comment by zzh3319** [comment]
请问  taro3.0.7  ts+dva    run dev的时候 页面  微信小程序报错   h5正常是什么原因

**Comment by zzh3319** [comment]
VM13:1 Invariant Violation: Could not find "store" in either the context or props of "Connect(Detail)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Detail)".
    at invariant (http://127.0.0.1:31726/appservice/vendors.js:8969:15)
    at new Connect (http://127.0.0.1:31726/appservice/vendors.js:6163:57)
    at Zc (http://127.0.0.1:31726/appservice/vendors.js:11275:171)
    at xe (http://127.0.0.1:31726/appservice/vendors.js:11314:149)
    at ig (http://127.0.0.1:31726/appservice/vendors.js:11392:396)
    at hg (http://127.0.0.1:31726/appservice/vendors.js:11369:22)
    at bg (http://127.0.0.1:31726/appservice/vendors.js:11368:366)
    at Of (http://127.0.0.1:31726/appservice/vendors.js:11362:214)
    at http://127.0.0.1:31726/appservice/vendors.js:11260:115
    at push../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority (http://127.0.0.1:31726/appservice/vendors.js:15090:438)

**Comment by luckyadam** [comment]
麻烦重新提个 issue，附个 demo 看看
