### ISSUE TITLE
代码运行成微信小程序报错了  运行成H5页面不会报错 

### ISSUE THREAD

**Issue by zzh3319** [NervJS/taro#7514]
![4BF75741-7251-4d0f-A53C-278BCC6A7503](https://user-images.githubusercontent.com/17757491/92092263-70532b00-ee04-11ea-8dab-5319b495aaf9.png)
![AABDD588-B436-4031-A3A2-491603008F04](https://user-images.githubusercontent.com/17757491/92092205-5dd8f180-ee04-11ea-9681-11b86a330a6f.png)
![167B9CEB-2C43-47cf-A1F2-D89F97E64586](https://user-images.githubusercontent.com/17757491/92092526-cb851d80-ee04-11ea-9e44-4c286aa6fadf.png)

### 相关平台
微信小程序

### 复现仓库
[https://github.com/zzh3319/taro-dva-ts.git](https://github.com/zzh3319/taro-dva-ts.git)
**小程序基础库: 2.12.2**
**使用框架: React**

### 复现步骤
taro3.0.7+ts+dva   直接代码运行成小程序报错了  运行成H5页面不会报错 

### 期望结果
小程序正常

### 实际结果
2VM13:1 Invariant Violation: Could not find "store" in either the context or props of "Connect(Detail)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Detail)".
    at invariant (http://127.0.0.1:31726/appservice/vendors.js:9036:15)
    at new Connect (http://127.0.0.1:31726/appservice/vendors.js:6132:57)
    at constructClassInstance (http://127.0.0.1:31726/appservice/vendors.js:15281:18)
    at updateClassComponent (http://127.0.0.1:31726/appservice/vendors.js:19490:5)
    at beginWork$1 (http://127.0.0.1:31726/appservice/vendors.js:21257:16)
    at Object.invokeGuardedCallbackImpl (http://127.0.0.1:31726/appservice/vendors.js:22850:10)
    at invokeGuardedCallback (http://127.0.0.1:31726/appservice/vendors.js:23027:31)
    at beginWork$$1 (http://127.0.0.1:31726/appservice/vendors.js:27056:7)
    at performUnitOfWork (http://127.0.0.1:31726/appservice/vendors.js:25983:12)
    at workLoopSync (http://127.0.0.1:31726/appservice/vendors.js:25956:22)
console.warn @ VM13:1
VM13:1 
    in Connect(Detail) (created by Page)
    in root (created by Page)
    in Page (created by AppWrapper)
    in Provider (created by App)
    in App (created by AppWrapper)
    in AppWrapper

### 环境信息
```
� Taro v3.0.8


  Taro CLI 3.0.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.5.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\75488\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
2VM13:1 Invariant Violation: Could not find "store" in either the context or props of "Connect(Detail)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Detail)".
    at invariant (http://127.0.0.1:31726/appservice/vendors.js:9036:15)
    at new Connect (http://127.0.0.1:31726/appservice/vendors.js:6132:57)
    at constructClassInstance (http://127.0.0.1:31726/appservice/vendors.js:15281:18)
    at updateClassComponent (http://127.0.0.1:31726/appservice/vendors.js:19490:5)
    at beginWork$1 (http://127.0.0.1:31726/appservice/vendors.js:21257:16)
    at Object.invokeGuardedCallbackImpl (http://127.0.0.1:31726/appservice/vendors.js:22850:10)
    at invokeGuardedCallback (http://127.0.0.1:31726/appservice/vendors.js:23027:31)
    at beginWork$$1 (http://127.0.0.1:31726/appservice/vendors.js:27056:7)
    at performUnitOfWork (http://127.0.0.1:31726/appservice/vendors.js:25983:12)
    at workLoopSync (http://127.0.0.1:31726/appservice/vendors.js:25956:22)
console.warn @ VM13:1
VM13:1 
    in Connect(Detail) (created by Page)
    in root (created by Page)
    in Page (created by AppWrapper)
    in Provider (created by App)
    in App (created by AppWrapper)
    in AppWrapper

**Comment by zzh3319** [comment]
@Chen-jj   i need you help

**Comment by zzh3319** [comment]
@Li,Weitao  i need you help

**Comment by zzh3319** [comment]
@luckyadam     i need you help

**Comment by Chen-jj** [comment]
@zzh3319 应该是 react-redux 版本问题，dva 依赖 5.x，最新的 7.x 没问题。你直接从 react-redux 取 connect 就可以跑了。

**Comment by zzh3319** [comment]
@Chen-jj  请问是怎么发现的。

**Comment by TujinLee** [comment]
> @zzh3319 应该是 react-redux 版本问题，dva 依赖 5.x，最新的 7.x 没问题。你直接从 react-redux 取 connect 就可以跑了。

刚升级了taro3，dva core是2.06，就是在模拟器请求运行啥的都正常，到手机上就请求报错了
