### ISSUE TITLE
taro update 3.0.9版本之后，npm run dev:weapp报错，并且启动服务 展示的是taro v3.0.7版本

### ISSUE THREAD

**Issue by wkh2** [NervJS/taro#7540]
### 相关平台
微信小程序

### 复现仓库
[https://git.jd.com/apollo-fe/apl-taro-example.git](https://git.jd.com/apollo-fe/apl-taro-example.git)
**小程序基础库: 2.3.1**
**使用框架: React**

### 复现步骤
```
1、首先全局安装新版本 npm i @tarojs/cli -g
2、安装成功之后在一个非3.0.9版本的项目中，将3.0.7 修改为3.0.9，执行npm install
3、安装依赖成功之后，确认node_modules 中taro升级依赖的版本，确认已经为3.0.9版本
4、执行npm run dev:weapp
5、报错⠸ 正在编译...Cannot read property 'buildTemplate' of undefined
6、rm -rf node_modules package-lock.json
7、npm install
8、npm run dev:weapp
9、继续报错 正在编译...Cannot read property 'buildTemplate' of undefined
```

### 期望结果
编译成功，正常启动服务

### 实际结果
```
正在编译...Cannot read property 'buildTemplate' of undefined


Cannot read property 'buildTemplate' of undefined


(node:53496) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'buildTemplate' of undefined
    at TaroMiniPlugin.<anonymous> (/Users/wanghui36/workspace/apollo/taro-components/apl-taro-example/node_modules/@tarojs/mini-runner/src/plugins/MiniPlugin.ts:628:71)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/wanghui36/workspace/apollo/taro-components/apl-taro-example/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:53496) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:53496) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠧ 正在编译...

```

### 环境信息
```
👽 Taro v3.0.9


  Taro CLI 3.0.9 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.7 - /usr/local/bin/zsh
    Binaries:
      Node: 10.15.2 - ~/.nvm/versions/node/v10.15.2/bin/node
      Yarn: 1.19.1 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v10.15.2/bin/npm
    npmPackages:
      @tarojs/components: 3.0.9 => 3.0.9 
      @tarojs/mini-runner: 3.0.9 => 3.0.9 
      @tarojs/react: 3.0.9 => 3.0.9 
      @tarojs/runtime: 3.0.9 => 3.0.9 
      @tarojs/taro: 3.0.9 => 3.0.9 
      @tarojs/webpack-runner: 3.0.9 => 3.0.9 
      babel-preset-taro: 3.0.9 => 3.0.9 
      eslint-config-taro: 3.0.9 => 3.0.9 
      react: ^16.10.0 => 16.13.1 
    npmGlobalPackages:
      typescript: 3.7.2

```

---
### 补充信息
小程序端都有有问题，如 npm run dev:tt

**Comment by wkh2** [comment]
如截图
![image](https://user-images.githubusercontent.com/19984871/92348788-afd08e80-f106-11ea-9f32-f5542c016ac5.png)

![image](https://user-images.githubusercontent.com/19984871/92348818-cf67b700-f106-11ea-9ffd-6524455e1f95.png)

**Comment by allendongyx** [comment]
把node_modules 全部删除一遍试试~ 
检查install 是否有报错，然后可以用淘宝源安装

**Comment by wkh2** [comment]
需要在项目本地安装 tarojs/cli

**Comment by zoushenglin** [comment]
楼上正解
