### ISSUE TITLE
taro init 创建一个项目后运行 dev:weapp 报错

### ISSUE THREAD

**Issue by clk528** [NervJS/taro#7559]
### 相关平台
微信小程序

**小程序基础库: 2.13.0**
**使用框架: Vue 2**

### 复现步骤
# 创建项目
```shell
taro init writing-seasons-applet --no-typescript
👽 Taro v3.0.9

Taro 即将创建一个新项目!
Need help? Go and open issue: https://tls.jd.com/taro-issue-helper

? 请输入项目介绍！
? 请选择框架 Vue
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板源 Gitee（最快）
✔ 拉取远程模板仓库成功！
? 请选择模板 default-youshu
```

# 运行项目
```shell
npm run dev:weapp
```

### 期望结果
正常运行

### 实际结果
```shell
 /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run dev:weapp --scripts-prepend-node-path=auto

> writing-seasons-applet@1.0.0 dev:weapp /Users/clk/Documents/project/qiadao/sxsj/writing-seasons-applet
> npm run build:weapp -- --watch


> writing-seasons-applet@1.0.0 build:weapp /Users/clk/Documents/project/qiadao/sxsj/writing-seasons-applet
> taro build --type weapp "--watch"

👽 Taro v3.0.9

Tips: 预览模式生成的文件较大，设置 NODE_ENV 为 production 可以开启压缩。
Example:
$ NODE_ENV=production taro build --type weapp --watch

生成  工具配置  /Users/clk/Documents/project/qiadao/sxsj/writing-seasons-applet/dist/project.config.json
(node:93114) UnhandledPromiseRejectionWarning: /Users/clk/Documents/project/qiadao/sxsj/writing-seasons-applet/node_modules/terser-webpack-plugin/node_modules/p-limit/index.js:30
                } catch {}
                        ^

SyntaxError: Unexpected token {
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Module._compile (/usr/local/lib/node_modules/@tarojs/cli/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (module.js:660:10)
    at Object.newLoader [as .js] (/usr/local/lib/node_modules/@tarojs/cli/node_modules/pirates/lib/index.js:104:7)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/clk/Documents/project/qiadao/sxsj/writing-seasons-applet/node_modules/terser-webpack-plugin/dist/index.js:26:38)
    at Module._compile (module.js:649:30)
    at Module._compile (/usr/local/lib/node_modules/@tarojs/cli/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (module.js:660:10)
(node:93114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:93114) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by luckyadam** [comment]
没有复现哦，建议重新安装一下依赖
![image](https://user-images.githubusercontent.com/1782542/92548019-91929c00-f288-11ea-81b1-c21e091b4ee3.png)
![image](https://user-images.githubusercontent.com/1782542/92548040-9bb49a80-f288-11ea-8be6-09711dd86426.png)

**Comment by clk528** [comment]
> 没有复现哦，建议重新安装一下依赖
> ![image](https://user-images.githubusercontent.com/1782542/92548019-91929c00-f288-11ea-81b1-c21e091b4ee3.png)
> ![image](https://user-images.githubusercontent.com/1782542/92548040-9bb49a80-f288-11ea-8be6-09711dd86426.png)

我刚刚试了下，我使用typescript选项创建的项目，是可以运行成功的。我是创建项目 添加了 `--no-typescript` 选项。最后生成的项目是跑不成功的。

```shell
👽 Taro v3.0.9


  Taro CLI 3.0.9 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
      npm: 6.14.5 - ~/.nvm/versions/node/v12.10.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.9 => 3.0.9 
      @tarojs/components: 3.0.9 => 3.0.9 
      @tarojs/mini-runner: 3.0.9 => 3.0.9 
      @tarojs/runtime: 3.0.9 => 3.0.9 
      @tarojs/taro: 3.0.9 => 3.0.9 
      @tarojs/webpack-runner: 3.0.9 => 3.0.9 
      babel-preset-taro: 3.0.9 => 3.0.9 
      eslint-config-taro: 3.0.9 => 3.0.9 
```
