### ISSUE TITLE
taro convert转换报错

### ISSUE THREAD

**Issue by hipig** [NervJS/taro#7618]
### 相关平台
微信小程序

**小程序基础库: 2.12.2 无关小程序基础库版本**
**使用框架: Vue 2**

### 复现步骤
taro convert

### 期望结果
所有页面转换成功

### 实际结果
报错导致未完全转换成功，部分页面未转换成功

### 环境信息
```

  Taro CLI 3.0.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.3 - E:\laragon\bin\nodejs\node-v12.18.3-win-x64\node.EXE
      npm: 6.14.6 - E:\laragon\bin\nodejs\node-v12.18.3-win-x64\npm.CMD
```

---
### 补充信息
``` Shell
TypeError: Cannot read property 'tokens' of undefined
    at new Generator (E:\laragon\bin\nodejs\node-v12.18.3-win-x64\node_modules\@tarojs\cli\node_modules\better-babel-generator\lib\index.js:55:22)
    at Object.exports.default (E:\laragon\bin\nodejs\node-v12.18.3-win-x64\node_modules\@tarojs\cli\node_modules\better-babel-generator\lib\index.js:23:13)
    at Object.generateMinimalEscapeCode (E:\laragon\bin\nodejs\node-v12.18.3-win-x64\node_modules\@tarojs\cli\src\util\astConvert.ts:36:18)
    at E:\laragon\bin\nodejs\node-v12.18.3-win-x64\node_modules\@tarojs\cli\src\convertor\index.ts:334:68
    at Array.forEach (<anonymous>)
    at exit (E:\laragon\bin\nodejs\node-v12.18.3-win-x64\node_modules\@tarojs\cli\src\convertor\index.ts:326:23)
    at NodePath._call (E:\laragon\bin\nodejs\node-v12.18.3-win-x64\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (E:\laragon\bin\nodejs\node-v12.18.3-win-x64\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (E:\laragon\bin\nodejs\node-v12.18.3-win-x64\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:117:8)
    at TraversalContext.visitQueue (E:\laragon\bin\nodejs\node-v12.18.3-win-x64\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\context.js:150:16)
```

**Comment by Chen-jj** [comment]
暂不支持转换为 Vue #7618
