### ISSUE TITLE
taro 选择微信小程序插件模板，尝试编译，直接报错

### ISSUE THREAD

**Issue by ahv5aw5n** [NervJS/taro#7636]
### 相关平台
微信小程序

**小程序基础库: 2.12.2**
**使用框架: React**

### 复现步骤
1、初始化 `taro init taro-plugin`

? 请输入项目介绍！

? 请选择框架 React

? 是否需要使用 TypeScript ？ No

? 请选择 CSS 预处理器（Sass/Less/Stylus） Less

? 请选择模板源 Github（最新）

✔ 拉取远程模板仓库成功！

? 请选择模板 wxplugin（小程序插件模板）

2、进入项目目录，修改project.config.json 和 src/app.jsx 的config中的appid，然后执行 `taro build --plugin weapp --watch`

3、错误输出

```bash
👽 Taro v3.0.10

开始编译微信小程序插件
Tips: 预览模式生成的文件较大，设置 NODE_ENV 为 production 可以开启压缩。
Example:
$ NODE_ENV=production taro build --type weapp --watch

生成  工具配置  /Users/这里省略n级目录/taro/taro-plugin/miniprogram/project.config.json
(node:19799) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at TaroMiniPlugin.getAppEntry (/Users/这里省略n级目录/taro/taro-plugin/node_modules/@tarojs/mini-runner/src/plugins/MiniPlugin.ts:299:56)
    at TaroMiniPlugin.apply (/Users/这里省略n级目录/taro/taro-plugin/node_modules/@tarojs/mini-runner/src/plugins/MiniPlugin.ts:143:26)
    at webpack (/Users/这里省略n级目录/taro/taro-plugin/node_modules/webpack/lib/webpack.js:51:13)
    at /Users/这里省略n级目录/taro/taro-plugin/node_modules/@tarojs/mini-runner/src/index.ts:40:22
    at new Promise (<anonymous>)
    at /Users/这里省略n级目录/taro/taro-plugin/node_modules/@tarojs/mini-runner/src/index.ts:39:10
    at Generator.next (<anonymous>)
    at fulfilled (/Users/这里省略n级目录/taro/taro-plugin/node_modules/@tarojs/mini-runner/dist/index.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:19799) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:19799) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### 期望结果
成功编译出小程序插件

### 实际结果
报错，退出编译

### 环境信息
```
👽 Taro v3.0.10


  Taro CLI 3.0.10 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.12.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.10 => 3.0.10
      @tarojs/mini-runner: 3.0.10 => 3.0.10
      @tarojs/react: 3.0.10 => 3.0.10
      @tarojs/runtime: 3.0.10 => 3.0.10
      @tarojs/taro: 3.0.10 => 3.0.10
      @tarojs/webpack-runner: 3.0.10 => 3.0.10
      babel-preset-taro: 3.0.10 => 3.0.10
      eslint-config-taro: 3.0.10 => 3.0.10
      react: ^16.10.0 => 16.13.1
    npmGlobalPackages:
      typescript: 3.5.3
```

**Comment by hugly** [comment]
我也遇到了  你解决没有？

**Comment by ahv5aw5n** [comment]
> 我也遇到了 你解决没有？

v3没有解决，使用Taro2正常

**Comment by tomzio** [comment]
通过wxplugin模板生成的代码中有一个pkg文件，将文件名改成package.json就正常了，可能是通过模板生成的文件名写错了。

**Comment by ahv5aw5n** [comment]
> 通过wxplugin模板生成的代码中有一个pkg文件，将文件名改成package.json就正常了，可能是通过模板生成的文件名写错了。

我选择 wxplugin模板 生成的代码没有发现pkg文件
```
Taro 即将创建一个新项目!
Need help? Go and open issue: https://tls.jd.com/taro-issue-helper

? 请输入项目介绍！
? 请选择框架 React
? 是否需要使用 TypeScript ？ No
? 请选择 CSS 预处理器（Sass/Less/Stylus） Less
? 请选择模板源 Github（最新）
✔ 拉取远程模板仓库成功！
? 请选择模板 wxplugin（小程序插件模板）

✔ 创建项目: taro-wxplugin-v3
✔ 创建文件: /Users/.../taro-wxplugin-v3/.editorconfig
✔ 创建文件: /Users/.../taro-wxplugin-v3/.eslintrc
✔ 创建文件: /Users/.../taro-wxplugin-v3/.gitignore
✔ 创建文件: /Users/.../taro-wxplugin-v3/package.json
✔ 创建文件: /Users/.../taro-wxplugin-v3/project.config.json
✔ 创建文件: /Users/.../taro-wxplugin-v3/config/dev.js
✔ 创建文件: /Users/.../taro-wxplugin-v3/config/index.js
✔ 创建文件: /Users/.../taro-wxplugin-v3/config/prod.js
✔ 创建文件: /Users/.../taro-wxplugin-v3/src/app.less
✔ 创建文件: /Users/.../taro-wxplugin-v3/src/app.jsx
✔ 创建文件: /Users/.../taro-wxplugin-v3/src/pages/index/index.less
✔ 创建文件: /Users/.../taro-wxplugin-v3/src/pages/index/index.jsx
✔ 创建文件: /Users/.../taro-wxplugin-v3/src/plugin/index.js
✔ 创建文件: /Users/.../taro-wxplugin-v3/src/plugin/plugin.json
✔ 创建文件: /Users/.../taro-wxplugin-v3/src/plugin/doc/README.md
✔ 创建文件: /Users/.../taro-wxplugin-v3/src/plugin/doc/example.jpeg
✔ 创建文件: /Users/.../taro-wxplugin-v3/src/plugin/components/avatar/avatar.less
✔ 创建文件: /Users/.../taro-wxplugin-v3/src/plugin/components/avatar/avatar.jsx
✔ 创建文件: /Users/.../taro-wxplugin-v3/src/plugin/components/listItem/listItem.less
✔ 创建文件: /Users/.../taro-wxplugin-v3/src/plugin/components/listItem/listItem.jsx
✔ 创建文件: /Users/.../taro-wxplugin-v3/src/plugin/pages/list/list.less
✔ 创建文件: /Users/.../taro-wxplugin-v3/src/plugin/pages/list/list.jsx
```

**Comment by ZakaryCode** [comment]
未能在指定版本复现该问题，可以重试或者更新版本

**Comment by ahv5aw5n** [comment]
debug 发现 mini-runner/src/plugins.ts 中 `originalEntry` 是 字符串`src` ，不是一个数组。taro-service 中初始化的config，entry是正确的。

```
  /**
   * 根据 webpack entry 配置获取入口文件路径
   * @returns app 入口文件路径
   */
  getAppEntry (compiler: webpack.Compiler) {
    const originalEntry = compiler.options.entry as webpack.Entry
    compiler.options.entry = {}
    return path.resolve(this.context, originalEntry.app[0])
  }
```
pull taro-next 代码，开启sourceMap，在调试插件项目过程中，有些包还是压缩后的代码，怎么在目标项目使用taro-next的包呢？

**Comment by xiaoyuze88** [comment]
taro3中插件模板跑不起来，originalEntry打印出来是一个字符串:  './src'

**Comment by Chen-jj** [comment]
Duplicate of #6959 
Taro 3 还没支持微信小程序插件开发，尽快支持
