### ISSUE TITLE
使用了组件的页面打包失败

### ISSUE THREAD

**Issue by Twining** [NervJS/taro#765]
**问题描述**
使用组件的页面在打包成H5时可以正常显示，打包成小程序则会提示

> 错误  组件编译  组件src/pages/components/nav-bar/index.js编译失败！
TypeError: Cannot read property 'children' of undefined
    at Object.parseJSXElement (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\transformer-wx\lib\src\jsx.js:110:30)
    at RenderParser.setOutputTemplate (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\transformer-wx\lib\src\render.js:895:37)
    at new RenderParser (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\transformer-wx\lib\src\render.js:773:14)
    at Transformer.parseRender (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\transformer-wx\lib\src\class.js:469:19)
    at Transformer.compile (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\transformer-wx\lib\src\class.js:481:14)
    at new Transformer (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\transformer-wx\lib\src\class.js:91:14)
    at transform (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\transformer-wx\lib\src\index.js:378:14)
    at buildSingleComponent (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1419:29)
    at Promise.all.componentPathList.map.componentObj (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1327:60)
    at Array.map (<anonymous>)

我的组件在E:\jzb\src\pages\components\nav-bar，
我在页面中的引用是import NavBar from '../components/nav-bar'。

**复现步骤**
[复现问题的步骤]
npm run build:weapp

**期望行为**
能正常打包在微信开发工具中显示

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 v1.0.3
 - Node.js 版本 v10.8.0

**Comment by luckyadam** [comment]
请贴一下页面的完整代码
