### ISSUE TITLE
高阶组件注入 与  mobx 注入冲突？  taro1.x 就没问题。

### ISSUE THREAD

**Issue by lxiaohui** [NervJS/taro#7863]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/lxiaohui/myapp3.0.14-mobx.git](https://gitee.com/lxiaohui/myapp3.0.14-mobx.git)
**小程序基础库: 2.13.1**
**使用框架: React**

### 复现步骤
这是demo 直接运行就可以

### 期望结果
正常运行

### 实际结果
报错了

### 环境信息
```
  Taro CLI 3.0.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
```

**Comment by lxiaohui** [comment]
VM176:1 pages/index/index.js:
 TypeError: Super expression must either be null or a function
    at _inherits (vendors.js:287)
    at withShare.ts:7
    at withShare.ts:7
    at Object../node_modules/babel-loader/lib/index.js!./src/pages/index/index.tsx (index.tsx:24)
    at __webpack_require__ (bootstrap:79)
    at Module../src/pages/index/index.tsx (index.tsx?aff8:1)
    at __webpack_require__ (bootstrap:79)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at index.js:2
console.error @ VM176:1
wrapFn @ appservice?t=1603173298485:4101
require @ VM183 WAService.js:2
(anonymous) @ VM197:30
doWhenAllScriptLoaded @ appservice?t=1603173298485:4179
scriptLoaded @ appservice?t=1603173298485:4199
script.onload @ appservice?t=1603173298485:4207
load (async)
(anonymous) @ appservice?t=1603173298485:4206
(anonymous) @ appservice?t=1603173298485:4217
VM176:1 MiniProgramError
Super expression must either be null or a function
TypeError: Super expression must either be null or a function
    at _inherits (http://127.0.0.1:14312/appservice/vendors.js:287:11)
    at http://127.0.0.1:14312/appservice/pages/index/index.js:175:146
    at http://127.0.0.1:14312/appservice/pages/index/index.js:202:6
    at Object../node_modules/babel-loader/lib/index.js!./src/pages/index/index.tsx (http://127.0.0.1:14312/appservice/pages/index/index.js:45:89)
    at __webpack_require__ (http://127.0.0.1:14312/appservice/runtime.js:81:30)
    at Module../src/pages/index/index.tsx (http://127.0.0.1:14312/appservice/pages/index/index.js:137:107)
    at __webpack_require__ (http://127.0.0.1:14312/appservice/runtime.js:81:30)
    at checkDeferredModules (http://127.0.0.1:14312/appservice/runtime.js:47:23)
    at Array.webpackJsonpCallback [as push] (http://127.0.0.1:14312/appservice/runtime.js:34:19)
    at http://127.0.0.1:14312/appservice/pages/index/index.js:2:49

**Comment by lxiaohui** [comment]
官方小哥哥 @Chen-jj

**Comment by xiao252** [comment]
请问解决了吗，遇到类似的问题。

**Comment by ZoneLabyrinth** [comment]
解决了吗，Inject装饰后变成Object了吧
