### ISSUE TITLE
使用 @tarojs/cli （v2.2.15）无法成功开启 RN

### ISSUE THREAD

**Issue by NicholasNC** [NervJS/taro#7901]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
1、第一步，使用 `taro init testTaroRN ` 生成一个初始化项目，模板信息如下：

```
"templateInfo": {
    "name": "redux",
    "typescript": false,
    "css": "less"
  },
```

2、第二步，按照 [React Native 端开发流程](https://taro-docs.jd.com/taro/docs/react-native/#%E7%AE%80%E4%BB%8B)，的步骤，搭建好 iOS 的环境

3、第三步，启用 `npm run dev:rn` ，编译

第一次执行，报了以下错误：
```
(node:2709) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'yellow' of undefined
    at /Users/nicholas/.nvm/versions/node/v12.19.0/lib/node_modules/@tarojs/cli/dist/rn/helper.js:17:37
    at new Promise (<anonymous>)
    at installDep (/Users/nicholas/.nvm/versions/node/v12.19.0/lib/node_modules/@tarojs/cli/dist/rn/helper.js:15:12)
    at /Users/nicholas/.nvm/versions/node/v12.19.0/lib/node_modules/@tarojs/cli/dist/rn/helper.js:62:13
    at new Promise (<anonymous>)
    at Object.updatePkgJson (/Users/nicholas/.nvm/versions/node/v12.19.0/lib/node_modules/@tarojs/cli/dist/rn/helper.js:55:12)
    at Object.<anonymous> (/Users/nicholas/.nvm/versions/node/v12.19.0/lib/node_modules/@tarojs/cli/dist/rn/index.js:29:28)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/nicholas/.nvm/versions/node/v12.19.0/lib/node_modules/@tarojs/cli/dist/rn/index.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2709) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2709) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

关闭命令行，执行第二次 `npm run dev:rn` 才行

`npm run dev:rn` 执行成功后，出现以下界面：

![BFlzmF.png](https://s1.ax1x.com/2020/10/22/BFlzmF.png)

并且弹出了一个命令行，好像有问题，如下图:

[![BF16nU.png](https://s1.ax1x.com/2020/10/22/BF16nU.png)](https://imgchr.com/i/BF16nU)

然后有自己开一个命令行，执行 `react-native start`，出现以下界面

![BFlvOU.png](https://s1.ax1x.com/2020/10/22/BFlvOU.png)

但没法按教程所示，浏览器访问 `https://127.0.0.1:8081/` 和 `https://127.0.0.1:8081/rn_temp/index.bundle?platform=ios&dev=true`

均没有反应

### 期望结果
按教程所示，浏览器可以访问 `https://127.0.0.1:8081/` 和 `https://127.0.0.1:8081/rn_temp/index.bundle?platform=ios&dev=true`

### 实际结果
浏览器访问 `https://127.0.0.1:8081/` 和 `https://127.0.0.1:8081/rn_temp/index.bundle?platform=ios&dev=true`

都没有反应

### 环境信息
```
👽 Taro v2.2.15


  Taro CLI 2.2.15 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v12.19.0/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
    npmPackages:
      @tarojs/components: 2.2.15 => 2.2.15 
      @tarojs/components-qa: 2.2.15 => 2.2.15 
      @tarojs/components-rn: ^2.2.15 => 2.2.15 
      @tarojs/mini-runner: 2.2.15 => 2.2.15 
      @tarojs/plugin-less: 2.2.15 => 2.2.15 
      @tarojs/plugin-terser: 2.2.15 => 2.2.15 
      @tarojs/redux: 2.2.15 => 2.2.15 
      @tarojs/redux-h5: 2.2.15 => 2.2.15 
      @tarojs/rn-runner: ^2.2.10 => 2.2.10 
      @tarojs/router: 2.2.15 => 2.2.15 
      @tarojs/taro: 2.2.15 => 2.2.15 
      @tarojs/taro-alipay: 2.2.15 => 2.2.15 
      @tarojs/taro-h5: 2.2.15 => 2.2.15 
      @tarojs/taro-qq: 2.2.15 => 2.2.15 
      @tarojs/taro-quickapp: 2.2.15 => 2.2.15 
      @tarojs/taro-redux-rn: ^2.2.15 => 2.2.15 
      @tarojs/taro-rn: ^2.2.15 => 2.2.15 
      @tarojs/taro-router-rn: ^2.2.15 => 2.2.15 
      @tarojs/taro-swan: 2.2.15 => 2.2.15 
      @tarojs/taro-tt: 2.2.15 => 2.2.15 
      @tarojs/taro-weapp: 2.2.15 => 2.2.15 
      @tarojs/webpack-runner: 2.2.15 => 2.2.15 
      eslint-config-taro: 2.2.15 => 2.2.15 
      eslint-plugin-taro: 2.2.15 => 2.2.15 
      nerv-devtools: ^1.5.5 => 1.5.7 
      nervjs: ^1.5.5 => 1.5.7 
      react: 16.8.0 => 16.8.0 
      react-native: 0.59.9 => 0.59.9 
      stylelint-config-taro-rn: 2.2.15 => 2.2.15 
      stylelint-taro-rn: 2.2.15 => 2.2.15 
```

**Comment by NicholasNC** [comment]
自问自答

## 猜想

今天突发奇想，猜测会不会是因为用了 nvm 安装 node 导致其找不到 node 命令，猜想的理由：

在执行完 `npm run dev:rn` 后，自动打开一个终端（mac 自带的终端），但是终端上显示：(如问题上图片所示)

```
/Users/nicholas/Nicholas/learn/testTaroRN/node_modules/react-native/scripts/packager.sh: line 23: node: command not found
Process terminated. Press <enter> to close the window
```

居然说 `/node_modules/react-native/scripts/packager.sh: line 23: node: command not found`，所以就猜会不会跟 nvm 有关

解决方法：先把mac 自带的终端打开（上一次在执行 `npm run dev:rn` 之前是没有开终端的），然后再执行 `npm run dev:rn`

果然，经过这个操作后，`npm run dev:rn` 顺利执行，并且打开的终端也顺利出现，下图：

![](https://user-images.githubusercontent.com/9441951/59322399-85780180-8d08-11e9-9ea7-b3e4b23c077c.png)

但这还不够，在浏览器上输入 `https://127.0.0.1:8081` 和 `https://127.0.0.1:8081/rn_temp/index.bundle?platform=ios&dev=true` 还是没用，不过换成了 `http://localhost:8081/` 和 `http://localhost:8081/rn_temp/index.bundle?platform=ios&dev=true` 就可以了

## 将 [NervJS/taro-native-shell](https://github.com/NervJS/taro-native-shell) 整合到 taro 项目中
Taro 将 React Native 工程中原生的部分剥离出来，如果运行 RN，需要把 [NervJS/taro-native-shell](https://github.com/NervJS/taro-native-shell) 放在项目的跟目录下

具体步骤如下：

1. 首先在项目的根目录下将应用代码 clone 下来： `git clone https://github.com/NervJS/taro-native-shell.git` (ps：如果是 taro2.0+，要使用 0.59.9 分支)
2. `cd taro-native-shell`，使用 yarn 或者 npm install 安装依赖
3. 在 iOS 目录运行( taro-native-shell 下的 ios 目录 )：`pod install`
    - 如果没有安装 CocoaPods，可以参考官方文档：[Getting Started](https://guides.cocoapods.org/using/getting-started.html)
4. 在 taro-native-shell 的目录下执行：`react-native run-ios`

等待几分钟，就可以看到自动打开模拟器，并且加载 taro 的项目
