### ISSUE TITLE
Error: 未找到 Taro.Component 的类定义

### ISSUE THREAD

**Issue by xiaoxingchao** [NervJS/taro#793]
**问题描述**
编译时候经常出现    Error: 未找到 Taro.Component 的类定义

**Comment by luckyadam** [comment]
把编译的内容截图看下

**Comment by xiaoxingchao** [comment]
就是用你给的例子,执行npm run dev:weapp第一次编译没问题,修改下文件内容,自动编译时候报错.[图片]

win7系统 node 8.10.0

**Comment by xiaoxingchao** [comment]
修改  页面文件  src/pages/index/index
编译  页面文件  src/pages/index/index
错误  页面编译  页面F:\xiaochengxu\taro\src\pages\index\index编译失败！
Error: 未找到 Taro.Component 的类定义
    at transform (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_@tarojs_transformer-wx@1.0.5@@tarojs\transformer-wx\lib\src\index.js:365:15)
    at buildSinglePage (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1117:29)
    at FSWatcher.watcher.on.on.on (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1714:19)
    at emitTwo (events.js:126:13)
    at FSWatcher.emit (events.js:214:7)
    at FSWatcher.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_chokidar@2.0.4@chokidar\index.js:199:15)
    at FSWatcher._emit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_chokidar@2.0.4@chokidar\index.js:241:5)
    at FSWatcher.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\_chokidar@2.0.4@chokidar\lib\nodefs-handler.js:267:16)
    at FSReqWrap.oncomplete (fs.js:153:5)

**Comment by luckyadam** [comment]
src/pages/index/index
这个页面的代码贴一下~

**Comment by xiaoxingchao** [comment]
![ut zd _ q 1zsof le 6jd](https://user-images.githubusercontent.com/20487037/46987340-62b82d80-d126-11e8-9cfe-4a23dc716eb2.png)

用的是官网上的例子,在另一台电脑上就没这种问题........

**Comment by luckyadam** [comment]
代码应该没啥问题，可能是 cli 没有安装好，可以用 cnpm 重新安装下~

**Comment by BruceZhang1993** [comment]
相同的问题

`监听文件修改中...

修改  页面文件  src/pages/index/index
编译  页面文件  src/pages/index/index
错误  页面编译  页面/home/bruce/Projects/taro/demoApp/src/pages/index/index编译失败！
Error: 未找到 Taro.Component 的类定义
    at transform (/home/bruce/.npm-global/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/index.js:410:15)
    at buildSinglePage (/home/bruce/.npm-global/lib/node_modules/@tarojs/cli/src/weapp.js:1172:29)
    at FSWatcher.watcher.on.on.on (/home/bruce/.npm-global/lib/node_modules/@tarojs/cli/src/weapp.js:1810:19)
    at FSWatcher.emit (events.js:182:13)
    at FSWatcher.<anonymous> (/home/bruce/.npm-global/lib/node_modules/@tarojs/cli/node_modules/chokidar/index.js:199:15)
    at FSWatcher._emit (/home/bruce/.npm-global/lib/node_modules/@tarojs/cli/node_modules/chokidar/index.js:241:5)
    at FSWatcher.<anonymous> (/home/bruce/.npm-global/lib/node_modules/@tarojs/cli/node_modules/chokidar/lib/nodefs-handler.js:267:16)
    at FSReqCallback.oncomplete (fs.js:162:5)`

**Comment by luckyadam** [comment]
升级下 taro 试试

**Comment by BruceZhang1993** [comment]
> @BruceZhang1993 升级下 taro 试试

@luckyadam 

```
$ taro --version
👽 Taro v1.1.9

1.1.9

$ which taro    
/home/bruce/.npm-global/bin/taro
```

**Comment by luckyadam** [comment]
请把 `/home/bruce/Projects/taro/demoApp/src/pages/index/index` 这个页面代码提供下

**Comment by BruceZhang1993** [comment]
基本没改动默认模板的代码，--watch 时修改代码时会出现报错 @luckyadam 
```tsx
// index.tsx
import Taro, { Component, Config } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
import './index.less'

export default class Index extends Component {

  /**
   * 指定config的类型声明为: Taro.Config
   *
   * 由于 typescript 对于 object 类型推导只能推出 Key 的基本类型
   * 对于像 navigationBarTextStyle: 'black' 这样的推导出的类型是 string
   * 提示和声明 navigationBarTextStyle: 'black' | 'white' 类型冲突, 需要显示声明类型
   */
  config: Config = {
    navigationBarTitleText: '首页'
  }

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='index'>
        <Text>Hello Taro App!</Text>
      </View>
    )
  }
}
```

**Comment by luckyadam** [comment]
@BruceZhang1993 没有复现，可以的话把整个项目发一下

**Comment by yuhong-l** [comment]
遇到此问题加一，本来正常运行，突然出现这个错误，代码应该是没问题的，最后通过重新npm i好了。估计有bug，暂时不知如何复现。

**Comment by xiaoxingchao** [comment]
感觉跟电脑运行速度,或网速有关.....我这有时也会出现,在保存一次就好

**Comment by PWDream** [comment]
我也遇到这个问题，怎么解决呢 @luckyadam 
![image](https://user-images.githubusercontent.com/4903755/56357906-9bd57580-620f-11e9-8c57-7d0e7e49e8a8.png)
![image](https://user-images.githubusercontent.com/4903755/56357969-cc1d1400-620f-11e9-9364-ff44025a63d9.png)

**Comment by czhhgghm** [comment]
请问同样的问题最后怎么解决呢？？？

**Comment by zicjin** [comment]
我也还在遇到同样问题
