### ISSUE TITLE
Taro 2.2.15  微信小程序编译正常但开发工具打开无法运行提示报错：TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<Object>'

### ISSUE THREAD

**Issue by polichan** [NervJS/taro#7946]
### 相关平台
微信小程序

**小程序基础库: 2.12.2**
**使用框架: React**

### 复现步骤
暂无发现重现步骤

### 期望结果
微信开发者工具可以正常预览小程序

### 实际结果
``yarn dev:weapp``  编译未提示错误，但微信开发者而工具无法预览，提示如下报错：
```json
MiniProgramError
Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<Object>'
TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<Object>'
    at getRawTag (http://127.0.0.1:45203/appservice/taro.js:1720:29)
    at baseGetTag (http://127.0.0.1:45203/appservice/taro.js:1774:66)
    at isPlainObject (http://127.0.0.1:45203/appservice/taro.js:1876:33)
    at isEmptyObject (http://127.0.0.1:45203/appservice/taro.js:1893:16)
    at http://127.0.0.1:45203/appservice/taro.js:2933:13
    at Array.forEach (<anonymous>)
    at doUpdate (http://127.0.0.1:45203/appservice/taro.js:2925:26)
    at mountComponent (http://127.0.0.1:45203/appservice/taro.js:2872:3)
    at Ze.initComponent (http://127.0.0.1:45203/appservice/taro.js:2590:3)
    at Ze.weappComponentConf.methods.onLoad (http://127.0.0.1:45203/appservice/taro.js:2696:21)
```

### 环境信息
```

  Taro CLI 2.2.15 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 2.2.15 => 2.2.15 
      @tarojs/components: 2.2.15 => 2.2.15 
      @tarojs/components-qa: 2.2.15 => 2.2.15 
      @tarojs/mini-runner: 2.2.15 => 2.2.15 
      @tarojs/plugin-sass: 2.2.15 => 2.2.15 
      @tarojs/plugin-uglify: 2.2.15 => 2.2.15 
      @tarojs/redux: 2.2.15 => 2.2.15 
      @tarojs/redux-h5: 2.2.15 => 2.2.15 
      @tarojs/router: 2.2.15 => 2.2.15 
      @tarojs/taro: 2.2.15 => 2.2.15 
      @tarojs/taro-alipay: 2.2.15 => 2.2.15 
      @tarojs/taro-h5: 2.2.15 => 2.2.15 
      @tarojs/taro-qq: 2.2.15 => 2.2.15 
      @tarojs/taro-quickapp: 2.2.15 => 2.2.15 
      @tarojs/taro-swan: 2.2.15 => 2.2.15 
      @tarojs/taro-tt: 2.2.15 => 2.2.15 
      @tarojs/taro-weapp: 2.2.15 => 2.2.15 
      @tarojs/webpack-runner: 2.2.15 => 2.2.15 
      eslint-config-taro: 2.2.15 => 2.2.15 
      eslint-plugin-taro: 2.2.15 => 2.2.15 
      nerv-devtools: ^1.5.7 => 1.5.7 
      nervjs: ^1.5.7 => 1.5.7 
      stylelint-config-taro-rn: 2.2.15 => 2.2.15 
      stylelint-taro-rn: 2.2.15 => 2.2.15 
      taro-ui: ^2.3.4 => 2.3.4 

```

---
### 补充信息
该项目最初使用的是 Taro 2.2.10 版本进行开发，现迁移开发设备（之前是 Windows 系统，现在是 macOS 系统），在利用 Taro 2.2.15 之前已经重新利用 Taro 2.2.10 编译（已保证依赖跟 taro 版本一致，即已使用 taro update project 至对应版本），编译正常，但开发者工具仍然提示 ``TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<Object>' `` ，遂尝试升级版本至 Taro 2.2.15，未能解决该问题，问题还是如上。另：H5 可以正常在浏览器中进行查看。

**Comment by polichan** [comment]
另：尝试进行 ``yarn build:weapp`` 编译之后会提示：

```
VM118:1 SystemError (jsEnginScriptError)
Component is not found in path "npm/taro-ui/dist/weapp/components/button/index" (using by "pages/index/index")
Error: Component is not found in path "npm/taro-ui/dist/weapp/components/button/index" (using by "pages/index/index")
```

不知道会不会跟这个有关，关联 issues #7913 #7868

**Comment by polichan** [comment]
解决了，解决方案其实是业务代码上的问题。不是依赖的问题。

**Comment by luckyadam** [comment]
> 另：尝试进行 `yarn build:weapp` 编译之后不会报错，但用开发者工具打开则会提示：
> 
> ```
> VM118:1 SystemError (jsEnginScriptError)
> Component is not found in path "npm/taro-ui/dist/weapp/components/button/index" (using by "pages/index/index")
> Error: Component is not found in path "npm/taro-ui/dist/weapp/components/button/index" (using by "pages/index/index")
> ```
> 
> 不知道会不会跟这个有关，关联 issues #7913 #7868

这个问题请尝试下
https://github.com/NervJS/taro/issues/7913#issuecomment-723991922

**Comment by qicmsg** [comment]
> 解决了，解决方案其实是业务代码上的问题。不是依赖的问题。

能告知一下吗？我也遇到这个问题。现在找不到具体问题。

**Comment by qicmsg** [comment]
> > 解决了，解决方案其实是业务代码上的问题。不是依赖的问题。
> 
> 能告知一下吗？我也遇到这个问题。现在找不到具体问题。

已找到问题，在写模块时，要写上默认导出包名 `export default xxx;` 。(2.2.13没有问题，升级到2.2.16就出现了问题。)
