### ISSUE TITLE
引入 环信sdk 报错  Cannot read property 'loglevel' of undefined

### ISSUE THREAD

**Issue by GitHub-Haisheng** [NervJS/taro#8097]
### 相关平台
微信小程序

**小程序基础库: 2.14.0**
**使用框架: React**

### 复现步骤
现在有微信小程序 引入 环信sdk 能正常工作。
现在有多端小程需求，准备使用 taro 在引入 环信 sdk 的时候报错。
Cannot read property 'loglevel' of undefined

appservice?t=1606057136928:4085 pages/demos/imDemo/index.js:
 TypeError: Cannot read property 'loglevel' of undefined
    at e.value (wxsdk3.3.0.js:1)
    at new e (wxsdk3.3.0.js:1)
    at Object.push../src/sdk/wxsdk3.3.0.js (wxsdk3.3.0.js:1)
    at r (wxsdk3.3.0.js:1)
    at Object.push../src/sdk/wxsdk3.3.0.js (wxsdk3.3.0.js:1)
    at r (wxsdk3.3.0.js:1)
    at Object.push../src/sdk/wxsdk3.3.0.js (wxsdk3.3.0.js:1)
    at r (wxsdk3.3.0.js:1)
    at Object.push../src/sdk/wxsdk3.3.0.js (wxsdk3.3.0.js:1)
    at r (wxsdk3.3.0.js:1)
wrapFn @ appservice?t=1606057136928:4085
require @ VM200 WAService.js:2
(anonymous) @ VM216:60
doWhenAllScriptLoaded @ appservice?t=1606057136928:4193
scriptLoaded @ appservice?t=1606057136928:4213
script.onload @ appservice?t=1606057136928:4221
load (async)
(anonymous) @ appservice?t=1606057136928:4220
(anonymous) @ appservice?t=1606057136928:4231
VM200 WAService.js:2 MiniProgramError
Cannot read property 'loglevel' of undefined
TypeError: Cannot read property 'loglevel' of undefined
    at e.value (http://127.0.0.1:59572/appservice/pages/demos/imDemo/index.js:270:22514)
    at new e (http://127.0.0.1:59572/appservice/pages/demos/imDemo/index.js:270:20136)
    at Object.push../src/sdk/wxsdk3.3.0.js (http://127.0.0.1:59572/appservice/pages/demos/imDemo/index.js:270:23875)
    at r (http://127.0.0.1:59572/appservice/pages/demos/imDemo/index.js:270:253)
    at Object.push../src/sdk/wxsdk3.3.0.js (http://127.0.0.1:59572/appservice/pages/demos/imDemo/index.js:270:40209)
    at r (http://127.0.0.1:59572/appservice/pages/demos/imDemo/index.js:270:253)
    at Object.push../src/sdk/wxsdk3.3.0.js (http://127.0.0.1:59572/appservice/pages/demos/imDemo/index.js:270:64113)
    at r (http://127.0.0.1:59572/appservice/pages/demos/imDemo/index.js:270:253)
    at Object.push../src/sdk/wxsdk3.3.0.js (http://127.0.0.1:59572/appservice/pages/demos/imDemo/index.js:270:172051)
    at r (http://127.0.0.1:59572/appservice/pages/demos/imDemo/index.js:270:253)

### 期望结果
能支持第三方 sdk 运行

### 实际结果
第三方sdk 运行不起来。

### 环境信息
```
👽 Taro v3.0.17


  Taro CLI 3.0.17 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    npmPackages:
      @tarojs/components: 3.0.17 => 3.0.17 
      @tarojs/mini-runner: 3.0.17 => 3.0.17 
      @tarojs/react: 3.0.17 => 3.0.17 
      @tarojs/runtime: 3.0.17 => 3.0.17 
      @tarojs/taro: 3.0.17 => 3.0.17 
      @tarojs/webpack-runner: 3.0.17 => 3.0.17 
      babel-preset-taro: 3.0.17 => 3.0.17 
      eslint-config-taro: 3.0.17 => 3.0.17 
      react: ^16.10.0 => 16.14.0 
```

**Comment by luckyadam** [comment]
提供一个 demo 看下

**Comment by GitHub-Haisheng** [comment]
> 提供一个 demo 看下

好的,有劳了。

taro 对接环信demo: [taro-im-demo](git@github.com:GitHub-Haisheng/technology-select-taro-mini.git)  （准备切多端的时候，sdk 对接报错）
环信 对接原生小程序demo: [im-wx-demo](git@github.com:easemob/webim-weixin-xcx.git)    （能正常运行，已上线）

**Comment by freeler** [comment]
同问，该问题近期会处理吗？
