### ISSUE TITLE
build:weapp报错

### ISSUE THREAD

**Issue by xiaoai7904** [NervJS/taro#8224]
### 相关平台
微信小程序

**小程序基础库: 2.13.0**
**使用框架: React**

### 复现步骤
npm run build:weapp

### 期望结果
正常运行

### 实际结果
(node:86138) UnhandledPromiseRejectionWarning: /Users/xxx/work/taro/smallShop/node_modules/_p-limit@3.1.0@p-limit/index.js:29
                } catch {}
                        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._compile (/Users/xxx/work/taro/smallShop/node_modules/_pirates@4.0.1@pirates/lib/index.js:99:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/Users/xxx/work/taro/smallShop/node_modules/_pirates@4.0.1@pirates/lib/index.js:104:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xxx/work/taro/smallShop/node_modules/_terser-webpack-plugin@3.1.0@terser-webpack-plugin/dist/index.js:26:38)
    at Module._compile (module.js:652:30)
    at Module._compile (/Users/xxx/work/taro/smallShop/node_modules/_pirates@4.0.1@pirates/lib/index.js:99:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/Users/xxx/work/taro/smallShop/node_modules/_pirates@4.0.1@pirates/lib/index.js:104:7)

### 环境信息
```
 Taro CLI 3.0.18 environment info:
    System:
      OS: macOS High Sierra 10.13.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
      npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.18 => 3.0.18 
      @tarojs/components: 3.0.18 => 3.0.18 
      @tarojs/mini-runner: 3.0.18 => 3.0.18 
      @tarojs/react: 3.0.18 => 3.0.18 
      @tarojs/runtime: 3.0.18 => 3.0.18 
      @tarojs/taro: 3.0.18 => 3.0.18 
      @tarojs/webpack-runner: 3.0.18 => 3.0.18 
      babel-preset-taro: 3.0.18 => 3.0.18 
      eslint-config-taro: 3.0.18 => 3.0.18 
      react: ^16.10.0 => 16.14.0 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3 
```

**Comment by luckyadam** [comment]
请提供一个可以复现的 demo

**Comment by xiaoai7904** [comment]
node版本问题
https://github.com/googleapis/nodejs-storage/issues/1274
