### ISSUE TITLE
templateFn is not a function

### ISSUE THREAD

**Issue by huangruitian** [NervJS/taro#8331]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/qiniu](https://github.com/qiniu)
**小程序基础库: 2.7.0**
**使用框架: React**

### 复现步骤
编译报错

### 期望结果
不报错

### 实际结果
报错了

### 环境信息
```
  Taro CLI 3.0.8 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.0 - /usr/local/bin/node
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.8 => 3.0.8 
      @tarojs/mini-runner: ^3.0.8 => 3.0.21 
      @tarojs/router: 3.0.8 => 3.0.8 
      @tarojs/runtime: 3.0.8 => 3.0.8 
      @tarojs/taro: 3.0.8 => 3.0.8 
      @tarojs/webpack-runner: ^3.0.8 => 3.0.21 
      babel-preset-taro: 3.0.8 => 3.0.8 
      eslint-config-taro: ^3.0.8 => 3.0.21 
      eslint-plugin-taro: ^3.0.8 => 3.0.21 
      nervjs: ^1.5.7 => 1.5.7 
```

---
### 补充信息
编译报错

**Comment by huangruitian** [comment]
```js
⠸ 正在编译...templateFn is not a function


templateFn is not a function


(node:5729) UnhandledPromiseRejectionWarning: TypeError: templateFn is not a function
    at TaroMiniPlugin.generateTemplateFile (/Users/huangruitian/Desktop/mini-program-fandom-taro/node_modules/@tarojs/mini-runner/src/plugins/MiniPlugin.ts:706:20)
    at TaroMiniPlugin.<anonymous> (/Users/huangruitian/Desktop/mini-program-fandom-taro/node_modules/@tarojs/mini-runner/src/plugins/MiniPlugin.ts:649:10)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/huangruitian/Desktop/mini-program-fandom-taro/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:5729) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5729) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Chen-jj** [comment]
升级到最新版后再试试吧。

**Comment by huangruitian** [comment]
> 升级到最新版后再试试吧。

cli 升级最新版的也不行

**Comment by nanxiaobei** [comment]
我也遇到，更新到 Taro v3.0.21 没问题了

**Comment by mebtte** [comment]
3.0.22也有这个问题

**Comment by Chen-jj** [comment]
提供一下可复现 demo

**Comment by mebtte** [comment]
> 3.0.22也有这个问题

应该是taro cli和taro版本不一致导致, 我把项目的taro升级到3.0.22, 然后使用`taro update self`升级cli, 虽然提示cli升级成功, 但是依然是旧的版本, 所以把cli安装到项目里面保持版本一直就可以了

**Comment by limichange** [comment]
出现这个问题是可能是因为你的taro项目里的包和cli的版本不一致导致的，建议@tarojs/cli直接安装在项目当中，并和其他的taro包的版本一致。
