### ISSUE TITLE
Taro3.0.21版本启动失败

### ISSUE THREAD

**Issue by caoliang-java** [NervJS/taro#8362]
yarn dev:rn
yarn run v1.22.10
$ NODE_ENV='dev' npm run build:rn -- --watch

> idata@1.4.0 build:rn /Users/caoliang/Desktop/App/rwebox-idata-hcp
> NODE_ENV='dev' taro build --type rn "--watch"

👽 Taro v3.0.21

dev
(node:29014) UnhandledPromiseRejectionWarning: Error: 不存在编译平台 rn
    at Kernel.runWithPlatform (/Users/caoliang/.config/yarn/global/node_modules/@tarojs/service/dist/Kernel.js:218:19)
    at Kernel.<anonymous> (/Users/caoliang/.config/yarn/global/node_modules/@tarojs/service/dist/Kernel.js:261:36)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/caoliang/.config/yarn/global/node_modules/@tarojs/service/dist/Kernel.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:29014) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29014) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 3.49s.

**Comment by luckyadam** [comment]
https://github.com/NervJS/taro/issues/8180
