### ISSUE TITLE
项目模板报错 Error: Invalid URI "git@github.com:icepy/test_taro.git"

### ISSUE THREAD

**Issue by icepy** [NervJS/taro#8584]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/icepy/test_taro](https://github.com/icepy/test_taro)
**小程序基础库: 1.2.0**
**使用框架: React**

### 复现步骤
npx @tarojs/cli init myapp

然后选择本地模板源

### 期望结果
可以顺利的下载安装模板

### 实际结果
? 请选择模板源 本地模板源：git@github.com:icepy/test_taro.git
⠋ 正在从 git@github.com:icepy/test_taro.git 拉取远程模板.../Users/xiangwenwen/.npm/_npx/9c0d86107f20e2c5/node_modules/request/request.js:273
    return self.emit('error', new Error(message))
                              ^

Error: Invalid URI "git@github.com:icepy/test_taro.git"
    at Request.init (/Users/xiangwenwen/.npm/_npx/9c0d86107f20e2c5/node_modules/request/request.js:273:31)
    at new Request (/Users/xiangwenwen/.npm/_npx/9c0d86107f20e2c5/node_modules/request/request.js:127:8)
    at request (/Users/xiangwenwen/.npm/_npx/9c0d86107f20e2c5/node_modules/request/index.js:53:10)
    at Function.get (/Users/xiangwenwen/.npm/_npx/9c0d86107f20e2c5/node_modules/request/index.js:61:12)
    at Object.<anonymous> (/Users/xiangwenwen/.npm/_npx/9c0d86107f20e2c5/node_modules/@tarojs/cli/src/create/fetchTemplate.ts:50:10)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/xiangwenwen/.npm/_npx/9c0d86107f20e2c5/node_modules/@tarojs/cli/dist/create/fetchTemplate.js:5:58)
Emitted 'error' event on Request instance at:
    at Request.init (/Users/xiangwenwen/.npm/_npx/9c0d86107f20e2c5/node_modules/request/request.js:273:17)
    at new Request (/Users/xiangwenwen/.npm/_npx/9c0d86107f20e2c5/node_modules/request/request.js:127:8)
    [... lines matching original stack trace ...]
    at fulfilled (/Users/xiangwenwen/.npm/_npx/9c0d86107f20e2c5/node_modules/@tarojs/cli/dist/create/fetchTemplate.js:5:58)
npm ERR! code 1
npm ERR! path /Users/xiangwenwen
npm ERR! command failed
npm ERR! command sh -c taro init myapp

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xiangwenwen/.npm/_logs/2021-01-26T07_05_42_104Z-debug.log

### 环境信息
```
👽 Taro v3.0.21


  Taro CLI 3.0.21 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.5.0 - ~/.nvm/versions/node/v15.5.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v15.5.0/bin/yarn
      npm: 7.3.0 - ~/.nvm/versions/node/v15.5.0/bin/npm
```

---
### 补充信息
希望可以使用 https://docs.taro.zone/docs/template 这个功能

在~/.taro3/index.json 配置文件中已经配置了 templateSource 字段：

{"templateSource":"git@github.com:icepy/test_taro.git"}

但是报错，也试过 http 的，一样报错

**Comment by Chen-jj** [comment]
@icepy Taro 使用 [download-git-repo](https://www.npmjs.com/package/download-git-repo) 去拉取模版，可以看看他的文档对模板源链接进行配置

**Comment by icepy** [comment]
> @icepy Taro 使用 [download-git-repo](https://www.npmjs.com/package/download-git-repo) 去拉取模版，可以看看他的文档对模板源链接进行配置

无解... 我单独写了一个 node 脚本，纯粹使用 download-git-repo 按照正常的配置可以，但是应用到 taro cli 3.0.21 上就报错，错误还是上述：无效的uri

暂时放弃了，让开发者自己 clone 仓库好了
