### ISSUE TITLE
button按钮添加onGetUserInfo报错Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Young1993** [NervJS/taro#8598]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/Young1993/tarotest.git](https://github.com/Young1993/tarotest.git)
**小程序基础库: 2.14.0**
**使用框架: Vue 3**

### 复现步骤
<button
          type="primary"
          onGetUserInfo="handleUserInfo"
          openType="getUserInfo"
        >
          获取信息
        </button>

### 期望结果
{ nickName: string; avatarUrl: string; gender: 0 | 1 | 2; province: string; city: string; country: string; }

### 实际结果
VM765 WAService.js:2 MiniProgramError
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at Object.n (http://127.0.0.1:39702/appservice/vendors.js:10058:88)
    at callWithAsyncErrorHandling (http://127.0.0.1:39702/appservice/vendors.js:1949:56)
    at callWithAsyncErrorHandling (http://127.0.0.1:39702/appservice/vendors.js:1960:21)
    at callWithAsyncErrorHandling (http://127.0.0.1:39702/appservice/vendors.js:1960:21)
    at callWithAsyncErrorHandling (http://127.0.0.1:39702/appservice/vendors.js:1960:21)
    at callWithAsyncErrorHandling (http://127.0.0.1:39702/appservice/vendors.js:1960:21)
    at callWithAsyncErrorHandling (http://127.0.0.1:39702/appservice/vendors.js:1960:21)
    at callWithAsyncErrorHandling (http://127.0.0.1:39702/appservice/vendors.js:1960:21)
    at callWithAsyncErrorHandling (http://127.0.0.1:39702/appservice/vendors.js:1960:21)
    at callWithAsyncErrorHandling (http://127.0.0.1:39702/appservice/vendors.js:1960:21)

### 环境信息
```
 Taro v3.0.25


  Taro CLI 3.0.25 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.3.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.25 => 3.0.25 
      @tarojs/mini-runner: 3.0.25 => 3.0.25 
      @tarojs/runtime: 3.0.25 => 3.0.25 
      @tarojs/taro: 3.0.25 => 3.0.25 
      @tarojs/webpack-runner: 3.0.25 => 3.0.25 
      babel-preset-taro: 3.0.25 => 3.0.25 
      eslint-config-taro: 3.0.25 => 3.0.25 
```

**Comment by Chen-jj** [comment]
@Young1993 事件绑定语法错了: https://cn.vuejs.org/v2/guide/events.html，建议先撸一遍 Vue 的基本语法

```js
<button
  v-if="!hasUser"
  type="primary"
  @getUserInfo="handleUserInfo"
  openType="getUserInfo"
>
  授权公开信息 onGetUserInfo
</button>
<button
  v-else
  type="primary"
  @getPhoneNumber="handlePhone"
  openType="getPhoneNumber"
>
  授权公开信息 onGetPhoneNumber
</button>
```

**Comment by Young1993** [comment]
> @Young1993 事件绑定语法错了，建议先撸一遍 Vue 的基本语法: https://cn.vuejs.org/v2/guide/events.html
> 
> ```js
> <button
>   v-if="!hasUser"
>   type="primary"
>   @getUserInfo="handleUserInfo"
>   openType="getUserInfo"
> >
>   授权公开信息 onGetUserInfo
> </button>
> <button
>   v-else
>   type="primary"
>   @getPhoneNumber="handlePhone"
>   openType="getPhoneNumber"
> >
>   授权公开信息 onGetPhoneNumber
> </button>
> ```

抱歉抱歉，我看文档以为是要 onGetUserInfo
