### ISSUE TITLE
H5编译预览模式启动报错

### ISSUE THREAD

**Issue by cikichen** [NervJS/taro#86]
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8080
    at Server.setupListenHandle [as _listen2] (net.js:1327:14)
    at listenInCluster (net.js:1375:12)
    at doListen (net.js:1501:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at emitErrorNT (net.js:1354:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! quan@1.0.0 build:h5: `taro build --type h5 "--watch"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the quan@1.0.0 build:h5 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by cikichen** [comment]
感觉是端口冲突了

**Comment by luckyadam** [comment]
嗯嗯，端口冲突，端口可以配置
在 `config/dev.js` 里的 `h5` 配置里增加 `port` 配置，来修改端口
```javascript
module.exports = {
  env: {
    NODE_ENV: '"development"'
  },
  defineConstants: {
  },
  weapp: {},
  h5: {
    port: 3000
  }
}
```
