### ISSUE TITLE
className 设置为字符串变量时报错

### ISSUE THREAD

**Issue by nyrf** [NervJS/taro#883]
如果` <View key={k} className={`sku k.active ? 'active' : ' ' k.disabled ? 'disabled' : ' '`}>{k}</View>` 这里写 ` <View key={k} className='sku'>{k}</View>` 就没有问题，不过这里className我想设置成这样 
```
<View key={k} className={`sku`}>{k}</View>
```

不过也不行

```js
    const keysItem = Object.keys(keys).map((key) => {
      return(
        <View className='item' key={key}>
        <View className="title">{key}</View>
        <View className='skus'>
        {
          Object.keys(keys[key]).map((k) => {
            return(
              <View key={k} className={`sku k.active ? 'active' : ' ' k.disabled ? 'disabled' : ' '`}>{k}</View>
            )
          })
        }
        </View>
      </View>
      )
    })
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**
```js
VM16349:1 thirdScriptError
key is not defined; [Component] Lifetime Method Error @ components/sku/sku#attached
ReferenceError: key is not defined
    at Sku._createData (http://127.0.0.1:28360/appservice/components/sku/sku.js:191:41)
    at doUpdate (http://127.0.0.1:28360/appservice/npm/@tarojs/taro-weapp/dist/index.js:3397:22)
    at updateComponent (http://127.0.0.1:28360/appservice/npm/@tarojs/taro-weapp/dist/index.js:3382:5)
    at c.initComponent (http://127.0.0.1:28360/appservice/npm/@tarojs/taro-weapp/dist/index.js:3221:3)
    at c.attached (http://127.0.0.1:28360/appservice/npm/@tarojs/taro-weapp/dist/index.js:3270:23)
    at o.safeCallback (http://127.0.0.1:28360/appservice/__dev__/WAService.js:15:19538)
    at o.call (http://127.0.0.1:28360/appservice/__dev__/WAService.js:15:19302)
    at t (http://127.0.0.1:28360/appservice/__dev__/WAService.js:16:1770)
    at t (http://127.0.0.1:28360/appservice/__dev__/WAService.js:16:2083)
    at t (http://127.0.0.1:28360/appservice/__dev__/WAService.js:16:2025)
```

**系统信息**

 - 操作系统: osx 10.14
 - Taro 版本 v1.07
 - Node.js 版本 v10.5.0
 - 报错平台 weapp

**Comment by yuche** [comment]
<View key={k} className='sku'>{k}</View> 和  <View key={k} className={`sku`}>{k}</View> 是没有区别的。[最新的beta版本](https://github.com/NervJS/taro/commit/ecc916aa5e4c69430173f073c3bf65c6ffb2f4fd)能够识别到这样的写法，不会再给你生成匿名变量了。

` <View key={k} className={`sku k.active ? 'active' : ' ' k.disabled ? 'disabled' : ' '`}>{k}</View>` 这个写法是错误的， className 是一个字符串，不会执行表达式。建议你去看一下 [template string](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/template_strings) 的用法。
