### ISSUE TITLE
Taro + dva + redux-sage的项目中，首次编译总报错：Cannot read property 'dispatch' of null

### ISSUE THREAD

**Issue by sqy371** [NervJS/taro#894]
**问题描述**
Taro + dva + redux-sage的项目中，用`taro build --type weapp --watch`编译小程序代码，发现第一次编译总是会出现报错，把pages配置的第一个页面路径和其他路径调换位置后保存，报错消失

**复现步骤**
如上述

**期望行为**
第一次编译不报错

**报错信息**
```
thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'dispatch' of null 
 TypeError: Cannot read property 'dispatch' of null
    at connect (http://127.0.0.1:31248/appservice/npm/@tarojs/redux/dist/index.js:183:23)
    at http://127.0.0.1:31248/appservice/pages/home/index.js:41:55
    at require (http://127.0.0.1:31248/appservice/__dev__/WAService.js:23:15279)
    at <anonymous>:7:7
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:31248/appservice/appservice?t=1540054483001:2309:23)
console.error @ VM358:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1540054483001:2122
window.onerror @ VM358:1
scriptLoaded @ appservice?t=1540054483001:2309
```

**系统信息**
 - 操作系统:  MacOS High Sierra 10.13.6
 - Taro 版本:  v1.1.0-beta.4
 - Node.js 版本:  v8.10.0
 - 报错平台:  weapp

**补充信息**
发现导致两次编译结果是否报错的根本原因在于编译后的dist/app.js文件，diff如下：
![image](https://user-images.githubusercontent.com/12246321/47258419-81734700-d4cd-11e8-9d78-17a2b2fb7272.png)

试验步骤如下：
1. 第一次编译，报错
2. 修改page顺序后由watch进行第二次编译，不报错，保存编译后的dist/app.js文件，以A指代
3. 手动重新编译（即再次进行第一次编译），报错，此时产生编译后的dist/app.js文件，以B指代
4. 用A替换B，报错消失

**Comment by ZackZheng2014** [comment]
@sqy371 请问具体是什么怎么引用导致的？我也出现这个错误，没找到怎么解决。

**Comment by xingyibiao** [comment]
> @sqy371 请问具体是什么怎么引用导致的？我也出现这个错误，没找到怎么解决。

好像是模板代码里面，store导入的是个工厂，改为导出一个单列就可以了

**Comment by ruralist-siyi** [comment]
你好。请问是如何解决这个问题？我也遇到了同样的问题
