### ISSUE TITLE
Error: You gave us a visitor for the node type StaticBlock but it's not a valid type

### ISSUE THREAD

**Issue by everything8** [NervJS/taro#9067]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/everything8/myRapp.git](https://github.com/everything8/myRapp.git)
**小程序基础库: react native**
**使用框架: React**

### 复现步骤
1.运行 npx @tarojs/cli init myApp 创建项目
2.运行 yarn dev:rn 执行报错

### 期望结果
期望正常执行

### 实际结果
执行报错：
PS E:\projects\taro-proj\myRapp> yarn dev:rn
yarn run v1.22.10
$ npm run build:rn -- --watch

> myRapp@1.0.0 build:rn E:\projects\taro-proj\myRapp
> taro build --type rn "--watch"

� Taro v3.2.1

Error: You gave us a visitor for the node type StaticBlock but it's not a valid type
    at verify (C:\Users\demo\AppData\Local\Yarn\Data\global\node_modules\@babel\traverse\lib\visitors.js:112:13)
    at explode (C:\Users\demo\AppData\Local\Yarn\Data\global\node_modules\@babel\traverse\lib\visitors.js:34:3)
    at Object.merge (C:\Users\demo\AppData\Local\Yarn\Data\global\node_modules\@babel\traverse\lib\visitors.js:147:5)
    at Object.<anonymous> (C:\Users\demo\AppData\Local\Yarn\Data\global\node_modules\@babel\plugin-transform-object-super\node_modules\@babel\helper-replace-supers\lib\index.js:60:44)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module._compile (C:\Users\demo\AppData\Local\Yarn\Data\global\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.newLoader [as .js] (C:\Users\demo\AppData\Local\Yarn\Data\global\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
(node:5252) UnhandledPromiseRejectionWarning: Error: You gave us a visitor for the node type StaticBlock but it's not a valid type
    at verify (C:\Users\demo\AppData\Local\Yarn\Data\global\node_modules\@babel\traverse\lib\visitors.js:112:13)
    at explode (C:\Users\demo\AppData\Local\Yarn\Data\global\node_modules\@babel\traverse\lib\visitors.js:34:3)
    at Object.merge (C:\Users\demo\AppData\Local\Yarn\Data\global\node_modules\@babel\traverse\lib\visitors.js:147:5)
    at Object.<anonymous> (C:\Users\demo\AppData\Local\Yarn\Data\global\node_modules\@babel\plugin-transform-object-super\node_modules\@babel\helper-replace-supers\lib\index.js:60:44)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module._compile (C:\Users\demo\AppData\Local\Yarn\Data\global\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.newLoader [as .js] (C:\Users\demo\AppData\Local\Yarn\Data\global\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
(node:5252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 3.48s.

### 环境信息
```
� Taro v3.2.1


  Taro CLI 3.2.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.4 - D:\nodejs\nvm\nodejs\node.EXE
      Yarn: 1.22.10 - D:\nodejs\nvm\nodejs\yarn.CMD
      npm: 6.14.6 - D:\nodejs\nvm\nodejs\npm.CMD
```

**Comment by zhiqingchen** [comment]
https://github.com/everything8/myRapp.git
试了下可以正常运行。

尝试下手动加入以下依赖，安装后重新运行

```
"@tarojs/taro-rn": "3.2.1"
"@tarojs/rn-runner": "3.2.1"
"react-native": "^0.64.0"
```

**Comment by zhiqingchen** [comment]
如再有问题，请reopen

**Comment by jschyz** [comment]
移除一些 yarn global 其他命令；如 @vitejs/ @umijs/ 等等，就好了。估计 @babel 冲突了
