### ISSUE TITLE
无法使用bootstrap样式

### ISSUE THREAD

**Issue by ai930** [NervJS/taro#927]
------------------------

**问题描述**
无法使用bootstrap样式

**复现步骤**
```js
//引入css
//npm install bootstrap@3 -S
import 'bootstrap/dist/css/bootstrap.css'
```

**期望行为**
可以使用bootstrap的样式

**报错信息**
```js
thirdScriptError 
 sdk uncaught third Error 
 module "npm/lodash/isFunction.js" is not defined 
 Error: module "npm/lodash/isFunction.js" is not defined
    at require (http://127.0.0.1:33081/appservice/__dev__/WAService.js:23:15138)
    at http://127.0.0.1:33081/appservice/__dev__/WAService.js:23:14886
    at http://127.0.0.1:33081/appservice/npm/taro-ui/dist/weapp/components/list/item/index.js:23:20
    at require (http://127.0.0.1:33081/appservice/__dev__/WAService.js:23:15279)
    at <anonymous>:25:7
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:33081/appservice/appservice?t=1540381954536:1713:23)
console.error @ VM9061:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1540381954536:1604
window.onerror @ VM9061:1
scriptLoaded @ appservice?t=1540381954536:1713
```

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 Taro v1.0.7
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
升级到最新的 beta 版本试试

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/fb10108bcba3dd69e12dd438e93c1c55e38a35d2
