### ISSUE TITLE
3.2.8 @tarojs/mini-runner安装失败

### ISSUE THREAD

**Issue by xiayuqing** [NervJS/taro#9322]
### 相关平台
微信小程序

**小程序基础库: 2.14.1**
**使用框架: Nerv**

### 复现步骤
taro update self
taro update project
执行上述命令升级版本至3.2.8，升级版本后删除 node_modules、package-lock.json进行重新安装，无法完成 npm install，单独安装 @tarojs/mini-runner也是报一样的错误。请问该如何处理？

```
44483 verbose stack Error: fibers@5.0.0 install: `node build.js || nodejs build.js`
44483 verbose stack spawn ENOENT
44483 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
44483 verbose stack     at ChildProcess.emit (events.js:198:13)
44483 verbose stack     at maybeClose (internal/child_process.js:982:16)
44483 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
44484 verbose pkgid fibers@5.0.0
44485 verbose cwd /Users/xxx/web/ai-factory-taro
44486 verbose Darwin 20.3.0
44487 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
44488 verbose node v10.16.0
44489 verbose npm  v6.14.13
44490 error code ELIFECYCLE
44491 error syscall spawn
44492 error file sh
44493 error errno ENOENT
44494 error fibers@5.0.0 install: `node build.js || nodejs build.js`
44494 error spawn ENOENT
44495 error Failed at the fibers@5.0.0 install script.
44495 error This is probably not a problem with npm. There is likely additional logging output above.
44496 verbose exit [ 1, true ]
```

依赖

```json
"dependencies": {
		"@babel/runtime": "7.7.7",
		"@tarojs/components": "3.2.8",
		"@tarojs/runtime": "3.2.8",
		"@tarojs/taro": "3.2.8",
		"classnames": "2.2.6",
		"nervjs": "1.5.7",
		"numeral": "2.0.6",
		"prop-types": "15.7.2",
		"taro-ui": "2.3.0",
		"js-base64": "3.6.0"
	},
	"devDependencies": {
		"@babel/core": "7.8.0",
		"@tarojs/mini-runner": "3.2.8",
		"@tarojs/webpack-runner": "3.2.8",
		"@types/react": "16.0.0",
		"@types/webpack-env": "1.13.6",
		"babel-preset-taro": "3.2.8",
		"eslint": "6.8.0",
		"eslint-config-taro": "3.2.8",
		"eslint-plugin-import": "2.12.0",
		"eslint-plugin-react": "7.8.2",
		"eslint-plugin-react-hooks": "1.6.1",
		"stylelint": "9.3.0"
	}
```

### 期望结果
能够正常安装

### 实际结果
无法完成安装，fibers@5.0.0的安装报错

### 环境信息
```
👽 Taro v3.2.8


  Taro CLI 3.2.8 environment info:
    System:
      OS: macOS 11.2.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.2.8 => 3.2.8 
      @tarojs/runtime: 3.2.8 => 3.2.8 
      @tarojs/taro: 3.2.8 => 3.2.8 
      babel-preset-taro: 3.2.8 => 3.2.8 
      eslint-config-taro: 3.2.8 => 3.2.8 
      nervjs: 1.5.7 => 1.5.7 
      taro-ui: 2.3.0 => 2.3.0 
```

**Comment by Chen-jj** [comment]
3.2.9 去掉 `fiber` 依赖了，可以再试试
