### ISSUE TITLE
Taro2.2.7升级至Taro3.1.5编译失败

### ISSUE THREAD

**Issue by BadmasterY** [NervJS/taro#9552]
### 相关平台
微信小程序

**小程序基础库: 2.16.0**
**使用框架: React**

### 复现步骤
1. 遵循[从旧版本迁移到 Taro Next](https://nervjs.github.io/taro/docs/migration/)逐步由2.2.7升级至3.1.5
2. 期间升级babel至7.x版本, 添加babel.config.js文件, 文件内容从@tarojs/cli 3.1.5 初始化创建的项目中获得
3. 修改代码中的 config 至对应目录的 xx.config.ts 文件

### 期望结果
编译成功

### 实际结果
编译失败

### 环境信息
```
Taro v3.1.5


  Taro CLI 3.1.5 environment info:
    System:
      OS: macOS 11.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.13.1 - ~/.nvm/versions/node/v14.13.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.13.1/bin/npm
```

---
##### 原因分析
报错信息是 `webapck/lib/Parser.js` 内出现的, 是否为 `babel-parse-taro 3.1.5` 无法正常解析, 导致 `webpack` 无法正确建立 `AST` 树?  
尝试过使用更高版本的 `babel-parse-taro` 依旧无法正确编译。

##### 报错信息
```bash
SyntaxError: Unexpected token (1:6)
    at Parser.pp$4.raise (/Users/user/Desktop/workspace/work/enrollTools/node_modules/acorn/dist/acorn.js:2825:15)
    at Parser.pp.unexpected (/Users/user/Desktop/workspace/work/enrollTools/node_modules/acorn/dist/acorn.js:689:10)
    at Parser.pp.expect (/Users/user/Desktop/workspace/work/enrollTools/node_modules/acorn/dist/acorn.js:683:28)
    at Parser.pp$3.parseParenAndDistinguishExpression (/Users/user/Desktop/workspace/work/enrollTools/node_modules/acorn/dist/acorn.js:2311:38)
    at Parser.pp$3.parseExprAtom (/Users/user/Desktop/workspace/work/enrollTools/node_modules/acorn/dist/acorn.js:2230:43)
    at Parser.pp$3.parseExprSubscripts (/Users/user/Desktop/workspace/work/enrollTools/node_modules/acorn/dist/acorn.js:2089:21)
    at Parser.pp$3.parseMaybeUnary (/Users/user/Desktop/workspace/work/enrollTools/node_modules/acorn/dist/acorn.js:2066:19)
    at Parser.pp$3.parseExprOps (/Users/user/Desktop/workspace/work/enrollTools/node_modules/acorn/dist/acorn.js:2010:21)
    at Parser.pp$3.parseMaybeConditional (/Users/user/Desktop/workspace/work/enrollTools/node_modules/acorn/dist/acorn.js:1993:21)
    at Parser.pp$3.parseMaybeAssign (/Users/user/Desktop/workspace/work/enrollTools/node_modules/acorn/dist/acorn.js:1968:21)
    at Parser.pp$3.parseExpression (/Users/user/Desktop/workspace/work/enrollTools/node_modules/acorn/dist/acorn.js:1933:21)
    at Parser.pp$1.parseStatement (/Users/user/Desktop/workspace/work/enrollTools/node_modules/acorn/dist/acorn.js:877:47)
    at Parser.pp$1.parseTopLevel (/Users/user/Desktop/workspace/work/enrollTools/node_modules/acorn/dist/acorn.js:746:23)
    at Parser.parse (/Users/user/Desktop/workspace/work/enrollTools/node_modules/acorn/dist/acorn.js:553:17)
    at Function.parse (/Users/user/Desktop/workspace/work/enrollTools/node_modules/acorn/dist/acorn.js:576:37)
    at Function.parse (/Users/user/Desktop/workspace/work/enrollTools/node_modules/webpack/lib/Parser.js:2409:22) {
  pos: 6,
  loc: Position { line: 1, column: 6 },
  raisedAt: 7
}
```

##### 项目依赖
```json
{
  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/components": "3.1.5",
    "@tarojs/react": "3.1.5",
    "@tarojs/runtime": "3.1.5",
    "@tarojs/taro": "3.1.5",
    "moment": "^2.26.0",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "sa-sdk-miniprogram": "^1.13.30",
    "taro-code": "^2.2.0",
    "ts-md5": "^1.2.7"
  },
  "devDependencies": {
    "@babel/core": "^7.8.0",
    "@tarojs/cli": "3.1.5",
    "@tarojs/mini-runner": "3.1.5",
    "@tarojs/webpack-runner": "3.1.5",
    "@types/react": "^17.0.2",
    "@typescript-eslint/eslint-plugin": "^4.15.1",
    "@typescript-eslint/parser": "^4.15.1",
    "babel-eslint": "^8.2.3",
    "babel-preset-env": "^1.6.1",
    "babel-preset-taro": "3.1.5",
    "eslint": "^5.16.0",
    "eslint-config-taro": "3.1.5",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "md5": "^2.2.1",
    "stylelint": "9.3.0",
    "typescript": "^4.1.0"
  }
}
```

##### ts.config.json
```json
{
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "removeComments": false,
    "preserveConstEnums": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "noImplicitAny": false,
    "allowSyntheticDefaultImports": true,
    "outDir": "lib",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "strictNullChecks": true,
    "sourceMap": true,
    "baseUrl": ".",
    "rootDir": ".",
    "jsx": "preserve",
    "jsxFactory": "Taro.createElement",
    "allowJs": true,
    "resolveJsonModule": true,
    "typeRoots": [
      "node_modules/@types",
      "global.d.ts"
    ],
    "paths": {
      "@/assets/*": ["./src/assets/*"],
      "@/components/*": ["./src/components/*"],
      "@/constants/*": ["./src/constants/*"],
      "@/pages/*": ["./src/pages/*"],
      "@/services/*": ["./src/services/*"],
      "@/store/*": ["./src/store/*"],
      "@/utils/*": ["./src/utils/*"]
    }
  },
  "exclude": [
    "node_modules",
    "dist"
  ],
  "compileOnSave": false
}
```

##### 项目代码书写样例
```tsx
import Taro , { Component } from '@tarojs/taro';
import { View } from '@tarojs/components';

import './demo.scss';

// DemoProps 与 DemoState 为声明的类型定义
export default class Demo extends Component<DemoProps, DemoState>{
  defaultProps = {
    text: '',
  };

  render() {
    const { text } = this.props;
    return (<View>{text}</View>);
  }
}
```

**Comment by Chen-jj** [comment]
@BadmasterY 

这里要改一下：

```js
import Taro from '@tarojs/taro';
import { Component } from 'react';
```

另外，看报错 Webpack Parser 里用的是 `acron`，和 Babel 应该无关。只看这个报错堆栈也推测不出来什么，只能先自行逐步迁移，大概定位问题了

**Comment by BadmasterY** [comment]
@Chen-jj 
感谢回复, 编译异常问题目前已定位, 由于定义了 `defineConstants`, `webpack` 版本变化, 需要对内部字符串添加 `JSON.stringfy()`
```js
{
  HOST: JSON.stringify('host')
}
```
详情参见 [define-plugin](https://webpack.js.org/plugins/define-plugin/)
