### ISSUE TITLE
3.3.0 版本 app.js 错误:  TypeError: Cannot read property 'initNativeApi' of undefined  

### ISSUE THREAD

**Issue by xQuotes** [NervJS/taro#9808]
### 相关平台
微信小程序

### 复现仓库

**小程序基础库: 2.17.3**
**使用框架: React**

### 复现步骤
npm run dev:weapp

### 期望结果
不报错

### 实际结果
报错

### 环境信息
```
Taro CLI 3.3.0 environment info:
    System:
      OS: macOS 11.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.3.0 => 3.3.0 
      @tarojs/mini-runner: 3.3.0 => 3.3.0 
      @tarojs/react: 3.3.0 => 3.3.0 
      @tarojs/runtime: ^3.3.0 => 3.3.0 
      @tarojs/taro: 3.3.0 => 3.3.0 
      @tarojs/webpack-runner: 3.3.0 => 3.3.0 
      babel-preset-taro: 3.3.0 => 3.3.0 
      eslint-config-taro: 3.3.0 => 3.3.0 
      react: ^17.0.2 => 17.0.2 
```

---
### 补充信息. 错误代码位置
```
const { CurrentReconciler } = require('@tarojs/runtime')
const taro = require('@tarojs/api').default

if (typeof CurrentReconciler.initNativeApi === 'function') {
  CurrentReconciler.initNativeApi(taro)
}

module.exports = taro
module.exports.default = module.exports
```

**Comment by ivan-94** [comment]
yarn.lock 或 package.lock 文件可以贴一下

**Comment by Chen-jj** [comment]
删掉 lock 再重装依赖试试。

**Comment by xiehui999** [comment]
> 删掉 lock 再重装依赖试试。

e.initNativeApi 报错
MiniProgramError
Error: APP-SERVICE-SDK:lanDebug:fail rejected due to no permission currently
Error: APP-SERVICE-SDK:lanDebug:fail rejected due to no permission currently
at Object.lanDebug (WASubContext.js:2:1792881)
at at (app-service.js:8598:91931)
at Array.forEach (<anonymous>)
at R (app-service.js:8598:90799)
at e.initNativeApi


升级3.3.0 后报错， 3.3.1 也报错， 小程序分享朋友圈点开必现， 随便初始化一个demo就可以复现  @Chen-jj

**Comment by axu6705** [comment]
+1

**Comment by xiehui999** [comment]
#9899 新创建一个issues
